### ISSUE TITLE
ICE when explicit object parameter be a function parameter pack

### ISSUE THREAD

**Issue by hewillk** [llvm/llvm-project#80971]
```cpp
struct S {
  auto f(this auto self...) {  }
};

int main() {
  S{}.f(0);
}
```
https://godbolt.org/z/bP8f6hzGs

Clang will crash with the above code. This should be a legal variadic function IMO.

**Comment by Sirraide** [comment]
Looks like we have an out-of-bounds access in `Sema::CheckNonDependentConversions`.
