### ISSUE TITLE
test-release.sh ninja install does builds in Phase 3

### ISSUE THREAD

**Issue by rorth** [llvm/llvm-project#80999]
When running `test-release.sh` on Linux/sparc64 (although this happens everywhere), I noticed that in Phase3, `ninja install` actually does builds.  This is unexpected, and made way worse because it passes on neither `-j<N>` options nor `-v`, so you cannot see what actually happens.

Missing the `-j<N>` even badly broke the Linux/sparc64 build which is on a somewhat resource-constrained system.  For that reason, the build is run with `-j12` while the system has 24 cores.  When it comes to Phase3, however, a large part of the build (`flang` in particular) is run with the full parallelism, which totally overwhelms the memory resources of the system and ultimately causes the build to fail.

`flang` has always been sort of nightmare on every system because the source files are quite big and compilation way more memory intensive than every other part of LLVM.

**Comment by rorth** [comment]
FWIW, I've successfully used the following patch to move the builds back out of `ninja install`:
```
--- test-release-18.sh.dist	2024-01-24 07:36:14.000000000 +0100
+++ test-release-18.sh	2024-02-07 20:05:12.035652340 +0100
@@ -537,6 +537,11 @@ function build_llvmCore() {
         InstallTarget="$InstallTarget install-runtimes"
       fi
     fi
+    if [ "$Phase" -eq "3" ]; then
+      # Build everything at once, with the proper parallelism and verbosity,
+      # in Phase 3.
+      BuildTarget=
+    fi
 
     cd $ObjDir
     echo "# Compiling llvm $Release-$RC $Flavor"
```

**Comment by tstellar** [comment]
@rorth Can you submit this fix in a PR?
