### ISSUE TITLE
Clang fails when building LLVM for RISCV

### ISSUE THREAD

**Issue by kongy** [llvm/llvm-project#81088]
`fatal error: error in backend: Do not know how to split the result of this operator!`

Reduced reproducer attached.

[reduce.zip](https://github.com/llvm/llvm-project/files/14204289/reduce.zip)

**Comment by topperc** [comment]
Looks like #66800 is missing a check for legal type.

**Comment by topperc** [comment]
Possible fix

```
diff --git a/llvm/lib/Target/RISCV/RISCVISelLowering.cpp b/llvm/lib/Target/RISCV/RISCVISelLowering.cpp
index 27037f4d5c5c..405d99f14d8f 100644
--- a/llvm/lib/Target/RISCV/RISCVISelLowering.cpp
+++ b/llvm/lib/Target/RISCV/RISCVISelLowering.cpp
@@ -15812,7 +15812,8 @@ SDValue RISCVTargetLowering::PerformDAGCombine(SDNode *N,
           MGN->getMemOperand(), IndexType, MGN->getExtensionType());
 
     if (Index.getOpcode() == ISD::BUILD_VECTOR &&
-        MGN->getExtensionType() == ISD::NON_EXTLOAD) {
+        MGN->getExtensionType() == ISD::NON_EXTLOAD &&
+        isTypeLegal(VT)) {
       if (std::optional<VIDSequence> SimpleVID = isSimpleVIDSequence(Index);
           SimpleVID && SimpleVID->StepDenominator == 1) {
         const int64_t StepNumerator = SimpleVID->StepNumerator;
```

**Comment by lukel97** [comment]
> Possible fix
> 
> ```
> diff --git a/llvm/lib/Target/RISCV/RISCVISelLowering.cpp b/llvm/lib/Target/RISCV/RISCVISelLowering.cpp
> index 27037f4d5c5c..405d99f14d8f 100644
> --- a/llvm/lib/Target/RISCV/RISCVISelLowering.cpp
> +++ b/llvm/lib/Target/RISCV/RISCVISelLowering.cpp
> @@ -15812,7 +15812,8 @@ SDValue RISCVTargetLowering::PerformDAGCombine(SDNode *N,
>            MGN->getMemOperand(), IndexType, MGN->getExtensionType());
>  
>      if (Index.getOpcode() == ISD::BUILD_VECTOR &&
> -        MGN->getExtensionType() == ISD::NON_EXTLOAD) {
> +        MGN->getExtensionType() == ISD::NON_EXTLOAD &&
> +        isTypeLegal(VT)) {
>        if (std::optional<VIDSequence> SimpleVID = isSimpleVIDSequence(Index);
>            SimpleVID && SimpleVID->StepDenominator == 1) {
>          const int64_t StepNumerator = SimpleVID->StepNumerator;
> ```

This fixes it on my end. And the combine kicks in again once the MGATHER has been split, so we end up with 2 v16i64 vlse64s from the one v32i64 it was crashing on.

**Comment by topperc** [comment]
@lukel97 can you make a PR?
