### ISSUE TITLE
Cannot find location for unit tests of __wrap_iter

### ISSUE THREAD

**Issue by hawkinsw** [llvm/llvm-project#81091]
Hello!

I was looking through the iterator unit tests last night and could not track down any unit tests for the `__wrap_iter` iterator type. If there are none, I would be more than happy to write a first batch.

If, however, I just simply was too ignorant to find them, please let me know! 

Will

**Comment by ldionne** [comment]
I think we probably don't have tests specifically for `__wrap_iter`. A lot of the internal helpers are not tested since we test the public API instead (I do think we would often benefit from more testing of internals). Feel free to add some tests under `libcxx/test/libcxx`!
