### ISSUE TITLE
llvm/lib/ExecutionEngine/JITLink/MachO_arm64.cpp:315: Sanity check in wrong place ?

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#81119]
Static analyser cppcheck says:

llvm/lib/ExecutionEngine/JITLink/MachO_arm64.cpp:315:22: warning: Opposite inner 'if' condition leads to a dead code block. [oppositeInnerCondition]

Source code is

          if (RelItr == RelEnd)
            return make_error<JITLinkError>("Unpaired Addend reloc at " +
                                            formatv("{0:x16}", FixupAddress));
          ++RelItr;
          RI = getRelocationInfo(RelItr);

The if can never be true. Maybe better code is to put the sanity check after the increment, not before. Like

          ++RelItr;
           if (RelItr == RelEnd)
            return make_error<JITLinkError>("Unpaired Addend reloc at " +
                                            formatv("{0:x16}", FixupAddress));
          RI = getRelocationInfo(RelItr);

**Comment by lhames** [comment]
Thanks for catching this @dcb314! This should be fixed by 1389260805ec.
