### ISSUE TITLE
llvm/lib/TableGen/TGLexer.cpp:1036:10: warning: Possible dereference of an invalid iterator

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#81120]
Static analyser cppcheck says:

llvm/lib/TableGen/TGLexer.cpp:1036:10: warning: Possible dereference of an invalid iterator: CurPtr [derefInvalidIterator]

Source code is

  while (*CurPtr != '\n' && *CurPtr != '\r' && CurPtr != CurBuf.end())

Suggest move third test to first place to ensure sanity check is before use, not after.

**Comment by MaskRay** [comment]
The `CurPtr != CurBuf.end()` condition is redundant. I'll inline the function and remove the redundant check.
