### ISSUE TITLE
[clang-tidy] google-explicit-constructor check with already specified `explicit(false)`

### ISSUE THREAD

**Issue by schaumb** [llvm/llvm-project#81121]
Explicit constructor check fix is wrong when already specified `explicit(false)` on that constructor

```cpp
struct A {};

struct B {
  explicit(false) B(A) {}
};
```

The [checker](https://github.com/llvm/llvm-project/blob/main/clang-tools-extra/clang-tidy/google/ExplicitConstructorCheck.cpp) tries to fix it with adding a new `explicit` keyword which makes compilation error.

```cpp
struct A {};

struct B {
  explicit(false) explicit B(A) {}
};
```

No warning/error should exist when specifying the `explicit(false)` attribute.

**Comment by angelforest** [comment]
This bug still affects conversion operators, i.e.

```c++
struct A {};

struct B {
    explicit(false) operator A() { return A{}; }
};
```

The checker still issues the warning and applies incorrect fix.
