### ISSUE TITLE
[clang-tidy] readability-avoid-return-with-void-value: what does StrictMode do?

### ISSUE THREAD

**Issue by chrchr-github** [llvm/llvm-project#81146]
~~~c++
void g(int);
void h();
void f(bool b) {
    if (b) {
        int i = 4;
        ++i;
        return g(i);
    }
    return h();
}
~~~
With `StrictMode` set to 0, there is still a warning for `return g(i);` in the `if` block.
https://godbolt.org/z/adh4Pves7

I'm not sure what to expext after reading the documentation:
_StrictMode
The value false specifies that a direct return statement shall be excluded from the analysis if it is the only statement not contained in a block like if (cond) return g();. The default value is true._
https://clang.llvm.org/extra/clang-tidy/checks/readability/avoid-return-with-void-value.html

**Comment by chrchr-github** [comment]
@SimplyDanny since you contributed the check

**Comment by PiotrZSL** [comment]
This work only for:
```
if (x) return h();
```
not for:
```
if (x) { return h(); }
```

https://github.com/llvm/llvm-project/pull/76249#issuecomment-1868461410

**Comment by chrchr-github** [comment]
Mmmkay, I would have expected `StrictMode` to differentiate between `returns` that can be removed outright and other instances that need to be split into two statements (`h(); return;`). Why do braces make a difference?

**Comment by PiotrZSL** [comment]
Almost always you need to split this into separate return, unless it's last stmt in function. This were made that way just to exclude lot of cases where not only return but also {} would need to be added. Probably it could be done in better way, and could be improvement in next releases, but for now it were just made that way.

**Comment by chrchr-github** [comment]
Thanks, that answers my question.
