### ISSUE TITLE
[Clang] Call to lambda expressions in unevaluated context is improperly rejected by Clang

### ISSUE THREAD

**Issue by zyn0217** [llvm/llvm-project#81145]
I'm not confident that I'm summarizing the issue accurately, but here is an example of the case that I discovered while at https://github.com/llvm/llvm-project/issues/70601.
```cpp
template <class T>
struct S {
  template <class U>
  using Type = decltype([]<class V> {
    return V();
  }.template operator()<U>());
};

S<int>::Type<int> V;
```

Clang currently rejects the above, complaining that there are no viable functions, which I think is suspicious.

```txt
<source>:6:14: error: no matching member function for call to 'operator()'
    4 |   using Type = decltype([]<class V> {
      |                         ~~~~~~~~~~~~~
    5 |     return V();
      |     ~~~~~~~~~~~
    6 |   }.template operator()<U>());
      |   ~~~~~~~~~~~^~~~~~~~~~~~~
<source>:9:9: note: in instantiation of template type alias 'Type' requested here
    9 | S<int>::Type<int> V;
      |         ^
<source>:4:25: note: candidate function template not viable: no known conversion from '(lambda at <source>:4:25)' to 'const S<int>::(lambda at <source>:4:25)' for object argument
    4 |   using Type = decltype([]<class V> {
      |                         ^
1 error generated.
```

The example is also on [godbolt](https://godbolt.org/z/EzsMY73x1), and we can see that this is accepted by both MSVC and GCC.

**Comment by MagentaTreehouse** [comment]
Possibly related issue: #76674

**Comment by jcsxky** [comment]
> Possibly related issue: #76674

Not really. Root case of these two issues are different. Skip transformation causes https://github.com/llvm/llvm-project/issues/76674 and I have a patch to fix it(but i haven't merge into main since it may not an perfect fix and can't fix other related issues)

**Comment by zyn0217** [comment]
> Not really. Root case of these two issues are different. Skip transformation causes #76674 and I have a patch to fix it(but i haven't merge into main since it may not an perfect fix and can't fix other related issues)

Oh, I have submitted a PR for these: https://github.com/llvm/llvm-project/pull/82310.
