### ISSUE TITLE
flang-new OpenMP reduction compiler crash

### ISSUE THREAD

**Issue by keidavis** [llvm/llvm-project#81176]
Reproducer below

flang-new -fopenmp -c -o ompmod.o ompmod.f90

llvm-project/llvm/include/llvm/Support/Casting.h:566: decltype(auto) llvm::cast(const From&) [with To = fir::ReferenceType; From = mlir::Type]: Assertion `isa<To>(Val) && "cast<Ty>() argument of incompatible type!"' failed.

Interestingly, if the array size is made explicit (e.g. replace len with 10) it gives a sensible error instead of a crash:

llvm-project/flang/lib/Lower/OpenMP.cpp:1129: not yet implemented: Reduction of some types is not supported

```
MODULE ompmod

    USE omp_lib

    IMPLICIT NONE

    PRIVATE

CONTAINS

  SUBROUTINE ompmods(len, fa)

    INTEGER, INTENT(IN) :: len
    double precision, INTENT(OUT) :: fa(len)
    double precision, DIMENSION(:), ALLOCATABLE :: ary

!$omp parallel               &                                                                                       
!$omp   reduction(+:fa)                                                                                              

    ALLOCATE(ary(len))

!$omp barrier                                                                                                        

    DEALLOCATE(ary)

!$omp end parallel                                                                                                   

  END SUBROUTINE ompmods

END MODULE ompmod
```

**Comment by tblah** [comment]
Thanks for reporting this. I am working on array reductions. I'll let you know when it is done.

**Comment by tblah** [comment]
Thank you for reporting this. I am working on array reduction support currently. I will keep your test case in mind.

**Comment by tblah** [comment]
Sorry I forgot about this ticket.

This looks fixed to me - at least current flang main doesn't crash building the file.
