### ISSUE TITLE
[InstCombine] Failure to fold (and %x, (sext i1 %m)) -> (select %m, %x, 0) with multiple uses of %m

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#81288]
Godbolt: https://simd.godbolt.org/z/ndz15vGjW

```ll
define <2 x i64> @src(<2 x i64> %x, <2 x i64> %y, <2 x i64> %a, <2 x i64> %b) {
entry:
  %cmp.i8 = icmp sgt <2 x i64> %x, %y
  %sext.i9 = sext <2 x i1> %cmp.i8 to <2 x i64>
  %and.i7 = and <2 x i64> %sext.i9, %a
  %and.i = and <2 x i64> %sext.i9, %b
  %add.i = add <2 x i64> %and.i7, %and.i
  ret <2 x i64> %add.i
}

define <2 x i64> @tgt(<2 x i64> %x, <2 x i64> %y, <2 x i64> %a, <2 x i64> %b) {
entry:
  %0 = icmp sgt <2 x i64> %x, %y
  %1 = add <2 x i64> %b, %a
  %add.i = select <2 x i1> %0, <2 x i64> %1, <2 x i64> zeroinitializer
  ret <2 x i64> %add.i
}
```

The tgt version gives better codegen:
```asm
src:                                    # @src
        pcmpgtq %xmm1, %xmm0
        pand    %xmm0, %xmm2
        pand    %xmm3, %xmm0
        paddq   %xmm2, %xmm0
        retq
tgt:                                    # @tgt
        pcmpgtq %xmm1, %xmm0
        paddq   %xmm3, %xmm2
        pand    %xmm2, %xmm0
        retq
```

I can try and address this in DAG but middle end seems to be the better choice.

**Comment by SahilPatidar** [comment]
I would like work on this one, Please let me know if there are any specific guidelines or procedures I should follow when tackling this issue.

**Comment by RKSimon** [comment]
Go for it, I'd start with locating the instcombine fold for the one use case and see the effects of allowing multiple uses of the sext'd book value.

**Comment by SahilPatidar** [comment]
@RKSimon, @dtcxzyw 
I've been reviewing some code in the InctCombine module, focusing on folding operations. While going through it, I noticed a potential improvement opportunity:
`
Value *A, *B;
if (match(&I, m_c_And(m_OneUse(m_SExt(m_Value(A))), m_Value(B))) &&
    A->getType()->isIntOrIntVectorTy(1))
  return SelectInst::Create(A, B, Constant::getNullValue(Ty));

`
It seems that this folding operation may face issues when m_SExt has multiple uses. The current m_OneUse matcher ensures m_SExt has only one use, but multiple uses could lead to unexpected behavior.

Do you think this code snippet is where the issue lies, or should I be looking at other parts of the codebase as well? If the problem lies here, what specific cases should I consider if I want to modify this code?

I would appreciate your thoughts on this matter.

**Comment by dtcxzyw** [comment]
> @RKSimon, @dtcxzyw I've been reviewing some code in the InctCombine module, focusing on folding operations. While going through it, I noticed a potential improvement opportunity: ` Value *A, *B; if (match(&I, m_c_And(m_OneUse(m_SExt(m_Value(A))), m_Value(B))) && A->getType()->isIntOrIntVectorTy(1)) return SelectInst::Create(A, B, Constant::getNullValue(Ty));
> 
> ` It seems that this folding operation may face issues when m_SExt has multiple uses. The current m_OneUse matcher ensures m_SExt has only one use, but multiple uses could lead to unexpected behavior.
> 
> Do you think this code snippet is where the issue lies, or should I be looking at other parts of the codebase as well? If the problem lies here, what specific cases should I consider if I want to modify this code?
> 
> I would appreciate your thoughts on this matter.

Nice catch! The `m_OneUse` here is redundant since we never create more instructions than we save.

**Comment by SahilPatidar** [comment]
After implementing changes in the code, I have obtained the following output from the provided snippet:

define <2 x i64> @src(<2 x i64> %x, <2 x i64> %y, <2 x i64> %a, <2 x i64> %b) local_unnamed_addr #0 {
entry:
  %cmp.i8 = icmp sgt <2 x i64> %x, %y
  %0 = add <2 x i64> %b, %a
  %add.i = select <2 x i1> %cmp.i8, <2 x i64> %0, <2 x i64> zeroinitializer
  ret <2 x i64> %add.i
}

Could you please provide guidance on updating associated test cases to ensure alignment with these changes? I'm unsure about the process.

**Comment by dtcxzyw** [comment]
> After implementing changes in the code, I have obtained the following output from the provided snippet:
> 
> define <2 x i64> @src(<2 x i64> %x, <2 x i64> %y, <2 x i64> %a, <2 x i64> %b) local_unnamed_addr #0 { entry: %cmp.i8 = icmp sgt <2 x i64> %x, %y %0 = add <2 x i64> %b, %a %add.i = select <2 x i1> %cmp.i8, <2 x i64> %0, <2 x i64> zeroinitializer ret <2 x i64> %add.i }
> 
> Could you please provide guidance on updating associated test cases to ensure alignment with these changes? I'm unsure about the process.

You should add new tests at the end of `llvm/test/Transforms/InstCombine/and.ll`, and generate the checks with `llvm/utils/update_test_checks.py`.
Then apply your changes and regenerate the checks to demonstrate the IR diff.
An example: https://github.com/llvm/llvm-project/pull/80796/commits

**Comment by SahilPatidar** [comment]
@dtcxzyw,
Could you quickly review my commit? Is it okay to have changes in other tests? Thanks!

**Comment by dtcxzyw** [comment]
> @dtcxzyw, Could you quickly review my commit? Is it okay to have changes in other tests? Thanks!

Please open a PR for review.

**Comment by SahilPatidar** [comment]
Hello @dtcxzyw and @RKSimon,

I wanted to express my gratitude for your guidance on my first PR. It was a valuable learning experience for me. I'm eager to contribute further and would be delighted to take on any beginner-friendly tasks you might have available.

Please let me know if there are any such tasks that I could work on. I'm eager to continue learning and contributing to the LLVM Project.

Thank you once again for your support.

**Comment by dtcxzyw** [comment]
> Hello @dtcxzyw and @RKSimon,
> 
> I wanted to express my gratitude for your guidance on my first PR. It was a valuable learning experience for me. I'm eager to contribute further and would be delighted to take on any beginner-friendly tasks you might have available.
> 
> Please let me know if there are any such tasks that I could work on. I'm eager to continue learning and contributing to the LLVM Project.
> 
> Thank you once again for your support.

Welcome to LLVM!
You may be interested in https://github.com/llvm/llvm-project/issues/82241 :)
