### ISSUE TITLE
Constraint satisfaction claims to depend on itself when it shouldn't

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#81334]
**Code**

```cpp
template <class _From, class _To>
constexpr bool is_convertible_v = __is_convertible(_From, _To);
template <class...> class tuple;
template <class T0> struct tuple<T0> {
  template <class U0>
    requires __is_constructible(U0, U0)
  tuple(U0);
};
struct ConvertibleFrom;
static_assert(is_convertible_v<tuple<int>, tuple<ConvertibleFrom>>);
```

**Command line**

```
clang++ -std=c++20 file.cpp
```

**Diagnostic**

```
file.cpp:6:14: error: satisfaction of constraint '__is_constructible(U0, U0)' depends on itself
    6 |     requires __is_constructible(U0, U0)
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~
file.cpp:6:14: note: while substituting template arguments into constraint expression here
    6 |     requires __is_constructible(U0, U0)
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~
file.cpp:6:14: note: while checking constraint satisfaction for template 'tuple<int>' required here
    6 |     requires __is_constructible(U0, U0)
      |              ^~~~~~~~~~~~~~~~~~
file.cpp:6:14: note: while substituting deduced template arguments into function template 'tuple' [with U0 = tuple<int>]
file.cpp:6:14: note: while substituting template arguments into constraint expression here
    6 |     requires __is_constructible(U0, U0)
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~
file.cpp:6:14: note: while checking constraint satisfaction for template 'tuple<int>' required here
    6 |     requires __is_constructible(U0, U0)
      |              ^~~~~~~~~~~~~~~~~~
file.cpp:6:14: note: in instantiation of function template specialization 'tuple<int>::tuple<tuple<int>>' requested here
file.cpp:6:14: note: while substituting template arguments into constraint expression here
    6 |     requires __is_constructible(U0, U0)
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~
file.cpp:2:62: note: while checking constraint satisfaction for template 'tuple<ConvertibleFrom>' required here
    2 | constexpr bool is_convertible_v = __is_convertible(_From, _To);
      |                                                              ^
file.cpp:2:62: note: in instantiation of function template specialization 'tuple<ConvertibleFrom>::tuple<tuple<int>>' requested here
file.cpp:10:15: note: in instantiation of variable template specialization 'is_convertible_v<tuple<int>, tuple<ConvertibleFrom>>' requested here
   10 | static_assert(is_convertible_v<tuple<int>, tuple<ConvertibleFrom>>);
      |               ^
```

**Discussion**

While I suspect that this is a bug in the constraint satisfaction, I'm not 100% certain. It might also be a diagnostic communication issue, because I don't see how checking `__is_constructible(U0, U0)` can end up as `__is_constructible(tuple<int>, tuple<int>)` in this case.

Given that the code here is a reduction of #81333's code, this may be the underlying bug.

**Comment by zyn0217** [comment]
I remembered I had seen a similar one: https://github.com/llvm/llvm-project/issues/62096

**Comment by cor3ntin** [comment]
this reduces to

```cpp
template <typename...>  
struct tuple {
  template <class U0>
    requires __is_constructible(U0, U0)
  tuple(U0);
};
tuple t{tuple<int> {0}};
```

I don't know how GCC manages to compile that.
This is recursively checking the tuple constructor.
Are we missing a terminal condition somewhere? But what would it be? @erichkeane

**Comment by erichkeane** [comment]
> this reduces to
> 
> ```c++
> template <typename...>  
> struct tuple {
>   template <class U0>
>     requires __is_constructible(U0, U0)
>   tuple(U0);
> };
> tuple t{tuple<int> {0}};
> ```
> 
> I don't know how GCC manages to compile that. This is recursively checking the tuple constructor. Are we missing a terminal condition somewhere? But what would it be? @erichkeane

Hmm... I implemented the 'depends on' part, and this certainly seems to depend on itself, so I'm not sure it is an incorrect diagnostic?  The only thing I can think of is that perhaps the builtin isn't 'checking' constraints on GCC?  Else I don't see how this is not recursively defined.

**Comment by cjdb** [comment]
Hmm, this is closer to the code that I'm actually working with, and I don't see why it should be an error.
```cpp
template <typename...>  
struct tuple {
  tuple(tuple const&);
  tuple(tuple&&);

  template <class U0>
    requires __is_constructible(U0, U0)
  tuple(U0);
};

tuple t{tuple<int> {0}};
```

**Comment by erichkeane** [comment]
Hmm... in that case, I wonder if GCC is deciding that one of the copy/move ctors is a 'better match' (as it is not a template) so not bothering to check the validity of the template match (since this is a `tuple<tuple<int>>` as deduced AFAICT).  I wouldn't be surprised if we are being too aggressive there, or perhaps the recursion error isn't being treated as a  'deduction failure' correctly?  

I don't recall, I did that feature so long ago I'm not sure how it ended up going, but I thought it was treated as a constraint failure.

**Comment by cjdb** [comment]
Oh, that would explain why an explicit `tuple<int>{tuple<int>{0}}` wasn't causing an error :)

If it's being deduced as `tuple<tuple<int>>`, then I'm still confused as to why this is recursively dependent. AFAICT `U0` is `tuple<int>`, and so `__is_constructible(U0, U0)` should be `__is_constructible(tuple<int>, tuple<int>)`. Where's the self-dependency there?

**Comment by erichkeane** [comment]
It seems that neither of the other two are an exact match as far as I can tell.  Interestingly, if I change it to requires `__is_constructible(const U0&, const U0&)` (https://godbolt.org/z/3Ed4aaTGv), we compile fine, which confirms for me that we don't consider those two constructors as sufficient.  I wonder if our `__is_constructible` isn't adding qualifiers in a way that GCC is.

**Comment by zygoloid** [comment]
GCC has a (strictly speaking, non-conforming) optimization where it doesn't look at all candidates in overload resolution if it can determine the outcome early. That's what's allowing it to accept this code.

**Comment by erichkeane** [comment]
> GCC has a (strictly speaking, non-conforming) optimization where it doesn't look at all candidates in overload resolution if it can determine the outcome early. That's what's allowing it to accept this code.

Ah! That makes sense.  I considered it might be doing something like that above, but not to that detail.  Thanks for the clarification/chiming in!

**Comment by shafik** [comment]
@cjdb I would urge a gcc bug report based on the feedback from @zygoloid even if they decide to leave the optimization in place at least it will be a documented choice.

**Comment by cjdb** [comment]
@zygoloid does that mean my `tuple` example is broken, or is there still work to do on Clang's end?
