### ISSUE TITLE
llvm/lib/IR/Instruction.cpp:522: bool llvm::Instruction::hasAllowReassoc() const: Assertion `isa<FPMathOperator>(this) && "getting fast-math flag on invalid op"' failed.

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#81351]
The attached code seems to have broken since yesterday. 

Git hashes are
95b14da678f4670283240ef4cf60f3a39bed97b4
and
c08b90c50bcac9f3f563c79491c8dbcbe7c3b574

[common-9d0806.c.gz](https://github.com/llvm/llvm-project/files/14228686/common-9d0806.c.gz)
[common-9d0806.sh.gz](https://github.com/llvm/llvm-project/files/14228687/common-9d0806.sh.gz)

**Comment by dcb314** [comment]
I haven't figured out how to add the crash label.

**Comment by dtcxzyw** [comment]
Sorry, I cannot reproduce this problem with the trunk version of clang (b17348c3b541d7fc7ec441c98db75c18d8959910).

**Comment by dcb314** [comment]
Agreed. I tried bf571059f3bcf50bf8d3b39dc6aadeb14ede14bf and the
problem seems to have gone away.
