### ISSUE TITLE
[libc++] GCC 13 and newer support -nostdlib++

### ISSUE THREAD

**Issue by poyaoc97** [llvm/llvm-project#81357]
Support for `-nostdlib++` was added for GCC 13.
We can rephrase this paragraph to reflect that:
https://github.com/llvm/llvm-project/blob/33c6b77d2a18862fb5b16160ef9d600382e93f19/libcxx/docs/UsingLibcxx.rst?plain=1#L107-L118

**Comment by ldionne** [comment]
This issue doesn't apply anymore since we've removed GCC-specific instructions for using libc++ from the docs.
