### ISSUE TITLE
[clang-format] Inconsistent formatting of template parameter with ternary

### ISSUE THREAD

**Issue by Disservin** [llvm/llvm-project#81385]
The following code gets formatted inconsistently.
`➜  ~ cat main.cpp`
```cpp
template <int num> void foo() {}

void bar() { return foo<true ? 1 : 2>(); }

int main() {
  bar();

  foo<true ? 1 : 2>();

  return 0;
}  
```
`➜  ~ clang-format-18 main.cpp`
```cpp
template <int num> void foo() {}

void bar() { return foo < true ? 1 : 2 > (); }

int main() {
  bar();

  foo<true ? 1 : 2>();

  return 0;
} 
```

The foo function call inside `bar()` is formatted differently than the one inside the `main` function.

Mainly weird spaces are added to the template parameter

**Comment by peregrineshahin** [comment]
Quite unfortunate that `SpacesInAngles: Never` does not work on this case...
