### ISSUE TITLE
[clang-format] Faulty RemoveParentheses: MultipleParentheses/ReturnStatement

### ISSUE THREAD

**Issue by prj-** [llvm/llvm-project#81399]
```console
$ cat no_return.c 
#define foo(...) bar((__VA_ARGS__))
$ clang-format --version
clang-format version 17.0.6
$ clang-format -style='{RemoveParentheses: ReturnStatement}' no_return.c 
#define foo(...) bar(__VA_ARGS__)
$ clang-format-18 -style='{RemoveParentheses: ReturnStatement}' no_return.c 
#define foo(...) bar(__VA_ARGS__)
$ clang-format-19 -style='{RemoveParentheses: ReturnStatement}' no_return.c
#define foo(...) bar(__VA_ARGS__)
```

**Comment by prj-** [comment]
My bad, I just realized that `ReturnStatement` applies on top of `MultipleParentheses`. I would like to just format the `return` statements, because this generates wrong code otherwise. Or would it be possible to fix `MultipleParentheses` in the first place?
```console
$ cat foo.c
cat foo.c 
#define PetscDefined_arg_1                                    shift,
#define PetscDefined_arg_                                     shift,
#define PetscDefined__take_second_expanded(ignored, val, ...) val
#define PetscDefined__take_second_expand(args)                PetscDefined__take_second_expanded args
#define PetscDefined__take_second(...)                        PetscDefined__take_second_expand((__VA_ARGS__))
#define PetscDefined__(arg1_or_junk)                          PetscDefined__take_second(arg1_or_junk 1, 0, at_)
#define PetscDefined_(value)                                  PetscDefined__(PetscConcat_(PetscDefined_arg_, value))
#define PetscDefined(def)                                     PetscDefined_(PetscConcat(PETSC_, def))

#if PetscDefined(FOO)

#endif
$ clang -c foo.c 2>/dev/null; echo $?
0
$ clang-format -style='{RemoveParentheses: MultipleParentheses}' foo.c > bar.c
$ clang -c bar.c 2>/dev/null; echo $?
1
```

**Comment by owenca** [comment]
IMO `MultipleParentheses` does what it's supposed to do in your case as there's no way to tell that the extra pair of parentheses enclosing `__VA_ARGS__` is required just by looking at the definition of `PetscDefined__take_second`. (There is a big warning in the [documentation](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#removeparentheses) and you must opt in.) Nevertheless, you can turn on [`SkipMacroDefinitionBody`](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#skipmacrodefinitionbody) or opt out of `RemoveParentheses`.

**Comment by prj-** [comment]
Yes, I’m aware of the warning. If you don’t think think there is anything to be done on your side, feel free to close the issue.

**Comment by owenca** [comment]
I'll disable removing parentheses in macro definitions.
