### ISSUE TITLE
Missing diagnostic for uninitialized local variable

### ISSUE THREAD

**Issue by JonPsson1** [llvm/llvm-project#81405]
This (reduced csmith) program should always print '1':

```
int printf(const char *, ...);
long a, e;
short b;
int d;
int main() {
  int f[2];
  for (b = 0; b <= 3; b++)
    ;
  int *g = &f[1];
  d = *g;
  e = d == 0 ? e : a / d;
  printf("%d\n", 1);
}
```
Even though f is uninitialized, the address of f[1] is taken, which means it will not be 'register', and not automatically disqualify the whole program as undefined, IIUC. 'd' holds the value of f[1], which is unspecified, but however checked against 0 before dividing. 'e' will always be 0 regardless of 'd', since both 'a' and 'e' are 0.

The result is however that the whole program is optimized away and the call to printf is never made.

I see:

```
*** IR Dump After EarlyCSEPass on main ***
...
  br i1 undef, label %cond.true, label %cond.false

cond.true:                                        ; preds = %for.end
  %1 = load i64, ptr @e, align 8, !tbaa !12
  br label %cond.end

cond.false:                                       ; preds = %for.end
  %2 = load i64, ptr @a, align 8, !tbaa !12
  br label %cond.end

cond.end:                                         ; preds = %cond.false, %cond.true
  %cond = phi i64 [ %1, %cond.true ], [ poison, %cond.false ]
  store i64 %cond, ptr @e, align 8, !tbaa !12
  %call = call signext i32 (ptr, ...) @printf(ptr noundef @.str, i32 noundef signext 1)
  ret i32 0
}
```

It is true that the branch is undefined in a way at this point, but regardless of which branch target is chosen, the result is the same and printf will be called. I wonder if it is really correct to optimize away the printf call in this case...?

@uweigand @efriedma-quic

**Comment by JonPsson1** [comment]
This actually gets optimized away also with unsigned:

```
int printf(const char *, ...);
unsigned long a, e;
unsigned short b;
unsigned int d;
int main() {
  unsigned int f[2];
  for (b = 0; b <= 3; b++)
    ;
  unsigned int *g = &f[1];
  d = *g;
  e = d == 0 ? e : a / d;
  printf("%d\n", 1);
}
```

=> `clang -O3 -march=z16 -o - -S -c -emit-llvm`

```

define dso_local noundef signext i32 @main() local_unnamed_addr #0 {
entry:
  unreachable
}
```

**Comment by JonPsson1** [comment]
@uweigand

**Comment by uweigand** [comment]
Looks like this is always undefined behavior in C, no matter whether `register` is used and what type the variable has.  The C standard says:
>The behavior is undefined in the following circumstances:
>[...]
>The value of an object with automatic storage duration is used while it is indeterminate (6.2.4, 6.7.9, 6.8).

**Comment by dwblaikie** [comment]
Yep. This is UB. https://godbolt.org/z/Eqf3KaG6z

**Comment by dwblaikie** [comment]
Chris Lattner wrote about this stuff a while back: https://blog.llvm.org/2011/05/what-every-c-programmer-should-know.html

**Comment by JonPsson1** [comment]
Thanks.

Ok, so it's actually correct then. I would have hoped for a diagnostic message, but it seems for some reason that empty loop confuses even the static analyzer:

```
cat test.c
int fun() {
  unsigned int f;
  return f;
}

clang -O0 test.c -Wall --analyze -emit-llvm -o /dev/null
test.c:3:3: warning: Undefined or garbage value returned to caller [core.uninitialized.UndefReturn]
    3 |   return f;
      |   ^~~~~~~~
1 warning generated.

cat test.c
int fun() {
  unsigned int f;
  for (int b = 0; b <= 3; b++)
    ;
  return f;
}
/home/ijonpan/llvm-project/install/bin/clang -O0 test.c -Wall --analyze -emit-llvm -o /dev/null
(no warnings)
```
Maybe this could be improved? @haoNoQ @danix800

**Comment by JonPsson1** [comment]
Thanks for clarifying this!
