### ISSUE TITLE
[Inliner] Assertion "context instruction should be in the same function"' failed.

### ISSUE THREAD

**Issue by JonPsson1** [llvm/llvm-project#81406]
[tc_inliner.tar.gz](https://github.com/llvm/llvm-project/files/14231984/tc_inliner.tar.gz)

opt -mtriple=s390x-unknown-linux -mcpu=z13 tc_inliner.ll -o /dev/null -O3

InstructionSimplify.cpp:6969:  Assertion "context instruction should be in the same function"' failed.

#18 0x000002aa073f818c llvm::simplifyInstruction
#23 0x000002aa0668a5ca llvm::InlinerPass::run

@aeubanks

**Comment by aeubanks** [comment]
cannot reproduce at trunk
