### ISSUE TITLE
Noreturn tailcall doesn't use jmp

### ISSUE THREAD

**Issue by gooncreeper** [llvm/llvm-project#81425]
C example
```C
_Noreturn void a(void);

void call(void) {
	a();
}
```

Generated
```ASM
call:                                   # @call
        push    rax
        call    a@PLT
```

Expected
```ASM
call:                                   # @call
        jmp     a@PLT                           # TAILCALL
```

**Comment by pinskia** [comment]
Dup of https://github.com/llvm/llvm-project/issues/76633

**Comment by gooncreeper** [comment]
> Dup of #76633

Andrew, I can't believe you memorized both the gcc bugzilla and llvm issue list.

**Comment by pinskia** [comment]
> > Dup of #76633
> 
> Andrew, I can't believe you memorized both the gcc bugzilla and llvm issue list.

Well this whole noreturn business is something which I found and filed a long time ago (21 years) so ...
