### ISSUE TITLE
[FMV] incorrect codegen when there is no TU-local caller

### ISSUE THREAD

**Issue by jroelofs** [llvm/llvm-project#81494]
https://clang.godbolt.org/z/heoTnxqz5

Compare:
```
__attribute__((target_version("dotprod+lse")))
int foo(void) { return 1; }

__attribute__((target_version("default")))
int foo(void) { return 0; }

#ifdef HAS_CALLER
int caller(void) { return foo(); }
#endif
```

```
--rtlib=compiler-rt -O2 -DHAS_CALLER=1
```
vs
```
--rtlib=compiler-rt -O2
```

While GCC's version has self-consistent and correct behavior, IMO it would be better to always emit the weak ifunc+resolver along with the definition of the `default` version so you can forward-declare the not-attributed version of the function and call these from any other TU.

**Comment by jroelofs** [comment]
cc @ilinpv @labrinea

**Comment by labrinea** [comment]
> IMO it would be better to always emit the weak ifunc+resolver along with the definition of the default version so you can forward-declare the not-attributed version of the function and call these from any other TU.

@jroelofs can you clarify this? If let's say we have a TU where a target version definition resides and has a local caller:
```
__attribute__((target_version("lse")))
int foo() { return 2; }

int bar() { return foo(); }
```
Are you saying we would rather NOT generate a resolver in that TU, but rather have one in the TU where the default definition resides?

**Comment by jroelofs** [comment]
We still could in that case, so long as the ifunc and resolver are still linkonce_odr. Maybe the right behavior is to emit it for both of these cases:
* Whenever there is a use in the TU.
* When the TU has a definition of the default version.

**Comment by labrinea** [comment]
Okay that is exactly what #84405 does, but let me discuss it with my colleagues to make sure we are on the same page.
