### ISSUE TITLE
interrupt handler useless cld

### ISSUE THREAD

**Issue by gooncreeper** [llvm/llvm-project#81543]
Example code:
```C
__attribute__((interrupt))
void isr(void*_) {
    return;
}
```
Generated ASM:
``` ASM
isr:                                    # @isr
        cld
        iretq
```
Ideally, and as generated by gcc
```ASM
isr:
        iretq
```

Clearing the direction flag should only be emitted if
1. We are using string operations
2. We are calling another function

IRETQ will revert the state of RFLAGS

**Comment by AtariDreams** [comment]
This is fixed as of https://github.com/llvm/llvm-project/commit/0a54b36d5e6d941e25c60520a7317d75355aeae5
