### ISSUE TITLE
odd behavior in std::map with an allocator with fancy pointers

### ISSUE THREAD

**Issue by ilazaric** [llvm/llvm-project#81554]
https://godbolt.org/z/xj63dcsGc
The point of the example is that `std::map` converts a raw pointer to a fancy pointer, when the raw pointer did not come from the allocator (it came from the stack)
This seems odd to me, a fancy pointer for a specific allocator is intended for memory related to that allocator (nullptr included)
The C++ standard, in the Cpp17Allocator requirement, specifies that `pointer_to(r)` has to work, but for specific references `r`, not all
Quoting:
* p denotes a value of type XX::pointer obtained by calling a1.allocate, where a1 == a
* r denotes a value of type T& obtained by the expression *p
* -only mention of pointer_to- pointer_traits<XX::pointer>::pointer_to(r) -- same as p

Current libc++ implementation of std::map then implies that fancy pointers HAVE to also be able to contain unrelated addresses, which restricts certain (in my opinion reasonable) usecases, for example offset pointers for <4GB fixed memory, containing a 32bit offset

**Comment by frederick-vs-ja** [comment]
See [Scenario B in P0773R0](https://wg21.link/p0773r0#B) and [LWG2261](https://cplusplus.github.io/LWG/issue2261).

It seems to me that your point implies that self-referential implementations of bidirectional node containers (called "sentinel-node containers" in P0773R0) are not properly allowed.

**Comment by ilazaric** [comment]
Not exactly, but kinda?
Assuming an allocator with sufficiently odd fancy pointers, and that you need to talk about pointers to nodes, including the sentinel node, you have two choices:
* internally store raw pointers, you can then put sentinel nodes wherever you want, heap, stack, static storage, ...
* internally store fancy pointers, you HAVE to get the storage for the sentinel node with the provided allocator

With the LWG you linked this implies the 2nd option IMO

**Comment by frederick-vs-ja** [comment]
[LWG4065](https://cplusplus.github.io/LWG/issue4065) opened.

The current proposed resolution may be not correct enough, but I believe the direction will be requiring fancy pointers to be able to point to everywhere and thus no implementation will need to change (which is ABI-breaking).

**Comment by ilazaric** [comment]
I agree changes are ABI-breaking, but this might not be a big deal.
* in case of raw-pointer allocator pointers, you can keep doing the same thing, and this is most of current allocators
* in case of fancy-pointer allocator pointers, I suspect they are extremely rarely, if ever, used with node-based STL containers, on account of this issue and https://gcc.gnu.org/bugzilla/show_bug.cgi?id=57272
