### ISSUE TITLE
libc++ formatter concept depends on itself

### ISSUE THREAD

**Issue by kelbon** [llvm/llvm-project#81590]
It is fixable with returning -> decltype(ctx.out()), but something went wrong, other libraries and compilers do not produce such errors.

https://godbolt.org/z/v1b13Mhb3

Localy (msvc library, clang17) error is worse (there are no consteval functions)
<details>
  <summary>error localy</summary>
In file included from E:/dev/projects/BC/src/sema.cpp:8:
In file included from E:/dev/projects/BC/include\utility/print.h:3:
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include\format:649:42: error: call to immediate function 'std::formatter<bc::unresolved_type>::format<std::basic_format_context<std::back_insert_iterator<std::_Fmt_buffer<char>>, char>>' is not a constant expression
  649 |                   _Format_ctx.advance_to(_Formatter.format(
  
  </details>

**Comment by mordante** [comment]
Thanks for the report, I just created a fix.

**Comment by frederick-vs-ja** [comment]
FYI, [LWG4061](https://cplusplus.github.io/LWG/issue4061) makes the example code ill-formed - `auto& ctx` should be written instead.
