### ISSUE TITLE
Add bit width length modifier to printf

### ISSUE THREAD

**Issue by michaelrj-google** [llvm/llvm-project#81685]
Specified in C23 on page 349 of this PDF: https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3096.pdf

C23 adds a new length modifier to printf: w_N_ and wf_N_ which allow the user to specify an exact bit width for an integer conversion. To support this, LLVM-libc needs to add support to the printf parser and converter, as well as the internal data types. Below is a (hopefully complete) list of tasks that will add this support. Feel free to reach out if you need help, you can find me as michaelrj on discord, or you can just leave a comment on this bug.

### Code:

In [core_structs.h](https://github.com/llvm/llvm-project/blob/main/libc/src/stdio/printf_core/core_structs.h):

- [x] add `w` and `wf` to the `LengthModifier` enum
- [x] add a member to `FormatSection` to hold the bit width (`size_t` would be an appropriate type)
- [ ] add both of these to the `operator==`.

In [parser.h](https://github.com/llvm/llvm-project/blob/main/libc/src/stdio/printf_core/parser.h)

- [ ] add `w` and `wf` to the `parse_length_modifier` function. This may also involve changing it to return a struct that contains a `LengthModifier` and a number.
- [ ] add the new length modifiers to the switch statement in `get_next_section`
- [ ] add the new length modifiers to the switch statement in `get_type_desc`

In [converter_utils.h](https://github.com/llvm/llvm-project/blob/main/libc/src/stdio/printf_core/converter_utils.h)

- [ ] add `w` and `wf` to `apply_length_modifier` (if you've already defined a struct that is a LengthModifier and a number, this would probably be another good place to use it).
- [ ] remember that the number of bits doesn't have to be a power of two, and can be any number (though you can assume it's small enough to fit in an `intmax_t`)

In [write_int_converter.h](https://github.com/llvm/llvm-project/blob/main/libc/src/stdio/printf_core/write_int_converter.h)

- [ ] add `w` and `wf` to the switch statement in `convert_write_int`

### Testing:

In [sprintf_test.cpp](https://github.com/llvm/llvm-project/blob/main/libc/test/src/stdio/sprintf_test.cpp)

- [ ] add tests for the length modifiers for the format specifiers that support them. This can be a new test, or added to the existing integer type tests.

In [PrintfMatcher.cpp](https://github.com/llvm/llvm-project/blob/main/libc/test/UnitTest/PrintfMatcher.cpp)

- [ ] Add support for printing the new length modifiers (feel free to ask for help with this, it can be fiddly)

In [parser_test.cpp](https://github.com/llvm/llvm-project/blob/main/libc/test/src/stdio/printf_core/parser_test.cpp)

- [ ] add a test case for each of the new length modifiers

**Comment by omprakaash** [comment]
Hey I am new to LLVM, and was wondering if I could take up this issue.

**Comment by EugeneZelenko** [comment]
@omprakaash: Just create pull request and mention it on this page.

**Comment by SahilPatidar** [comment]
@omprakaash,
are you working on this?

**Comment by omprakaash** [comment]
Yep. I am. Should be done pretty soon.
