### ISSUE TITLE
"ld: Undefined symbols" with `Clang/LLVM 15.0.0` and `ifort 2021.7.0.20220726`

### ISSUE THREAD

**Issue by zaikunzhang** [llvm/llvm-project#81695]
Dear LLVM maintainers,

My project at 

https://github.com/libprima/prima 

fails to build with `Clang/LLVM 15.0.0` and `ifort 2021.7.0.20220726`, the error being "ld: Undefined symbols `___for_ieee_signaling_ge_k4_` ..."

See https://github.com/libprima/prima/actions/runs/7894696232/job/21545822585

Note, however, that the following run was successful:

https://github.com/libprima/prima/actions/runs/7894650578/job/21545696890

Checking the runner images (See "Set up job" section of the log), I found the following. 

Failure (for https://github.com/libprima/prima/actions/runs/7894696232/job/21545822585):
```
  Image: macos-13
  Version: 20240204.1
  Included Software: https://github.com/actions/runner-images/blob/macos-13/20240204.1/images/macos/macos-13-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-13%2F20240204.1
```

Success (for https://github.com/libprima/prima/actions/runs/7894650578/job/21545696890): 
```
  Image: macos-13
  Version: 20240114.1
  Included Software: https://github.com/actions/runner-images/blob/macos-13/20240114.1/images/macos/macos-13-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-13%2F20240114.1
```

We can see that the two runs used different versions of the image. In particular, following the "Included Software" link, I find that the failing run used `Clang/LLVM 15.0.0`, while the successful one used `Clang/LLVM 14.0.3`.  I am not sure whether this is the reason for the failure (doesn't `clang` provide `ld` on macOS-13?).

Maybe related:
1. `gfortran` works fine (maybe due to the `ld` it uses?).
2. `ld` also complains that "d: warning: no platform load command found in '/opt/intel/oneapi/compiler/2022.2.0/mac/bin/intel64/../../compiler/lib/libirc.a[165](intel_avx_rep_memset.o)', assuming: macOS".

Thanks for taking a look.

Best regards,
Zaikun

**Comment by EugeneZelenko** [comment]
Could you please try 18 or `main` branch?

**Comment by zaikunzhang** [comment]
Thank you @EugeneZelenko for the comment. Is this a known issue for 15? Since the error occurs on the [GitHub Actions macos-13 image](https://github.com/actions/runner-images/blob/macos-13/20240204.1/images/macos/macos-13-Readme.md), I cannot change the version of llvm easily.

**Comment by zaikunzhang** [comment]
Tunnel you @asl . What about the following:


https://github.com/opt2ai/prima/actions/runs/7897105795/job/21552133271#step:12:1

The error comes from clang. 


I didn't post this one because it involves one more player, i.e., MATLAB.

**Comment by asl** [comment]
> Thank you @asl . What about the following:
> 
> https://github.com/opt2ai/prima/actions/runs/7897105795/job/21552133271#step:12:1
> 
> The error comes from clang:
> 
> > clang: error: linker command failed with exit code 1 (use -v to see invocation)
The errors are again come from unresolved fortran symbols:
```
ld: Undefined symbols:
    ___powr4i8, referenced from:
        _string_mod_mp_real2str_scalar_ in string.o
        _string_mod_mp_real2str_scalar_ in string.o
        _string_mod_mp_real2str_scalar_ in string.o
        _string_mod_mp_real2str_scalar_ in string.o
        _string_mod_mp_real2str_scalar_ in string.o
```

Maybe ifort is calling linker improperly / using some deprecated functionality.

**Comment by zaikunzhang** [comment]
Thank you @asl . 

Looking at the names of the undefined symbols, I guess there is a name-mangling problem. For example, `___power4i8` has three leading underscores, which seem to be excessively many.

**Comment by zaikunzhang** [comment]
The problem has been fixed: 

https://github.com/libprima/prima/commit/ac3f58d11f0f713c63cf449de99891e434de2689

It is true that nothing is wrong with Clang or LLVM. Thank you.
