### ISSUE TITLE
llvm/lib/Target/AMDGPU/SIISelLowering.cpp: 2 * suspicious if statements

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#81766]
Static analyser cppcheck says

1.

llvm/lib/Target/AMDGPU/SIISelLowering.cpp:14576:46: style: Same expression on both sides of '||'. [duplicateExpression]

Source code is 

    // v2i16 (scalar_to_vector i16:x) -> v2i16 (bitcast (any_extend i16:x))
    if (VT == MVT::v2i16 || VT == MVT::v2f16 || VT == MVT::v2f16) {

2.

llvm/lib/Target/AMDGPU/SIISelLowering.cpp:6308:65: style: Same expression on both sides of '||'. [duplicateExpression]

Source code is

  if (VT == MVT::v4f16 || VT == MVT::v8f16 || VT == MVT::v16f16 ||
      VT == MVT::v16f16)

**Comment by arsenm** [comment]
Second one should be v2bf16

**Comment by nickleus27** [comment]
can this be assigned to me?
