### ISSUE TITLE
Clang pre-defined macros for C23 binary format?

### ISSUE THREAD

**Issue by SchrodingerZhu** [llvm/llvm-project#81896]
Is there any plan to add  pre-defined macros for binary format (`b/B`) similar to `__UINT8_FMTx__`?

`Glibc` has added `PRIbN` and `PRIBN`: https://github.com/bminor/glibc/blob/bbd248ac0d75efdef8fe61ea69b1fb25fb95b6e7/stdlib/inttypes.h#L168.

Having `__UINT8_FMTb__` or `__UINT8_FMTB__` will help `libc` to define `PRIbN` and `PRIBN` as in https://github.com/llvm/llvm-project/blob/e82659fff2f07b5ea1d94e0d8bcb9c540d6bede1/libc/include/llvm-libc-macros/inttypes-macros.h#L167

**Comment by shafik** [comment]
CC @AaronBallman @cor3ntin

**Comment by AaronBallman** [comment]
We defer to the host system's `inttypes.h`: https://github.com/llvm/llvm-project/blob/4d273b948ef064230091e41cf81f4c1b91d5beb4/clang/lib/Headers/inttypes.h#L21 so it's not something I think we were planning to support directly.

**Comment by AaronBallman** [comment]
Ah, I see what you're saying, thank you! Yeah, I think that's a reasonable request.
