### ISSUE TITLE
Warning for coroutine lambdas that have a closure

### ISSUE THREAD

**Issue by KayEss** [llvm/llvm-project#81963]
I'd like to propose a new warning that is issued for dangerous/invalid uses of closures together with coroutine lambdas. Because of the way that that coroutines work in C++ the lifetime of the closure and the lifetime of the coroutine are not coupled -- the closure will be destructed the first time that the coroutine is suspended making any access into the closure after that point UB. Many (most?) coroutine libraries will always suspend at the initial suspension point meaning that use of the closure will always be UB.

Anything that would normally be put in the closure needs to be passed in as an argument to the lambda to be safe for use after suspension.

If a coroutine lambda is used in a class's member function which accesses other members, currently the compiler will suggest to add `this` to the closure, when the correct solution is generally to pass it as a parameter.

I've been using coroutines with clang ever since they first landed in trunk and have made this mistake many times. ASAN does not generally catch this problem and debugging it can be difficult due to the UB. It's a very easy mistake to make and I expect many more will come across this foot-gun as more people start to use coroutines.

**Comment by usx95** [comment]
This already exists in clang to some extent through `[[clang::coro_lifetimebound]]` ([doc](https://clang.llvm.org/docs/AttributeReference.html#coro-lifetimebound)). [godbolt example](https://godbolt.org/z/Y7W75ejT6).

>  the closure will be destructed the first time that the coroutine is suspended making any access into the closure after that point UB
This is not true. Closure is part of the lambda object, and this object should live as long as the coroutine execution. In cases where coro lambda is defined and called inline, the lambda object is only temporary and dies after the full expression.
```cpp
int a = 1;

auto coro = [a]() -> co_task<int> { co_return a; }(); // unsafe. lambda obj dies.

auto safe = [a]() -> co_task<int> { co_return a; };
co_await safe(); // fine.

```
Also, I would be surprised if ASAN did not catch such an issue. 

`coro_lifetimebound` tries to addresses the problem of reference parameters of coroutines in general.
Lambda captures fits naturally into this as "lambda object" is lifetimebound argument to the underlying lambda `operator()`.

Related:
https://discourse.llvm.org/t/rfc-lifetime-bound-check-for-parameters-of-coroutines/74253

**Comment by ChuanqiXu9** [comment]
Besides the coro_lifetimebound attribute, there is also an existing check in clang-tidy for this:  `cppcoreguidelines-avoid-capturing-lambda-coroutines`. So I'd like to close the issue. Feel free to require to reopen this.

**Comment by KayEss** [comment]
I've been trying to make use of these attributes in my coro library, but the problem is the virality of `coro_wrapper`. This has to be attached to any higher order function that might return a coro return type, including `std::function::operator()` and `std::__invoke`, and these are not marked (and there's no way for me to mark them). This breaks all higher order functions that are used to manipulate coroutines. I assume this would be even worse for lambdas as their synthesised `operator()` also won't have the attribute.

In practice this breaks so much code that I have to leave the attributes off. If the compiler can produce an error saying that the `coro_wrapper` attribute is required, why can't it just assume that the attribute is there?

**Comment by KayEss** [comment]
I've been trying to make use of these attributes in my coro library, but the problem is the virality of `coro_wrapper`. This has to be attached to any higher order function that might return a coro return type, including `std::function::operator()` and `std::__invoke`, and these are not marked (and there's no way for me to mark them). This breaks all higher order functions that are used to manipulate coroutines. I assume this would be even worse for lambdas as their synthesised `operator()` also won't have the attribute.

In practice this breaks so much code that I have to leave the attributes off. If the compiler can produce an error saying that the `coro_wrapper` attribute is required, why can't it just assume that the attribute is there?
