### ISSUE TITLE
Is there a memory leak in locale.cpp?

### ISSUE THREAD

**Issue by gavinchang1380** [llvm/llvm-project#82]
I am locating a memory leak problem about Android NDK shared library. When I dlopen a shared library and dlclose it, there will be an 8 bytes memory leak. And when I dlopen and dlclose it again, there will be another 8 bytes memory leak.

And I find the leak is in the libc++.so, in locale.cpp file.

In locale.cpp:
locale_t __cloc() {
  // In theory this could create a race condition. In practice
  // the race condition is non-fatal since it will just create
  // a little resource leak. Better approach would be appreciated.
  static locale_t result = newlocale(LC_ALL_MASK, "C", 0);
  return result;
}

And the os will malloc 8 bytes without free.

Is it a memory leak bug?

**Comment by mclow** [comment]
The appropriate place to report LLVM bugs is at https://bugs.llvm.org.

That being said, yes, that's a memory leak. As the comment says, a "Better approach would be appreciated"

**Comment by gavinchang1380** [comment]
Thank you. 

The llvm bug report web site need account and self-registration is disabled. 
The comment commit time is 2011.  And now is 2019.

**Comment by echristo** [comment]
You can send mail to the admin as it says to file a bug.

**Comment by gavinchang1380** [comment]
I have a account and file a bug on it.
