### ISSUE TITLE
Duplicate output of "-r" argument when invoking the linker with Clang

### ISSUE THREAD

**Issue by gbreynoo** [llvm/llvm-project#82010]
When requesting `-r` output multiple Clang drivers will output `-r` twice in the constructed commandline for the linker invocation. The cause looks to be that they explicitly add `options::OPT_r` within their `::Linker::ConstructJob()` function. The argument also has the option flag `LinkerInput` in `Options.td` so it is also added when `AddLinkerInputs()` is called. Only `-r` looks to be duplicated like this so there is no difference in linker behavior. 

Below is a list of drivers that I have seen the issue, I've not checked for more:
- darwin
- dragonfly
- freebsd
- openbsd
- ps4 and ps5

**Comment by brad0** [comment]
Looking at the Drivers there are a few more.
