### ISSUE TITLE
[AMDGPU][AsmParser] 32-bit integer can't be used as PK2_BF16 operand

### ISSUE THREAD

**Issue by shiltian** [llvm/llvm-project#82038]
The assembler doesn't recognize cases such as `v_dot2_bf16_bf16 v2, s0, 0x3f803f80, v2` where `0x3f803f80` stands for `<bfloat 1.0, bloat 1.0>`.

**Comment by rampitec** [comment]
https://github.com/llvm/llvm-project/pull/82423
