### ISSUE TITLE
[clang] implement __builtin_popcountg

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#82058]
GCC recently added this builtin <https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html#index-_005f_005fbuiltin_005fpopcountg> which makes implementing C23's `stdc_count_ones` (and `stdc_count_zeros`) way way simpler.  In particular, because it's type generic, it makes it easier to support not only the existing standard types pre-C23, but the extended 128b+ types (`__int128`) and C23 addition `BitInt` types.

This was alluded to by @pinskia in https://github.com/llvm/llvm-project/issues/79630#issuecomment-1912561197.

**Comment by RKSimon** [comment]
Related - we could do with __builtin_elementwise_popcnt (and ctz/clz) as well

**Comment by overmighty** [comment]
I am interested in implementing this.
