### ISSUE TITLE
LlVm 17.0.6 compile error in MathExtras.h from VS 17.8.6 x64

### ISSUE THREAD

**Issue by Bob64375** [llvm/llvm-project#82053]
In MathExtras.h 

`inline uint64_t alignToPowerOf2(uint64_t Value, uint64_t Align) {
  assert(Align != 0 && (Align & (Align - 1)) == 0 &&
         "Align must be a power of 2");
  return (Value + Align - 1) & -Align;`

Visual Studio x64 gives the error:

llvm-project-17.0.6.src\llvm\include\llvm\Support\MathExtras.h(385,32): error C4146: unary minus operator applied to unsigned type, result still unsigned.

Is the intent here `~` instead of `-`? What is expected here when unary minus is applied to unsigned 64 bits?

**Comment by RKSimon** [comment]
Code was OK, but the warning was avoided in #68978 / 3654b93d57db060377b4858ff0bac6a5836d097c - but its unlikely this will be cherry picked back to 17.X
