### ISSUE TITLE
[Flang] Incorrect diagnose of procedure pointer withno proc-interface pointer assign to a function

### ISSUE THREAD

**Issue by DanielCChen** [llvm/llvm-project#82078]
Consider the following code
```
Program main
  interface
    integer function foo()
    end
  end interface
  procedure(), pointer :: p1
  integer :: res
  p1 => foo
  res = p1()
end
```

Flang currently issues an error as
```
./t.f:8:3: error: Function pointer 'p1' associated with incompatible function designator 'foo': function results have distinct types: REAL(4) vs INTEGER(4)
    p1 => foo
    ^^^^^^^^^
./t.f:6:27: Declaration of 'p1'
    procedure(), pointer :: p1
                            ^^
 ```
 
 The standard [F2018: 15.4.3.6]
 "
If proc-interface does not appear, the procedure declaration statement does not specify whether the declared procedure entities are subroutines or functions.
"

Such a procedure pointer should be able to point to a function or subroutine that doesn't require explicit interface.

**Comment by klausler** [comment]
> Such a procedure pointer should be able to point to a function or subroutine that doesn't require explicit interface.

And it is being allowed to do so.  But as it is called as a function, it needs to have a result type, and as no explicit result type was declared, it is implicitly typed (by the default implicit type rule in effect) as REAL.
