### ISSUE TITLE
Investigate backdeployment tests.

### ISSUE THREAD

**Issue by mordante** [llvm/llvm-project#82107]
```suggestion
// XFAIL: using-built-library-before-llvm-19
```

_Originally posted by @ldionne in https://github.com/llvm/llvm-project/pull/76467#discussion_r1488334399_

Applying this suggestion failed for the "Apple system" [CI](https://buildkite.com/llvm-project/libcxx-ci/builds/33635#018da3e0-d01f-4ba4-a04f-60bb5daa4679). Based on the CI configuration this does not seem like a back-deployment target. Maybe there is something off in the backdeployment detection.

**Comment by ldionne** [comment]
The problem is that `stdlib=apple-libc++ && target={{.+}}-apple-macosx{{.+}}` is not an accurate way to check for this:

```
Feature(
        name="using-built-library-before-llvm-18",
        when=lambda cfg: BooleanExpression.evaluate(
            # For now, no released version of macOS contains LLVM 18
            # TODO(ldionne) Please provide the correct value.
            "using-built-library-before-llvm-17 || stdlib=apple-libc++ && target={{.+}}-apple-macosx{{.+}}",
            cfg.available_features,
        ),
    ),

    Feature(
        name="using-built-library-before-llvm-19",
        when=lambda cfg: BooleanExpression.evaluate(
            # For now, no released version of macOS contains LLVM 19
            # TODO(ldionne) Please provide the correct value.
            "using-built-library-before-llvm-18 || stdlib=apple-libc++ && target={{.+}}-apple-macosx{{.+}}",
            cfg.available_features,
        ),
    ),
```
    
For example when we build the `apple-system` configuration on `main`, we do have `stdlib=apple-libc++` but we have all the LLVM 19 content as well, since we're building from trunk. I have to think about how to handle that properly.
