### ISSUE TITLE
AddressSanitizer doesn't catch `std::vector` OOB access with `std::views::take`

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#82127]
The following is caught by AddressSanitizer:
```cpp
auto const v = std::vector<int>{0, 1, 2};
std::println("{}", std::ranges::fold_left(v.begin(), v.end() + 1, 0, std::plus{})); // asan crash here
```

Changing to `std::views::take(v.size() + 1)` seems to mask this error:
```cpp
auto const v = std::vector<int>{0, 1, 2};
std::println("{}", std::ranges::fold_left(v | std::views::take(v.size() + 1), 0, std::plus{})); // prints 3
```

**Repro:** https://godbolt.org/z/5P4sdzhb1

We should identify why (hopefully only some) range adaptors are hiding the overflow access so that they're consistent with the underlying range's bounds checking, and so that ranges are more safe to use.

**Comment by philnik777** [comment]
`views::take` is defined to be the minimum length of `v` or the number you give it, so this doesn't read out of bounds. This is perfectly defined behaviour. You have to use `views::counted` (which is much more cumbersome to use) to get the UB case: https://godbolt.org/z/ac34rEa1x.

**Comment by cjdb** [comment]
Right, I mixed this up with `take_exactly`. Thanks!
