### ISSUE TITLE
llvm-prof crash.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#8214]
|  |  |
| --- | --- |
| Bugzilla Link | [7842](https://llvm.org/bz7842) |
| Version | trunk |
| OS | Linux |
| Attachments | [clang -c cache.c -o cache.bc -O3 -emit-llvm](https://user-images.githubusercontent.com/60944935/143741821-6a81c4dd-9031-4b3b-9704-ee2fa674e465.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

hi,

i've noticed the utils/profile.pl crash during some tests.
testcase and logs attached.

$ ~/src/llvm/utils/profile.pl cache.bc       
size  =         64 res =         15 time =     160000 cps
size  =        128 res =         31 time =     160000 cps
size  =        256 res =         63 time =     170000 cps
size  =        512 res =        127 time =     160000 cps
size  =       1024 res =        255 time =     160000 cps
size  =       2048 res =        511 time =     160000 cps
size  =       4096 res =       1023 time =     160000 cps
size  =       8192 res =       2047 time =     150000 cps
size  =      16384 res =       4095 time =     160000 cps
size  =      32768 res =       8191 time =     150000 cps
size  =      65536 res =      16383 time =     170000 cps
size  =     131072 res =      32767 time =     160000 cps
size  =     262144 res =      65535 time =     170000 cps
size  =     524288 res =     131071 time =     170000 cps
size  =    1048576 res =     262143 time =     170000 cps
size  =    2097152 res =     524287 time =     190000 cps
size  =    4194304 res =    1048575 time =     490000 cps
size  =    8388608 res =    2097151 time =     660000 cps
size  =   16777216 res =    4194303 time =     740000 cps
size  =   33554432 res =    8388607 time =     780000 cps
size  =   67108864 res =   16777215 time =     840000 cps
size  =  134217728 res =   33554431 time =     960000 cps
size  =  268435456 res =   67108863 time =    1270000 cps
size  =  536870912 res =  134217727 time =    1810000 cps
time = 10 ms
===-------------------------------------------------------------------------===
LLVM profiling output for execution:
  cache.bc 

===-------------------------------------------------------------------------===
Function execution frequencies:

 ##   Frequency
  1.    24/25 ram_test
  2.     1/25 main

===-------------------------------------------------------------------------===
Top 20 most frequently executed basic blocks:

 ##      %%     Frequency
  1. 52.7964% 268435440/5.08436e+08     ram_test() - for.body
  2. 47.2036% 240000000/5.08436e+08     ram_test() - for.body24
  3. 4.72036e-06%    24/5.08436e+08     ram_test() - entry
  4. 4.72036e-06%    24/5.08436e+08     ram_test() - for.end123
  5. 4.72036e-06%    24/5.08436e+08     main() - for.body
  6. 1.96682e-07%     1/5.08436e+08     main() - bb.nph
  7. 1.96682e-07%     1/5.08436e+08     main() - for.end
While deleting: i8* %
Use still stuck around after Def is destroyed:  %call137 = call i32 (i8*, ...)* @&#8203;printf(i8* getelementptr inbounds (0  llvm-prof       0x00000000005d583f
1  llvm-prof       0x00000000005d7113
2  libpthread.so.0 0x00007f021756d580
3  llvm-prof       0x0000000000448d98
4  llvm-prof       0x0000000000467efe
5  llvm-prof       0x0000000000464967
6  llvm-prof       0x00000000004657a4
7  llvm-prof       0x0000000000463d23
8  llvm-prof       0x000000000054e974
9  llvm-prof       0x00000000004822c4
10 llvm-prof       0x00000000004f8f88
11 llvm-prof       0x00000000004f0b00
12 llvm-prof       0x00000000004ed2a1
13 llvm-prof       0x00000000004ee09e
14 llvm-prof       0x000000000059dc3e
15 llvm-prof       0x000000000059dca5
16 llvm-prof       0x00000000004087d7 main + 423
17 libc.so.6       0x00007f021686ed3d __libc_start_main + 253
18 llvm-prof       0x0000000000408359
Stack dump:
0.      Program arguments: llvm-prof cache.bc

**Comment by JOE1994** [comment]
`llvm/tools/llvm-prof` &`llvm/utils/profile.pl` were removed way back
between `llvmorg-3.3.0` & `llvmorg-3.4.0`.

Seems unnecessary to keep this issue open.
