### ISSUE TITLE
Clang rejects valid program involving user defined literal 

### ISSUE THREAD

**Issue by ranaanoop** [llvm/llvm-project#82167]
The following valid(afaik) program is rejected by clang but accepted by gcc and msvc.

```
#include <array>

template<std::size_t N>
struct Literal
{
    std::array<char, N> arr;
    constexpr Literal(char const(&pp)[N]): arr(""){} 
};
 
template<Literal> 
constexpr auto operator""_S()
{
    return 4;
}
int main() {
    auto i = "test"_S;   
    auto j =  "ch"_S;       
}
```
Clang says:
```
<source>:7:48: error: initializer-string for char array is too long, array size is 3 but initializer has size 5 (including the null terminating character)
    7 |     constexpr Literal(char const(&pp)[N]): arr(""){}
      |    
      <source>:17:15: note: in instantiation of member function 'Literal<3>::Literal' requested here
   17 |     auto j =  "ch"_S;
```

Another thing to note that if we write `auto i = "test"_S;   auto j =  "chjjgjgjt"_S;` then clang starts [accepting](https://godbolt.org/z/qGPjhYeKe).

Similarly clang also [accepts](https://godbolt.org/z/Kcz3rco33) `auto i = "test"_S;   auto j =  "chjt"_S;`

**Comment by tbaederr** [comment]
Using an assertion build: https://godbolt.org/z/E655srqGj 

We run into an assertion in `Expr::ClassifyImpl`:
```
clang++: /root/llvm-project/clang/lib/AST/ExprClassification.cpp:57: Cl clang::Expr::ClassifyImpl(clang::ASTContext&, clang::SourceLocation*) const: Assertion `isLValue()' failed.
```

**Comment by cor3ntin** [comment]
the operator is not necessary to trigger the bug https://godbolt.org/z/PPGGjrzz5

**Comment by Fedr** [comment]
This issue was initially found and reported here: https://stackoverflow.com/q/78015884/7325599

**Comment by zyn0217** [comment]
Without the header:
```cpp
template <typename Tp, unsigned Nm> struct array {
  Tp elems[Nm];
};

template <unsigned N> struct Literal {
  array<char, N> arr;
  constexpr Literal(const char (&pp)[N]) : arr("") {}
};

template <Literal> struct S {};

int main() {
  auto i = S<"abc">{};
  auto j = S<"ab">{};
}
```

removing either the `i` or `j` makes the crash disappear. https://godbolt.org/z/3EYTMx7zo

**Comment by shafik** [comment]
Maybe related to: https://github.com/llvm/llvm-project/issues/69874

@cor3ntin wdyt?
