### ISSUE TITLE
Inconsistent results when using --int-range-optimizations

### ISSUE THREAD

**Issue by wangyongj1a** [llvm/llvm-project#82168]
I have the following MLIR program:
test.mlir:
```
module {
  func.func @func1() {
    %false = arith.constant false
    %c2060639849_i64 = arith.constant 2060639849 : i64

    %c1_i64 = arith.constant 1 : i64
    %c0_i64 = arith.constant 0 : i64

    %36 = scf.if %false -> (i64) {  //the result should be 2060639849
      scf.yield %c1_i64 : i64
    } else {
      scf.yield %c2060639849_i64 : i64
    }
    %37 = arith.divsi %c1_i64, %36 : i64  //the result should be 0

    %41 = arith.addi %c2060639849_i64, %37 : i64  //the result should be 2060639849

    %70 = arith.xori %41, %c2060639849_i64 : i64  //the result should be 0

    %88 = arith.cmpi eq, %70, %c0_i64 : i64  //the result should be true

    %89 = scf.if %88 -> (i64) {  //the result should be 3
      %c3_i64 = arith.constant 3 : i64
      scf.yield %c3_i64 : i64
    } else {
      scf.yield %70 : i64
    }
    %94 = arith.divsi %c1_i64, %89 : i64  //the result should be 0
    vector.print %94 : i64
    return
  }
}
```
However, when I ran different pass sequences on the program, I got inconsistent results of ```0``` and ```Floating point exception```. I tested the sequences respectively, and I found that the inconsistency was caused in the last scf.if operation, which reached the false branch when ```--int-range-optimizations``` pass was specified, and reached the true branch when ```--int-range-optimizations``` pass was not specified.
I guess there might be a problem in the usage of pass the ```--int-range-optimizations```, when I ran ```mlir-opt --convert-scf-to-cf --convert-cf-to-llvm --int-range-optimizations test.mlir``` on the program, I got the following result:
```
module {
  func.func @func1() {
    %c3_i64 = arith.constant 3 : i64
    %false = arith.constant false
    %c2060639849_i64 = arith.constant 2060639849 : i64
    %c1_i64 = arith.constant 1 : i64
    llvm.cond_br %false, ^bb1(%c1_i64 : i64), ^bb1(%c2060639849_i64 : i64)
  ^bb1(%0: i64):  // 2 preds: ^bb0, ^bb0
    llvm.br ^bb2(%0 : i64)
  ^bb2(%1: i64):  // pred: ^bb1
    llvm.br ^bb3
  ^bb3:  // pred: ^bb2
    %2 = arith.divsi %c1_i64, %1 : i64
    %3 = arith.addi %2, %c2060639849_i64 : i64
    %4 = arith.xori %3, %c2060639849_i64 : i64
    llvm.cond_br %false, ^bb4(%c3_i64 : i64), ^bb4(%4 : i64)
  ^bb4(%5: i64):  // 2 preds: ^bb3, ^bb3
    llvm.br ^bb5(%5 : i64)
  ^bb5(%6: i64):  // pred: ^bb4
    llvm.br ^bb6
  ^bb6:  // pred: ^bb5
    %7 = arith.divsi %c1_i64, %6 : i64
    vector.print %7 : i64
    return
  }
}
```
I've tried to analyze the result manually, and I guess the operation ```llvm.cond_br %false, ^bb4(%c3_i64 : i64), ^bb4(%4 : i64)``` in the result seems to be wrong. The passes seem to turn the operation ```%88 = arith.cmpi eq, %70, %c0_i64 : i64``` into a constant ```false``` value, but in my analysis, the result of this operation is expected to be ```true```.  I'm not sure if there is any bug in my program or some other problems that caused this result.
My git version is 1a8c6130f60fe517fb722ab4309997ce7b638234.

**Comment by wangyongj1a** [comment]
I made a small change where I cast the result of scf.if to f32 type, and made the function return the casted value to satisfy mlir-cpu-runner.
test.mlir:
```
module {
  func.func @func1() -> f32 {
    %false = arith.constant false
    %c2060639849_i64 = arith.constant 2060639849 : i64

    %c1_i64 = arith.constant 1 : i64
    %c0_i64 = arith.constant 0 : i64

    %36 = scf.if %false -> (i64) {  //the result should be 2060639849
      scf.yield %c1_i64 : i64
    } else {
      scf.yield %c2060639849_i64 : i64
    }
    %37 = arith.divsi %c1_i64, %36 : i64  //the result should be 0

    %41 = arith.addi %c2060639849_i64, %37 : i64  //the result should be 2060639849

    %70 = arith.xori %41, %c2060639849_i64 : i64  //the result should be 0

    %88 = arith.cmpi eq, %70, %c0_i64 : i64  //the result should be true

    %89 = scf.if %88 -> (i64) {  //the result should be 3
      %c3_i64 = arith.constant 3 : i64
      scf.yield %c3_i64 : i64
    } else {
      scf.yield %70 : i64
    }
    vector.print %89 : i64
    %1 = arith.sitofp %89 : i64 to f32
    return %1 : f32
  }
}
```
When I ran ```/data/tmp/v1029/llvm-project/build/bin/mlir-opt --convert-scf-to-cf --convert-cf-to-llvm --convert-arith-to-llvm --convert-func-to-llvm --convert-vector-to-llvm test.mlir | /data/tmp/v1029/llvm-project/build/bin/mlir-cpu-runner -e func1 --shared-libs=/data/tmp/v1029/llvm-project/build/lib/libmlir_runner_utils.so,/data/tmp/v1029/llvm-project/build/lib/libmlir_c_runner_utils.so``` on the program, I got the result of:
```
3
3.000000e+00
```
However, when I ran ```/data/tmp/v1029/llvm-project/build/bin/mlir-opt --convert-scf-to-cf --convert-cf-to-llvm --int-range-optimizations --convert-arith-to-llvm --convert-func-to-llvm --convert-vector-to-llvm test.mlir | /data/tmp/v1029/llvm-project/build/bin/mlir-cpu-runner -e func1 --shared-libs=/data/tmp/v1029/llvm-project/build/lib/libmlir_runner_utils.so,/data/tmp/v1029/llvm-project/build/lib/libmlir_c_runner_utils.so```  on the program, I got the result of:
```
0
0.000000e+00
```
This problem seems to still exist.  I'm not sure if there is any bug in my program or if the wrong usage of the above passes caused these results.
My git version is e19a5fc6d306a81d181a9597a8b25c444c08d722.

**Comment by wangyongj1a** [comment]
I tried to reproduce this issue on history commit versions, and l found these inconsistent results can be reproduced on the commit of pass ```-int-range-optimizations``` that was first added([ 1a867bf ](https://github.com/llvm/llvm-project/commit/1a867bf1c7ccd4fe38ca59346f4b6268643940bb)). Hi @Hardcode84, sorry to disturb but l was wondering if you would mind taking a look at this problem?

**Comment by krzysz00** [comment]
As a side note, `mlir-cpu-runner` lets you specify the return type of main()

**Comment by Hardcode84** [comment]
@wangyongj1a thanks for the report, yeah, we will look into it

**Comment by wangyongj1a** [comment]
> As a side note, `mlir-cpu-runner` lets you specify the return type of main()

I see, thank you for reminding!

**Comment by Hardcode84** [comment]
@wangyongj1a https://github.com/llvm/llvm-project/commit/0733f384142b02558b80b3e9a4633dc4d202a14b should fix this issue

**Comment by wangyongj1a** [comment]
> @wangyongj1a [0733f38](https://github.com/llvm/llvm-project/commit/0733f384142b02558b80b3e9a4633dc4d202a14b) should fix this issue

Thanks for your work!
