### ISSUE TITLE
What happened to [[no_unique_address]] ? Deadlock occured!

### ISSUE THREAD

**Issue by kelbon** [llvm/llvm-project#82181]
On windows its not working, clang17 outputs
```cpp
warning: unknown attribute 'no_unique_address' ignored [-Wunknown-attributes]
```
https://github.com/llvm/llvm-project/issues/49358

I read and it also does not solve problem, even when i add flag `-fms-compatibility` (rly i dont want FULL compatibility with non-standard compatible msvc for one standard attribute!!!)
```cpp
struct E {};
struct A {
  char c;
  [[msvc::no_unique_address]] E val;
};

int main() { static_assert(sizeof(A) == 1); }
```
Output:
```
PS C:\Users\User> clang++ ./test.cpp -std=c++20 -fms-compatibility                                    
./test.cpp:4:5: warning: unknown attribute 'no_unique_address' ignored [-Wunknown-attributes]
    4 |   [[msvc::no_unique_address]] E val;
      |     ^~~~~~~~~~~~~~~~~~~~~~~
./test.cpp:7:28: error: static assertion failed due to requirement 'sizeof(A) == 1'
    7 | int main() { static_assert(sizeof(A) == 1); }
      |                            ^~~~~~~~~~~~~~
./test.cpp:7:38: note: expression evaluates to '2 == 1'
    7 | int main() { static_assert(sizeof(A) == 1); }
      |                            ~~~~~~~~~~^~~~
```

Same output for just [[no_unique_address]], so, now i see deadlock in those conversations, while clang waits for msvc support and some abi smart things, msvc waits CLANG to support [[no_unique_address]] (i dont know why)
https://github.com/microsoft/STL/issues/1364#issuecomment-1034167093

![image](https://github.com/llvm/llvm-project/assets/58717435/879fd289-401b-4383-a78f-e004d372c6df)

(its really deadlock)

I will not comment on the decision of MSVC to add its own attribute [[msvc::no_unique_address]] after [[no_unique_address]] was standartized, but it is obvious that the longer it is delayed, the more code will be affected by the so-called ABI breakdown, because people use this attribute all over the place, but it doesn't work right now

In any case, I do not consider adjusting to the MSVC policy to be the correct strategy, especially since due to this strategy, now clang is the only compiler on which it is impossible to use this attribute. On GCC it just works, on MSVC you can write [[msvc::no_unique_address]] and on clang ?? there are no way!

**Comment by philnik777** [comment]
What exactly are you trying to report? Clang implements `[[msvc::no_unique_address]]` now, as you can see in the issue you linked yourself.

**Comment by kelbon** [comment]
> What exactly are you trying to report? Clang implements `[[msvc::no_unique_address]]` now, as you can see in the issue you linked yourself.

i cannot reproduce iit on windows localy, i use clang 17 and it does not work even with flag msvc compatibility

**Comment by philnik777** [comment]
It's been added in Clang 18.

**Comment by dwblaikie** [comment]
@amykhuang in case any of this is interesting to you (the linked MSVC bug seems older than your work to add support, and I think most of the dust has settled/this issue is a bit out of date, basically - and the conclusion that MSVC and clang would use `[[msvc::no_unique_address]]` until MSVC does an ABI break at some indeterminate point in the future is the status quo and now implemented by both compilers)
