### ISSUE TITLE
`clang --analyze` is slow

### ISSUE THREAD

**Issue by jirislaby** [llvm/llvm-project#82222]
I have a [static checker to collect structs+members](https://github.com/jirislaby/clang-struct) of the Linux kernel.

I have `compile_commands.json` with properly defined command line for each file, so if I put the command line into an array `cmdline`, I can do:
```sh
clang "${cmdline[@]}" -E | clang -cc1  -analyze -load clang-struct.so -analyzer-checker jirislaby.StructMembersChecker
```

But this is not right as (for example) the second `clang` needs to know about `-fshort-wchar` from the former (from `cmdline`), otherwise I see errors like:
```
arch/x86/platform/efi/quirks.c:80:27: error: initializing wide char array with incompatible wide string literal
   80 | static const efi_char16_t efi_dummy_name[] = L"DUMMY";
```

I can go closer with **one** `clang` process using `--analyze` and **no** `-cc1`:

```sh
clang "${cmdline[@]}" --analyze --analyzer-no-default-checks -Xclang -load -Xclang clang-struct.so \
    -Xclang -analyzer-checker -Xclang jirislaby.StructMembersChecker
```

But while the former (*piped*) `clang` takes 1,3 s real time, the latter takes 3,5 s.

Is this a bug in `--analyze` switch (so that it compiles the result too) or is the command line wrong?

Note that here:
https://github.com/llvm/llvm-project/blob/6009708b4367171ccdbf4b5905cb6a803753fe18/clang/lib/Driver/Driver.cpp#L4129-L4133
`PL` is `clang::driver::phases::Compile` perhaps as expected? `FullPL` contains also `clang::driver::phases::Backend`, `clang::driver::phases::Assemble`, `clang::driver::phases::Link` (which is expected for `TY_C`, perhaps?):
```
(gdb) p PL
$6 = llvm::SmallVector of Size 2, Capacity 7 = {clang::driver::phases::Preprocess, clang::driver::phases::Compile}
(gdb) p FullPL
$7 = llvm::SmallVector of Size 5, Capacity 7 = {clang::driver::phases::Preprocess, clang::driver::phases::Compile, clang::driver::phases::Backend, clang::driver::phases::Assemble, 
  clang::driver::phases::Link}
```

### Details
The invocation I do is as follows. Note that neither `--analyze`, nor `-fsyntax-only` avoids compilation (ie. the cmd still takes 3,5s, opposing to `-cc1 -analyze`).
```sh
clang -Wp,-MMD,arch/x86/platform/efi/.quirks.o.d -nostdinc -I/mnt/storage/xslaby/linux/arch/x86/include -I./arch/x86/include/generated -I/mnt/storage/xslaby/linux/include -I./include -I/mnt/storage/xslaby/linux/arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I/mnt/storage/xslaby/linux/include/uapi -I./include/generated/uapi -include /mnt/storage/xslaby/linux/include/linux/compiler-version.h -include /mnt/storage/xslaby/linux/include/linux/kconfig.h -include /mnt/storage/xslaby/linux/include/linux/compiler_types.h -D__KERNEL__ --target=x86_64-linux-gnu -fintegrated-as -Werror=unknown-warning-option -Werror=ignored-optimization-argument -Werror=option-ignored -Werror=unused-command-line-argument -fmacro-prefix-map=/mnt/storage/xslaby/linux/= -std=gnu11 -fshort-wchar -funsigned-char -fno-common -fno-PIE -fno-strict-aliasing -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fcf-protection=branch -fno-jump-tables -m64 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mstack-alignment=8 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -Wno-sign-compare -fno-asynchronous-unwind-tables -mretpoline-external-thunk -mindirect-branch-cs-prefix -mfunction-return=thunk-extern -fpatchable-function-entry=16,16 -fno-delete-null-pointer-checks -Os -fstack-protector-strong -ftrivial-auto-var-init=zero -fno-stack-clash-protection -pg -mfentry -DCC_USING_NOP_MCOUNT -DCC_USING_FENTRY -falign-functions=16 -fstrict-flex-arrays=3 -fno-strict-overflow -fno-stack-check -Wall -Wundef -Werror=implicit-function-declaration -Werror=implicit-int -Werror=return-type -Werror=strict-prototypes -Wno-format-security -Wno-trigraphs -Wno-frame-address -Wno-address-of-packed-member -Wframe-larger-than=2048 -Wno-gnu -Wno-unused-but-set-variable -Wno-unused-const-variable -Wvla -Wno-pointer-sign -Wcast-function-type -Wimplicit-fallthrough -Werror=date-time -Werror=incompatible-pointer-types -Wenum-conversion -Wno-unused-but-set-variable -Wno-unused-const-variable -Wno-pointer-to-enum-cast -Wno-tautological-constant-out-of-range-compare -Wno-unaligned-access -Wno-cast-function-type-strict -Wno-missing-field-initializers -Wno-type-limits -Wno-shift-negative-value -Wno-initializer-overrides -Wno-sign-compare -I /mnt/storage/xslaby/linux/arch/x86/platform/efi -I ./arch/x86/platform/efi    -DKBUILD_MODFILE='"arch/x86/platform/efi/quirks"' -DKBUILD_BASENAME='"quirks"' -DKBUILD_MODNAME='"quirks"' -D__KBUILD_MODNAME=kmod_quirks/x86/platform/efi/quirks.o /mnt/storage/xslaby/linux/arch/x86/platform/efi/quirks.c -w --analyze --analyzer-no-default-checks -Xclang -load -Xclang clang-struct.so -Xclang -analyzer-checker -Xclang jirislaby.StructMembersChecker -Xclang -analyzer-config -Xclang jirislaby.StructMembersChecker:basePath=../linux/
```

`compile_commands.json` entry for the above example:
```json
  {
    "command": "clang -Wp,-MMD,arch/x86/platform/efi/.quirks.o.d -nostdinc -I/mnt/storage/xslaby/linux/arch/x86/include -I./arch/x86/include/generated -I/mnt/storage/xslaby/linux/include -I./include -I/mnt/storage/xslaby/linux/arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I/mnt/storage/xslaby/linux/include/uapi -I./include/generated/uapi -include /mnt/storage/xslaby/linux/include/linux/compiler-version.h -include /mnt/storage/xslaby/linux/include/linux/kconfig.h -include /mnt/storage/xslaby/linux/include/linux/compiler_types.h -D__KERNEL__ --target=x86_64-linux-gnu -fintegrated-as -Werror=unknown-warning-option -Werror=ignored-optimization-argument -Werror=option-ignored -Werror=unused-command-line-argument -fmacro-prefix-map=/mnt/storage/xslaby/linux/= -std=gnu11 -fshort-wchar -funsigned-char -fno-common -fno-PIE -fno-strict-aliasing -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fcf-protection=branch -fno-jump-tables -m64 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mstack-alignment=8 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -Wno-sign-compare -fno-asynchronous-unwind-tables -mretpoline-external-thunk -mindirect-branch-cs-prefix -mfunction-return=thunk-extern -fpatchable-function-entry=16,16 -fno-delete-null-pointer-checks -Os -fstack-protector-strong -ftrivial-auto-var-init=zero -fno-stack-clash-protection -pg -mfentry -DCC_USING_NOP_MCOUNT -DCC_USING_FENTRY -falign-functions=16 -fstrict-flex-arrays=3 -fno-strict-overflow -fno-stack-check -Wall -Wundef -Werror=implicit-function-declaration -Werror=implicit-int -Werror=return-type -Werror=strict-prototypes -Wno-format-security -Wno-trigraphs -Wno-frame-address -Wno-address-of-packed-member -Wframe-larger-than=2048 -Wno-gnu -Wno-unused-but-set-variable -Wno-unused-const-variable -Wvla -Wno-pointer-sign -Wcast-function-type -Wimplicit-fallthrough -Werror=date-time -Werror=incompatible-pointer-types -Wenum-conversion -Wno-unused-but-set-variable -Wno-unused-const-variable -Wno-pointer-to-enum-cast -Wno-tautological-constant-out-of-range-compare -Wno-unaligned-access -Wno-cast-function-type-strict -Wno-missing-field-initializers -Wno-type-limits -Wno-shift-negative-value -Wno-initializer-overrides -Wno-sign-compare -I /mnt/storage/xslaby/linux/arch/x86/platform/efi -I ./arch/x86/platform/efi    -DKBUILD_MODFILE='\"arch/x86/platform/efi/quirks\"' -DKBUILD_BASENAME='\"quirks\"' -DKBUILD_MODNAME='\"quirks\"' -D__KBUILD_MODNAME=kmod_quirks -c -o arch/x86/platform/efi/quirks.o /mnt/storage/xslaby/linux/arch/x86/platform/efi/quirks.c",
    "directory": "/mnt/storage/xslaby/cl",
    "file": "/mnt/storage/xslaby/linux/arch/x86/platform/efi/quirks.c"
  },
```

**Comment by steakhal** [comment]
My guess is that --analyze enables CSA, besides the regular clang frontend action (which is to compile code).
I'd suggest to have a look at how scan-build sets up the analyzer and mimic that.

Note that its highly discouraged to use CSA using the -cc1 tool. Users should try to use tools like scan-build or CodeChecker to capture, transform the build command and set uo the analysis flags accordingly.

Im also unsure if a CSA plugin is the best way to log some AST constructs, such as structs. There is a python wrapper library for clang to do basic stuff in that context.
And if its not powerful enough to express the logging logic you want, you can make your own ASTConsumer and traverse the AST natively. There should be some unittests that give you some examples.

**Comment by jirislaby** [comment]
>  I'd suggest to have a look at how scan-build sets up the analyzer and mimic that.

Oh wow, `scan-build` apparently (AFAIU) invokes the provided command line and adds `-###`. The generated `-cc1` line is then invoked. That works around the problem, indeed. Both py and pl variants seem to do the same.

> Note that its highly discouraged to use CSA using the -cc1 tool

OTOH `scan-build` does exactly that ;).  So I am still not sure why the obvious `--analyze` does not avoid the compilation the same as `-cc1 -analyze`.

> Users should try to use tools like scan-build or CodeChecker

`scan-build` won't fly for the kernel -- I don't need a wrapper for `make` -- the kernel already provides a way to generate `compile_commands.json`. And that should be used (somehow) in this case IMO.

Let me check `CodeChecker` as that consumes the json. Let's see if it can fit the use case…

> There is a python wrapper library for clang to do basic stuff in that context.

Good, except I don't speak snakes. I speak llamas. So the Py binding is somewhat hopeless for me.

> ASTConsumer and traverse the AST natively

Hmm, I currently use `ASTMatch`ers. Let me see what `ASTConsumer` can/do. Thanks.

**Comment by haoNoQ** [comment]
> So I am still not sure why the obvious --analyze does not avoid the compilation the same as -cc1 -analyze.

They both perform compilation up to the AST, and then they both don't perform LLVM IR generation. 

> But while the former (piped) clang takes 1,3 s real time, the latter takes 3,5 s.

This is probably because of all the other checkers enabled by `--analyze`. In your manual `-cc1` invocation only your checker is enabled. In the normal `--analyze` invocation all default checkers are enabled. In particular, path-sensitive analysis is enabled, which is *much* slower than compilation.

**Comment by jirislaby** [comment]
> In the normal --analyze invocation all default checkers are enabled

But I run with `--analyzer-no-default-checks` (see above).

**Comment by Snape3058** [comment]
> Hmm, I currently use ASTMatchers. Let me see what ASTConsumer can/do. Thanks.

I think you can implement your tool as a part of clang-tidy, which uses astmatchers.

> scan-build won't fly for the kernel -- I don't need a wrapper for make -- the kernel already provides a way to generate compile_commands.json. And that should be used (somehow) in this case IMO.

which also provides the [run-clang-tidy.py script]([llvm-project/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py](https://github.com/llvm/llvm-project/blob/main/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py)) to directly read the compilation database and execute clang-tidy on every TU.

Besides, you can also use my [panda tool](https://github.com/Snape3058/panda) to achieve this goal. It can run both clang tooling tools and the compiler directly with customized options and compilation arguments.

**Comment by haoNoQ** [comment]
> > In the normal --analyze invocation all default checkers are enabled
> 
> But I run with `--analyzer-no-default-checks` (see above).

Oh, right, yes, now that I read this more carefully, this indeed sounds really weird. The `--analyze` flag is supposed to completely suppress IR generation, and I've never seen it not do that.

Can you try to figure out which compiler flag causes this to happen? You have a minimal `-cc1` invocation that doesn't do compilation, and you have an `--analyze` invocation that does do compilation. Does your default `--analyze` invocation on a "hello world" input file (eg. literally just `clang --analyze helloworld.c`) perform compilation? If not, can you remove compiler flags from your large `--analyze` invocation one by one until it stops performing compilation, to figure out which flag causes it? Otherwise (which would already be insanely surprising), can you pass `-###` to your hello world invocation to see the corresponding `-cc1` invocation and remove flags from it one by one until it starts behaving like your minimal `-cc1` invocation?

**Comment by haoNoQ** [comment]
(Can you reproduce this on godbolt.org? I.e., manipulate the run-line in https://godbolt.org/z/P6GbEsM1E until you see assembly generated?)

**Comment by jirislaby** [comment]
I am now not sure if I measured correctly. I switched to `--analyze` and the times for processing all linux kernel files are comparable...
