### ISSUE TITLE
[InstCombine] Failure to convert vector fp comparisons that can be represented as integers

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#82241]
https://rust.godbolt.org/z/dfWjnToef

We will simplify a comparison of scalar floats that can be represented as integers to compare the integers directly, but we don't do this for vectors:

```ll
define i32 @cmpf(i32 %x) {
  %and = and i32 %x, 3
  %conv = sitofp i32 %and to float
  %cmp = fcmp oeq float %conv, 3.000000e+00
  %sext = sext i1 %cmp to i32
  ret i32 %sext
}

define <8 x i32> @vcmpf(<8 x i32> %x) {
  %and = and <8 x i32> %x, <i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3>
  %conv = sitofp <8 x i32> %and to <8 x float>
  %cmp = fcmp oeq <8 x float> %conv, <float 3.000000e+00, float 3.000000e+00, float 3.000000e+00, float 3.000000e+00, float 3.000000e+00, float 3.000000e+00, float 3.000000e+00, float 3.000000e+00>
  %sext = sext <8 x i1> %cmp to <8 x i32>
  ret <8 x i32> %sext
}
```
opt -O3
```ll
define i32 @cmpf(i32 %x) {
  %and = and i32 %x, 3
  %cmp = icmp eq i32 %and, 3
  %sext = sext i1 %cmp to i32
  ret i32 %sext
}

define <8 x i32> @vcmpf(<8 x i32> %x) {
  %and = and <8 x i32> %x, <i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3, i32 3>
  %conv = sitofp <8 x i32> %and to <8 x float>
  %cmp = fcmp oeq <8 x float> %conv, <float 3.000000e+00, float 3.000000e+00, float 3.000000e+00, float 3.000000e+00, float 3.000000e+00, float 3.000000e+00, float 3.000000e+00, float 3.000000e+00>
  %sext = sext <8 x i1> %cmp to <8 x i32>
  ret <8 x i32> %sext
}
```

**Comment by SahilPatidar** [comment]
@dtcxzyw,
I would like to work on this one.

**Comment by SahilPatidar** [comment]
@RKSimon and @dtcxzyw,

I have been reviewing the foldFCmpIntToFPConst function in InstCombineCompares.cpp and have noticed a potential issue regarding vector of floats. The current implementation only checks for ConstantFP, which means it would return nullptr for vector of floats.

I am planning to make some changes to address this issue and related code. Before proceeding, I wanted to confirm if my understanding is correct and if there is a specific procedure I should follow for making these changes.
Thank you for your time and assistance.

**Comment by RKSimon** [comment]
Just using Constant::getSplatValue(false) would safely solve this for splat vectors (with no undefs)

**Comment by SahilPatidar** [comment]
@RKSimon,
I'm seeking clarification on a line in the foldFCmpIntToFPConst function in LLVM:

`IntegerType *IntTy = cast<IntegerType>(LHSI->getOperand(0)->getType());`

This line is casting the type of the first operand of LHSI to IntegerType. However, the type of the operand is actually a vector type <8 x i32>. Could you provide guidance on how to properly handle this situation?

**Comment by RKSimon** [comment]
AFAICT you can tweak it to work with scalar or vector integer types by changing it to:
```cpp
auto *IntTy = cast<IntegerType>(LHSI->getOperand(0)->getType()->getScalarType());
```
Type::getScalarType will just pass through scalar types, but will return the element type for vectors

**Comment by RKSimon** [comment]
Although the more I look at it - I don't think we need the IntegerType type at all - IntTy->getBitWidth() is just the same as IntTy->getScalarSizeInBits() below.

```cpp
auto *IntTy = LHSI->getOperand(0)->getType();
unsigned InputSize = IntTy->getScalarSizeInBits();
...
APSInt RHSCvt(InputSize , LHSUnsigned);
```

**Comment by SahilPatidar** [comment]
@RKSimon,
Will the test updates be made in the fcmp.ll file?

**Comment by SahilPatidar** [comment]
@RKSimon,
Please let me know if anything is incorrect or requires improvement.

**Comment by RKSimon** [comment]
Some minor comments, but if you rebase against upstream trunk and then create a PR we'll get it to a wider audience.
