### ISSUE TITLE
polly: 3 * trivial performance issues

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#82263]
Static analyser cppcheck says:

polly/lib/Support/GICHelper.cpp:89:64: performance: Function parameter 'DefaultValue' should be passed by const reference. [passedByValue]
polly/lib/Transform/MatmulOptimizer.cpp:637:62: performance: Function parameter 'MMI' should be passed by const reference. [passedByValue]
polly/lib/Transform/MatmulOptimizer.cpp:714:35: performance: Function parameter 'MMI' should be passed by const reference. [passedByValue]

This issue would be suitable for a new starter.

**Comment by chrisj-quic** [comment]
My team will take a look into addressing these issues.

**Comment by firewave** [comment]
The suggestion might not be correct and the actual fix might be to add a `std::move()` (see https://trac.cppcheck.net/ticket/12384).

**Comment by dcb314** [comment]
Avoiding string copies on stack by using const references has been 
a standard technique for over 35 years in C++.

Are you saying that has now changed ?

**Comment by firewave** [comment]
C++11 introduced `std::move()` which can completely enable copies in some cases. Just check the linked ticket for an example where the suggestion is misleading.

**Comment by dcb314** [comment]
?? I don't see any mention of std::move in the example you suggest.

In general, a const reference will always be cheaper than a copy.
I don't see anything here or in your example that changes that.
