### ISSUE TITLE
[mlir][mesh] Sharding propagation does not produce a complete sharding annotation

### ISSUE THREAD

**Issue by sogartar** [llvm/llvm-project#82375]
I have not noticed that sharding propagation would not produce `mesh.shard` for each result and a `mesh.shard` with `annotate_for_users` fro each use. See [test](https://github.com/llvm/llvm-project/blob/135529aab0ebe4915143f376d94f8aba6ec71e4e/mlir/test/Dialect/Mesh/sharding-propagation.mlir#L21).

Running the pass on
```mlir
mesh.mesh @mesh_2d(shape = 2x4)

func.func @element_wise_on_def(%arg0: tensor<8x16xf32>) -> tensor<8x16xf32> {
  %0 = tosa.sigmoid %arg0 : (tensor<8x16xf32>) -> tensor<8x16xf32>
  %1 = mesh.shard %0 to <@mesh_2d, [[0], [1]]> : tensor<8x16xf32>
  return %1 : tensor<8x16xf32>
}
```

results in

```mlir
mesh.mesh @mesh_2d(shape = 2x4)
func.func @element_wise_on_def(%arg0: tensor<8x16xf32>) -> tensor<8x16xf32> {
  %0 = mesh.shard %arg0 to <@mesh_2d, [[0], [1]]> annotate_for_users : tensor<8x16xf32>
  %1 = tosa.sigmoid %0 : (tensor<8x16xf32>) -> tensor<8x16xf32>
  %2 = mesh.shard %1 to <@mesh_2d, [[0], [1]]> : tensor<8x16xf32>
  return %2 : tensor<8x16xf32>
}
```

I thought that it should result in
```mlir
mesh.mesh @mesh_2d(shape = 2x4)
func.func @element_wise_on_def(%arg0: tensor<8x16xf32>) -> tensor<8x16xf32> {
  %0 = mesh.shard %arg0 to <@mesh_2d, [[0], [1]]> : tensor<8x16xf32>
  %1 = mesh.shard %0 to <@mesh_2d, [[0], [1]]> annotate_for_users : tensor<8x16xf32>
  %2 = tosa.sigmoid %1 : (tensor<8x16xf32>) -> tensor<8x16xf32>
  %3 = mesh.shard %2 to <@mesh_2d, [[0], [1]]> : tensor<8x16xf32>
  %4 = mesh.shard %3 to <@mesh_2d, [[0], [1]]> annotate_for_users : tensor<8x16xf32>
  return %4 : tensor<8x16xf32>
}
```

I implemented the spmdization pass under the assumption that the sharding annotations at this point are complete.
It may be easy to handle the cases with the missing shardings, but the canonical form should be without missing annotations.

**Comment by sogartar** [comment]
@yaochengji, what was your rationale when you implemented the sharding propgataion pass?

**Comment by yaochengji** [comment]
@sogartar thanks for noticing this, this is for simplifying the IR. The rationale is that when a Value's producer and users share the same sharding annotation, we only need to add one.

**Comment by sogartar** [comment]
OK. This could potentially reduce the number of operations significantly if there is no resharding, which should be generally avoided due to its communication cost.
It seems that the spmdization pass is going to be the only downstream consumer of a fully annotated program, wheres the sharding propagation is in place of a myriad of possible sharding algorithms. I may adapt spmdization to handle these corner cases.
Another place where this IR will be consumed is in tests. The it is desirable to define a canonical form and have sharding propagation always produce canonical full annotations. The canonical form may be that if there is no resharding then always have only one `mesh.shard` without `annotate_for_users`.
There is another consideration that if a fully annotated program is ran again through sharding propagation, there should be no change. I am not sure if you can always get that if we use the concise form.

**Comment by sogartar** [comment]
I decided to extend the spmdization pass to support the concise representation #82442
