### ISSUE TITLE
NaNs do not compare false

### ISSUE THREAD

**Issue by gonzalobg** [llvm/llvm-project#82471]
I found it surprising that in C++ using `clang` (see here https://cpp.godbolt.org/z/K6oTvMo69):

- `qNaN == qNaN` returns true, 
- `qNan != qNaN` returns false, and 
- `numeric_limits` claims `iec559`.

Does someone know why this is the case?

**Comment by topperc** [comment]
`std::numeric_limits<double>::quiet_NaN` is a point to a function. You want to make a call to the function `std::numeric_limits<double>::quiet_NaN()`

**Comment by gonzalobg** [comment]
Oh well, that for sure explains it, thanks!
