### ISSUE TITLE
The order of parameters is incorrect In the old version

### ISSUE THREAD

**Issue by tianxinghe** [llvm/llvm-project#82473]
https://github.com/llvm/llvm-project/blob/main/llvm/lib/Support/Z3Solver.cpp
![image](https://github.com/llvm/llvm-project/assets/26410605/1cacd2f4-e176-4fc5-bb7a-8656914c15b6)

https://github.com/llvm/llvm-project/blob/release/9.x/llvm/lib/Support/Z3Solver.cpp
![image](https://github.com/llvm/llvm-project/assets/26410605/89c59b67-0744-412d-9994-be55d6b1db31)

It has been corrected in the new version, but it seems that it has not been synchronized to the old version (such as llvm9)

**Comment by nikic** [comment]
Only the latest version of LLVM is maintained by upstream.
