### ISSUE TITLE
[Flang] macro + comment + line continuation

### ISSUE THREAD

**Issue by ye-luo** [llvm/llvm-project#82579]
main.f90
```
#define DEV_ACC !!!

program aa
implicit none

integer i,j,a
DEV_ACC data &
DEV_ACC & copyin(i)
do i=1,10
do j=1,10
  a=1
enddo
enddo
end program
```

got
```
$ flang-new -cpp main.f90 
error: Could not parse main.f90
./main.f90:13:4: error: expected end of statement
  enddo
     ^
./main.f90:13:1: in the context: END PROGRAM statement
  enddo
  ^
./main.f90:3:1: in the context: main program
  program aa
  ^
```
`gfortran -cpp main.f90` works

**Comment by jeffhammond** [comment]
The code used in this test is just terrible and should be removed from whatever app is doing it.

It doesn't compile with Intel Fortran either.
```
$ ifx bad.F90
bad.F90(8): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: ( , % . /
 & copyin(i)
------------^
compilation aborted for bad.F90 (code 1)
$ ifort bad.F90
bad.F90(8): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: ( , % . /
 & copyin(i)
------------^
compilation aborted for bad.F90 (code 1)
```

**Comment by ye-luo** [comment]
@jeffhammond for Intel compilers. Additional compiler option `-allow nofpp_comments` is needed.
```
$ ifx -fpp -allow nofpp_comments main.f90 # works.
$ ifx -fpp main.f90
main.f90(8): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: ( , % . /
 & copyin(i)
------------^
compilation aborted for main.f90 (code 1)
```

**Comment by ye-luo** [comment]
The preprocessor seems buggy.
```
flang-new -cpp repro.f90 -E
#line "./repro.f90" 3
      program aa
      implicit none

      integer i,j,a



      do j=1,10
      a=1
      enddo
      enddo
      end program
```
the loop i went missing.

**Comment by ye-luo** [comment]
@klausler I assigned you because I saw you working on the preprocessor. Do you mind taking a look?

**Comment by klausler** [comment]
f18 processes Fortran continuation lines before performing macro replacement, so

```
DEV_ACC data &
DEV_ACC & copyin(i)
do I=1,10
```

becomes
```
DEV_ACC data DEV_ACC do I=1,10
```
with a warning about extraneous tokens (`copyin(i)`) after the continuation marker

and then is ignored as a comment when `DEV_ACC` is replaced with `!!!`.

I suggest that you try using a macro for `&` if you want to play these games with preprocessing and also want code portability.

**Comment by jeffhammond** [comment]
This is not a bug.  There is no standard Fortran preprocessor.  This code only works with GCC `cpp`.  If you want that, then put it in the build system explicitly the way that NWChem does (for a different reason than the one here).  You cannot expect Flang to support `cpp` in the front-end.

**Comment by klausler** [comment]
I might be able to hack around this case; reopening until I know for sure.

**Comment by ye-luo** [comment]
https://fortranwiki.org/fortran/show/Continuation+lines
mentioned "Comments are allowed after the ampersand."

However, if characters after ampersand are not comment nor white spaces, the ampersand should be treated as "an optional ampersand at the beginning of the continuation line". Thus the `do I=1,10` should not be appended to the previous line. Right?

**Comment by klausler** [comment]
https://github.com/llvm/llvm-project/pull/94663
