### ISSUE TITLE
Github workflow misattributes /cherry-pick backport request comment

### ISSUE THREAD

**Issue by patrick-rivos** [llvm/llvm-project#82580]
Request: https://github.com/llvm/llvm-project/issues/82430#issuecomment-1958608125
Misattributed to me: https://github.com/llvm/llvm-project/pull/82572

Current workflow: https://github.com/llvm/llvm-project/blob/815644b4dd882ade2e5649d4f97c3dd6f7aea200/.github/workflows/issue-release-workflow.yml#L68

Replacing this line with `${{ github.event.comment.user.login }}` would attribute the PR to the user that commented `/cherry-pick`

From looking at the workflow it looks like it supports cherry-pick in newly opened issues too. Replacing the `.issue` with `.comment` won't work in that case, so issues/comments need to have different logic to attribute properly in all cases.

**Comment by lukel97** [comment]
I noticed this too, thanks for filing this!
