### ISSUE TITLE
[TBAA][DSE] bitfield store is incorrectly optimized out

### ISSUE THREAD

**Issue by dtcxzyw** [llvm/llvm-project#82586]
Reproducer: https://godbolt.org/z/jKrGW5jEh
```
#include <stdint.h>

struct S1 {
   signed f0 : 9;
   unsigned f1 : 2;
   int8_t  f2;
};

struct S1 g;

struct S1 func(struct S1* x) {
    x->f2 = 3;
    *x = g;
    return *x;
}
```
`x->f2 = 3` is incorrectly eliminated by `DSEPass`.
This miscompilation is caused by recent commit https://github.com/llvm/llvm-project/pull/81313.

**Comment by dtcxzyw** [comment]
Another reproducer: https://godbolt.org/z/Y3bnsMqd7

**Comment by fhahn** [comment]
Let me take a look. It seems like clang emits tbaa .struct with overlapping fields. Need to check what exactly is going on
