### ISSUE TITLE
[arm32] using lld, the names of functions in plt are replaced by $*

### ISSUE THREAD

**Issue by Zhenhang1213** [llvm/llvm-project#82589]
Using lld, the names of functions in plt are replaced by $* in arm32, 

code:
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
int func()
{
        char c = 'b';
        char str1[8];
        memset(str1, c, 8);
        return 0;
}
int main()
{
        func();
        return 0;
}
```

clang demo.c -o demo32.o -fuse-ld=lld   -fstack-protector
llvm-objdump -d  demo32.o

Disassembly of section .plt:

000106e0 <$a>:                       <<<<----- There is the question
   106e0: e52de004      str     lr, [sp, #-4]!
   106e4: e28fe600      add     lr, pc, #0, #12
   106e8: e28eea20      add     lr, lr, #32, #20
   106ec: e5bef1a4      ldr     pc, [lr, #420]!

000106f0 <$d>:                        <<<<----- There is the question
   106f0: d4 d4 d4 d4   .word   0xd4d4d4d4
   106f4: d4 d4 d4 d4   .word   0xd4d4d4d4
   106f8: d4 d4 d4 d4   .word   0xd4d4d4d4
   106fc: d4 d4 d4 d4   .word   0xd4d4d4d4

00010700 <$a>:                      <<<<----- There is the question
   10700: e28fc600      add     r12, pc, #0, #12
   10704: e28cca20      add     r12, r12, #32, #20
   10708: e5bcf18c      ldr     pc, [r12, #396]!

**Comment by asl** [comment]
These are so-called mapping symbols: https://sourceware.org/binutils/docs/as/ARM-Mapping-Symbols.html Their presence is expected.

**Comment by asl** [comment]
> But why doesn't this happen when I use the arm64 architecture?

Because there are no mapping symbols on aarch64. It's entirely different architecture.

**Comment by Zhenhang1213** [comment]
> But why is it possible to use binutils tools, especially this document or binutils extract?

But why is it possible to use binutils tools, especially this document or binutils extract?

> > But why doesn't this happen when I use the arm64 architecture?
> 
> Because there are no mapping symbols on aarch64. It's entirely different architecture.

**Comment by Zhenhang1213** [comment]
> > But why doesn't this happen when I use the arm64 architecture?
> 
> Because there are no mapping symbols on aarch64. It's entirely different architecture.

But why is it possible to use binutils tools, especially this document or binutils extract? And arrch64 use $x as mapping symbols:https://sourceware.org/binutils/docs/as/AArch64-Mapping-Symbols.html

**Comment by Zhenhang1213** [comment]
> There are no plt symbols in the binary. They are made up on the fly by objdump, and afaik this only works for x86 and AArch64. You can see symbols in the binary with `llvm-readelf --syms`.

I think you're right, but I can't generate plt symbols with objdump, but I can generate spe civic plt symbols with arrch64 and x86

**Comment by Zhenhang1213** [comment]
> There are no plt symbols in the binary. They are made up on the fly by objdump, and afaik this only works for x86 and AArch64. You can see symbols in the binary with `llvm-readelf --syms`.

I see that the llvm doesn't  have the implementation of adding plt symbols for arm. What is the reason for this?
