### ISSUE TITLE
libc/src/__support/memory_size.h:57: Possible missing else ?

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#82644]
Static analyser cppcheck says:

libc/src/__support/memory_size.h:57:12: style: Variable 'result' is reassigned a value before the old one has been used. [redundantAssignment]

Source code is

    if (LIBC_UNLIKELY((value | other.value) < 0))
      result = -1;
    result = value + other.value;

Maybe there is a missing else ?

**Comment by SchrodingerZhu** [comment]
Will take a look
