### ISSUE TITLE
[infra] Add git CLI to Linux container

### ISSUE THREAD

**Issue by sudonatalie** [llvm/llvm-project#82646]
Since #81349 the [SPIR-V Tests](https://github.com/llvm/llvm-project/actions/workflows/spirv-tests.yml) workflow has been failing with `/bin/sh: 1: git: not found`.

**Comment by sudonatalie** [comment]
@tstellar Can you take a look at this or help point me to an appropriate config file? I can't seem to figure out where packages would be managed for the container.

**Comment by tstellar** [comment]
@sudonatalie The dockerfile for the container is here: https://github.com/llvm/llvm-project/blob/main/.github/workflows/containers/github-action-ci/stage2.Dockerfile

But why is the SPIR-V build trying to clone and build code from another repo?  Is that used for testing?

**Comment by sudonatalie** [comment]
@tstellar Yes, it's a test-only dependency on an external tool that does some additional validation of test output. It's off by default but we've enabled it on the bots because it can catch certain classes of regressions that are otherwise difficult to identify.

**Comment by boomanaiden154** [comment]
I remember adding `git` to the container at some point. It looks like I added it to the toolchain build container rather than the image that actually gets used in the CI jobs.
