### ISSUE TITLE
[CodeGen] Refactor MachineInstr findRegisterDefOperandIdx/findRegisterDefOperand etc. to stop missing TRI args

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#82659]
As noticed by @AtariDreams on #82411, by having the TargetRegisterInfo argument at the end of a long line of optional args, we are often missing it in our function calls and not correctly testing for super reg kill state etc.

```cpp
  int findRegisterUseOperandIdx(Register Reg, bool isKill = false, const TargetRegisterInfo *TRI = nullptr) const;
  MachineOperand *findRegisterUseOperand(Register Reg, bool isKill = false, const TargetRegisterInfo *TRI = nullptr);
  ... etc ...
```
ideally we need to refactor the calls so the TRI is no longer optional, so when we don't care about super-registers we explicitly have to set it nullptr.
```cpp
  int findRegisterUseOperandIdx(Register Reg, const TargetRegisterInfo *TRI, bool isKill = false) const;
  MachineOperand *findRegisterUseOperand(Register Reg, const TargetRegisterInfo *TRI, bool isKill = false);
  ... etc ...
```

**Comment by RKSimon** [comment]
@simonzgx Please keep an eye on #82411 as @AtariDreams is adding explicit TRI to several locations to address some implicit bugs - its likely that patch will land first so you may have to rebase a large number of conflicts

**Comment by simonzgx** [comment]
@RKSimon Got it.

**Comment by simonzgx** [comment]
@RKSimon Okay, will do it pretty soon.
