### ISSUE TITLE
[RISCV][MacroFusion] Improve fusion in pre-RA

### ISSUE THREAD

**Issue by zxc12523** [llvm/llvm-project#82738]
#79425 has adopted TableGen-based macro fusion. 

And it will generate RISCVGenMacroFusion.inc.

```cpp
bool isTuneAUIPCADDIFusion(
    const TargetInstrInfo &TII,
    const TargetSubtargetInfo &STI,
    const MachineInstr *FirstMI,
    const MachineInstr &SecondMI) {
  auto &MRI = SecondMI.getMF()->getRegInfo();
  {
    const MachineInstr *MI = &SecondMI;
    if (( MI->getOpcode() != RISCV::ADDI ))
      return false;
  }
  if (!FirstMI)
    return true;
  {
    const MachineInstr *MI = FirstMI;
    if (( MI->getOpcode() != RISCV::AUIPC ))
      return false;
  }
  {
    const MachineInstr *MI = &SecondMI;
    if (!(
        MI->getOperand(0).getReg().isVirtual()
        || MI->getOperand(0).getReg() == MI->getOperand(1).getReg()
      ))
      return false;
  }
  {
    Register FirstDest = FirstMI->getOperand(0).getReg();
    if (FirstDest.isVirtual() && !MRI.hasOneNonDBGUse(FirstDest))
      return false;
  }
  if (!(FirstMI->getOperand(0).isReg() &&
        SecondMI.getOperand(1).isReg() &&
        FirstMI->getOperand(0).getReg() == SecondMI.getOperand(1).getReg()))
    return false;
  return true;
}
```

My question is, is it possible to check `FirstMI->getOperand(0).getReg() == SecondMI.getOperand(2).getReg()` when these two regs are virtual and the second inst is commutative?

**Comment by wangpc-pp** [comment]
> is it possible to check FirstMI->getOperand(0).getReg() == SecondMI.getOperand(2).getReg() when these two regs are virtual and the second inst is commutative?

Yes, it can be set via adding a `TieReg<0, 2>`.

This can be done automatically, I will create a PR for this. Thanks for reporting!

**Comment by zxc12523** [comment]
Thanks for your response! Are there any tablegen learning materials or source code reading tools I can use? I am a newbie and I want to learn more about this topic.

**Comment by wangpc-pp** [comment]
> Thanks for your response! Are there any tablegen learning materials or source code reading tools I can use? I am a newbie and I want to learn more about this topic.

You mean the TableGen-based macro fusion? I have some links that you can refer to:
* [[RFC] TableGen-driven MacroFusion predicators generator](https://discourse.llvm.org/t/rfc-tablegen-driven-macrofusion-predicators-generator/74912). This is the RFC, but the implementation is a little different now after reviewing and some refactors.
* https://github.com/llvm/llvm-project/pull/72224#issuecomment-1846927348. This is the whole patchset of TableGen-based macro fusion.

Some code links:
* https://github.com/llvm/llvm-project/blob/8be39b3901e3326ceebeaf0381f8cc57fdc0d464/llvm/include/llvm/Target/TargetSchedule.td#L585-L699. This the TableGen definitions. I think it is expressive but not so easy to use(I'm continue to improve it).
* https://github.com/llvm/llvm-project/blob/main/llvm/utils/TableGen/MacroFusionPredicatorEmitter.cpp. This is the TableGen backend that generates these predicators.
