### ISSUE TITLE
[libc][c23] implement `memset_explicit`

### ISSUE THREAD

**Issue by SchrodingerZhu** [llvm/llvm-project#82817]
See: 
1. https://gustedt.gitlabpages.inria.fr/c23-library/
2. [n3088](https://www.open-std.org/jtc1/sc22/WG14/www/docs/n3088.pdf)

--------------
I am currently working on this but I am still trying to make it clear about the assumptions/requirements of this function, given that [1] lists some suggestions that are seemingly too restrictive.

**Comment by BreadTom** [comment]
Clang, just like [GCC](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68034), has no __builtin_memset_explicit, I think this should be added for C23 support.
