### ISSUE TITLE
modules;json: inconsistent keys: `is-standard-library` vs `is-std-library`

### ISSUE THREAD

**Issue by mathstuf** [llvm/llvm-project#82879]
@mordante In `libc++.modules.json`, there are two spellings for "is this a standard library module": `is-standard-library` and `is-std-library`. This should be resolved before 18.0.0 is released. Introduced in https://github.com/llvm/llvm-project/pull/75741.

Pinging release managers to get this marked as a blocker for 18.0: @llvm/llvm-release-managers

**Comment by mordante** [comment]
@mathstuf actually it seems I copied this correctly. The proposal on the SG15 reflector uses both. (I'll mail the reflector.)
