### ISSUE TITLE
Calling a static constexpr method on a non-constexpr variable does not yield a constexpr result

### ISSUE THREAD

**Issue by eyelash** [llvm/llvm-project#82891]
The following C++ code fails to compile with Clang 17.0.1:

```cpp
struct A {
    static constexpr int n() {
        return 42;
    }
};

void foo(const A& a) {
    constexpr int n = a.n();
}
```

with the following error message:

```
<source>:8:19: error: constexpr variable 'n' must be initialized by a constant expression
    8 |     constexpr int n = a.n();
      |                   ^   ~~~~~
<source>:8:23: note: function parameter 'a' with unknown value cannot be used in a constant expression
    8 |     constexpr int n = a.n();
      |                       ^
<source>:7:19: note: declared here
    7 | void foo(const A& a) {
      |                   ^
```

GCC compiles the same code without errors.

**Comment by EugeneZelenko** [comment]
Could you please try 18 or `main` branch? https://godbolt.org should be helpful.

**Comment by eyelash** [comment]
Clang trunk x86-64 (cd1d4d8dd31f527615de26f5b62d687c6b2982a6) still fails with the same error message.

**Comment by eyelash** [comment]
This might be covered by [P2280](https://wg21.link/P2280R4) which is not yet implemented in Clang according to [this page](https://clang.llvm.org/cxx_status.html).

**Comment by shafik** [comment]
Duplicate: https://github.com/llvm/llvm-project/issues/63139
