### ISSUE TITLE
-Wfatal-errors doesn't work.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#8290]
|  |  |
| --- | --- |
| Bugzilla Link | [7918](https://llvm.org/bz7918) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
If I have t.cpp containing:

  int blubx = 3;
  template <typename> struct X {};
  template <typename R> void g(typename X<R>::type);
  void f() { g<int>(blabx); }

Then if I do:

  clang t.cpp -Wfatal-errors

I get the output:

  t.cpp:4:19: fatal error: use of undeclared identifier 'blabx'; did you mean 'blubx'?
  ...
  t.cpp:4:12: fatal error: no matching function for call to 'g'
  ...
  2 errors generated.

I could not find -Wfatal-errors in the Clang manual, but I'm assuming the intent is that it behaves like GCC's -Wfatal-errors, whose behavior is described in the GCC manual as:

  This option causes the compiler to abort compilation on the
  first error occurred

Clang generated /two/ errors, so it did not abort on the first one. :)

I'm using Clang r111084.

**Comment by philnik777** [comment]
This has been fixed: https://godbolt.org/z/aKrP1nT4b
