### ISSUE TITLE
[MC] __FUNCTION__ not in symtab in AArch64

### ISSUE THREAD

**Issue by CoTinker** [llvm/llvm-project#82961]
test.c
```
#include <stdio.h>

int main() {
    printf("%s\n", __FUNCTION__);
}
```
compile command:
```
clang test.c -o test.o -c
```
https://godbolt.org/z/PPaGT3j46
```
// X86 backend
% clang test.c -o test.o -c
% llvm-readelf -s test.o
Symbol table '.symtab' contains 7 entries:
   Num:    Value          Size Type    Bind   Vis       Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT   UND 
     1: 0000000000000000     0 FILE    LOCAL  DEFAULT   ABS test.c
     2: 0000000000000000     0 SECTION LOCAL  DEFAULT     2 .text
     3: 0000000000000000     4 OBJECT  LOCAL  DEFAULT     4 .L.str
     4: 0000000000000004     5 OBJECT  LOCAL  DEFAULT     4 .L__FUNCTION__.main
     5: 0000000000000000    29 FUNC    GLOBAL DEFAULT     2 main
     6: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND printf


// AArch64 backend
% clang test.c -o test.o -c
% llvm-readelf -s test.o
Symbol table '.symtab' contains 10 entries:
   Num:    Value          Size Type    Bind   Vis       Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT   UND
     1: 0000000000000000     0 FILE    LOCAL  DEFAULT   ABS test.c
     2: 0000000000000000     0 SECTION LOCAL  DEFAULT     2 .text
     3: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT     2 $x.0
     4: 0000000000000000     0 SECTION LOCAL  DEFAULT     4 .rodata.str1.1
     5: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT     4 $d.1
     6: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT     5 $d.2
     7: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT     7 $d.3
     8: 0000000000000000    40 FUNC    GLOBAL DEFAULT     2 main
     9: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND printf
```
I don't known why symbol `.L__FUNCTION__.main` is in symtab in X86 but not in AArch64

**Comment by asl** [comment]
> I don't known why symbol .L__FUNCTION__.main is in symtab in X86 but not in AArch64

Why this is a problem?

**Comment by CoTinker** [comment]
I'm not saying it's a problem, I'm just wondering why there is such a difference

**Comment by CoTinker** [comment]
https://github.com/llvm/llvm-project/blob/cace477c0b6c3d9494ead66eb725c6e72f27b767/llvm/lib/MC/ELFObjectWriter.cpp#L1446

https://github.com/llvm/llvm-project/blob/cace477c0b6c3d9494ead66eb725c6e72f27b767/llvm/lib/MC/ELFObjectWriter.cpp#L1392-L1397

the value of C in AArch64 is 0, in X86 is -4

**Comment by CoTinker** [comment]
CC @Grosbach

**Comment by CoTinker** [comment]
CC @MaskRay

**Comment by MaskRay** [comment]
Both x86 and non-x86 behaviors are intended.
For AArch64, a relocation referencing the `.L*` symbol can be converted to reference the STT_SECTION symbol instead, because the addend is zero.
There is no ambiguity which string piece a relocation references.

For x86, because the addend is negative (relative to the next instruction), we cannot do the conversion.
If we do, linkers would consider the relocation to reference a different string piece.

**Comment by CoTinker** [comment]
If I need the `.L__FUNCTION__.main` symbol in kernel, how can I get it in symtab.

**Comment by MaskRay** [comment]
> If I need the `.L__FUNCTION__.main` symbol in kernel, how can I get it in symtab.

I cannot think of a way in MC. Why do you need the symbol in the kernel? If your kernel does some linker tasks, you can teach it `SHF_MERGE` semantics.
