### ISSUE TITLE
clang-diagnostics: -Wswitch-default and -Wcovered-switch-default contradictory warnings

### ISSUE THREAD

**Issue by FalcoGer** [llvm/llvm-project#82960]
When having both `-Wswitch-default` and `-Wcovered-switch-default` this generates contradictory warnings. When you don't have a `default` case for a `switch` statement that handles every `enum` value you get a warning for not having it; and if you do you get a warning for having it. However you require both those flags if you wish to get related warnings elsewhere when dealing with `switch` statements not related to `enum`s or `enum`s but not all the values.

[Example](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:5,endLineNumber:9,positionColumn:5,positionLineNumber:9,selectionStartColumn:5,selectionStartLineNumber:9,startColumn:5,startLineNumber:9),source:'%23include+%3Ccstdint%3E%0A%0Aenum+class+ETest+:+std::uint8_t%0A%7B%0A++++TEST1,%0A++++TEST2,%0A%7D%3B%0A%0Aauto+main()+-%3E+int%0A%7B%0A++++ETest+test+%3D+ETest::TEST2%3B%0A++++%5B%5Bmaybe_unused%5D%5D%0A++++int+++a+%7B%7D%3B%0A%0A++++switch+(test)%0A++++%7B%0A++++++++case+ETest::TEST1:+a+%3D+1%3B+break%3B%0A++++++++case+ETest::TEST2:+a+%3D+2%3B+break%3B%0A++++++++//+default:+++++++++++a+%3D+99%3B+break%3B%0A++++%7D%0A%0A++++return+0%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:33.333333333333336,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:clang_trunk,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-std%3Dc%2B%2B23+-Wall+-Wextra+-Wpedantic+-Wswitch-default+-Wcovered-switch-default',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+clang+(trunk)+(Editor+%231)',t:'0')),k:33.333333333333336,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'AVR+gcc+13.2.0',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+clang+(trunk)+(Compiler+%231)',t:'0')),k:33.33333333333333,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

```c++
#include <cstdint>

enum class ETest : std::uint8_t
{
    TEST1,
    TEST2,
};

auto main() -> int
{
    ETest test = ETest::TEST2;
    [[maybe_unused]]
    int   a {};

    switch (test)
    {
        case ETest::TEST1: a = 1; break;
        case ETest::TEST2: a = 2; break;
        // default:           a = 99; break;
    }

    return 0;
}
```

What I would expect is that `-Wswitch-default` is suppressed when dealing with `enum`s and every `case` is covered, but active otherwise.

The way it is now, you will miss out on at least one of those three possible cases that require a warning:

- A `switch` statement that is not handling an `enum` doesn't have a `default` case (which is bad)
- A `switch` statement that is dealing with an `enum` is fully defined but has a `default` case (which is bad)
- A `switch` statement that is dealing with an `enum` is not fully defined and doesn't have a `default` case (which is bad)

This was not the case in earlier versions of clang, which handled this correctly.

My version is

```text
Ubuntu clang version 19.0.0 (++20240222031214+307409a8872f-1~exp1~20240222151237.1514)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by aaronpuchert** [comment]
Correct, the intention was to have the warning behave like GCC's implementation.

> What I would expect is that `-Wswitch-default` is suppressed when dealing with `enum`s and every `case` is covered, but active otherwise.

That is the behavior of clang-tidy's [bugprone-switch-missing-default-case](https://clang.llvm.org/extra/clang-tidy/checks/bugprone/switch-missing-default-case.html). I guess a discussion can be had about having this in the core compiler, but we'd need some good arguments.

> This was not the case in earlier versions of clang, which handled this correctly.

Earlier versions of Clang didn't implement `-Wswitch-default` at all. You can see that #73077 implemented the warning which was previously only a no-op. If you want to restore the behavior of earlier versions, simply disable the warning.

**Comment by aaronpuchert** [comment]
Duplicates #81354.
