### ISSUE TITLE
Using -dsa-no-filter-callcc=false causes BU to crash

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#8301]
|  |  |
| --- | --- |
| Bugzilla Link | [7929](https://llvm.org/bz7929) |
| Version | trunk |
| OS | All |
| Attachments | [Test case](https://user-images.githubusercontent.com/60944935/143741856-7c846a87-9e24-48de-b3ab-06dd3cf35572.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Using the -dsa-no-filter-callcc=false option while running the -calltarget pass causes DSA to segfault.  The problem appears to be that filtering out invalid function call targets causes the calculateGraphs() function to recurse indefinitely.

The problem can be reproduced on the attached .ll file by assembling it and doing the following:

opt -load $HOME/box/x86/llvm27/projects/poolalloc/Debug/lib/libLLVMDataStructure.so -calltarget -analyze test2.bc -dsa-no-filter-callcc=false

**Comment by arsenm** [comment]
The mentioned flag no longer exists
