### ISSUE TITLE
llvm-cxxfilt should accept symbols from stdin

### ISSUE THREAD

**Issue by alanzhao1** [llvm/llvm-project#83048]
GNU's c++filt can accept input from stdin. This is extremely convenient for piping assembly or LLVM IR to c++filt and get back the same input but with the symbols demangled. Currently, llvm-cxxfilt only accepts mangled symbols as command line parameters. llvm-cxxfilt should have the same functionality as c++filt.

**Comment by philnik777** [comment]
I just tried with `echo _Z3std7my_func | llvm-cxxfilt` and everything works just as expected. What version do you have?

**Comment by alanzhao1** [comment]
Oh huh, it does work. Not sure what was going on...

Comdat sections however don't get demangled - e.g.

```sh
$ echo '$_ZN6MyTask12promise_type17get_return_objectEv = comdat any' | bin/llvm-cxxfilt
$_ZN6MyTask12promise_type17get_return_objectEv = comdat any
```

**Comment by ADKaster** [comment]
c++filt from binutils 2.38 doesn't demangle that, nor does `demumble` (https://github.com/nico/demumble)

Where did you get the version of c++filt that tolerates a leading `$` ? and where did the symbol come from?

**Comment by philnik777** [comment]
I'm not sure it's actually a symbol. This is most likely tool output. I'm using the Gentoo 2.41 p2 version of c++filt.

**Comment by alanzhao1** [comment]
This is the version of `c++filt` that I'm using:

```
$ c++filt --version
GNU c++filt (GNU Binutils for Debian) 2.41.50.20231206
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.

$ echo '$_ZN6MyTask12promise_type17get_return_objectEv = comdat any' | c++filt
MyTask::promise_type::get_return_object() = comdat any
```

**Comment by alanzhao1** [comment]
Based on the comments, I'll close this issue as WAI/obsolete.
