### ISSUE TITLE
[clang] implement __builtin_clzg

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#83075]
similar to #82058 and mentioned in #79630. To implement parts of C23 stdbit.h, it would be nice if we exposed a similar builtin to GCC.

This is a type agnostic builtin that lowers to an intrinsic I suspect we already have in LLVM.

cc @overmighty

**Comment by frederick-vs-ja** [comment]
Just a question: can/should we use these new intrinsics to simplify C++20 `<bit>` utilities?

**Comment by nickdesaulniers** [comment]
Yes; thanks for pointing out C++20 <bit> to me; looking at the interface I now see that C23's bit.h is very similar.

I see that libcxx's include/__bit/*.h mostly implements these using the non-type generic builtins.  The type generic builtins could be used if they are available.  `__has_builtin` is pretty nascent in GCC FWICR, and these type generic variants are mostly not yet implemented in clang.  So if you need to support older versions of GCC and clang, it's perhaps not worth the effort yet to use some of these.

cc @ldionne @philnik777

**Comment by philnik777** [comment]
If all compilers we support in libc++ have it we'd probably switch, but until then I don't see us using it. This really isn't a throughput-intensive part of the code base, so adding a branch for that doesn't seem worth it to me.
