### ISSUE TITLE
[Flang][OpenMP] verification of lowering to FIR failed with "address must dereference to value type"

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#83144]
Reproducible on Godbolt:
https://godbolt.org/z/5Wa1bqG7d

Reproducer (`flang-new -fopenmp test.f90`):
```console
$ cat test.f90
program p
    implicit none
    logical :: l
    !$omp atomic write
        l = .true.
    !$omp end atomic
end
$ flang-new -fopenmp test.f90
error: address must dereference to value type
error: verification of lowering to FIR failed
```

**Comment by ohno-fj** [comment]
Let me add some information.

I found a similar error when building [mumps](https://mumps-solver.org/index.php) using flang-new.  
If `logical` is changed to `real` or `integer`, the compilation terminates normally.

**Comment by k-arrows** [comment]
I will provide another reproducer for this error. (At least the error message is identical.)

The following is reduced from https://github.com/gcc-mirror/gcc/blob/master/libgomp/testsuite/libgomp.fortran/atomic1.f90
```console
$ cat atomic1_reduced.f90
program pr92899_reduced
  real :: x = 1.0
  double precision :: y
  !$omp atomic capture
  y = x
  x = 2.0
  !$omp end atomic
  if (y /= 1.0 .or. x /= 2.0) stop 1
end
$ flang-new -fopenmp atomic1_reduced.f90
error: address must dereference to value type
error: verification of lowering to FIR failed
```
https://godbolt.org/z/vaTo6h5vo

**Comment by k-arrows** [comment]
The compilation error has been resolved. I will close this issue.
