### ISSUE TITLE
[Flang] fir.rebox verification failure when passing rank-2 actual to polymorphic assumed-size dummy

### ISSUE THREAD

**Issue by DanielCChen** [llvm/llvm-project#83164]
Consider the following code:
```
type base
  integer :: i
end type
class(base), pointer :: b1(:,:)
call sub(b1)
contains
subroutine sub(arg)
class(base) :: arg(1:*)
end
end
```

Flang currently issues
```
error: loc("t1.f":5:1): 'fir.rebox' op result type and shape operand ranks must match
error: verification of lowering to FIR failed
```

XLF, gfortran and ifort all compile this successfully.

**Comment by kkwli** [comment]
Is it the same as https://github.com/llvm/llvm-project/issues/82640?

**Comment by DanielCChen** [comment]
> Is it the same as #82640?

I think it is in the same category. The possible difference is that the test case in this issue could pass a descriptor while #82640 passes the the address of the object.
