### ISSUE TITLE
clangd crashes on initializing designator of field in anonymous struct or union

### ISSUE THREAD

**Issue by alirezamoshtaghi** [llvm/llvm-project#83185]
See attached test case and fix for it:

[fix-clangd-crash-on-designator-init.patch](https://github.com/llvm/llvm-project/files/14425623/fix-clangd-crash-on-designator-init.patch)

**Comment by HighCommander4** [comment]
@alirezamoshtaghi thank you for writing a test case and fix. Would you mind submitting it as a pull request please?

**Comment by alirezamoshtaghi** [comment]
I don't think I have the permission to create pull request.
I created a fork and was able to push my changes to that fork but it does not give me the option to create the pull request. Am I doing it right?

**Comment by HighCommander4** [comment]
> I created a fork and was able to push my changes to that fork

Could you link to the commit in your fork?

**Comment by alirezamoshtaghi** [comment]
@HighCommander4 ,
I was able to create the pull request 👍 
https://github.com/llvm/llvm-project/pull/83369

**Comment by alirezamoshtaghi** [comment]
The checks are complete for the pull request. Hopefully soon someone reviews it

**Comment by HighCommander4** [comment]
For reference, here is the stack trace of the crash that occurs if the test case is run without the fix:

```
clangd: clang/lib/Basic/SourceManager.cpp:1986: bool clang::SourceManager::isBeforeInTranslationUnit(clang::SourceLocation, clang::SourceLocation) const: Assertion `LHS.isValid() && RHS.isValid() && "Passed invalid source location!"' failed.
 #0 0x00007fe39298776d llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) llvm/lib/Support/Unix/Signals.inc:723:11
 #1 0x00007fe392987c5b PrintStackTraceSignalHandler(void*) llvm/lib/Support/Unix/Signals.inc:798:1
 #2 0x00007fe392985ce6 llvm::sys::RunSignalHandlers() llvm/lib/Support/Signals.cpp:105:5
 #3 0x00007fe3929883e5 SignalHandler(int) llvm/lib/Support/Unix/Signals.inc:413:1
 #4 0x00007fe398bf7730 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12730)
 #5 0x00007fe391c9c8eb raise /build/glibc-6iIyft/glibc-2.28/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #6 0x00007fe391c87535 abort /build/glibc-6iIyft/glibc-2.28/stdlib/abort.c:81:7
 #7 0x00007fe391c8740f _nl_load_domain /build/glibc-6iIyft/glibc-2.28/intl/loadmsgcat.c:1177:9
 #8 0x00007fe391c951a2 (/lib/x86_64-linux-gnu/libc.so.6+0x301a2)
 #9 0x00007fe39334ad64 clang::SourceManager::isBeforeInTranslationUnit(clang::SourceLocation, clang::SourceLocation) const clang/lib/Basic/SourceManager.cpp:1987:11
#10 0x000055d1311d2fe2 clang::SourceManager::isPointWithin(clang::SourceLocation, clang::SourceLocation, clang::SourceLocation) const clang/include/clang/Basic/SourceManager.h:1705:13
#11 0x000055d1311ccc97 clang::clangd::(anonymous namespace)::ExtractionContext::exprIsValidOutside(clang::Stmt const*) const clang-tools-extra/clangd/refactor/tweaks/ExtractVariable.cpp:180:12
#12 0x000055d13114a4a9 clang::clangd::(anonymous namespace)::ExtractionContext::computeInsertionPoint() const clang-tools-extra/clangd/refactor/tweaks/ExtractVariable.cpp:230:9
#13 0x000055d13114a321 clang::clangd::(anonymous namespace)::ExtractionContext::ExtractionContext(clang::clangd::SelectionTree::Node const*, clang::SourceManager const&, clang::ASTContext const&) clang-tools-extra/clangd/refactor/tweaks/ExtractVariable.cpp:162:20
#14 0x000055d1311494b8 std::_MakeUniq<clang::clangd::(anonymous namespace)::ExtractionContext>::__single_object std::make_unique<clang::clangd::(anonymous namespace)::ExtractionContext, clang::clangd::SelectionTree::Node const*&, clang::SourceManager const&, clang::ASTContext const&>(clang::clangd::SelectionTree::Node const*&, clang::SourceManager const&, clang::ASTContext const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/unique_ptr.h:831:34
#15 0x000055d131148cc0 clang::clangd::(anonymous namespace)::ExtractVariable::prepare(clang::clangd::Tweak::Selection const&) clang-tools-extra/clangd/refactor/tweaks/ExtractVariable.cpp:593:14
#16 0x00007fe398a90553 clang::clangd::prepareTweaks(clang::clangd::Tweak::Selection const&, llvm::function_ref<bool (clang::clangd::Tweak const&)>, clang::clangd::FeatureModuleSet const*) clang-tools-extra/clangd/refactor/Tweak.cpp:79:9
#17 0x00007fe398bb35dc clang::clangd::(anonymous namespace)::Checker::testLocationFeatures(std::optional<clang::clangd::Range>) clang-tools-extra/clangd/tool/Check.cpp:415:11
#18 0x00007fe398bb1f34 clang::clangd::check(llvm::StringRef, clang::clangd::ThreadsafeFS const&, clang::clangd::ClangdLSPServer::Options const&) clang-tools-extra/clangd/tool/Check.cpp:515:45
#19 0x00007fe398b721b2 clang::clangd::clangdMain(int, char**) clang-tools-extra/clangd/tool/ClangdMain.cpp:976:12
#20 0x000055d13127e152 main clang-tools-extra/clangd/tool/ClangdToolMain.cpp:12:3
```

**Comment by HighCommander4** [comment]
And steps to reproduce the crash would be:

1. Open a file containing:

```c
typedef struct S {
  unsigned char id;
  union {
    unsigned int mask;
    struct {
      unsigned int unused:10;
      unsigned int reserved:3;
      unsigned int rest:19;
    };
  };
} __attribute__((packed)) S_t;

typedef struct H {
  unsigned char hid;
  unsigned int val;
} handler_t;

struct S
get_foo (handler_t *h)
{
  S_t retval =
    {.id=h->hid,
     .mask=h->val};
  return retval;
}
```

2. Select the `->` characters on the line `.mask=h->val`.

Clangd crashes while trying to figure out whether the "extract variable" code action should be offered for this selection.

**Comment by HighCommander4** [comment]
The crash is a regression on trunk, not present in clangd 18 or earlier.

**Comment by HighCommander4** [comment]
(It's not clear to me what change regressed this; I couldn't find an obviously related change to clangd's "extract variable" code or to `DesignatedInitExpr` since 18.x branched. @alirezamoshtaghi if you happen to know, I would be curious.)

**Comment by alirezamoshtaghi** [comment]
I could not locate one either. It maybe deeper than clangd and be somewhere in llvm itself; however I think the code segment that I fixed is executed from clangd and the problem doesnt show in the llvm test cases. ASent from my iPhoneOn Mar 11, 2024, at 1:01 AM, Nathan Ridge ***@***.***> wrote:﻿
(It's not clear to me what change regressed this; I couldn't find an obviously related change to clangd's "extract variable" code or to DesignatedInitExpr since 18.x branched. @alirezamoshtaghi if you happen to know, I would be curious.)

**Comment by HighCommander4** [comment]
Here is a further reduced testcase. This one does not involve a union, just an anonymous struct:

```c++
struct A {
  struct {
    int x;
  };
};

struct B {
  int y;
};

void foo(struct B *b) {
  struct A a = {.x=b->y };
}
```

The crash is triggered by selecting the `->` token.

**Comment by HighCommander4** [comment]
The reason for the crash is that the `DesignatedInitExpr` representing `.x=b->y` does not have a valid begin location.

The begin location is determined by asking the **first** designator for its begin location. Here, representation built by clang has two designators: (1) an anonymous designator referring to the anonymous struct field of `A`, and (2) the `.x` designator referring to the field `x` of that struct. The anonymous one does not have a valid source location since it's implicit.

Clangd assumes that the AST nodes enclosing the selection (which, for the selection `->`, includes this `DesignatedInitExpr`) have valid source ranges.

**Comment by HighCommander4** [comment]
> The crash is a regression on trunk, not present in clangd 18 or earlier.

Sorry, I was mistaken about this. The crash is present on clangd 18 and earlier as well, it just only happens with assertions enabled (and my trunk build had assertions enabled while the release builds I was testing with didn't).
