### ISSUE TITLE
Incorrect configuration snippets for some AlignConsecutive... option sets

### ISSUE THREAD

**Issue by EugeneZelenko** [llvm/llvm-project#83207]
[Current documentation](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) has incorrect configuration snippets for `AlignConsecutiveAssignments`, `AlignConsecutiveBitFields`, `AlignConsecutiveDeclarations`, `AlignConsecutiveTableGenCondOperatorColons`, `AlignConsecutiveTableGenDefinitionColons` that refer to `AlignConsecutiveMacros` instead of actual option set.

**Comment by PeterChou1** [comment]
Hi! I opened a PR to fix the issue

**Comment by EugeneZelenko** [comment]
@PeterChou1: Thank you for fix!
