### ISSUE TITLE
llvm/lib/TextAPI/TextStub.cpp: 2 * redundant condition ?

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#83241]
Static analyser cppcheck says:

trunk/llvm/lib/TextAPI/TextStub.cpp:279:18: style: Redundant condition: Ctx. '!Ctx || (Ctx && Ctx->FileKind!=FileType::Invalid)' is equivalent to '!Ctx || Ctx->FileKind!=FileType::Invalid' [redundantCondition]
trunk/llvm/lib/TextAPI/TextStub.cpp:301:18: style: Redundant condition: Ctx. '!Ctx || (Ctx && Ctx->FileKind!=FileType::Invalid)' is equivalent to '!Ctx || Ctx->FileKind!=FileType::Invalid' [redundantCondition]

**Comment by Troy-Butler** [comment]
Hi, could you please assign this issue to me?

**Comment by dcb314** [comment]
> Hi, could you please assign this issue to me?

I have had a look around the GUI and couldn't find the button, so no ;-<
Perhaps someone with more idea can help ?
