### ISSUE TITLE
[X86] v4f16 -> v4i32 conversion unnecessarily using YMM registers

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#83402]
https://rust.godbolt.org/z/PEfxzYY4z

```ll
define <4 x i32> @fptosi_4f16_to_4i32(<4 x half> %a) nounwind {
  %cvt = fptosi <4 x half> %a to <4 x i32>
  ret <4 x i32> %cvt
}
```
llc -mcpu=x86-64-v3
```asm
fptosi_4f16_to_4i32:                    # @fptosi_4f16_to_4i32
        vcvtph2ps       %xmm0, %ymm0
        vcvttps2dq      %ymm0, %ymm0
        vzeroupper
        retq
```

We should only require the xmm variants (and avoid the vzeroupper entirely)

**Comment by vedantparanjape-amd** [comment]
I am taking a look at this, I tried to do this in selectionDAG, seems it won't work there. What might be a good place to do this optimization ?

**Comment by RKSimon** [comment]
```
SelectionDAG has 11 nodes:
  t0: ch,glue = EntryToken
          t2: v8f16,ch = CopyFromReg t0, Register:v8f16 %0
        t12: v8f32 = fp_extend t2
      t13: v8i32 = fp_to_sint t12
    t11: v4i32 = extract_subvector t13, Constant:i64<0>
  t8: ch,glue = CopyToReg t0, Register:v4i32 $xmm0, t11
  t9: ch = X86ISD::RET_GLUE t8, TargetConstant:i32<0>, Register:v4i32 $xmm0, t8:1
```
To start, the vcvttps2dq instruction (the FP_TO_SINT node) should be reduced to v8f32 ->v4i32 - DAGCombine already has narrowExtractedVectorBinOp so maybe we need an equivalent narrowExtractedVectorUnaryOp/narrowExtractedVectorCastOp?

**Comment by RKSimon** [comment]
After that, X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode has a section dedicated to reducing the vector width of target nodes if the high half elements are not demanded - adding X86ISD::CVTPH2PS should be reltively easy.

**Comment by RKSimon** [comment]
Additionally, you could investigate adding more cast nodes (FP_TO_SINT / SINT_TO_FP / FP_EXTEND etc.) to TargetLowering::SimplifyDemandedVectorElts so that it at calls SimplifyDemandedVectorElts on the source operand.

**Comment by vedantparanjape-amd** [comment]
> ```
> SelectionDAG has 12 nodes:
>   t0: ch,glue = EntryToken
>             t2: v8f16,ch = CopyFromReg t0, Register:v8f16 %0
>           t14: v8i16 = bitcast t2
>         t15: v8f32 = X86ISD::CVTPH2PS t14
>       t13: v8i32 = fp_to_sint t15
>     t11: v4i32 = extract_subvector t13, Constant:i64<0>
>   t8: ch,glue = CopyToReg t0, Register:v4i32 $xmm0, t11
>   t9: ch = X86ISD::RET_GLUE t8, TargetConstant:i32<0>, Register:v4i32 $xmm0, t8:1
> ```
> 
> To start, the vcvttps2dq instruction (the FP_TO_SINT node) should be reduced to v8f32 ->v4i32 - DAGCombine already has narrowExtractedVectorBinOp so maybe we need an equivalent narrowExtractedVectorUnaryOp/narrowExtractedVectorCastOp?

I was able to implement this part, but it fails in legalization as these two DAG nodes

>       t13: v8i32 = fp_to_sint t15
>     t11: v4i32 = extract_subvector t13, Constant:i64<0>

are reduced to:

>       t13: v4i32 = fp_to_sint t15

where t15 is v8f16

```
llc: /home/vparanja/llvm-project-upstream/llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp:5781: llvm::SDValue llvm::SelectionDAG::getNode(unsigned int, const llvm::SDLoc&, llvm::EVT, llvm::SDValue, llvm::SDNodeFlags): Assertion `(!VT.isVector() || VT.getVectorElementCount() == N1.getValueType().getVectorElementCount()) && "Vector element count mismatch!"' failed.
```

**Comment by RKSimon** [comment]
Please can you show current patch in a draft PR?

**Comment by RKSimon** [comment]
@vedantparanjape-amd I've pushed 0bbe953aa3289a32cd816647820c8676bb3a61bc to avoid the need for #87977

The next step would be to add X86ISD::CVTPH2PS handling to X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode if you are still able to help?

**Comment by vedantparanjape-amd** [comment]
> @vedantparanjape-amd I've pushed [0bbe953](https://github.com/llvm/llvm-project/commit/0bbe953aa3289a32cd816647820c8676bb3a61bc) to avoid the need for #87977
> 
> The next step would be to add X86ISD::CVTPH2PS handling to X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode if you are still able to help?

Thanks! but the draft PR I shared, what was wrong with that ?

I checked SimplifyDemandedVectorEltsForTargetNode, I think, CVTPH2PS is already handled there! (https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/X86/X86ISelLowering.cpp 

Added in this commit 7f92efa5a9c6f3c1c9d7cdbd83460792d5984689

**Comment by RKSimon** [comment]
I was referring to the later code in X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode that halves the size of 256/512-bit nodes if the upper elements are undemanded.

Search for "(op ymm0, ymm1) --> insert undef, (op xmm0, xmm1), 0"

**Comment by vedantparanjape-amd** [comment]
> I was referring to the later code in X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode that halves the size of 256/512-bit nodes if the upper elements are undemanded.
> 
> Search for "(op ymm0, ymm1) --> insert undef, (op xmm0, xmm1), 0"

Got it! I will implement this, and send a PR. Thanks!

**Comment by RKSimon** [comment]
@vedantparanjape-amd reverse-ping

**Comment by vedantparanjape-amd** [comment]
> @vedantparanjape-amd reverse-ping

Hey @RKSimon , sorry it has been a super busy week. I will take a look at this soon!

**Comment by RKSimon** [comment]
@vedantparanjape-amd Are you still looking at this? I have a candidate fix if you don't have the time.

**Comment by vedantparanjape-amd** [comment]
> @vedantparanjape-amd Are you still looking at this? I have a candidate fix if you don't have the time.

sorry, I left AMD recently for grad school, and couldn't get time to work on this.
