### ISSUE TITLE
__builtin_cpu_supports should accept unknown options

### ISSUE THREAD

**Issue by DanielKristofKiss** [llvm/llvm-project#83407]
Backward\forward compatibility reasons any string shaped parameter in __builtin_cpu_supports should be accepted.
A given codebase might use a valid features that is supported in a new toolchain but not in the previous version.

```__builtin_cpu_supports("unsupported-features")``` 

It is valid to turn this into a constant false when the feature is not supported by the compiler.

see #82378

**Comment by jroelofs** [comment]
ISTM this should come with a warning like you get for `__attribute__((target_version("unsupported-feature")))`. Then codebases that want to turn those back into an error can `-Werror=` it.

**Comment by KanRobert** [comment]
CC @FreddyLeaf
