### ISSUE TITLE
[SimplifyCFG] Missed optimization: simplify if-else BBs that share common destinations

### ISSUE THREAD

**Issue by XChy** [llvm/llvm-project#83417]
Alive2 proof: https://alive2.llvm.org/ce/z/Q3dd5y

### Motivating example 

```llvm
define void @src(i1 %c1, i1 %c2) {
entry:
  br i1 %c1, label %then, label %else

then:
  br i1 %c2, label %bb1, label %bb2
  
else:
  br i1 %c2, label %bb2, label %bb1

bb1:
  call void @dummy1()
  ret void
bb2:
  call void @dummy2()
  ret void
}
```
can be folded to
```llvm
define void @tgt(i1 %c1, i1 %c2) {
entry:
  %xor = xor i1 %c1, %c2
  br i1 %xor, label %bb2, label %bb1

bb1:
  call void @dummy1()
  ret void
bb2:
  call void @dummy2()
  ret void
}
```
Here both `then` and `else` are trivial basicblocks with only a conditional branch inst, but I think it's possible to generalize it,  like replacing the condition of one of branch inst with `%c3`: https://alive2.llvm.org/ce/z/Xw9Ms2.

### Real-world motivation

This snippet of IR is derived from [z3/src/sat/tactic/goal2sat.cpp@convert_iff](https://github.com/Z3Prover/z3/blob/2880ea39719971226e616d1077788288d6107632/src/sat/tactic/goal2sat.cpp#L626) (after O3 pipeline).
The example above is a reduced version. Original IR comes from https://github.com/dtcxzyw/llvm-opt-benchmark/blob/main/bench/z3/original/goal2sat.cpp.ll. If you want optimal one, email me please.

**Let me know if you can confirm that it's an optimization opportunity, thanks.**

**Comment by elhewaty** [comment]
Assign me, please

**Comment by elhewaty** [comment]
I think the modification should go here, and after hoisting the identical code
we can see if the 2 blocks will only have the branch instruction, and see if we can 
merge the branching conditions, what do you think?

https://github.com/llvm/llvm-project/blob/main/llvm/lib/Transforms/Utils/SimplifyCFG.cpp#L7394

**Comment by XChy** [comment]
> I think the modification should go here, and after hoisting the identical code we can see if the 2 blocks will only have the branch instruction.

Maybe we don't care much about whether the identical code is hoisted(no impact on correctness), but care about whether the two successors has unique predecessor. Anyway, the link your post looks a good place to me.
