### ISSUE TITLE
[ClangCL] Does not recognize `/std:c++latest`

### ISSUE THREAD

**Issue by psiha** [llvm/llvm-project#83435]
I get:
2>clang-cl : warning : argument unused during compilation: '/std:c++latest' [-Wunused-command-line-argument]

(Visual Studio 17.9.2, Clang-CL 17.0.3)

**Comment by MaxEW707** [comment]
@psiha I am unable to reproduce this with Clang-CL 17.0.3 shipped with VS 17.9.x.

Can you paste the full command line including any quoting and escaping used when you got the above warning.

Thanks :).
