### ISSUE TITLE
[ClangCL] Add support for [[msvc::no_unique_address]]

### ISSUE THREAD

**Issue by psiha** [llvm/llvm-project#83445]
Currently (v17.0.3) I get: `warning : unknown attribute 'no_unique_address' ignored [-Wunknown-attributes] ` even with the msvc:: prefix one (which is supposed to work).

**Comment by frederick-vs-ja** [comment]
Duplicate of #49358.

I believe this is already fixed in Clang 18 by #65675 (also #67199).

**Comment by psiha** [comment]
Thanks for the 'pointer'!
