### ISSUE TITLE
[clangd] "--sysroot" options seems not work on Windows

### ISSUE THREAD

**Issue by HYJJJJJJJJ** [llvm/llvm-project#83449]
I get this error on Windows with both version 15.0.0 and 17.0.3, but "--sysroot" options is worked on Mac with version 15.0.0……
```
clangd.exe: Unknown command line argument '--sysroot=E:/mcu/GNU_Arm_Toolchain/arm-none-eabi'.  Try: 'E:\mcu\LLVM\bin\clangd.exe --help'
clangd.exe: Did you mean '--sync=E:/mcu/GNU_Arm_Toolchain/arm-none-eabi'?
```
I haven't try this command option on Mac with Ver 17.0.3.

**Comment by HighCommander4** [comment]
The command line options accepted by clangd itself, and the command line options that go in the "compile commands" that clangd uses to process opened files, are two different things.

`--sysroot` is an option in the second category. It has never been accepted by clangd itself as far as I'm aware.

**Comment by HYJJJJJJJJ** [comment]
> The command line options accepted by clangd itself, and the command line options that go in the "compile commands" that clangd uses to process opened files, are two different things.
> 
> `--sysroot` is an option in the second category. It has never been accepted by clangd itself as far as I'm aware.

Thank you for your reply.

Yes, I have the same doubt. I checked the source code of clangd and it seems that it does not support this option.

If clangd does not support the "--sysroot" option, how should I set sysroot or includepath to index the header file directory in the compilation chain I specify during smart jump?

**Comment by HYJJJJJJJJ** [comment]
I checked the compile_commands.json, judging from this file, the command used for compilation already contains the sysroot compilation option. This should indicate that there is no problem with my cmake configuration.

```
{
  "directory": "/Users/huangyongjie/Workspace/mcu/test-project/build",
  "command": "/Users/huangyongjie/Workspace/mcu/arm-gnu-toolchain-13.2.Rel1-darwin-arm64-arm-none-eabi/bin/arm-none-eabi-gcc -DSTM32F1 -DSTM32F103xE -I/Users/huangyongjie/Workspace/mcu/test-project/build -I/Users/huangyongjie/Workspace/mcu/test-project -I/Users/huangyongjie/Workspace/mcu/test-project/APP -I/Users/huangyongjie/Workspace/mcu/test-project/BSP -isystem /Users/huangyongjie/Workspace/mcu/STM32Cube_FW_F1_V1.8.0/Drivers/STM32F1xx_HAL_Driver/Inc -isystem /Users/huangyongjie/Workspace/mcu/STM32Cube_FW_F1_V1.8.0/Drivers/CMSIS/Include -isystem /Users/huangyongjie/Workspace/mcu/STM32Cube_FW_F1_V1.8.0/Drivers/CMSIS/Device/ST/STM32F1xx/Include -g --sysroot=\\\"/Users/huangyongjie/Workspace/mcu/arm-gnu-toolchain-13.2.Rel1-darwin-arm64-arm-none-eabi/arm-none-eabi\\\" -mthumb -Wall -ffunction-sections -fdata-sections -mcpu=cortex-m3 --specs=nosys.specs -o CMakeFiles/DickCleaner.dir/Users/huangyongjie/Workspace/mcu/STM32Cube_FW_F1_V1.8.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c.obj -c /Users/huangyongjie/Workspace/mcu/STM32Cube_FW_F1_V1.8.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c",
  "file": "/Users/huangyongjie/Workspace/mcu/STM32Cube_FW_F1_V1.8.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c",
  "output": "CMakeFiles/DickCleaner.dir/Users/huangyongjie/Workspace/mcu/STM32Cube_FW_F1_V1.8.0/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c.obj"
}
```

**Comment by HighCommander4** [comment]
Yes, `compile_commands.json` is the place to put it.

If it's not having the effect you're expecting, please be more specific about what you're expecting and what actually happens.

**Comment by HYJJJJJJJJ** [comment]
My development environment is vscode, and I have correctly configured it and the corresponding clangd plug-in.

In the current active project, I need to use the /Users/huangyongjie/Workspace/mcu/arm-gnu-toolchain-13.2.Rel1-darwin-arm64-arm-none-eabi cross-compilation chain to build the target. The ${sysroot}/include  of this compilation chain contains some header files that are not included in the LLVM project (such as stdio.h)

When I add "#include stdio.h" to my code, the clangd plugin will report an error:
`'stdio.h' file not foundclang(pp_file_not_found)`

I think this is caused by sysroot not being set up correctly, causing clangd to be unable to find the header file path of the cross-compilation chain. Are there any options to configure this path?

**Comment by HighCommander4** [comment]
The `--sysroot` flag in your `compile_commands.json` snippet looks like this:

```
--sysroot=\\\"/Users/huangyongjie/Workspace/mcu/arm-gnu-toolchain-13.2.Rel1-darwin-arm64-arm-none-eabi/arm-none-eabi\\\"
```

I've never seen a `\\\` like that before. Is that supposed to be there? Could that be the issue?

**Comment by HighCommander4** [comment]
Oh, I guess the `\\\"` is just two levels of escaping for `"` (though I'm not sure why two levels are needed, or indeed why quoting is needed for this path which does not contain any spaces).

**Comment by HYJJJJJJJJ** [comment]
!!!!!
I tried to remove these translation characters '\', and then clangd can work normally, thank you for your help!
