### ISSUE TITLE
General Question - Approach to Use of Clang for Windows Apps (Windows API)

### ISSUE THREAD

**Issue by CompCodeNet** [llvm/llvm-project#83453]
Hi, goal is:

- Write general Windows desktop and server apps using the Windows API
- Windows-only approach is OK, portability to other OS is not a priority
- Desktop apps include Windows UI (e.g. CreateWindow(...))
- Windows SDK only - No Visual Studio and no MSVC tools / libs that require Visual Studio license

What is a recommended approach to this? For example, can the LLVM 17.0.6 installation for Windows be used? Is mingw-64 (e.g. msys2) a better approach?

What are important considerations?
- Ramifications regarding standard C and C++ libraries? 
- Issues regarding compiling with Windows headers, e.g. Windows.h?
- Issues linking with windows API libraries 

Thank You. I'm somewhat familiar with clang and clang tools, but this is my first foray into using clang for Windows app development. I have existing code, and making changes to adapt it to use of Clang is not a problem.

**Comment by asl** [comment]
I would probably suggest you asking this on [Discourse](https://discourse.llvm.org/)

**Comment by CompCodeNet** [comment]
I will do that. Thank you.
