### ISSUE TITLE
[flang] flang accepts definition of selectors that are polymorphic pointer function results. Nag, gfortran, xlf do not. 

### ISSUE THREAD

**Issue by jeanPerier** [llvm/llvm-project#83549]
gfortran expects the following test to be rejected by semantic on the basis that the selector cannot be defined. 
https://github.com/llvm/llvm-test-suite/blob/main/Fortran/gfortran/regression/select_type_17.f03

Flang, ifort, and nvfortran accept it, and I do not see why it should be rejected given `fun(1)` is a variable since `fun` result is a POINTER (F2018 C1158 and R902).

I am just surprised that all of nag, xlf, and gfortran reject it, and I would like to confirm that this program is valid and I am not missing some rule here.

**Comment by klausler** [comment]
I think that the program conforms, since the function result is a pointer and hence a variable, not an expression.

**Comment by jeanPerier** [comment]
Thank you Peter. Closing this, I will flag the test as having incorrect expectation.
