### ISSUE TITLE
[flang] Behavior differs with gfortran/ifort when passing Hollerith to CLASS(*)

### ISSUE THREAD

**Issue by jeanPerier** [llvm/llvm-project#83548]
The following test fails with flang https://github.com/llvm/llvm-test-suite/blob/main/Fortran/gfortran/regression/unlimited_polymorphic_14.f90

It ends with STOP 2 because the Hollerith is passed to the CLASS(*) as a character while gfortran/ifort pass it with another type (which does not seem to be an intrinsic type, maybe it is some type code specific for Hollerith, I did not dig further).

Since this is not a standard feature, I am not sure about the expectation. Nag refuses it with an explicit message that Hollerith cannot be passed to CLASS(*).

**Comment by klausler** [comment]
This compiler treats Hollerith actual arguments as if they had been default kind character literals, and I think that's a sensible interpretation.  There is no good precedent: NAG disallows them from associating with `CLASS(*)` dummy arguments entirely as you noted; nvfortran and XLF compiler crash with internal errors; gfortran and Intel seem to treat the Hollerith as if it had been BOZ.  What do you think?

**Comment by klausler** [comment]
Done; https://github.com/llvm/llvm-project/pull/84084
