### ISSUE TITLE
-flang-experimental-polymorphism breaks OpenMPI build

### ISSUE THREAD

**Issue by jdenny-ornl** [llvm/llvm-project#83633]
I am building [OpenMPI 5.0.2](https://www.open-mpi.org/software/) using Clang and Flang.  The build started failing at 325f51237252, which enabled `-flang-experimental-polymorphism` by default.  The build was successful at the previous commit.

This is my build procedure for OpenMPI:

```
$ mkdir build && cd build
$ CC=clang CXX=clang++ FC=flang-new \
  CFLAGS="-O3" CXXFLAGS="-O3" FCFLAGS="-O3" \
  ../configure --prefix=$PWD/../install \
    --without-knem --without-ucx --enable-pretty-print-stacktrace \
    --enable-orterun-prefix-by-default --enable-mpi1-compatibility
$ make -j
$ make install
```

The error at 325f51237252 is:

```
error: loc("/home/jdenny/openmpi-5.0.2/build/ompi/mpi/fortran/use-mpi-f08/profile/paccumulate_f08.F90":30:4): /home/jdenny/llvm/flang/lib/Lower/ConvertCall.cpp:2409: not yet implemented: assumed type actual argument
```

I'm not aware of any use of assumed types in the associated code, but my fortran experience is limited, so please advise if I misunderstood something.

**Comment by jdenny-ornl** [comment]
Thanks for the reply.  While such issues are being fixed, is there a command-line option to disable -flang-experimental-polymorphism?

**Comment by jeanPerier** [comment]
@jdenny-ornl, the implementation for the TODO was merged a couple days ago. With the current llvm, I can build OpenMPI 5.0.2 given your config.

Can you confirm and close the issue if that is indeed fixed?

**Comment by jdenny-ornl** [comment]
I was able to build OpenMPI 5.0.2 using LLVM at 575ca6744b75 (a main commit from today).  Thanks for the fix!
