### ISSUE TITLE
use bolt to optimize Mysql got an extra fail test

### ISSUE THREAD

**Issue by andyzhaozhenyu** [llvm/llvm-project#83653]
When I use Bolt to optimize MySQL, and I use mtr test set, I get an extra fail -- gis.spatial_utility_function_distance_sphere. It should return an Overflow Error, but the mysqld after using bolt returned a memory allocation error. Even if I use bolt without any options to do that, this case still happens, can someone explain it or fix it plz?

**Comment by yota9** [comment]
What platform do you use, could you share binaries?

**Comment by andyzhaozhenyu** [comment]
The version of bolt 12, and I use bolt 17 to check it again. It passed the test. Is there some changes about disassembling and re-assembling these two versions? I used Linux arm, and just MySQL-8.0.24

**Comment by yota9** [comment]
Many bugs are being fixed from version to version, it is hard to say what exactly influenced it without more closely look. It is always better to use the latest bolt version to escape such situations.

**Comment by andyzhaozhenyu** [comment]
i see, BTW thanks for ur patient
