### ISSUE TITLE
[clang] 19.0.0 aborts due to Assertion `!T->isDependentType() && "should not see dependent types here"` failed in `tools/clang/include/clang/AST/TypeNodes.inc`

### ISSUE THREAD

**Issue by bjrjk** [llvm/llvm-project#83684]
Compile the following `1.cpp` with command line `clang++ -Xclang -fdump-record-layouts-complete 1.cpp` cause a clang abort:
```cpp
template <class Pointer>
struct AllocationResult {
  Pointer ptr = nullptr;
  int count = 0;
};
int main(){}
```

The attachment is crash backtrace, preprocessed source, and associated run script.
[crashsite.zip](https://github.com/llvm/llvm-project/files/14470166/crashsite.zip)

**Comment by Sirraide** [comment]
Looking at the patch that added this (https://reviews.llvm.org/D104484), we may be trying to dump an uninstantiated class template, which doesn’t really make sense. 

We’re also printing the layout of both `__NSConstantString_tag` and `__va_list_tag`, which seems a bit questionable. Perhaps we should skip implicitly defined records here.

**Comment by Sirraide** [comment]
Yeah, looks like that’s the problem.
