### ISSUE TITLE
[clang++] Compiler producing wrong code/discarding code.

### ISSUE THREAD

**Issue by Rugau** [llvm/llvm-project#83746]
I accidentally found this bug that seems to be present in clang++ >= 13.0.0
```
#include <stdio.h>

int main(int argc, char** argv)
{
    if (argc * 2 > 999)
      printf("WTF?"); 

    while(1);
}
```

```
main:                                   # @main
        push    rax
        lea     rdi, [rip + .L.str]
        xor     eax, eax
        call    printf@PLT
.L.str:
        .asciz  "WTF?"
```

The compiler removed the if condition above, and considered it to be always true.

This is only present in the C++ compiler, in the C compiler it is producing the correct code.

In GCC and MSVC compilers, this does not happen and produces the correct code.

Is this right?
(and by the way, where is while(1)? -- the compiler removed it too? 🤣 )

https://godbolt.org/z/5MWEKrKjz

**Comment by DimitryAndric** [comment]
Remove the `while(1);`. The program's behavior is undefined otherwise. You should also return a value from `main()`.

**Comment by shafik** [comment]
Duplicate of: https://github.com/llvm/llvm-project/issues/66307
