### ISSUE TITLE
[PAC][ELF] Add support for authenticated call lowering

### ISSUE THREAD

**Issue by asl** [llvm/llvm-project#83787]
Downstream commit https://github.com/access-softek/llvm-project/commit/66766f2ef8a7ce710f7b49e1780e2a4b740e4aa9 seems to be generic enough, but ELF-related tests should be added

**Comment by asl** [comment]
@kovdan01 What is left here?

**Comment by kovdan01** [comment]
> @kovdan01 What is left here?

Tests for ELF were already added in #85736, no additional ELF-specific logic is required. Closing as completed.
