### ISSUE TITLE
Clang only warns about [-Wmissing-noreturn] for functions with a void return type.

### ISSUE THREAD

**Issue by mushenoy** [llvm/llvm-project#83813]
Clang reports ```-Wmissing-noreturn``` warning only for functions with void return type. 
It doesnt seem to report the warning for functions with non-void return type.

GCC reports the warnings for both type of functions.

Sample program:
void_prog.c:
```
#include <stdlib.h>

void test ()
{
    abort();                               ;
    return;
}
```

int_prog.c:
```
#include <stdlib.h>

int test ()
{
    abort();                               ;
    return 0;
}
```

Compilation with Clang:
void_prog.c Compilation:
```
# clang -c -Wmissing-noreturn void_prog.c
void_prog.c:4:1: warning: function 'test' could be declared with attribute 'noreturn' [-Wmissing-noreturn]
{
^
1 warning generated.
```

int_prog.c Compilation:
```
# clang -c -Wmissing-noreturn int_prog.c
#
```

Compilation with GCC:
void_prog.c Compilation:
```
# gcc -c -Wmissing-noreturn void_prog.c
void_prog.c: In function test:
void_prog.c:3:6: warning: function might be candidate for attribute noreturn [-Wsuggest-attribute=noreturn]
    3 | void test ()
      |      ^~~~
```
int_prog.c Compilation:
```
# gcc -c -Wmissing-noreturn int_prog.c
int_prog.c: In function test:
int_prog.c:3:5: warning: function might be candidate for attribute noreturn [-Wsuggest-attribute=noreturn]
    3 | int test ()
      |     ^~~~
```

Compiler Versions:

```
clang version 16.0.6 
gcc (GCC) 13.2.1
```

**Comment by shafik** [comment]
clang will diagnose this with `-Wunreachable-code-return` which I think is the appropriate way to catch this. If you really want to return a value then `noteturn` is not the right approach.
