### ISSUE TITLE
[X86][AVX] Recognise out of bounds AVX2 shift amounts

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#83840]
Pulled out of #39822 which was a bit too general.

Unlike the general ISD SRA/SRL/SHL nodes, the AVX2 vector shift nodes X86ISD VSRAV/VSRLV/VSHLV handle out of bounds shift amounts:

- VSRAV clamps the unsigned shift amount to (BITWIDTH-1)
- VSRLV/VSHLV returns a zero value for unsigned shift amounts greater than (BITWIDTH-1).

So when lowering vector shifts, we should be able to fold any shift amount clamp patterns and use the X86ISD nodetypes.

e.g.

```ll
define <4 x i32> @ashr(<4 x i32> %sh, <4 x i32> %amt) {
  %elt.min.i = tail call <4 x i32> @llvm.umin.v4i32(<4 x i32> %amt, <4 x i32> <i32 31, i32 31, i32 31, i32 31>)
  %shr = ashr <4 x i32> %sh, %elt.min.i
  ret <4 x i32> %shr
}
```
-> 
```asm
ashr(int vector[4], unsigned int vector[4]):
        vpbroadcastd    xmm2, dword ptr [rip + .LCPI0_0] # xmm2 = [31,31,31,31]
        vpminud xmm1, xmm1, xmm2
        vpsravd xmm0, xmm0, xmm1
        ret
```
vs
```asm
ashr(int vector[4], unsigned int vector[4]):
        vpsravd xmm0, xmm0, xmm1
        ret
```

Logical shifts are trickier but also foldable:
```ll
define <4 x i32> @lshr(<4 x i32> %sh, <4 x i32> %amt) {
  %cmp.i = icmp ult <4 x i32> %amt, <i32 32, i32 32, i32 32, i32 32>
  %shr = lshr <4 x i32> %sh, %amt
  %0 = select <4 x i1> %cmp.i, <4 x i32> %shr, <4 x i32> zeroinitializer
  ret <4 x i32> %0
}

define <4 x i32> @lshr2(<4 x i32> %sh, <4 x i32> %amt) {
  %cmp.i = icmp ult <4 x i32> %amt, <i32 32, i32 32, i32 32, i32 32>
  %0 = select <4 x i1> %cmp.i, <4 x i32> %sh, <4 x i32> zeroinitializer
  %shr = lshr <4 x i32> %0, %amt
  ret <4 x i32> %shr
}
```

**Comment by RKSimon** [comment]
https://godbolt.org/z/W1r1c4fzY

**Comment by SahilPatidar** [comment]
@RKSimon,
I'm interested in working on this issue. Could you confirm if all the mentioned behavior regarding the AVX2 vector shift nodes (X86ISD VSRAV/VSRLV/VSHLV) and the handling of out-of-bounds shift amounts occurs in the llvm/lib/Target/X86 directory?

**Comment by RKSimon** [comment]
I expect all of this to be handled as DAG combines inside X86ISelLowering.cpp

**Comment by SahilPatidar** [comment]
What command did you use for this?

**Comment by SahilPatidar** [comment]
@RKSimon,
I am working on it, so could you please assign it to me?

**Comment by RKSimon** [comment]
I suggest you start with the SRA(X,UMIN(Y,BW-1)) case in combineShiftRightArithmetic

You should be able to use supportedVectorVarShift to detect when the target supports replacing the ISD::SRA node with X86ISD::VSRAV

**Comment by SahilPatidar** [comment]
@RKSimon,
IWhile reviewing the X86ISelLowering codebase, I encountered a scenario where the code executes the SRA operation and calls the combineShiftRightArithmetic function. However, when the following condition is met:
```c++
if (VT.isVector() || N1.getOpcode() != ISD::Constant ||
    N0.getOpcode() != ISD::SHL || !N0.hasOneUse() ||
    N0.getOperand(1).getOpcode() != ISD::Constant)
  return SDValue();
```
the code returns without performing any optimization.

My observation is that even though we are working with vectors, the code does not invoke the combineVectorShiftImm function in these cases.

I would like to understand why the code behaves this way and does not call the combineVectorShiftImm function when dealing with vectors. Could you please provide some insights into this behavior?

**Comment by RKSimon** [comment]
The code below that early-out is for a single fold (see the description comment) - just above it is the combineShiftToPMULH fold - you can put your code after combineShiftToPMULH.

**Comment by SahilPatidar** [comment]
@RKSimon 
I have been working on a particular piece of code in LLVM and encountered an unexpected behavior that I'm seeking clarification on.
```c++
APInt ShiftAmt;
SDNode *NNode = N1.getNode();
if (NNode->getOpcode() == ISD::UMIN &&
    ISD::isConstantSplatVector(NNode->getOperand(1).getNode(), ShiftAmt) && 
    ShiftAmt == VT.getScalarSizeInBits() - 1) {
  SDValue SHAmtVal = NNode->getOperand(0);
  SDLoc DL(N);
  return DAG.getNode(N->getOpcode(), DL, N->getVTList(), N0, SHAmtVal);
}
```
When running this code, I observed the following unexpected output:
```asm
vpsravd %xmm1, %xmm0, %xmm0
retq
```
I would greatly appreciate it if you could help me understand why the position of `xmm` is changing in the output.

**Comment by RKSimon** [comment]
The order looks to just be the difference between Intel and AT&T ASM ayntax

**Comment by SahilPatidar** [comment]
@RKSimon, I think some changes need to be made in select and logical shift operations.

**Comment by RKSimon** [comment]
That SRA code looks fine - I'd like to see it in a PR, and then there is the question of adding test coverage....

**Comment by SahilPatidar** [comment]
@RKSimon,
Do tests need to be changed in combine-sra.ll?

**Comment by RKSimon** [comment]
> @RKSimon, Do tests need to be changed in combine-sra.ll?

Yes

**Comment by RKSimon** [comment]
ISD::SRA handling landed at #84426 / 186565513c57cd625ea7afd7b33897adfed7e9f8

**Comment by SahilPatidar** [comment]
@RKSimon, could you please tell me what issue we're having?

**Comment by RKSimon** [comment]
Logical shift left/right both need dealing with, but those will be combined from either VSELECT or AND nodes.

**Comment by SahilPatidar** [comment]
> Logical shift left/right both need dealing with, but those will be combined from either VSELECT or AND nodes.

could you please provide an example for `AND`?

**Comment by RKSimon** [comment]
This was the kind of thing I had in mind: https://gcc.godbolt.org/z/rdh9j3ocW
