### ISSUE TITLE
Buildbot updates for Python 3.8

### ISSUE THREAD

**Issue by boomanaiden154** [llvm/llvm-project#83962]
Landing https://github.com/llvm/llvm-project/pull/78828 (as a part of https://discourse.llvm.org/t/rfc-upgrading-llvms-minimum-required-python-version/67571) caused failures on the following buildbots:
1. [x] [sanitizer-pcc64be-linux](https://lab.llvm.org/buildbot/#/builders/18/builds/15081) - emailed
2. [x] [libc-x86_64-debian-fullbuild-dbg-asan](https://lab.llvm.org/buildbot/#/builders/162/builds/51187) - @michaelrj-google @lntue @nickdesaulniers 
3. [x] [clang-ppc64be-linux-test-suite](https://lab.llvm.org/buildbot/#/builders/231/builds/20820) - emailed
4. [x] [libc-x86_64-debian-gcc-fullbuild-dbg](https://lab.llvm.org/buildbot/#/builders/250/builds/18780) - @michaelrj-google @lntue @nickdesaulniers 
5. [x] [polly-arm-linux](https://lab.llvm.org/buildbot/#/builders/56/builds/10516) - emailed
6. [x] [clangd-ubuntu-tsan](https://lab.llvm.org/buildbot/#/builders/131/builds/59442) - @ChristianKuehnel 
7. [x] [sanitizer-x86_64-linux-android](https://lab.llvm.org/buildbot/#/builders/77/builds/34771) - @vitalybuka 
8. [x] [clang-ppc64le-linux-test-suite](https://lab.llvm.org/buildbot/#/builders/230/builds/25159) - emailed
9. [x] [sanitizer-ppc64le-linux](https://lab.llvm.org/buildbot/#/builders/19/builds/24817) - emailed
10. [x] [ppc64le-lld-multistage-test](https://lab.llvm.org/buildbot/#/builders/36/builds/42792) - emailed
11. [x] [libc-x86_64-debian-dbg-runtimes-build](https://lab.llvm.org/buildbot/#/builders/225/builds/31362) - @michaelrj-google @lntue @nickdesaulniers 
12. [x] [libc-x86_64-debian](https://lab.llvm.org/buildbot/#/builders/78/builds/65860) - @michaelrj-google @lntue @nickdesaulniers 
13. [x] [libc-x86_64-debian-dbg-asan](https://lab.llvm.org/buildbot/#/builders/73/builds/62872) - @michaelrj-google @lntue @nickdesaulniers 
14. [x] [clang-ppc64le-linux-multistage](https://lab.llvm.org/buildbot/#/builders/121/builds/39265) - emailed
15. [x] [libc-x86_64-debian-fullbuild-dbg](https://lab.llvm.org/buildbot/#/builders/163/builds/51774) - @michaelrj-google @lntue @nickdesaulniers 
16. [x] [ppc64le-mlir-rhel-clang](https://lab.llvm.org/buildbot/#/builders/88/builds/71503) - emailed
17. [x] [ppc64le-flang-rhel-clang](https://lab.llvm.org/buildbot/#/builders/21/builds/92881) - emailed

These are the buildbots that I saw fail after landing the Python 3.8 upgrade ([status page](https://lab.llvm.org/buildbot/#/changes/124772). It's possible there are more failures as I only left the patch in for less than an hour before pulling it, so we'll probably have to do another round of this. I have either pinged buildbot maintainers here or emailed them with a link to this issue so that we can get things moving.

**Action needed:** Please upgrade the buildbot(s) for which you are a maintainer to Python 3.8 or newer so we can reland the change described in the RFC (and/or add additional context/a timeline on this issue/the discourse RFC thread).

**Comment by kadircet** [comment]
Issue title says 3.10, but I believe that's a typo and this should be 3.8, right?

**Comment by boomanaiden154** [comment]
> Issue title says 3.10, but I believe that's a typo and this should be 3.8, right?

Good point. Updated to reflect that the minimum version is only being bumped to 3.8.

**Comment by nickdesaulniers** [comment]
Yesterday I upgraded the libc buildbots from debian 10 to debian 12. They're now running Python 3.11.2.

**Comment by vitalybuka** [comment]
CC @fmayer

**Comment by fmayer** [comment]
Running update of the Android buildbot to Ubuntu focal (which has Python 3.8)

**Comment by fmayer** [comment]
sanitizer-x86_64-linux-android updated:

```
$ python3 --version
Python 3.8.10
```

**Comment by lei137** [comment]
The PowerPC linux LE and BE bots have been updated to use Python 3.8.18.

**Comment by DeinAlptraum** [comment]
Since all boxes on the list are ticked, is there a reason this is still open?
If not, can we repeat https://github.com/llvm/llvm-project/pull/78828 now?

**Comment by boomanaiden154** [comment]
Yes. I just realized that someone updated the `clangd-ubuntu-tsan` bot yesterday. I just need to do the actual push and see if anything else breaks again.

**Comment by boomanaiden154** [comment]
I'm going to pull this one more time as the relanding saw a couple bots fail:
* [ ] [openmp-offload-sles-build-only](https://lab.llvm.org/buildbot/#/builders/285/builds/758) - emailed, @jplehr 
* [ ] [clang-m68k-linux-cross](https://lab.llvm.org/buildbot/#/builders/192/builds/8866) - @glaubitz 
* [ ] [clang-with-thin-lto-ubuntu](https://lab.llvm.org/buildbot/#/builders/67/builds/15551) - @gkistanova 
* [ ] [clang-with-lto-ubuntu](https://lab.llvm.org/buildbot/#/builders/124/builds/10491) - @gkistanova

Action needed for the people pinged here: **Please update the buildbots for which you are listed as a maintainer to Python 3.8 so we can complete the upgrade described in the RFC.**

**Comment by jplehr** [comment]
Thanks for the ping. When this RFC was active for comments, we did not yet have this SLES bot running, so I missed the discussions, and this change caught me a bit by surprise.

I have updated the bot and triggered a build in https://lab.llvm.org/buildbot/#/builders/285/builds/779 which restored the bot status back to green.

**Comment by boomanaiden154** [comment]
Sorry about that. Thanks for getting a fix pushed so quickly!

**Comment by glaubitz** [comment]
> I'm going to pull this one more time as the relanding saw a couple bots fail:
> 
>     * [x]  [openmp-offload-sles-build-only](https://lab.llvm.org/buildbot/#/builders/285/builds/758) - emailed, @jplehr
> 
>     * [ ]  [clang-m68k-linux-cross](https://lab.llvm.org/buildbot/#/builders/192/builds/8866) - @glaubitz
> 
>     * [ ]  [clang-with-thin-lto-ubuntu](https://lab.llvm.org/buildbot/#/builders/67/builds/15551) - @gkistanova
> 
>     * [ ]  [clang-with-lto-ubuntu](https://lab.llvm.org/buildbot/#/builders/124/builds/10491) - @gkistanova
> 
> 
> Action needed for the people pinged here: **Please update the buildbots for which you are listed as a maintainer to Python 3.8 so we can complete the upgrade described in the RFC.**

The buildbot is running openSUSE Leap 15.5. Let me see whether I can install Python 3.11 without problems.

**Comment by glaubitz** [comment]
> The buildbot is running openSUSE Leap 15.5. Let me see whether I can install Python 3.11 without problems.

Upgraded the whole machine to openSUSE Tumbleweed now as there was no other way to switch the system's default Python interpreter to 3.8 or newer. Default Python version is 3.11 now.

**Comment by boomanaiden154** [comment]
@gkistanova Do you have updates on when the bots for which you're listed as a maintainer above (`clang-with-thin-lto-ubuntu` and `clang-with-lto-ubuntu`) will be updated to Python 3.8?

**Comment by boomanaiden154** [comment]
@gkistanova Bump on this. I'm going to land this on Friday as it's been about two months, these are the last two remaining bots, and checking the build logs they've been broken for weeks now due to unrelated changes.

**Comment by gkistanova** [comment]
Landing on Friday is fine. I'll update those 2 workers by then. Thanks for waiting.

**Comment by boomanaiden154** [comment]
Looks like the landing stuck this time.
