### ISSUE TITLE
[c++] error: address of vector element requested

### ISSUE THREAD

**Issue by vfdff** [llvm/llvm-project#83996]
* test: https://gcc.godbolt.org/z/z3bnbvn14
```
void testVectorComponentAccess() {
  typedef float v4sf __attribute__ ((vector_size (16)));
  static v4sf q;
  float* r = &q[0]; // expected-error {{address of vector element requested}}
}
```
For above small case, the gcc accepts, while llvm report a error, so is it a **GCC extension** ?
the above case is spilted from [expr-address-of.c](https://chromium.googlesource.com/external/github.com/kripken/emscripten-fastcomp-clang/+/refs/tags/1.30.0/test/Sema/expr-address-of.c)

**Comment by shafik** [comment]
Based on the code here: 

https://github.com/llvm/llvm-project/blob/a8cb9db5f59dc97c9b3d0370a5879539e7b233d8/clang/lib/Sema/SemaExpr.cpp#L15160-L15162

This looks to be a purposeful choice on the clang side.

CC @efriedma-quic who added the comment here: 3a1e692fed745

**Comment by frederick-vs-ja** [comment]
This was intended, see #2475 (from https://bugs.llvm.org/show_bug.cgi?id=2103).
