### ISSUE TITLE
[Clang][Module] Transitive importation as in [module.import]/7 is not fully implemented

### ISSUE THREAD

**Issue by poyaoc97** [llvm/llvm-project#84002]
Looks like Clang does transitive import as in [[module.import]/7](https://timsong-cpp.github.io/cppwp/n4868/module.import#7.sentence-2) only when the `U` is ["implicitly imported ([module.unit]/8)"](https://timsong-cpp.github.io/cppwp/n4868/module.unit#8).

Basically, I expect transitive import to work when dealing with module partitions. Right now, [this program](https://godbolt.org/z/dnbqooKPa) doesn't compile:

The primary module interface unit:
```c++
export module test;
import std;
export import :part_interface;
import :part_impl;

export void testMIU();
```
Module impl unit (the non-importable/not-a-partition one)
```c++
module test;
// OK, implicitly imports the primary module interface unit,
// and transitively imports std as expected
void testMIU() { std::println("testMIU"); }
```
A partition:
```c++
export module test:part_interface;
import std;

export void testPartition();
```
Another partition:
```c++
module test:part_impl;
import :part_interface; // should transitively import std!!
// import std; // <============ should NOT be needed

void testPartition() {
  std::println("testPartition");
} 
```

**Comment by poyaoc97** [comment]
> hmmm, I don't understand. https://timsong-cpp.github.io/cppwp/n4868/module.unit#8 explicitly says:
> 
> > A [module-declaration](https://timsong-cpp.github.io/cppwp/n4868/module.unit#nt:module-declaration) that contains neither an export-keyword nor a **[module-partition](https://timsong-cpp.github.io/cppwp/n4868/module.unit#nt:module-partition)** implicitly imports the primary module interface unit of the module as if by a [module-import-declaration](https://timsong-cpp.github.io/cppwp/n4868/module.import#nt:module-import-declaration)[.](https://timsong-cpp.github.io/cppwp/n4868/module.unit#8.sentence-1)
> 
> ...

It's really *not* about [[module.unit]/8](https://timsong-cpp.github.io/cppwp/n4868/module.unit#8). I mention it because Clang transitively import only in that case.

> ...
> is a partition, so it wouldn't fall here. Do I misunderstand anything?

Do notice how my comment says transitive importation should happen for modules that are not implicitly imported with not one but two exclamation marks!!:
```c++
import :part_interface; // should transitively import std!!
```

My issue is about Clang not importing transitively in the case above, thus unfinished implementation of [[module.import]/7](https://timsong-cpp.github.io/cppwp/n4868/module.import#7.sentence-2) which says:
> Additionally, when a [module-import-declaration](https://timsong-cpp.github.io/cppwp/n4868/module.import#nt:module-import-declaration) in **_a module unit of some module M_** imports another module unit U of M, it also imports all translation units imported by non-exported [module-import-declaration](https://timsong-cpp.github.io/cppwp/n4868/module.import#nt:module-import-declaration)s in the module unit purview of U[.](https://timsong-cpp.github.io/cppwp/n4868/module.import#7.sentence-2)

__*A module unit of some module M*__ in the paragraph above doesn't have to be the non-importable module implementation unit described by [[module.unit]/8](https://timsong-cpp.github.io/cppwp/n4868/module.unit#8) (and in this case the **_"U"_** is the implicitly imported primary module interface unit).

CC @DanielaE and @iains just to be extra sure.

**Comment by DanielaE** [comment]
@poyaoc97 is right here. **[module.import]/7** is key!

@ChuanqiXu9 this is **not** about the **implicit import** of the _primary module interface_ that applies to the _module declaration_ of _module implementation units_.

**Comment by ChuanqiXu9** [comment]
Got it. Thanks. I'll try to look into this.

**Comment by poyaoc97** [comment]
Thanks for the confirmation. 

I have fixed this locally. If you’d rather review my code, I can upload it when I’m home~

**Comment by ChuanqiXu9** [comment]
> Thanks for the confirmation.
> 
> I have fixed this locally. If you’d rather review my code, I can upload it when I’m home~

Thanks. But I have fixed it locally already. Also I noticed that the existing mechanism for transitive import for the implicit import of the implementation unit is not good. It looks like it can't work if we add the depth of transitive imports. In other words, it doesn't make it recursively.

**Comment by poyaoc97** [comment]
Hmm… that’s indeed the case.
