### ISSUE TITLE
LLVM 18.1.0 release have rc suffix

### ISSUE THREAD

**Issue by SuperSodaSea** [llvm/llvm-project#84168]
It seems that the LLVM 18.1.0 release still have an rc suffix:

<https://github.com/llvm/llvm-project/blob/461274b81d8641eab64d494accddc81d7db8a09e/llvm/CMakeLists.txt#L27-L29>

The rc suffix will show up in the version info:

```
$ clang -v
clang version 18.1.0rc
```

It also shows up in the documentation:

<https://releases.llvm.org/18.1.0/tools/clang/docs/ReleaseNotes.html>

> Clang 18.1.0rc documentation

Is this intentional or a mistake?

**Comment by Endilll** [comment]
> Is this intentional or a mistake?

IIRC 17.0.0 had the same issue, and was quickly followed by 17.0.1.

**Comment by tstellar** [comment]
Sorry I missed this. I'm still deciding whether to do an immediate 18.1.1 or wait two weeks as currently planned.

**Comment by Endilll** [comment]
@tstellar In case it's important for your decision, Clang 18 seems to have a serious CodeGen regression: https://github.com/llvm/llvm-project/issues/84178

**Comment by debohman** [comment]
I noticed this, too. I caught it while cmake was running, so I just fixed the `llvm/CMakeLists.txt` and then reran cmake from scratch. It is building now.

**Comment by finagolfin** [comment]
I am seeing this in the upcoming Termux release too, termux/termux-packages#19399, which runs natively on Android devices.
```
> clang --version
clang version 18.1.0rc
Target: aarch64-unknown-linux-android24
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/bin
> ls -l /data/data/com.termux/files/usr/lib/libLLVM*so*
lrwxrwxrwx 1 u0_a318 u0_a318        22 Mar  7 08:03 /data/data/com.termux/files/usr/lib/libLLVM-18rc.so -> libLLVM.so.18.1rc
-rw------- 1 u0_a318 u0_a318 114521088 Mar  6 21:27 /data/data/com.termux/files/usr/lib/libLLVM.so
```

**Comment by MehdiChinoune** [comment]
A simple workaround is to pass `-DLLVM_VERSION_SUFFIX=""` to cmake.

**Comment by andypost** [comment]
It was fixed via https://github.com/llvm/llvm-project/commit/b92012c777e602d557124583651313a0afa33484 in 18.1.1
