### ISSUE TITLE
clang-18: -ffat-lto-objects gives multiple definition of `.str.llvm.0'

### ISSUE THREAD

**Issue by stsp** [llvm/llvm-project#84167]
I made the bug reproducer.
Please do the following:

1. git clone https://github.com/dosemu2/fdpp.git
2. cd fdpp
3. git checkout lto-bug
4. ./bug.sh

Build process ending with:

/usr/bin/ld: /tmp/lto-llvm-00e3b8.o:(.rodata.str1.1+0x70): multiple definition of `.str.2.llvm.0'; /tmp/lto-llvm-98e51f.o:(.rodata.str1.1+0x5b): first defined here

Removing -ffat-lto-objects avoids the
problem, but unfortunately rpmbuild
in fedora forces this option.

**Comment by nikic** [comment]
cc @ilovepi for fat LTO

**Comment by ilovepi** [comment]
Is this happening at head? I think https://github.com/llvm/llvm-project/pull/83159 should have fixed this. While I didn't run into this for Fuchsia, when trying to enable FatLTO in our Toolchain builds I hit this. Basically the way we set module flags was inconsistent with what we do outside of FatLTO.

**Comment by nikic** [comment]
The reproducer doesn't work for me, fails with:
> 2024-03-07 10:11:21,731 [ERROR] koji: Unknown command: install

And I'm not sure how I would test build setup against a different clang version. @stsp Is that possible somehow?

We can at least backport that PR though.

/cherry-pick 7d8b50aaab8e0f935e3cb1f3f397e98b9e3ee241

**Comment by stsp** [comment]
@nikic can you prepare the rpm
with the patched version of clang?
I'll test locally.
Is this an option?

**Comment by nikic** [comment]
@stsp I created a scratch build with this patch: https://koji.fedoraproject.org/koji/taskinfo?taskID=114603529

**Comment by stsp** [comment]
Thanks!
I confirm that the problem is now fixed.

**Comment by nikic** [comment]
Awesome, thanks!

**Comment by ilovepi** [comment]
Thanks @nikic I didn't realize we could still backport.
