### ISSUE TITLE
`vpdpwssd` instruction not generated despite giving better performance than `vpmaddwd+vpaddd` expansion

### ISSUE THREAD

**Issue by bjacob** [llvm/llvm-project#84182]
Filing this Issue with two Compiler Explorer testcases - one in LLVM IR and the other in C.

# LLVM IR testcase

Compiler Explorer link: https://godbolt.org/z/3Wf1cfEo1

Problem: when the parent function has `"target-cpu"="znver4"`, the `@llvm.x86.avx512.vpdpwssd.512` intrinsic fails to compile to the expected AVX-512-VNNI `vpdpwssd` instruction and instead generates a (`vpmaddwd`, `vpaddd`) fallback implementation.

The problem only reproduces with `"target-cpu"="znver4"` and not with `"target-cpu"="cascadelake"` or when `"target-cpu"` is simply omitted, as shown in the Compiler Explorer link.

Inlining the LLVM IR testcase here for completeness:

```llvm
; Testing with "target-cpu"="znver4" in attributes #0 below. Nothing else changes between testcases.

define dso_local <8 x i64> @foo(<8 x i64> noundef %0, <8 x i64> noundef %1, <8 x i64> noundef %2) local_unnamed_addr #0 {
  %4 = bitcast <8 x i64> %0 to <16 x i32>
  %5 = bitcast <8 x i64> %1 to <16 x i32>
  %6 = bitcast <8 x i64> %2 to <16 x i32>
  %7 = tail call <16 x i32> @llvm.x86.avx512.vpdpwssd.512(<16 x i32> %4, <16 x i32> %5, <16 x i32> %6)
  %8 = bitcast <16 x i32> %7 to <8 x i64>
  ret <8 x i64> %8
}

declare <16 x i32> @llvm.x86.avx512.vpdpwssd.512(<16 x i32>, <16 x i32>, <16 x i32>) #1

declare void @llvm.dbg.value(metadata, metadata, metadata) #2

attributes #0 = { mustprogress nofree norecurse nosync nounwind willreturn memory(none) uwtable "min-legal-vector-width"="512" "no-trapping-math"="true" "stack-protector-buffer-size"="8"
  "target-cpu"="znver4" "target-features"="+adx,+aes,+avx,+avx2,+avx512bf16,+avx512bitalg,+avx512bw,+avx512cd,+avx512dq,+avx512f,+avx512ifma,+avx512vbmi,+avx512vbmi2,+avx512vl,+avx512vnni,+avx512vpopcntdq,+bmi,+bmi2,+clflushopt,+clwb,+clzero,+crc32,+cx16,+cx8,+evex512,+f16c,+fma,+fsgsbase,+fxsr,+gfni,+invpcid,+lzcnt,+mmx,+movbe,+mwaitx,+pclmul,+pku,+popcnt,+prfchw,+rdpid,+rdpru,+rdrnd,+rdseed,+sahf,+sha,+shstk,+sse,+sse2,+sse3,+sse4.1,+sse4.2,+sse4a,+ssse3,+vaes,+vpclmulqdq,+wbnoinvd,+x87,+xsave,+xsavec,+xsaveopt,+xsaves" }
attributes #1 = { mustprogress nocallback nofree nosync nounwind willreturn memory(none) }
attributes #2 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
```

# C testcase

Compiler Explorer link: https://godbolt.org/z/z6xxf35hG

Problem: when compiling with `-march=znver4`, the `_mm512_dpwssd_epi32` intrinsic fails to compile to the expected AVX-512-VNNI `vpdpwssd` instruction and instead generates a (`vpmaddwd`, `vpaddd`) fallback implementation.

The problem only reproduces with `-march=znver4` and not with `-march=cascade` or when `-march` is simply omitted and individual AVX-512 features are passed instead, as shown in the Compiler Explorer link.

Inlining the C testcase here for completeness:

```c
#include <immintrin.h>

__m512i foo(__m512i x, __m512i y, __m512i z) {
    return _mm512_dpwssd_epi32(x, y, z);
}
```

**Comment by bjacob** [comment]
The problem is avoided by adding the `"tune-cpu"="generic"` attribute in the LLVM IR testcase, or equivalently passing the `-mtune=generic` in the C testcase.

This points to an issue with the scheduling model for `znver4` ?

**Comment by bjacob** [comment]
This comes from practical matrix multiplication kernels and benchmarks show when the fallback from  `vpdpwssd` to (`vpmaddwd`, `vpaddd`) occurs, this results in the matrix multiplication kernel running about 1.45x slower on my Zen4-architecture CPU (`AMD Ryzen 9 7950X3D`).

Single-thread `i16xi16->i32` matrix multiplication performance on this CPU:

Matrix multiplication kernel | Gop/s
--- | ---
With `vpdpwssd` | 336
With (`vpmaddwd`, `vpaddd`) | 231

The C source code for this kernel is here for completeness: https://github.com/openxla/iree/blob/f34e534a16f9cfe328f0a513ef474fd44af29a30/runtime/src/iree/builtins/ukernel/arch/x86_64/mmt4d_x86_64_avx512_vnni.c#L138-L171

**Comment by bjacob** [comment]
This is also a regression that occurred between LLVM 16 (good) and LLVM 17 (bad).

**Comment by bjacob** [comment]
If I understand correctly, this is the part of the scheduler model that affects VPDPWSSD? https://github.com/llvm/llvm-project/blob/f448b8ec03bbd0e1b47d56f461b324fb2af8c113/llvm/lib/Target/X86/X86ScheduleZnver4.td#L1568-L1577

**Comment by bjacob** [comment]
Naive question: the measure of cost that is the most important to practical code using this kind of arithmetic instruction, tends to be throughput rather than latency. I'm confused how is throughput taken into account here?

**Comment by bjacob** [comment]
Completed bisection, points to https://github.com/llvm/llvm-project/commit/8f7f9d86a7555263ef08fded15a6b778d796ec3f / https://reviews.llvm.org/D148980. 

@RKSimon WDYT, is this commit merely exposing the above-discussed schedulign model issue?

```
(HEAD) ~/iree/third_party/llvm-project git bisect good
8f7f9d86a7555263ef08fded15a6b778d796ec3f is the first bad commit
commit 8f7f9d86a7555263ef08fded15a6b778d796ec3f
Author: Luo, Yuanke <yuanke.luo@intel.com>
Date:   Fri Apr 21 19:28:58 2023 +0800

    [X86] Machine combine vnni instruction.
    
    "vpmaddwd + vpaddd" can be combined to vpdpwssd and the latency is
    reduced after combination. However when vpdpwssd is in a critical path
    the combination get less ILP. It happens when vpdpwssd is in a loop, the
    vpmaddwd can be executed in parallel in multi-iterations while vpdpwssd
    has data dependency for each iterations. If vpaddd is in a critical path
    while vpmaddwd is not, it is profitable to split vpdpwssd into "vpmaddwd
    + vpaddd".
    This patch is based on the machine combiner framework to acheive decision
    on "vpmaddwd + vpaddd" combination. The typical example code is as
    below.
    ```
    __m256i foo(int cnt, __m256i c, __m256i b, __m256i *p) {
    
        for (int i = 0; i < cnt; ++i) {
            __m256i a = p[i];
            __m256i m = _mm256_madd_epi16 (b, a);
            c = _mm256_add_epi32(m, c);
        }
    
        return c;
    }
    ```
    
    Differential Revision: https://reviews.llvm.org/D148980

 llvm/include/llvm/CodeGen/MachineCombinerPattern.h |   3 +
 llvm/include/llvm/CodeGen/TargetInstrInfo.h        |   7 +
 llvm/lib/CodeGen/MachineCombiner.cpp               |  34 +-
 llvm/lib/Target/X86/X86InstrInfo.cpp               | 137 +++++
 llvm/lib/Target/X86/X86InstrInfo.h                 |  28 +
 llvm/test/CodeGen/X86/avx512vnni-combine.ll        |  31 +-
 llvm/test/CodeGen/X86/avxvnni-combine.ll           | 589 ++++++++++++++-------
 7 files changed, 618 insertions(+), 211 deletions(-)
```

**Comment by RKSimon** [comment]
yes - that patch is fine, its just a lot of accuracy issues with the znver4 model

**Comment by bjacob** [comment]
> Yes - looking at uops.info it suggests that the entire override block is unnecessary (so it'd use the default WriteVecIMul* classes) - which uops.info + Agner ALSO says should be FPU0/1 not FPU0/3 (which was the znver3 port mapping).

Thanks a ton for these pointers -- I'll try that.  Next naive question (sorry): it seems tempting to try to systematically import the tables from uops.info or Agner into LLVM x86 scheduling models. But surely this has been tried before? Do you know of past attempts or reasons why that's not a good idea ?  Either way I'll look into the specific fix you suggested here but I was curious about how one generalizes from there.

**Comment by RKSimon** [comment]
The problem is none of the sources are 100% correct / complete so scraping isn't a great idea - auto comparison with the uops.info xml is possible though, I played with getting converting it to llvm-exegesis capture data a while ago as llvm-exegesis analysis mode can then validate against the scheduler model, but I think I gave up when I hit the the instruction mapping @boomanaiden154 might have some ideas?

**Comment by bjacob** [comment]
Removing the override block does fix my issue here, `vpdpwssd` gets generated. However, it also causes some existing tests to fail (`tools/llvm-mca/X86/Znver4/resources-avxvnni.s` and a few others in that directory). That is because falling back on `WriteVecIMul` causes the latency to change from 4 to 3. According to uops.info, the current scheduling table is correct about the latencies: `vpmaddwd` has 3 and the instructions that the the override block applies to do have 4 (`vpdpwssd`, `vmpadd52huq`) as in the override block.

If I keep the override block but just change `Zn4FPFMisc01` to `Zn4FPVMul01` then that doesn't fix my issue.

So, to summarize:
* It really is true that `vpmaddwd` has lower latency than other instructions that are preferrable over it for performance (3 vs 4).
* We need the override block at least to document the precise latencies for consumers who care about that (such as `llvm-mca`).
* But this example shows that latency isn't always the metric to decide instruction selection.
* How do we convey that `vpdpwssd` is preferable to the `vpmaddwd + vpaddd` pair despite having higher latency? Is the current instruction selection logic simply omitting the cost of the 2nd `vpaddd` instruction here ? If there wasn't that second instruction, then `vpmaddwd` would indeed be preferable.

**Comment by bjacob** [comment]
Here is what `llc -debug` says while performing the rewrite of `vpdpwssd` to `vpmaddwd + vpaddd`:

```
Machine InstCombiner: vpdpwssd_test
Combining MBB 
Computing MinInstr trace through %bb.0
  pred for %bb.0: null
  succ for %bb.0: null

Depths for %bb.0:
      0 Instructions
0       %2:vr512 = COPY $zmm2
0       %1:vr512 = COPY $zmm1
0       %0:vr512 = COPY $zmm0
0       %3:vr512 = VPDPWSSDZr %0:vr512(tied-def 0), %1:vr512, %2:vr512
4       $zmm0 = COPY %3:vr512
4       RET 0, $zmm0
Heights for %bb.0:
      2 Instructions
     1c @ Zn4AGU012 (1 ops x12)
     1c @ Zn4BRU01 (1 ops x18)
     1c @ Zn4FP (4 ops x6)
     2c @ Zn4FPAES01 (4 ops x18)
     2c @ Zn4FPCLM01 (4 ops x18)
     2c @ Zn4FPFMisc01 (4 ops x18)
     1c @ Zn4FPFMisc0123 (4 ops x9)
     2c @ Zn4FPFMul01 (4 ops x18)
     1c @ Zn4FPU0123 (4 ops x9)
     2c @ Zn4FPVAdd01 (4 ops x18)
     1c @ Zn4FPVAdd0123 (4 ops x9)
     1c @ Zn4FPVMisc0123 (4 ops x9)
     1c @ Zn4Int (2 ops x4)
     1c @ Zn4LSU (1 ops x12)
     1c @ Zn4Load (1 ops x12)
4       0       RET 0, $zmm0
4       0       $zmm0 = COPY %3:vr512
4       4       %3:vr512 = VPDPWSSDZr %0:vr512(tied-def 0), %1:vr512, %2:vr512
4       4       %0:vr512 = COPY $zmm0
4       4       %1:vr512 = COPY $zmm1
4       4       %2:vr512 = COPY $zmm2
%bb.0 Live-ins: XMM0@4 XMM1@4 XMM2@4
Critical path: 4
  Dependence data for %3:vr512 = VPDPWSSDZr %0:vr512(tied-def 0), %1:vr512, %2:vr512
        NewRootDepth: 3 RootDepth: 0
        NewRootLatency: 1       RootLatency: 4
        RootSlack: 0 SlackIsAccurate=1
        NewRootDepth + NewRootLatency = 4
        RootDepth + RootLatency + RootSlack = 4
          It IMPROVES PathLen because
                NewCycleCount = 4, OldCycleCount = 4
                Resource length before replacement: 4 and after: 2
                  As result it IMPROVES/PRESERVES Resource Length
Invalidate %bb.0 MinInstr height.
Invalidate %bb.0 MinInstr depth.
********** X86 cmov Conversion : vpdpwssd_test**********
```

**Comment by bjacob** [comment]
The logic as stated in that log seems to be ignoring the dependency between the produced `vpmaddwd` and the consumer `vpaddd`. Indeed, its stated rational for the rewrite is `It IMPROVES PathLen because ... Resource length before replacement: 4 and after: 2 ... As result it IMPROVES/PRESERVES Resource Length`.

I found this comment explaining the concept of resource length:
https://github.com/llvm/llvm-project/blob/04bbbba271ebe4c2421f34a4fbf34c328df9f111/llvm/include/llvm/CodeGen/MachineTraceMetrics.h#L287-L298

So resource length is not modelling the dependency in the `vpmaddwd + vpaddd` chain.

Secondarily, leaving that aside, I don't understand where the value 2 comes from, since `vpmaddwd` alone has latency 3.  The value 2 is the max latency of the `vpaddd`. Is it counting only that?

**Comment by bjacob** [comment]
I would like to discuss the commit identified above by `git bisect`: https://github.com/llvm/llvm-project/commit/8f7f9d86a7555263ef08fded15a6b778d796ec3f

1. It is concerned about the dependency in the case back-to-back accumulation on the same accumulator in a loop.  But my above testcase has no loop and only a single intrinsic, so this can't, in itself, justify a change to how it's compiled.
2. The loop given as example in the commit message of https://github.com/llvm/llvm-project/commit/8f7f9d86a7555263ef08fded15a6b778d796ec3f has a data dependency that seems artificially exacerbated by using only a single accumulator register, which puts emphasis on instruction latency. But in real optimized numerical code, one would generally tile/unroll the *caller*'s loops to compute multiple more results in parallel; e.g. with 8x unrolling the loop body would now have 8 mutually-independent `vpdpwssd` instructions on separate accumulators, so even at a throughput of 2 per cycle, the 4-cycle latency would not be felt anymore. The general idea here is that *emphasis on latency is generally a smell that the focus is on an artificial/suboptimal test case*.
3. I wonder if there is some Intel-specific assumption baked in the logic here, outside of the scheduling model. Specifically, CPUs often have short-circuit special cases for back-to-back multiply-add instructions on the same accumulator, bypassing the register file. As a result, as a detail of each CPU, the cost of an accumulator dependency can be lower than it would appear from a general scheduling model that doesn't account for that (and I don't see where the current scheduling model accounts for that, so perhaps that's what's missing?).

**Comment by bjacob** [comment]
Sent https://github.com/llvm/llvm-project/pull/84347 for review.

**Comment by RKSimon** [comment]
CC @LuoYuanke @phoebewang This was reported on znver4 but I'm not convinced its working properly on any VNNI AVX512 target where VPDPWSSD is (always?) better than VPMADDWD+VPADDD?

**Comment by topperc** [comment]
If I recall correctly the report that added the machine combiner change was related to the compiler combining vpmaddwd+vpadd into vpdwssd. If the user used the vpdwssd intrinsic directly should we trust them and never break it?

**Comment by phoebewang** [comment]
cc @williamweixiao. @LuoYuanke is not working on X86 now.

> I'm not convinced its working properly on any VNNI AVX512 target where VPDPWSSD is (always?) better than VPMADDWD+VPADDD?

According to D148980's description, it solves the data dependency of following VPDPWSSD instructions. And the test cases in the patch also demonstrated it (The fisrt VPDPWSSD is not split).

Given the single `vpdpwssd` always been split on znver4. I'm guessing znver4's scheduler model may indicate `VPMADDWD+VPADDD` always better than `VPDPWSSD`?

> This comes from practical matrix multiplication kernels and benchmarks show when the fallback from `vpdpwssd` to (`vpmaddwd`, `vpaddd`) occurs, this results in the matrix multiplication kernel running about 1.45x slower on my Zen4-architecture CPU (`AMD Ryzen 9 7950X3D`).

We once noticed a similar issue. Our analysis showed it's caused by the following machine instructions scheduling instead of spliting here. Maybe the same reason here?

**Comment by bjacob** [comment]
> Given the single vpdpwssd always been split on znver4.

My single `vpdpwssd` testcase originally attached here was not split priot to D148980, which is why my `git bisect` pointed to D148980 as the point of regression.

The znver4 scheduler model gives `vpmaddwd` *alone* as slightly better than `vpdpwssd`, but it does not give `vpmaddwd + vpaddd` as better than `vpdpwssd` (latency 3 vs 4). In the above https://github.com/llvm/llvm-project/issues/84182#issuecomment-1981594856 I found that `-debug` indicated that it only found it to be "better" in terms of "resource length" but then in the next comment I looked up the definition of "resource length" in the next comment above and learned that it didn't model dependency between instructions. Also, even so, I don't understand how it even arrived at the value 2, since `vpmaddwd` alone has latency 3.

> We once noticed a similar issue. Our analysis showed it's caused by the following machine instructions scheduling instead of spliting here. Maybe the same reason here?

My matrix multiplication kernels make use of a large portion of the 32 available avx-512 registers to have a high degree of mutual independence between instruction (the loop body has 16 consecutive mutually independent `vpdpwssd` on 16 separate accumulator `zmm` registers) so they are completely immune to instruction latency. So the kind of consideration in D148980 is not possibly going to help here, and splitting `vpdpwssd` into `vpmaddwd + vpaddd` is not going to improve performance in any scheduling.

**Comment by FreddyLeaf** [comment]
> the loop body has 16 consecutive mutually independent vpdpwssd on 16 separate accumulator zmm registers

They are independent, do they have inter-iteration loop dependency? If so, the spitting can help `vpmaddwd`s of inter-iteration independent comparing to inter-iteration `vpdpwssd`

**Comment by bjacob** [comment]
There is inter-iteration dependency, since each iteration uses again the same 16 zmm accumulator registers. But the pipeline in any x86 CPU that I know of is already fully utilized, so there is no room for improvement that I can see.

**Comment by phoebewang** [comment]
> My single `vpdpwssd` testcase originally attached here was not split prior to D148980, which is why my `git bisect` pointed to D148980 as the point of regression above ([#84182 (comment)](https://github.com/llvm/llvm-project/issues/84182#issuecomment-1981272918))

By always I meant always on znver4, which implies the differece comes from scheduler model difference.

> The znver4 scheduler model gives `vpmaddwd` _alone_ as slightly better than `vpdpwssd` (latency 3 vs 4), but it does not give `vpmaddwd + vpaddd` as better than `vpdpwssd`. In the above [#84182 (comment)](https://github.com/llvm/llvm-project/issues/84182#issuecomment-1981594856) I found that `-debug` indicated that it only found it to be "better" in terms of "resource length" but then in the next comment [#84182 (comment)](https://github.com/llvm/llvm-project/issues/84182#issuecomment-1981604600) I looked up the definition of "resource length" and learned that it didn't model dependency between instructions.

How to calculate scheduler model is another topic. And I agree the method may be also target related. We can either invent a new formula works for both, or simply add a Tuning flag for znver4 to disable the optimization here.

> Also, even so, I don't understand how it even arrived at the value 2, since `vpmaddwd` alone has latency 3.

I don't know either. It looks to me it comes from the framework of MachineCombiner, not specific to the patch.

> This is really a generic idea, that ISAs get multiply-accumulate instructions and that authors of matrix multiplication kernels just put as many as they can side by side given the number of available registers, and hit peak performance. The logic in D148980 flies in the face of basically all the SIMD ISA and matrix multiplication kernel design of the past 15 years...

I doubt how generic it is in practice. Our experience is D148980 helped with some workloads and didn't bring regressions on others as far as I have known.
I took a look at you code, I think the key you said "a large portion of the 32 available avx-512 registers" is achieved by `IREE_UK_UNROLL`. It's just not a typical scenarios D148980 works for.
And since you have manipulated the loop unroll, it's nature to suggest another approach that to design a switch for this optimization and turn it off explicitly in your scenario.

**Comment by bjacob** [comment]
> I took a look at you code, I think the key you said "a large portion of the 32 available avx-512 registers" is achieved by IREE_UK_UNROLL. It's just not a typical scenarios D148980 works for.

Yes, the IREE_UK_UNROLL (which as a macro expands to `pragma clang unroll(full)`) ensures that this loop expands into a block of 16 independent `vpdpwssd`. A typical matmul kernel would be written in an already-unrolled form, with these 16 intrinsics.

I thought that I could simply rely on the compiler to perform this repetitive task, and that that shouldn't make any difference to the final object code. Also, writing it as an unrolled loop allows me to easily generate variants for other values of `M0` than 16.

Would you view my use case differenly if it was written in a manually unrolled form instead ?

**Comment by bjacob** [comment]
Regarding the importance of the workload at hand:
- Matrix multiplication, in general, is a particularly important workload that often dominates profiles.
- My particular matrix multiplication kernel here is just one implementation but you could look at any other matrix multiplication kernel and it would be the same, up to details like the above IREE_UK_UNROLL thing.

For example, here is a source file from one of my favorite competitors, XNNPACK:
https://github.com/google/XNNPACK/blob/master/src/qs8-gemm/MRx16c8-avx512vnni.c.in#L146-L148
In these lines you can see the exact same idea as in my kernel, except that instead of relying on unrolling within the C compiler to generate these mutually independent instructions, it is doing the same in a python-based code generator, so from the point of view of the C compiler it will be hand-unrolled code.

I could go browse the code in literally any other serious matrix multiplication library and the result would be the same, because the design of a matrix multiplication kernel is essentially dictated by the SIMD ISA, there isn't much for the author to invent, except for these tools to generate repetitive code such as XNNPACK's python preprocessor, or my reliance on pragma unroll.

**Comment by phoebewang** [comment]
I'm not saying your scenario is not important or do nothing with it.
My point is the optimization is not in a wrong direction as you think but rationale for its original targets.
So we need to research the method for coexistence instead of one replace another.

**Comment by boomanaiden154** [comment]
> The problem is none of the sources are 100% correct / complete so scraping isn't a great idea - auto comparison with the uops.info xml is possible though, I played with converting it to llvm-exegesis capture data a while ago as llvm-exegesis analysis mode can then validate against the scheduler model, but I think I gave up when I hit the the instruction mapping @boomanaiden154 might have some ideas?

No major ideas there. I haven't really touched any of the instruction benchmarkng/analysis mode parts of exegesis. Theoretically we should be able to collect all the data with exegesis (assuming there's someone to actually get the capture), but it might need some more work in some cases. One big addition I think would be using blocking instructions instead of uop counters, especially for AMD CPUs (which don't really have good uop counters from what I understand), and at least the current Intel e-core architectures like Gracemont (at least from what I understand). Uops.info also has the advantage of doing things in kernel space which not only gives data for privileged instructions, but also reduces noise. I've done some work on that within exegesis so it produces more accurate data (like the middle half repetition mode and validation counters to see if things are out of whack), but there are just some inherent disadvantages to doing user-space benchmarking.

Having a conversion script would be good. I might try and spend some time on this at some point (wouldn't be until the summer though) as I'd be interested in improving the accuracy of llvm-mca (and instruction scheduling on top), but can't guarantee that will be a higher priority.

Either way, we should probably discuss this further at EuroLLVM (assuming you're going to be there)(maybe a round table?) so we can maybe setup a roadmap/some directions to improve the scheduling models.

**Comment by RKSimon** [comment]
> Having a conversion script would be good. I might try and spend some time on this at some point (wouldn't be until the summer though) as I'd be interested in improving the accuracy of llvm-mca (and instruction scheduling on top), but can't guarantee that will be a higher priority.

Cheers - I'm going to try and cleanup the trivial script I have so far and post it to my llvm-scripts https://github.com/RKSimon/llvm-scripts repro

**Comment by ganeshgit** [comment]
> I'm not saying your scenario is not important or do nothing with it. My point is the optimization is not in a wrong direction as you think but rationale for its original targets. So we need to research the method for coexistence instead of one replace another.

@RKSimon mentioned, I would prefer having a Feature bit  and enable it under SubTargets at will and skip the code. I will submit a patch for AMD zen4.

**Comment by venkataramananhashkumar** [comment]
Currently splitting of vpdpwssd instruction into vpmaddwd + vpaddd is disabled for Znver4 Target.  This is just work around as of now. The splitting is needed for Znver4 target also when there are no enough independent vpdpwssd  instructions within an iteration of the loop as in D148980.  Also It is needed in cases where one vpdpwssd  is feeding to another forming a chain.   

So the costing model in machine combiner needs to be improved to handle cases where splitting is needed.
