### ISSUE TITLE
[ADT] Add APIntOps::mulhs / APIntOps::mulhu

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#84207]
- [ ] Move implementations from SelectionDAG.cpp FoldValue into APInt.h APIntOps
https://github.com/llvm/llvm-project/blob/deff460b46dfcc8d6d5917a2b78c0d52edbe4afb/llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp#L6012-L6016
https://github.com/llvm/llvm-project/blob/deff460b46dfcc8d6d5917a2b78c0d52edbe4afb/llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp#L6018-L6022

- [ ] Add APIntTest unit test coverage
- [ ] Update DivisionByConstantTest.cpp (this might require the lhs/rhs operands to be extended to the same bitwidth)
- [ ] Update KnownBitsTest.cpp to use APIntOps::mulhs/u in exhaustive tests
- [ ] Update mlir ArithOps.cpp + SPIRVCanonicalization.cpp to use APIntOps::mulhs/mulhu

**Comment by Atousa** [comment]
@RKSimon I am interested in working on this issue.

**Comment by EugeneZelenko** [comment]
@Atousa: Just create pull request and mention it on this page.

**Comment by Sh0g0-1758** [comment]
Hey there, I am also interested in working on this. I will link a PR soon.

**Comment by Atousa** [comment]
@Sh0g0-1758 this is assigned to me and I am working on it.

**Comment by Sh0g0-1758** [comment]
Hm... I saw no PR on this so thought of working on it. Anyways, if you do not wish to collaborate, that is fine. Please link a PR and I will close mine. Though, @RKSimon, I suppose there is no harm in 2 people working on same issue.

**Comment by Sh0g0-1758** [comment]
Just out of curiosity, @RKSimon, in the 4th task, you mentioned updating `KnownBitsTest.cpp` but In it, we are using KnownBits::mul. I don't think I was supposed to update it, so could you please clarify as to what you meant?

**Comment by RKSimon** [comment]
> Just out of curiosity, @RKSimon, in the 4th task, you mentioned updating `KnownBitsTest.cpp` but In it, we are using KnownBits::mul. I don't think I was supposed to update it, so could you please clarify as to what you meant?

I meant the APInt reference version in the exhaustive tests

https://github.com/llvm/llvm-project/blob/deff460b46dfcc8d6d5917a2b78c0d52edbe4afb/llvm/unittests/Support/KnownBitsTest.cpp#L540-L543

**Comment by RKSimon** [comment]
BTW @Sh0g0-1758 I thought @Atousa was working on this ticket?

**Comment by Sh0g0-1758** [comment]
Well yeah, she still can, I don't mind closing my PR. I guess this sums it up : https://github.com/llvm/llvm-project/issues/84207#issuecomment-1986753981

**Comment by RKSimon** [comment]
OK - 3 days is a bit short, especially for good first issues where new contributors might still be getting up to speed.

We typically recommend at least 7 days between pings on reviews that have gone quiet, we should probably have a similar recommendation here.

Glad you're keen to help :)

**Comment by Sh0g0-1758** [comment]
Ah sure thing. Will keep that in mind from now on.

**Comment by Atousa** [comment]
> BTW @Sh0g0-1758 I thought @Atousa was working on this ticket?

Yes I am woking on it.

**Comment by Atousa** [comment]
@RKSimon @jayfoad, this task has been assigned to me. As we try to foster a healthy collaborative community within LLVM, it's crucial that we adhere to the code of conduct. I'm puzzled by why this individual continues to work on the task despite my clear communication that it's not meant to be a collaborative effort. I intend to bring this matter to  @AaronBallman's attention to prevent similar incidents from occurring in the future within the LLVM community. Please continue the conversation on this matter here: https://github.com/llvm/llvm-project/pull/80939

**Comment by Sh0g0-1758** [comment]
No worries. I will close my PR. Sorry for the inconvenience.

**Comment by RKSimon** [comment]
Thank you.

I had not expected the amount of interest in the good-first-issue tickets that I created, in the past such tickets have been ignored for months, my advice is in future to ensure that you have been tagged as assignee before beginning anything more substantive than triage work on a ticket. I intend to create more good-first-issue tickets as there is obviously interest at the moment, I just ask that everyone works on only one (or two) issues at once - please don't accumulate too many assigned tickets at once.

@Atousa was the assignee for #84207 and should be given a reasonable amount of time to create their own PR - as I said previously, typically about 7 days to respond to 'ping' request-for-update messages.

**Comment by Sh0g0-1758** [comment]
Yes, I understand. I just saw it as an easy fix and gave a patch. I guess what really went wrong was my misinterpretation of the below message as an approval for my view on the topic ie. To go ahead with my PR but to keep this in mind in the future. 

> OK - 3 days is a bit short, especially for good first issues where new contributors might still be getting up to speed.
> 
> We typically recommend at least 7 days between pings on reviews that have gone quiet, we should probably have a similar recommendation here.
> 
> Glad you're keen to help :)
