### ISSUE TITLE
[ADT] Add APIntOps::avgfloors/avgflooru/avgceils/avgceilu

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#84211]
- [ ] Move implementations from SelectionDAG.cpp FoldValue into APInt.h APIntOps
https://github.com/llvm/llvm-project/blob/deff460b46dfcc8d6d5917a2b78c0d52edbe4afb/llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp#L6024-L6047
- [ ] Add APIntTest unit test coverage

**Comment by Atousa** [comment]
@RKSimon I am interested in working on this issue. Please assign it to me.

**Comment by EugeneZelenko** [comment]
@Atousa: Just create pull request and mention it on this page.
