### ISSUE TITLE
[Support] Investigate making KnownBits::abdu optimal

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#84212]
https://github.com/llvm/llvm-project/blob/ffe41819e58365dfbe85a22556c0d9d284e746b9/llvm/unittests/Support/KnownBitsTest.cpp#L386-L391

Investigate if we can make the implementation optimal (checkOptimalityBinary)

**Comment by aamod-wick** [comment]
HI @RKSimon can you please direct me to any reference material for this issue ??

**Comment by RKSimon** [comment]
There isn't any really :( You will need a good understanding of the typical bit twiddling patterns.

If you edit checkCorrectnessOnlyBinary -> checkOptimalityBinary, rebuild and run:
```
unittests\Support\SupportTests --gtest_filter=KnownBitsTest.BinaryExhaustive
```
You will get an error dump of all the cases where the abdu knownbits aren't optimal e.g.:
```
E:\llvm\llvm-project\llvm\unittests\Support\KnownBitsTest.cpp(123): error: Value of: isOptimal(Exact, Computed, {Known1, Known2})
  Actual: false (Inputs = ???1, 1000, Computed = ???1, Exact = 0??1)
Expected: true

E:\llvm\llvm-project\llvm\unittests\Support\KnownBitsTest.cpp(123): error: Value of: isOptimal(Exact, Computed, {Known1, Known2})
  Actual: false (Inputs = ??1?, 100?, Computed = ????, Exact = 0???)
Expected: true

E:\llvm\llvm-project\llvm\unittests\Support\KnownBitsTest.cpp(123): error: Value of: isOptimal(Exact, Computed, {Known1, Known2})
  Actual: false (Inputs = ??1?, 1001, Computed = ????, Exact = 0???)
Expected: true
```
Then its a lot of triage trying to work out why it failed.

**Comment by RKSimon** [comment]
CC @goldsteinn who may have some suggestions

**Comment by goldsteinn** [comment]
> CC @goldsteinn who may have some suggestions

I think whats missing is we don't set `nuw` flag when comparing `diff0`/`diff1`.
What might work is pull the impl of `computeForAddSub` out to a helper that
does not reset conflicts/poison.
Then have something like:
```
  KnownBits Diff0 =
      computeForAddSubNoResolvePoison(/*Add=*/false, /*NSW=*/false, /*NUW=*/true, LHS, RHS);
  KnownBits Diff1 =
      computeForAddSubNoResolvePoison(/*Add=*/false, /*NSW=*/false, /*NUW=*/true, RHS, LHS);
  KnownBits SubDiff = Diff0;
  if(SubDiff.hasConflict())
    SubDiff = Diff1
  elif(!Diff1.hasConflict())
   SubDiff = SubDiff.intersectWith(Diff1)
  assert(!SubDiff.hasConflict());
```

Take the cases you have above. 

In the LHS - RHS case, since we have NUW, we will deduce the signbit as leading 1s in RHS always imply zero (or poison).
In the RHS-LHS case, RHS.maxValue() - LHS.minValue() also underflows the signbit.

**Comment by aamod-wick** [comment]
Id like to try to fix it . Can this be assigned to me ?

**Comment by aamod-wick** [comment]
@goldsteinn  i do have some doubts in this approach .if we do set NUW flag then how would we be resolving poison /conflicts.  for the given test cases setting NUW flag in computeForAddSub with its current implementation should work right (though
 it doesnt)?

**Comment by goldsteinn** [comment]
> @goldsteinn i do have some doubts in this approach .if we do set NUW flag then how would we be resolving poison /conflicts. for the given test cases setting NUW flag in computeForAddSub with its current implementation should work right (though it doesnt)?

So with the NUW flag, poison inputs generate conflicts (same bitpos known zero/one). In `computeForAddSub` we currently handle conflicts by setting the output to zero.

How I would suggest proceeding is to move the core logic of `computeForAddSub` to a helper that does not resolve
conflicts to zero.

Then in `computeForAddSub` just call the helper and if the result has conflicts, set the result to zero.

In your code you can then check conflict to see if a result is usable.

**Comment by jayfoad** [comment]
@aamod-wick sorry I did not know you were working on this.

**Comment by aamod-wick** [comment]
No no issues . I was taking way too long anyways. I completely understand.
