### ISSUE TITLE
Clang's error on non-pack parameter of alias template in a dependent type

### ISSUE THREAD

**Issue by jonathanpoelen** [llvm/llvm-project#84220]
It seems that clang does not consider `sizeof...(xs)` to be a dependent expression when the call to foo is made with a known number of arguments. The expression must absolutely contain `xs...`.

The following code compiles with gcc, but not clang (https://godbolt.org/z/TYzvjTePT):

```cpp
template<int>
struct foo_impl {
  template<class>
  using f = int;
};

template<class... xs> constexpr int sizeof_pack = sizeof...(xs);

template<class... xs>
using foo = typename foo_impl< // error: pack expansion used as argument for non-pack parameter of alias template
  sizeof...(xs) // does not work
  // sizeof_pack<xs...>  // ok
>::template f<xs...>; // f is dependent on xs

template<class... xs>
using test = list<foo<xs>...>;

// template<class... xs>
// using test = foo<xs...>; // ok with pack...

test<int> a; // ko
```

**Comment by shafik** [comment]
Maybe this is [cwg1430](https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#1430)

Similar gcc bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=59701

Not totally sure.

CC @zygoloid @erichkeane

**Comment by zygoloid** [comment]
While canonicalizing the RHS of `test`, we form `foo<xs>`, for which `sizeof...(xs)` is 1. This gives

`using foo<xs> = typename foo_impl<1>::template f<{xs}...>;`

... which I suppose we reject per #1430. But I don't think we should: at this point, `{xs}...` should have already been expanded into the single argument `xs`, which is not itself a pack expansion, so #1430 shouldn't apply.

**Comment by zyn0217** [comment]
The issue arises in `RebuildDependentTemplateSpecializationType`, where the working case `using test = foo<xs...>` causes name `template f` to be considered dependent (and thus the diagnosis in `CheckTemplateArgumentList` gets bypassed) while the other `using test = list<foo<xs>...>` resolves the name `template f` in some way, resulting in the diagnosis in `CheckTemplateArgumentList`.
