### ISSUE TITLE
Add strfrom<float> functions to LLVM-libc

### ISSUE THREAD

**Issue by michaelrj-google** [llvm/llvm-project#84244]
Specified in C23 on page 370 of this PDF: https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3220.pdf

C23 adds a new family of functions to convert floating point numbers to strings: `strfromf`, `strfromd`, and `strfroml`. The interface is set up to piggyback on the existing printf interface, so no floating point knowledge is needed for this implementation. Since this involves adding a new public function there will be a lot of files that need to be touched, but each individual piece should be simple. Below is a (hopefully complete) list of tasks to add these functions. Feel free to reach out if you need help, you can find me as michaelrj on discord, or you can just leave a comment on this bug.

### Build System

In [entrypoints.txt](https://github.com/llvm/llvm-project/blob/main/libc/config/linux/x86_64/entrypoints.txt)
- [ ] Add the new functions to the list of entrypoints for stdlib.h (you need to do this before it will build)
- [ ] (Optional) Add the functions to the list of entrypoints for platforms other than linux/x86_64

In [stdlib/CMakeLists.txt](https://github.com/llvm/llvm-project/blob/main/libc/src/stdlib/CMakeLists.txt)
- [ ] Add new entrypoint objects to the list (they will need dependencies on printf components, which are found in [printf_core](https://github.com/llvm/llvm-project/tree/main/libc/src/stdio/printf_core))

In [stdc.td](https://github.com/llvm/llvm-project/blob/main/libc/spec/stdc.td#L923)
- [ ] Add the functions to the list of functions for stdlib.h (this can be confusing, ask for help if you're stuck).

### Code

Create `stdlib/strfromf.h`
- [ ] look at [strtof.h](https://github.com/llvm/llvm-project/blob/main/libc/src/stdlib/strtof.h) for an example of how this should be laid out (copying the whole file and modifying it is fine).
- [ ] Remember to add `#include <stddef.h>` since this function takes a `size_t`

Create `stdlib/strfromf.cpp`
- [ ] Again, look at look at [strtof.cpp](https://github.com/llvm/llvm-project/blob/main/libc/src/stdlib/strtof.cpp) for an example.
The plan is to have a shared utility function for all of the variants of these functions, so don't worry about filling this file out yet.

Create matching files for `strfromd` and `strfroml`
- [ ] Same as above.

Create a shared utility file (suggested path: `stdlib/str_from_util.h`) for the actual implementation
- [ ] Implement a function that takes the simplified format string and converts it into a FormatSection (defined in [core_structs.h](https://github.com/llvm/llvm-project/blob/main/libc/src/stdio/printf_core/core_structs.h))
  - [ ] How to handle things outside of the format the standard specifies is up to you, but make sure to leave a comment explaining your decision.
- [ ] Implement a templated function that takes the arguments from strto<float> that...
  - [ ] calls the parsing function mentioned above, then fills in the `conv_val_raw` argument in the FormatSection (you'll need to use a `cpp::bit_cast`, like how [parser.h](https://github.com/llvm/llvm-project/blob/main/libc/src/stdio/printf_core/parser.h#L59) does)
  - [ ] Creates a `Writer` object (like how [snprintf](https://github.com/llvm/llvm-project/blob/main/libc/src/stdio/snprintf.cpp) does)
  - [ ] Passes the completed FormatSection and writer to the appropriate converter (like how [converter.cpp](https://github.com/llvm/llvm-project/blob/main/libc/src/stdio/printf_core/converter.cpp) does)
  - [ ] Finally, return the result.

### Testing

Create `test/src/stdlib/strfromf_test.cpp`
- [ ] This will be similar to [snprintf_test.cpp](https://github.com/llvm/llvm-project/blob/main/libc/test/src/stdio/snprintf_test.cpp)
- [ ] Write tests to check the various parts of your implementation
  - [ ] Make sure to test your parser thoroughly, but you don't need to test the existing printf pieces as hard since they already have tests.
  - [ ] If you want complete floating point tests, look at [sprintf_test.cpp](https://github.com/llvm/llvm-project/blob/main/libc/test/src/stdio/sprintf_test.cpp#L1083)

Create similar files for `strfromd` and `strfroml`
- [ ] In the test for `strfroml` make sure to check which `long double` type you're working with, since it can be 64, 80, or 128 bits, and that will effect your results.
- [ ] (optional) Make all of these tests come from the same file, like how [StrtolTest.h](https://github.com/llvm/llvm-project/blob/main/libc/test/src/stdlib/StrtolTest.h) is implemented.

Add your tests to [test/src/stdlib/CMakeLists.txt](https://github.com/llvm/llvm-project/blob/main/libc/test/src/stdlib/CMakeLists.txt)
- [ ] Hopefully self-explanatory

**Comment by Poseydon42** [comment]
Hi! I'm a beginner contributor to LLVM and this looks like something I would be able to do. Can this issue please be assigned to me?

**Comment by Poseydon42** [comment]
Ok, will do, thank you.

**Comment by pranayrauni** [comment]
Hi! I'm Pranay.  Since it involves multiple tasks and no pull requests has been raised yet so may I also work on this issue? 

I'm an outreachy  applicant.

**Comment by panosfol** [comment]
Hello! Im also working on it.

**Comment by michaelrj-google** [comment]
If you're all working on this at the same time make sure you're working together to avoid wasted work. It would be good if one of you (probably @Poseydon42 as the first person to claim it) could create a PR with whatever you have currently (doesn't have to be complete). This way the others can provide their changes on the PR.

**Comment by Poseydon42** [comment]
Sorry for not responding sooner, I'll be definitely happy about getting some help. I will create a draft PR with the changes I've got so far first thing tomorrow in the morning.

**Comment by panosfol** [comment]
> Sorry for not responding sooner, I'll be definitely happy about getting some help. I will create a draft PR with the changes I've got so far first thing tomorrow in the morning.

Sounds good.

**Comment by Poseydon42** [comment]
I have created a draft PR with everything I've got so far (which is not much, but I'm planning to make a lot of progress over the weekend). The PR can be found [here](https://github.com/llvm/llvm-project/pull/84629).

**Comment by panosfol** [comment]
> * [ ]  Implement a templated function that takes the arguments from strto that...

@michaelrj-google Im having trouble understanding where the `strto` family of function come into place.
Can I get some input please?

**Comment by michaelrj-google** [comment]
ah, that's a typo, I meant the `strfrom` functions

**Comment by vinayakdsci** [comment]
@michaelrj-google  Hello! I was working on this issue, and I have been able to come up with a working implementation of `strfromf()`. The one thing that I am confused about is that the parsing function still requires the float to be cast to a double, to get `cpp::bit_cast<>()` to work correctly.
I just wanted to ask if this behavior is expected? doing a bit_cast for float type does not yield the correct results.
If the answer is yes, then I will start working on polishing the code and writing tests.

Thanks!

**Comment by michaelrj-google** [comment]
can you show me the code you have so far? Based on what you've said it sounds like you need to bit cast your templated float type to `fputil::FPBits<T>::StorageType` instead of a constant type.

**Comment by vinayakdsci** [comment]
> can you show me the code you have so far? Based on what you've said it sounds like you need to bit cast your templated float type to `fputil::FPBits<T>::StorageType` instead of a constant type.

I do do that, borrowing some of the implementation from `parser.h`. Should I open a pull request? I haven't committed the code I have written yet, as I am unable to figure out how to write the tests, but I am willing to open a draft PR.
Or should I just paste and format the code here only?

Thanks!

**Comment by michaelrj-google** [comment]
a draft PR would probably be the easiest solution

**Comment by michaelrj-google** [comment]
I've left some comments on that PR. I see what the problem is, and it's unfortunately my fault for how I designed the float converters :P

**Comment by vinayakdsci** [comment]
I have implemented the changes you suggested. One problem I am facing is that despite adding the test file to `CMakeLists.txt`, the build system does not seem to be recognizing and running the tests.
If you find time could you look at the tests too and help find out the mistake? I would really appreciate it!
Thanks!

**Comment by michaelrj-google** [comment]
I've added a comment to your patch explaining the issue (it's the one on the cmake in src) but also when debugging these in the future you can add `-DLIBC_CMAKE_VERBOSE_LOGGING=ON` to your cmake command to get logging messages telling you why each test is being skipped.

**Comment by vinayakdsci** [comment]
I was able to get the tests working after correcting the mistake you pointed out. I will make sure to use logging in the future. I have added some new tests, and made some fixes to the old ones.
Thanks a lot!

**Comment by michaelrj-google** [comment]
The patch is merged and the buildbots seem clean, thank you all for contributing to this :)

**Comment by vinayakdsci** [comment]
@michaelrj-google hello! I have opened PR #86113 implementing `strfromd()` and `strfroml()`. I had to make some changes to `strfromf_test.cpp` to make the test files consistent across all three functions, but I haven't changed any of the tests themselves. This PR should complete all of the tasks in this issue. Thanks!
