### ISSUE TITLE
clang drops volatile from struct on assignment from call

### ISSUE THREAD

**Issue by sunfishcode** [llvm/llvm-project#8426]
|  |  |
| --- | --- |
| Bugzilla Link | [8054](https://llvm.org/bz8054) |
| Version | trunk |
| OS | All |

## Extended Description 
On this C code:

struct T { int i; int j; int k; int l; int m; };
extern volatile struct T t;

struct T foo(void);

void bar(void) {
  t = foo();
}

clang emits this:

  call void @&#8203;foo(%struct.T* sret @&#8203;t)

The volatile qualifier has not been preserved.

**Comment by arsenm** [comment]
Clang emits this:
```
define dso_local void @bar() #0 {
  %1 = alloca %struct.T, align 4
  call void @foo(ptr sret(%struct.T) align 4 %1)
  call void @llvm.memcpy.p0.p0.i64(ptr align 4 @t, ptr align 4 %1, i64 20, i1 true)
  ret void
}

```

The volatile is preserved on the memcpy
