### ISSUE TITLE
[WebAssembly]: `__attribute__((used))` doesn't preserve symbol

### ISSUE THREAD

**Issue by sunfishcode** [llvm/llvm-project#84364]
It appears `__attribute__((used))` doesn't cause a symbol to be preserved in the final output, on Wasm. Similarly, functions with an `export_name` are not preserved, even though it also has `no_dead_strip` in the output.

Specifically, here's a C testcase where everything is prefixed with "abc" for easy grepping:
```c
__attribute__((export_name("abc-red")))
static void abc_apple(void) {}

__attribute__((used))
static void abc_pear(void) {}

void abc_banana(void) {}

__attribute__((export_name("abc-green")))
void abc_grape(void) {}
```

`abc_apple`, `abc_pear`, and `abc_grape` are all marked with `no_dead_strip`, as expected:
```
$ clang -S -o - test.c | grep no_dead_strip
	.no_dead_strip	abc_apple
	.no_dead_strip	abc_pear
	.no_dead_strip	abc_grape
	.no_dead_strip	__indirect_function_table
```

However, the only function that gets preserved is `abc_grape`:
```sh
$ clang test.c -o test.wasm
$ wasm-tools print test.wasm | grep abc
  (func $abc_grape (;6;) (type 2)
  (export "abc-green" (func $abc_grape))
```

So it appears wasm-ld is not honoring no_dead_strip.

I can reproduce with with the clang packages in [wasi-sdk](https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-21) and with a build from current wasi-sdk and llvm git sources.

**Comment by sunfishcode** [comment]
I was trying to use `static` + `export_name` in generated bindings: there's a wrapper around user code, where the wrapper is Wasm-exported, and isn't itself meant to be called from within the C linkage namespace. As you say, my workaround is to not use `static`.

**Comment by sbc100** [comment]
Interestingly `__attribute__((used))` also doesn't seem to preserve functions under ELF when used with `-Wl,--gc-sections -ffunction-sections`.    The ELF linker always seems to strip unused functions regardless of `static` or `used`.

**Comment by sunfishcode** [comment]
Oh, interesting. So if we think of wasm-ld as just doing those optimizations by default, then this isn't a bug.

**Comment by sbc100** [comment]
Maybe exporting of a static function could/should work still though.   Or at least it should be an error to attach export attributes to static symbols?

**Comment by sunfishcode** [comment]
Good point. I had been approaching this from the perspective of `__attribute__((used))` because it uses the same `no_dead_strip` property that exports do. But maybe exports should be different. Maybe they should be kept live no matter what, even in wasm-ld doing function-sections/gc-sections-style optimizations.

**Comment by sbc100** [comment]
Yes, wasm-ld will never strip something that is exported... but the problem is that its currently impossible to export an internal/static symbol (via any mechanism at all, eg. --export=foo also won't work).

I don't really consider this a bug, so I'm inclined to opt make it an error to put export_name on a static symbol.

**Comment by sbc100** [comment]
the problem is that things like `--export=foo` depend on looking up `foo` in the symbol table and static symbols don't appear in the symbol table at all.
