### ISSUE TITLE
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.

### ISSUE THREAD

**Issue by KA2010** [llvm/llvm-project#84361]
Stack dump:
0.      Program arguments: opt -load-pass-plugin=./build/StringObfuscator/libLLVMStringObfuscator.so -passes=string-obfuscator-pass -o out_stringObf.bc
#0 0x000000000498ffea llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/myuser/llvm-project/llvm/lib/Support/Unix/Signals.inc:565:11
#1 0x00000000049901bb PrintStackTraceSignalHandler(void*) /home/myuser/llvm-project/llvm/lib/Support/Unix/Signals.inc:632:1
#2 0x000000000498e795 llvm::sys::RunSignalHandlers() /home/myuser/llvm-project/llvm/lib/Support/Signals.cpp:96:5
#3 0x0000000004990931 SignalHandler(int) /home/myuser/llvm-project/llvm/lib/Support/Unix/Signals.inc:407:1
#4 0x00007f08ab31e420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
#5 0x00007f08ab14ec98 vtable for __cxxabiv1::__si_class_type_info (/lib/x86_64-linux-gnu/libstdc++.so.6+0x1d3c98)
Segmentation fault

Hi,  I have found this bug when I try to use llvm-string-obfuscator
any help to solve it!

**Comment by EugeneZelenko** [comment]
@KA2010: Could you please provide reproducer?

**Comment by KA2010** [comment]
How-To:
1- Install llvm `sudo apt install llvm`

2- Build the StringObfuscator library:

```
mkdir build
cd build
cmake ..
make
```
3- Generate LLVM bytecode from your binary and run the StringObfuscator pass on it:
```
clang -emit-llvm hello.c -c -o hello.bc
opt -load-pass-plugin=./build/StringObfuscator/libLLVMStringObfuscator.so -passes="string-obfuscator-pass" < hello.bc -o out.bc
llc out.bc -o out.s
clang -static out.s -o out
```
the source [https://github.com/tsarpaul/llvm-string-obfuscator?tab=readme-ov-file#how-to](url)

**Comment by asl** [comment]
This is not an LLVM project. Consider reporting it to `StringObfuscator`.

**Comment by KA2010** [comment]
@asl 
Why you close the issue?, I know it is not LLVM project but the error come from llvm project as mentioned above 
keep it open may someone nicer than you can help.

**Comment by KA2010** [comment]
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.

**Comment by asl** [comment]
It is not an LLVM bug. Likely that downstream project did something strange / unsupported. The error message is generic. Consider reporting your issue to https://github.com/tsarpaul/llvm-string-obfuscator

Feel free to reopen showing that this is LLVM bug and not an "llvm-string-obfuscator"
