### ISSUE TITLE
libc++: No parallel execution with parallel STL

### ISSUE THREAD

**Issue by Gei0r** [llvm/llvm-project#84442]
I know that the parallel STL implementation is still experimental, but according to [the status page](https://releases.llvm.org/18.1.0/projects/libcxx/docs/Status/PSTL.html#pstl-status), `for_each` should already be "complete".

However, with my test program, I don't see any parallization. The parallel algorithm takes the same time as the sequential version. I tested both libc++ 17.0.6 and 18.1.0 on both Windows and Linux.

[Compiler Explorer](https://godbolt.org/z/9sxfaqoqr)

What's wrong? Did I miss something?

**Comment by philnik777** [comment]
"complete" in this case means that the interface is implemented. It doesn't mean it's actually run in parallel. We currently only have a parallel implementation for macOS. An OpenMP backend is WIP.
