### ISSUE TITLE
[analyzer] MemRegion::getDescriptiveName breaks for Index not of type nonloc::ConcreteInt

### ISSUE THREAD

**Issue by T-Gruber** [llvm/llvm-project#84463]
I am currently working with the Clang Static Analyzer to analyze small C code examples. Thereby I have come across a behaviour of MemRegion::getDescriptiveName that I do not fully understand. I am working with the llvm-project 17.x-release version. 
The simple checker below should be sufficient for demonstration purposes. Basically, the MemRegion and its name for a given SVal should be extracted within the checkLocation method.

```Cpp
namespace {
class TestChecker : public clang::ento::Checker<clang::ento::check::Location> {

public:
  void checkLocation(const clang::ento::SVal &Loc, bool IsLoad,
                     const clang::Stmt *S,
                     clang::ento::CheckerContext &CC) const {
    clang::ento::ProgramStateRef PSR = CC.getState();
    const clang::ento::MemRegion *MemReg = Loc.getAsRegion();

    if (MemReg) {
      std::string MemRegName = MemReg->getDescriptiveName();
      llvm::outs() << "MemRegion: Name = " << MemRegName << "\n";
    }
  }
};
} // namespace

void clang::ento::registerTestChecker(clang::ento::CheckerManager &CM) {
  CM.registerChecker<TestChecker>();
}

bool clang::ento::shouldRegisterTestChecker(
    const clang::ento::CheckerManager &CM) {
  return true;
}
```

This is the C code example to be analysed.

```C
unsigned int index1 = 1;
extern unsigned int index2;
extern int array[10];

int main() {
  array[index1];
  array[index2];
  return 0;
}
```

The extracted MemRegions and their names for the first statement match my expectations.:
```
MemRegion: Name = 'index1'
ElementRegion: ER = Element{array,1 S64b,int}
Index: ConcreteInt = 1
Next iteration: R = array
MemRegion: Name = 'array[1]'
```

Here is the relevant part of MemRegion::getDescriptiveName with a few additional outputs:
```Cpp
std::string MemRegion::getDescriptiveName(bool UseQuotes) const {
  std::string VariableName;
  std::string ArrayIndices;
  const MemRegion *R = this;
  SmallString<50> buf;
  llvm::raw_svector_ostream os(buf);

  // Obtain array indices to add them to the variable name.
  const ElementRegion *ER = nullptr;
  while ((ER = R->getAs<ElementRegion>())) {
    // Index is a ConcreteInt.
    llvm::outs() << "ElementRegion: ER = " << ER->getString() << "\n";
    if (auto CI = ER->getIndex().getAs<nonloc::ConcreteInt>()) {
      llvm::SmallString<2> Idx;
      CI->getValue().toString(Idx);
      ArrayIndices = (llvm::Twine("[") + Idx.str() + "]" + ArrayIndices).str();
      llvm::outs() << "Index: ConcreteInt = " << Idx.str() << "\n";
    }
    // If not a ConcreteInt, try to obtain the variable
    // name by calling 'getDescriptiveName' recursively.
    else {
      std::string Idx = ER->getDescriptiveName(false);
      if (!Idx.empty()) {
        ArrayIndices = (llvm::Twine("[") + Idx + "]" + ArrayIndices).str();
        llvm::outs() << "Index: NOT ConcreteInt = " << Idx << "\n";
      }
    }
    R = ER->getSuperRegion();
    if (R)
      llvm::outs() << "Next iteration: R = " << R->getString() << "\n";
  }
...
```

The second statement, however, causes the method to call itself recursively with the same instance (else branch inside while statement). This finally leads to a segmentation fault.
```
MemRegion: Name = 'index2'
ElementRegion: ER = Element{array,reg_$0<unsigned int index2>,int}
ElementRegion: ER = Element{array,reg_$0<unsigned int index2>,int}
ElementRegion: ER = Element{array,reg_$0<unsigned int index2>,int}
...
#254 0x000055f02a6171ed clang::ento::MemRegion::getDescriptiveName[abi:cxx11](bool) const (bin/clang+0x57321ed)
#255 0x000055f02a6171ed clang::ento::MemRegion::getDescriptiveName[abi:cxx11](bool) const (bin/clang+0x57321ed)
Segmentation fault (core dumped)
```

The result that would correspond to my expectation could be achieved by the following additional lines (else if):

```Cpp
std::string MemRegion::getDescriptiveName(bool UseQuotes) const {
  std::string VariableName;
  std::string ArrayIndices;
  const MemRegion *R = this;
  SmallString<50> buf;
  llvm::raw_svector_ostream os(buf);

  // Obtain array indices to add them to the variable name.
  const ElementRegion *ER = nullptr;
  while ((ER = R->getAs<ElementRegion>())) {
    // Index is a ConcreteInt.
    llvm::outs() << "ElementRegion: ER = " << ER->getString() << "\n";
    if (auto CI = ER->getIndex().getAs<nonloc::ConcreteInt>()) {
      llvm::SmallString<2> Idx;
      CI->getValue().toString(Idx);
      ArrayIndices = (llvm::Twine("[") + Idx.str() + "]" + ArrayIndices).str();
      llvm::outs() << "Index: ConcreteInt = " << Idx.str() << "\n";
    }
    // Added: Try to get index as SymbolVal -> SymbolRef -> OriginRegion -> Name
    else if (auto SI = ER->getIndex().getAs<nonloc::SymbolVal>()) {
      if (auto SR = SI->getAsSymbol()) {
        if (auto OR = SR->getOriginRegion()) {
          std::string Idx = OR->getDescriptiveName(false);
          ArrayIndices = (llvm::Twine("[") + Idx + "]" + ArrayIndices).str();
          llvm::outs() << "Index: SymbolVal = " << Idx << "\n";
        }
      }
    }
    // If not a ConcreteInt, try to obtain the variable
    // name by calling 'getDescriptiveName' recursively.
    else {
      std::string Idx = ER->getDescriptiveName(false);
      if (!Idx.empty()) {
        ArrayIndices = (llvm::Twine("[") + Idx + "]" + ArrayIndices).str();
        llvm::outs() << "Index: NOT ConcreteInt = " << Idx << "\n";
      }
    }
    R = ER->getSuperRegion();
    if (R)
      llvm::outs() << "Next iteration: R = " << R->getString() << "\n";
  }
  ```

This would achieve the following output and the recursion of MemRegion::getDescriptiveName would also be solved for this case:
 ```
 MemRegion: Name = 'index2'
ElementRegion: ER = Element{array,reg_$0<unsigned int index2>,int}
Index: SymbolVal = index2
Next iteration: R = array
MemRegion: Name = 'array[index2]'
```

Am I missing something or is the described behaviour intended?

**Comment by steakhal** [comment]
So the `getDescriptiveName()` is called on `R`.
If `R` is an `ER`, and `ER.getIndex()` is not a `ConcreteInt`, then we call `ER->getDescriptiveName()`, which the same from where we started. This is definitely a bug, like you said.
I can also confirm that this `else if` where the infinite recursion would happen is not covered by tests, see the [coverage report](https://lab.llvm.org/coverage/coverage-reports/coverage/Users/buildslave/jenkins/workspace/coverage/llvm-project/clang/lib/StaticAnalyzer/Core/MemRegion.cpp.html#L726).

So, a call to `std::string Idx = ER->getDescriptiveName(false);` definitely does not make sense, even after your extra `else if` branch.

Speaking of your `else if` branch, it seems to be correct to me.

I can see that the `ArrayBoundV2` checker uses this API, so I wonder if we could create a test case invoking this infinite recursion.

**Comment by NagyDonat** [comment]
Thanks for reporting this infinite recursion!

I agree that this is a bug and the suggested `else if` branch is a correct solution for resolving it. I'm also agreeing with
> [...] a call to `std::string Idx = ER->getDescriptiveName(false);` definitely does not make sense, even after your extra else if branch.

-- instead of keeping the original `else` branch we should insert a "we give up" return statement (IIRC this method signals failure with `return "";`) because at that point we don't have a meaningful description for that index and there is no point in re-trying anything.

**Comment by T-Gruber** [comment]
Thank you @steakhal & @NagyDonat for your answers!
Should I create a separate pull request for this or what is the next step?

**Comment by steakhal** [comment]
> -- instead of keeping the original `else` branch we should insert a "we give up" return statement (IIRC this method signals failure with `return "";`) because at that point we don't have a meaningful description for that index and there is no point in re-trying anything.

I think I'd prefer something like this for that unlikely case:
```c++
assert(false && "we should have a descriptive name");
return "";
```
This way we get notified, but won't affect production.

> Should I create a separate pull request for this or what is the next step?

Yes. Please create a PR, and add `Fixes #84463` to the description there.
Make sure you have tests covering the parts you change; or ask for help thinking about testing.

**Comment by T-Gruber** [comment]
Hi @steakhal, as this is my first PR I would be very thankful for any advice on what to consider regarding testing.

**Comment by steakhal** [comment]
> Hi @steakhal, as this is my first PR I would be very thankful for any advice on what to consider regarding testing.

The rule of thumb is to have line coverage for the parts you touch in clang. This proves its not dead code, and there is at least one way it does something useful. The hardest part here would be to find a checker that can hit this path for some valid code.
That might not be possible, in which case you can create a unittest for a checker doing basically what you did to uncover this issue. For a test, have look at clang/test/Analysis/out-of-bounds-new.cpp. For a unittest, you can get inspired by clang/unittests/StaticAnalyzer/SymbolReaperTest.cpp for example.

**Comment by T-Gruber** [comment]
Thanks @steakhal for your support! 
I created a PR: https://github.com/llvm/llvm-project/pull/85104.
