### ISSUE TITLE
Bugpoint segfaults when diagnosing bug 8078

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#8451]
|  |  |
| --- | --- |
| Bugzilla Link | [8079](https://llvm.org/bz8079) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @nlewycky |

**Comment by arsenm** [comment]
Can't reproduce, bugpoint doesn't accept a raw "-indvars" argument anymore
