### ISSUE TITLE
18.1.0 build from source missing mlir/Dialect/Func/IR/FuncOps.h.inc?

### ISSUE THREAD

**Issue by hpcpony** [llvm/llvm-project#84568]
I download llvm-project-18.1.0.src.tar.xz and tried to build with the following:

```
[]$ cmake                                                            \
? -DLLVM_TARGETS_TO_BUILD=X86                                        \
? -DCLANG_CONFIG_FILE_USER_DIR="${SRC}/${VER}/${TAR}/llvm.cfg"       \
? -DCMAKE_C_COMPILER=${HOST_GCC}/bin/gcc                             \
? -DCMAKE_CXX_COMPILER=${HOST_GCC}/bin/g++                           \
? -DCMAKE_BUILD_TYPE="Release"                                       \
? -DLIBOMP_ARCH="x86_64"                                             \
? -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX}                                       \
? -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;cross-project-tests;libc;lld;lldb;mlir;polly;pstl" \
? -DLLVM_ENABLE_RUNTIMES="compiler-rt;libc;libcxx;libcxxabi;libunwind;openmp"    \
? -DCMAKE_CXX_LINK_FLAGS="-L${HOST_GCC}/lib64 -Wl,-rpath,${HOST_GCC}/lib64"      \
? ../llvm
  .
  .
  .
[]$ make
  .
  .
  .
[ 71%] Built target MLIRSCFDialect
[ 71%] Building CXX object tools/mlir/lib/Dialect/Affine/Analysis/CMakeFiles/obj.MLIRAffineAnalysis.dir/AffineAnalysis.cpp.o
In file included from /scr/LLVM/llvm-18.1.0/llvm-project-18.1.0.src/mlir/lib/Dialect/Affine/Analysis/AffineAnalysis.cpp:20:
/scr/LLVM/llvm-18.1.0/llvm-project-18.1.0.src/mlir/include/mlir/Dialect/Func/IR/FuncOps.h:29:10: fatal error: mlir/Dialect/Func/IR/FuncOps.h.inc: No such file or directory
   29 | #include "mlir/Dialect/Func/IR/FuncOps.h.inc"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

I'm not sure what the appropriate work around is.  Maybe just remove mlir from projects?

**Comment by joker-eph** [comment]
This is a missing dependency in CMake, so a non-deterministic failure unfortunately.

You can try `make tools/mlir/include/mlir/Dialect/Func/IR/FuncOps.h.inc` and then rerun make.

(Note that make is sequential I believe, we recommend replace this with Ninja these days)

**Comment by Romendakil** [comment]
I am having the same problem, building under Ubuntu 20.04 with gcc 11.4

**Comment by ncihnegn** [comment]
Same error for 18.1.4 on macOS.

**Comment by gfernval** [comment]
"make tools/mlir/include/mlir/Dialect/Func/IR/FuncOps.h.inc" does not work, without mlir package lld cannot be build.
Any solution? Could someone post the missing file FuncOps.h.inc?

**Comment by jschueller** [comment]
FuncOps.h.inc is generated after:
`make MLIRFuncOpsIncGen`

**Comment by joker-eph** [comment]
>  without mlir package lld cannot be build.

You don't need MLIR for build lld actually.

**Comment by Laurent-777** [comment]
> Same error for 18.1.4 on macOS.

Ditto with 18.1.8 under Macos Monterey (12.7.5)

**Comment by joker-eph** [comment]
The workaround is to run first `make MLIRFuncOpsIncGen`.

Just restarting the build until it passes can work as well: this is a race condition in parallel builds.
