### ISSUE TITLE
Allow C99 flexible array members in unions and alone in structs like 0-length arrays

### ISSUE THREAD

**Issue by kees** [llvm/llvm-project#84565]
GNU and MSVC have extensions where flexible array members (or their equivalent) can be in unions or alone in structs. This is already fully supported in Clang through the 0-sized array ("fake flexible array") extension or when C99 flexible array members have been syntactically obfuscated.

Please explicitly allow these extensions directly for C99 flexible arrays, since they are common code patterns in active use by the Linux kernel (and other projects). Such projects have been using either 0-sized arrays (which is considered deprecated in favor of C99 flexible array members) or via obfuscated syntax, both of which complicate their code bases.

For example, these do not error by default:
```
union one {
	int a;
	int b[0];
};

union two {
	int a;
	struct {
		struct { } __empty;
		int b[];
	};
};
```
But this does:
```
union three {
	int a;
	int b[];
};
```

Matching request has been made to GCC as well: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53548

@nickdesaulniers

**Comment by shafik** [comment]
CC @AaronBallman @erichkeane

**Comment by kees** [comment]
PR #84428 has been proposed to fix this.
