### ISSUE TITLE
[clang-format] SeparateDefinitionBlocks always puts a break between a UCLASS defined and the unreal class

### ISSUE THREAD

**Issue by duyaokun** [llvm/llvm-project#84596]
StatementMacros: ['UPROPERTY', 'UFUNCTION', 'UCLASS', 'USTRUCT', 'UENUM', 'UINTERFACE', 'GENERATED_BODY', 'Q_UNUSED', 'QT_REQUIRE_VERSION']
StatementAttributeLikeMacros: ['UCLASS'] 
SeperateDefinitionBlocks: Always

```
/** This is unreal class */
UCLASS(Abstract)

class AMyActor : public AActor
{
```

I wish the result like this:
```
/** This is unreal class */
UCLASS(Abstract)
class AMyActor : public AActor
{
```

**Comment by owenca** [comment]
clang-format doesn't remove empty lines if `MaxEmptyLinesToKeep` isn't exceeded.
