### ISSUE TITLE
[OBJC] __attribute__((NSObject)) types should be usable as lightweight generic types

### ISSUE THREAD

**Issue by dmaclach** [llvm/llvm-project#84592]
```
typedef __attribute__((NSObject)) struct Foo *FooRef;
NSArray<FooRef> *array;
```

Currently gives you the error `type argument 'FooRef' (aka 'const struct Foo *') is neither an Objective-C object nor a block type`
which is not true given that it has `__attribute__((NSObject))` and as per https://clang.llvm.org/docs/AutomaticReferenceCounting.html#retainable-object-pointers is a retainable type.

**Comment by nico** [comment]
(dmac: If you say something like `Fixes #84592` in your commit description, github will auto-close the issue when the commit gets merged.)
