### ISSUE TITLE
Optimize x * !x to 0 for vector

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#84608]
Consider the following test case from https://github.com/gcc-mirror/gcc/blob/master/gcc/testsuite/gcc.dg/tree-ssa/pr114009.c
```c
typedef int V __attribute__((vector_size (4 * sizeof (int))));

V qux (V x)
{
  return x * (x == 0);
}
```
Godbolt: https://godbolt.org/z/dfGacerv8
Alive2: https://alive2.llvm.org/ce/z/uijB4T

**Comment by dtcxzyw** [comment]
Alive2: https://alive2.llvm.org/ce/z/-XEPRP

**Comment by SahilPatidar** [comment]
@dtcxzyw,
 I would like to work on this one.

**Comment by SahilPatidar** [comment]
> Alive2: https://alive2.llvm.org/ce/z/-XEPRP

This case also needs to be handled. Additionally, I couldn't find any such pattern in the existing code in InstCombineMulDivRem.cpp, so it likely needs to be implemented from scratch.
