### ISSUE TITLE
[DAG] TargetLowering::expandABD - investigate alternative expansions

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#84639]
As mentioned here by @jayfoad https://github.com/llvm/llvm-project/pull/84431#issuecomment-1986043833

> Incidentally Hacker's Delight has a section "Average of Two Integers" which has some neat tricks for implementing these operations without extending to N+1-bit integers.

These include alternative code for targets with poor MIN/MAX/SAT/CMPSEL instructions as well as simpler expansions depending upon the knownbits/numsignbits of the operands.

**Comment by Sh0g0-1758** [comment]
Hey @RKSimon, I would like to work on this.

**Comment by changkhothuychung** [comment]
Hi I would like to work on this if this is available

**Comment by EugeneZelenko** [comment]
@changkhothuychung: Just create pull request and mention it on this page.

**Comment by Sh0g0-1758** [comment]
Does this issue aim to look at both the optimization of "Average of two integers" or only alternative code targets for absolute difference in the TargetLowering.cpp file? The description of the issue also seems a little open to me. Can you please refine it with fine-grained tasks?

**Comment by Sh0g0-1758** [comment]
If I am not wrong, the optimizations that were introduced in `TargetLowering::expandAddSubSat` need to be introduced in `TargetLowering::expandABD`.

**Comment by Sh0g0-1758** [comment]
During my findings, I found doz (difference or zero) to be a suitable alternative expansion. We can implement ABD(x,y) as : 

`doz(x,y) + doz(y,x)`

Here is how it is defined : 

![Screenshot from 2024-03-11 15-47-23](https://github.com/llvm/llvm-project/assets/114918019/dc5f8f06-ee66-4ef5-9b17-4832cfc26bda)

And for the Average of two integers without using extra bits and ensuring no overflow, we can use : 

`(x&y)+((x^y)>>1)`

**Comment by RKSimon** [comment]
Closing this as it references the wrong lowering code, is too broad and rather confusing - I'll create more useful smaller issues.

**Comment by Sh0g0-1758** [comment]
Right, that's what I thought, was scratching my head all morning :) Nevertheless, found some interesting resources on compiler optimization.
