### ISSUE TITLE
[Support] Add KnownBits implementations for avgFloor and avgCeil

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#84640]
Followup to #84211

These are implemented as part of #76644 but in SelectionDAG not in the KnownBits class directly

- [x] Add KnownBIts::avgfloors/avgflooru/avgceils/avgceilu implementations based off #76644
- [x] Add exhaustive KnownBits test coverage (can it be optimal or just correct?)
- [x] Depending upon whether #76644 lands before or after this, you might need to update the SelectionDAG code or coordinate with @snikitav

**Comment by Sh0g0-1758** [comment]
Hey @RKSimon, I would like to work on this.

**Comment by changkhothuychung** [comment]
Hi I would like to work on this if this is available

**Comment by EugeneZelenko** [comment]
@changkhothuychung: Just create pull request and mention it on this page.

**Comment by RKSimon** [comment]
@changkhothuychung @Sh0g0-1758 Both of you have requested assignment for #84640 and #84639 - do either of you have a preference? I'd prefer to keep the good-first-issue tickets distributed.

**Comment by Sh0g0-1758** [comment]
I can work on #84639

**Comment by Sh0g0-1758** [comment]
I have started working on #84639

**Comment by changkhothuychung** [comment]
@RKSimon RK
Thank you for assigning this ticket to me. I have a few questions for direction. 

- I am supposed to add the implementations in the file KnownBits.cpp right? 
- Is there any documentation which explains what KnownBits are for and the use case of it? So I can have a better understanding of what I am doing. Thanks.

**Comment by RKSimon** [comment]
KnownBits are for analysis to allow us to track whether any specific bits of a variable are guaranteed to be zero or one, and help considerably with codegen simplification.

The implementations need moving into KnownBits.cpp - #76644 has the 4 implementations merged into 1 case, but ideally we'd want them separate.
```cpp
KnownBits::avgCeilS
KnownBits::avgCeilU
KnownBits::avgFloorS
KnownBits::avglFoorU
```

The exhaustive tests will need to be added around here:https://github.com/llvm/llvm-project/blob/995d1d114e4e4ff708a03cdb0a975209c6197f9f/llvm/unittests/Support/KnownBitsTest.cpp#L601-L609

You will need to wait until #84431 is completed so the equivalent APInt constant methods are available.

**Comment by RKSimon** [comment]
@changkhothuychung reverse-ping

**Comment by changkhothuychung** [comment]
@RKSimon Hi, I am figuring out how to do the implementations, I will make a PR as soon as I have something.

**Comment by RKSimon** [comment]
Fixed by #86445 ( we might be able to improve optimal testing in a future commit)

**Comment by changkhothuychung** [comment]
@RKSimon 
I have a quick conceptual question about this part of llvm since im still new to the repo. It seems like to me SelectionDAG is a graph, and each node will contain an assembly instruction for later stages to generate assembly code is it correct? What parts of llvm will take in a SelectionDAG and begin the code generation process? 

And also, are all the code optimizations done at SelectionDAG level? Thanks.

**Comment by RKSimon** [comment]
Most optimization is done in the middle end (InstCombine etc.), aiming for optimized, canonical code but very little is platform specific (just some combining of target intrinsics and some cost driven optimizations).

The Instruction selection stage (SelectionDAG, FastISel, GlobalISel) then transforms the IR into types/ops suitable for a specific target: https://llvm.org/docs/CodeGenerator.html#introduction-to-selectiondags, and then converts to a DAG of target instructions and then MachineInstructions.
