### ISSUE TITLE
[libc][stdbit] Typos in type generic macros for `bit_width`, `bit_floor`

### ISSUE THREAD

**Issue by Flandini** [llvm/llvm-project#84658]
I think I noticed a potential typo in the stdbit type generic macros for `stdc_bit_width` and `stdc_bit_floor`:

```
#define stdc_bit_width(x)                                                      \
  _Generic((x),                                                                \
      unsigned char: stdc_bit_width_ui, <---                                   \
      unsigned short: stdc_bit_width_us,                                       \
      unsigned: stdc_bit_width_ui,                                             \
      unsigned long: stdc_bit_width_ul,                                        \
      unsigned long long: stdc_bit_width_ull)(x)
#define stdc_bit_floor(x)                                                      \
  _Generic((x),                                                                \
      unsigned char: stdc_bit_floor_ui, <---                                   \
      unsigned short: stdc_bit_floor_us,                                       \
      unsigned: stdc_bit_floor_ui,                                             \
      unsigned long: stdc_bit_floor_ul,                                        \
      unsigned long long: stdc_bit_floor_ull)(x)
```

I think the assignment exprs for the assocs for `unsigned char` should refer to the respective `*_uc` functions.

Seems like this is missed by the tests because we only test the `__cplusplus` part of the preprocessor conditional. 

I will fix these and add tests for both branches of the preprocessor conditional in `stdbit-macros.h`, let me know if these are actually as expected.

**Comment by lntue** [comment]
I think to test the other code path, we just need to have a test in C (.c) instead of C++ (.cpp).  But I don't think our current testing framework works for C.

You could try to add a C test in `test/include` with some simple assertion using the `libc.src.assert.__assert_fail` target.  We can extend it to a separate test framework for C tests later.
