### ISSUE TITLE
New clang-tidy check: stack address escape by lambda capture

### ISSUE THREAD

**Issue by HerrCai0907** [llvm/llvm-project#84679]
stack address can be escape when lambda expression captures it by reference.
For example:
```C++
auto f() {
  int a;
  return [&]() {
    return a;
  };
}
```

**Comment by PiotrZSL** [comment]
This case is already detected by compiler warning:
`warning: address of stack memory associated with local variable 'a' returned [-Wreturn-stack-address]`
