### ISSUE TITLE
[clang-format] "SpaceInEmptyBlock: true" is not respected in C#

### ISSUE THREAD

**Issue by HermesonBF** [llvm/llvm-project#84695]
How to reproduce:

1 - Create a file .clang-format with the following content: "SpaceInEmptyBlock: true"

2 - Run clang-format in the following C# code, it will format to "new string[] {}" instead of "new string[] { }" as it should be.

```
using UnrealBuildTool;

public class GameProject : ModuleRules {
  public GameProject(ReadOnlyTargetRules Target) : base(Target) {
    PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;
    PublicDependencyModuleNames.AddRange(new string[] { "Core" });
    PrivateDependencyModuleNames.AddRange(new string[] {});
  }
}
```

**Comment by owenca** [comment]
> How to reproduce:
> 
> 1 - Create a file .clang-format with the following content: "SpaceInEmptyBlock: true"
> 
> 2 - Run clang-format in the following C# code, it will format to "new string[] {}" instead of "new string[] { }" as it should be.

Doesn't the pair of braces enclose an init list instead of a block?

**Comment by HermesonBF** [comment]
Yes, it correctly added the space in a block like "void f() { }", still it's strange that the behavior is different for a list with no option to control it.

**Comment by HermesonBF** [comment]
Here is another glitch:

```
Event += () => {}; // here the formatter removes the space from the block

void Method() { } // here the formatter inserts the space from the block
```

**Comment by owenca** [comment]
> Here is another glitch:
> 
> ```
> Event += () => {}; // here the formatter removes the space on the block
> 
> void Method() { } // here the formatter inserts the space on the block
> ```

This is a bug, but please open a new (enhancement) issue for the example at the top.
