### ISSUE TITLE
[DAG] Match some basic ISD::AVGFLOORU patterns

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#84749]
Pulled out of Hacker's Delight, both of these are valid patterns that can be folded to ISD::AVGFLOORU (assuming the target supports it):
```ll
define i4 @fixedwidth(i4 %a0, i4 %a1)  {
  %and = and i4 %a0, %a1
  %xor = xor i4 %a0, %a1
  %srl = lshr i4 %xor, 1
  %res = add i4 %and, %srl
  ret i4 %res
}

define i4 @zext_add_extract(i4 %a0, i4 %a1)  {
  %x0 = zext i4 %a0 to i5
  %x1 = zext i4 %a1 to i5
  %sum = add i5 %x0, %x1
  %srl = lshr i5 %sum, 1
  %res = trunc i5 %srl to i4
  ret i4 %res
}
```
These will need aarch64 vector tests as thats the only target that has legal ISD::AVGFLOORU instructions so far.

**Comment by RKSimon** [comment]
combineShiftToAVG already does this for some extraction patterns, its the fixedwidth variants that we're missing entirely.

**Comment by Sh0g0-1758** [comment]
Had a few doubts. 

I think this pattern gives the AVGCEIL and not AVGFLOOR as implied by the issue. 

```asm
define i4 @fixedwidth(i4 %a0, i4 %a1)  {
  %and = and i4 %a0, %a1
  %xor = xor i4 %a0, %a1
  %srl = lshr i4 %xor, 1
  %res = add i4 %and, %srl
  ret i4 %res
}
```

And this pattern is exactly how AVGFLOORU is implemented in `SelectionDAG.cpp`. I wonder why we still don't support detection of this pattern. Just needed a sanity check for this whether or not I should go ahead with its pattern matching in `TargetLowering.cpp`. 

```asm
define i4 @zext_add_extract(i4 %a0, i4 %a1)  {
  %x0 = zext i4 %a0 to i5
  %x1 = zext i4 %a1 to i5
  %sum = add i5 %x0, %x1
  %srl = lshr i5 %sum, 1
  %res = trunc i5 %srl to i4
  ret i4 %res
}
```

**Comment by Sh0g0-1758** [comment]
I see. thanks for the alive link. The issue is clear to me now. I will add the logic in DAGCombine and raise a PR soon.
