### ISSUE TITLE
build fail:  version `GLIBCXX_3.4.20' not found

### ISSUE THREAD

**Issue by zcfh** [llvm/llvm-project#84752]
I encountered the error `/lib64/libstdc++.so.6: version 'GLIBCXX_3.4.20' not found required by bin/llvm-min-tblgen` when building clang-17 from source. What I'm more confused about is why such a problem still occurs when I build clang17 from the **source code**. Although setting LD_LIBRARY_PATH and specifying a higher version of libstdc++ can bypass it, the binary compiled in this way also needs to set `LD_LIBRARY_PATH` to run. Is it a problem with my option settings?

build command
```
cmake -G Ninja -DCMAKE_C_COMPILER=gcc-10.3.0/bin/gcc -DCMAKE_CXX_COMPILER=gcc-10.3.0/bin/g++ -DLLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN=ON -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_USE_LINKER=lld -DLIBCXXABI_ENABLE _SHARED=OFF -DLIBCXX_ENABLE_SHARED=OFF '- DLLVM_ENABLE_RUNTIMES=libcxx;libcxxabi' -DCMAKE_BUILD_TYPE=Release '-DLLVM_ENABLE_PROJECTS=clang;lld;compiler-rt;bolt' ../llvm-project-llvmorg-17.0.6/llvm
ninja
```

**Comment by pinskia** [comment]
if you are using `gcc-10.3.0/bin/gcc` as your build Compiler and don't set LD_LIBRARY_PATH for C++ code in general, you will run into this issue. GCC itself avoids the issue by compiling with -static-libstdc++ but I am not sure LLVM wants to do that. Also this is not really a LLVM issue at all just how you decided to build with not the system installed GCC and think you don't need special options for the libraries that comes with GCC.

**Comment by zcfh** [comment]
Thanks, using `-static-libstdc++` will work
