### ISSUE TITLE
Implement fixits for malformed 'main' declaration

### ISSUE THREAD

**Issue by ggreif** [llvm/llvm-project#8476]
|  |  |
| --- | --- |
| Bugzilla Link | [8104](https://llvm.org/bz8104) |
| Version | trunk |
| OS | All |
| CC | @dwblaikie,@gribozavr |

## Extended Description 
[7:30pm] gabor: dgregor: FixIt idea: error: C++ requires a type specifier for all declarations
[7:30pm] gabor: main (int , const char * argv [])
[7:30pm] gabor: ^--- "int "

Since main must return "int" this is an always applicable fixit.

I am not so sure with the main arguments
- either "int main(void)" in C++ also "int main()"
- or "int main(int argc, const char* argv[])"

But these are often mis-declared, so a fixit would be useful too.

**Comment by philnik777** [comment]
There are quite a few fixits now for misdeclared `main`s, so I think this can be closed.
