### ISSUE TITLE
Multiply by a power of 2 and ctz+shift should often be interchangeable

### ISSUE THREAD

**Issue by Validark** [llvm/llvm-project#84763]
The compiler should probably be able to optimize either of these functions to the other one, depending on cost for the particular hardware ([Godbolt link](https://zig.godbolt.org/z/6fcrzqc4b)):

```zig
export fn foo(x: u64, y: u64) u64 {
    return x *% (y & (~y +% 1));
}

export fn bar(x: u64, y: u64) u64 {
    if (y == 0) return 0;
    return x << @intCast(@ctz(y));
}
```

x86 znver4 emit:

```asm
foo:
        blsi    rax, rsi
        imul    rax, rdi
        ret

bar:
        tzcnt   rax, rsi
        shlx    rax, rdi, rax
        cmovb   rax, rsi
        ret
```

RISC-V sifive_u74 emit:

```asm
foo:
        neg     a2, a1
        and     a1, a1, a2
        mul     a0, a1, a0
        ret

.LCPI1_0:
        .quad   151050438420815295
.LCPI1_1:
        .ascii  "\000\001\002\007\003\r\b\023\004\031\016\034\t\"\024(\005\021\032&\017.\0350\n\037#6\0252)9?\006\f\022\030\033!'\020%-/\036518>\013\027 $,47=\026+3<*;:"
bar:
        beqz    a1, .LBB1_2
        lui     a2, %hi(.LCPI1_0)
        neg     a3, a1
        and     a1, a1, a3
        ld      a2, %lo(.LCPI1_0)(a2)
        mul     a1, a1, a2
        lui     a2, %hi(.LCPI1_1)
        srli    a1, a1, 58
        addi    a2, a2, %lo(.LCPI1_1)
        add     a1, a1, a2
        lbu     a1, 0(a1)
        sll     a0, a0, a1
        ret
.LBB1_2:
        li      a0, 0
        ret
```

**Comment by nikic** [comment]
I think the ask is for this transform? https://alive2.llvm.org/ce/z/Aht97G

**Comment by nikic** [comment]
@dtcxzyw @goldsteinn I'm a bit unsure on whether this is better suited as a middle-end or back-end transform. Any thoughts?

**Comment by Validark** [comment]
> Could you also include the LLVM IR that gets generated for both functions (and ideally also an alive2 proof that the transformation is correct)?

I think @nikic already provided you what you were asking for, but the reason this works is as follows: The idiom `(y & (~y +% 1))`, or perhaps `y & -y` in C, extracts the lowest set bit, hence the `blsi` emit on x86. Multiplying `a * b` at a bit level is equivalent to `(a << 0)*b₀ + (a << 1)*b₁ + (a << 2)*b₂ + (a << 3)*b₃ + (a << 4)*b₄ + (a << 5)*b₅ + (a << 6)*b₆ + (a << 7)*b₇ + ...`, where `b₀` is the least significant bit of `b`. In this case, only one of the bits of `b` is a `1`, so the answer is one of the terms in the previous expression. That's why `a << @ctz(b)` is equivalent to `a * b` when the popcount of `b` is 1.

**Comment by Validark** [comment]
Related https://github.com/llvm/llvm-project/issues/76810

**Comment by dtcxzyw** [comment]
> @dtcxzyw @goldsteinn I'm a bit unsure on whether this is better suited as a middle-end or back-end transform. Any thoughts?

We can canonicalize `x * (y & -y)` into `x << cttz(y)` in `InstCombine`. Then we reverse the transform in CGP if `cttz` is not natively supported by the target.

Alive2: https://alive2.llvm.org/ce/z/vhskjz

**Comment by dtcxzyw** [comment]
Confirmed that the pattern `x * (y & -y)` exists in `openmpi` :)

**Comment by Explorer09** [comment]
Is this the same issue that I've reported in GCC bug tracker? [GCC bug 114341](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=114341)

Just for reference :)
