### ISSUE TITLE
[consteval] Inside consteval member function: use of 'this' pointer is only allowed within the evaluation of a call to a 'constexpr' member function

### ISSUE THREAD

**Issue by CarloWood** [llvm/llvm-project#84810]
The following snippet:

```c++
template<int Id>
struct SymbolRef { };

struct Symbol {
  int const id_;

  consteval Symbol() : id_(1) { }

  template<int Id>
  consteval operator SymbolRef<Id>() const
  {
    return SymbolRef<this->id_>{};
  }
}
```

results in the compile error:

```
<source>:12:22: error: non-type template argument is not a constant expression
   12 |     return SymbolRef<this->id_>{};
      |                      ^~~~~~~~~
<source>:12:22: note: use of 'this' pointer is only allowed within the evaluation of a call to a 'constexpr' member function
1 error generated.
```

g++ compiles this without errors.

I think the code is well-formed?

**Comment by CarloWood** [comment]
Note: using `return SymbolRef<id_>{};` (without the `this->`) also doesn't compile with g++. I think that is a bug in gcc however. Imho both should compile (with or without `this->`).

**Comment by efriedma-quic** [comment]
Template parameters have to be constant independent of the context, even in a consteval function.

gcc also diagnoses this, it just waits until you try to instantiate the template.
