### ISSUE TITLE
[libc++] `<random>`: Enforce `seed_seq::generate()`'s mandate for `RandomAccessIterator`

### ISSUE THREAD

**Issue by StephanTLavavej** [llvm/llvm-project#84843]
[N4971](https://isocpp.org/files/papers/N4971.pdf) \[rand.util.seedseq\]/7:

> ```cpp
> template<class RandomAccessIterator>
>   void generate(RandomAccessIterator begin, RandomAccessIterator end);
> ```
> *Mandates:* `iterator_traits<RandomAccessIterator>::value_type` is an unsigned integer type capable of accommodating 32-bit quantities.

This example should be rejected, but isn't: https://godbolt.org/z/86qrr5PEa

```cpp
#include <random>

int main() {
    std::seed_seq seq;
    int arr[1];
    seq.generate(arr, arr + 1); // should be rejected!
}
```

(MSVC's STL was also affected: https://github.com/microsoft/STL/issues/4434 )

**Comment by ldionne** [comment]
This is the eel.is link: https://eel.is/c++draft/rand.util.seedseq#7

Thanks for the report, this seems easy to fix.
