### ISSUE TITLE
Support -H during compilation

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#8487]
|  |  |
| --- | --- |
| Bugzilla Link | [8115](https://llvm.org/bz8115) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
In GCC, the -H option works during compilation as well as preprocessing. This is marginally useful sometimes, Clang should support it if easy:
--
ddunbar@ozzy:tmp$ cat t.c
#include <stdio.h>

ddunbar@ozzy:tmp$ gcc -H -c t.c
. /usr/include/stdio.h
.. /usr/include/_types.h
... /usr/include/sys/_types.h
.... /usr/include/sys/cdefs.h
.... /usr/include/machine/_types.h
..... /usr/include/i386/_types.h
.. /usr/include/secure/_stdio.h
... /usr/include/secure/_common.h
Multiple include guards may be useful for:
/usr/include/secure/_stdio.h
ddunbar@ozzy:tmp$ clang -H -c t.c
ddunbar@ozzy:tmp$ 
--

**Comment by philnik777** [comment]
This is now supported by clang: https://godbolt.org/z/qb3vdxPo4
