### ISSUE TITLE
[DAG] SelectionDAG::computeKnownBits - add ISD::ABDU/ISD::ABDS handling

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#84905]
We now have KnownBits::abdu/abds implementations, so we can now add this to computeKnownBits.

The actual addition of the code is trivial, a little more work will be adding suitable tests - I'd recommend using aarch64 as it has dedicated ABD vector intrinsics:

```ll
declare <8 x i16> @llvm.aarch64.neon.uabd.v8i16(<8 x i16>, <8 x i16>)
declare <8 x i16> @llvm.aarch64.neon.sabd.v8i16(<8 x i16>, <8 x i16>)
```

**Comment by SahilPatidar** [comment]
@RKSimon,
I would like to work on this one

**Comment by SahilPatidar** [comment]
@RKSimon This is my first issue related to SelectionDAG. Could you please suggest some good starting points?

**Comment by RKSimon** [comment]
The actual implementation is straightforward - just add ABDS/ABDU variants similar to the existing MULH case:
https://github.com/llvm/llvm-project/blob/99be3875fb161a5786aaad5dab0b92fa052e47d1/llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp#L3385-L3396

The harder bit is creating knowbits tests, using the aarch intrinsics
