### ISSUE TITLE
[DirectX] [DXIL] Document Specification Details of DXIL Operations in DXIL.td

### ISSUE THREAD

**Issue by bharadwajy** [llvm/llvm-project#84932]
DXIL.td should be single source of reference for all DXIL operations. It should be subsume all relevant and applicable functionalities of [hctdb.py](https://github.com/microsoft/DirectXShaderCompiler/blob/main/utils/hct/hctdb.py) and other hct utilities.

Document the choices made to describe DXIL operations in `DXIL.td` along with the principles of design choices made. 

PR #85170

**Comment by davidcook-msft** [comment]
Spec to be updated to identify what is the minimum amount of information required to lower to DXIL.  Related to #91489
