### ISSUE TITLE
Flang should handle the -mtune option

### ISSUE THREAD

**Issue by tukss** [llvm/llvm-project#84947]
`flang-new` already knows about the `-march` option but not about `-mtune`. `clang` (and also `gcc`/`gfortran`) handles both options. For context, `-mtune` produces code that's optimized for a certain subarchitecture (say `haswell` or `zen3`) while retaining compatibility with other subarchitectures, whereas `-march` might produce illegal instructions when run on the wrong hardware.

My reason for asking is that is makes it hard to use `flang-new` within [Spack](https://github.com/spack/spack). Spack handles `flang-new` as the Fortran component of the `clang` compiler but unfortunately doesn't provide a way to specify different compiler flags for the C, C++, and Fortran compilers. `-mtune` is used as an option for most architectures (e.g., [here](
https://github.com/spack/spack/blob/develop/lib/spack/external/archspec/json/cpu/microarchitectures.json)), which breaks using `flang-new` to build anything with Spack.

Even if `-mtune` wasn't implemented immediately it would at least be helpful if `flang-new` wouldn't just stop compilation but just display a warning and continue.

**Comment by AlexisPerry** [comment]
PR for basic mtune support: https://github.com/llvm/llvm-project/pull/95043

**Comment by banach-space** [comment]
@AlexisPerry , thanks for working on this! Given that https://github.com/llvm/llvm-project/pull/95043 has landed, can we close this ticket?

**Comment by tukss** [comment]
I was just about to test it but then I've seen it has been reverted in #96678.
So I guess we leave this open for now.

**Comment by AlexisPerry** [comment]
https://github.com/llvm/llvm-project/pull/95043 was reverted.  A fixed version of the patch has been posted: https://github.com/llvm/llvm-project/pull/96688

**Comment by AlexisPerry** [comment]
PR https://github.com/llvm/llvm-project/pull/98517 has been merged.  @tukss Could you check to see if the issue still persists?  Thank you.
