### ISSUE TITLE
Code using a lambda to capture a reference to a function rejected with `could not match (null template argument) against (null template argument)`

### ISSUE THREAD

**Issue by abbeyj** [llvm/llvm-project#84961]
The following code is accepted by other compilers but rejected by clang.  The error message is a bit weird.

```C++
template<typename T>
void g(const T& t) {
}

template<typename T>
void f(const T& t) {
  [t] { g(t); };
}

void h() {
}

int main() {
  f(h);
}
```

Output:
```
<source>:7:9: error: no matching function for call to 'g'
    7 |   [t] { g(t); };
      |         ^
<source>:7:7: note: while substituting into a lambda expression here
    7 |   [t] { g(t); };
      |       ^
<source>:14:3: note: in instantiation of function template specialization 'f<void ()>' requested here
   14 |   f(h);
      |   ^
<source>:2:6: note: candidate template ignored: could not match (null template argument) against (null template argument)
    2 | void g(const T& t) {
      |      ^
```

Changing the call `g(t)` to be either `g<T>(t)` or `g<void()>(t)` changes the error message to:

```
note: candidate function template not viable: 1st argument ('void (const()') would lose const qualifier
```

Note that the type mentioned here (`void (const()`) has unbalanced parentheses.

Workaround: change the lambda capture from `[t]` to `[t=t]`.

This code was accepted by clang 3.0.0 but is rejected by all version from 3.1 to the latest trunk currently available on Godbolt.

Godbolt link: https://godbolt.org/z/d87rPjja4

**Comment by Sirraide** [comment]
Ok, yeah, there’s something very wrong here. I’ll see if I can take a look at this.

**Comment by Sirraide** [comment]
The AST for the type of `t` in `g(t)`:
```
QualType 0x5585adce8131 'void (const(void)' const
`-SubstTemplateTypeParmType 0x5585adce8130 'void (void)' sugar typename depth 0 index 0 T
  |-FunctionTemplate 0x5585adccb838 'f'
  `-FunctionProtoType 0x5585adccbdf0 'void (void)' cdecl
    `-BuiltinType 0x5585adc7f2c0 'void'
```

**Comment by zyn0217** [comment]
@Sirraide You have any progress with it? Otherwise I think I have figured out why and it's seemingly not hard to fix.

**Comment by Sirraide** [comment]
> You have any progress with it?

Ah, no, my bad, I somehow completely lost track of this issue..
