### ISSUE TITLE
[libc] Implement fcntl function

### ISSUE THREAD

**Issue by SchrodingerZhu** [llvm/llvm-project#84968]
This is currently missing. It is useful when checking fd flags.

**Comment by 1366240475** [comment]
@nickdesaulniers I'd like to work on this.

**Comment by SchrodingerZhu** [comment]
The function itself is defined in:

https://man7.org/linux/man-pages/man2/fcntl.2.html

https://pubs.opengroup.org/onlinepubs/007904975/functions/fcntl.html

For Linux, it should be simply a syscall wrapper.

https://elixir.bootlin.com/linux/latest/source/fs/fcntl.c

**Comment by SchrodingerZhu** [comment]
You can refer to #84974. It is still a WIP PR, but it shows what files would a syscall wrapper implementation typically involve.

**Comment by vinayakdsci** [comment]
Hi @l32zhao, are you still working on this? Otherwise I'd be happy to take this issue up. Thanks!
