### ISSUE TITLE
Flang does not match any OpenMPI subroutine when called with an element of an assumed-shape array

### ISSUE THREAD

**Issue by tukss** [llvm/llvm-project#84970]
Below you see a simple MPI Fortran program which doesn't compile with flang-new using `use
mpi` or `use mpi_f08` but works fine with `include 'mpif.h'`. I'm testing with OpenMPI (version 4.1.6).

This only seems to be triggered when you pass an array into a subroutine as an assumed-shape array and use a single element of it as the argument to `mpi_recv`. Putting the same call to `mpi_recv` into the main program body works fine.

This is the error I'm getting:
```
./mpitest.f90:34:5: error: No specific subroutine of generic 'mpi_recv' matches the actual arguments
      call mpi_recv(x(5), 1, MPI_INTEGER, 0, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE, ierr)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
     

The same program works fine and correctly using gfortran.

This is the test program:
```f90
program test
  ! Neither of these options work with flang-new.
  use mpi
  ! use mpi_f08

  ! This compiles with flang-new
  ! include 'mpif.h'
  
  integer :: rank, ierr
  integer, parameter :: n=10
  integer :: b(n)

  call mpi_init(ierr)

  call mpi_comm_rank(MPI_COMM_WORLD, rank, ierr)

  b = rank

  if (rank == 0) then
     call mpi_ssend(b(1), 1, MPI_INTEGER, 1, 0, MPI_COMM_WORLD, ierr)
  else
     call recv(b)
  end if

  print*, rank, ': ', b

  call mpi_finalize(ierr)

contains
  subroutine recv(x)
    integer :: x(:)
    call mpi_recv(x(5), 1, MPI_INTEGER, 0, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE, ierr)
  end subroutine recv
end program test
```

**Comment by tukss** [comment]
Just as another data point, assumed-size arrays `x(*)` work fine here.

**Comment by klausler** [comment]
Assumed-shape dummy arrays are not `CONTIGUOUS` unless explicitly attributed so.  Storage association rules do not apply to their elements, as they do with contiguous storage (like assumed-size or explicit shape arrays).

**Comment by tukss** [comment]
Thank you for that pointer. It does compile and work if I use the `CONTIGUOUS` attribute on the array argument. I wasn't aware that accessing a single element of a rank 1 assumed-shape array doesn't just give me the same as a scalar.

This is actually being triggered by real-world code, such as [here](https://github.com/geodynamics/Rayleigh/blob/75f66679ed0c309fea8e3d1083a9ae198580b8ae/src/Parallel_Framework/SendReceive.F90#L656). Gfortran and ifort never complained about it. I'll look at the standard more closely to understand the detailed semantics here.

**Comment by klausler** [comment]
It does give you a scalar; but it's not a scalar array element that can be argument-associated as a storage sequence, which is what the explicit interface needs.

**Comment by klausler** [comment]
Can you please post the interfaces of the specific procedures for `mpi_recv` that might have been called (or just the contents of the mpi.mod file that you have)?  I'll double-check my analysis to make sure that we don't have a bug here.

**Comment by tukss** [comment]
Thank you for analyzing this. There is only one interface for `mpi_recv` in `mpi.mod`.

```f90
interface
subroutine mpi_recv(buf,count,datatype,source,tag,comm,status,ierror)
real(4)::buf(1_8:*)
!dir$ ignore_tkr(tkrdm) buf
integer(4),intent(in)::count
integer(4),intent(in)::datatype
integer(4),intent(in)::source
integer(4),intent(in)::tag
integer(4),intent(in)::comm
integer(4),intent(out)::status(1_8:6_8)
integer(4),intent(out)::ierror
end
end interface
! ...
interface mpi_recv
procedure::mpi_recv
end interface
```

The F90 interface is not standard compliant anyway as the MPI standard discusses. As the `mpi_f08` module fails in the same way, I'm sharing the respective parts of that module, too.

```f90
interface
subroutine mpi_recv_f08(buf,count,datatype,source,tag,comm,status,ierror)
use mpi_f08_types,only:mpi_comm
use mpi_f08_types,only:mpi_datatype
use mpi_f08_types,only:mpi_status
real(4)::buf(1_8:*)
!dir$ ignore_tkr(tkrdm) buf
integer(4),intent(in)::count
type(mpi_datatype),intent(in)::datatype
integer(4),intent(in)::source
integer(4),intent(in)::tag
type(mpi_comm),intent(in)::comm
type(mpi_status)::status
integer(4),intent(out),optional::ierror
end
end interface
! ...
interface mpi_recv
procedure::mpi_recv_f08
end interface
```

I'm a bit surprised that `type(*)` isn't used in the `mpi_f08` interface.

**Comment by klausler** [comment]
Thanks; yes, that confirms my analysis.  If your data are not contiguous at runtime, then your application may have been saved from weird failures that other compilers should have also prevented.  And if your data actually are contiguous, the `CONTIGUOUS` attribute will help you keep things safe, if you can use it on the assumed-shape dummy argument.  (If you can't, there's other ways to work around this, like associating a `CONTIGUOUS` rank-1 pointer with an array element, and then passing the pointer.)

**Comment by tukss** [comment]
I've just tried the same using mpich 4.1.2. My example program actually compiles fine there. This is the interface for `use mpi`:
```f90
interface
subroutine mpi_recv(buf,count,datatype,source,tag,comm,status,ierr)
real(4)::buf
!dir$ ignore_tkr(tkrdm) buf
integer(4)::count
integer(4)::datatype
integer(4)::source
integer(4)::tag
integer(4)::comm
integer(4)::status(1_8:5_8)
integer(4)::ierr
end
end interface
```

So I guess it works here because the `buf` dummy variable isn't defined as an array in the interface but as a scalar.

Another interesting finding: I noticed that the `mpi_f08` is not built at all using mpich. The reason is a failing test for Fortran 2008 support  in the `configure` script of mpich. The test source they use is [here](https://github.com/pmodels/mpich/blob/main/confdb/aclocal_fc.m4#L1105) and this is the error I get when I try to compile it:
```
error: loc("/[...]/test.f90":56:33): /vast/home/pedelmann/ngc-home/llvm-flang/flang/lib/Lower/ConvertVariable.cpp:1846: not yet implemented: assumed-rank variable in procedure implemented in Fortran
LLVM ERROR: aborting
```

Do you think the test is actually an indicator for a missing F2008 feature in flang or is it the authors of the test interpreting the standard in a wrong way?

**Comment by tblah** [comment]
@tukss flang spells the continguity check for ignore_tkr with a `c`: e.g. `dir$ ignore_tkr(tkrdmc) buf`. Does adding the `c` help? See discussion here: https://github.com/llvm/llvm-project/pull/78196

**Comment by tukss** [comment]
@tblah You were spot on. I've just tried editing OpenMPI's generated  `mpi.mod` adding a `c` to the directive for `mpi_recv`. After outsmarting the module checksum, `flang` compiles my example fine.

It looks like the `(tkrdmc)` part is generated by flang when it builds a module, so I guess this isn't something that could be added to OpenMPI.

**Comment by tblah** [comment]
@tukss I think this was fixed in upstream openmpi: https://github.com/open-mpi/ompi/pull/12512 does this resolve everything you need?

Thanks @pawosm-arm for diagnosing the issue and reporting it to openmpi

**Comment by tukss** [comment]
Yes, the problem is fixed in the current `main` branch of OpenMPI. Thank you!

**Comment by tukss** [comment]
I've double checked that [Rayleigh](https://github.com/geodynamics/Rayleigh) builds fine with flang and OpenMPI (`main` branch) now. This includes the F77, F90, and F08 MPI bindings. That's great. Thanks to everyone who helped fixing this!
