### ISSUE TITLE
libcxx/src/algorithms.cpp doesn't compile with c++17

### ISSUE THREAD

**Issue by niranjanyardi** [llvm/llvm-project#84985]
This line in libcxx/src/algortihms.cpp

auto depth_limit = 2 * std::__bit_log2(static_cast<size_t>(last - first));

is not able to compile when c++ standard is set to 17 

The root cause seems to be that definition in  libcxx/include/__bit/bit_log2.h is gaurded by a c++20 version check like this:

#if _LIBCPP_STD_VER >= 20

template <__libcpp_unsigned_integer _Tp>
_LIBCPP_HIDE_FROM_ABI constexpr _Tp __bit_log2(_Tp __t) noexcept {
  return numeric_limits<_Tp>::digits - 1 - std::countl_zero(__t);
}

#endif // _LIBCPP_STD_VER >= 20

a) How do we substitute the std::__bit_log2() call for C++17
b) IF this is a bug when will this be fixed ?

**Comment by philnik777** [comment]
libc++ is always built in C++23 mode. I'm not sure how you got it things to build in C++17 mode, but it's definitely not supported. There is no reason to build things with any other standard.
