### ISSUE TITLE
[libc][c11] add support for stdio.h's rename()

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#84980]
See also `7.23.4.2 The rename function` in n3096

libc++ needs this for [LIBCXX_ENABLE_FILESYSTEM](https://libcxx.llvm.org/BuildingLibcxx.html#cmdoption-arg-LIBCXX_ENABLE_FILESYSTEM-BOOL) support.

**Comment by aniplcc** [comment]
Would the implementation be somewhat as in stdio.h's remove() using syscalls? I'll create a PR.

**Comment by AtharvKshirsagar** [comment]
Hi I am Atharv Kshirsagar from IIT Bombay.I would like to request you to grant me access to the issue.Thanks

**Comment by nickdesaulniers** [comment]
Hi @AtharvKshirsagar , @aniplcc already is working on this (is assigned, and their PR is linked above).  Thanks for your interest, but there may be another bug that's a better place to start.
