### ISSUE TITLE
[DAG] SDPatternMatch - add m_Neg and m_Not matchers

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#85065]
I've started using the SDPatternMatch.h matchers to simplify dag combines (especially commutable ones - thank you for that!).

We're currently missing a couple of convenience matchers for
```c
m_Neg(m_Value(X)) == m_Sub(m_Zero(), m_Value(X))
m_Not(m_Value(X)) == m_Xor(m_Value(X), m_AllOnes())
```
You will need some experience with C++ templates to understand the pattern matching system to add these.

CC @mshockwave

**Comment by ZiCong-Wang** [comment]
@RKSimon Hi. I would like to work on it as my first issue.

**Comment by mshockwave** [comment]
yeah I think this is a good first issue, thank you @RKSimon 
@ZiCong-Wang let me know if you need any help.

**Comment by ZiCong-Wang** [comment]
@mshockwave Is there anything I need to provide except m_Neg and m_Not functions?

**Comment by RKSimon** [comment]
- [ ] Add SDPatternMatch m_Neg / m_Not pattern matchers
- [ ] Update existing m_Sub(m_Zero(), ...) patterns in DAGCombiner.cpp to m_Neg(...)
- [ ] Test coverage in SelectionDAGPatternMatchTest.cpp

**Comment by mshockwave** [comment]
> @mshockwave Is there anything I need to provide except m_Neg and m_Not functions?

Basically what Simon mentioned in the comment above. Note that for the second action item (update patterns in DAGCombiner), please remember to validate your changes by running all the codegen tests. The most common way would be `ninja check-llvm-codegen` (or `make check-llvm-codegen`).
