### ISSUE TITLE
clang gets confused by ambiguities in template-name checks introduced by using directives

### ISSUE THREAD

**Issue by rjmccall** [llvm/llvm-project#8509]
|  |  |
| --- | --- |
| Bugzilla Link | [8137](https://llvm.org/bz8137) |
| Version | unspecified |
| OS | All |
| CC | @DougGregor |

## Extended Description 
```cpp
namespace A {
  template <class T> class foo;
}
using namespace A;

template <class T> void foo();
template <> void foo<int>();
```

**Comment by shafik** [comment]
This looks fixed: https://godbolt.org/z/W111sT9zT
