### ISSUE TITLE
[Clang] `AttributedType`s are stripped from lambda function types

### ISSUE THREAD

**Issue by Sirraide** [llvm/llvm-project#85120]
Consider
```c++
struct S {
  void g() const [[clang::annotate_type("foo", "bar", 1)]] {}
};

void f() {
  auto l = [] () [[clang::annotate_type("foo", "bar", 1)]] {};
}
```

AST dump prints `'void () const [[clang::annotate_type(...)]]':'void () const'` for the type of `S::g()`, but `void () const` for the type of `l`, which is problematic if someone actually wants to use this information for something (#84983). We should fix this unless there’s a good reason why we’re desugaring the function type here.

**Comment by shafik** [comment]
CC @erichkeane @AaronBallman

**Comment by Sirraide** [comment]
So it seems this is happening because `adjustDeducedFunctionResultType()` doesn’t care about sure; I’ll try and see if changing that helps (if we even get to that point because we’re currently crashing before we ever get there because of #85154, which I’m currently looking into).
