### ISSUE TITLE
Duplicate (?) error on function pointer assignment with incompatible exception specification

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#8512]
|  |  |
| --- | --- |
| Bugzilla Link | [8140](https://llvm.org/bz8140) |
| Version | unspecified |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
Testcase:
```c++
void (*pf)() throw(int);
void f() {
  pf = f;
};
```
Error output:
```
<stdin>:3:8: error: target exception specification is not superset of source
  pf = f;
       ^
<stdin>:3:6: error: assigning to 'void (*)() throw(int)' from incompatible type
      'void ()'
  pf = f;
     ^ ~
```
This should be one error (possibly with a note), not two pointing out the same issue.

**Comment by philnik777** [comment]
Fixed in Clang 4.0: https://godbolt.org/z/d6Wsn3dTv
