### ISSUE TITLE
Stuck in Compiling `libc/src/stdfix`

### ISSUE THREAD

**Issue by zixuanweeei** [llvm/llvm-project#85169]
Building CMD:
```
CC=clang CXX=clang++ cmake ../llvm -GNinja -DCMAKE_INSTALL_PREFIX=$HOME/.local/llvm-main -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;compiler-rt;cross-project-tests;libc;libclc;lld;lldb;openmp;polly;pstl;mlir;bolt" -DLLVM_ENABLE_RUNTIMES=all -DCMAKE_BUILD_TYPE=Release

ninja install
```

Clang Version:

```
$ clang --version

clang version 19.0.0git (8c5e9cf737138aba22a4a8f64ef2c5efc80dd7f9)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: ${HOME}/.local/llvm-main/bin
```

OS Version:

```
$ cat /etc/os-release

PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

The building seems go into deep universe after runtimes being completed

```
[11484/11530] Performing build step for 'runtimes'
[1331/1331] Linking CXX static library /path/to/llvm-project/build/lib/x86_64-unknown-linux-gnu/libc++.a                                                                  [11518/11530] No install step for 'runtimes'
[11520/11530] Completed 'runtimes'
```

Looking into the processes of clang++, I found that it is compiling the sources in `libc/src/stdfix/`.

**Comment by zixuanweeei** [comment]
Project commit: 15a55486a54183d4fc597ed86c0d49fe9482f2bd

**Comment by lntue** [comment]
I think it is because `libc` is included in both `LLVM_ENABLE_PROJECTS` and `LLVM_ENABLE_RUNTIMES` (implicitly in `all`).  Can you try removing `libc` from the `LLVM_ENABLE_PROJECTS` to see if it fixes the problem?

**Comment by zixuanweeei** [comment]
> I think it is because `libc` is included in both `LLVM_ENABLE_PROJECTS` and `LLVM_ENABLE_RUNTIMES` (implicitly in `all`). Can you try removing `libc` from the `LLVM_ENABLE_PROJECTS` to see if it fixes the problem?

That's a good point. It works like a charm. Thanks.

BTW, there is a note in https://llvm.org/docs/CMake.html

> Note: the list should not have duplicates with LLVM_ENABLE_PROJECTS.

Closing this issue.
