### ISSUE TITLE
Miscompile of musl-c memset on ARM

### ISSUE THREAD

**Issue by AtariDreams** [llvm/llvm-project#85176]
comparing the assembler output of memset from the Musl-C library, I noticed that the final compilation is missing the assignment of the sum of r2 (which would be the size argument) and r0 (the pointer argument). This doesn't happen in LLVM-17. 

As a result, memory is being written right before the dest pointer instead of at the tail end. 

![image](https://github.com/llvm/llvm-project/assets/83477269/774c4a7c-1d08-40fa-9358-11a0253ede30)

**Comment by AtariDreams** [comment]
This affects LLVM-18.1.0 release version and 18.1.1

**Comment by davemgreen** [comment]
It looks like the `strb r1, [r3], r2` is already calculating r3=r3+r2 (and r3=r0). Are you sure this is incorrect?

**Comment by AtariDreams** [comment]
> It looks like the `strb r1, [r3], r2` is already calculating r3=r3+r2 (and r3=r0). Are you sure this is incorrect?

I forgot post indexing was a thing.
