### ISSUE TITLE
[lldb-dap] Support for Swift

### ISSUE THREAD

**Issue by wojciech-kulik** [llvm/llvm-project#85237]
Please consider adding support for Swift in `lldb-dap`, currently the debugger is unable to show correctly local variables and frames.

**Comment by JDevlieghere** [comment]
Because of the dependency on the Swift compiler, there is no Swift support in LLDB upstream. All swift support lives on Apple's Swift fork: https://github.com/apple/llvm-project where `lldb-dap` supports Swift.
