### ISSUE TITLE
missed fold, fcmp ogt (x - y), 0 => fcmp ogt x, y

### ISSUE THREAD

**Issue by zhengyang92** [llvm/llvm-project#85245]
https://alive2.llvm.org/ce/z/azHAHq
https://godbolt.org/z/M8WbdYE8x

```llvm
define i1 @src(float %0, float %1) {
%t2 = fsub float %0, %1
%t3 = fcmp ogt float %t2, 0.000000e+00
ret i1 %t3
}

define i1 @tgt(float %0, float %1) {
%olt = fcmp ogt float %0, %1
ret i1 %olt
}
```
@jayfoad @regehr

**Comment by SahilPatidar** [comment]
@dtcxzyw, I would like to take this one.

**Comment by jayfoad** [comment]
This only works for floating point formats that have IEEE-like denormals (does LLVM currently support any formats that do _not_ have denormals?), and when denormals are not being flushed to zero. Otherwise you can have two _different_ values `x` and `y` where `x - y` evaluates to 0.

**Comment by jayfoad** [comment]
As a follow up we could do the same kind of thing for plus, e.g. `fcmp (x + y), 0 => fcmp x, -y`, if either `x` or `y` can be negated for free.
