### ISSUE TITLE
LLVM stack alignment doesn't match gcc's requirements on Linux32

### ISSUE THREAD

**Issue by edwintorok** [llvm/llvm-project#8524]
|  |  |
| --- | --- |
| Bugzilla Link | [8152](https://llvm.org/bz8152) |
| Version | trunk |
| OS | Linux |
| CC | @asl,@sunfishcode |

## Extended Description 
... which causes the gcc compiled function to crash because it expects 16-byte aligned stack (in gcc 4.4 at least with -fpmath=sse).

I'm told that older gcc's don't require (or set) 16, so just setting 16-byte would break older ones.

This seems to be a good solution:
richi: well, just make sure outgoing stack boundary is always 16-byte and do not assume anything about incoming stack alignemnt

Idea from aKor:
(12:37:18 PM) aKor: [13:32] aKor: edwin: but maintaining outgoing stack boundary is certainly possible in "common cases"
(12:37:18 PM) aKor: [13:32] aKor: (without dynamic allocas)
(12:37:34 PM) aKor: this seems to be the best way wrt backward compatibility stuff

**Comment by arsenm** [comment]
X86Subtarget has this so I'm assuming this is fixed:

```
  // Stack alignment is 16 bytes on Darwin, Linux, kFreeBSD, NaCl, and for all
  // 64-bit targets.  On Solaris (32-bit), stack alignment is 4 bytes
  // following the i386 psABI, while on Illumos it is always 16 bytes.
  if (StackAlignOverride)
    stackAlignment = *StackAlignOverride;
  else if (isTargetDarwin() || isTargetLinux() || isTargetKFreeBSD() ||
           isTargetNaCl() || Is64Bit)
    stackAlignment = Align(16);
```
