### ISSUE TITLE
missed fold, fneg(t ? c1 : c2) => t ? -c1 : -c2

### ISSUE THREAD

**Issue by zhengyang92** [llvm/llvm-project#85251]
https://alive2.llvm.org/ce/z/RWUbrQ
https://godbolt.org/z/qd5Tqbrzc

```llvm
define float @src(i1 %0) {
entry:
%t2 = select i1 %0, float -1.000000e+00, float 1.000000e+00
%t3 = fneg float %t2
ret float %t3
}

define float @tgt(i1 %0) {
entry:
%sel = select i1 %0, float 1.000000e+00, float -1.000000e+00
ret float %sel
}
```

@jayfoad @regehr

**Comment by 1366240475** [comment]
I'd like to work on this

**Comment by dtcxzyw** [comment]
Please read the [guide](https://github.com/llvm/llvm-project/pull/79007/files) before posting your patch :)

**Comment by HendrikHuebner** [comment]
@l32zhao Are you still going to work on this? Otherwise I'd like to take this issue

**Comment by dtcxzyw** [comment]
It has been handled by https://github.com/llvm/llvm-project/pull/89947.
