### ISSUE TITLE
missed FP fold, (x >= 0) ? x : -x == 0 => x == 0

### ISSUE THREAD

**Issue by zhengyang92** [llvm/llvm-project#85250]
https://alive2.llvm.org/ce/z/NFEKjp
https://godbolt.org/z/7Ef9Kf4s3
```llvm
define i1 @src(float %0) {
entry:
%1 = fcmp oge float %0, 0.000000e+00
%2 = fneg float %0
%3 = select i1 %1, float %0, float %2
%4 = fcmp oeq float %3, 0.000000e+00
ret i1 %4
}

define i1 @tgt(float %0) {
entry:
%oeq = fcmp oeq float %0, 0.000000e+00
ret i1 %oeq
}
```
@jayfoad @regehr

**Comment by SahilPatidar** [comment]
@dtcxzyw, I'd be happy to take a look at this issue.

**Comment by SahilPatidar** [comment]
@dtcxzyw, Does this whole expression need to be folded, or has some work already been done on it?

**Comment by jayfoad** [comment]
I think this generalizes to `cond ? x : -x == 0 => x == 0` for any condition `cond`.

**Comment by regehr** [comment]
@jayfoad looks like it!

https://alive2.llvm.org/ce/z/VgXu2n
