### ISSUE TITLE
[libc] implement pipe2

### ISSUE THREAD

**Issue by michaelrj-google** [llvm/llvm-project#85289]
The pipe2 is defined on linux here: https://man7.org/linux/man-pages/man2/pipe.2.html

This is a simple syscall wrapper, so implementation should be straightforward.

### Build System

In [entrypoints.txt](https://github.com/llvm/llvm-project/blob/main/libc/config/linux/x86_64/entrypoints.txt)
- [ ] Add the new function to the list of entrypoints for unistd.h (you need to do this before it will build)

In [unistd/CMakeLists.txt](https://github.com/llvm/llvm-project/blob/main/libc/src/unistd/CMakeLists.txt)
- [ ] Add new entrypoint objects to the list
- [ ] Also add it to the list for unistd/linux/CMakeLists.txt

In [linux.td](https://github.com/llvm/llvm-project/blob/main/libc/spec/linux.td)
- [ ] Add the functions to the list of functions for unistd.h (this can be confusing, ask for help if you're stuck).

### Code

Create `unistd/pipe2.h`
- [ ] look at [dup.h](https://github.com/llvm/llvm-project/blob/main/libc/src/unistd/dup.h) for an example of how this should be laid out (copying the whole file and modifying it is fine).

Create `unistd/linux/pipe2.cpp`
- [ ] Again, look at look at [linux/dup.cpp](https://github.com/llvm/llvm-project/blob/main/libc/src/unistd/linux/dup.cpp) for an example.

### Testing

Create `test/src/unistd/pipe2_test.cpp`
- [ ] This needs to test the function succeeding and failing
- [ ] This is only testing the code you wrote, so don't worry too much about testing parts of the interface that the kernel handles.

Add your tests to [test/src/unistd/CMakeLists.txt](https://github.com/llvm/llvm-project/blob/main/libc/test/src/unistd/CMakeLists.txt)
- [ ] Hopefully self-explanatory

**Comment by muffpy** [comment]
Interested

**Comment by muffpy** [comment]
@michaelrj-google Under build system, did you mean add the function spec for pipe2 to [posix.td](https://github.com/llvm/llvm-project/blob/main/libc/spec/posix.td)? I don't see a header spec for unistd.h in [linux.td](https://github.com/llvm/llvm-project/blob/main/libc/spec/linux.td).

**Comment by michaelrj-google** [comment]
I did mean to put it in `linux.td` since it's specifically a linux function and not in posix. If there isn't a `unistd.h` `HeaderSpec` in `linux.td` yet then you'll have to create a new one and add it to the list of headers at the bottom.

**Comment by muffpy** [comment]
@michaelrj-google Should this `HeaderSpec` in linux.td contain `FunctionSpec`s for every syscall in libc/src/unistd/ or just for pipe2?

**Comment by michaelrj-google** [comment]
just `pipe2` is fine for the moment

**Comment by muffpy** [comment]
@michaelrj-google I am unable to generate the test file for pipe2_test.cpp. I have tried:

```
$ cmake ../llvm -G Ninja -DLLVM_ENABLE_PROJECTS="libc"  -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
$ ninja libc_unistd_unittests
```

but the output does not show a test for pipe2.

Please take a look at my patch [85514](https://github.com/llvm/llvm-project/pull/85514).

**Comment by duncpro** [comment]
If @muffpy isn't working on this anymore I'd like to give it a go.

**Comment by nickdesaulniers** [comment]
All yours @duncpro . Reassigning.
