### ISSUE TITLE
[libc][math][c23] Implement canonicalize functions.

### ISSUE THREAD

**Issue by lntue** [llvm/llvm-project#85286]
This is defined in C23 standard: section 7.12.11.7 in https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3096.pdf

Need to support the following data types: float, single, double, float128.

**Comment by Sh0g0-1758** [comment]
Hey there @lntue, I would like to work on this.

**Comment by Sh0g0-1758** [comment]
Hey @lntue, can you provide me some pointers? I went through the doc, need a sanity check whether or not I am heading in the right direction.

**Comment by lntue** [comment]
Hi @Sh0g0-1758 , the steps needed to add a new math function is as follow:

- [ ] Add the function specification to `math.h` spec at: https://github.com/llvm/llvm-project/blob/main/libc/spec/stdc.td#L369
- [ ] Add the entry point(s) to `math.h` list in `entrypoints.txt` of your target platforms: https://github.com/llvm/llvm-project/blob/main/libc/config/linux/x86_64/entrypoints.txt#L337
- [ ] Add the function's header to `libc/src/math` folder, and its generic implementation to `libc/src/math/generic` folder.  If the implementation can work for all data types, consider putting it in `libc/src/__support/FPUtil` as header-only.
- [ ] Update `libc/src/math/CMakeLists.txt` and `libc/src/math/generic/CMakeLists.txt`
- [ ] Add unit tests for your functions.  Since these functions do not need to compared with arbitrary precision results, you only need to add smoke tests in `libc/src/math/smoke` folder.
- [ ] Update documentations in `libc/docs/math/index.rst`

You can take a look at https://github.com/llvm/llvm-project/pull/85431 or https://github.com/llvm/llvm-project/pull/84882 for the most recent examples.

About the `canonicalize` functions:
- `float`, `double`, and `float128`: these are IEEE 754 standard formats, most of the inputs are already canonical, with signaling NaNs are the only exception.
- `long double`: this will be the most trouble-some type for this functions, where you will have to deal with 3 distinct cases: long double as double, long double as float128, and x86 long double.

Let me know if you have further question.

**Comment by deeptirajora** [comment]
hey assign this issue to me please
