### ISSUE TITLE
[libc] implement __errno_location

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#85284]
Linux standard base defines this function: http://refspecs.linux-foundation.org/LSB_4.0.0/LSB-Core-generic/LSB-Core-generic/baselib---errno-location.html . I've seen it referenced by libc++.so (but not explicitly in source). We may need this at some point for compatibility, but it's not high priority.

**Comment by nickdesaulniers** [comment]
We can probably have this return the address of `__llvmlibc_errno`.

**Comment by Sh0g0-1758** [comment]
I can take this up. Can you give me some pointers to get started.

**Comment by michaelrj-google** [comment]
I'm not sure this is actually necessary. We already have an implementation of errno (https://github.com/llvm/llvm-project/blob/main/libc/src/errno/libc_errno.cpp) it just has a different name. As long as nobody's trying to link against `__errno_location` directly, the macro in the public header (https://github.com/llvm/llvm-project/blob/main/libc/include/errno.h.def#L56) should direct them to the correct definition.

**Comment by nickdesaulniers** [comment]
I'll close this for now (we can always reopen later).  At some point, we likely will have a porting guide.  When we do so, we can re-evaluate if it's necessary to mention this symbol or not. Also not yet sure what our policy is wrt. LSB.
