### ISSUE TITLE
[libc][math][c23] Implement C23 math functions nextup, nextdown.

### ISSUE THREAD

**Issue by lntue** [llvm/llvm-project#85283]
These functions are defined in C23 standard: section 7.12.11.5 and 7.12.11.6 in https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3096.pdf

Could simply be implemented using `fputil::nextafter` template.

Need to support the following data types: float, double, long double, float128.

**Comment by overmighty** [comment]
I am interested in implementing this.
