### ISSUE TITLE
missed fold, x / c < x => x > 0

### ISSUE THREAD

**Issue by zhengyang92** [llvm/llvm-project#85313]
https://alive2.llvm.org/ce/z/yG_wxp
https://godbolt.org/z/fKo893Pv1

```llvm
define i1 @src(i32 %0, i1 %1, i1 %2, i1 %3, i8 %4) {
if.then160:
  %5 = sdiv i32 %0, 131313
  %6 = icmp slt i32 %5, %0
  ret i1 %6
}


define i1 @tgt(i32 %0, i1 %1, i1 %2, i1 %3, i8 %4) {
if.then160:
  %5 = icmp sgt i32 %0, 0
  ret i1 %5
}
```

Constant 131313 can be anything but 0 or 1.

@dtcxzyw @regehr

**Comment by Poseydon42** [comment]
I would like to work on this issue.

**Comment by zhengyang92** [comment]
sdiv can be also replaced with lshr, udiv. slt/sgt can be replaced with ult/ugt.
https://alive2.llvm.org/ce/z/iNBZVy https://alive2.llvm.org/ce/z/XA_HG5
