### ISSUE TITLE
Define a generic macro for -mno-unaligned-access

### ISSUE THREAD

**Issue by wzssyqa** [llvm/llvm-project#85337]
Arm32/Arm64/LoongArch/MIPSr6/RISCV may disable unaligned memory access with option
   `-mno-unaligned-access`

Currently Arm32/Arm64 predefine `__ARM_FEATURE_UNALIGNED`, while LoongArch, RISC-V and MIPSr6 not yet.

Maybe it's time for use to define a more generic predefined macro for this case.

Will `__UNALIGN_ACCESS_DISABLED__` be OK?

For GCC, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111555

**Comment by wzssyqa** [comment]
@MaskRay any idea?

**Comment by MaskRay** [comment]
An architecture may make fine-grained choices for unaligned access (scalar vs vector, etc; RISC-V has recently got cleanup in #73971)). I think this is an area where targets may diverge large enough that a generic macro may not make sense for GCC and Clang.

**Comment by MaskRay** [comment]
On the GCC side, Richard Biener seems to reject the idea as well: https://gcc.gnu.org/pipermail/gcc-patches/2024-March/647920.html

**Comment by wzssyqa** [comment]
> On the GCC side, Richard Biener seems to reject the idea as well: https://gcc.gnu.org/pipermail/gcc-patches/2024-March/647920.html

Yes. So I closed this ticket.
