### ISSUE TITLE
[lld][ELF] Unresolved TPOFF64 in -static-pie when using lld

### ISSUE THREAD

**Issue by wc00862805aj** [llvm/llvm-project#85349]
Here is the `demo.go` file that I compiled:

```go
package main

// #cgo LDFLAGS: -ldl
// #include <stdlib.h>
// #include <dlfcn.h>
import "C"
import (
	"fmt"
)

func main() {
	fmt.Printf("This is a Go demo.\n")
	C.CString("libsystemd-login.so.0")
	return
}
```

When I compile it with the following command:
```shell
export CC=
go build -buildmode=pie -o demo-ld.exe -ldflags '-buildid=none -tmpdir=. -extldflags=-ftrapv -extldflags=-Wl,-z,relro,-z,now -linkmode=external -extldflags=-static-pie' demo.go;
```
`demo-ld` can be executed correctly. However, if I compile it with:
```shell
export CC=clang
go build -buildmode=pie -o demo-lld.exe -ldflags '-buildid=none -tmpdir=. -extldflags=-ftrapv -extldflags=-Wl,-z,relro,-z,now -linkmode=external -extldflags=-static-pie' demo.go;
```
`demo-lld` cannot be executed and ends with a "Segmentation fault (core dumped)" error.

Hence, I tried to use `readelf -r` on these files to identify the cause of the failure. I discovered that `demo-lld.exe` cannot resolve the TPOFF64 relocation type statically, while `demo-ld.exe` can. As a result, `demo-lld.exe` has several TPOFF64 entries in its dynamic relocation section. I also attempted to debug `demo-lld` with GDB and found that when the linker skips the resolution of TPOFF64, it can be executed correctly. However, if the resolution is performed, it fails at `dl_allocate_static_tls` due to uninitialized TLS, which does not occur with `demo-ld.exe`.

![image](https://github.com/llvm/llvm-project/assets/152485077/60a0dc79-1897-42e1-a68e-726382ae418c)

During my search on glibc, I came across an existing issue report (https://sourceware.org/bugzilla/show_bug.cgi?id=31302) that addresses this problem. According to their conclusion, `lld` should be able to resolve TPOFF64 relocations with -static-pie.

**Comment by MaskRay** [comment]
Added in #77208 

I'd suggest that Go switches from TPOFF64 to TPOFF32. TPOFF64 was added as a theoretical possibility, not a recommended mode. TPOFF32 overflow means that the static TLS block is at least 2GiB, which will consume 2GiB for each thread. This is very unlikely realistic at all.

**Comment by wc00862805aj** [comment]
Thanks for your reply; however, the submitted patch in #77208 cannot solve the problem here, as it focuses on resolving unknown relocation types rather than unresolved relocation types in static linking, which eventually is the cause of the segmentation error. Let's me provide more detail below:

![image](https://github.com/llvm/llvm-project/assets/152485077/c2ee7866-e223-4e0c-ba3f-46abc41a4426)
Here's the `readelf -rW` output of the demo given `CC=clang`. As I mentioned before, `CC=clang` and `-static-pie` cannot statically resolve TPOFF64. Hence, dynamic relocation section has several TPOFF64. Conversely, when compiled with `CC=` and `-static-pie`, these TPOFF64 relocations are not present.

![image](https://github.com/llvm/llvm-project/assets/152485077/65945439-5e68-47b3-84de-1620f7a51b1b)
Thus, during the debugging process as the picture above, `CC=clang` one will have such relocation (highlighted in yellow) while `CC=` won't.

![image](https://github.com/llvm/llvm-project/assets/152485077/a0964c23-b857-4ead-beb1-8fe30fce16d6)
Because `CC=` one can be executed properly without resolving TPOFF64 dynamically, I tried to bypass the resolution of TPOFF64 by setting `rbx` as the image above. And it passes and runs successfully.

Given these findings, I'm curious to know if there is any possible way to resolve TPOFF64 when using CC=clang with -static-pie in order to ensure that the executable runs properly.

**Comment by MaskRay** [comment]
I'm afraid that you have misunderstanding. `R_X86_64_TPOFF64` is a local-exec TLS model relocation, resolved at static link time for both ET_EXEC and PIE. lld reports `error: relocation R_X86_64_TPOFF64 against i cannot be used with -shared` if you use it for DSO.

https://github.com/llvm/llvm-project/pull/77208 is not lld 17, but likely in the just released 18.

Your CC= and `-static-pie` are not relevant to this question. You need to figure out the underlying linker, and if it is lld, check whether it contains the aforementioned patch.

**Comment by wc00862805aj** [comment]
Thanks for your @MaskRay reply! I have built lld in 18.1.2. but seems like the segmentation fault still here.

Here's the demo.go:
```go
package main

func main() {
        return
}
```

```cmd
$ make compile
CGO_ENABLED=1 CGO_CFLAGS="-fstack-protector-strong -fPIE" CGO_CPPFLAGS="-fstack-protector-strong -fPIE" CGO_LDFLAGS_ALLOW="-Wl,-z,relro,-z,now" CGO_LDFLAGS="-Wl,-z,relro,-z,now -Wl,-z,noexecstack" /usr/bin/go tool compile -S -o demo.o demo.go
```

**Comment by wc00862805aj** [comment]
Ping
