### ISSUE TITLE
mlir/lib/Transforms/InlinerPass.cpp:101: Suspicious condition ?

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#85400]
mlir/lib/Transforms/InlinerPass.cpp:101:21: style: Same expression on both sides of '||'. [duplicateExpression]

  Region *callerRegion = resolvedCall.sourceNode->getCallableRegion();
  Region *calleeRegion = resolvedCall.targetNode->getCallableRegion();

  // We should not get external nodes here, but just return true
  // for now to preserve the original behavior of the inliner pass.

  if (!calleeRegion || !calleeRegion)
    return true;

**Comment by dcb314** [comment]
Git blame says:

732f5368cdc (Slava Zakharin 2024-03-13 08:23:10 -0700 101)   if (!calleeRegion || !calleeRegion)
732f5368cdc (Slava Zakharin 2024-03-13 08:23:10 -0700 102)     return true;

**Comment by joker-eph** [comment]
Seems like a typo here, thanks for the report!

@vzakhari can you revisit this? (and add a test for it)

**Comment by vzakhari** [comment]
Thank you for the report @dcb314!
@joker-eph I am not sure if it is possible to create such a test, i.e. the inliner should not try to inline from/to external nodes.  Should I try to change it into an assertion?

**Comment by joker-eph** [comment]
Yes, let's assert then
