### ISSUE TITLE
[mlir] createOrFold does not sort commutative constant operands before trying to fold

### ISSUE THREAD

**Issue by inbelic** [llvm/llvm-project#85440]
Reproduction commit is found here: https://github.com/llvm/llvm-project/commit/0f099162404e89abfbd605d4bfbbe5a3bee494cc. Output of test case displayed below.

Expected behaviour:
Commutative operations should switch the constant operand to the second operand before trying to fold.

Problem:
spirv.IMul and spirv.IAdd are commutative operations, as such it is assumed that a constant operand should be positioned as the second operand when folding. In the reproduction we lower from MemRef.load to SPIR-V and there is the possibility to fold away a spirv.IMul 1 x -> x and spirv.IAdd 0 x -> x by invoking createOrFold. However, in the reproduction we see that the constant operands are not placed in the second position, and so they do not match the pattern to fold. Further, if we manually switch the order of the operands at the createOrFold we have the desired behaviour that the folding occurs.

From brief inspection, it does appear that the commutative implementation of the fold is being invoked.

```
mlir-opt -split-input-file -convert-memref-to-spirv="bool-num-bits=8" -cse commutative-folding.mlir
%cst1_i32 = spirv.Constant 1 : i32    <------------------- IMul.getOperand1()
%0 = unrealized_conversion_cast %arg1 : index to i32    <------------------- IMul.getOperand2()

%cst0_i32_0 = spirv.Constant 0 : i32    <------------------- IAdd.getOperand1()
%2 = spirv.IMul %0, %cst1_i32 : i32    <------------------- IAdd.getOperand2()

module attributes {spirv.target_env = #spirv.target_env<#spirv.vce<v1.0, [Shader, Int64], [SPV_KHR_storage_buffer_storage_
class]>, #spirv.resource_limits<>>} {
  func.func @load_i16(%arg0: memref<10xi16, #spirv.storage_class<StorageBuffer>>, %arg1: index) -> i16 {
    %0 = builtin.unrealized_conversion_cast %arg0 : memref<10xi16, #spirv.storage_class<StorageBuffer>> to !spirv.ptr<!spi
rv.struct<(!spirv.array<5 x i32, stride=4> [0])>, StorageBuffer>
    %1 = builtin.unrealized_conversion_cast %arg1 : index to i32
    %cst0_i32 = spirv.Constant 0 : i32
    %cst1_i32 = spirv.Constant 1 : i32
    %2 = spirv.IMul %1, %cst1_i32 : i32 <-------------- operands are sorted AFTER fold is applied
    %3 = spirv.IAdd %2, %cst0_i32 : i32 <-------------- operands are sorted AFTER fold is applied
    %cst2_i32 = spirv.Constant 2 : i32
    %4 = spirv.SDiv %3, %cst2_i32 : i32
    %5 = spirv.AccessChain %0[%cst0_i32, %4] : !spirv.ptr<!spirv.struct<(!spirv.array<5 x i32, stride=4> [0])>, StorageBuf
fer>, i32, i32
    %6 = spirv.Load "StorageBuffer" %5 : i32
    %cst16_i32 = spirv.Constant 16 : i32
    %7 = spirv.UMod %3, %cst2_i32 : i32
    %8 = spirv.IMul %7, %cst16_i32 : i32
    %9 = spirv.ShiftRightArithmetic %6, %8 : i32, i32
    %cst65535_i32 = spirv.Constant 65535 : i32
    %10 = spirv.BitwiseAnd %9, %cst65535_i32 : i32
    %11 = spirv.ShiftLeftLogical %10, %cst16_i32 : i32, i32
    %12 = spirv.ShiftRightArithmetic %11, %cst16_i32 : i32, i32
    %13 = builtin.unrealized_conversion_cast %12 : i32 to i16
    return %13 : i16
  }
}

```

**Comment by kuhar** [comment]
Per @matthias-springer on discourse:
> The IsCommutative trait has a folder that puts the constant operands at the end. I would have expected that that function is called during createAndFold.
