### ISSUE TITLE
[libc][math][c23] Implement C23 floating point min and max functions

### ISSUE THREAD

**Issue by lntue** [llvm/llvm-project#85496]
- The missing functions are: `fmaximum`, `fminimum`, `fmaximum_mag`, `fminimum_mag`, `fmaximum_num`, `fminimum_num`, `fmaximum_mag_num`, `fminimum_mag_num`.
- These functions are defined in C23 standard: sections 7.12.12.4 - 7.12.12.11 in https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3096.pdf
- Need to support the following data types: float, double, long double, float128.

**Comment by Jobhdez** [comment]
can this issue be assigned to me please? thanks

**Comment by Jobhdez** [comment]
@lntue thanks. I started working on it today.

**Comment by deeptirajora** [comment]
please assign this issue  to me ?

**Comment by Jobhdez** [comment]
> please assign this issue to me ?

Hey this has been assigned to me already. I’m working on it right now.

**Comment by Jobhdez** [comment]
@lntue hello, hope all is well. I just want to let you know that I’m about to make the tests for my changes. I have written the library functions. I just need to test my code and then I’ll submit my pr. Thanks
