### ISSUE TITLE
`[[assume(++a)]]` warns that the side-effects will be discarded, but they are not discarded at compile time

### ISSUE THREAD

**Issue by tbaederr** [llvm/llvm-project#85519]
```c++
constexpr int a() {
  int a = 0;
  [[assume(++a)]];
  return a;
}
static_assert(a() == 1);

#include <iostream>

int main() {
  std::cout << a() << "\n";
}
```

This code prints `0`, even though the `static_assert` doesn't fail. Clang does print a warning about the side-effects of `++a` being discarded, but that is not true at compile time.

CC @Sirraide

**Comment by Sirraide** [comment]
Oh, duh, I forgot to check for side-effects in constant evaluation; that’s an easy fix, fortunately.
