### ISSUE TITLE
Can I use standard library module using released libc++?

### ISSUE THREAD

**Issue by stripe2933** [llvm/llvm-project#85511]
I have C++ project that using standard library module, referenced in [here](https://libcxx.llvm.org/Modules.html). I also use CI build for cross-platform compatibility. However, the CI took time too much for cloning the whole LLVM repository and building, for just only generate `std.cppm` and `std.compat.cppm`. Is there way to not cloning the whole repository, like just download the `libcxx-18.1.1.src.tar.xz` in [releases](https://github.com/llvm/llvm-project/releases/tag/llvmorg-18.1.1), and build those two files?

**Comment by mordante** [comment]
In LLVM 18 it's possible to build and install the modules. https://releases.llvm.org/18.1.0/projects/libcxx/docs/ReleaseNotes.html
```
The .cppm files of experimental standard library modules can now be installed. By default, they are not installed. This can be enabled by configuring CMake with -DLIBCXX_INSTALL_MODULES=ON. The installation directory can be configured with the CMake option -DLIBCXX_INSTALL_MODULE_DIR=<path>. The default location is ${PREFIX}/share/libc++/v1.
```
This change allows build systems to add better module support. This is still work in progress.

As for your problem maybe you can build it once and create a tarball with the needed files. Then you use that in your CI. Still not ideal, but that means unpacking a small set of files instead of all of LLVM.

**Comment by stripe2933** [comment]
> As for your problem maybe you can build it once and create a tarball with the needed files. 

Does "it" means libc++? How can I build only libc++ without cloning the whole repository?

(+) Also, I use homebrew for LLVM installation. I'm wondering if I can configure `-DLIBCXX_INSTALL_MODULES=1` with homebrew LLVM (it seems they not distribute LLVM 18 yet).

**Comment by mordante** [comment]
> > As for your problem maybe you can build it once and create a tarball with the needed files.
> 
> Does "it" means libc++? How can I build only libc++ without cloning the whole repository?

You can download the release tarball. The you can build libc++ and make an artifact of the build directory. Then the next builds only need to download and unpack this artifact.

The goal is the have things work "out-of-the-box" in a future release of LLVM, but that's work in progress.

**Comment by ldionne** [comment]
Just to clarify, we don't support building libc++ without the whole monorepo. It's technically possible to do it, but it requires having the right subdirectories available.

**Comment by stripe2933** [comment]
Thank you for clarification. I hope the standard library module introduced with built-in support, as soon as possible.
