### ISSUE TITLE
[clang][frontend] fwd declararation _and_ definition of a member struct within the outer enclosing struct does not compile

### ISSUE THREAD

**Issue by psiha** [llvm/llvm-project#85532]
https://godbolt.org/z/TohYzv39n

```
struct foo
{
    struct bar
    {
        struct baz;
    };

    struct bar::baz {};
};
```
`error: non-friend class member 'baz' cannot have a qualified name`

compiles fine with GCC and MSVC.

**Comment by shafik** [comment]
clang is correct this is a gcc/MSVC bug: https://github.com/llvm/llvm-project/issues/55923
