### ISSUE TITLE
Feature request: expose getOpcode through Python bindings

### ISSUE THREAD

**Issue by sergiunagy** [llvm/llvm-project#85549]
Hello,
 
   I'm using clang and the Python bindings to perform some automated code analysis .
   I ran into the issue where I cannot differentiate between the different Binary Operations using just the available bindings.
   I am working on creating a custom binding for this but an exposed binding in the clang package would be cleaner (and probably more efficient).

**Comment by Endilll** [comment]
CC @DeinAlptraum can you take a look at this, too?

**Comment by DeinAlptraum** [comment]
Isn't this resolved through #98489?

**Comment by Endilll** [comment]
Indeed, thank you!
This should be available in Clang 19. Feel free to reopen if that's not the case.
