### ISSUE TITLE
std::enable_if mangling different in clang >= 18 compared to clang <= 17 or gcc

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [llvm/llvm-project#85656]
Hi,

While migrating to clang 18, we hit a name mangling difference compared to clang 17 (or gcc).

The following snippet:

```
#include <type_traits>

template <typename T> class SomeCondition
{
    public:
        static constexpr bool value = true;
};

template <typename T, typename std::enable_if<SomeCondition<T>::value, int>::type = 0> void SomeFunction(const T&);

void f()
{
    SomeFunction(0);
}
```

eventually leads to clang 18 mangle the call to SomeFunction as `_Z12SomeFunctionIiTnNSt9enable_ifIXsr13SomeConditionIT_EE5valueEiE4typeELi0EEvRKS1_` (see Compiler explorer: https://godbolt.org/z/Khv93qxvf) while clang 17 does mangle it as `_Z12SomeFunctionIiLi0EEvRKT_` (Compiler explorer: https://godbolt.org/z/WKeanb15P), and gcc as well (Compiler explorer: https://godbolt.org/z/1eqGKdnzY).

Is this change with clang 18 expected ?

**Comment by DimitryAndric** [comment]
@philnik777 did a bunch of refactoring touching `enable_if`:

76a247271507f009a186e81c7f90076ffb043ec3 [libc++] Refactor more __enable_ifs to the canonical style (#81457)
640274ff1fe17852615564a80d9f8c69b67f1d59 [libc++][NFC] Refactor __enable_ifs in <cstddef> to be defaulted template arguments
48c805bafdfd6b2ece12d809c67b887b39bd739f [libcxx] replaces SFINAE with requires-expressions in `bind_front` and `bind_back` (#68249)
9f3e3efd98a29eb8df9e3ad43a573c9141d1ace2 [libc++][NFC] Refactor __enable_if return types to defaulted template parameters
6256ccfd4f062f0b72b73adffe1dbf2c5b9903bb [libc++][NFC] Update the remaining enable_ifs
4da76ea70ad3d225d495703efca9b2f56bdefbf6 [libc++][NFC] Refactor enable_ifs in defaulted arguments to defaulted template arguments
475bd19ee8e42e68635b9770d5725461b7300914 [libc++][NFC] Refactor return type enable_ifs to defaulted template arguments
f3589d25fe09a9ec5d05d9ac389109a94f3f6187 [libc++][NFC] Refactor the enable_ifs in the math headers

Not sure if these were supposed to change any mangling, though.

**Comment by Romain-Geissler-1A** [comment]
Mmmm I should have written it in my first message, the STL used is libstdc++, not libc++.

**Comment by Romain-Geissler-1A** [comment]
Ok thanks. So I opened this bug on gcc side to adopt the same mangling change if indeed the historical one was invalid: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=114383

**Comment by pinskia** [comment]
It would be useful to point to the change that was done so the GCC folks can make sure it is done correctly there.
Note this seems like a huge ABI for many uses of enable_if so I am shocked it was decided it would be the default ...

**Comment by philnik777** [comment]
https://github.com/llvm/llvm-project/commit/4b163e343cfa54c8d55c9da73c70d58f55ea9df2 is the patch that changed it. I've read the commit message again, and it may not actually be intended given that the patch claims that only new constructs are affected, which I don't think is the case here. CC @zygoloid @AaronBallman @erichkeane

**Comment by zygoloid** [comment]
It's intentional that the mangling here changed, and necessary for conformance. Note that this is valid:

```c++
template <typename T, typename std::enable_if<SomeCondition<T>::value, int>::type = 0> void SomeFunction(const T&) {}
template <typename T, typename std::enable_if<OtherSomeCondition<T>::value, int>::type = 0> void SomeFunction(const T&) {}
```

... and declares two different function templates. Without this change, they would mangle the same. It's also valid for one of those templates to be declared in one translation unit and the other to be declared in a different translation unit, resulting in both templates actually being used with the same T in the same program.

> It would be useful to point to the change that was done so the GCC folks can make sure it is done correctly there.

See:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100825
https://github.com/itanium-cxx-abi/cxx-abi/issues/24
https://github.com/itanium-cxx-abi/cxx-abi/issues/31
https://github.com/itanium-cxx-abi/cxx-abi/issues/47
