### ISSUE TITLE
[CodeGen] x86_64 unable to select `X86ISD::VSHLV`/`X86ISD::VSRLV` on v32i1

### ISSUE THREAD

**Issue by DataCorrupted** [llvm/llvm-project#85681]
# Reproduction

https://godbolt.org/z/d4YWMP6cT

Same problem with emeraldrapids, sapphirerapids, or znver4.

@phoebewang Is this a bug or misuse? If it is a bug, I can help fix it.

**Comment by phoebewang** [comment]
@DataCorrupted `shl` on `i1` type is allowed, but the result is UB if the second operator is not full of zeros. Nevertheless, a crash is always a bug. I think we may simply optimize a
```
%c = shl <32 x i1> %a, %b
```
to
```
%c = %a
```
Similarly to lshr/ashr https://godbolt.org/z/KcTo3h8cq

**Comment by RKSimon** [comment]
Alive2: https://alive2.llvm.org/ce/z/SdESbg

**Comment by RKSimon** [comment]
Reduced: 
```ll
define i32 @PR85681(i32 %a0) {
  %v0 = bitcast i32 %a0 to <32 x i1>
  %s = shl <32 x i1> <i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true>, %v0
  %r = bitcast <32 x i1> %s to i32
  ret i32 %r
}

```
