### ISSUE TITLE
[MLIR Affine Bug] Error in simplification of an expression with a mod

### ISSUE THREAD

**Issue by AlexandreEichenberger** [llvm/llvm-project#85726]
Right now, the following affine expression `(s0 mod 32) * 64` is erroneously simplified to `s0 * 64 + (s0 floordiv 32) * 2048`.

Reproducer
```
#map = affine_map<()[s0] -> ((s0 mod 32)*64)> 
func.func @affine_test(%arg0: index) -> index {
  %0 = affine.apply #map()[%arg0]
  return %0: index
}
```

When simplified with the `mlir-opt -canonicalize` pass, we get

```
#map = affine_map<()[s0] -> (s0 * 64 - (s0 floordiv 32) * 2048)>
module {
  func.func @affine_test(%arg0: index) -> index {
    %0 = affine.apply #map()[%arg0]
    return %0 : index
  }
}
```

Expected results is the original expression, aka `affine_map<()[s0] -> ((s0 mod 32)*64)> `

**Comment by lipracer** [comment]
`s0 * 64 - (s0 floordiv 32) * 2048` => `64 * (s0 - 32 * (s0 // 32))` => `64 * (s0 mod 32)`
This seems equivalent in mathematics. Did you encounter a numerical value with overflow?

**Comment by AlexandreEichenberger** [comment]
You are correct; I looked at values using excel, must have used the wrong math formula. 
Using a c program shows that the opt is correct. Thanks for the quick answer.
