### ISSUE TITLE
O3 optimization level(clang 18) causes instruction disorder

### ISSUE THREAD

**Issue by xukang919** [llvm/llvm-project#85728]
**When I use `risc-v rv32gc clang 18.1.0` compiler to compile the example.c, the instruction in output.s is disordered.** 

All compilation options are `-g -o output.s -S -target riscv32-unknown-elf -march=rv32gc -mabi=ilp32d --gcc-toolchain=/opt/compiler-explorer/riscv32/gcc-10.2.0/riscv32-unknown-elf -fcolor-diagnostics -fno-crash-diagnostics -O3 example.c`

 example.c:
```c
#define SET_FLOAT_ROUNDING_MODE(reg)      ({      \
        asm ("fsrm %0" : : "r"(reg));              \
})

float add_f32_f32_test(float X,  float Y) { 
    volatile unsigned int reg = 0x4;
    SET_FLOAT_ROUNDING_MODE(reg);
    return X + Y;
}
```
And the output.s is as follow:
```c
add_f32_f32_test:                       # @add_f32_f32_test
        addi    sp, sp, -16
        li      a0, 4
        sw      a0, 12(sp)
        lw      a0, 12(sp)
        fadd.s  fa0, fa0, fa1
        fsrm    a0
        addi    sp, sp, 16
        ret
```
**Obviously, the `fsrm`  instruction should not follow `fadd.s ` instruction.**

But, when I use the O0 optimization level,the `fsrm`  instruction's order is true.

All compilation options are `-g -o output.s -S -target riscv32-unknown-elf -march=rv32gc -mabi=ilp32d --gcc-toolchain=/opt/compiler-explorer/riscv32/gcc-10.2.0/riscv32-unknown-elf -fcolor-diagnostics -fno-crash-diagnostics -O0 example.c `

And the output.s is as follow:
```c
add_f32_f32_test:                       # @add_f32_f32_test
        addi    sp, sp, -32
        sw      ra, 28(sp)                      # 4-byte Folded Spill
        sw      s0, 24(sp)                      # 4-byte Folded Spill
        addi    s0, sp, 32
        fsw     fa0, -12(s0)
        fsw     fa1, -16(s0)
        li      a0, 4
        sw      a0, -20(s0)
        lw      a0, -20(s0)
        fsrm    a0
        flw     fa5, -12(s0)
        flw     fa4, -16(s0)
        fadd.s  fa0, fa5, fa4
        lw      ra, 28(sp)                      # 4-byte Folded Reload
        lw      s0, 24(sp)                      # 4-byte Folded Reload
        addi    sp, sp, 32
        ret
```

So, is there a bug in clang-18？ or are there grammar issues in example.c ?

**Comment by topperc** [comment]
The compiler doesn't read the inline assembly text so it doesn't know you changed the rounding mode.

You can use `#pragma STDC FENV_ACCESS ON` and fesetround to change the rounding mode.

Or you could make the inline assembly `volatile` and try `#pragma STDC FENV_ACCESS ON` or pass `-frounding-math` on the command line. That might also prevent the reordering.

**Comment by xukang919** [comment]
Hi，Thank you for your reply！
the `fsrm `instruction's order is true when I add `#pragma STDC FENV_ACCESS ON`.

But, when I use` risc-v(32 bits) gcc 13.2.0` to compile the example.c,  the `fsrm `instruction's order is true without adding `#pragma STDC FENV_ACCESS ON` . 

All compilation options of ` risc-v(32 bits) gcc 13.2.0`  are `-g -o output.s -S -fdiagnostics-color=always -O3 example.c`

So, Why is there no problem when using `gcc`, but problems arise when using `llvm`

**Comment by topperc** [comment]
> Hi，Thank you for your reply！ the `fsrm `instruction's order is right when I add `#pragma STDC FENV_ACCESS ON`.
> 
> But, when I use` risc-v(32 bits) gcc 13.2.0` to compile the example.c, the `fsrm `instruction's order is right without adding `#pragma STDC FENV_ACCESS ON` .
> 
> All compilation options of ` risc-v(32 bits) gcc 13.2.0` are `-g -o output.s -S -fdiagnostics-color=always -O3 example.c`
> 
> So, Why is there no problem when using `gcc`, but problems arise when using `llvm`

I don't know if gcc behavior is guaranteed or you just got lucky that it didn't rearrange the instructions.

LLVM has a long history of assuming the rounding mode is never changed. The normal floating point instructions in LLVM IR are assumed to use the default rounding mode. Using `#pragma STDC FENV_ACCESS ON` causes the frontend to use llvm.constrained* intrinsics instead. This has the effect of making most optimizations ignore them or treat them conservatively. This prevents the reordering.

**Comment by dzaima** [comment]
As a side-note, [here's](https://godbolt.org/z/MdMozdves) an example of gcc reordering - the `X += 4;` got moved to after the `asm`.

**Comment by xukang919** [comment]
Thanks
