### ISSUE TITLE
[clang-format] `PointerAlignment` does not respect pointer to member field

### ISSUE THREAD

**Issue by CDAlexanderW** [llvm/llvm-project#85761]
### Environment
The tested v19 clang-format executable was built from latest source of 13.03.2024. Also tested with clang-format 17.0.3.

Setting in .clang-format is:
```
Language: Cpp
PointerAlignment: Left
SpaceAroundPointerQualifiers: Before
```
### Problem
```
class A {
public:
  int B;
};
void function(int A::* parameter, int* parameter2) {
  int A::* variable = &A::B;
  int* A::B;
}
```
formats to 
```
class A {
public:
  int B;
};
void function(int A::*parameter, int* parameter2) {
  int A::*variable = &A::B;
  int* A::B;
}
```
For the pointers to member field we expect the space between the `::*` and the `variable/parameter` name to be there and NOT removed.

**Comment by owenca** [comment]
Is `A::` a qualifier like `const`?

**Comment by CDAlexanderW** [comment]
> Is `A::` a qualifier like `const`?

Hi owenca!
Thx for your reply.

No, not a qualifier. See (2) [Pointer to member declarator](https://en.cppreference.com/w/cpp/language/pointer) on cppreference for the explanation of the language feature.

**Comment by owenca** [comment]
I knew `A::*` is for pointers to class members. I asked the question because I was thrown off by the `SpaceAroundPointerQualifiers` option and thought that maybe you expected `A::` to be treated like a qualifier.
