### ISSUE TITLE
llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:3804: lacking () for clarity

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#85868]
Static analyser cppcheck says:

llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:3804:47: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]

Source code is

    for (unsigned i = TSFlags & X86II::EVEX_K ? 2 : 1;

I am guessing that 

    for (unsigned i = (TSFlags & X86II::EVEX_K) ? 2 : 1;

was intended. Suggest add () for clarity of intention. 
Not all of us know all the C precedence rules well.

**Comment by EugeneZelenko** [comment]
It may be useful to wait for #84481 and extend it bitwise operators, so such code patterns could be improved on entire code base.

**Comment by RKSimon** [comment]
@EugeneZelenko Do we have any working clang-tidy report of the codebase?

https://llvm.org/reports/scan-build/ has barely worked for years now........

**Comment by EugeneZelenko** [comment]
@RKSimon: #84481 is not merged into `main` yet and in its current state it deals only with arithmetic operators.

**Comment by dcb314** [comment]
>@RKSimon: https://github.com/llvm/llvm-project/pull/84481 is not merged into main yet 
>and in its current state it deals only with arithmetic operators.

IMHO, doing this for arithmetic operators isn't as useful as doing it for the other operators.

Most people remember basic school material, but an average C programmer has only
an average understanding of the C operator table. 

I find the bit twiddling and ? : operators particularly troublesome. K&R does mention
some problems in the area of precedence.

I counted 62 examples across the llvm code base where cppcheck didn't like the look 
of uses of the ? : operator, so those are the first ones I'd be looking at. The original posting is an example.

**Comment by luolent** [comment]
Hi,

with a quick look at the [precedence table for C++](https://en.cppreference.com/w/cpp/language/operator_precedence), the proposal looks accurate.
I have added the parenthesis and run the tests, as expected no issue appeared.
Should I proceed on creating this small pull request?

On a second phase I can create a pull request with the warnings from CppCheck on ternary operators.

**Comment by dcb314** [comment]
> On a second phase I can create a pull request with the warnings from CppCheck on ternary operators.

Here is the current list from cppcheck:

trunk/clang/lib/Basic/Targets/AMDGPU.cpp:235:62: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/compiler-rt/lib/xray/xray_utils.h:64:63: style: Clarify calculation precedence for '%' and '?'. [clarifyCalculation]
trunk/libclc/generic/lib/math/log_base.h:292:32: style: Clarify calculation precedence for '|' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/aarch64/fenv_darwin_impl.h:71:37: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/aarch64/fenv_darwin_impl.h:75:43: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/aarch64/fenv_darwin_impl.h:76:45: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/aarch64/fenv_darwin_impl.h:77:44: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/aarch64/fenv_darwin_impl.h:78:45: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/aarch64/fenv_darwin_impl.h:79:43: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/aarch64/fenv_darwin_impl.h:80:44: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/aarch64/fenv_darwin_impl.h:84:34: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/aarch64/fenv_darwin_impl.h:85:36: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/aarch64/fenv_darwin_impl.h:86:35: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/aarch64/fenv_darwin_impl.h:87:36: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/aarch64/fenv_darwin_impl.h:88:34: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/aarch64/fenv_darwin_impl.h:89:38: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/aarch64/fenv_darwin_impl.h:93:34: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/aarch64/fenv_darwin_impl.h:94:36: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/aarch64/fenv_darwin_impl.h:95:35: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/aarch64/fenv_darwin_impl.h:96:36: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/aarch64/fenv_darwin_impl.h:97:34: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/aarch64/fenv_darwin_impl.h:98:38: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/aarch64/FEnvImpl.h:64:30: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/aarch64/FEnvImpl.h:65:32: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/aarch64/FEnvImpl.h:66:31: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/aarch64/FEnvImpl.h:67:32: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/aarch64/FEnvImpl.h:68:30: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/arm/FEnvImpl.h:53:37: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/arm/FEnvImpl.h:54:39: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/arm/FEnvImpl.h:55:38: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/arm/FEnvImpl.h:56:39: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/arm/FEnvImpl.h:57:37: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/arm/FEnvImpl.h:77:37: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/arm/FEnvImpl.h:78:39: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/arm/FEnvImpl.h:79:38: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/arm/FEnvImpl.h:80:39: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/arm/FEnvImpl.h:81:37: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/riscv/FEnvImpl.h:68:30: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/riscv/FEnvImpl.h:69:32: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/riscv/FEnvImpl.h:70:31: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/riscv/FEnvImpl.h:71:32: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/riscv/FEnvImpl.h:72:30: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/x86_64/FEnvImpl.h:86:46: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/x86_64/FEnvImpl.h:90:50: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/x86_64/FEnvImpl.h:91:47: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/x86_64/FEnvImpl.h:92:48: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libc/src/__support/FPUtil/x86_64/FEnvImpl.h:93:46: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/libcxxabi/src/cxa_personality.cpp:721:38: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/lldb/tools/debugserver/source/MacOSX/MachException.cpp:250:34: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/lld/ELF/LinkerScript.cpp:805:15: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/llvm/lib/Target/AMDGPU/AsmParser/AMDGPUAsmParser.cpp:3924:54: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/llvm/lib/Target/AMDGPU/Disassembler/AMDGPUDisassembler.cpp:932:49: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/llvm/lib/Target/AVR/AVRAsmPrinter.cpp:138:52: style: Clarify calculation precedence for '%' and '?'. [clarifyCalculation]
trunk/llvm/lib/Target/SystemZ/SystemZInstrInfo.cpp:1898:44: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/llvm/lib/Target/SystemZ/SystemZInstrInfo.cpp:1899:44: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/llvm/lib/Target/X86/MCTargetDesc/X86MCCodeEmitter.cpp:983:59: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
trunk/mlir/lib/Dialect/Tosa/Transforms/TosaDecomposeTransposeConv.cpp:185:34: style: Clarify calculation precedence for '%' and '?'. [clarifyCalculation]
trunk/mlir/lib/Dialect/Tosa/Transforms/TosaDecomposeTransposeConv.cpp:187:33: style: Clarify calculation precedence for '%' and '?'. [clarifyCalculation]

Some, all or none of these might be worth improving for clarity.

**Comment by luolent** [comment]
Hi @dcb314 , 
thanks for the list!

@EugeneZelenko can you assign me this issue?

**Comment by RKSimon** [comment]
Is the plan on this ticket to fix all the reports from cppcheck or update clang-tidy to report them in a similar way?

**Comment by dcb314** [comment]
Suggest

a) fix this one style issue
b) fix the 50+ style issues
c) fix clang-tidy to make sure the style issues can be seen if they occur again sometime
in the future.

For b) I would be particularly careful to only make changes that do not change
the meaning of the code. A C precedence table near to hand would be useful.

I can't be sure that, if the meaning of the code were accidentally changed by
( and ) in the wrong place, the test suite would catch it.

**Comment by luolent** [comment]
Hi @dcb314 ,

regarding c), clang-tidy does not catch the referenced cases in this issue. 
Should I proceed on creating a pass like [#84481](https://github.com/llvm/llvm-project/pull/84481)?

**Comment by dcb314** [comment]
>Should I proceed on creating a pass like [#84481](https://github.com/llvm/llvm-project/pull/84481)?

I know nothing about clang-tidy, so I should not comment on it.

However, I would do a) and b) first, which are existing problems.
c) will catch any future problems which may occur.

**Comment by RKSimon** [comment]
@dcb314 @luolent I've raised #91077 as a potential new/improved clang-tidy check

**Comment by MaskRay** [comment]
The ternary conditional pattern `[-+*%] \w+ \?` is a common idiom used in many codebases, e.g. `I == E - 1 ? Size : Layout->getElementOffset(I + 1)`. 

Adding parentheses around these expressions seems to provide little benefit in terms of readability or maintainability.  Consider suppressing these static analyzer reports for this specific pattern.

**Comment by dcb314** [comment]
>Adding parentheses around these expressions seems to provide little benefit in terms of 
>readability or maintainability

Disagree. Does the specified code mean

(I == E - 1) ? Size : Layout->getElementOffset(I + 1)

or

I == ((E - 1) ? Size : Layout->getElementOffset(I + 1))

?

Whatever the right answer is, are you sure a sufficient proportion of coders
know enough of the precedence table to get it right consistently ?

Making code obvious, without too many (), matters.

**Comment by MaskRay** [comment]
> > Adding parentheses around these expressions seems to provide little benefit in terms of
> > readability or maintainability
> 
> Disagree. Does the specified code mean
> 
> (I == E - 1) ? Size : Layout->getElementOffset(I + 1)
> 
> or
> 
> I == ((E - 1) ? Size : Layout->getElementOffset(I + 1))
> 
> ?
> 
> Whatever the right answer is, are you sure a sufficient proportion of coders know enough of the precedence table to get it right consistently ?
> 
> Making code obvious, without too many (), matters.

Many coders are familiar with the relative precedence of (`+-*/%`) and the ternary conditional (`?:`).
While I believe some coders might disagree, it's up to the prevailing style in this code base and the value/churn tradeoff.

I believe the majority of this code base doesn't add parens for such code patterns and there are potentially many users disagreeing with this change.
