### ISSUE TITLE
[clang] Crash on clang 18

### ISSUE THREAD

**Issue by rockwotj** [llvm/llvm-project#85873]
When attempting to upgrade my project to Clang 18, I get the following errors (adding as comments because that's easier to do from the command line). I unfortunately don't have the stack trace anymore.

**Comment by rockwotj** [comment]
# Crash reproducer for Ubuntu clang version 18.1.2 (++20240319123532+7fd9979eb9cf-1~exp1~20240319003652.95)
# Driver args: "--driver-mode=g++" "-D" "BOOST_ALL_DYN_LINK" "-D" "BOOST_NO_CXX98_FUNCTION_BASE" "-D" "FMT_LOCALE" "-D" "FMT_SHARED" "-D" "IS_GTEST" "-D" "SEASTAR_API_LEVEL=6" "-D" "SEASTAR_BUILD_SHARED_LIBS" "-D" "SEASTAR_DEBUG" "-D" "SEASTAR_DEBUG_SHARED_PTR" "-D" "SEASTAR_DEFAULT_ALLOCATOR" "-D" "SEASTAR_SCHEDULING_GROUPS_COUNT=16" "-D" "SEASTAR_SHUFFLE_TASK_QUEUE" "-D" "SEASTAR_TYPE_ERASE_MORE" "-I" "/home/rockwood/code/redpanda2/src/v" "-I" "/home/rockwood/code/redpanda2/build/debug/src/v" "-I" "/home/rockwood/code/redpanda2/src/v/base/include" "-I" "/home/rockwood/code/redpanda2/src/v/test_utils/include" "-I" "/home/rockwood/code/redpanda2/src/v/bytes/include" "-I" "/home/rockwood/code/redpanda2/src/v/random/include" "-I" "/home/rockwood/code/redpanda2/src/v/crypto/include" "-I" "/home/rockwood/code/redpanda2/src/v/container/include" "-I" "/home/rockwood/code/redpanda2/src/v/strings/include" "-I" "/home/rockwood/code/redpanda2/src/v/io/include" "-isystem" "/home/rockwood/code/redpanda2/build/debug/_deps/seastar-src/include" "-isystem" "/home/rockwood/code/redpanda2/build/debug/_deps/seastar-build/gen/include" "-isystem" "/home/rockwood/code/redpanda2/build/debug/_deps/fmt-src/include" "-isystem" "/home/rockwood/code/redpanda2/build/debug/_deps/gtest-src/googletest/include" "-isystem" "/home/rockwood/code/redpanda2/build/debug/_deps/gtest-src/googletest" "-isystem" "/home/rockwood/code/redpanda2/build/debug/_deps/gtest-src/googlemock/include" "-isystem" "/home/rockwood/code/redpanda2/build/debug/_deps/gtest-src/googlemock" "-isystem" "/home/rockwood/code/redpanda2/build/debug/_deps/gtest-src/include" "-isystem" "/home/rockwood/code/redpanda2/build/debug/_deps/gtest-src" "-isystem" "/home/rockwood/code/redpanda2/build/debug/_deps/absl-src" "-g" "-std=c++20" "-fsanitize=address,leak,undefined" "-Wall" "-Wextra" "-Werror" "-Wno-missing-field-initializers" "-Wno-unused-parameter" "-Wno-sign-compare" "-U" "_FORTIFY_SOURCE" "-D" "SEASTAR_SSTRING" "-Wno-error=unused-result" "-Wno-error=#warnings" "-fstack-clash-protection" "-fsanitize=address" "-fsanitize=undefined" "-fno-sanitize=vptr" "-MD" "-MT" "src/v/io/tests/CMakeFiles/io_rpunit.dir/common_test.cc.o" "-MF" "src/v/io/tests/CMakeFiles/io_rpunit.dir/common_test.cc.o.d" "-o" "src/v/io/tests/CMakeFiles/io_rpunit.dir/common_test.cc.o" "-c" "/home/rockwood/code/redpanda2/src/v/io/tests/common_test.cc"
# Original command:  "/usr/lib/llvm-18/bin/clang" "-cc1" "-triple" "x86_64-pc-linux-gnu" "-emit-obj" "-mrelax-all" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "common_test.cc" "-mrelocation-model" "pic" "-pic-level" "2" "-pic-is-pie" "-mframe-pointer=all" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-funwind-tables=2" "-target-cpu" "x86-64" "-tune-cpu" "generic" "-debug-info-kind=constructor" "-dwarf-version=5" "-debugger-tuning=gdb" "-fdebug-compilation-dir=/home/rockwood/code/redpanda2/build/debug" "-fcoverage-compilation-dir=/home/rockwood/code/redpanda2/build/debug" "-resource-dir" "/usr/lib/llvm-18/lib/clang/18" "-dependency-file" "src/v/io/tests/CMakeFiles/io_rpunit.dir/common_test.cc.o.d" "-MT" "src/v/io/tests/CMakeFiles/io_rpunit.dir/common_test.cc.o" "-sys-header-deps" "-isystem" "/home/rockwood/code/redpanda2/build/debug/_deps/seastar-src/include" "-isystem" "/home/rockwood/code/redpanda2/build/debug/_deps/seastar-build/gen/include" "-isystem" "/home/rockwood/code/redpanda2/build/debug/_deps/fmt-src/include" "-isystem" "/home/rockwood/code/redpanda2/build/debug/_deps/gtest-src/googletest/include" "-isystem" "/home/rockwood/code/redpanda2/build/debug/_deps/gtest-src/googletest" "-isystem" "/home/rockwood/code/redpanda2/build/debug/_deps/gtest-src/googlemock/include" "-isystem" "/home/rockwood/code/redpanda2/build/debug/_deps/gtest-src/googlemock" "-isystem" "/home/rockwood/code/redpanda2/build/debug/_deps/gtest-src/include" "-isystem" "/home/rockwood/code/redpanda2/build/debug/_deps/gtest-src" "-isystem" "/home/rockwood/code/redpanda2/build/debug/_deps/absl-src" "-D" "BOOST_ALL_DYN_LINK" "-D" "BOOST_NO_CXX98_FUNCTION_BASE" "-D" "FMT_LOCALE" "-D" "FMT_SHARED" "-D" "IS_GTEST" "-D" "SEASTAR_API_LEVEL=6" "-D" "SEASTAR_BUILD_SHARED_LIBS" "-D" "SEASTAR_DEBUG" "-D" "SEASTAR_DEBUG_SHARED_PTR" "-D" "SEASTAR_DEFAULT_ALLOCATOR" "-D" "SEASTAR_SCHEDULING_GROUPS_COUNT=16" "-D" "SEASTAR_SHUFFLE_TASK_QUEUE" "-D" "SEASTAR_TYPE_ERASE_MORE" "-I" "/home/rockwood/code/redpanda2/src/v" "-I" "/home/rockwood/code/redpanda2/build/debug/src/v" "-I" "/home/rockwood/code/redpanda2/src/v/base/include" "-I" "/home/rockwood/code/redpanda2/src/v/test_utils/include" "-I" "/home/rockwood/code/redpanda2/src/v/bytes/include" "-I" "/home/rockwood/code/redpanda2/src/v/random/include" "-I" "/home/rockwood/code/redpanda2/src/v/crypto/include" "-I" "/home/rockwood/code/redpanda2/src/v/container/include" "-I" "/home/rockwood/code/redpanda2/src/v/strings/include" "-I" "/home/rockwood/code/redpanda2/src/v/io/include" "-U" "_FORTIFY_SOURCE" "-D" "SEASTAR_SSTRING" "-internal-isystem" "/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13" "-internal-isystem" "/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/x86_64-linux-gnu/c++/13" "-internal-isystem" "/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/backward" "-internal-isystem" "/usr/lib/llvm-18/lib/clang/18/include" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../x86_64-linux-gnu/include" "-internal-externc-isystem" "/usr/include/x86_64-linux-gnu" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "-Wall" "-Wextra" "-Werror" "-Wno-missing-field-initializers" "-Wno-unused-parameter" "-Wno-sign-compare" "-Wno-error=unused-result" "-Wno-error=#warnings" "-std=c++20" "-fdeprecated-macro" "-ferror-limit" "19" "-fsanitize=address,leak,alignment,array-bounds,bool,builtin,enum,float-cast-overflow,function,integer-divide-by-zero,nonnull-attribute,null,pointer-overflow,return,returns-nonnull-attribute,shift-base,shift-exponent,signed-integer-overflow,unreachable,vla-bound" "-fsanitize-recover=alignment,array-bounds,bool,builtin,enum,float-cast-overflow,function,integer-divide-by-zero,nonnull-attribute,null,pointer-overflow,returns-nonnull-attribute,shift-base,shift-exponent,signed-integer-overflow,vla-bound" "-fsanitize-system-ignorelist=/usr/lib/llvm-18/lib/clang/18/share/asan_ignorelist.txt" "-fno-sanitize-memory-param-retval" "-fsanitize-address-use-after-scope" "-fsanitize-address-globals-dead-stripping" "-fno-assume-sane-operator-new" "-fstack-clash-protection" "-fgnuc-version=4.2.1" "-fno-implicit-modules" "-fskip-odr-check-in-gmf" "-fcxx-exceptions" "-fexceptions" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-o" "src/v/io/tests/CMakeFiles/io_rpunit.dir/common_test.cc.o" "-x" "c++" "/home/rockwood/code/redpanda2/src/v/io/tests/common_test.cc"
 "/usr/lib/llvm-18/bin/clang" "-cc1" "-triple" "x86_64-pc-linux-gnu" "-emit-obj" "-mrelax-all" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "common_test.cc" "-mrelocation-model" "pic" "-pic-level" "2" "-pic-is-pie" "-mframe-pointer=all" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-funwind-tables=2" "-target-cpu" "x86-64" "-tune-cpu" "generic" "-debug-info-kind=constructor" "-dwarf-version=5" "-debugger-tuning=gdb" "-fdebug-compilation-dir=/home/rockwood/code/redpanda2/build/debug" "-fcoverage-compilation-dir=/home/rockwood/code/redpanda2/build/debug" "-sys-header-deps" "-D" "BOOST_ALL_DYN_LINK" "-D" "BOOST_NO_CXX98_FUNCTION_BASE" "-D" "FMT_LOCALE" "-D" "FMT_SHARED" "-D" "IS_GTEST" "-D" "SEASTAR_API_LEVEL=6" "-D" "SEASTAR_BUILD_SHARED_LIBS" "-D" "SEASTAR_DEBUG" "-D" "SEASTAR_DEBUG_SHARED_PTR" "-D" "SEASTAR_DEFAULT_ALLOCATOR" "-D" "SEASTAR_SCHEDULING_GROUPS_COUNT=16" "-D" "SEASTAR_SHUFFLE_TASK_QUEUE" "-D" "SEASTAR_TYPE_ERASE_MORE" "-U" "_FORTIFY_SOURCE" "-D" "SEASTAR_SSTRING" "-Wall" "-Wextra" "-Werror" "-Wno-missing-field-initializers" "-Wno-unused-parameter" "-Wno-sign-compare" "-Wno-error=unused-result" "-Wno-error=#warnings" "-std=c++20" "-fdeprecated-macro" "-ferror-limit" "19" "-fsanitize=address,leak,alignment,array-bounds,bool,builtin,enum,float-cast-overflow,function,integer-divide-by-zero,nonnull-attribute,null,pointer-overflow,return,returns-nonnull-attribute,shift-base,shift-exponent,signed-integer-overflow,unreachable,vla-bound" "-fsanitize-recover=alignment,array-bounds,bool,builtin,enum,float-cast-overflow,function,integer-divide-by-zero,nonnull-attribute,null,pointer-overflow,returns-nonnull-attribute,shift-base,shift-exponent,signed-integer-overflow,vla-bound" "-fsanitize-system-ignorelist=/usr/lib/llvm-18/lib/clang/18/share/asan_ignorelist.txt" "-fno-sanitize-memory-param-retval" "-fsanitize-address-use-after-scope" "-fsanitize-address-globals-dead-stripping" "-fno-assume-sane-operator-new" "-fstack-clash-protection" "-fgnuc-version=4.2.1" "-fno-implicit-modules" "-fskip-odr-check-in-gmf" "-fcxx-exceptions" "-fexceptions" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-x" "c++" "common_test-98b25f.cpp"

**Comment by rockwotj** [comment]
Reproducer C++ file

[common_test-98b25f.cpp.txt](https://github.com/llvm/llvm-project/files/14657489/common_test-98b25f.cpp.txt)

**Comment by Endilll** [comment]
I built Clang at 7fd9979eb9cf in debug mode, but wasn't able to reproduce still.
@rockwotj Can you reproduce the issue and at least show us stack trace?

**Comment by rockwotj** [comment]
@Endilll I have spent the morning running my build in a loop but haven't reproduce it either, sorry for the noise but I'll close this and reopen if I see it again.
