### ISSUE TITLE
SAFECode does not check allocation sizes of type-known memory objects

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#8588]
|  |  |
| --- | --- |
| Bugzilla Link | [8216](https://llvm.org/bz8216) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
SAFECode assumes that when a memory object is used in a type-consistent fashion that all allocations made for that memory object are large enough to hold the type inferred by DSA.

To the best of my knowledge, this is not true.  DSA can detect type-consistency but does not track whether allocation sizes for a DSNode are large enough to contain objects of the inferred type.

Note that such checks are unnecessary for type-unknown objects; load/store checks should catch allocation sizes that are too small.

**Comment by Endilll** [comment]
SAFECode is archived.
