### ISSUE TITLE
[SelectionDAG] Add a new ISD Node for vector saturating truncation

### ISSUE THREAD

**Issue by sun-jacobi** [llvm/llvm-project#85903]
Based on the #73424. There were several patches and issues on the vector saturating truncation operation on different platform.

For instance, #68466 for x86 and #75145 for RISC-V vector extension. I think it is better for us to do a target-independent combine for this operation, which could be expressed as a sequence of LLVM IR like: 

```
define void @trunc_sat_i8i16(ptr %x, ptr %y) {
  %1 = load <8 x i16>, ptr %x, align 16
  %2 = tail call <8 x i16> @llvm.smax.v8i16(<8 x i16> %1, <8 x i16> <i16 -128, i16 -128, i16 -128, i16 -128, i16 -128, i16 -128, i16 -128, i16 -128>)
  %3 = tail call <8 x i16> @llvm.smin.v8i16(<8 x i16> %2, <8 x i16> <i16 127, i16 127, i16 127, i16 127, i16 127, i16 127, i16 127, i16 127>)
  %4 = trunc <8 x i16> %3 to <8 x i8>
  store <8 x i8> %4, ptr %y, align 8
  ret void
}
```

Especially, I think this combine could be done at the SelectionDAG, like the other saturating operation such as `ISD::SADDSAT`. This could remove complex TableGen pattern matching and refactor each platform's CodeGen path for this operation.

**Comment by dtcxzyw** [comment]
cc @topperc @RKSimon @preames @asb

**Comment by RKSimon** [comment]
I'm sure this has come up before as a phab review but I can't find it right now (@davemgreen can you remember?).

What would be awesome is if there was a way to handle the 2 SSE PACK instruction signed saturations: 
```
/// PACKSS (normal signed sat)
/// (truncate (smin ((smax (x, signed_min_of_dest_type)),
///                  signed_max_of_dest_type)) to dest_type)
/// or:
/// (truncate (smax ((smin (x, signed_max_of_dest_type)),
///                  signed_min_of_dest_type)) to dest_type).
///
/// PACKUS (signed sat of unsigned range) - NOT the same as USAT
/// the smax/smin range is [0, unsigned_max_of_dest_type].
```

**Comment by sun-jacobi** [comment]
@RKSimon Thank you for the information. Do you mean we also need to add a new ISD Node for signed sat of unsigned range?

**Comment by davemgreen** [comment]
For MVE this is spelled ARMISD::VQMOVNs/ARMISD::VQMOVNu, but as it uses the top/bottom instructions the new ISD might not be a good fit.

It would be better for AArch64/Neon (the SQXTN/UQXTN instructions) - there I think I added tablegen patterns to keep the nodes generic as long as possible, but so long as the new nodes handled known/demanded bits and whatnot then it should be a good replacement.

**Comment by ParkHanbum** [comment]
Can a beginner take over this issue? if may, I'm very glad to take.

**Comment by topperc** [comment]
The RISC-V code was further modified in #93596 #93728 #93756 #93752. There are no longer complex tablegen patterns, but there is a bunch of DAG combine code.

**Comment by ParkHanbum** [comment]
@topperc Thanks for letting us know. If there are any architectures that have not been patched yet, I will refer to the link you provided.

**Comment by topperc** [comment]
> @topperc Thanks for letting us know. If there are any architectures that have not been patched yet, I will refer to the link you provided.

I think the RISC-V specific DAGCombine code could be removed if we had a generic saturation node. We'd still need custom lowering to split something like a vXi32->vXi8 saturating truncate into multiple vnclip instructions since we can only truncate vXi32->vXi16 or vXi16->vXi8 in a single instruction.

**Comment by sun-jacobi** [comment]
> @topperc Thanks for letting me know. If there are any architectures that have not been patched yet, I will refer to the link you provided.

What I proposed is actually a generic saturation node (just as @topperc said). The proposed node is somewhat difficult to work with x86, but AArch64/Neon and RISCV-V would benefit. 

If you are interested in this, feel free to try it :)

**Comment by RKSimon** [comment]
Starting with adding ISD::TRUNCSSAT would make sense - cheers.

**Comment by ParkHanbum** [comment]
I'm on duty for this. as @RKSimon guided, implemented (is it correctly?) truncate_ssat first. 
 

```
Legalized selection DAG: %bb.0 'saturate2:'
SelectionDAG has 7 nodes:
  t0: ch,glue = EntryToken
      t2: v8i16,ch = CopyFromReg t0, Register:v8i16 %0
    t13: v8i8 = truncate_ssat t2
  t11: ch,glue = CopyToReg t0, Register:v8i8 $d0, t13
  t12: ch = AArch64ISD::RET_GLUE t11, Register:v8i8 $d0, t11:1
```

https://github.com/ParkHanbum/llvm-project/commit/f88709cb39098d8cc82aac7b83b8d7807259600a#diff-d7065626b3d269e24241429ce037d51fc91d5ead5896d67fcc038aefc1111fd2

I should start implementing architecture-specific DAGToDAGISel now, right? 😄

**Comment by inclyc** [comment]
Hi @ParkHanbum, 

> I should start implementing architecture-specific DAGToDAGISel now, right?

I think maybe modifications on `llvm/lib/Target/*.td` files would be sufficient. You can start looking there.

**Comment by ParkHanbum** [comment]
Hi @inclyc thanks for advice. I'll find what can I do!

**Comment by RKSimon** [comment]
@ParkHanbum You might want to use something like 2887f1463930044a6093f111dc8eba5594144c33 as reference about introducing a new ISD node, although in that case this was a conversion of an existing aarch64 opcode

**Comment by ParkHanbum** [comment]
@RKSimon thanks!! it is very helpful!!

**Comment by ParkHanbum** [comment]
can I ask a question? 
is we cannot support i64 type for this issue in aarch64 and x86?

because I found it does not supported in aarch64&x86 but supported in riscv.
https://godbolt.org/z/7W6baE83c


and as I tested result, that trunc at @vqmovni64_smaxmin  is saturized.
```

Optimized legalized selection DAG: %bb.0 'vqmovni64_smaxmin:entry'
SelectionDAG has 7 nodes:
  t0: ch,glue = EntryToken
      t2: v2i64,ch = CopyFromReg t0, Register:v2i64 %0
    t17: v2i32 = truncate_ssat t2
  t15: ch,glue = CopyToReg t0, Register:v2i32 $d0, t17
  t16: ch = AArch64ISD::RET_GLUE t15, Register:v2i32 $d0, t15:1


```

**Comment by RKSimon** [comment]
I expect you will have to add legalizer support as well - not just handle known legal instructions.

Search for ISD::TRUNCATE in the llvm\lib\CodeGen\SelectionDAG\Legalize* files - its likely you will just have duplicate some of this code with a suitable smin/smax clamping before truncation.

**Comment by ParkHanbum** [comment]
Thanks @RKSimon, the commits you shared earlier gave me what I have to do. 

The reason I asked is that I wanted to make sure that the cases that currently appear to be unsupported are still unsupportable.

**Comment by ParkHanbum** [comment]
I've implemented truncate_[us]at for aarch64, riscv. x86 has a complicated implementation and I think I need to do more work on it, can I send a PR with the implemented one first?

**Comment by RKSimon** [comment]
Please raise a PR, keep it as draft if you want (but people will comment whatever :))
