### ISSUE TITLE
-Wunused-value and statement expressions

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#8590]
|  |  |
| --- | --- |
| Bugzilla Link | [8218](https://llvm.org/bz8218) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @tkremenek |

## Extended Description 
The return value of a statement expression doesn't yield -Wunused-value warnings for gcc, but does for clang. This is very annoying because it makes huge codebases uncheckable with clang wrt unused values.

For example, this macro that "rethrows" POSIX errors:
```c
#define POSIX_RETHROW(expr) \
  ({ typeof(expr) __res = (expr); if (__res < 0) return __res; __res; })
```
Many POSIX functions return 0 when they work and their return value is uninteresting, in that case, it is used as a single statement:

  ...
  POSIX_RETHROW(dup2(fd, 0));
  ...

Sadly this yields an unused value warning with clang.

I'd suggest that one (or more ;p) of the following is implemented:
- provide an attribute to say that the given value may be unused and should not yield a warning, the final __res in the macro would be marked with that attribute.
- ignore the returned value of a statement expression for the warning (this is what happens for functions that return something and whose return value is ignored already, and this is probably why gcc ignores the return value of statement expressions as well, because it's consistent);
- have a -W[no-]unused-statement-expression-value that will generate the warning for statement expressions values so that -Wunused-value can work like it does with gcc.

TIA :)

**Comment by philnik777** [comment]
Fixed in Clang 3.2: https://godbolt.org/z/9K76nPqGz
