### ISSUE TITLE
[OpenMP] Dependency on "opt" during runtimes-configure may be missing

### ISSUE THREAD

**Issue by uweigand** [llvm/llvm-project#85933]
The openmp-s390x-linux builder is sporadically failing with:
```
# | clang: error: no such file or directory: '/home/uweigand/sandbox/buildbot/openmp-s390x-linux/llvm.build/./lib/libomptarget.devicertl.a'
```
when running the test.   It turns out that library isn't being built due the following configure decision:
```
-- LIBOMPTARGET: Not building DeviceRTL. Missing clang: /home/uweigand/sandbox/buildbot/openmp-s390x-linux/llvm.build/bin/clang, llvm-link: /home/uweigand/sandbox/buildbot/openmp-s390x-linux/llvm.build/bin/llvm-link, opt: OPT_TOOL-NOTFOUND, or clang-offload-packager: /home/uweigand/sandbox/buildbot/openmp-s390x-linux/llvm.build/bin/clang-offload-packager
```
(note the `OPT_TOOL-NOTFOUND`).

And even in successful builds, I sometimes see the line:
```
381.426 [3/2/4993] Linking CXX executable bin/opt
```
*after*
```
375.273 [42/4/4951] Performing configure step for 'runtimes'
```

So it looks like there needs to be a dependency on `opt` for the `runtimes-configure` target, but this may be missing.  Looking at the `llvm/runtimes/CMakeLists.txt` file, I see this block:
```
  if("openmp" IN_LIST LLVM_ENABLE_RUNTIMES)
    foreach(dep opt llvm-link llvm-extract clang clang-offload-packager)
      if(TARGET ${dep} AND OPENMP_ENABLE_LIBOMPTARGET)
        list(APPEND extra_deps ${dep})
      endif()
    endforeach()
  endif()
```
and this `extra_deps` variable is used when configuring the *default* runtimes target:
```
  if(NOT LLVM_RUNTIME_TARGETS)
    runtime_default_target(
      DEPENDS ${builtins_dep} ${extra_deps}
      CMAKE_ARGS ${libc_cmake_args}
      PREFIXES ${prefixes})
    set(test_targets check-runtimes)
```

But when only some runtimes components are enabled, `extra_deps` doesn't appear to be used:
```
    foreach(name ${LLVM_RUNTIME_TARGETS})
      if(builtins_dep)
        if (LLVM_BUILTIN_TARGETS)
          set(builtins_dep_name "${builtins_dep}-${name}")
        else()
          set(builtins_dep_name ${builtins_dep})
        endif()
      endif()

      check_apple_target(${name} runtime)

      runtime_register_target(${name}
        DEPENDS ${builtins_dep_name} ${hdrgen_deps}
        CMAKE_ARGS -DLLVM_DEFAULT_TARGET_TRIPLE=${name} ${libc_cmake_args}
        EXTRA_ARGS TARGET_TRIPLE ${name})
    endforeach()
```

(Note that `hdrgen_deps` is also present in `extra_deps`, but the latter may include many more dependencies.)

Should `extra_deps` be used here as well?

CC @jhuber6 @petrhosek

**Comment by jhuber6** [comment]
I really hate the handling here, unfortunately it's a little difficult to set up the library in the way we need it without fishing a few of these tools out of the build directory. I think in the future I should be able to rewrite a lot of this, but for now does it work if you force the `opt` dependency on everything?

**Comment by uweigand** [comment]
This patch seems to work for me:
```
diff --git a/llvm/runtimes/CMakeLists.txt b/llvm/runtimes/CMakeLists.txt
index 623c43d564cc..b0d428881fde 100644
--- a/llvm/runtimes/CMakeLists.txt
+++ b/llvm/runtimes/CMakeLists.txt
@@ -531,7 +531,7 @@ if(runtimes)
       check_apple_target(${name} runtime)
 
       runtime_register_target(${name}
-        DEPENDS ${builtins_dep_name} ${hdrgen_deps}
+        DEPENDS ${builtins_dep_name} ${extra_deps}
         CMAKE_ARGS -DLLVM_DEFAULT_TARGET_TRIPLE=${name} ${libc_cmake_args}
         EXTRA_ARGS TARGET_TRIPLE ${name})
     endforeach()
```

**Comment by uweigand** [comment]
Actually, I take it back; that seems to have been just happenstance.  Looks like I confused LLVM_RUNTIME_TARGETS with LLVM_ENABLE_RUNTIMES.   Need to look into this some more.

**Comment by uweigand** [comment]
Now I see.   While executing this block of code:
```
  if("openmp" IN_LIST LLVM_ENABLE_RUNTIMES)
    foreach(dep opt llvm-link llvm-extract clang clang-offload-packager)
      if(TARGET ${dep} AND OPENMP_ENABLE_LIBOMPTARGET)
        list(APPEND extra_deps ${dep})
      endif()
    endforeach()
  endif()
```
nothing ever happens because `OPENMP_ENABLE_LIBOMPTARGET` is not set.  Looks like this would be set in `openmp/CMakeLists.txt`, but that file isn't parsed at initial cmake time.   Maybe this broke when moving openmp from LLVM_ENABLE_PROJECTS to LLVM_ENABLE_RUNTIMES?

Do we even need that check here?   We might as well add those dependencies always ...  This patch does fix the problem for me:
```
diff --git a/llvm/runtimes/CMakeLists.txt b/llvm/runtimes/CMakeLists.txt
index 623c43d564cc..b4664b4baa23 100644
--- a/llvm/runtimes/CMakeLists.txt
+++ b/llvm/runtimes/CMakeLists.txt
@@ -435,7 +435,7 @@ if(runtimes)
       list(APPEND extra_deps "flang-new")
     endif()
     foreach(dep opt llvm-link llvm-extract clang clang-offload-packager)
-      if(TARGET ${dep} AND OPENMP_ENABLE_LIBOMPTARGET)
+      if(TARGET ${dep})
         list(APPEND extra_deps ${dep})
       endif()
     endforeach()
```

(The previous patch is probably also needed in case people use a non-default LLVM_RUNTIME_TARGETS ...)

**Comment by jhuber6** [comment]
That seems correct, that probably just wasn't thought through correctly when written and moving to runtimes. If you make a PR for that I'll approve it.
