### ISSUE TITLE
Aarch64 popcountg codegen worse than RISC-V

### ISSUE THREAD

**Issue by hiraditya** [llvm/llvm-project#85965]
popcountg instruction was added to clang: https://github.com/llvm/llvm-project/commit/21d83324fbdb

https://godbolt.org/z/7fzrar4fE

```c
int test_builtin_popcountg(unsigned i) {
  return __builtin_popcountg(i);
}
```

RISCV
```asm
test_builtin_popcountg(unsigned int):            # @test_builtin_popcountg(unsigned int)
        cpopw   a0, a0
        ret
```

AArch64
```asm
test_builtin_popcountg(unsigned int):            // @test_builtin_popcountg(unsigned int)
        fmov    s0, w0
        cnt     v0.8b, v0.8b
        uaddlv  h0, v0.8b
        fmov    w0, s0
        ret
```

**Comment by hiraditya** [comment]
cc: @kbeyls @DanielKristofKiss

**Comment by topperc** [comment]
Does AArch64 have a scalar pop count instruction?

**Comment by DanielKristofKiss** [comment]
There is one:
https://developer.arm.com/documentation/ddi0602/2023-12/Base-Instructions/CNT--Count-bits-?lang=en

**Comment by antoniofrighetto** [comment]
> There is one:
> https://developer.arm.com/documentation/ddi0602/2023-12/Base-Instructions/CNT--Count-bits-?lang=en

Which already seems to be used here.

**Comment by topperc** [comment]
> > There is one:
> > https://developer.arm.com/documentation/ddi0602/2023-12/Base-Instructions/CNT--Count-bits-?lang=en
> 
> Which already seems to be used here.

`v0.8b` would seem to be a vector operand right?

**Comment by topperc** [comment]
Using -march=armv8+cssc does generate a single instruction like RISC-V. https://godbolt.org/z/d4nK3Gehv

**Comment by topperc** [comment]
So this tciket can be closed?

**Comment by efriedma-quic** [comment]
Closing.  (On a side-note, it might make sense to file a ticket for RISCV code quality without zbb; it looks like it could be improved a bit.)

**Comment by topperc** [comment]
> Closing. (On a side-note, it might make sense to file a ticket for RISCV code quality without zbb; it looks like it could be improved a bit.)

Do you have a specific suggestion for improvement?

**Comment by efriedma-quic** [comment]
I thought there was a way to reduce the number of instructions used to materialize the constants... but I misread the code a bit; it can't actually be optimized the way I thought it could. (I suspect some way exists, but I can't see it.)

Filed #86205 and #86207 for related cases which can be optimized.
