### ISSUE TITLE
lldb/source/Utility/Scalar.cpp:756: Condition can never be true

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#85985]
lldb/source/Utility/Scalar.cpp:756:23: warning: Opposite inner 'if' condition leads to a dead code block. [oppositeInnerCondition]

Source code is

  if (sign_bit_pos < max_bit_pos) {
    switch (m_type) {
    case Scalar::e_void:
    case Scalar::e_float:
      return false;

    case Scalar::e_int:
      if (max_bit_pos == sign_bit_pos)
        return true;

**Comment by dcb314** [comment]
git blame says:

99b5474310 (Jonas Hahnfeld 2023-08-01 18:31:51 +0200 756)       if (max_bit_pos == sign_bit_pos)
^99b5474310 (Jonas Hahnfeld 2023-08-01 18:31:51 +0200 757)         return true;

**Comment by dcb314** [comment]
>This is 100% bogus:

Agreed.

> If you click on the commit, you will see that it only added a Clang test. 

Agreed.

>Do you maybe only have a shallow clone without the full history?

Maybe I do. I have had trouble with shallow clones and git blame finding
the wrong commit in the past.

Do you perhaps know who the real author of the code was ?

**Comment by hahnjo** [comment]
Just use the GitHub interface: https://github.com/llvm/llvm-project/blame/e68d505008d878c6303032631fcfd5918b62f3d6/lldb/source/Utility/Scalar.cpp#L756
