### ISSUE TITLE
lldb/source/Core/Debugger.cpp:1118: Pointless code ?

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#85984]
lldb/source/Core/Debugger.cpp:1118:9: warning: Opposite inner 'if' condition leads to a dead code block. [oppositeInnerCondition]

Source code is 

  while (top_reader_sp) {
    if (!top_reader_sp)
      break;

**Comment by Troy-Butler** [comment]
Can you please assign this to me?

**Comment by Troy-Butler** [comment]
Hi, could you please assign this to me?

**Comment by jryans** [comment]
@Troy-Butler I would suggest just working towards a PR, and then submit that when you have it ready.

**Comment by Troy-Butler** [comment]
I really need for it to be assigned to me. I'm making contributions for a project, and they don't count if I'm not assigned.

**Comment by bulbazord** [comment]
> I really need for it to be assigned to me. I'm making contributions for a project, and they don't count if I'm not assigned.

I see you've been asking to be assigned several issues. I'm not sure about other subprojects, but for LLDB there's no policy or precedent for claiming an issue before opening a PR to address an issue (unless you filed the issue and assigned it to yourself). Could you give us some more context about what you're doing? I'd be happy to assign this issue to you after learning a bit more about your situation.

**Comment by Troy-Butler** [comment]
I understand. I'm a university student working on a project for a software development course. The project involves contributing to open source projects, and requires that I am assigned to existing issues and that my pull requests are successfully accepted/merged.

**Comment by bulbazord** [comment]
Thanks for the explanation. I've assigned you this issue, feel free to add me as a reviewer on the associated PR.

**Comment by JDevlieghere** [comment]
Fixed by @Troy-Butler in 2987fca041caddead6655a34009b6a6517d0c7df
