### ISSUE TITLE
fatal error: error in backend: 'fstat64' label emitted multiple times to assembly file

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#8600]
|  |  |
| --- | --- |
| Bugzilla Link | [8228](https://llvm.org/bz8228) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl |

## Extended Description 
When processing a file that includes system headers, the above error is given.

I've preprocessed the code and reduced it as much as possible to get this snippet:

extern int fstat (int __fd) __asm__ ("" "fstat64");

extern __inline__ int fstat (int __fd)
{
  return 0;
}

extern __inline__ int fstat64 (int __fd)
{
  return 0;
}

Compiling the above with clang leads to the error given. Compiling it with GCC does not result in any error.

**Comment by arsenm** [comment]
Comment says problem was in system headers
