### ISSUE TITLE
missed fold, shuffle(shuffle(v1, m1), v2, m2) => shuffle(v1, v2, m3)

### ISSUE THREAD

**Issue by zhengyang92** [llvm/llvm-project#86068]
https://alive2.llvm.org/ce/z/4BPEz9
https://godbolt.org/z/qExEGvbfn (see the subpar codegen)

```
define <2 x float> @src(<2 x float> %0, <2 x float> %1) {
entry:
  %3 = shufflevector <2 x float> %1, <2 x float> poison, <2 x i32> <i32 1, i32 poison>
  %4 = shufflevector <2 x float> %3, <2 x float> %0, <2 x i32> <i32 0, i32 3>
  ret <2 x float> %4

}
define <2 x float> @tgt(<2 x float> %0, <2 x float> %1) {
entry:
  %sv = shufflevector <2 x float> %0, <2 x float> %1, <2 x i32> <i32 3, i32 1>
  ret <2 x float> %sv

}
```
@regehr @dtcxzyw @nikic @efriedma-quic @RKSimon @topperc

**Comment by dtcxzyw** [comment]
> <2 x float> %1, <2 x i32> <i32 3, i32 1>

TBH I am not sure that the generalized folding is always a win :(

https://github.com/llvm/llvm-project/blob/ce8e86971036cb34c3d32cf0b70169379c85ae2f/llvm/lib/Transforms/InstCombine/InstCombineVectorOps.cpp#L1676-L1684

**Comment by RKSimon** [comment]
We avoid shuffle combines in the middle-end - even vector-combine (with its cost based folding) avoids it unless its associated with other instructions.

I can look at fixing the x86 shuffle lowering though.
