### ISSUE TITLE
scan-build "--exclude" option do not exclude 3rparty directory from large project as expected.

### ISSUE THREAD

**Issue by cgilles** [llvm/llvm-project#86094]
Hi,

I'm a long time user of the static analyzer. I parse the whole digiKam project to clean up entries.

The digiKam project includes source code from 3rdparty libraries. I use a bash script to run the analyzer with many "--exclude __absolute_path__" arguments to try to ignore unwanted entries. This do not work as expected...

The bash script can be seen [here](https://invent.kde.org/graphics/digikam/-/blob/master/project/reports/clangscan.sh?ref_type=heads)

The script use a file at root repository dir named .krazy which share configuration with others analyzers (as cppcheck, clazy, krazy, etc.). The file is this [one](https://invent.kde.org/graphics/digikam/-/blob/master/.krazy?ref_type=heads)

The first line of this is the most important as it's a list of relative directory to skip from the analysis.

I generated 3 files resulting of one analyze. 

[01-scan-build-configure.txt](https://github.com/llvm/llvm-project/files/14689836/01-scan-build-configure.txt)

This is the configuration stage where you can see the absolute path to exclude.

[02-scan-build-compilewarnings.txt](https://github.com/llvm/llvm-project/files/14689892/02-scan-build-compilewarnings.txt)

This is a small part of the compilation where a directory excluded is reported with analysis errors.

[03-scan-build-endcompilation.txt](https://github.com/llvm/llvm-project/files/14689915/03-scan-build-endcompilation.txt)

This is the end of the compilation. Look the excluded directories list which is reduced a lots.

The question is... why?

Thanks in advance for your help.

Gilles Caulier

**Comment by cgilles** [comment]
Additional info:
OS: Kubuntu 23.10 Arm
LLVM : 16

**Comment by Sirraide** [comment]
I’m not entirely sure if this is a question or a bug (and I’m not familiar w/ this part of the code base), but have you tried this with a more recent version of LLVM (18 or 19)? If it is a bug, then it may be fixed in a newer version.

**Comment by cgilles** [comment]
hi,

Yes it's a question in a first time as the /usr/include and /opt/qt6/include paths are well excluded from the analysis. So the functionality work, but not with the absolute path pointing in 3rd party libs included in my project...

And no, i don't yet tried with a more recent LLVM version, as the computer is in production. I need to create a VM up-to-date to double check this point.

More Q about the exclude paths : 

- Do i need to pass the absolute path and just a relative path is enough. It's not clear in the documentation.
- What happen with the nested hierarchy from an excluded path ? It's also excluded (eg. foo/bar/lib/ is excluded if i specify foo/bar/ as path) ?
- There is a limitation about path length ?
- There is a limitation of number of excluded paths to pass as arguments ?

Best

Gilles Caulier

**Comment by cgilles** [comment]
Hi,

I updated to LLVM 16 to 17 and problem is exactly the same. There is no more recent LLVM under Ubuntu 23.10...

Gilles Caulier

**Comment by cgilles** [comment]
I fixed the issue by using a dedicated config file for scan-build. Without to figure where the problem is...

To respond to my Q: exclude paths can be absolute and no.

Gilles Caulier
