### ISSUE TITLE
[X86] _mm_sqrt_ps() generates odd rsqrtps with fast-math

### ISSUE THREAD

**Issue by tru** [llvm/llvm-project#86096]
We have some highly tuned math code that's using a lot of intrinsic in one of our code-bases and when we started to convert this code base to Clang we noticed that with fast-math enabled it generates some odd ASM on X86 at times.

The following example shows that:

https://godbolt.org/z/TfoTPbqY1

Giving clang the benefit of the doubt we benchmarked these functions and the one generated by clang is much slower. Only clang generates this construct as well, neither GCC nor MSVC.

Is there a reason for this or is this a bug in the DAG? @RKSimon @phoebewang @nikic

**Comment by tru** [comment]
Ah figured out that if I pass `-march=skylake` we will get a much more sane ASM output, so it must be that clang tries to do optimized instruction based on the older default CPU target.

I think my internal teams expectation was that using a intrinsic would be a much clearer mapping to the ASM instruction used, while clang seems to generate a IR intrinsic that can be converted to be optimized for the selected target. While I might not think it's the best idea, is there a way to let clang know that we want the intrinsic to generate ASM instruction it's supposed to mean, or is it straight to inline assembly at this point?

**Comment by RKSimon** [comment]
You've enabled fast-math so all gloves are off :) If you want to keep generic SSE2 level code to maximize compatibility you can use ` -mtune=skylake` instead? But use inline asm if you really want it, otherwise let clang/llvm do its optimizations.

**Comment by phoebewang** [comment]
> Ah figured out that if I pass `-march=skylake` we will get a much more sane ASM output, so it must be that clang tries to do optimized instruction based on the older default CPU target.

That's right, we have a `TuningFastScalarFSQRT` on recent target which do not generate the `rsqrtps` any more.

> I think my internal teams expectation was that using a intrinsic would be a much clearer mapping to the ASM instruction used, while clang seems to generate a IR intrinsic that can be converted to be optimized for the selected target. While I might not think it's the best idea, is there a way to let clang know that we want the intrinsic to generate ASM instruction it's supposed to mean, or is it straight to inline assembly at this point?

Intrinsics are not always mapped to a single instruction. It just true in most cases due to its implementation. That doesn't mean intrinsic have guarantee on this. I would suppose most user want to compiler chooses the best performed instruction when used with option like `-ffast-math`. We don't have a configurable option to select the preference. An alternative way is to undo fast math on these intrinsics explicitly, e.g, https://godbolt.org/z/3qefhYGov

**Comment by tru** [comment]
Thanks for the explanations! We have a fix for this now. I think this means that everything works as expected and in that case I think we can close this issue.
