### ISSUE TITLE
[X86] Enable constexpr on LZCNT and BMI intrinsics

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#86128]
The x86 specific LZCNT and BMI intrinsics in lzcntintrin.h and bmiintrin.h are all capable of being converted to constexpr

We did something similar for the POPCNT intrinsics here: https://reviews.llvm.org/D86229 / cff0db08761f310dfebb5b41b307d2c12bda85fc

- [x] Update `__builtin_ia32_*` intrinsics to allow handling in ExprConstant
- [x] Update headers - ensuring they work for c, pre-C++11 and later C++ builds
- [x] Test coverage - including the macro variants of some of the methods (e.g. `_tzcnt_u32` for `__tzcnt_u32`)

**Comment by aniplcc** [comment]
I'm interested in taking this one.

**Comment by RKSimon** [comment]
@aniplcc reverse-ping?

**Comment by RKSimon** [comment]
#110499 added support for LZCNT/TZCNT x86 intrinsics

**Comment by RKSimon** [comment]
#110581 added support for BMI1 intrinsics

**Comment by RKSimon** [comment]
#110515 added support for TBM intrinsics

**Comment by RKSimon** [comment]
#110508 / #110535 / #110654 added support for BMI2 BZHI / PDEP+PEXT / MULX intrinsics
