### ISSUE TITLE
FMF on fcmps

### ISSUE THREAD

**Issue by tschuett** [llvm/llvm-project#86164]
I looked at this line:
https://github.com/llvm/llvm-project/blob/d9c4c312d81b4a2059d0ca2bb454c3452e52042e/llvm/lib/Transforms/InstCombine/InstCombineVectorOps.cpp#L490
It does not pass the flags from the matched compare to the newly created. According to the langref fcmps have FMF.

**Comment by tschuett** [comment]
There is no `CmpInst::CreateWithCopiedFlags` constructor.

**Comment by marcauberer** [comment]
I would like to work on this
