### ISSUE TITLE
[HLSL] Remove Double from pow intrinsic

### ISSUE THREAD

**Issue by farzonl** [llvm/llvm-project#86181]
We don't have double pow intrinsics in dxc:
https://godbolt.org/z/P4c8dKvcG

code to be removed:
https://github.com/llvm/llvm-project/blob/main/clang/lib/Headers/hlsl/hlsl_intrinsics.h#L1177C1-L1184C31

The change will also need to remove the accompanying tests.

**Comment by akwotom** [comment]
Hello @farzonl, I would love to give this a try. 
Can you please explain the issue in a different way to aid my understanding?
Thank you.

**Comment by shashu8660** [comment]
hello @farzonl i would like to work with this issue parallel with @akwotom
