### ISSUE TITLE
[X86] GlobalIsel removed type info when legalizing ICMP, causing out of bound access on debug build

### ISSUE THREAD

**Issue by DataCorrupted** [llvm/llvm-project#86203]
## Reproduction 

[Out of bound on debug build](https://godbolt.org/z/zTPP5jbTG) 
[Unable to legalize on release build](https://godbolt.org/z/hrnsaofYY)

The bug can be reproduced on LLVM 16, 17, and upstream.

@phoebewang  Any hints on how should we fix this?

**Comment by e-kud** [comment]
Bug was introduced by me. Preparing a fix.
