### ISSUE TITLE
[mlir][amdgpu][nvgpu] Duplicate pass 'OptimizeSharedMemory' 

### ISSUE THREAD

**Issue by kuhar** [llvm/llvm-project#86208]
Both amdgpu and nvgpu have a transform pass 'OptimizeSharedMemory'. The logic is identical modulo determining the shared memory address spaces.

We should consider merging them and parametrize the bits that differ across the implementations.

**Comment by kuhar** [comment]
cc: @harsh-nod @erman-gurses

**Comment by akwotom** [comment]
### Hi, I would really love to give this a try. 

I admit, it's complex, and I don't know where to start. 

Currently, I understand that the task is to merge the common transform pass feature called, "**OptimizeSharedMemory**", and make the bits that differ across different implementations to become parameters. 
Please, **which files** can I take a look at?
Also, **what is a _transform pass_?**

**Comment by kuhar** [comment]
Hi @akwotom,

Sure, give it a try! The main files are:
* https://github.com/llvm/llvm-project/blob/718fbbef5f18a2b7e7fc4f842b1452ae9bee581a/mlir/lib/Dialect/NVGPU/Transforms/OptimizeSharedMemory.cpp with tests in https://github.com/llvm/llvm-project/blob/main/mlir/test/Dialect/NVGPU/optimize-shared-memory.mlir
* https://github.com/llvm/llvm-project/blob/718fbbef5f18a2b7e7fc4f842b1452ae9bee581a/mlir/lib/Dialect/AMDGPU/Transforms/OptimizeSharedMemory.cpp with tests in https://github.com/llvm/llvm-project/blob/main/mlir/test/Dialect/AMDGPU/optimize_shmem_reads_writes.mlir

I'm not 100% where should put the merged pass, I thought of https://github.com/llvm/llvm-project/tree/main/mlir/lib/Dialect/GPU/Transforms and exposing the address space checks as a callbacks/pass options, such that the pass won't have to know about the vendor dialects like AMDGPU and NVGPU.

**Comment by kuhar** [comment]
Actually never mind, upon closer inspection there is more API surface area than I initially spotted. Given that the pass is small, let's keep is the two implementations separate.
