### ISSUE TITLE
A feature to make clang format not touch macros

### ISSUE THREAD

**Issue by BGOPC** [llvm/llvm-project#86277]
Hey, I'm using Clang format to format my competitive programming codes, I have a large coding template, and when I format using Clang it opens up everything and creates a 100-line mess while when it's compressed it's 31, mostly the thing that happens is this:
```C++
#define sik(x) {cout << x << nl; return;}
```
which turns to this:
```C++
#define sik(x)       \
  {                  \
    cout << x << nl; \
    return;          \
  }
  ```
  please add a flag to tell clang not touch macros

**Comment by owenca** [comment]
See https://releases.llvm.org/18.1.1/tools/clang/docs/ClangFormatStyleOptions.html#skipmacrodefinitionbody.
