### ISSUE TITLE
[DAG] Fold AVGU(ZEXT(X),ZEXT(Y)) -> ZEXT(AVGU(X,Y))

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#86301]
This works for AVGCEILU and AVGFLOORU: https://alive2.llvm.org/ce/z/ea-m5Y

If the pre-extended AVGCEILU/AVGFLOORU node is legal, then we should perform the operation with the shorter width and then extend afterward.

**Comment by houndlord** [comment]
I would like to work on this as well

**Comment by RKSimon** [comment]
@houndlord any progress? #92096 is likely to create more examples of this pattern

**Comment by houndlord** [comment]
Thank you for the new context. 
I think I do not have to touch `TargetLowering` yet and should implement the changes in a similar way to `foldAddToAvg` i.e. pattern matching followed by DAG transformation?

**Comment by RKSimon** [comment]
You should be able to handle this in DAGCombiner::visitAVG

**Comment by RKSimon** [comment]
@houndlord ping?

**Comment by houndlord** [comment]
@RKSimon sorry for the delay. I finished my exams last week and will try to submit a PR as soon as possible.

**Comment by houndlord** [comment]
> @houndlord ping?

Sorry for the delay. Well, it seems @c8ef already picked it up.
