### ISSUE TITLE
Assertion failure with nested parameter packs and lambdas

### ISSUE THREAD

**Issue by dwblaikie** [llvm/llvm-project#86361]
Another similar to https://github.com/llvm/llvm-project/issues/61460 (in fact the original internal reproduce tripped over both #61460 and this new bug - in that once #61460 was fixed, the original reproducer still crashed, so I had to reduce a new reproducer for this bug)
```
template <typename... Ts>
void f1(Ts... ts) {
  [&](auto... indexes) {
    ([&] {
        (ts);
        indexes;
      }, ...);
  };
}
void f2() { f1(); }
```
https://godbolt.org/z/6KW6jT1n7

**Comment by dwblaikie** [comment]
@zyn0217 in case this one interests you as much as #61460

**Comment by shafik** [comment]
Confirmed

**Comment by zyn0217** [comment]
Yeah, at my first glance this is similar to #85667, but the crash stacktrace is different.

**Comment by zyn0217** [comment]
I took a closer look and realized this is not #85667 but rather falls into the same problem as #61460 - the nuance is that we have extra parentheses on the `FunctionParmPackExpr` so the guard condition gets bypassed.
