### ISSUE TITLE
Backport request for fix POCL building on LoongArch

### ISSUE THREAD

**Issue by ouankou** [llvm/llvm-project#86370]
When building the main branch (6.0 pre-release) of [POCL](http://portablecl.org/) on LoongArch, 74 out of 252 tests failed because they lacked `addrspacecast` support. If we backport this [commit](https://github.com/llvm/llvm-project/commit/dd3e0a4643670f33850278ad281a358bbdd04e92) to the 18.x release, they all passed. The changes are only applied to LoongArch target.

/cherry-pick https://github.com/llvm/llvm-project/commit/dd3e0a4643670f33850278ad281a358bbdd04e92

```bash
  STDOUT:

  STDERR:

  6 warnings generated.

  LLVM ERROR: Cannot select: 0x7fffd94c7390: i64 = addrspacecast[0 -> 2]
  0x7fffd905c940

    0x7fffd905c940: i64 = PseudoLA_PCREL TargetGlobalAddress:i64<ptr @.str> 0
      0x7fffd94a5710: i64 = TargetGlobalAddress<ptr @.str> 0

  In function: _pocl_kernel_draw
```

**Comment by EugeneZelenko** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/dd3e0a4643670f33850278ad281a358bbdd04e92
