### ISSUE TITLE
Inconsistency in macos/macosx version CLI flag vs. availability attributes/macros

### ISSUE THREAD

**Issue by h-vetinari** [llvm/llvm-project#86376]
The clang attribute [reference](https://clang.llvm.org/docs/AttributeReference.html#availability) says:
> * `macos`: 
>     Apple’s macOS operating system. The minimum deployment target is specified by the `-mmacosx-version-min=*version*` command-line argument. `macosx` is supported for backward-compatibility reasons, but it is deprecated.

So we learn that the attribute should be spelled with `macos`, not `macosx`:
```
__attribute__((availability(macos,introduced=10.14)))
```
however, the CLI-flag as documented still uses the "x":
```
-mmacosx-version-min=*version*
       ^
       X
```
At the very least, this leads to confusion, as both forms are found in the current LLVM repo:
* search for [`-mmacosx-version-min`](https://github.com/search?q=repo%3Allvm%2Fllvm-project%20%2F-mmacosx-version-min%2F&type=code)
* search for [`-mmacos-version-min`](https://github.com/search?q=repo%3Allvm%2Fllvm-project%20%2F-mmacos-version-min%2F&type=code)

I also believe it may lead to bugs, in the sense that `-mmacosx-version-min=10.9` in newer clang ends up not setting `MAC_OS_X_VERSION_MIN_REQUIRED` or `__MAC_OS_X_VERSION_MIN_REQUIRED`?

I don't have a mac to test this hypothesis, but this is consistent with the failures I'm seeing.

**Comment by h-vetinari** [comment]
CC @ldionne

**Comment by Xazax-hun** [comment]
The driver currently accepts both `-mmacosx-version-min=10.9` and `-mmacos-version-min=10.9`, they are aliases: https://github.com/llvm/llvm-project/blob/f3afdc4ad980bfba5c196f2248bedf03945cd32a/clang/include/clang/Driver/Options.td#L4680

I tested them with the following small program and both seem to work as expected:
```
#include <AvailabilityMacros.h>
#include <iostream>

int main() {
  std::cout << MAC_OS_X_VERSION_MIN_REQUIRED << " "  << __MAC_OS_X_VERSION_MIN_REQUIRED << std::endl;
}
```

Is there any action item in this ticket? E.g., do we want to make one of the flags deprecated, potentially emitting a warning to migrate to another one? I am not sure how often are we doing that in Clang.

**Comment by h-vetinari** [comment]
Thanks for the response!

From my POV, the _default_ CLI flag should match the naming in the availability macros, i.e. use `macos` not `macosx`. I don't care particularly if or how long the `macosx` spelling is kept around as an alias, but aside from the definition of the alias (and perhaps some docs about the preferred way going forward), all mentions of `-mmacosx-version-min` in the codebase should vanish IMO (and replaced by `-mmacos-version-min`).

**Comment by ldionne** [comment]
^ I agree. Basically, the action item in this ticket would be to make sure that the default flag is `-mmacos-version-min` and that the other one is an alias for it, and to update any references in the documentation that use `-mmacosx-version-min` to start steering users towards the preferred spelling.

**Comment by Xazax-hun** [comment]
I opened a PR to update the documentation and tests. I also realized scan-build did not properly handle the new spelling, so I also updated that.
