### ISSUE TITLE
flang/lib/Semantics/tools.cpp:1290: Possible missing return ?

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#86391]
Static analyser cppcheck says:

flang/lib/Semantics/tools.cpp:1290:3: error: Found an exit path from function with non-void return type that has missing return statement [missingReturn]

Source code is

  } else if constexpr (componentKind == ComponentKind::PotentialAndPointer) {
    return true;
  }
}

Suggest add return statement at end of function.

**Comment by klausler** [comment]
https://github.com/llvm/llvm-project/pull/86523

**Comment by firewave** [comment]
Since the branch is unreachable because all possible values are covered this could be considered a false positive. I filed https://trac.cppcheck.net/ticket/12551 upstream about this.
