### ISSUE TITLE
[Clang] Deducing this Lambda ignores assignment rules for captured references

### ISSUE THREAD

**Issue by Link1J** [llvm/llvm-project#86398]
When using C++23 deducing this, captured references are assignable to anything.
The following code compiles with `clang -std=c++23`, when it clearly shouldn't. [Godbolt](https://godbolt.org/z/7TMoPK6an)
```c++
struct function {};
int main() {
    function list;
    [&list](this auto self) {
        list = self;
    }();
}
```
It even works with types that are not assignable. [Godbolt](https://godbolt.org/z/scazq7sfo)
```c++
struct function {
    function& operator=(function const&) = delete;
};
int main() {
    function list;
    [&list](this auto self) {
        list = self;
    }();
}
```
And even it doesn't even need `self` as part of the assignment expression. [Godbolt](https://godbolt.org/z/8jxs4Pxbb)
```c++
struct function {
    function& operator=(function const&) = delete;
};
int main() {
    function list;
    [&list](this auto self) {
        list = function{};
    }();
}
```

**Comment by Sirraide** [comment]
This is basically #84163 but also not technically a duplicate; either way, it’s also fixed by #84473.
