### ISSUE TITLE
[flang] OpenBLAS 0.3.27 (with openmp) not buildable on windows with flang 18

### ISSUE THREAD

**Issue by h-vetinari** [llvm/llvm-project#86463]
I had been under the impression that flang had already been able to compile BLAS/LAPACK and OpenBLAS successfully (c.f. https://github.com/llvm/llvm-project/issues/64750, https://github.com/llvm/llvm-project/issues/67675, https://github.com/llvm/llvm-project/issues/70458).

However, while trying to use flang 19.0.0 (as of https://github.com/llvm/llvm-project/commit/edf5782f1780f480c3ae3fc0a44bf5432f9aa48b) to compile OpenBLAS 0.3.27, there's a missing `omp_lib` module
```
[...]
[3643/19184] Building Fortran object CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\stplqt.f.obj
[3644/19184] Building Fortran object CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\stplqt2.f.obj
[3645/19184] Building Fortran object CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\stpmlqt.f.obj
[3646/19184] Building Fortran object CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\ssytrd_2stage.f.obj
[3647/19184] Building Fortran object CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\ssytrd_sb2st.F.obj
FAILED: CMakeFiles/LAPACK_OVERRIDES.dir/lapack-netlib/SRC/ssytrd_sb2st.F.obj 
%BUILD_PREFIX%\Library\bin\flang.exe -I%SRC_DIR%\lapack-netlib\SRC -I%SRC_DIR%\lapack-netlib\LAPACKE\include -fopenmp -fopenmp -ffixed-line-length-72 -o CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\ssytrd_sb2st.F.obj -c CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\ssytrd_sb2st.F-pp.f
error: Semantic errors in CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\ssytrd_sb2st.F-pp.f
D:\\bld\\openblas_1719536014536\\work\\lapack-netlib\\SRC\\ssytrd_sb2st.F:237:11: error: Cannot read module file for module 'omp_lib': Source file 'omp_lib.mod' was not found
        use omp_lib
            ^^^^^^^
```

---------

_Previously:_

While [trying](https://github.com/conda-forge/openblas-feedstock/pull/115)[^1] to use flang 18.1.2 to compile the latest OpenBLAS 0.3.26 (aside from from backporting a small [fix](https://github.com/OpenMathLib/OpenBLAS/commit/52b71a1673dfe1fddfcbae3b8a03486438223fdf) due to flang 18 being stricter on unknown flags), things fail pretty early with what looks like a parsing problem...

[^1]: despite the title of the PR, the error here is for the case with `USE_OPENMP=0`, i.e. no OpenMP; with OpenMP I still have to fix stuff around `OpenMP_Fortran`

```
[2005/19090] Building Fortran object CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\sgbcon.f.obj
FAILED: CMakeFiles/LAPACK_OVERRIDES.dir/lapack-netlib/SRC/sgbcon.f.obj 
%BUILD_PREFIX%\Library\bin\flang.exe -I%SRC_DIR%\lapack-netlib\SRC -I%SRC_DIR%\lapack-netlib\LAPACKE\include -ffixed-line-length-72 -o CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\sgbcon.f.obj -c CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\sgbcon.f-pp.f
error: loc("D:\\bld\\openblas_1711274852957\\work\\lapack-netlib\\SRC\\sgbcon.f":206:7): operation with block successors must terminate its parent block

error: verification of lowering to FIR failed
```

Looking for the error message, the only open issue I've found is https://github.com/llvm/llvm-project/issues/61281, but that issue explicitly says "This case is OK in OpenMP". There's also https://github.com/llvm/llvm-project/issues/74348 (which got fixed in 18.1) and https://github.com/llvm/llvm-project/issues/72792 (where it's unclear when/what was fixed).

**Comment by h-vetinari** [comment]
Hm, this might somehow be related to https://github.com/llvm/llvm-project/issues/86459?

**Comment by h-vetinari** [comment]
While building OpenBLAS with flang built from main still fails, the good news is that this particular failure seems to have been resolved. Now we're failing at:
```
3643/19184] Building Fortran object CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\stplqt.f.obj
[3644/19184] Building Fortran object CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\stplqt2.f.obj
[3645/19184] Building Fortran object CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\stpmlqt.f.obj
[3646/19184] Building Fortran object CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\ssytrd_2stage.f.obj
[3647/19184] Building Fortran object CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\ssytrd_sb2st.F.obj
FAILED: CMakeFiles/LAPACK_OVERRIDES.dir/lapack-netlib/SRC/ssytrd_sb2st.F.obj 
%BUILD_PREFIX%\Library\bin\flang.exe -I%SRC_DIR%\lapack-netlib\SRC -I%SRC_DIR%\lapack-netlib\LAPACKE\include -fopenmp -fopenmp -ffixed-line-length-72 -o CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\ssytrd_sb2st.F.obj -c CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\ssytrd_sb2st.F-pp.f
error: Semantic errors in CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\ssytrd_sb2st.F-pp.f
D:\\bld\\openblas_1719536014536\\work\\lapack-netlib\\SRC\\ssytrd_sb2st.F:237:11: error: Cannot read module file for module 'omp_lib': Source file 'omp_lib.mod' was not found
        use omp_lib
            ^^^^^^^
```
At first glance, this looks like a problem in OpenBLAS, thus I opened: https://github.com/OpenMathLib/OpenBLAS/issues/4768

**Comment by h-vetinari** [comment]
OK, so the missing `omp_lib` module is apparently flang's responsibility after all.

CC @banach-space @kiranchandramohan

**Comment by h-vetinari** [comment]
OK, so the non-openmp build actually passed (even though it generated logs so big that I cannot seem to download them, presuambly from warning spam). So the question reduces to OpenBLAS on windows with openmp enabled.

**Comment by tblah** [comment]
Thanks for reporting the issue.

Please could you test again after https://github.com/llvm/llvm-project/pull/96557

**Comment by tblah** [comment]
How are you building flang and openmp? I wonder if https://github.com/llvm/llvm-project/pull/90888 could be related.

**Comment by h-vetinari** [comment]
> How are you building flang and openmp?

Everything is built stand-alone but from a consistent version (or commit, in this case). I'm using indentation to indicate dependency:
* [libllvm, llvm-tools, lit](https://github.com/conda-forge/llvmdev-feedstock/blob/dev/recipe/bld.bat)
  * [openmp](https://github.com/conda-forge/openmp-feedstock/blob/dev/recipe/bld-llvm-openmp.bat)
  * [mlir](https://github.com/conda-forge/mlir-feedstock/blob/dev/recipe/bld.bat)
  * [clang, clangxx, libclang, etc.](https://github.com/conda-forge/clangdev-feedstock/blob/dev/recipe/bld.bat)
    * [compiler-rt](https://github.com/conda-forge/compiler-rt-feedstock/blob/dev/recipe/bld.bat)
      * [flang](https://github.com/conda-forge/flang-feedstock/blob/dev/recipe/bld.bat) (also depends on mlir & openmp)

> I wonder if #90888 could be related.

That definitely sounds plausible! I could test that patch on top of our openmp builds and see if it changes anything, if that helps.

**Comment by h-vetinari** [comment]
Looking a bit closer, it could just be that we need to set `-DLIBOMP_FORTRAN_MODULES=ON`? 🤔

**Comment by h-vetinari** [comment]
So I managed to build `omp_lib.mod` and have it be used by the openblas build, so that's nice. Currently failing at the linking stage, but I think that's just a path question. Will report back once this is figured out.

**Comment by h-vetinari** [comment]
I'm happy to report that (using a small [fix](https://github.com/OpenMathLib/OpenBLAS/issues/4768#issuecomment-2213594747) to explicitly link `OpenMP::OpenMP_C`), a ~2 week old flang 19 (as of edf5782f1780f480c3ae3fc0a44bf5432f9aa48b, to be precise) is able to build OpenBLAS also on windows. 🥳 

There's some issues with the OpenMP configuration for the Fortran bits not correctly being picked up by CMake's `find_package(OpenMP)`, but that's out of scope here (though follow the link for an explanation, if you're interested).

Leaving this open for a little while longer in case there are comments, but otherwise this can be closed now. :)
