### ISSUE TITLE
Porting from version llvm 3.8 project to 14.0.6 project,met up with error,error occurs  D:\LLVM\llvm14\llvm\include\llvm\ADT\BitVector.h	485 enum : unsigned { ExprResultIdx = std::numeric_limits<unsigned>::max() }; compile error in for (unsigned i = 0, e = std::min(ThisWords, RHSWords); i != e; ++i)	D:\LLVM\llvm14\llvm\include\llvm\Analysis\AssumptionCache.h	46 error in 

### ISSUE THREAD

**Issue by bethebset** [llvm/llvm-project#86510]
build on visual studio 2019 llvm14.0.6, Windows 10,The error occurs in the header files ADT\BitVector.h and Analysis\AssumptionCache.h under the llvm/include directory, where errors are reported at std::min and std::numeric_limits<unsigned>::max().And finally The source code has no syntax errors.But when compile main cpp,the error occurs.Unable to recover from previous errors; stopping compilation. Compiler internal error at D:\LLVM\llvm14\llvm\include\llvm\IR\Operator.h 198

**Comment by dtcxzyw** [comment]
> Unable to recover from previous errors; stopping compilation. Compiler internal error at

This is an MSVC bug. Please report the issue to https://developercommunity.visualstudio.com/cpp.
See also https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1903?view=msvc-170

**Comment by dtcxzyw** [comment]
BTW llvm14 is not longer maintained. You can try llvm18 or later :)

**Comment by bethebset** [comment]
> > Unable to recover from previous errors; stopping compilation. Compiler internal error at
> 
> This is an MSVC bug. Please report the issue to https://developercommunity.visualstudio.com/cpp. See also https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1903?view=msvc-170

Thanks a lot.I will give it a try!
