### ISSUE TITLE
[clang] __builtin_clzg / __builtin_ctzg aren't usable in constexpr contexts

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#86549]
These newly added builtins (#83431) can't used in `constexpr` contexts.  https://godbolt.org/z/ebP4E7rqd

I'd like to be able to use them a la #86531.  I think it's a quick fix to just add `Constexpr` to the `Attributes` for these in clang/include/clang/Basic/Builtins.td, but we should add some unit tests for this.

I also think we should audit some of these builtins to see where else `constexpr` support might be missing.

https://github.com/llvm/llvm-project/pull/83431/files#r1538025252 may be useful.

cc @overmighty @efriedma-quic

**Comment by overmighty** [comment]
I can work on this now unless you wish to leave it for someone else due to the "good first issue" label.
