### ISSUE TITLE
[libc] remove LIBC_HAS_ATTRIBUTE

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#86547]
Similar to #86546, `__has_attribute` has also long been supported by modern toolchains; at least the versions we advertise support for.
https://libc.llvm.org/compiler_support.html

We should remove this preprocessor macro and its usage throughout the codebase. cc @gchatelet

**Comment by nickdesaulniers** [comment]
Yeah! Thanks for the help!

**Comment by gchatelet** [comment]
SGTM. While we're at it, how about bundling the macros under a single header _a la_ [type_traits](https://github.com/llvm/llvm-project/blob/main/libc/src/__support/CPP/type_traits.h) to reduce `#include` and build targets?

**Comment by Unique-Usman** [comment]
> SGTM. While we're at it, how about bundling the macros under a single header _a la_ [type_traits](https://github.com/llvm/llvm-project/blob/main/libc/src/__support/CPP/type_traits.h) to reduce `#include` and build targets?

Hello @gchatelet, is this I can work since @vinayakdsci is working on this current issue. Thank you.

**Comment by gchatelet** [comment]
> > SGTM. While we're at it, how about bundling the macros under a single header _a la_ [type_traits](https://github.com/llvm/llvm-project/blob/main/libc/src/__support/CPP/type_traits.h) to reduce `#include` and build targets?
> 
> Hello @gchatelet, is this I can work since @vinayakdsci is working on this current issue. Thank you.

Sure, I just want to make sure @nickdesaulniers is in favor of this change first. It may be a low value churn.

**Comment by nickdesaulniers** [comment]
> how about bundling the macros

Which macros?
