### ISSUE TITLE
[libc] remove LIBC_HAS_BUILTIN

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#86546]
libc/src/__support/macros/config.h defines LIBC_HAS_BUILTIN. This was necessary to support older compilers that did not support `__has_builtin`.  All of the compilers we support already have this builtin.
https://libc.llvm.org/compiler_support.html

We should remove this preprocessor macro and its usage throughout the codebase. cc @gchatelet

**Comment by marcauberer** [comment]
@nickdesaulniers I would want to work on this

**Comment by nickdesaulniers** [comment]
@marcauberer all yours! Thanks!
