### ISSUE TITLE
[libc] implement pathconf/fpathconf

### ISSUE THREAD

**Issue by SchrodingerZhu** [llvm/llvm-project#86544]
Now that #86169 added `linux_statfs` and `linux_fstatvs`. We can be use them to implement `pathconf` and `fpathconf`.

See also:
- https://android.googlesource.com/platform/bionic/+/refs/heads/main/libc/bionic/pathconf.cpp
- https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/
- https://linux.die.net/man/3/pathconf

**Comment by SchrodingerZhu** [comment]
@robincaloudis want to take a look?

**Comment by changkhothuychung** [comment]
If this is available I would like to take this issue.

**Comment by robincaloudis** [comment]
@changkhothuychung, sure, go ahead. @SchrodingerZhu, I would overtake in case no patch is provided. The necessary steps seem to be clear. However, as I am on vacation for a few days, it is going to take me until mid/end of next week. In case that's too late for you, you or someone else is more than welcome to overtake.

**Comment by Unique-Usman** [comment]
@changkhothuychung, are you still working on this issue, if not I will like to work on it.

**Comment by SchrodingerZhu** [comment]
I will assign @changkhothuychung first since they signed up earlier for this. Feel free to update me if there is anything changed.

**Comment by changkhothuychung** [comment]
@SchrodingerZhu Thanks for assigning this to me. I have a question, since you mentioned the link of the implementation from android, am I allowed to reference it to implement in libc?
