### ISSUE TITLE
[tapi] XCode14 *.tbd + lld (TextAPI) => invalid imports

### ISSUE THREAD

**Issue by alx32** [llvm/llvm-project#86548]
Hello,

I am seeing an issue where using an older version of `tapi` binary to generate `*.tbd`'s for libraries is ending up with invalid binaries after [this change](https://reviews.llvm.org/D149860#inline-1455260). The issue seems to be coming from [SymbolSet.h](https://github.com/llvm/llvm-project/blob/main/llvm/include/llvm/TextAPI/SymbolSet.h#L105) - where if a binary has a `_OBJC_EHTYPE_` for a class, then it is assumed that the binary also has the class. This is not always true - as the following example shows. 

The issue only repro's if using XCode 14's `tapi` binary to generated the `*.tbd` for a library. This is because it exports the `_OBJC_EHTYPE_` as:
```
objc-eh-types:   [ Banana ]
```
Whereas XCode 15 (as well as `llvm-readtapi -stubify`) exports the  `_OBJC_EHTYPE_` as:
```
weak-symbols:    [ '_OBJC_EHTYPE_$_Banana' ]
```

In the below repro, the issue is that `BananaStore_LinkTbd.dylib` is trying to import `_OBJC_CLASS_$_Banana` from `BananaPealer.dylib`.  The class is actually located in `BananaLib.dylib`.

The script requires llvm's `clang`(and `ld64.lld`) and XCode14's `tapi` (or just use the linked `gist`'s).
In the script output, notice the difference when importing the library directly vs the `*.tbd`:
```
Printing where from BananaStore_LinkDirect.dylib imports _OBJC_CLASS_$_Banana:
        __DATA       __objc_data      0x000080C0              bind  BananaLib.dylib/_OBJC_CLASS_$_Banana
Printing where from BananaStore_LinkTbd.dylib    imports _OBJC_CLASS_$_Banana:
        __DATA       __objc_data      0x000080C0              bind  BananaPealer.dylib/_OBJC_CLASS_$_Banana
```

`repro.sh` (Has to be run on MacOS - update first 2 lines with your paths)
```
CLANG_BIN=~/llvm-project/build/Debug/bin/clang
TAPI_BIN=/Applications/Xcode_14/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/tapi

mkdir -p /tmp/banana_test
cd /tmp/banana_test
rm -f /tmp/banana_test/*

echo '
  __attribute__((objc_root_class)) @interface Banana @end
' > Banana.h

echo '
  #import "Banana.h"
  @implementation Banana @end
  void *_objc_empty_vtable;
  void *_objc_empty_cache;
' > BananaLib.mm

echo '
  #import "Banana.h"
  extern "C" void pealBanana();
  extern "C" void pealBanana() {
    try {} catch (Banana *error) {}
  }
  void *objc_ehtype_vtable;
  void *objc_empty_cache;
  void *objc_empty_vtable;
' > BananaPealer.mm

echo '
  #import "Banana.h"
  @interface BananaStore : Banana @end
  @implementation BananaStore @end
' > BananaStore.mm


DYLD_INFO_BIN=$(xcrun --find dyld_info)
CLANG_COMMON="-nostdlib -fPIC -target arm64-apple-macos -arch arm64 -fuse-ld=lld -Wl,-dylib,-dynamic,-platform_version,macos,11.0.0,11.0.0 -mmacosx-version-min=11.0"

$CLANG_BIN $CLANG_COMMON -o BananaLib.dylib BananaLib.mm
$TAPI_BIN -stubify --filetype=tbd-v4 BananaLib.dylib # BananaLib.tbd - https://gist.github.com/alx32/03bbe94c2e9459bad63825e974195d48
$CLANG_BIN $CLANG_COMMON -o BananaPealer.dylib BananaPealer.mm -Wl,BananaLib.dylib
$TAPI_BIN -stubify --filetype=tbd-v4 BananaPealer.dylib # BananaPealer.tbd - https://gist.github.com/alx32/b800a8547e4686616cc986183051bbec
$CLANG_BIN $CLANG_COMMON -o BananaStore_LinkDirect.dylib BananaStore.mm -Wl,BananaPealer.dylib,BananaLib.dylib
$CLANG_BIN $CLANG_COMMON -o BananaStore_LinkTbd.dylib BananaStore.mm -Wl,BananaPealer.tbd,BananaLib.tbd

echo 'Printing where from BananaStore_LinkDirect.dylib imports _OBJC_CLASS_$_Banana:'
dyld_info -fixups BananaStore_LinkDirect.dylib | grep '_OBJC_CLASS_$_Banana'

echo 'Printing where from BananaStore_LinkTbd.dylib    imports _OBJC_CLASS_$_Banana:'
dyld_info -fixups BananaStore_LinkTbd.dylib | grep '_OBJC_CLASS_$_Banana'
```

Q: Is this actually an issue in llvm or is XCode14's `tapi` producing invalid `*.tbd`'s ? 
Q: Is it possible to hit this issue in any other scenario - or this is strictly related to XCode14 invalid `*.tbd`'s?

**Comment by alx32** [comment]
@cyndyishida / @ributzka - the comments [here](https://reviews.llvm.org/D149860#inline-1455260) seem to have some potential overlap with the issue - do you have more context or could you tag someone that would know more ?

**Comment by cyndyishida** [comment]
> Q: Is this actually an issue in llvm or is XCode14's tapi producing invalid *.tbd's ?

The issue you described about `OBJC_EHTYPE` symbols was indeed a tapi bug and should be resolved in Xcode 15 and up-to-date versions of `llvm-readtapi -stubify` as you mentioned.

> Q: Is it possible to hit this issue in any other scenario - or this is strictly related to XCode14 invalid *.tbd's?
 
I can't speak for every TBD file out in the wild, but generally speaking, if you run into issues with the latest versions of tools, it's definitely possible we don't know about it, so please file issues. Otherwise, if you observe bugs in older versions of tools, but not newer ones, it's safe to assume they have been fixed. 

FWIW, you should able to directly run `llvm-readtapi -compare <binary dylib> <tbd file>` and see if the tbd file was missing or has incorrect information. It's not always a bug but in the case of `stubify` generated TBD files, it should usually be the same.
