### ISSUE TITLE
[libcxx] utilize __builtin_popcountg, __builtin_clzg, __builtin_ctzg

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#86556]
clang-19+ and gcc-14+ will support type generic builtins (only for unsigned types) for these builtins.

I see them being used in:
- libcxx/include/__bit/countl.h (__builtin_clz{l|ll})
- libcxx/include/__bit/countr.h (__builtin_ctz{l|ll})
- src/include/ryu/ryu.h (ctz)
- include/__bit/popcount.h (__builtin_popcount{l|ll})
- test/libcxx/containers/unord/next_pow2.pass.cpp (popcount)

There's currently a slight issue in clang-19 with the clz + ctz builtins that I expect to get resolved quickly and before the clang-19 release.  https://github.com/llvm/llvm-project/issues/86549

(Consider whether this request may improve things, and if so, does it make sense to tag it as a good first issue?)

https://github.com/llvm/llvm-project/commit/b1e40ede9fd2cd33c7f533147827b23541c516c9 is an example of me utilizing `__builtin_popcountg` in llvm-libc as an example.

**Comment by marcauberer** [comment]
@nickdesaulniers Can you assign me?
