### ISSUE TITLE
[libc][c11] implement ctime

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#86567]
@alanzhao1 points out that quake3 uses `man 3 ctime`.  We already support `asctime`; my guess is that `ctime` would be similar to implement in terms of `LIBC_NAMESPACE::time_utils` but for a different input parameter type.

**Comment by aniplcc** [comment]
I'd like to implement this.

**Comment by nickdesaulniers** [comment]
Thanks @aniplcc !

**Comment by SharmaRithik** [comment]
Can I request any update on this issue?

**Comment by aniplcc** [comment]
I'm working on it, (a bit busy with exams rn)
It actually involves two more dependencies,
`man 3 tzset` 
and 
`man 3 localtime`
to be implemented as well.

**Comment by SharmaRithik** [comment]
Thanks for the update. Sounds good! Let me know if you need any help or reviews.

**Comment by tszhin-swe** [comment]
Hello @aniplcc, are you still working on this? If not, I would be happy to take over.

**Comment by SharmaRithik** [comment]
This has been up for a while. Thanks @tszhin-swe, please ping here for any questions!

**Comment by zimirza** [comment]
I hope it is ok if I created a pull request for this.

**Comment by michaelrj-google** [comment]
Yes, I'll reassign this issue to you and review your PR soon.
