### ISSUE TITLE
[DXIL] implement `reversebits` lowering

### ISSUE THREAD

**Issue by farzonl** [llvm/llvm-project#86582]
https://godbolt.org/z/so4fxz4xM

Simple change just need to add mapping from `llvm::Intrinsic::bitreverse` to dixil op `30`

like so:
```
call i16 @dx.op.unary.i16(i32 30, i16 %x)
call i32 @dx.op.unary.i32(i32 30, i32 %x)
call i64 @dx.op.unary.i64(i32 30, i64 %x)
```

**Comment by hekota** [comment]
I can take a look at this.
