### ISSUE TITLE
[aarch64] Prefer use callee save register to avoid repeat load when cross call

### ISSUE THREAD

**Issue by vfdff** [llvm/llvm-project#86635]
* test: https://gcc.godbolt.org/z/hdPf8veEc
```
float foo (float num[], float r2inv, int n) {
   float sum = 0.0;
   for (int i=0; i < 1000; i++) {
       float a = num[i];
       // const float r = a / std::sqrt (r2inv);
       const float expm2 = std::exp (a);

       float tmp = expm2 * num[i];
       sum += tmp * tmp;
   }
    
    return sum;
}
```

* llvm:  When built with O3, use 2 load to get num[i] **before** and **after** the call expf
```
.LBB0_1:                                // =>This Inner Loop Header: Depth=1
        ldr     s0, [x19, x20]  // load num[i]
        bl      expf
        ldr     s1, [x19, x20]   // repeat load the num[i]
        add     x20, x20, #4
        cmp     x20, #4000
        fmul    s0, s0, s1
        fmadd   s8, s0, s0, s8
        b.ne    .LBB0_1
```
* gcc: Only one load for num[i] because it use the callee save register
```
.L2:
        ldr     s15, [x19], 4
        fmov    s0, s15
        bl      expf
        fmul    s15, s15, s0
        fmadd   s14, s15, s15, s14
        cmp     x19, x20
        bne     .L2
```

**Comment by jroelofs** [comment]
I bet this is alias-analysis related, since adding `__restrict` fixes it: https://gcc.godbolt.org/z/s9x7hcvrM

Marking the called function `pure` also fixes it: https://gcc.godbolt.org/z/vedjadMh3

**Comment by vfdff** [comment]
Thanks @jroelofs for your input
so it more likely gcc will add `pure` attribute for buildin math function? gcc also use 2 load if we delete the `pure` attribute for fn,
https://gcc.godbolt.org/z/f1W98eehq

**Comment by vfdff** [comment]
It seems math libraries will access (read & write) global variable **error** if `without -ffast-math`, so they are not pure in that case, and it is more likely a **alias-analysis** related.

**Comment by vfdff** [comment]
Add option **-fno-math-errno** can avoid the issue for clang,  https://gcc.godbolt.org/z/hcqrWhhMb
