### ISSUE TITLE
Why doesn't LLDB use Clang's MCDisassembler class to decode RISCV instructions?

### ISSUE THREAD

**Issue by zzh1010016195** [llvm/llvm-project#86646]
https://github.com/llvm/llvm-project/blob/6a6f9bf38e65ec45b32da4b578e2830341a9b364/lldb/source/Plugins/Instruction/RISCV/EmulateInstructionRISCV.cpp#L70C1-L76C1

I'm glad to see that LLDB supports debugging of RISCV programs. I have a little doubt. Why did the RISCV Instruction plugin choose to decode the instructions itself instead of using the MCDisassembler class provided by Clang? RISCV is an extensible instruction set, and if someone adds a custom instruction, LLDB will have to be updated to support it. If LLDB uses MCDisassembler, it can offload all of this work to Clang, which is what I noticed with the MIPS Instruction plugin. What is the reason that makes LLDB decide to implement the instruction decoding by itself?

I sincerely hope to receive an answer, thank you. @bulbazord

**Comment by zzh1010016195** [comment]
In addition, RISCV supports the combination of different features. Whether the current RISCV instruction decoding function can meet this requirement? :smiley:

**Comment by DavidSpickett** [comment]
> I'm glad to see that LLDB supports debugging of RISCV programs.

Kinda, follow https://github.com/llvm/llvm-project/issues/55383 for the up to date status.

>What is the reason that makes LLDB decide to implement the instruction decoding by itself?

I reviewed most of the code there and at the time didn't know that MIPS had taken this approach, and likely neither did the contributor. We were using the AArch64 and Arm plugins as examples more so I think, and those don't do this.

That could just be chance or it could be that there are many fewer instructions we need to emulate, so it wasn't a problem to write it out manually.

>  RISCV is an extensible instruction set, and if someone adds a custom instruction, LLDB will have to be updated to support it. 

True but we're talking about instruction emulation here, so you would need to add an emulation routine regardless of whether MCDisassembler could do the disassembly for you. And if an instruction doesn't need emulation, it doesn't matter that the emulation plugin doesn't know what it is.

The disassembly you see *inside* the debugger is done using MCDisassembler so it will automatically pick up new encodings as you'd expect.

However you are correct that taking the MIPS approach would save some work and in hindsight should have been considered.

And if you're wondering why RISC-V has to emulate so many instructions my understanding is that it lacked (lacks? I don't keep up with it) a standardised hardware single step mechanism. This means the debugger has to emulate what the instruction would have done to implement single stepping efficiently.

**Comment by DavidSpickett** [comment]
> In addition, RISCV supports the combination of different features. Whether the current RISCV instruction decoding function can meet this requirement? 😃

Well as long as they never overlap in encoding it shouldn't be an issue. Generally we initialise disassemblers with the maximum feature set for the architecture, certainly AArch64 does this.

So lldb will have the ability to decode exotic extensions always but we assume program files aren't going to include those encodings unless they actually intended to. llvm-objump takes the same approach for AArch64.

I seem to recall that it does not for RISC-V, but I could be misremembering. It might use the object file flags to enable extensions.

**Comment by zzh1010016195** [comment]
Thank you for such a detailed explanation. 

> I seem to recall that it does not for RISC-V, but I could be misremembering. It might use the object file flags to enable extensions.

The enabled RISC-V extensions are recorded in the object file. I am unsure if it is the object file flags you said. You can see the information using `readelf -A <program>`. Such as:
```
Attribute Section: riscv
File Attributes
  Tag_RISCV_stack_align: 16-bytes
  Tag_RISCV_arch: "rv64i2p1_m2p0_a2p1_f2p2_d2p2_c2p0_zicsr2p0_zifencei2p0"
```

You mentioned:
>  And if an instruction doesn't need emulation, it doesn't matter that the emulation plugin doesn't know what it is.

In addition to the single step, Emulation plugins are also used for stack unwinding. So for LLDB, what instructions must be emulated?

**Comment by DavidSpickett** [comment]
> So for LLDB, what instructions must be emulated?

No idea. Random ideas to find out - check your ABI documentation, look at what has been added to other plugins, look at what has been done in libunwind, try backtracing in a bunch of random programs, see what works and what doesn't.

There's probably some rule of thumb to it but not my area of expertise.
