### ISSUE TITLE
[Clang-18 Miscompilation] clang miscompiles loop with break

### ISSUE THREAD

**Issue by wierton** [llvm/llvm-project#86685]
Compiler Explorer: https://gcc.godbolt.org/z/3s1ezjzW4
I sanitized this program with ubsan,msan and asan, they report nothing as shown in the CompilerExplorer, so I think this is likely a true miscompilation bug.

Below shows the bug triggering program:
```
#include <stdio.h>
#include <stdlib.h>

void foo(int *s, float *f, long n)
{
  for (long i = 0; i < n; ++i) {
    *f = 2;
    if (i == 1) break;
    *s = 4;
  }
}

int main(void)
{
  union {int s; float f;} u = {0};
  foo(&u.s, &u.f, 2);
  printf("%.f\n", u.f);
  return 0;
}
```

In Compiler Explorer, it is observed that the program compiled with `clang -O0` outputs `2`, whereas the same program compiled with `clang -O1` outputs `0`. Given that the third argument `n` of the function `foo` is 2, the expected execution trace within `foo`'s loop would be `*f = 2`, followed by `*s = 4`, and then `*f = 2` again. This sequence should  leave `u.f` with the value `2` instead of `0`.

**Comment by shafik** [comment]
This is undefined behavior, you are violating the strict aliasing rules, we can see this more easily by using `-fno-strict-aliasing` which "fixes" the issue: https://gcc.godbolt.org/z/K5zjM5ocf

If you type punned via the union, that is allowed in C but you passed a `float*` and an `int*` which are not allowed to alias. Also note that if you remove the store to `*s` this also causes the issue to go away: https://gcc.godbolt.org/z/xYxbTnMPq

**Comment by wierton** [comment]
> This is undefined behavior, you are violating the strict aliasing rules, we can see this more easily by using `-fno-strict-aliasing` which "fixes" the issue: https://gcc.godbolt.org/z/K5zjM5ocf
> 
> If you type punned via the union, that is allowed in C but you passed a `float*` and an `int*` which are not allowed to alias. Also note that if you remove the store to `*s` this also causes the issue to go away: https://gcc.godbolt.org/z/xYxbTnMPq

@shafik , Thanks for pointing out the strict aliasing issue. I get that there's undefined behavior happening, and the compiler can handle it in its own way. I'm also interested in finding out about other kinds of undefined behaviors that diagnostics and UBSan might not pick up on. Thanks in advance for any further explanation you can provide.

**Comment by shafik** [comment]
> > This is undefined behavior, you are violating the strict aliasing rules, we can see this more easily by using `-fno-strict-aliasing` which "fixes" the issue: https://gcc.godbolt.org/z/K5zjM5ocf
> > If you type punned via the union, that is allowed in C but you passed a `float*` and an `int*` which are not allowed to alias. Also note that if you remove the store to `*s` this also causes the issue to go away: https://gcc.godbolt.org/z/xYxbTnMPq
> 
> @shafik , Thanks for pointing out the strict aliasing issue. I get that there's undefined behavior happening, and the compiler can handle it in its own way. I'm also interested in finding out about other kinds of undefined behaviors that diagnostics and UBSan might not pick up on. Thanks in advance for any further explanation you can provide.

UBSan is not expect to catch strict aliasing violation. There is a type sanitizer that is being worked on, I don't know what the status is at this point but you can find an update here: https://discourse.llvm.org/t/reviving-typesanitizer-a-sanitizer-to-catch-type-based-aliasing-violations/66092

**Comment by wierton** [comment]
> UBSan is not expect to catch strict aliasing violation. There is a type sanitizer that is being worked on, I don't know what the status is at this point but you can find an update here: https://discourse.llvm.org/t/reviving-typesanitizer-a-sanitizer-to-catch-type-based-aliasing-violations/66092

@shafik Thanks a lot! I'll check out this 'typesan'.
