### ISSUE TITLE
lldb add support for escaping special characters in identifiers

### ISSUE THREAD

**Issue by Victorious3** [llvm/llvm-project#86809]
I'm using lldb on apple silicon to debug my custom programming language.
My language makes heavy use of special characters such as colons in identifiers. In gdb you could use single quotes like `'parser::Node'` to refer to those identifiers and it would be great if lldb supported a syntax like that too.

**Comment by jimingham** [comment]
In what context do you need to do this?  lldb supports debugging swift which allows all sorts of extended glyphs as identifier names.  When debugging swift programs, I can set breakpoints on these symbols, and call functions with those names, print variables, etc.

I'm pretty sure all this support is in the mainline llvm.org lldb and not the swift fork.  If there's support that is still in the swift fork, we should try to merge it back to the non-swift sources as it really shouldn't be swift specific.

**Comment by Victorious3** [comment]
My programming language pretends to be C maybe that's the problem. I can't just come up with a new language for dwarf though.

**Comment by jimingham** [comment]
We don't add non-language syntax to any of the expressions run by the expression evaluator, we always use the front-end parser for that language.  We relax the protection mechanisms the language has (you can see private ivars when not in methods of the class, etc.) and augment the lookup rules so you can for instance cast values to types that aren't visible where the expression is being run.  But this is meant to be a "language accurate" expression evaluator.  It would be directly contrary to its design to add special syntax like the gdb one to the expression parser.  

We can do more in the DIL - the little c-like language supported by `frame variable` for printing elements of structured values - though I would be surprised if that didn't already work.

You certainly can add an enum for your language to DWARF.  For your development purposes, just choose something in the languages enum that's not occupied.  If you get to the point where you are going to release this language out into the world, then you ask the DWARF committee for an official name.  They usually grant those pretty easily.

But if you want to evaluate expressions you're still going to need to incorporate your front end into lldb as was done with the C family and Swift.  Some languages, like Rust, are C-like enough that they just pretend they are C and then use a bunch of data formatters to present values that aren't C-like.  But the expression parser is not high fidelity in that use.

**Comment by Victorious3** [comment]
Thanks for the clarification. With those goals in mind it makes no sense to augment the expression language. I'll look into providing my own frontend in the future but for now it's probably easier to change my output to confirm to C's identifier constraints.
