### ISSUE TITLE
Fix some GCC diagnostic QoI gripes

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#8681]
|  |  |
| --- | --- |
| Bugzilla Link | [8309](https://llvm.org/bz8309) |
| Version | unspecified |
| OS | All |
| CC | @DougGregor |

## Extended Description 
There are some interesting examples of terrible diagnostics here:
http://web.archive.org/web/20080504011352/http://www.digitalfanatics.org/index.php?title=CompilerErrors

Amusingly, I found this through the GCC "better diagnostics" page:
http://gcc.gnu.org/wiki/Better_Diagnostics

**Comment by philnik777** [comment]
I've looked through a few of the examples and the error messages clang produced seemed quite reasonable, so I'm closing this.
