### ISSUE TITLE
<algorithm>: `contains_subrange` should not use `std::distance`

### ISSUE THREAD

**Issue by hewillk** [llvm/llvm-project#86833]
https://github.com/llvm/llvm-project/blob/c335accb07c0cfa4bd7f47edc94c9005692edfcc/libcxx/include/__algorithm/ranges_contains_subrange.h#L72-L80

...because it is based on the C++17 iterator model rather than the C++20 Ranges iterator model.
In addition, `__n2` is an integer type and may not accommodate `difference_type`.
I believe the above can be just simplified to: 

```cpp
if (ranges::distance(__range2) == 0)
  return true;
```

testcase:

```cpp
#include <ranges>
#include <algorithm>

static_assert(
  std::ranges::contains_subrange(
    std::views::iota(0, 5),
    std::views::iota(0, 5) | std::views::filter([](int i) { return true; }) )
);
```
https://godbolt.org/z/G6oMoM5Wz

**Comment by hewillk** [comment]
If we only want to know whether `__range2` is empty, we only need to check `first == last` or use `ranges::empty`, which is what MSVC-STL does.
 If `__range2` is very large, the `ranges::distance` will only be an unnecessary bottleneck.

**Comment by frederick-vs-ja** [comment]
Currently `__n2` is of type `int` here, which can lead to wrong results with `uint64_t` ([Godbolt link](https://godbolt.org/z/jMfM5YY6W)). This was pointed out during review (https://github.com/llvm/llvm-project/pull/66963#discussion_r1341362102) but not fully resolved.

@ZijunZhaoCCK Did you think there is some case in which `ranges::empty` doesn't work?

**Comment by hewillk** [comment]
> Edit: oops, perhaps we shouldn't call ranges::empty as a member empty function can return an undesired value (which doesn't seem UB or IFNDR)?

That's why I wrote [P3156](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2024/p3156r0.html) even though it was closed. But I have submitted a LWG for this.

**Comment by ZijunZhaoCCK** [comment]
> @ZijunZhaoCCK Did you think there is some case in which `ranges::empty` doesn't work?
I didn't think that `ranges::empty` doesn't work before 😢 . Maybe it can be replaced by `empty_checkable_range`.

**Comment by hewillk** [comment]
> But I have submitted a LWG for this.

https://cplusplus.github.io/LWG/issue4062
