### ISSUE TITLE
[OpenMP RT] taskdep_if0.c assert hit

### ISSUE THREAD

**Issue by mikaoP** [llvm/llvm-project#86952]
`KMP_DEBUG_ASSERT(n >= 0);` is hit on taskdep_if0.c https://github.com/llvm/llvm-project/blob/main/openmp/runtime/src/kmp_taskdeps.h#L26

It's a bit difficult to hit it so I did:
```
$ while (cd /path/to/build/runtimes/runtimes-bins/openmp && /usr/bin/python3.10 /path/to/build/./bin/llvm-lit -v --xunit-xml-output=xunit.xml /path/to/build/runtimes/runtimes-bins/openmp/runtime/test/tasking/taskdep_if0.c); do date; done
```

**Comment by shiltian** [comment]
This might share similar root cause as https://github.com/llvm/llvm-project/issues/85963.

**Comment by mikaoP** [comment]
> This might share similar root cause as #85963.

That was fast :) . I've been testing this with latest upstream, which includes the fix, and it appears to work now :+1: 
I close the issue
