### ISSUE TITLE
[DAG] Remove extract_vector_elt(freeze(x)), idx -> freeze(extract_vector_elt(x), idx) fold

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#86968]
This fold is the reverse of what the rest of the DAG is trying to achieve - moving the freeze nodes UP towards the root nodes.

CC @topperc @arsenm @efriedma-quic

**Comment by arsenm** [comment]
This was added in f5700e7b69048de958172fb513b336564e7f8709
