### ISSUE TITLE
Issues with building due to blake3 directory

### ISSUE THREAD

**Issue by bob80905** [llvm/llvm-project#87007]
Hello,
I'd like to set up my machine to build llvm, using cmake and ninja. However, there are problems when doing so.
I create a build directory "build" underneath the root directory, which in my case is D:\llvm-project.
Then, I run
`cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -C ../clang/cmake/caches/HLSL.cmake ../llvm`
But near the bottom I get this error:
```

CMake Error in lib/Support/BLAKE3/CMakeLists.txt:
  MSVC_DEBUG_INFORMATION_FORMAT value 'ProgramDatabase' not known for this
  ASM_MASM compiler.


-- Generating done
CMake Error:
  Running

   'C:/PROGRA~1/MICROS~1/2022/ENTERP~1/Common7/IDE/COMMON~1/MICROS~1/CMake/Ninja/ninja.exe' '-C' 'D:/llvm-project/build' '-t' 'recompact'

  failed with:

   ninja: error: build.ninja:35: loading 'CMakeFiles\rules.ninja': The system cannot find the file specified.



  include CMakeFiles\rules.ninja

                                ^ near here



CMake Generate step failed.  Build files cannot be regenerated correctly.
```

I am running the developer command prompt from visual studio with:
`cmd.exe /k "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"`

What could be wrong? 
CMake version: 3.25.1

**Comment by bob80905** [comment]
> What cmake version do you have? I tried reproducing this, with cmake 3.28.3, and the cmake configuration runs successfully.

I have cmake version 3.25.1

**Comment by bob80905** [comment]
> What cmake version do you have? I tried reproducing this, with cmake 3.28.3, and the cmake configuration runs successfully.

Building succeeds when updating cmake to 3.29.1. Thanks!

**Comment by V-FEXrt** [comment]
I just spent the last couple days fighting this issue. Wanted to post my fix in case someone else (honestly me probably) bumps into this in the future.

For me, the fix was to use the Developer PowerShell console instead of the Windows PowerShell console
