### ISSUE TITLE
The nullPointerConstant matcher is problematic

### ISSUE THREAD

**Issue by GKxxQAQ** [llvm/llvm-project#87008]
Current definition of `clang::ast_matchers::nullPointerConstant` (in `clang/include/clang/ASTMatchers.h`) is

```cpp
AST_MATCHER_FUNCTION(internal::Matcher<Expr>, nullPointerConstant) {
  return anyOf(
      gnuNullExpr(), cxxNullPtrLiteralExpr(),
      integerLiteral(equals(0), hasParent(expr(hasType(pointerType())))));
}
```

The third argument to `anyOf` here is problematic, I think. Counterexample:

```cpp
int main() {
  int *p[1];
  p[0];
}
```

The integer literal `0` in `p[0]` is matched by `expr(nullPointerConstant())`.

**Comment by Sirraide** [comment]
> In this example, the integer literal `0` in `p[0]` is matched by `expr(nullPointerConstant())`, because its parent expression `p[0]` does have a pointer type.

Yeah, this seems pretty wrong to me at least; I’m more familiar w/ C++ than C, but it would seem *very* strange to me candidly if the C standard really considered that `0` in `p[0]` to be a null pointer constant. I’m also not too familiar w/ AST matchers, but we should probably be able to check for an enclosing (possibly implicit) cast expression instead?

**Comment by Sirraide** [comment]
Godbolt link: <https://godbolt.org/z/jaz4jYohe>

**Comment by KHicketts** [comment]
Hello! Can I pick this up please?  I'm slightly suspicious as to why it's been open ages and no one picked it up (I just spent about 1 hour looking for an actually available issue)

**Comment by shafik** [comment]
> Hello! Can I pick this up please? I'm slightly suspicious as to why it's been open ages and no one picked it up (I just spent about 1 hour looking for an actually available issue)

Looks like the issue still reproduces based on the godbolt link above. We don't assign issues until there is a PR and we check it is going in the right direction but saying you are going to work on it helps avoid duplicate work.

**Comment by KHicketts** [comment]
took me about 3 hours to figure out what was the one line I needed to update 0_o.  I have a draft PR.  I'll check it again on Monday when my brain has more energy.

**Comment by KHicketts** [comment]
I marked this as ready here: https://github.com/llvm/llvm-project/pull/201893
