### ISSUE TITLE
[mlir][arith][spirv] Convert `arith.truncf` with rounding mode to SPIR-V

### ISSUE THREAD

**Issue by victor-eds** [llvm/llvm-project#87050]
#86152 added an optional rounding mode attribute to `arith.truncf`. Due to missing infrastructure in SPIR-V, conversion to the SPIR-V dialect was not implemented as part of that PR.

SPIR-V accepts specifying an operation rounding mode using the `FPRoundingMode` decoration, receiving an [FP rounding mode](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#FP_Rounding_Mode) value. The decoration key is present in the dialect already, but we're missing a representation for the FP rounding mode values. Once we have that, we could convert:

```mlir
func.func @experimental_constrained_fptrunc(%arg0 : f64) {
  %0 = arith.truncf %arg0 tonearesteven : f64 to f32
  %1 = arith.truncf %arg0 downward : f64 to f32
  %2 = arith.truncf %arg0 upward : f64 to f32
  %3 = arith.truncf %arg0 towardzero : f64 to f32
  return
}
```

into:

```mlir
func.func @experimental_constrained_fptrunc(%arg0 : f64) {
  %0 = spirv.FConvertOp %arg0 {FPRoundingMode = #spirv.FPRoundingMode<RTE>} : f64 to f32
  %1 = spirv.FConvertOp %arg0 {FPRoundingMode = #spirv.FPRoundingMode<RTN>} : f64 to f32
  %2 = spirv.FConvertOp %arg0 {FPRoundingMode = #spirv.FPRoundingMode<RTP>} : f64 to f32
  %3 = spirv.FConvertOp %arg0 {FPRoundingMode = #spirv.FPRoundingMode<RTZ>} : f64 to f32
  return
}
```

Note there is no representation of `tonearestaway` in SPIR-V, so conversion should fail in that case.

**Comment by andfau-amd** [comment]
I did this and it's now merged. Beware that if you're targeting Vulkan, there is a rather strict validation rule in the SPIR-V spec:

> The FPRoundingMode [decoration](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Decoration) must be applied only to a width-only conversion instruction whose only uses are Object operands of [OpStore](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpStore) instructions storing through a pointer to a 16-bit floating-point object in the StorageBuffer, PhysicalStorageBuffer, Uniform, or Output [Storage Classes](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Storage_Class).

**Comment by victor-eds** [comment]
> I did this and it's now merged. Beware that if you're targeting Vulkan, there is a rather strict validation rule in the SPIR-V spec:

Thanks! Yes, users should be wary of this.
