### ISSUE TITLE
[GH] Comment on an issue: All jobs have failed

### ISSUE THREAD

**Issue by Sirraide** [llvm/llvm-project#87102]
I got an email by github about this and was told to open an issue about it. Apparently there’s an issue w/ some workflow:

https://github.com/llvm/llvm-project/actions/runs/8483329928

**Comment by tstellar** [comment]
Do you know which pull request triggered this job?

**Comment by Sirraide** [comment]
> Do you know which pull request triggered this job?

That’s the thing: it doesn’t seem to tell you (or me at least) anything about what commit or pr caused this; the only commit it links to is [this one](https://github.com/llvm/llvm-project/commit/0dbd804a690720688d8234d8bdaee8f8f4fdcddc), and I had nothing to do w/ that one from what I can tell.

The last pr I opened that I also merged today was [this one](https://github.com/llvm/llvm-project/pull/84169), other than that, nothing comes to mind really (unless it’s pinging me about something I reviewed?). As I said, I’m not sure how to even begin interpreting that error...

**Comment by Sirraide** [comment]
Actually, wait, looking a the logs a bit closer, this is the title of the pr I merged:
![image](https://github.com/llvm/llvm-project/assets/74590115/432c60b1-2334-4666-9811-ceeee9f8aedc)

**Comment by Sirraide** [comment]
So this pr had been open for about 3 weeks and was approved today; I had to merge the release notes, so I did that; what’s weird is that I then tried to merge it, but it showed me an error message that told me to reload the page (maybe that’s what caused the error here?). Then, it did that and proceeded to merge it w/o any further issues. That’s all I know, though.

**Comment by tstellar** [comment]
@Sirraide Did you delete the branch right after merging the PR ?

**Comment by Sirraide** [comment]
I did, yeah, but I’ve done that many times before here.

**Comment by tstellar** [comment]
@Sirraide OK, thanks.  I think I know what happened, I will try to make a fix.
