### ISSUE TITLE
Move __builtin_hlsl_wave_get_lane_index to EmitHLSLBuiltinExpr

### ISSUE THREAD

**Issue by farzonl** [llvm/llvm-project#87109]
`Value *CodeGenFunction::EmitHLSLBuiltinExpr(unsigned BuiltinID, const CallExpr *E)`

is where all the other hlsl builtins live.

_Originally posted by @farzonl in https://github.com/llvm/llvm-project/pull/80680#discussion_r1544449419_

**Comment by marcauberer** [comment]
I can do that
