### ISSUE TITLE
Clang incorrectly disallows SVE builtins & types when SVE is disabled but SME is enabled

### ISSUE THREAD

**Issue by aemerson** [llvm/llvm-project#87129]
Issue is what it says on the tin. One example is `svdup_u8`

There are two parts to this as far as I can see. In `Sema.cpp` there's some diagnostics that check if "sve" is enabled for the target before sizeless types are used. This one is easy to fix.

The worse one is the fact that `SInst` which is the parent of every SVE instruction defines `TargetGuard = "sve";` and we have to manually override it every time something diverges. I'm not sure which is the best way to fix this. We could have the default be "sve|sme" and the make sure that every override takes into consideration whether or not SME should be in the list of valid prerequisites. This seems like less work than having to change it for every instruction definition.

**Comment by sdesmalen-arm** [comment]
This was resolved by #95787
(See https://godbolt.org/z/eeb998vcM)
