### ISSUE TITLE
[libc][posix] implement `_exit`

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#87126]
Posix 2008 added _exit which is like exit but it does not call the atexit callbacks.  Looks like we do already support the posix 2008 / c11 `_Exit`, so the implementation is probably the same.

**Comment by aniplcc** [comment]
I'll take this one as well

**Comment by aniplcc** [comment]
Also if its just _Exit, can I just call the already implemented _Exit in the implementation for this?

**Comment by nickdesaulniers** [comment]
> Also if its just _Exit, can I just call the already implemented _Exit in the implementation for this?

No; because LLVM-libc may be overlayed onto a system libc, what if the user overlays `_exit` onto a system whose `_Exit` calls `_exit`? Then we'd have infinite co-recursion. This is why sin/cos aren't implemented in terms of each other.

**Comment by aniplcc** [comment]
```
CMake Error at /home/ompworker/bbot/openmp-offload-libc-amdgpu-runtime/llvm.src/libc/cmake/modules/LLVMLibCLibraryRules.cmake:56 (get_target_property):
  get_target_property() called with non-existent target
  "libc.src.unistd._exit".
Call Stack (most recent call first):
  /home/ompworker/bbot/openmp-offload-libc-amdgpu-runtime/llvm.src/libc/cmake/modules/LLVMLibCLibraryRules.cmake:237 (get_all_object_file_deps)
  /home/ompworker/bbot/openmp-offload-libc-amdgpu-runtime/llvm.src/libc/lib/CMakeLists.txt:22 (add_entrypoint_library)
``` several more lines...
 openmp-offload-libc-amdgpu-runtime buildbot is failing.
 
 I think I configured the config/gpu/ entrypoints correctly, so not sure why this is happening
 cc @nickdesaulniers

**Comment by nickdesaulniers** [comment]
looking now cc @jhuber6

**Comment by jhuber6** [comment]
I'll look at it, at least the bot is actually working.

**Comment by jhuber6** [comment]
I just removed it from the GPU build. I believe that there were other dependencies which we can't fulfil (At least not yet) that prevented us from building the `unistd` support so it wasn't creating the headers and other stuff.

**Comment by aniplcc** [comment]
gotcha, thanks!
