### ISSUE TITLE
[BOLT] [MC] [AArch64] MCInst printing issue

### ISSUE THREAD

**Issue by YuanSha0** [llvm/llvm-project#87188]
Hi!
In BOLT, while working on some optimizations, I am attempting to directly modify instructions using the MCInst class to alter the stack access offset. However, when I print out the Operand information, I find that the results do not match my expectations.
  

![image](https://github.com/llvm/llvm-project/assets/81171521/ff0386ac-1cc0-469e-b0dc-311e1ef3600f)

printing result:

![image](https://github.com/llvm/llvm-project/assets/81171521/2cd6e160-1a2c-4c82-b1b0-6a7329c5d7ab)

What I can't understand is that its Imm value is 4, and the Imm values are the same among them.

**Comment by YuanSha0** [comment]
By the way, this 4 seems to act as a sort of coefficient. When I added 16 to this 4, the resulting value was indeed 20. However, unexpectedly, the stack access offset increased by a factor of 5 rather than reflecting the simple addition.

![image](https://github.com/llvm/llvm-project/assets/81171521/2ce5e6d9-3f36-418e-8dc9-480ac6cff1cd)

**Comment by yota9** [comment]
It is coefficient indeed. In the first ldr you load 32 bits in w9 and coefficient 4 Imm * 4 bytes = 16 bytes offset you see in instruction. In second instruction you load 64 bits in x10 and 4 Imm * 8 bytes = 32 bytes offset.

**Comment by YuanSha0** [comment]
@yota9 Thank you again. 
This means that if I need to perform fixed value addition or subtraction on the stack offset, I also need to consider the type of register.
