### ISSUE TITLE
Combiner dags/patterns.

### ISSUE THREAD

**Issue by tschuett** [llvm/llvm-project#87194]
I have issues with opcodes that a variable number of operands:
```
def G_BUILD_VECTOR : GenericInstruction {
  let OutOperandList = (outs type0:$dst);
  let InOperandList = (ins type1:$src0, variable_ops);
  let hasSideEffects = false;
  let variadicOpsType = type1;
}
```
For build vector the number of sources is variable.

I tried in the combiner:
```
def extract_vector_element_build_vector : GICombineRule<
   (defs root:$root, build_fn_matchinfo:$matchinfo),
   (match (G_BUILD_VECTOR $src, $x),
          (G_EXTRACT_VECTOR_ELT $root, $src, $idx),
   [{ return Helper.matchExtractVectorElementWithBuildVector(${root}, ${matchinfo}); }]),
   (apply [{ Helper.applyBuildFnMO(${root}, ${matchinfo}); }])>;
```
but it fails when there are two operands.

I could copy-paste up to 8 or 16 operands, but ....

**Comment by Pierre-vh** [comment]
How does it fail? I just tried it locally and it works.
Can you add the error message + repro instructions?

**Comment by tschuett** [comment]
In https://github.com/llvm/llvm-project/pull/85321/files I copy pasted build vector  and the trunk kind.

It is a bit vague, but IIRC I have to specify all registers in a pattern.

**Comment by tschuett** [comment]
Again vague, but the MIR patterns guide seems to hint at specifying all operands for an instruction.

**Comment by Pierre-vh** [comment]
Ah I see what you mean, this is a feature not a bug at this time. Patterns are explicit and don't support variable arguments yet
I created #87459 to track the actual feature so I don't forget about looking into this again :)
