### ISSUE TITLE
llvm/lib/Object/MachOObjectFile.cpp:5197: Condition can never be true ?

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#87203]
Static analyser cppcheck says:

llvm/lib/Object/MachOObjectFile.cpp:5197:18: warning: Identical condition 'ImportsEnd>Symbols', second condition is always false [identicalConditionAfterEarlyExit]

Source code is

  if (ImportsEnd > Symbols)
    return malformedError("bad chained fixups: imports end " +
                          Twine(ImportsEndOffset) + " extends past end " +
                          Twine(DyldChainedFixups.datasize));

  if (ImportsEnd > Symbols)
    return malformedError("bad chained fixups: imports end " +
                          Twine(ImportsEndOffset) + " overlaps with symbols");

This code might benefit from some tidyup.

**Comment by EugeneZelenko** [comment]
@dcb314: Do you have `triage` role? If not, please request it, so you could label issues yourself. Process is same as for `commit` role.

**Comment by dcb314** [comment]
> @dcb314: Do you have `triage` role?

No.

> If not, please request it, 

How ? I had a look around the GUI but didn't see anything suitable.

**Comment by EugeneZelenko** [comment]
@dcb314: See https://llvm.org/docs/DeveloperPolicy.html#obtaining-commit-access.

**Comment by dcb314** [comment]
> > If not, please request it,

Done.

**Comment by lattner** [comment]
@EugeneZelenko we don't have anything in the developer policy about getting "triage" roles, I'm not sure what is being asked here.  People shouldn't apply for commit access if they don't meet the qualifications.
