### ISSUE TITLE
[Compatibility] Option -w can't disable the warning -Wimplicit-function-declaration 

### ISSUE THREAD

**Issue by vfdff** [llvm/llvm-project#87221]
* test: https://gcc.godbolt.org/z/b6djWGGW9
```
int square(int num) {
    memset (&num, 0, 4);
    return 0;
}
```

* **report**: 
 > error: call to undeclared library function 'memset' with type 'void *(void *, int, unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

* since clang15, miss head file <string.h>for **memset** will report an **error**, so it can't be disable by add option `-w`, and many old code should modify the source to avoid this issue. Does we still have an option to compatible with old code ?

**Comment by thesamesam** [comment]
Please use `-std=c89` or `-std=gnu89`.

**Comment by vfdff** [comment]
Thanks @thesamesam
