### ISSUE TITLE
clang/lib/Frontend/InterfaceStubFunctionsConsumer.cpp:35: Pointless copy of vector ?

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#87255]
Static analyser cppcheck says:

clang/lib/Frontend/InterfaceStubFunctionsConsumer.cpp:35:44: performance: Function parameter 'Names' should be passed by const reference. [passedByValue]

Source code is

    MangledSymbol(const std::string &ParentName, uint8_t Type, uint8_t Binding,
                  std::vector<std::string> Names)

**Comment by shafik** [comment]
This is not totally correct here. We are copying into the local member `Names` in the `mem-initializer-list` and so we should probably be doing a move there. We need to take the copy and taking it when passing the parameter is probably fine and then moving out of the parameter when initializer the member is probably the way to go.
