### ISSUE TITLE
clang/lib/Format/Format.cpp:3581: vector copy problem ?

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#87254]
Static analyser cppcheck says:

clang/lib/Format/Format.cpp:3581:49: performance: Function parameter 'Ranges' should be passed by const reference. [passedByValue]

Source code is

                   std::vector<tooling::Range> Ranges,

This might be worth using a constant reference on.

**Comment by shafik** [comment]
This one is not as obvious, it looks like we are taking a copy when we don't need to.

CC @AaronBallman
