### ISSUE TITLE
clang/utils/TableGen/SveEmitter.cpp:102: possible wrong operator ? 

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#87271]
Static analyser cppcheck says:

clang/utils/TableGen/SveEmitter.cpp:102:37: style: Boolean result is used in bitwise operation. Clarify expression with parentheses. [clarifyCondition]

Source code is

  bool isVoid() const { return Void & !Pointer; }

Perhaps better code:

  bool isVoid() const { return Void && !Pointer; }

**Comment by shafik** [comment]
Based on: https://reviews.llvm.org/D75470

This indeed looks wrong. 

CC @sdesmalen-arm @sjoerdmeijer
