### ISSUE TITLE
Don't do unprofitable narrowing of loads.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#8728]
|  |  |
| --- | --- |
| Bugzilla Link | [8356](https://llvm.org/bz8356) |
| Version | trunk |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |
| CC | @sunfishcode |

## Extended Description 
Our backend only does 32 bit loads.  I noticed some loads were narrowed to 8 bits and then had to be reverted back to 32 bit loads.  This patch prevents the initial lowering.  I've only tested this on my backend. 

Index: CodeGen/SelectionDAG/TargetLowering.cpp
===================================================================
```diff
--- CodeGen/SelectionDAG/TargetLowering.cpp    (revision 115815)
+++ CodeGen/SelectionDAG/TargetLowering.cpp    (working copy)
@@ -1899,7 +1899,9 @@
               else
                 bestOffset = (uint64_t)offset * (width/8);
               bestMask = Mask.lshr(offset * (width/8) * 8);
-              bestWidth = width;
+              EVT NewVT = EVT::getIntegerVT(*DAG.getContext(), width);
+              if  (isNarrowingProfitable(Lod->getMemoryVT(), NewVT))
+                bestWidth = width;
               break;
             }
             newMask = newMask << width;
```

**Comment by philnik777** [comment]
Closing, since there doesn't seem to be consensus that this is an issue worth tackling and the discussion ended over a decade ago.
