### ISSUE TITLE
Resolve call to atoi with constant input at compile time.

### ISSUE THREAD

**Issue by Bigcheese** [llvm/llvm-project#8732]
|  |  |
| --- | --- |
| Bugzilla Link | [8360](https://llvm.org/bz8360) |
| Version | trunk |
| OS | All |
| CC | @d0k |

## Extended Description 
Ran into this while trying to get LLVM to not optimize away my contrived code. Seems like an easy SimplifyLibCalls opt to implement to get used to transforms. 

Filing this so I don't forget.

atoi("42") -> i32 42

**Comment by RKSimon** [comment]
https://godbolt.org/z/vWMaxsr4x

This was fixed for 7.x by https://reviews.llvm.org/D45418 / cb8ca5f37c29bef9b5b1f119d7ab10ae288956c9
