### ISSUE TITLE
[HLSL] Propose and discuss a holistic approach to math operations in HLSL

### ISSUE THREAD

**Issue by bogner** [llvm/llvm-project#87367]
From @farzonl's investigation of #83882 it's become clear that splitting up HLSL math operations between generic LLVM intrinsics and special cased HLSL intrinsics is pretty unfortunate. We would prefer to avoid having to implement a large chunk of generic math operations in our own playground, and instead handle them generically in LLVM.

To do this, we should propose implementing the set of math intrinsics we're interested in as generic LLVM intrinsics, and work with the community to get to a solution that makes sense across the board.

A couple of things to note:
1. A chunk of the community has been reticent to accept new math intrinsics in the past (see https://discourse.llvm.org/t/math-intrinsics/67192, https://github.com/llvm/llvm-project/pull/79948, etc), but there have been discussions debating the split between libcalls and intrinsics for math for a very long time (https://discourse.llvm.org/t/rfc-canonicalize-libcalls-to-intrinsics/39697)
2. The proposal should discuss the full set of math operations we're interested in so that people understand the full picture when discussing this.

AC: This work item tracks sending the initial RFC and driving the conversation to an actionable conclusion.

**Comment by bogner** [comment]
I took a look through the [HLSL Intrinsics], [HLSL 6.0 Intrinsics], [HLSL 6.4 Intrinsics], and [DXIL Ops] and filtered down to the simple math operations manually. From there we see a few things.

[HLSL Intrinsics]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-intrinsic-functions
[HLSL 6.0 Intrinsics]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/shader-model-6-0
[HLSL 6.4 Intrinsics]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/hlsl-shader-model-6-4-features-for-direct3d-12#single-precision-floating-point-2-element-dot-product-and-accumulate
[DXIL Ops]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#operations-via-external-functions

There are 26 operations that map trivially to existing LLVM intrinsics. Note that three of these don't have direct HLSL intrinsics - IsNormal seems to be unused, and UAddc/USubb are only used by expansions of 64 bit math in dxc. Nothing needs to be done for these.

| HLSL Intrinsic     | DXIL Op                   | LLVM Intrinsic            |
|--------------------|---------------------------|---------------------------|
| [abs] (float)      | [FAbs][dx.FAbs]           | [llvm.fabs]               |
| [ceil]             | [Round_pi][dx.Round_pi]   | [llvm.ceil]               |
| [cos]              | [Cos][dx.Cos]             | [llvm.cos]                |
| [countbits]        | [Countbits][dx.Countbits] | [llvm.ctpop]              |
| [exp2]             | [Exp][dx.Exp]             | [llvm.exp2]               |
| [floor]            | [Round_ni][dx.Round_ni]   | [llvm.floor]              |
| [fma]              | [Fma][dx.Fma]             | [llvm.fma]                |
| [frac]             | [Frc][dx.Frc]             | [llvm.frexp]              |
| [isfinite]         | [IsFinite][dx.IsFinite]   | [llvm.is.fpclass]         |
| [isinf]            | [IsInf][dx.IsInf]         | [llvm.is.fpclass]         |
| [isnan]            | [IsNaN][dx.IsNaN]         | [llvm.is.fpclass]         |
|                    | [IsNormal][dx.IsNormal]   | [llvm.is.fpclass]         |
| [log2]             | [Log][dx.Log]             | [llvm.log2]               |
| [max] (float)      | [FMax][dx.FMax]           | [llvm.maxnum]             |
| [max] (int)        | [IMax][dx.IMax]           | [llvm.smax]               |
| [max] (uint)       | [UMax][dx.UMax]           | [llvm.umax]               |
| [min] (float)      | [FMin][dx.FMin]           | [llvm.minnum]             |
| [min] (int)        | [IMin][dx.IMin]           | [llvm.smin]               |
| [min] (uint)       | [UMin][dx.UMin]           | [llvm.umin]               |
| [reversebits]      | [Bfrev][dx.Bfrev]         | [llvm.bitreverse]         |
| [round]            | [Round_ne][dx.Round_ne]   | [llvm.roundeven]          |
| [sin]              | [Sin][dx.Sin]             | [llvm.sin]                |
| [sqrt]             | [Sqrt][dx.Sqrt]           | [llvm.sqrt]               |
| [trunc]            | [Round_z][dx.Round_z]     | [llvm.trunc]              |
|                    | [UAddc][dx.UAddc]         | [llvm.uadd.with.overflow] |
|                    | [USubb][dx.USubb]         | [llvm.usub.with.overflow] |

[abs]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-abs
[dx.FAbs]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#fabs
[llvm.fabs]: https://llvm.org/docs/LangRef.html#llvm-fabs-intrinsic
[ceil]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-ceil
[dx.Round_pi]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#round_pi
[llvm.ceil]: https://llvm.org/docs/LangRef.html#llvm-ceil-intrinsic
[cos]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-cos
[dx.Cos]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#cos
[llvm.cos]: https://llvm.org/docs/LangRef.html#llvm-cos-intrinsic
[countbits]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/countbits
[dx.Countbits]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#countbits
[llvm.ctpop]: https://llvm.org/docs/LangRef.html#llvm-ctpop-intrinsic
[exp2]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-exp2
[dx.Exp]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#exp
[llvm.exp2]: https://llvm.org/docs/LangRef.html#llvm-exp2-intrinsic
[floor]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-floor
[dx.Round_ni]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#round_ni
[llvm.floor]: https://llvm.org/docs/LangRef.html#llvm-floor-intrinsic
[fma]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-fma
[dx.Fma]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#fma
[llvm.fma]: https://llvm.org/docs/LangRef.html#llvm-fma-intrinsic
[frac]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-frac
[dx.Frc]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#frc
[llvm.frexp]: https://llvm.org/docs/LangRef.html#llvm-frexp-intrinsic
[isfinite]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-isfinite
[dx.IsFinite]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#isfinite
[llvm.is.fpclass]: https://llvm.org/docs/LangRef.html#llvm-is-fpclass-intrinsic
[isinf]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-isinf
[dx.IsInf]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#isinf
[isnan]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-isnan
[dx.IsNaN]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#isnan
[log2]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-log2
[dx.Log]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#log
[llvm.log2]: https://llvm.org/docs/LangRef.html#llvm-log2-intrinsic
[max]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-max
[dx.FMax]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#fmax
[llvm.maxnum]: https://llvm.org/docs/LangRef.html#llvm-maxnum-intrinsic
[dx.IMax]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#imax
[llvm.smax]: https://llvm.org/docs/LangRef.html#llvm-smax-intrinsic
[dx.UMax]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#umax
[llvm.umax]: https://llvm.org/docs/LangRef.html#llvm-umax-intrinsic
[min]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-min
[dx.FMin]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#fmin
[llvm.minnum]: https://llvm.org/docs/LangRef.html#llvm-minnum-intrinsic
[dx.IMin]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#imin
[llvm.smin]: https://llvm.org/docs/LangRef.html#llvm-smin-intrinsic
[dx.UMin]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#umin
[llvm.umin]: https://llvm.org/docs/LangRef.html#llvm-umin-intrinsic
[reversebits]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/reversebits
[dx.Bfrev]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#bfrev
[llvm.bitreverse]: https://llvm.org/docs/LangRef.html#llvm-bitreverse-intrinsics
[round]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-round
[dx.Round_ne]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#round_ne
[llvm.roundeven]: https://llvm.org/docs/LangRef.html#llvm-roundeven-intrinsic
[sin]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-sin
[dx.Sin]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#sin
[llvm.sin]: https://llvm.org/docs/LangRef.html#llvm-sin-intrinsic
[sqrt]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-sqrt
[dx.Sqrt]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#sqrt
[llvm.sqrt]: https://llvm.org/docs/LangRef.html#llvm-sqrt-intrinsic
[trunc]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-trunc
[dx.Round_z]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#round_z
[llvm.trunc]: https://llvm.org/docs/LangRef.html#llvm-trunc-intrinsic
[dx.IsNormal]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#isnormal
[dx.UAddc]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#uaddc
[llvm.uadd.with.overflow]: https://llvm.org/docs/LangRef.html#llvm-uadd-with-overflow-intrinsics
[dx.USubb]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#usubb
[llvm.usub.with.overflow]: https://llvm.org/docs/LangRef.html#llvm-usub-with-overflow-intrinsics

There are 17 HLSL operations that map directly to C/C++ standard math functions, though only 7 of these have DXIL operations. We should definitely push for adding the 7 DXIL ops as llvm intrinsics, and we should probably just get all of these in.

| HLSL Intrinsic | DXIL Op         | C stdlib               |
|----------------|-----------------|------------------------|
| [acos]         | [Acos][dx.Acos] | [acos][c.acos]         |
| [asin]         | [Asin][dx.Asin] | [asin][c.asin]         |
| [atan]         | [Atan][dx.Atan] | [atan][c.atan]         |
| [cosh]         | [Hcos][dx.Hcos] | [cosh][c.cosh]         |
| [sinh]         | [Hsin][dx.Hsin] | [sinh][c.sinh]         |
| [tanh]         | [Htan][dx.Htan] | [tanh][c.tanh]         |
| [tan]          | [Tan][dx.Tan]   | [tan][c.tan]          |
| [atan2]        |                 | [atan2][c.atan2]       |
| [exp]          |                 | [exp][c.exp]           |
| [fmod]         |                 | [fmod][c.fmod]         |
| [frexp]        |                 | [frexp][c.frexp]       |
| [ldexp]        |                 | [ldexp][c.ldexp]       |
| [log]          |                 | [log][c.log]           |
| [log10]        |                 | [log10][c.log10]       |
| [modf]         |                 | [modf][c.modf]         |
| [pow]          |                 | [pow][c.pow]           |
| [sign]         |                 | [copysign][c.copysign] |

[acos]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-acos
[dx.Acos]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#acos
[c.acos]: https://en.cppreference.com/w/cpp/numeric/math/acos
[asin]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-asin
[dx.Asin]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#asin
[c.asin]: https://en.cppreference.com/w/cpp/numeric/math/asin
[atan]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-atan
[dx.Atan]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#atan
[c.atan]: https://en.cppreference.com/w/cpp/numeric/math/atan
[cosh]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-cosh
[dx.Hcos]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#hcos
[c.cosh]: https://en.cppreference.com/w/cpp/numeric/math/cosh
[sinh]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-sinh
[dx.Hsin]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#hsin
[c.sinh]: https://en.cppreference.com/w/cpp/numeric/math/sinh
[tanh]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-tanh
[dx.Htan]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#htan
[c.tanh]: https://en.cppreference.com/w/cpp/numeric/math/tanh
[tan]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-tan
[dx.Tan]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#tan
[c.tan]: https://en.cppreference.com/w/cpp/numeric/math/tan
[atan2]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-atan2
[c.atan2]: https://en.cppreference.com/w/cpp/numeric/math/atan2
[exp]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-exp
[c.exp]: https://en.cppreference.com/w/cpp/numeric/math/exp
[fmod]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-fmod
[c.fmod]: https://en.cppreference.com/w/cpp/numeric/math/fmod
[frexp]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-frexp
[c.frexp]: https://en.cppreference.com/w/cpp/numeric/math/frexp
[ldexp]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-ldexp
[c.ldexp]: https://en.cppreference.com/w/cpp/numeric/math/ldexp
[log]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-log
[c.log]: https://en.cppreference.com/w/cpp/numeric/math/log
[log10]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-log10
[c.log10]: https://en.cppreference.com/w/cpp/numeric/math/log10
[modf]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-modf
[c.modf]: https://en.cppreference.com/w/cpp/numeric/math/modf
[pow]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-pow
[c.pow]: https://en.cppreference.com/w/cpp/numeric/math/pow
[sign]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-sign
[c.copysign]: https://en.cppreference.com/w/cpp/numeric/math/sign

We also have 4 common math operations that don't map to the C standard library, but can be awkward to pattern match on if we lower early. We should consider asking for these as well.

| HLSL Intrinsic | DXIL Op           |
|----------------|-------------------|
| [dot]          | [Dot2][dx.Dot2]   |
| [dot]          | [Dot3][dx.Dot3]   |
| [dot]          | [Dot4][dx.Dot4]   |
| [rsqrt]        | [Rsqrt][dx.Rsqrt] |
| [clamp]        |                   |
| [rcp]          |                   |

[dot]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-dot
[dx.Dot2]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#dot2
[dx.Dot3]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#dot3
[dx.Dot4]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#dot4
[clamp]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-clamp
[rcp]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/rcp
[rsqrt]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-rsqrt
[dx.Rsqrt]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#rsqrt

Then there are mad and sincos. I personally don't think these are worth having intrinsics for, as separating them into two operations feels like it won't really lose anything. Note that these are MAD not FMA, so they aren't fused at all.

| HLSL Intrinsic | DXIL Op         |
|----------------|-----------------|
| [mad] (float)  | [FMad][dx.FMad] |
| [mad] (int)    | [IMad][dx.IMad] |
| [mad] (uint)   | [UMad][dx.UMad] |
| [sincos]       |                 |

[mad]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/mad
[dx.FMad]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#fmad
[dx.IMad]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#imad
[dx.UMad]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#umad
[sincos]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-sincos

We also have a few bitfield instructions. We should probably pursue getting generic intrinsics for these, as *a lot* of architectures have this kind of instruction. However, I think it falls outside of the "this is just normal math" umbrella and we should do that separately.

| DXIL Op         |
|-----------------|
| [Bfi][dx.Bfi]   |
| [Ibfe][dx.Ibfe] |
| [Ubfe][dx.Ubfe] |

[dx.Bfi]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#bfi
[dx.Ibfe]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#ibfe
[dx.Ubfe]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#ubfe

Next we have operations that seem like they should map simply to intrinsics, but they're defined to return 0xffffffff instead of poison in edge cases. I don't really know what to do with these, but we clearly can't define them as generic intrinsics.

| HLSL Intrinsic     | DXIL Op                 |
|--------------------|-------------------------|
| [firstbithigh]     | [FirstbitSHi]           |
| [firstbithigh]     | [FirstbitHi]            |
| [firstbitlow]      | [FirstbitLo]            |
|                    | [UDiv][dx.UDiv]         |

[firstbithigh]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/firstbithigh
[FirstbitSHi]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#firstbitshi
[FirstbitHi]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#firstbithi
[firstbitlow]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/firstbitlow
[FirstbitLo]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#firstbitlo
[dx.UDiv]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#udiv

After that we're left with some highly specific operations. I can't see implementing any of these generically, though saturate could pretty trivially be implemented in terms of clamp if we add that one.

| HLSL Intrinsic     | DXIL Op                 |
|--------------------|-------------------------|
| [dot2add]          | Dot2AddHalf             |
| [dot4add_i8packed] | Dot4AddI8Packed         |
| [dot4add_u8packed] | Dot4AddU8Packed         |
| [msad4]            | [MSad][dx.MSad]         |
| [saturate]         | [Saturate][dx.Saturate] |
|                    | [UMul][dx.UMul]         |

[dot2add]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/hlsl-shader-model-6-4-features-for-direct3d-12#unsigned-integer-dot-product-of-4-elements-and-accumulate
[dot4add_i8packed]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/hlsl-shader-model-6-4-features-for-direct3d-12#signed-integer-dot-product-of-4-elements-and-accumulate
[dot4add_u8packed]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/hlsl-shader-model-6-4-features-for-direct3d-12#unsigned-integer-dot-product-of-4-elements-and-accumulate
[msad4]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-msad4
[dx.MSad]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#msad
[saturate]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-saturate
[dx.Saturate]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#saturate
[dx.UMul]: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#umul

Finally, there are some utility functions that dxc lowers early. I suspect we should simply do the same and there isn't any value kicking them around as intrinsics.

| HLSL Intrinsic |
|----------------|
| [all]          |
| [any]          |
| [degrees]      |
| [radians]      |
| [step]         |

[all]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-all
[any]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-any
[degrees]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-degrees
[radians]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-radians
[step]: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-step

Conclusions
-----------

1. We should propose adding 17 math intrinsics that map to C standard math functions: `acos`, `asin`, `atan`, `cosh`, `sinh`, `tanh`, `tan`, `atan2`, `exp`, `fmod`, `frexp`, `ldexp`, `log`, `log10`, `modf`, `pow`, and `copysign`.
2. We should propose adding intrinsics for `dot`, `rsqrt`, `clamp`, and `rcp`.
3. We should propose adding bitfield extract and insert intrisics.

**Comment by farzonl** [comment]
First Thanks @bogner  for putting this list together. I thinks its a good starting point for discussion. There are a few corrections We need to make in the backend That this list has made clear.

There are others that this list isn't correct on.

FIrst we dont need  to propose any of the below they already exist:

1. [llvm.exp](https://llvm.org/docs/LangRef.html#llvm-exp-intrinsic)
2. [llvm.log](https://llvm.org/docs/LangRef.html#llvm-log-intrinsic)
3. [llvm.log10](https://llvm.org/docs/LangRef.html#llvm-log10-intrinsic)
4. [llvm.pow](https://llvm.org/docs/LangRef.html#llvm-pow-intrinsic)

Second I don't agree with your`mad ` intrisnic conclusions. FIrst because we have an FMad intrinsic via
[llvm.fmulladd](https://llvm.org/docs/LangRef.html#llvm-fmuladd-intrinsic)
We just lack the signed\unsigned variants. Second if we have a DXIL op that is a good indication we need an intrinsic.

Third DIXL isn't the only backend we would want to consider for our proposal. Part of why we want to make this proposal is because the more math intrinsics exist in llvm the easier it will be to support the SPIRV backend.
SO with that said  any HLSL's intrinsic  that  has its own SPIRV opcode lowering should also be considered for a generic intrinsic. So `all` and `any` need their own intrinsics b\c they Map to SPIRV instructions
example: https://shader-playground.timjones.io/2c2f5508935b069873558be1cdb3a2b7

```python
%12 = OpConstantComposite %v4float %float_0 %float_0 %float_0 %float_0
%34 = OpFOrdNotEqual %v4bool %32 %12
%35 = OpAny %bool %34

%38 = OpFOrdNotEqual %v4bool %37 %12
 %39 = OpAll %bool %38
```

degrees and radians map to GLSL extentions
https://shader-playground.timjones.io/adc906317f915e0d2ce2e22c85565b02
```python
%13 = OpExtInst %v4float %1 Degrees %12
%14 = OpExtInst %v4float %1 Radians %12
%15 = OpExtInst %v4float %1 Step %12 %12 # 
```

In your conclusions you had dot and rcp listed. We don't need an `rcp` intrinsic that can just be lowered to `1 / x` that seems to be consistent in SPIRV so I'll make a change to move the lowering of that one out of .
As for dot. if we do dot we have to also consider how we are going to handle the integer cases. In DXIL its a daisy change of mad operations. In  SPIRV it is all multiplies upfront then accumulate them at the end. Do we need an intrinsic for the integer cases since the backend behaviors are different? Also dot for DIXL makes a distinction between using umad\imad but  SPIRV  has no ir differences between signed and unsigned dot.
https://shader-playground.timjones.io/e7b3068d8b1d1e298b2790f666853d19

```python
%12 = OpCompositeExtract %int %11 0
         %13 = OpIMul %int %12 %12
         %14 = OpCompositeExtract %int %11 1
         %15 = OpIMul %int %14 %14
         %16 = OpCompositeExtract %int %11 2
         %17 = OpIMul %int %16 %16
         %18 = OpCompositeExtract %int %11 3
         %19 = OpIMul %int %18 %18
         %20 = OpIAdd %int %13 %15
         %21 = OpIAdd %int %20 %17
         %22 = OpIAdd %int %21 %19
         %23 = OpCompositeConstruct %v4int %22 %22 %22 %22
```

So my conclusion is you only need 13 of your math intrinsics (-4).
The 5 utillity functions you have listed likely need intrinsics (+5)
We probalby need an imad\umad intriinsic  since we have an llvm generic one for (fmad). (+2)
We don't need `rcp`) (-1)

Does dot need  special typed versions (+0 to +2)?

**Comment by bogner** [comment]
Started an RFC here: https://discourse.llvm.org/t/rfc-all-the-math-intrinsics/78294

**Comment by bogner** [comment]
- The RFC for generic math has general consensus: https://discourse.llvm.org/t/rfc-all-the-math-intrinsics/78294/16
- Proposing bitfield intrinsics will be tracked by #89641
