### ISSUE TITLE
[HLSL] Rich availability diagnostics

### ISSUE THREAD

**Issue by llvm-beanz** [llvm/llvm-project#87389]
## Description

Each new shader model introduces new APIs that expose new hardware and runtime functionality. We should provide diagnostics to users about API availability notifying them when they use APIs that are not available.

A detailed design proposal for the Clang implementation is available here:
https://github.com/microsoft/hlsl-specs/blob/main/proposals/infra/INF-0001-availability-diagnostics.md

## Acceptance Criteria

- [x] microsoft/hlsl-specs#188
- [x]  microsoft/hlsl-specs#189
- [x] #89802
- [x] #90095
- [x] #90096
- [x] #92073

**Comment by llvm-beanz** [comment]
@hekota is going to be taking this over

**Comment by hekota** [comment]
I will take this.
