### ISSUE TITLE
Support `preserve_none` calling convention on AArch64 targets

### ISSUE THREAD

**Issue by antangelo** [llvm/llvm-project#87423]
#76868 adds support for a new `preserve_none` calling convention for X86_64 where all general registers are caller saved, and can be used to pass arguments. The corresponding RFC is here: https://discourse.llvm.org/t/rfc-exposing-ghccc-calling-convention-as-preserve-none-to-clang/74233

This issue is to track AArch64 support for the feature.

**Comment by microcai** [comment]
any plans for Loongarch64 support?
