### ISSUE TITLE
llvm.threadlocal.address changes regressed code using TLS

### ISSUE THREAD

**Issue by MatzeB** [llvm/llvm-project#87437]
Writing this mostly as a FYI and wondering if others have observed this or are looking into this too?

We are in the process of upgrading compiler versions and noticed a 0.5% regression in HHVM which is a heavy user of TLS. This was bisected to the changes in https://reviews.llvm.org/D125291 and https://reviews.llvm.org/D129833 that introduce `llvm.theadlocal.address`.

While I am still in the process of completely classifying (and maybe fixing) things, I believe this shows up as increased CSEing of TLS base addresses and consequently increased spilling activity. We also seem to be unable to rematerialize or fold such accesses further increasing register pressure and hence spills.

Example of bad codegen pattern (within a bigger function):
```
        movq    %fs:0x0, %rcx
        leaq    -0x2540(%rcx), %rcx
        movq    %rcx, -0x68(%rbp)
        movq    %fs:-0x2540, %rcx
        ...
        movq    -0x68(%rbp), %rcx
        movq    (%rcx), %rcx
```

**Comment by MatzeB** [comment]
This was observed with llvm-17.x; still need to check if things improved afterwards.

**Comment by MatzeB** [comment]
I think I will push the x86 ISel/Codegen to fold the segment register for TLS as aggressively into addressing modes as possible. As to me it seems it is pretty much never worth it to share/re-use the TLS base address[1].

[1] I tried some ad-hoc benchmarking with this and `t1` seems to be consistently faster here:
```
#include <benchmark/benchmark.h>

__thread __attribute__((used)) char tls[1000];

static void t0(benchmark::State& state) {
  for (auto _ : state) {
    long t, t2;
    asm volatile("\
    movq %%fs:0x0, %1 \n\
    movq -0x48(%1), %0 \n\
    movq -0x48(%1), %0 \n\
    movq -0x48(%1), %0 \n\
    movq -0x48(%1), %0 \n\
    movq -0x48(%1), %0 \n\
    movq -0x48(%1), %0 \n\
    movq -0x48(%1), %0 \n\
    movq -0x48(%1), %0 \n\
    movq -0x48(%1), %0 \n\
    movq -0x48(%1), %0 \n\
    ":"=r"(t), "=r"(t2)::);
  }
}
BENCHMARK(t0);

static void t1(benchmark::State& state) {
  for (auto _ : state) {
    long t, t2;
    asm volatile("\
    movq %%fs:-0x48, %0 \n\
    movq %%fs:-0x48, %0 \n\
    movq %%fs:-0x48, %0 \n\
    movq %%fs:-0x48, %0 \n\
    movq %%fs:-0x48, %0 \n\
    movq %%fs:-0x48, %0 \n\
    movq %%fs:-0x48, %0 \n\
    movq %%fs:-0x48, %0 \n\
    movq %%fs:-0x48, %0 \n\
    movq %%fs:-0x48, %0 \n\
    ":"=r"(t), "=r"(t2)::);
  }
}
BENCHMARK(t1);
BENCHMARK_MAIN();
```

**Comment by MatzeB** [comment]
Well it seems using a segment register forces full sized immediates so is bad for code size, but compared to the risk of extra spills/reloads and perf regressions I think it's worth it.

**Comment by WenleiHe** [comment]
https://github.com/llvm/llvm-project/issues/73314 looks related too

**Comment by MatzeB** [comment]
Also found that the intrinsic obstructed value-tracking and alias analysis. Submitted #88418 for instances in `GlobalsAAResult::AnalyzeUsesOfPointer` and `llvm::getUnderlyingObject`. Does anyone know about other cases that need adjustment? Not sure I have a good pattern to search for...
