### ISSUE TITLE
[SLP] Assertion "Packing must reduce size of vector type." failed 

### ISSUE THREAD

**Issue by JonPsson1** [llvm/llvm-project#87477]
opt -mtriple=s390x-unknown-linux -mcpu=z16 -O3 ./tc_slp.ll -o /dev/null

[tc_slp.ll.tar.gz](https://github.com/llvm/llvm-project/files/14851317/tc_slp.ll.tar.gz)

Assertion "Packing must reduce size of vector type."' failed.
...
#23 0x0000000004f8b146 llvm::SLPVectorizerPass::run

@alexey-bataev 

Thanks for the fixes, but I still wonder: Are these all separate issues? Is a proper review done for each fix? Fourth time now...

**Comment by alexey-bataev** [comment]
> opt -mtriple=s390x-unknown-linux -mcpu=z16 -O3 ./tc_slp.ll -o /dev/null
> 
> [tc_slp.ll.tar.gz](https://github.com/llvm/llvm-project/files/14851317/tc_slp.ll.tar.gz)
> 
> Assertion "Packing must reduce size of vector type."' failed. ... #23 0x0000000004f8b146 llvm::SLPVectorizerPass::run
> 
> @alexey-bataev
> 
> Thanks for the fixes, but I still wonder: Are these all separate issues? Is a proper review done for each fix? Fourth time now...

Yes, all these issues are separate, as I said before. They have common symptoms, but have different causes. Usually, this fixes are pretty simple, so I rely on post-commit review for them.

**Comment by alexey-bataev** [comment]
Fixed in 07a566793b2f94d0de6b95b7e6d1146b0d7ffe49
