### ISSUE TITLE
NUMERIC_STORAGE_SIZE should change to 64 when -fdefault-integer-8 and -fdefault-real-8 are set

### ISSUE THREAD

**Issue by jeffhammond** [llvm/llvm-project#87476]
Fortran 16.10.2.23 and 19.5.3.2 say that when `INTEGER`, `REAL`, and `LOGICAL` are 64b and `COMPLEX` and `DOUBLE PRECISION` are 128b, `NUMERIC_STORAGE_SIZE` should be 64.

I applaud LLVM for implementing the other aspects of this correctly, unlike most Fortran compilers.  Intel Fortran is the only other compiler that supports this configuration at all, and it too fails to change `NUMERIC_STORAGE_SIZE` to 64 (I reported it this morning).

```
% /opt/llvm/latest/bin/flang-new fsizes.F90 -fdefault-integer-8 -fdefault-real-8 && ./a.out
 NUMERIC_STORAGE_SIZE= 32
 STORAGE_SIZE(LOGICAL)= 64
 STORAGE_SIZE(INTEGER)= 64
 STORAGE_SIZE(REAL)= 64
 STORAGE_SIZE(DOUBLE PRECISION)= 128
 STORAGE_SIZE(COMPLEX)= 128
```

```fortran
! fsizes.F90
program main
    use iso_fortran_env
    implicit none
    logical :: l
    integer :: i
    real :: r
    double precision :: d
    complex :: c
    print*,'NUMERIC_STORAGE_SIZE=',NUMERIC_STORAGE_SIZE
    print*,'STORAGE_SIZE(LOGICAL)=',STORAGE_SIZE(l)
    print*,'STORAGE_SIZE(INTEGER)=',STORAGE_SIZE(i)
    print*,'STORAGE_SIZE(REAL)=',STORAGE_SIZE(r)
    print*,'STORAGE_SIZE(DOUBLE PRECISION)=',STORAGE_SIZE(d)
    print*,'STORAGE_SIZE(COMPLEX)=',STORAGE_SIZE(c)
end program main
```

# LLVM Version
```
% /opt/llvm/latest/bin/flang-new --version
flang-new version 19.0.0git (https://github.com/llvm/llvm-project.git d1f585056f71bc63bd2e71d744051139809e5d8b)
Target: arm64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /opt/llvm/latest/bin
```

**Comment by klausler** [comment]
What value should `NUMERIC_STORAGE_SIZE` have when only one of those options is set?

**Comment by jeffhammond** [comment]
gfortran issued a diagnostic message when the user insists violating the Fortran standard. I would encourage Flang to do the same.

**Comment by klausler** [comment]
The Fortran standard doesn't discuss compiler options, so I'm not sure what you mean here.

**Comment by jeffhammond** [comment]
When the user provides a set of options that instruct the Fortran compiler to implement Fortran type sizes that violate the aforementioned text of the Fortran standard, the GCC Fortran compiler issues the following diagnostic which, while imperfect in its pedagogy, nonetheless represents a reasonable  disclaimer of liability by the compiler that the user has done a bad thing.

Unfortunately, all Fortran compilers in use today support non-conforming behavior, brought upon by options that change the individual type sizes, rather than a single standard-conforming option that controls `NUMERIC_STORAGE_SIZE` and indirectly changes all of the relevant types in a consistent manner.  I don't think it is practical for Flang to not support such usage models - I merely recommend that the user be informed that employing them is non-conforming and some aspects of the Fortran standard are no longer implementable.

```
% gfortran -fdefault-integer-8 -fdefault-real-8  fsizes.F90
fsizes.F90:2:9:

    2 |     use iso_fortran_env
      |         1
Warning: Use of the NUMERIC_STORAGE_SIZE named constant from intrinsic module ISO_FORTRAN_ENV at (1) is incompatible with option -fdefault-integer-8
```

```
% gfortran -fdefault-real-8   fsizes.F90
fsizes.F90:2:9:

    2 |     use iso_fortran_env
      |         1
Warning: Use of the NUMERIC_STORAGE_SIZE named constant from intrinsic module ISO_FORTRAN_ENV at (1) is incompatible with option -fdefault-real-8
```

```
% gfortran -fdefault-integer-8   fsizes.F90
fsizes.F90:2:9:

    2 |     use iso_fortran_env
      |         1
Warning: Use of the NUMERIC_STORAGE_SIZE named constant from intrinsic module ISO_FORTRAN_ENV at (1) is incompatible with option -fdefault-integer-8
```

**Comment by klausler** [comment]
When both default `INTEGER` and `REAL` have the same storage size, why should there be a warning?

**Comment by jeffhammond** [comment]
With gfortran, there are no options to modify the size of `LOGICAL` or `DOUBLE PRECISION`, so it cannot implement any conforming configuration outside of the default.

Flang does not suffer _this issue_, but you have noted that if Flang is used with only of `-fdefault-integer-8` and `-fdefault-real-8`, then the usage is non-confirming.  This is the situation in which I recommend Flang provide a diagnostic message.

**Comment by klausler** [comment]
`LOGICAL` is the same size as default `INTEGER` and `DOUBLE PRECISION` is twice the size of default `REAL` with both gfortran and f18.  So everything is consistent and conforming when default `INTEGER` and `REAL` have the same size.

**Comment by jeffhammond** [comment]
That is not true with gfortran when those options are used. I tested this today.

**Comment by klausler** [comment]
What I'm observing:
```
$ gfortran -v
Reading specs from /home/sw/thirdparty/gcc/gcc-13.2.0/Linux_x86_64/lib/gcc/x86_64-pc-linux-gnu/13.2.0/specs
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/home/sw/thirdparty/gcc/gcc-13.2.0/Linux_x86_64/libexec/gcc/x86_64-pc-linux-gnu/13.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../gcc-13.2.0/configure --prefix=/home/sw/thirdparty/gcc/gcc-13.2.0/Linux_x86_64 --enable-languages=c,c++,fortran,lto,objc,obj-c++,d,ada,go,m2 --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --disable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto --host=x86_64-pc-linux-gnu --target=x86_64-pc-linux-gnu
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 13.2.0 (GCC) 
$ cat t.f90
! fsizes.F90
program main
    use iso_fortran_env
    implicit none
    logical :: l
    integer :: i
    real :: r
    double precision :: d
    complex :: c
    print*,'NUMERIC_STORAGE_SIZE=',NUMERIC_STORAGE_SIZE
    print*,'STORAGE_SIZE(LOGICAL)=',STORAGE_SIZE(l)
    print*,'STORAGE_SIZE(INTEGER)=',STORAGE_SIZE(i)
    print*,'STORAGE_SIZE(REAL)=',STORAGE_SIZE(r)
    print*,'STORAGE_SIZE(DOUBLE PRECISION)=',STORAGE_SIZE(d)
    print*,'STORAGE_SIZE(COMPLEX)=',STORAGE_SIZE(c)
end program main
$ gfortran t.f90; ./a.out
 NUMERIC_STORAGE_SIZE=          32
 STORAGE_SIZE(LOGICAL)=          32
 STORAGE_SIZE(INTEGER)=          32
 STORAGE_SIZE(REAL)=          32
 STORAGE_SIZE(DOUBLE PRECISION)=          64
 STORAGE_SIZE(COMPLEX)=          64
$ gfortran -fdefault-integer-8 t.f90; ./a.out
t.f90:3:9:

    3 |     use iso_fortran_env
      |         1
Warning: Use of the NUMERIC_STORAGE_SIZE named constant from intrinsic module ISO_FORTRAN_ENV at (1) is incompatible with option -fdefault-integer-8
 NUMERIC_STORAGE_SIZE=                   32
 STORAGE_SIZE(LOGICAL)=                   64
 STORAGE_SIZE(INTEGER)=                   64
 STORAGE_SIZE(REAL)=                   32
 STORAGE_SIZE(DOUBLE PRECISION)=                   64
 STORAGE_SIZE(COMPLEX)=                   64
$ gfortran -fdefault-real-8 t.f90; ./a.out
t.f90:3:9:

    3 |     use iso_fortran_env
      |         1
Warning: Use of the NUMERIC_STORAGE_SIZE named constant from intrinsic module ISO_FORTRAN_ENV at (1) is incompatible with option -fdefault-real-8
 NUMERIC_STORAGE_SIZE=          32
 STORAGE_SIZE(LOGICAL)=          32
 STORAGE_SIZE(INTEGER)=          32
 STORAGE_SIZE(REAL)=          64
 STORAGE_SIZE(DOUBLE PRECISION)=         128
 STORAGE_SIZE(COMPLEX)=         128
$ gfortran -fdefault-integer-8 -fdefault-real-8 t.f90; ./a.out
t.f90:3:9:

    3 |     use iso_fortran_env
      |         1
Warning: Use of the NUMERIC_STORAGE_SIZE named constant from intrinsic module ISO_FORTRAN_ENV at (1) is incompatible with option -fdefault-integer-8
 NUMERIC_STORAGE_SIZE=                   32
 STORAGE_SIZE(LOGICAL)=                   64
 STORAGE_SIZE(INTEGER)=                   64
 STORAGE_SIZE(REAL)=                   64
 STORAGE_SIZE(DOUBLE PRECISION)=                  128
 STORAGE_SIZE(COMPLEX)=                  128
```

**Comment by klausler** [comment]
Ok, I have a patch ready to go for f18.  In the inconsistent case (storage_size(1) /= storage_size(1.0)) when a warning is emitted, I still need to set `NUMERIC_STORAGE_SIZE` to some value -- should it be the smaller or the larger of the two sizes?

**Comment by klausler** [comment]
https://github.com/llvm/llvm-project/pull/87566

**Comment by jeffhammond** [comment]
My `gfortran` experiments were wrong.  Yours are correct.  I don't know what happened.

> Ok, I have a patch ready to go for f18. 

Thanks.

> In the inconsistent case (storage_size(1) /= storage_size(1.0)) when a warning is emitted, I still need to set NUMERIC_STORAGE_SIZE to some value -- should it be the smaller or the larger of the two sizes?

If it must be a constant, then it should be 32, because that is the value that corresponds to the default options.

I think a warning about `NUMERIC_STORAGE_SIZE` when either or both of `-fdefault-integer-8` and `-fdefault-real-8` is used is appropriate, albeit less important than what you just implemented.

**Comment by klausler** [comment]
My patch will emit a warning if the sizes are inconsistent; if they're both 8 bytes, the compiler and program both conform, so no warning is appropriate.

**Comment by kargl** [comment]
It seems that there is a fundamental misunderstanding of what these options mean for gfortran.  So, to declare that other compilers do not do something correctly is a bit  disingenuous.  

Default integer kind has `kind=4` under gfortran.   Default real kind and double precision are `kind=4` and `kind=8`.

-fdefault-integer-8 essentially treats a declaration of the form `integer i` as-if the user wrote `integer(8) i`.  It leaves the kind of the declaration `integer(4) j` unchanged.  -fdefault-real-8 treats `real x` as-if the user wrote `real(8) x`.  It leaves the kind of the declaration `real(8) y` unchanged.  So, the underlying storage unit size is unchanged as one can still have `real(4)` entities within a program.  More importantly, the -default-* options do not effect numeric literal constants.
```
program main
   implicit none
   character(len=*), parameter :: fmt = '(A,4(1X,I3))'
   integer i
   real  r
   double precision :: d
   integer(4) i4
   real(4) r4
   real(8) d8
   print fmt, 'integer: ', storage_size(i), storage_size(i4), storage_size(1), storage_size(1_4)
   print fmt, '   real: ', storage_size(r), storage_size(r4), storage_size(1.e0), storage_size(1._4)
   print fmt, ' double: ', storage_size(d), storage_size(d8),  storage_size(1.d0), storage_size(1._8)
end program main
```

    gfcx -o z a.f90 -w && ./z
    integer:   32  32  32  32
      real:   32  32  32  32
     double:   64  64  64  64

**Comment by klausler** [comment]
```
$ gfortran -v
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.4.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04) 
$ cat t2.f90
print *, storage_size(1), storage_size(1.), storage_size((1.,2.)), storage_size(.true.)
end
$ gfortran t2.f90; ./a.out
          32          32          64          32
$ gfortran -fdefault-integer-8 t2.f90; ./a.out
                   64                   32                   64                   64
$ gfortran -fdefault-real-8 t2.f90; ./a.out
          32          64         128          32
$ gfortran -fdefault-integer-8 -fdefault-real-8 t2.f90; ./a.out
```

**Comment by jeffhammond** [comment]
> It seems that there is a fundamental misunderstanding of what these options mean for gfortran. So, to declare that other compilers do not do something correctly is a bit disingenuous.

Please see the original post.  The Fortran standard says what `NUMERIC_STORAGE_SIZE` means.  The behavior of `REAL(4)`, `INTEGER(4)`, `REAL(8)` and `INTEGER(8)` is irrelevant.  The as-if behavior of GCC is also irrelevant.  If you run the original source code file through GCC with `-fdefault-integer-8` and `-fdefault-real-8`, the behavior of the resulting program does not comply with the aforementioned text of the Fortran standard.

**Comment by kargl** [comment]
> > It seems that there is a fundamental misunderstanding of what these options mean for gfortran. So, to declare that other compilers do not do something correctly is a bit disingenuous.
> 
> Please see the original post. The Fortran standard says what `NUMERIC_STORAGE_SIZE` means. The behavior of `REAL(4)`, `INTEGER(4)`, `REAL(8)` and `INTEGER(8)` is irrelevant. The as-if behavior of GCC is also irrelevant. If you run the original source code file through GCC with `-fdefault-integer-8` and `-fdefault-real-8`, the behavior of the resulting program does not comply with the aforementioned text of the Fortran standard.
> 
> Simply put, `NUMERIC_STORAGE_SIZE` must be the same as `STORAGE_SIZE()` of an `INTEGER`, `LOGICAL, and `REAL`. Today, only Cray Fortran complies with this. Flang will comply once Peter's PR is merged.

I did read the original post.  The one where you wrote:

> Fortran 16.10.2.23 and 19.5.3.2 say that when `INTEGER`, `REAL`, and `LOGICAL` are 64b and `COMPLEX` and `DOUBLE PRECISION` are 128b, `NUMERIC_STORAGE_SIZE` should be 64.
> 
> I applaud LLVM for implementing the other aspects of this correctly, unlike most Fortran compilers.

Then you (and Peter) discuss gfortran's behavior with these options, which suggests you think gfortran's behavior is incorrect.  I'm simply pointing out what these options do with respect to gfortran.  With the following code, what value should `numeric_storage_size ` be given gfortran's documented behavior for -fdefault-real-8? 

```
real i
real(4) j
print *, numeric_storage_unit(i), numeric_storage_unit(j)
end

! gfcx -o z -fdefault-real-8 a.f90 && ./z
!  64          32
```

Those options under gfortran change the mean of a *declaration statement* that use a default `real`.   The option you're looking for is -fdefault-storage-size=8.  Well, gfortran does not have that option.

I'll also note that the Fortran standard says nothing about command line options.

**Comment by klausler** [comment]
gfortran is fine, apart from needlessly warning about using `numeric_storage_size` when both `-fdefault-int-8` and `-fdefault-real-8` are used.  and it applies the effects of these options correctly to default literals in source, too.
