### ISSUE TITLE
Scudo ERROR: internal map failure has no details

### ISSUE THREAD

**Issue by ilya-fedin** [llvm/llvm-project#87473]
I'm getting reports from some end users that application doesn't launch with `Scudo ERROR: internal map failure.` error in terminal after updating scudo from llvmorg-17.0.5 to llvmorg-18.1.1. I would expect the error to print the `strerror(errno)` just like reportUnmapError and reportProtectError do.

**Comment by cferris1000** [comment]
I'll add it, but I'm not sure if it will help you diagnose the problem.

I would guess that it might be that the reserve in the primary might be causing issues if these applications are using setrlimit to change the address space. Or if these applications are doing something else that limits the amount of virtual address space available to Scudo.

**Comment by ilya-fedin** [comment]
No, no such tricks in application itself. Although I have no idea if any of third party libraries or the user can do that...

**Comment by cferris1000** [comment]
Change has been submitted. If you are able to figure out what's causing the mmap failures please open a new bug with that information.
