### ISSUE TITLE
-fno-unsafe-math-optimizations enables constrained intrinsics

### ISSUE THREAD

**Issue by topperc** [llvm/llvm-project#87523]
I expected -fno-unsafe-math-optimizations would be the default behavior and only undo -funsafe-math-optimizations. Instead it enables constrained intrinsics. https://godbolt.org/z/ooYdY4Kox

I checked with @andykaylor who thought this behavior might be because gcc documentation says -fno-unsafe-math-optimizations implies -ftrapping-math. gcc has -ftrapping-math by default, but clang does not.

**Comment by andykaylor** [comment]
I was looking through the revision history, and I see that until https://github.com/llvm/llvm-project/commit/7f9b5138470db1dc58f3bc05631284c653c9ed7a the clang driver code was setting trapping math to true by default, but it isn't clear to me that it actually did anything to support that. The local variable in the driver was used to decide whether options like `-menable-unsafe-fp-math` and `-ffast-math` were passed to the cc1 invocation. 

If TrappingMath was false at the end of the fp option rendering, the driver passed `-fno-trapping-math` but I don't think that option actually did anything. The commit above introduced -ffp-exception-behavior, which actually triggers constrained intrinsic use and is now connected to the driver fp rendering function's TrappingMath variable.
