### ISSUE TITLE
[Ocaml] Bindings produce wrong IR for pointers

### ISSUE THREAD

**Issue by kritonios01** [llvm/llvm-project#87552]
Hello all,
I have been working on a compiler in OCaml and I am using the LLVM bindings to compile to LLVM IR.
I believe I have found a bug in OCaml's LLVM bindings. Please find attached a .ml file which when compiled and run produces the file "llvm_ir.ll". Open the file and you will see that in the store instruction, a ptr* type is used which of course is invalid causing llc to fail with:
`error: ptr* is invalid - use ptr instead`
The issue exists both on version 15 and 16 of bindings. Please confirm if this is a bug and what can be done. More generally, I do not see how opaque pointers can be codegened. In C++ when using `PointerType::getUnqual` the pointer is automatically converted to opaque pointer in LLVM 15. This does not seem to be the behaviour in OCaml. Almost all of the bindings produce IR with typed pointers. Please find attached an semantically equivalent C++ file which when compiled and run produces correct LLVM 15 IR using only opaque pointers.
[Archive.zip](https://github.com/llvm/llvm-project/files/14858109/Archive.zip)
I provide here the IR produced by each one for convenience:

OCaml
```
; ModuleID = 'program'
source_filename = "program"

%frame = type { ptr }

define void @main(ptr %0) {
main_entry:
  %frame_ptr = alloca %frame, align 8
  %frame_elem_ptr = getelementptr inbounds %frame, %frame* %frame_ptr, i32 0, i32 0
  store ptr %0, ptr* %frame_elem_ptr, align 8
  ret void
}
```

C++
```
; ModuleID = 'program'
source_filename = "program"

%frame = type { ptr }

define void @main(ptr %0) {
main_entry:
  %frame_ptr = alloca %frame, align 8
  %frame_elem_ptr = getelementptr inbounds %frame, ptr %frame_ptr, i32 0, i32 0
  store ptr %0, ptr %frame_elem_ptr, align 8
  ret void
}
```

**Comment by jberdine** [comment]
IIUC this issue has been resolved through email discussion between @kritonios01, @alan-j-hu and myself. The crux of the issue is that the state of the available documentation is suboptimal and lead to usage that mixed opaque and transparent pointers with the OCaml bindings for LLVM 15. The situation is better for LLVM 16 and later. @kritonios01 please feel free to reopen if you think I have overlooked or misunderstood.

**Comment by kritonios01** [comment]
Dear Josh, the issue should indeed be marked as closed and I had overlooked it. However, I should suggest that somehow we mention it in the documentation of version 15 of the bindings because it is not obvious and it is not mentioned anywhere. It is my understanding that opaque pointers are simply disabled in v15 and cannot be turned on, however in the official documentation of LLVM 15 it is mentioned that opaque pointers are not only supported, but also the default. Please see the version support segment [here](https://llvm.org/docs/OpaquePointers.html). It is very probable still, that some people might want to target version 15 of LLVM. And it is an issue which can in many cases cause unexpected problems due to the lack of documentation in OCaml's bindings. @alan-j-hu had mentioned in one of his e-mails that he owns a site in which he hosts the documentation (which is very good work btw) and that there is also the docs in OCaml's [official site](https://ocaml.org/p/llvm/latest/doc/index.html). Nevertheless, none of these sites have documentation for v15 of the bindings. I reckon that at least there should be a reference of this issue, even if we don't go the extra mile to describe every function of the bindings. Please, could you suggest how can this be done (especially on the official site) ? I could submit a pull request if needed..
