### ISSUE TITLE
[libc][c23][fenv] implement fetestexceptflag

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#87565]
See `7.6.4.6 The fetestexceptflag function`.  Another C23 addition. We have fetestexcept, but not the symmetrical API for accepting a `fexcept_t*`.

**Comment by robincaloudis** [comment]
Looks like a well defined scope for a newby. I would like to give it a shot. Just started working on it.

**Comment by nickdesaulniers** [comment]
Thanks @robincaloudis ! If it serves as a helpful reference, checkout the recent PR #87603 from @aniplcc

**Comment by robincaloudis** [comment]
@nickdesaulniers, do you mind to review https://github.com/llvm/llvm-project/pull/87828? Thank you.
