### ISSUE TITLE
Undefined symbols "std::__1::__libcpp_verbose_abort(char const*, ...)"

### ISSUE THREAD

**Issue by ryandesign** [llvm/llvm-project#87590]
Various software that used to build fine on older versions of macOS (with its older libc++) when using a newer version of llvm.org clang now fails to build with llvm.org clang 16 and 17 with a message like:

```
Undefined symbols for architecture x86_64:
  "std::__1::__libcpp_verbose_abort(char const*, ...)", referenced from:
      __ZNSt3__120__throw_out_of_rangeB8un170004EPKc in GooString.cc.o
      __ZNSt3__120__throw_length_errorB8un170004EPKc in GooString.cc.o
      __ZNSt3__120__throw_length_errorB8un170004EPKc in gbase64.cc.o
      __ZNSt3__120__throw_length_errorB8un170004EPKc in gbasename.cc.o
      __ZNSt3__120__throw_length_errorB8un170004EPKc in gfile.cc.o
      __ZNSt3__120__throw_length_errorB8un170004EPKc in grandom.cc.o
      __ZNSt3__120__throw_length_errorB8un170004EPKc in FoFiTrueType.cc.o
      ...
```

MacPorts is tracking this issue at https://trac.macports.org/ticket/68640 but we do not know how to solve it other than forever limiting older systems to using clang 15 and older, which is eventually going to be a problem when software requires features introduced in clang 16 and later.

Possibly, MacPorts will have to begin providing and using a newer libc++ for older systems to solve this and other problems. This already exists on an opt-in basis which more and more software is having to use due to `std::filesystem` (which projects are increasingly adopting) being implemented only in versions of libc++ newer that those included with older systems.

**Comment by philnik777** [comment]
What exactly is the problem you're trying to report? We can't change what has been shipped on an older system, and we can't implement `filesystem` with a reasonable amount of effort in the headers. If you want to support these features on older systems you'll have to ship a dylib that supports these features.

**Comment by ryandesign** [comment]
For many years, MacPorts has been successfully using newer versions of clang together with the older versions of libc++ that shipped on older versions of macOS to allow newer software to build on older systems (software requiring features only implemented in new libc++, like `std::filesystem`, being an exception). That broke with clang 16 with the appearance of the new error about `std::__1::__libcpp_verbose_abort` being undefined.

**Comment by ldionne** [comment]
@ryandesign So you are using a recent Clang (let's say Clang 17) to compile on an old macOS. What libc++ are you using? Are you using the libc++ provided in the SDK on the old macOS, or are you using the libc++ version shipped with Clang 17?

I actually suspect that you are mixing the Clang 17 headers of libc++ with the old macOS libc++.dylib. So the headers are recent and configured for upstream, but then you link against an old libc++ configured for being a system library. That's broken on several levels, and the work-around suggested in https://trac.macports.org/ticket/68640 is very brittle, please don't go down that route.

To be fair, I agree that it's way too easy to fall into that trap, and in fact Clang does the wrong thing by default (see https://github.com/llvm/llvm-project/issues/77653).

Please confirm that the above is what's happening (i.e. you are unknowingly using Clang 17 headers with the system-provided dylib), and then we can figure out how to get your configuration clean from there.

**Comment by hoyhoy** [comment]
@ryandesign what happens if you add `-lc++-abi` to your `LDFLAGS`?

**Comment by kencu** [comment]
> Please confirm that the above is what's happening (i.e. you are unknowingly using Clang 17 headers with the system-provided dylib), and then we can figure out how to get your configuration clean from there.

To support some very keen users of older MacOS systems, MacPorts ships a newer packaged libc++.dylib on old systems that provides things like filesystem. Unsanctioned by llvm for sure, but it works, mostly. 

To make it work, we turn off the Apple availability settings and use generic settings. This works too, mostly.

The generic availability header settings in clang 16 and newer indicate the libc++.dylib supports verbose abort. The newer libc++.dylib MacPorts ships does not support verbose abort.

So disabling that setting as per the workaround in the ticket you referenced works just perfectly, for now at least.

This is an extremely MacPorts-specific issue doing unsanctioned llvm hacks that NEVER should have been posted here as an issue to disturb you. Please close this issue if you agree.

If there are too many more headaches shipping the newer libc++.dylib, we’ll just stop doing that, and users of the older Mac hardware that can upgrade any more will have to install Ubuntu on those systems instead.

**Comment by ldionne** [comment]
Thanks for the context and information. It's interesting and useful for us to know that these use cases exist. Note that this problem would basically arise should we introduce any other widely-used symbol in the dylib, so this is a general problem indeed.

Since there is nothing concretely actionable for us in this issue, I'll close it to keep the tracker clean. Cheers and don't hesitate to let us know if you encounter issues that you think are actionable in the future.
