### ISSUE TITLE
[clang] Double free generated in move assignment when accessing a pointer via mixin

### ISSUE THREAD

**Issue by kaimfrai** [llvm/llvm-project#87662]
The following code erroneously results in a double free/delete being generated for the move assignment operator. It's a simplified version of a customizable dynamic array template: One version would simply borrow it (ommited for brevity) the other owns it. The difference is handled in 2 distinct mixin classes, selected at compile time.

```
#include <utility>
#include <new>
#include <cassert>

struct Ptr
{
    int* p = nullptr;
};

template<typename T>
struct ArrayMixin
{
    template<typename... U>
    constexpr ArrayMixin(U... u) noexcept
    {
        static_cast<T&>(*this).p = new int[sizeof...(U)]{static_cast<int>(u)...};
    }

    constexpr ArrayMixin(ArrayMixin&& o) noexcept
    {
        int*& p = static_cast<T&>(*this).p;
        int*& q = static_cast<T&>(o).p;

        p = std::exchange(q, nullptr);
    }

    friend constexpr void swap(ArrayMixin& l, ArrayMixin& r) noexcept
    {
        int*& p = static_cast<T&>(l).p;
        int*& q = static_cast<T&>(r).p;
        assert(p != q);
        std::swap(p, q);
    }

    constexpr ArrayMixin& operator=(ArrayMixin&& o) noexcept
    {
        int*& p = static_cast<T&>(*this).p;
        int*& q = static_cast<T&>(o).p;
        assert(p != q);
        if (p)
        {
            delete[] p;
            p = nullptr;
        }

        p = std::exchange(q, nullptr);

        return *this;
    }

    constexpr auto& operator[](int i) noexcept
    {
        return static_cast<T&>(*this).p[i];
    }

    constexpr ~ArrayMixin() noexcept
    {
        int*& p = static_cast<T&>(*this).p;
        if (p)
        {
            delete[] p;
            p = nullptr;
        }
    }
};

struct Combined : Ptr, ArrayMixin<Combined>
{
    using ArrayMixin<Combined>::ArrayMixin;
};

constexpr inline auto Swap() noexcept
{
    Combined c{9, 7, 6, 5, 8};
    c[0] = 5;
    Combined d{};
    swap(c, d);

    return d[0];
}

constexpr inline auto Construct() noexcept
{
    Combined c{9, 7, 6, 5, 8};
    c[0] = 5;
    Combined d{std::move(c)};

    return d[0];
}

constexpr inline auto Assign() noexcept
{
    Combined c{9, 7, 6, 5, 8};
    c[0] = 5;
    Combined d{};
    d = std::move(c);

    return d[0];
}

int main()
{
    return 5 - Swap() + Construct() - Assign();
}
```
https://godbolt.org/z/Ef193W48G

With -O3 and -DNDEBUG this generates 2 calls to delete[] for only 1 call for new[].  Without either flag an assertion is triggered in the assignment operator. Suprisingly the pointers pointing to different allocations are the same, resulting in that allocation being freed twice. This does not happen when using the move constructor or swap.

Moving the int* p member directly into the mixin or letting the mixin inherit from Ptr directly resolves the issue. It is not an option however if you want multiple mixins to operate on the same member and only one mixin can hold the member to access it.
It is my understanding that acessing the variable p from ArrayMixin would also be correct, as Ptr is within its lifetime by the time the constructor for ArrayMixin is called and especially by the time the assignment operator is called. Even when adding another cast from T& (not fully constructed in the Array Mixin constructor, but it's just referenced anyways) to Ptr&, the behaviour is the same.

**Comment by dwblaikie** [comment]
I don't think there's a compiler bug here - I think what's happening in `Combined`'s move assignment operator is that the `Ptr` base is being assigned first, using the builtin assignment operator - copying the value from the RHS to the LHS. Then the `ArrayMixin`'s move assignment operator runs, and swaps the identical values - so the same value gets deleted twice, because it's owned by two objects?
