### ISSUE TITLE
Does lto support dynamic loading of Pass?

### ISSUE THREAD

**Issue by Zeroc0077** [llvm/llvm-project#87780]
I tried using function like `registerFullLinkTimeOptimizationEarlyEPCallback` to load the pass that is processed during the link phase, but it doesn't seem to work.

**Comment by EugeneZelenko** [comment]
@Zeroc0077: Could you please elaborate?

**Comment by Zeroc0077** [comment]
> @Zeroc0077: Could you please elaborate?

`registerFullLinkTimeOptimizationEarlyEPCallback` only support register a lto pass for elf now. It doesn't support Mach-O.
