### ISSUE TITLE
[address of label] llvm-gcc generates bad assembly: invalid sections for operation on ...

### ISSUE THREAD

**Issue by markus-oberhumer** [llvm/llvm-project#8779]
|  |  |
| --- | --- |
| Bugzilla Link | [8407](https://llvm.org/bz8407) |
| Version | trunk |
| OS | Linux |
| Attachments | [Small C source code to demonstrate the problem.](https://user-images.githubusercontent.com/92601886/143742144-3ded647b-b244-4896-b7a4-b076e2beea4c.gz) |
| CC | @asl |

## Extended Description 

llvm-gcc seems to generate bad assembly for jump-table offsets.

This could be related to bug2023.

Snippet from the attached source file:

#define LABEL_DIFF(t,a,b) ((t) ((const char*)&&a - (const char*)&&b))

int *test_short(int i)
{
    static const short t[] = { 0, LABEL_DIFF(short,l1,l0) };
    goto * (const void *) ((const char *)&&l0 + t[i]);
    l0: return &a;
    l1: return &b;
}

**Comment by gwelymernans** [comment]
Closing as DragonEgg appears gone.
