### ISSUE TITLE
[libc][docs] generate docs for signal.h

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#87835]
Using [n3096](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3096.pdf) Section 7.14, we should fill out the function list in a new file called libc/utils/docgen/signal.json (so that we have entries about which standard section talks about what, similar to libc/utils/docgen/fenv.json).

Then we should run ./libc/utils/docgen/docgen.py signal.h > libc/docs/signal.rst to create a page for signal.h.

Then we should add a link to signal in libc/docs/index.rst so that it's linked from libc.llvm.org (similar to fenv).

**Comment by nickdesaulniers** [comment]
For this, we'll also need to modify libc/utils/docgen/docgen.py to recurse into `linux/` directories to see what functions "exist" or are implemented.

**Comment by simonzgx** [comment]
I'd like to work on these two issues, including #87833.

**Comment by zdumonts** [comment]
> I'd like to work on these two issues, including #87833.

Hi, I just submitted a pr for #87833. Are you working on either issue as of now?

**Comment by simonzgx** [comment]
> > I'd like to work on these two issues, including #87833.
> 
> Hi, I just submitted a pr for #87833. Are you working on either issue as of now?

Yeah.
It's ok, I'll open a PR for the current issue later.
