### ISSUE TITLE
[libc] Add proxy header for fenv.h macro constants.

### ISSUE THREAD

**Issue by lntue** [llvm/llvm-project#87863]
Context: https://github.com/llvm/llvm-project/pull/87017 https://github.com/llvm/llvm-project/pull/87598

Add a proxy header for fenv.h macro constants so that our implementations and tests will work nicely for both overlay and full build modes.

- [ ]  Add `libc/hdr/fenv_macros.h` that will include the system `<fenv.h>` in overlay mode or include `libc/include/llvm-libc-macros/fenv-macros.h` in full build mode.  (See for instance `libc/hdr/math_macros.h` ).
- [ ] Add its corresponding cmake target in `libc/hdr/CMakeLists.txt`.
- [ ] Replacing as many `#include <fenv.h>` and cmake target dependency on `libc.include.fenv` as possible, and document where those inclusion cannot be removed yet (due to usage of types or functions defined in `fenv.h`)
- [ ] Add `hdr_fenv_macros` target in `utils/bazel/llvm-project-overlay/libc/BUILD.bazel`.
- [ ] Update dependencies to all targets that include `hdr/fenv_macros.h`.

**Comment by Jobhdez** [comment]
Can you please assign this to me? thanks
