### ISSUE TITLE
Clang-18 CRASHING on VALID recursive lambda code

### ISSUE THREAD

**Issue by nyyakko** [llvm/llvm-project#87861]
System:
`Windows 10 Pro 21H2`

Clang++:
```
PS C:\Users\Wellington> clang++ --version
clang version 18.1.3
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```

Snippet:
```cpp
int main()
{
    std::string string {};

    for (auto index = 0zu; index < string.size(); index += 1)
    {
        if (string.at(index) == '<')
        {
            [&] (this auto self) -> void {
                index += 1;
                while (string.at(index) != '>')
                {
                    if (string.at(index) == '<')
                        self();
                    else
                    {
                        index += 1;
                    }
                }
                index += 1;
            }();
        }
    }
}
```

Backtrace (from compiler-explorer because the pre-compiled binary without debug info which doesn't give any meaningful info, see replies):
```
<source>:13:24: error: cannot compile this l-value expression yet
   13 |                 while (string.at(index) != '>')
      |                        ^~~~~~~~~
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -std=c++23 <source>
1.	<eof> parser at end of file
2.	Per-file LLVM IR generation
3.	<source>:11:13: Generating code for declaration 'main()::(anonymous class)::operator()'
 #0 0x00000000036ac218 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x36ac218)
 #1 0x00000000036aa364 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x36aa364)
 #2 0x00000000035f2e98 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007f8bb7442520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x0000000003d11827 arrangeFreeFunctionLikeCall(clang::CodeGen::CodeGenTypes&, clang::CodeGen::CodeGenModule&, clang::CodeGen::CallArgList const&, clang::FunctionType const*, unsigned int, bool) CGCall.cpp:0:0
 #5 0x0000000003dac869 clang::CodeGen::CodeGenFunction::EmitCall(clang::QualType, clang::CodeGen::CGCallee const&, clang::CallExpr const*, clang::CodeGen::ReturnValueSlot, llvm::Value*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3dac869)
 #6 0x0000000003dae1b7 clang::CodeGen::CodeGenFunction::EmitCallExpr(clang::CallExpr const*, clang::CodeGen::ReturnValueSlot) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3dae1b7)
 #7 0x0000000003df6fea (anonymous namespace)::ScalarExprEmitter::VisitCallExpr(clang::CallExpr const*) CGExprScalar.cpp:0:0
 #8 0x0000000003ded321 clang::StmtVisitorBase<std::add_pointer, (anonymous namespace)::ScalarExprEmitter, llvm::Value*>::Visit(clang::Stmt*) CGExprScalar.cpp:0:0
 #9 0x0000000003dfb888 (anonymous namespace)::ScalarExprEmitter::EmitBinOps(clang::BinaryOperator const*, clang::QualType) CGExprScalar.cpp:0:0
#10 0x0000000003dfbc9d (anonymous namespace)::ScalarExprEmitter::EmitCompare(clang::BinaryOperator const*, llvm::CmpInst::Predicate, llvm::CmpInst::Predicate, llvm::CmpInst::Predicate, bool) CGExprScalar.cpp:0:0
#11 0x0000000003deea0c clang::StmtVisitorBase<std::add_pointer, (anonymous namespace)::ScalarExprEmitter, llvm::Value*>::Visit(clang::Stmt*) CGExprScalar.cpp:0:0
#12 0x0000000003df3072 clang::CodeGen::CodeGenFunction::EmitScalarExpr(clang::Expr const*, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3df3072)
#13 0x0000000003d91864 clang::CodeGen::CodeGenFunction::EvaluateExprAsBool(clang::Expr const*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3d91864)
#14 0x00000000039bb310 clang::CodeGen::CodeGenFunction::EmitWhileStmt(clang::WhileStmt const&, llvm::ArrayRef<clang::Attr const*>) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x39bb310)
#15 0x00000000039b6eab clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x39b6eab)
#16 0x00000000039bc959 clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x39bc959)
#17 0x0000000003a1b9d3 clang::CodeGen::CodeGenFunction::EmitFunctionBody(clang::Stmt const*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3a1b9d3)
#18 0x0000000003a27c25 clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3a27c25)
#19 0x0000000003a7f2db clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3a7f2db)
#20 0x0000000003a7afe3 clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3a7afe3)
#21 0x0000000003a857c1 clang::CodeGen::CodeGenModule::EmitDeferred() (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3a857c1)
#22 0x0000000003a87c63 clang::CodeGen::CodeGenModule::Release() (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3a87c63)
#23 0x0000000003f1029e (anonymous namespace)::CodeGeneratorImpl::HandleTranslationUnit(clang::ASTContext&) ModuleBuilder.cpp:0:0
#24 0x0000000003f0efac clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3f0efac)
#25 0x0000000005db9b4c clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5db9b4c)
#26 0x0000000003f0e665 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3f0e665)
#27 0x00000000041a3621 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-trunk/bin/clang+++0x41a3621)
#28 0x00000000041299ab clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x41299ab)
#29 0x0000000004286f93 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x4286f93)
#30 0x0000000000c4ce9c cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0xc4ce9c)
#31 0x0000000000c46e4d ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#32 0x0000000003f57529 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#33 0x00000000035f32c3 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x35f32c3)
#34 0x0000000003f57749 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#35 0x0000000003f1dcb7 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3f1dcb7)
#36 0x0000000003f1e66d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3f1e66d)
#37 0x0000000003f2848c clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3f2848c)
#38 0x0000000000c4a301 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0xc4a301)
#39 0x0000000000b2e3e4 main (/opt/compiler-explorer/clang-trunk/bin/clang+++0xb2e3e4)
#40 0x00007f8bb7429d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#41 0x00007f8bb7429e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#42 0x0000000000c469ae _start (/opt/compiler-explorer/clang-trunk/bin/clang+++0xc469ae)
clang++: error: clang frontend command failed with exit code 139 (use -v to see invocation)
Compiler returned: 139
```

**Comment by nyyakko** [comment]
> System: `Windows 10 Pro 21H2`
> 
> Clang++:
> 
> ```
> PS C:\Users\Wellington> clang++ --version
> clang version 18.1.3
> Target: x86_64-pc-windows-msvc
> Thread model: posix
> InstalledDir: C:\Program Files\LLVM\bin
> ```
> 
> Snippet:
> 
> ```c++
> int main()
> {
>     std::string string {};
> 
>     for (auto index = 0zu; index < string.size(); index += 1)
>     {
>         if (string.at(index) == '<')
>         {
>             [&] (this auto self) -> void {
>                 index += 1;
>                 while (string.at(index) != '>')
>                 {
>                     if (string.at(index) == '<')
>                         self();
>                     else
>                     {
>                         index += 1;
>                     }
>                 }
>                 index += 1;
>             }();
>         }
>     }
> }
> ```
> 
> Backtrace (from compiler-explorer because the pre-compiled binary without debug info which doesn't give any meaningful info, see replies):
> 
> ```
> <source>:13:24: error: cannot compile this l-value expression yet
>    13 |                 while (string.at(index) != '>')
>       |                        ^~~~~~~~~
> PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
> Stack dump:
> 0.	Program arguments: /opt/compiler-explorer/clang-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -std=c++23 <source>
> 1.	<eof> parser at end of file
> 2.	Per-file LLVM IR generation
> 3.	<source>:11:13: Generating code for declaration 'main()::(anonymous class)::operator()'
>  #0 0x00000000036ac218 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x36ac218)
>  #1 0x00000000036aa364 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x36aa364)
>  #2 0x00000000035f2e98 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
>  #3 0x00007f8bb7442520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
>  #4 0x0000000003d11827 arrangeFreeFunctionLikeCall(clang::CodeGen::CodeGenTypes&, clang::CodeGen::CodeGenModule&, clang::CodeGen::CallArgList const&, clang::FunctionType const*, unsigned int, bool) CGCall.cpp:0:0
>  #5 0x0000000003dac869 clang::CodeGen::CodeGenFunction::EmitCall(clang::QualType, clang::CodeGen::CGCallee const&, clang::CallExpr const*, clang::CodeGen::ReturnValueSlot, llvm::Value*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3dac869)
>  #6 0x0000000003dae1b7 clang::CodeGen::CodeGenFunction::EmitCallExpr(clang::CallExpr const*, clang::CodeGen::ReturnValueSlot) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3dae1b7)
>  #7 0x0000000003df6fea (anonymous namespace)::ScalarExprEmitter::VisitCallExpr(clang::CallExpr const*) CGExprScalar.cpp:0:0
>  #8 0x0000000003ded321 clang::StmtVisitorBase<std::add_pointer, (anonymous namespace)::ScalarExprEmitter, llvm::Value*>::Visit(clang::Stmt*) CGExprScalar.cpp:0:0
>  #9 0x0000000003dfb888 (anonymous namespace)::ScalarExprEmitter::EmitBinOps(clang::BinaryOperator const*, clang::QualType) CGExprScalar.cpp:0:0
> #10 0x0000000003dfbc9d (anonymous namespace)::ScalarExprEmitter::EmitCompare(clang::BinaryOperator const*, llvm::CmpInst::Predicate, llvm::CmpInst::Predicate, llvm::CmpInst::Predicate, bool) CGExprScalar.cpp:0:0
> #11 0x0000000003deea0c clang::StmtVisitorBase<std::add_pointer, (anonymous namespace)::ScalarExprEmitter, llvm::Value*>::Visit(clang::Stmt*) CGExprScalar.cpp:0:0
> #12 0x0000000003df3072 clang::CodeGen::CodeGenFunction::EmitScalarExpr(clang::Expr const*, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3df3072)
> #13 0x0000000003d91864 clang::CodeGen::CodeGenFunction::EvaluateExprAsBool(clang::Expr const*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3d91864)
> #14 0x00000000039bb310 clang::CodeGen::CodeGenFunction::EmitWhileStmt(clang::WhileStmt const&, llvm::ArrayRef<clang::Attr const*>) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x39bb310)
> #15 0x00000000039b6eab clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x39b6eab)
> #16 0x00000000039bc959 clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x39bc959)
> #17 0x0000000003a1b9d3 clang::CodeGen::CodeGenFunction::EmitFunctionBody(clang::Stmt const*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3a1b9d3)
> #18 0x0000000003a27c25 clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3a27c25)
> #19 0x0000000003a7f2db clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3a7f2db)
> #20 0x0000000003a7afe3 clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3a7afe3)
> #21 0x0000000003a857c1 clang::CodeGen::CodeGenModule::EmitDeferred() (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3a857c1)
> #22 0x0000000003a87c63 clang::CodeGen::CodeGenModule::Release() (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3a87c63)
> #23 0x0000000003f1029e (anonymous namespace)::CodeGeneratorImpl::HandleTranslationUnit(clang::ASTContext&) ModuleBuilder.cpp:0:0
> #24 0x0000000003f0efac clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3f0efac)
> #25 0x0000000005db9b4c clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x5db9b4c)
> #26 0x0000000003f0e665 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3f0e665)
> #27 0x00000000041a3621 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-trunk/bin/clang+++0x41a3621)
> #28 0x00000000041299ab clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x41299ab)
> #29 0x0000000004286f93 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x4286f93)
> #30 0x0000000000c4ce9c cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0xc4ce9c)
> #31 0x0000000000c46e4d ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
> #32 0x0000000003f57529 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
> #33 0x00000000035f32c3 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x35f32c3)
> #34 0x0000000003f57749 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
> #35 0x0000000003f1dcb7 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3f1dcb7)
> #36 0x0000000003f1e66d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3f1e66d)
> #37 0x0000000003f2848c clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3f2848c)
> #38 0x0000000000c4a301 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0xc4a301)
> #39 0x0000000000b2e3e4 main (/opt/compiler-explorer/clang-trunk/bin/clang+++0xb2e3e4)
> #40 0x00007f8bb7429d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
> #41 0x00007f8bb7429e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
> #42 0x0000000000c469ae _start (/opt/compiler-explorer/clang-trunk/bin/clang+++0xc469ae)
> clang++: error: clang frontend command failed with exit code 139 (use -v to see invocation)
> Compiler returned: 139
> ```

here's the link for the code on [godbolt](https://gcc.godbolt.org/z/9TK13WWd8)

and here's the original backtrace emitted from my machine:

```
[1/2] Building CXX object fun/CMakeFiles/fun.dir/source/Main.cpp.obj
FAILED: fun/CMakeFiles/fun.dir/source/Main.cpp.obj
C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE  -IC:/Users/Wellington/Git/fun/fun/include/fun -IC:/Users/Wellington/Git/fun/fun/include -isystem "C:/Program Files (x86)/LibError/include" -O0 -std=gnu++23 -D
_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -g -Xclang -gcodeview -Werror -Wall -Wextra -Wshadow -Wnon-virtual-dtor -Wold-style-cast -Wcast-align -Wunused -Woverloaded-virtual -Wpedanti
c -Wconversion -Wsign-conversion -Wnull-dereference -Wdouble-promotion -Wimplicit-fallthrough -Wno-gnu-statement-expression-from-macro-expansion -Wno-language-extension-token -MD -MT fun/CMakeF
iles/fun.dir/source/Main.cpp.obj -MF fun\CMakeFiles\fun.dir\source\Main.cpp.obj.d -o fun/CMakeFiles/fun.dir/source/Main.cpp.obj -c C:/Users/Wellington/Git/fun/fun/source/Main.cpp
C:/Users/Wellington/Git/fun/fun/source/Main.cpp:37:24: error: cannot compile this l-value expression yet
   37 |                 while (string.at(index) != '>')
      |                        ^~~~~~~~~
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: C:\\PROGRA~1\\LLVM\\bin\\CLANG_~1.EXE -IC:/Users/Wellington/Git/fun/fun/include/fun -IC:/Users/Wellington/Git/fun/fun/include -isystem "C:/Program Files (x86)/LibErro
r/include" -O0 -std=gnu++23 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -g -Xclang -gcodeview -Werror -Wall -Wextra -Wshadow -Wnon-virtual-dtor -Wold-style-cast -Wcast-align -Wunused 
-Woverloaded-virtual -Wpedantic -Wconversion -Wsign-conversion -Wnull-dereference -Wdouble-promotion -Wimplicit-fallthrough -Wno-gnu-statement-expression-from-macro-expansion -Wno-language-exte
nsion-token -MD -MT fun/CMakeFiles/fun.dir/source/Main.cpp.obj -MF fun\\CMakeFiles\\fun.dir\\source\\Main.cpp.obj.d -o fun/CMakeFiles/fun.dir/source/Main.cpp.obj -c C:/Users/Wellington/Git/fun/
fun/source/Main.cpp
1.      <eof> parser at end of file
2.      Per-file LLVM IR generation
3.      C:/Users/Wellington/Git/fun/fun/source/Main.cpp:35:13: Generating code for declaration 'main()::(anonymous class)::operator()'
Exception Code: 0xC0000005
 #0 0x00007ff6ac4a5579 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x1d25579)
 #1 0x00007ff6aa964134 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x1e4134)
 #2 0x00007ff6ac49904b (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x1d1904b)
 #3 0x00007ff6ac49434d (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x1d1434d)
 #4 0x00007ff6aa96b98d (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x1eb98d)
 #5 0x00007ff6ac4946b4 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x1d146b4)
 #6 0x00007ff6ac4940e1 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x1d140e1)
 #7 0x00007ff6aa81034a (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x9034a)
 #8 0x00007ff6aa81c3da (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x9c3da)
 #9 0x00007ff6ac0fa559 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x197a559)
#10 0x00007ff6ac0f9ed7 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x1979ed7)
#11 0x00007ff6ac0f94d1 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x19794d1)
#12 0x00007ff6ac0f5d45 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x1975d45)
#13 0x00007ff6ac0f50e7 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x19750e7)
#14 0x00007ff6ac0f4d06 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x1974d06)
#15 0x00007ff6aaf17ef6 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x797ef6)
#16 0x00007ff6aaf17e54 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x797e54)
#17 0x00007ff6ac83e9eb (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x20be9eb)
#18 0x00007ff6acbfe398 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x247e398)
#19 0x00007ff6aad2c9a1 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x5ac9a1)
#20 0x00007ff6aad2c442 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x5ac442)
#21 0x00007ff6aad29174 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x5a9174)
#22 0x00007ff6aad26cf0 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x5a6cf0)
#23 0x00007ff6aad256be (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x5a56be)
#24 0x00007ff6abaa827d (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x132827d)
#25 0x00007ff6aaeb6e35 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x736e35)
#26 0x00007ff6aaeb6c38 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x736c38)
#27 0x00007ff6aab6abe8 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x3eabe8)
#28 0x00007ff6aab6a59e (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x3ea59e)
#29 0x00007ff6aab6a0b7 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x3ea0b7)
#30 0x00007ff6aab63f47 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x3e3f47)
#31 0x00007ff6aab615c3 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x3e15c3)
#32 0x00007ff6acc840d0 (C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE+0x25040d0)
#33 0x00007ffba2dc7344 (C:\Windows\System32\KERNEL32.DLL+0x17344)
#34 0x00007ffba32c26b1 (C:\Windows\SYSTEM32\ntdll.dll+0x526b1)
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 18.1.3
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\PROGRA~1\LLVM\bin
```

**Comment by erikolofsson** [comment]
Most places I tried to convert to "deducing this" lambdas seem to have this problem.

**Comment by erikolofsson** [comment]
Cherrypicking https://github.com/llvm/llvm-project/pull/84473 and https://github.com/llvm/llvm-project/pull/88428 to `release/18.x` seems to have fixed my issues.
