### ISSUE TITLE
Is there a plan to add handleStmtAttribute to ParsedAttrInfo?

### ISSUE THREAD

**Issue by IuriiKobein** [llvm/llvm-project#87940]
Hello,

Custom attributes is very useful feature that allows extend C++ code with some meta information.
Currently it's not possible to add custom attribute to AST out of the box without changing clang source code.
However for `Decl` it possible to add custom attribute with custom arguments parser using built in attribute kind(Annotate for example).
It possible due to existence of `HandleDeclAttribute` virtual method in `ParsedAttrInfo` class.
However such method is not provided for `Stmt`.

Is there plan to add such interface for Stmt?
Or there some other reasons why it's missed?

**Comment by AaronBallman** [comment]
Support for this was added in 9a97a57d9ee9dbaa4f7ecfdaba565171ea49b7ac
