### ISSUE TITLE
Fatal Error while building LLVM: FAILED Building CXX object tools/mlir/lib/Dialect/LLVMIR/CMakeFiles/obj.MLIRNVVMDialect.dir/IR/NVVMDialect.cpp.o

### ISSUE THREAD

**Issue by AkhilAkkapelli** [llvm/llvm-project#87943]
I am building LLVM in Ubuntu 22.04 LTS by following instructions from [llvm-project/flang/docs/GettingStarted.md at main · llvm/llvm-project (github.com)](https://github.com/llvm/llvm-project/blob/main/flang/docs/GettingStarted.md).

After using ninja command from Building flang in tree method, I am getting fatal error and the build stops.
![f34a77cb-8879-45f8-b751-b900e2bd7343](https://github.com/llvm/llvm-project/assets/41839847/1af66b28-c340-4b29-b1b6-abd44e4b185e)

**Comment by joker-eph** [comment]
Your fatal error says "Killed signal terminated program ..." which is the usual indication that you ran out of memory and the linux kernel kills some of the heavy memory user process.

You may try to reduce the parallelism with the `-j` ninja option.
