### ISSUE TITLE
How to get coverage during the execution of llc ??

### ISSUE THREAD

**Issue by cpython-java** [llvm/llvm-project#87960]
How to capture code coverage during the execution of llc, for example: executing 'llc test_cover.bc -o test_cover.s', how to know which files and code lines in the llc source code are covered during this process?

I know 'lcov' and 'gcov' seem to be able to capture coverage during gcc execution. I'm not sure if they can be used to capture coverage during llc execution. Perhaps there are other tools that can accomplish this?

If someone could help me, I would be extremely grateful  !!!!

**Comment by dtcxzyw** [comment]
1. Make sure that `llvm-cov` and `llvm-profdata` are available.
2. Pass `-DLLVM_BUILD_INSTRUMENTED_COVERAGE=ON -DLLVM_CODE_COVERAGE_TARGETS=llc` to cmake
3. Build the target `generate-coverage-report`.

See also https://llvm.org/docs/CMake.html#llvm-related-variables and https://clang.llvm.org/docs/SourceBasedCodeCoverage.html#collecting-coverage-reports-for-the-llvm-project.

Related file: https://github.com/llvm/llvm-project/blob/73ddb2a7471986a7ed600dbea14efc60f0d0db47/llvm/cmake/modules/CoverageReport.cmake
