### ISSUE TITLE
Arise“relocation truncated to fit: R_RISCV_JAL against `.L13090'” when I cross-compile LLVM for RISC-V on X86

### ISSUE THREAD

**Issue by dinyy** [llvm/llvm-project#87979]
This is my cmake command：
![image](https://github.com/llvm/llvm-project/assets/107465691/29af2d33-fc79-44e1-bc84-f19853f16741)

And my `ToolchainExample.cmake` shows blow：
![image](https://github.com/llvm/llvm-project/assets/107465691/dd3da8e1-08c9-4364-a8ac-7a689acbd9eb)

And the error log when I building is that：
`
FAILED: lib/libclang-cpp.so.19.0git
: && /home/sole/opt/riscv/gcc/bin/riscv64-unknown-linux-gnu-g++ -fPIC -march=rv64gcv -mcmodel=medany - ...
.....
/home/sole/work/qemu_rvv/llvm-project-main/clang/lib/CodeGen/CGBuiltin.cpp:21038:(.text+0x13606a): relocation truncated to fit: R_RISCV_JAL against .L13090'
collect2: error: ld returned 1 exit status
[442/486] Linking CXX static library lib/libclangSerialization.a
ninja: build stopped: subcommand failed.
`
I hava add "-mcmodel=medany" in flag, but it not working.
If my method is wrong，I want to know how to do?

**Comment by dinyy** [comment]
I have upload all command and  logs in this repository：[https://github.com/dinyy/llvm_build_config](https://github.com/dinyy/llvm_build_config)

**Comment by topperc** [comment]
@dinyy did you close this because it's the same as #87127?

**Comment by dinyy** [comment]
> @dinyy did you close this because it's the same as #87127?

I think maybe I shoule try another way.
- LLVM build host: x86_64
- LLVM run host: RISC-V
- Target: RISC-V
I want this kind of LLVM, maybel it's difficult to me.
