### ISSUE TITLE
[SPIRV][HLSL]  Add clamp intrinsic lowering

### ISSUE THREAD

**Issue by farzonl** [llvm/llvm-project#88052]
Add an intrinsic like this one from https://github.com/llvm/llvm-project/blob/cfb86ae7497e43e9221ab890221789ae320381e9/llvm/include/llvm/IR/IntrinsicsDirectX.td#L25C1-L26C118
to 
https://github.com/llvm/llvm-project/blob/1e6ce5e284f5c0e8d64eee21af727bb164eb3caf/llvm/include/llvm/IR/IntrinsicsSPIRV.td#L59

update the clamp.hlsl unit tests:
https://github.com/llvm/llvm-project/blob/1e6ce5e284f5c0e8d64eee21af727bb164eb3caf/clang/test/CodeGenHLSL/builtins/clamp.hlsl

and implement the three `Clamp` Lowering:
https://registry.khronos.org/SPIR-V/specs/1.0/GLSL.std.450.html#FClamp
https://registry.khronos.org/SPIR-V/specs/1.0/GLSL.std.450.html#UClamp
https://registry.khronos.org/SPIR-V/specs/1.0/GLSL.std.450.html#SClamp

**Comment by damyanp** [comment]
Need resolution to #87367.

**Comment by damyanp** [comment]
@bogner  - this work item is specifically about the SPIR-V implementation. Please file an issue to track doing clamp generically if we still want to do that.
