### ISSUE TITLE
[SPIRV][HLSL] Implement `frac` lowering 

### ISSUE THREAD

**Issue by farzonl** [llvm/llvm-project#88059]
- Create a frac intrinsic for spirv use the hlsl intrinsic switching to swap on target.

update the frac.hlsl unit tests:
https://github.com/llvm/llvm-project/blob/1e6ce5e284f5c0e8d64eee21af727bb164eb3caf/clang/test/CodeGenHLSL/builtins/frac.hlsl#L2

example:
https://shader-playground.timjones.io/020254826814c6bfb01e671c08c15db4

and implement the `OpExtInst Fract` Lowering:
`%13 = OpExtInst %v4float %1 Fract %12`
https://registry.khronos.org/SPIR-V/specs/1.0/GLSL.std.450.html#Fract

**Comment by damyanp** [comment]
Need resolution to #87367 before doing this.

**Comment by davidcook-msft** [comment]
Issue to be re-evaluated and updated

**Comment by farzonl** [comment]
@davidcook-msft  this ticket is now just add frac support for spirv. Should just be create a spirv intrinsic use our target switching so hlsl picks the right intrinsic. then update the existing tests and add new spirv backend tests

**Comment by tex3d** [comment]
Sign me up!
