### ISSUE TITLE
[WebAssembly] Question about multiple memories feature support

### ISSUE THREAD

**Issue by BenSunWhiteBoard** [llvm/llvm-project#88094]
I see many related flags are added in [this commit](https://github.com/llvm/llvm-project/commit/86ed8cb8fabe7716b9046317231f861fee5f126a) last year. Is this feature available now? If not, will it be supported or is there any plan to support it in the near future?

Thanks in advance for anyone who take your time answer my newbie question

**Comment by tlively** [comment]
No, it's not implemented yet and I'm not aware of anyone working on this, unfortunately.

**Comment by BenSunWhiteBoard** [comment]
Got it, thanks
