### ISSUE TITLE
Clang frontend crash with deduction guide inside class template

### ISSUE THREAD

**Issue by elbeno** [llvm/llvm-project#88142]
This seems to be a regression from 17 to 18/trunk. 

```cpp
template <typename, typename...>
struct X {
  template <typename>
  struct Y {
    template <typename T>
    Y(T) {}
  };

  template <typename T, typename... Vs>
  Y(T, Vs...) -> Y<T>;
};

using T = X<int>::Y<int>;
```
https://godbolt.org/z/K5d3sWGjP

**Comment by lukevalenty** [comment]
This breaks an Intel open source repo: https://github.com/intel/compile-time-init-build. At least in message.hpp, maybe more.

**Comment by elbeno** [comment]
With assertions: `clang++: /root/llvm-project/clang/lib/Sema/SemaTemplateInstantiate.cpp:2533: clang::QualType {anonymous}::TemplateInstantiator::TransformTemplateTypeParmType(clang::TypeLocBuilder&, clang::TemplateTypeParmTypeLoc, bool): Assertion `Arg.getKind() == TemplateArgument::Type && "Template argument kind mismatch"' failed.`

**Comment by shafik** [comment]
Maybe related: https://github.com/llvm/llvm-project/issues/63823

It does indeed look like a regression introduced between clang-17 and clang-18.

CC @zyn0217 @hokein

**Comment by elbeno** [comment]
Thanks @zyn0217 ! https://github.com/intel/compile-time-init-build is building with clang-18 now.
