### ISSUE TITLE
missed optimization, (x + 0.0) > y => x > y

### ISSUE THREAD

**Issue by zhengyang92** [llvm/llvm-project#88168]
```llvm

define i1 @src(float %n2, float %n3) {
  %n0 = fadd float %n3, 0.000000e+00
  %n1 = fcmp ogt float %n0, %n2
  ret i1 %n1
}


define i1 @tgt(float %n2, float %n3) {
  %n1 = fcmp ogt float %n3, %n2
  ret i1 %n1
}
```

https://alive2.llvm.org/ce/z/wOonbv
https://godbolt.org/z/8Tz7zxP68

found in llm.c (https://github.com/karpathy/llm.c)

@dtcxzyw @regehr

**Comment by dtcxzyw** [comment]
@zhengyang92 Can we simplify `fadd/fsub X, 0.0` into `X` if the result is only used by `fcmp`?

**Comment by zhengyang92** [comment]
@dtcxzyw I think so,

https://alive2.llvm.org/ce/z/AZvvbf , fcmp(fadd) for all preds verifies.
https://alive2.llvm.org/ce/z/Y3fp_f, fcmp(fsub) for all preds verifies as well.

**Comment by vmishelcs** [comment]
Hello, I would like to give this issue a try. This would be my first time attempting to contribute to the main LLVM project :)

**Comment by vmishelcs** [comment]
Hi @zhengyang92 @dtcxzyw, do you have any example PRs that I could take a look at for inspiration on how to tackle this issue?

I've got the `llvm-lit` testing utility working and I ran all of the `Transforms` tests to make sure everything is passing. I assume that I can ignore the tests that are "Expectedly Failed" right?

![image](https://github.com/llvm/llvm-project/assets/43666597/cba44156-2b7e-46a9-b138-25851bb71f7c)

Looking through some of the code, I imagine that I'll probably have to make some changes to the `lib/Transforms/InstCombine/InstCombineCompares.cpp` file to fix this issue?

My plan at the moment is this:
1. Get familiar with how to set up test cases.
2. Create a test case for the missed optimization: (x + 0.0) > y => x > y.
3. Make sure that test case fails with `llvm-lit`.
4. Implement a fix.
5. Make sure the test case now passes.

**Comment by vmishelcs** [comment]
@dtcxzyw Thank you for the link. I read through it today and I am now working on implementing the fix. If I have some questions about my implementation, should I just write here?

**Comment by dtcxzyw** [comment]
> @dtcxzyw Thank you for the link. I read through it today and I am now working on implementing the fix. If I have some questions about my implementation, should I just write here?

Sure!

**Comment by vmishelcs** [comment]
> > @dtcxzyw Thank you for the link. I read through it today and I am now working on implementing the fix. If I have some questions about my implementation, should I just write here?
> 
> Sure!

Should I test each comparison operator? In other words, should I add a separate test case for each of `ugt`, `uge`, `ogt` etc.?

**Comment by arsenm** [comment]
> > > @dtcxzyw Thank you for the link. I read through it today and I am now working on implementing the fix. If I have some questions about my implementation, should I just write here?
> > 
> > 
> > Sure!
> 
> Should I test each comparison operator? In other words, should I add a separate test case for each of `ugt`, `uge`, `ogt` etc.?

Yes, that would be best
