### ISSUE TITLE
add disable condition in `instCombine` pass

### ISSUE THREAD

**Issue by ESI-SYD** [llvm/llvm-project#88222]
### Describe the bug

We may need to disable [instCombine](https://github.com/llvm/llvm-project/blob/main/llvm/lib/Transforms/InstCombine/InstCombineCasts.cpp#L1689) when function is marked with attribute like `strictfp` to avoid unexpected simplification.
In a case, 
```llvm
  %21 = fpext float %15 to double, !dbg !20
  %22 = fpext float %19 to double, !dbg !21
  %23 = fdiv double %21, %22, !dbg !22
  %24 = fptrunc double %23 to float, !dbg !23
```
will be simplified to after this pass.
```llvm
 %16 = fdiv float %10, %14, !dbg !20
```

### To reproduce
Unzip the attachment, [repro.zip](https://github.com/intel/llvm/files/14913127/repro.zip)
apply llvm optimization with
`opt -O3 repro.ll -S -o output.ll`

**Comment by nikic** [comment]
If you use strictfp, you must also use the constrained floating point intrinsics, which will indeed disable such optimizations (https://llvm.org/docs/LangRef.html#constrained-floating-point-intrinsics).
