### ISSUE TITLE
[arm] `VSRI` is included in `mpe`

### ISSUE THREAD

**Issue by Validark** [llvm/llvm-project#88227]
I happened to notice that the `cortex-a9` ISA does not have `mve`, which I care about today because I want to use `vsri`, which currently only resides in `arm.mve.vsri`. 

https://github.com/llvm/llvm-project/blob/b0662a7a7d6d7a4a5339b95d3a20a53390636716/llvm/include/llvm/IR/IntrinsicsARM.td#L1089-L1090

However, according to [this documentation](https://developer.arm.com/documentation/ddi0409/i/instruction-timing/cortex-a9-neon-mpe-instructions?lang=en), the `cortex-a9` has `vsri`, because it (also) exists within `neon mpe`. So LLVM should probably understand that and allow me to use that instruction on that machine unless there is a good reason not to.

Thank you!

**Comment by davemgreen** [comment]
Hi. There is indeed a neon equivalent instruction, that is apparently called llvm.arm.neon.vshiftins.
You can see it here: https://godbolt.org/z/fEz4fhxW4

**Comment by Validark** [comment]
Weird name, but thank you for finding this!

**Comment by davemgreen** [comment]
I agree, I'm not sure why it was named that!

**Comment by Validark** [comment]
@davemgreen I have another question, if you don't mind. Aside from the `VSRI` instruction, I also want the `VSHRN` instruction to be emitted. Unfortunately, LLVM does not appear to be trying to canonicalize the aforementioned arm instructions at all (although it works sometimes on aarch64), so writing polyfills does not get the job done. What is the intrinsic for `VSHRN`? I see the rounding and saturating versions in [llvm-project/llvm/include/llvm/IR/IntrinsicsARM.td](https://github.com/llvm/llvm-project/blob/b0662a7a7d6d7a4a5339b95d3a20a53390636716/llvm/include/llvm/IR/IntrinsicsARM.td), but I don't see a truncating version. And, even for the ones I see, I can't figure out the function signature. If you could please tell me where I would be able to look that information up, I would be much obliged.

**Comment by davemgreen** [comment]
Hi - There is a test for them in llvm/test/CodeGen/ARM/vshrn.ll, which suggests they should be generated from a trunc + shift. https://godbolt.org/z/evzM6xoce

Is that not working for you?

**Comment by Validark** [comment]
I don't think so. This is my first time writing LLVM IR but

```llvm
define i32 @vshrns32(<4 x i16> %tmp1) nounwind {
    %tmp2 = lshr <4 x i16> %tmp1, <i16 4, i16 4, i16 4, i16 4>
    %tmp3 = trunc <4 x i16> %tmp2 to <4 x i8>
    %tmp4 = bitcast <4 x i8> %tmp3 to i32
    ret i32 %tmp4
}
```

gives:

```asm
vshrns32:
        sub     sp, sp, #4
        vshr.u16        d16, d0, #4
        vuzp.8  d16, d17
        vmov.32 r0, d16[0]
        add     sp, sp, #4
        bx      lr
```

https://godbolt.org/z/GenjhsG6b

**Comment by davemgreen** [comment]
Ah I see. It is only dealing with "half" a vector. The compiler could be doing better, but if you want a way to represent this then you could create a large vector from the input: https://godbolt.org/z/3v4ojnGzo.
