### ISSUE TITLE
`__builtin_clz` produces different results if argument is a function call returns 0

### ISSUE THREAD

**Issue by bi6c** [llvm/llvm-project#88234]
```c
#include <stdio.h>
int w;
int s;
int f() {
    return 0;
}
void main() {
  s = __builtin_clz(f());
  w = s && 4;
  printf("The value of s is: %d\n", s); // output: The value of s is: 31
  /***********************/
  w = (s = __builtin_clz(f())) && 4;
  printf("The value of s is: %d\n", s); // output: The value of s is: 30
}
```
Hi, we are using clang to compile in Ubuntu 22.04.4 LTS amd 64.
In the main function, we believe that the assignment to variable `s` would lead variable `s` to have the same value.
This also happens when the function call is replaced to a similar macro function which also returns 0.

**Comment by crosdahl** [comment]
`__builtin_clz()` has undefined return value when passed 0, `__builtin_clzg(f(), 0)` works as you expected. https://clang.llvm.org/docs/LanguageExtensions.html#builtin-clzg-and-builtin-ctzg
