### ISSUE TITLE
[Clang] `-mxros-version-min` does not exist

### ISSUE THREAD

**Issue by madsmtm** [llvm/llvm-project#88271]
Clang allows specifying the deployment target using flags like `-miphoneos-version-min`, `-mtvos-version-min` as documented in the [attribute docs for `availability`](https://clang.llvm.org/docs/AttributeReference.html#availability), but similar functionality is not exposed for xrOS / visionOS.

**Comment by madsmtm** [comment]
Would the proper workaround be to use `-mtargetos=xros1.0`, or does that have other problems?

**Comment by shafik** [comment]
CC @Bigcheese @ldionne

**Comment by ldionne** [comment]
Thanks for the heads up, asking around what to do with this.

**Comment by ributzka** [comment]
> Would the proper workaround be to use -mtargetos=xros1.0, or does that have other problems?
This is not just a workaround - this is now the recommended option. Ideally you use `--target`, but the next best thing after that is the combination of `-arch` and `-mtargetos`.

**Comment by ldionne** [comment]
This looks like NTBF to me, then. I will tentatively close this, please reopen if someone disagrees.
