### ISSUE TITLE
[libc] examples/ s/LIBC_FULLBUILD/LLVM_LIBC_FULL_BUILD/

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#88328]
libc/examples/ mentions `LIBC_FULLBUILD` 3 times. This should be `LLVM_LIBC_FULL_BUILD` instead.

**Comment by medievalghoul** [comment]
I will take this issue if its available, thanks

**Comment by medievalghoul** [comment]
Just curious, do i have to ask to be assign with an issue before submitting a PR? Or can I just submit a PR before asking?

**Comment by michaelrj-google** [comment]
You can just submit a PR before asking.

**Comment by nickdesaulniers** [comment]
@medievalghoul thanks for the interest; it seems that @Rajveer100 [already has a PR out for review](https://github.com/llvm/llvm-project/pull/88657) which has already been accepted.

Take a look at [these issues](https://github.com/llvm/llvm-project/issues?q=is%3Aopen+is%3Aissue+label%3Alibc+label%3A%22good+first+issue%22) for good beginner bugs in libc!
