### ISSUE TITLE
Compiler(19.0.0git) Hangs on Execution without Outputting Compilation Result

### ISSUE THREAD

**Issue by iamanonymouscs** [llvm/llvm-project#88338]
# Command
`clang test.c`
# Code
When utilizing the LLVM compiler (version 19.0.0git), I have encountered a situation where it hangs and fails to generate any compilation output. It is worth noting that I have not encountered a similar issue when using GCC or different versions of LLVM.
```c
static char * name[] = {
    [0x80000000]  = "bar"
  };

```
# Version
`clang --version`
```sh
clang version 19.0.0git (https://github.com/llvm/llvm-project.git 987087df90026605fc8d03ebda5a1cd31b71e609)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```
# Output
```sh
None
```

**Comment by EugeneZelenko** [comment]
See also https://godbolt.org/z/5M8xzrrP7

**Comment by shafik** [comment]
duplicate: https://github.com/llvm/llvm-project/issues/77690
