### ISSUE TITLE
flang-new: forcing arrays to be allocated on the heap and a possible bug

### ISSUE THREAD

**Issue by zaikunzhang** [llvm/llvm-project#88344]
This is related to https://github.com/llvm/llvm-project/issues/56018. 

According to https://github.com/llvm/llvm-project/issues/56018 , `flang -mmlir -fdynamic-heap-array` should force dynamic arrays to be allocated on the heap and hence avoid stackoverflows when large dynamic arrays are present.  The example mentioned at https://github.com/llvm/llvm-project/issues/56018 works but the following does not. 

```fortran
! array.f90

module outprod_mod
contains
function outprod(y, z) result(x)
implicit none
real, intent(in) :: y(:), z(:)
real :: x(size(y), size(z))
integer :: i, j, n, m

m = size(y)
n = size(z)
do i = 1, m
    do j = 1, n
        x(i, j) = y(i) * z(j)
    end do
end do
end function
end module outprod_mod

program prog
use outprod_mod, only : outprod
implicit none

integer, parameter :: k = 10000
integer :: i
real :: y(k)
y = 1.0
do i = 1, k
    write (*, *) i, size(outprod(y(1:i), y(1:i)))
end do
end
```

With flang-new, it crashes with a segfault as follows.

```text
$ uname -a && flang --version && flang -fno-stack-arrays -mmlir -fdynamic-heap-array -o array array.f90 && ./array

Linux 6.5.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
flang-new version 19.0.0git (git@github.com:llvm/llvm-project.git 37c175af955f0aeab67e8c553a0a47b2ed0fdba2)
Target: x86_64-unknown-linux-gnu
Thread model: posix
 ... ...
 1445 2088025
 1446 2090916
 Segmentation fault (core dumped)
```

Questions:

- What are the correct flags to effectively force dynamic arrays to be allocated on the heap? 
- `-fdynamic-heap-array` alone cannot be recognized by the  compiler. It must be `-mmlir -fdynamic-heap-array`. Is this intended?  

Notes: 
- `ulimit -s unlimited` seems to help, but we need a solution on flang's side. 
- Compiled with Classic Flang 15.0.3 without any flags, the code runs fine. 

Thank you for taking a look.

**Comment by rouson** [comment]
@zaikunzhang I don't have a specific answer to your question, but I do have a related question: are you certain that the provided example is standard-conforming?  I'm wondering whether the example might run afoul of Fortran's anti-aliasing rules.  Unfortunately I've frequently heard mention of such rules, but a quick search for "alias" in the standard doesn't take me directly to an articulation of the rules.  Specially, I'm wondering about the line
```
    write (*, *) i, size(outprod(y(1:i), y(1:i)))
```
and I don't recall whether an array section is considered an expression (in which case no aliasing is involved) or not.  I tried compiling the code below with the NAG compiler, which is often a good way to check for standard-conformance:
```
% cat possible-aliasing.f90
program main
  implicit none
  integer, allocatable :: y(:)
  y = [1,2,3]
  call foo(y(1:2),y(1:2))
  print *,y
contains
  subroutine foo(x,z)
    integer, intent(out):: x(:), z(:)
    x = 0
    z = 0
  end subroutine
end program
```
I get the result
```
which yielded the output
```
 0 0 3
```
I interpret this to mean that an array section is *not* an expression, in which case the `call` arguments involve aliasing and the code is presumably not standard-conforming.

Unfortunately I don't have an answer to your specific question.  I just want to be sure that the question is posed in a way that is standard-conforming because that would seem to be a prerequisite for someone providing a helpful answer to your actual question.

**Comment by zaikunzhang** [comment]
Hi, @rouson, I see your concern. I think you are right. 

To avoid this problem, I have revised the code as follows. The problem persists. 

```fortran
! array.f90
!
! Compiled with Classic Flang 15.0.3 without any flags, it runs fine. With flang-new, it crashes
! with a segfault as follows.
!
! $ uname -a && flang --version && flang -fno-stack-arrays -mmlir -fdynamic-heap-array -o array array.f90 && ./array
!Linux 6.5.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
!flang-new version 19.0.0git (git@github.com:llvm/llvm-project.git 37c175af955f0aeab67e8c553a0a47b2ed0fdba2)
!Target: x86_64-unknown-linux-gnu
!Thread model: posix
! ... ...
! 1445 2.088025E+06
! 1446 2.090916E+06
! Segmentation fault (core dumped)

module outprod_mod
contains
function outprod(y, z) result(x)
implicit none
real, intent(in) :: y(:), z(:)
real :: x(size(y), size(z))
integer :: i, j, n, m

m = size(y)
n = size(z)
do i = 1, m
    do j = 1, n
        x(i, j) = y(i) * z(j)
    end do
end do
end function
end module outprod_mod

program prog
use outprod_mod, only : outprod
implicit none

integer, parameter :: k = 10000
integer :: i
real :: y(k), z(k), t
y = 1.0
z = 1.0
do i = 1, k
    t = sum(outprod(y(1:i), z(1:i)))
    write (*, *) i, t
end do
end

```

**Comment by klausler** [comment]
>     write (*, *) i, size(outprod(y(1:i), y(1:i)))

Both of `outprod`'s dummy arguments are `INTENT(IN)` and neither are modified; nor is any variable external to `out prod`.  The program conforms w/r/t the restrictions on dummy arguments that associate with the same effective arguments.  This is pretty basic Fortran.

**Comment by zaikunzhang** [comment]
> >     write (*, *) i, size(outprod(y(1:i), y(1:i)))
> 
> 
> 
> Both of `outprod`'s dummy arguments are `INTENT(IN)` and neither are modified; nor is any variable external to `outprod`.  The program conforms w/r/t the restrictions on dummy arguments that associate with the same effective arguments.  This is pretty basic Fortran.
> 
> 
> 
> EDIT: see F'2023, 15.5.2.14, p1, items (3) & (4), for information on aliasing restrictions for dummy arguments.

Hi @EugeneZelenko ,

Thank you for your comments. So both versions of the code is conforming. How should we deal with the segfault ? 

Thank you.

Zaikun

**Comment by jeanPerier** [comment]
Hi @zaikunzhang

With https://github.com/llvm/llvm-project/pull/98457 that was merged, your example now works with `-mmlir -fdynamic-heap-array`.

Regarding your question about the flag names:

> What are the correct flags to effectively force dynamic arrays to be allocated on the heap?

Currently `-mmlir -fdynamic-heap-array` is indeed the only way to get the behavior you want. This is because it was experimental and hence not properly advertised as an official flag. I think we may want to reconsider that now.

> Compiled with Classic Flang 15.0.3 without any flags, the code runs fine.

That is right, but if you test with ifort/ifx without any flags, you will also get a segfault without unlimited stack. There is no silver bullet regarding what people want (performance or low stack usage).
