### ISSUE TITLE
[InstCombine] Regard `zext nneg` as `sext` when folding `add(zext neg(add))`

### ISSUE THREAD

**Issue by DianQK** [llvm/llvm-project#88348]
The following transformation is legal after adding `nneg`:

```llvm
define i32 @src(i8 %v) {
  %switch.tableidx = add nsw i8 %v, 1
  %switch.idx.cast = zext nneg i8 %switch.tableidx to i32
  %switch.offset = add nsw i32 %switch.idx.cast, -1
  ret i32 %switch.offset
}

define i32 @tgt(i8 %v) {
  %ext = sext i8 %v to i32
  ret i32 %ext
}
```

Alive2: https://alive2.llvm.org/ce/z/2iCmDs
From: https://github.com/rust-lang/rust/issues/106459#issuecomment-1925647607

**Comment by XChy** [comment]
Should be easy to fix in:
https://github.com/llvm/llvm-project/blob/efb8cc5ddb03897795dc153a03d0c1548c8ee4a7/llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp#L830

**Comment by ZelinMa557** [comment]
Can I work on this issue? I'm glad to try it :)
