### ISSUE TITLE
Bus error on Loop::getTripCount if getAnalysis<LoopInfo> is called twice

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#8835]
|  |  |
| --- | --- |
| Bugzilla Link | [8463](https://llvm.org/bz8463) |
| Version | 2.8 |
| OS | MacOS X |
| Attachments | [Test case to reproduce crash; run on bitcode containing a loop](https://user-images.githubusercontent.com/60944935/143742181-138ebc65-0545-4aae-bc7f-aa40ebc61e85.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

The following sequence of events triggers a crash in an LLVM pass:

1. Call getAnalysis<LoopInfo>
2. Identify a Loop block
3. Call getAnalysis<LoopInfo> again
4. Call getTripCount on the Loop block

If step 3 is omitted, the crash does not occur.

The attached test case reproduces the problem. It is a drop-in replacement for the Hello example, so you should be able to overwrite your own Hello and run the pass as you normally would. Of course, the bitcode that you analyze must contain a loop, something as simple as:

void foo() {
    for (int i = 0; i < 10; i++);
}

Note that the test case is a ModulePass because I could not reproduce the problem as a FunctionPass.

**Comment by arsenm** [comment]
Old pass manager
