### ISSUE TITLE
[SystemZ] No compile time error returned for vector double _Complex type

### ISSUE THREAD

**Issue by bahareh-farhadi** [llvm/llvm-project#88399]
The test expects a compile time error when a `vector double _Complex` variable is declared; however, no error is returned. 
According to the supported vector data types listed in [https://www.ibm.com/docs/en/zos/2.5.0?topic=support-vector-data-types](https://www.ibm.com/docs/en/zos/2.5.0?topic=support-vector-data-types) `vector double _Complex` is not supported, so a compile time error is expected. 

**Test case:**
```
$ cat t.c
 
double _Complex b;
 
int main()
{
    vector double _Complex a = {b};
}
```
**Command to reproduce the actual behaviour:**
```
$ clang -mvx -mzvector  t.c
$ echo $?
0
```
**GCC returns a compile time error as expected:**
```
$ gcc -mvx -mzvector t.c
t.c: In function ‘main’:
t.c:5:5: error: invalid vector type for attribute ‘vector_size’
    5 |     vector double _Complex a = {b};
      |     ^~~~~~
```

**Comment by uweigand** [comment]
Confirmed.  Note that this also happens for "vector float _Complex".
