### ISSUE TITLE
[coroutines] clang fails to run trivial ABI destructors when a suspended coroutine is destroyed

### ISSUE THREAD

**Issue by jacobsa** [llvm/llvm-project#88478]
Here's a small program containing a coroutine (`Foo`) that starts to evaluate a function call expression but then destroys itself before actually making the function call:

```c++
#include <coroutine>
#include <cstdlib>
#include <iostream>

struct DestroySelfTag {};

// An eager coroutine result type that supports awaiting DestroySelf to
// cause the promise to destroy the coroutine frame.
struct MyTask {
  struct promise_type {
    MyTask get_return_object() { return {}; }
    std::suspend_never initial_suspend() { return {}; }
    std::suspend_always final_suspend() noexcept { return {}; }
    void unhandled_exception();
    void return_void();

    auto await_transform(DestroySelfTag) {
      struct Awaiter {
        bool await_ready() { return false; }
        void await_suspend(const std::coroutine_handle<> h) { h.destroy(); }

        int await_resume() {
          // We should never resume; we destroyed ourselves just after
          // suspending.
          std::abort();
        }
      };

      return Awaiter{};
    }
  };
};

// A trivial ABI type that lets us know when it's created and destroyed.
struct HasDestructor {
  HasDestructor() { std::cout << "created:   " << this << "\n"; }
  ~HasDestructor() { std::cout << "destroyed: " << this << "\n"; }
};

// A function that we have a call expression for below in Foo. This just
// needs to accept the right types -- it should never actually be called.
void AcceptArgs(HasDestructor, int, HasDestructor) { std::abort(); }

// A coroutine that creates a HasDestructor object then destroys itself
// before doing anything with it.
MyTask Foo() {
  AcceptArgs(HasDestructor(), co_await DestroySelfTag(), HasDestructor());
  std::abort();
}

int main() {
  Foo();
  return 0;
}
```

When compiled with `-std=c++20 -O2 -fno-exceptions` ([Compiler Explorer](https://godbolt.org/z/bzG8xsMM9)), the program works as expected. It creates one `HasDestructor` object, then destroys it again when `std::coroutine_handle::destroy` is called:

```
created:   0x7ffd04aa2b6a
destroyed: 0x7ffd04aa2b6a
```

However, the program is miscompiled when we put the `[[clang::trivial_abi]]` attribute on `HasDestructor` ([Compiler Explorer](https://godbolt.org/z/fPxn5jE5b)). In this case we fail to run the destructor, creating but then not ever destroying the `HasDestructor` object:

```
created:   0x7fff8f4da6b2
```

It doesn't seem like this should happen. There isn't extremely rigorous documentation on the semantics of `[[clang::trivial_abi]]`, but [what does exist](https://clang.llvm.org/docs/AttributeReference.html#trivial-abi) says "the convention is that the callee will destroy the object before returning". That makes sense, but _there is no function call here_. `AcceptArgs` is never actually called. Instead this should be treated the same as the following, which [does work correctly](https://godbolt.org/z/fe8EY9KM1):

```c++
MyTask Foo() {
  HasDestructor(), co_await DestroySelfTag();
  std::abort();
}
```

In a real codebase this bug could cause resources to be leaked when a coroutine is stopped early, e.g. due to cancellation.

**Comment by usx95** [comment]
Reproduces with early exit in statement expression. So this is very likely an edge case of https://github.com/llvm/llvm-project/issues/63818.
The fact that it works with exceptions is reassuring. I will take a look at it.

```cpp
void Foo() {
    AcceptArgs(HasDestructor(), ({return; 0;}), HasDestructor());
}
```
[compiler explorer](https://godbolt.org/z/EhcGE9haP)

**Comment by rnk** [comment]
> The fact that it works with exceptions is reassuring. 

I agree, that is reassuring. I was going to say that's the case we need to check. There are a few places like this where clang has a scheme to push EH-only cleanups, and then disable or pop them off the stack after the call transferring ownership occurs, which seems related.

**Comment by usx95** [comment]
Sent out fix: https://github.com/llvm/llvm-project/pull/88751

**Comment by usx95** [comment]
(the primary commit for stmt-expr cleanups was reverted)

**Comment by Alcaro** [comment]
For those wondering, the revert is https://github.com/llvm/llvm-project/pull/88884 (which also reverts https://github.com/llvm/llvm-project/issues/63818 )

**Comment by usx95** [comment]
Updated PR: https://github.com/llvm/llvm-project/pull/89154
