### ISSUE TITLE
No way to disable -Wcast-align, with -Wno-cast-align

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#8848]
|  |  |
| --- | --- |
| Bugzilla Link | [8476](https://llvm.org/bz8476) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @seanm |

## Extended Description 
clang version r117443 built from SVN today has this bug, its been in clang for a number of weeks at least.

I have a project which generates lots of cast allign warnings even though I have 
 -Wno-cast-align in my CFLAGS and CXXFLAGS eg:

/data/src/blender/blender/source/blender/blenkernel/intern/texture.c:1065:9: warning: cast from 'char *' to 'short *' increases required alignment from 1 to 2 [-Wcast-align]
        switch(GS(id->name)) {
               ^~~~~~~~~~~~
In file included from /data/src/blender/blender/source/blender/blenkernel/intern/texture.c:59:
/data/src/blender/blender/source/blender/blenkernel/./BKE_utildefines.h:223:18: note: instantiated from:
#define GS(a)   (*((short *)(a)))
                   ^~~~~~~~~~~~

**Comment by philnik777** [comment]
This doesn't happen in trunk: https://godbolt.org/z/GfKo5e8cx
