### ISSUE TITLE
[libclc] [trunk] unable to open output file obj.libclc.dir/tahiti-amdgcn--/generic/lib/workitem/get_global_id.cl.o': 'No such file or directory'

### ISSUE THREAD

**Issue by LW-archlinux** [llvm/llvm-project#88626]
llvm trunk rev 72f9881c3ffcf4be6361c3e4312d91c9c8d94a98

First I build a binary containg llvm, compiler-rt;clang-tools-extra & clang trunk versions.
Then I built spirv-llvm-translator trunk against that binary.

Finally libclc is built against both binaries .

#87622 breaks this way of building libclc .

```
[  1%] Generating obj.libclc.dir/tahiti-amdgcn--/generic/lib/workitem/get_global_id.cl.o
error: unable to open output file '/home/panoramix/Documents/Aur/pkgbuilds/libclc-minimal-git/src/_build/obj.libclc.dir/tahiti-amdgcn--/generic/lib/workitem/get_global_id.cl.o': 'No such file or directory'
```

[libclc-minimal-git-19.0.0_r495404.72f9881c3ffc-1-x86_64-build.log](https://github.com/llvm/llvm-project/files/14967775/libclc-minimal-git-19.0.0_r495404.72f9881c3ffc-1-x86_64-build.log)

**Comment by LW-archlinux** [comment]
rev 6f7160eedb2d . error message has changed, but failure hasn't .

[libclc-minimal-git-19.0.0_r496020.6f7160eedb2d-1-x86_64-build.log](https://github.com/llvm/llvm-project/files/15015726/libclc-minimal-git-19.0.0_r496020.6f7160eedb2d-1-x86_64-build.log)

Pinging @frasercrmck , the author of the MR and the later libclc commits to get their attention .

**Comment by frasercrmck** [comment]
Hi, thanks for pinging me. Sorry about this.

I can't tell what's going wrong. Would you be able to paste your cmake invocation(s), perhaps? It doesn't look like it's anything to do with SPIRV-LLVM-Translator.

Maybe it's Unix Makefiles? I'll take a look.

**Comment by frasercrmck** [comment]
Yes it looks like I've broken the build with Unix Makefiles - sorry. The Ninja generator will probably work for you but I'll see if there's something I can do quickly. Else we can revert if it's going to take longer.
