### ISSUE TITLE
`#pragma GCC unroll 0` not allowed: `invalid value '0'; must be positive`

### ISSUE THREAD

**Issue by MonsterDruide1** [llvm/llvm-project#88624]
`#pragma GCC unroll 0` does not compile, as apparently the specified number needs to be positive.

```
/app/main.cpp:4:24: error: invalid value '0'; must be positive
    4 |     #pragma GCC unroll 0
      |                        ^
1 error generated.
```

However, from <https://gcc.gnu.org/onlinedocs/gcc/Loop-Specific-Pragmas.html>:
> The values of 0 and 1 block any unrolling of the loop.

The program also successfully compiles with GCC, only `clang` seems to have this implemented incorrectly.

Godbolt: https://godbolt.org/z/bEPo64GsP

**Comment by MonsterDruide1** [comment]
Additional info from discussion on Discord:
- There is a test to check for the error on `0`: https://github.com/llvm/llvm-project/blob/26852565a5f609e6b466f43c2f690ce3047d04c7/clang/test/Parser/pragma-unroll.cpp#L43-L44
- The check is implemented here: https://github.com/llvm/llvm-project/blob/26852565a5f609e6b466f43c2f690ce3047d04c7/clang/lib/Sema/SemaExpr.cpp#L3903
- This behaviour does not seem to have changed over time, as at the time of the first release with this pragma (8.1, see [changelog](https://gcc.gnu.org/gcc-8/changes.html)) the documentation already allows `0` as value: https://web.archive.org/web/20180331074143/http://gcc.gnu.org/onlinedocs/gcc/Loop-Specific-Pragmas.html

**Comment by yronglin** [comment]
We have a check here https://github.com/llvm/llvm-project/blob/26852565a5f609e6b466f43c2f690ce3047d04c7/clang/lib/Sema/SemaExpr.cpp#L3903, it only allows strictly positive integer.

**Comment by shafik** [comment]
If we look at c724a83e2054d where this change was implemented it looks like the behavior did not change.

**Comment by yronglin** [comment]
I've a PR to fix this issue https://github.com/llvm/llvm-project/pull/88666 .

**Comment by MonsterDruide1** [comment]
Great, thanks for handling it @yronglin !
