### ISSUE TITLE
import of module 'std' imported non C++20 importable modules

### ISSUE THREAD

**Issue by TheRustifyer** [llvm/llvm-project#88652]
Building a project on a `GitHub` virtual machine with `llvm-18`, I found the following build error:

```
test test_clang_full_process ... [2024-04-14T09:23:44Z DEBUG zork::utils::reader] Searching for Zork++ configuration files...
[2024-04-14T09:23:44Z TRACE zork::worker] Config files found: ["/tmp/.tmpXI187w/clang_example/zork_clang.toml"]
[2024-04-14T09:23:44Z INFO  zork::compiler] Building the module interfaces and partitions...
[2024-04-14T09:23:44Z INFO  zork::compiler] Building the module implementations...
[2024-04-14T09:23:44Z INFO  zork::compiler] Building the source files...
[2024-04-14T09:23:44Z INFO  zork::compiler] Generating the main command line...
[2024-04-14T09:23:44Z INFO  zork::cli::output::commands] Proceeding to execute the generated commands...
[2024-04-14T09:23:44Z TRACE zork::cli::output::commands] [clang] - Executing command => "clang++ -std=c++2b -stdlib=libc++ -fimplicit-modules -x c++-module --precompile -fimplicit-module-maps -fprebuilt-module-path=/tmp/.tmpXI187w/out/clang/modules/interfaces -o /tmp/.tmpXI187w/out/clang/modules/interfaces/math.pcm /tmp/.tmpXI187w/clang_example/ifc/math.cppm"
[2024-04-14T09:23:44Z TRACE zork::cli::output::commands] [clang] - Executing command => "clang++ -std=c++2b -stdlib=libc++ -fimplicit-modules -c -fimplicit-module-maps -o /tmp/.tmpXI187w/out/clang/modules/implementations/math.o -fmodule-file=/tmp/.tmpXI187w/out/clang/modules/interfaces/math.pcm /tmp/.tmpXI187w/clang_example/src/math.cpp"
warning: the form '-fmodule-file=<BMI-path>' is deprecated for standard C++ named modules;consider to use '-fmodule-file=<module-name>=<BMI-path>' instead [-Weager-load-cxx-named-modules]
1 warning generated.
[2024-04-14T09:23:44Z TRACE zork::cli::output::commands] [clang] - Executing command => "clang++ -std=c++2b -stdlib=libc++ -fimplicit-modules -c -fimplicit-module-maps -o /tmp/.tmpXI187w/out/clang/modules/implementations/math2.o -fmodule-file=/tmp/.tmpXI187w/out/clang/modules/interfaces/math.pcm /tmp/.tmpXI187w/clang_example/src/math2.cpp"
warning: the form '-fmodule-file=<BMI-path>' is deprecated for standard C++ named modules;consider to use '-fmodule-file=<module-name>=<BMI-path>' instead [-Weager-load-cxx-named-modules]
1 warning generated.
[2024-04-14T09:23:44Z TRACE zork::cli::output::commands] [clang] - Executing command => "clang++ -std=c++2b -c -stdlib=libc++ -fimplicit-modules -fimplicit-module-maps -fprebuilt-module-path=/tmp/.tmpXI187w/out/clang/modules/interfaces -o /tmp/.tmpXI187w/out/clang/sources/main.o /tmp/.tmpXI187w/clang_example/main.cpp"
/tmp/.tmpXI187w/clang_example/main.cpp:5:5: error: import of module 'std' imported non C++20 importable modules
    5 |     import std;
      |     ^
```

I can confirm that such code and build flags works on `Clang 15`, `Clang 16` and `Clang 17`.

Tell me if I can provide more details in any form

**Comment by Endilll** [comment]
Can you provide a minimal reproducer?
CC @ChuanqiXu9

**Comment by TheRustifyer** [comment]
> Can you provide a minimal reproducer? CC @ChuanqiXu9

Are you open to download a release of `Zork++`?

Then it will be super easy, since all the cmd args and flags that are used to build the project are autogenerated, as well as a template that will give you a minimal reproducible example with a couple of commands.

Tell me if you can do it and I can provide you some guidance (if required)

**Comment by Endilll** [comment]
We need something small to reproduce the issue, and put it into our test suite if it's confirmed.
Ideally we need something small and self-contained that can be put inside Compiler Explorer.

**Comment by TheRustifyer** [comment]
> We need something small to reproduce the issue, and put it into our test suite if it's confirmed. Ideally we need something small and self-contained that can be put inside Compiler Explorer.

I am not a proficent user of `compiler explorer`. 
That's the far the minimal reproducible example that I can give you that it should trigger the same error:

https://godbolt.org/z/e1bfTbesh

But I am unable to pass the same compiler flags generated by `Zork++` to build a modules project. Well, I mean, I am unable to make them work, since it generates a command line order per file.

I left the generated commands in a pane within compiler explorer.

Are you guys able to fix it? It should be only to correctly how the arguments are passed to the `CE` compiler

**Comment by poyaoc97** [comment]
The arguments passed to Clang don't make sense. Have you read https://libcxx.llvm.org/Modules.html and https://clang.llvm.org/docs/StandardCPlusPlusModules.html?

**Comment by TheRustifyer** [comment]
> The arguments passed to Clang don't make sense. Have you read https://libcxx.llvm.org/Modules.html and https://clang.llvm.org/docs/StandardCPlusPlusModules.html?

Sure. I read both, and from a long time ago I've been reading their updates.
The commands are generated by a custom built system that started in 2021.

In any case, I am able to successfully compile the provided code with `Clang 15-16-17`.

So I would be glad if you could provide any better and/or further explanation rather than just: 

> `The arguments passed to Clang don't make sense`

Some notes that could help to clarify things:

- The issue is first spot in my local dev environment. And the same in the `GitHub` actions as stated.
- This issue arise from `clang-18` onwards
- The way of how this issue is reproduced is trying to develop a [build system](https://github.com/zerodaycode/Zork)
- We were able to compile `C++ standard modules` based projects up until `v17` included, even I suppose that it could just be thanks to the *modulemap* feature? (asking)
- Following the previous point, we follow the documentation [here](https://libcxx.llvm.org/Modules.html) in their previous revisions when we was develop the application in previous iterations (and some time ago, btw)
- From `Clang 18`, we already saw such documentation and saw the `CMake` script that should be used to build `std` and `std.compat`. But as you may guess, that's not a viable solution for us.

So the thing is that is just a *compiler flags* issue? Should we change our workflows from `Clang 18`?

There's no way to invoke `Clang` to build the modular `std` library? That could be an option for us. I already asked on *Discord* some time ago, and I was invoked to the same documentation that you provided.

At the end of the day, I assumed that `CMake` should do certain actions to build the `std` and make it available.

So I am pretty sure that I am totally wrong, and I am doing things wrong. So I just would like to have some guidance to spot what we're missing.

NOTE: I already tried in my local environment to convert the `-DLIBCXX_BUILD=<build>` in some compiler flag to invoke directly via the command line to test different approaches based on the new documentation, but the error is exactly the same. But in this case, I tried with a fresh installation of the `llvm` suite from the last commit on main, with the exact same flags that are provided in the documentation.

Thanks for the time spent to all the people who is commenting in this issue.

**Comment by ChuanqiXu9** [comment]
The problem should be that the compiler saw `import std;` which should a C++20 standard form module, but actually find Clang Header Module extensions. (which generally is a Objective C extension actually) This is a big mismatch and inconsistent. Such inconsistent is definitely not wanted. So we banned this in clang18. This behavior change here is not a regression since the things it banned was not well defined.

> We were able to compile C++ standard modules based projects up until v17 included, even I suppose that it could just be thanks to the modulemap feature? (asking)

No, since the things you tried to compile is the Clang Header Module extensions, not the standard C++ modules.

> There's no way to invoke Clang to build the modular std library? 

We need the involvement of standard library: https://libcxx.llvm.org/Modules.html

> So the thing is that is just a compiler flags issue? Should we change our workflows from Clang 18?

The problem is that you tried to mix the standard modules and the extensions. It is a deep dark corner. We don't intend to change behaviors suddenly. But it should be better to break something bad early instead of being late.

---

BTW, if someday we want to import clang header modules via names, we can we do, maybe we should introduce a new syntax:

```
@import std;
```

**Comment by ChuanqiXu9** [comment]
Given this doesn't break things wanted, I'd like to close this as not planned. Thanks for looking into it.
