### ISSUE TITLE
Assertion `getScaleH() == getScaleW()' failed.

### ISSUE THREAD

**Issue by hongtaofly** [llvm/llvm-project#88683]
使用tpu-mlir进行模型转换报错tpuc-opt: /workspace/tpu-mlir/lib/Dialect/Tpu/Interfaces/BM1684X/Upsample.cpp:20: void tpu_mlir::tpu::UpsampleOp::codegen_global_bm1684x(): Assertion `getScaleH() == getScaleW()' failed.；所转换模型的shape为[1,3,32,128],请问是什么原因呢？原先也可以成功转换[1,3,448,768]的模型

**Comment by dtcxzyw** [comment]
Please file this issue to the downstream repo https://github.com/sophgo/tpu-mlir.
