### ISSUE TITLE
Clang drops variable, keeps it when referenced by __asm__

### ISSUE THREAD

**Issue by Midar** [llvm/llvm-project#88706]
Attached is the preprocessed source. In the bad file, at the line 11882, `pool` only contains garbage at the end. In the one with the workaround, which references `pool` via an empty `__asm__` block, `pool` has the correct value. Looking at the disassembly, with the workaround Clang is reserving more space on the stack and no other change.

I think Clang falsely thinks the variable isn't being used anymore and reuses the stack space without the `__asm__` block.

Tested with Clang 13, 15, 17 and 18 on OpenIndiana, and they all exhibit this behavior.
Could not reproduce this on any other OS.

[preprocessed-bad.txt](https://github.com/llvm/llvm-project/files/14977057/preprocessed-bad.txt)
[preprocessed-workaround.txt](https://github.com/llvm/llvm-project/files/14977059/preprocessed-workaround.txt)

See openindiana/oi-userland#16894

**Comment by DimitryAndric** [comment]
I'm not an Objective-C expert by any means, but as far as I can see, `pool` is not used at all in the function you are referring to? I.e. it is 'allocated' at line 11800, released at line 11882, but never referenced anywhere else:

```c
 11798  - (void)createDirectoryAtIRI: (OFIRI *)IRI
 11799  {
 11800   void *pool = objc_autoreleasePoolPush();
...
 11882   objc_autoreleasePoolPop(pool);
 11883
 11884   return IRIs;
 11885  }
```

It is possible that clang knows about `objc_autoreleasePoolPush` and `objc_autoreleasePoolPop` similar to `malloc` and `free`, and considers them no-ops if you don't do anything with the returned object?

**Comment by Midar** [comment]
Yes, they are never referenced because all objects being created are automatically added to the topmost pool. It's a form of garbage collection.

Basically, `objc_autoreleasePoolPush()` returns a pool and all objects created after this automatically get added to this pool. When `objc_autoreleasePoolPop(pool)` gets called, all objects stored in this pool are released.

**Comment by shafik** [comment]
CC @Bigcheese @rjmccall

**Comment by Midar** [comment]
Agreed on this extremely unlikely being Objective-C related, other than maybe exceptions getting the compiler confused (which at least with GCC is a common thing).

My first idea was also memory corruption, however, all these turned up nothing:

* valgrind only complains on the pop being an invalid read -- which is correct, as a that point, pool is garbage.
* -fsanitize=undefined only finds a bunch of NULL passed to memcpy and memcmp
* -fsanitize=address doesn't seem to work on OpenIndiana
* Switching from readdir_r to readdir made no difference

**Comment by rjmccall** [comment]
I don't see anything wrong with `pool`.  It's initialized at the start of the function and then used later, at a point dominated by the initialization.  What exactly is the valgrind complaint?

**Comment by Midar** [comment]
`pool` just becomes random garbage by the end of the function without the `__asm__` block. Valgrind then complains about the inside of `objc_autoreleasePoolPop` accessing invalid memory as a result of the garbage value.

**Comment by rjmccall** [comment]
Again, the asm block is probably just perturbing the stack layout, e.g. by making the compiler save the value in the locals area instead of as a spill.  If there's only a small amount of stack corruption, it's quite possible that that's enough to hide the bug in practice.

Given that the bug only happens with OpenIndiana, you are going to have to take the lead on debugging it.  I can try to walk you through it, though.  Please provide some more basic information about the bug:
- What architecture are you running on?  Wikipedia says OpenIndiana supports both x86_64 and SPARC.
- What command line are you using?  Does the bug only reproduce with optimization enabled?  Are there any interesting flags you're using?
- Are you able to reproduce the crash in a debugger?
- Can you provide assembly for the function?

**Comment by Midar** [comment]
* This happens on x86_64 (-m64), but i386 (-m32) has a similar crash.
* The full command line is `clang -fPIC -DPIC -g -O2 -Wall -fexceptions -fobjc-exceptions -funwind-tables -fconstant-string-class=OFConstantString -std=gnu11 -pipe -fno-common -Xclang -fno-constant-cfstrings -Wsign-compare -Wshadow -Wshorten-64-to-32 -Wundeclared-selector -Wsemicolon-before-method-body -Wobjc-missing-property-synthesis -Wmissing-method-return-type -Xclang -fobjc-runtime=objfw -Xclang -fblocks -Wwrite-strings -Wpointer-arith -Werror -Wcast-align -Wunreachable-code -Wdocumentation -pedantic -Wno-gnu-imaginary-constant -D__EXTENSIONS__ -D_POSIX_PTHREAD_SEMANTICS   -DOF_COMPILING_OBJFW -Wp,-pthread -I. -I.. -Iexceptions -Iruntime -MD -MF OFFileIRIHandler.lib.dep -c -o OFFileIRIHandler.lib.o OFFileIRIHandler.m
`. It happens with all optimization levels, from -O0 to -O2, however, with -O0 pool doesn't get corrupted, but instead the file name.
* Yes, easily reproduces is gdb.
* Assembly attached, with and without asm block (both generated without -g to reduce noise).

While there is a certain pattern of all of these being around readdir_r, there are no issues when using GCC.

[broken.s.txt](https://github.com/llvm/llvm-project/files/14984524/broken.s.txt)
[workaround.s.txt](https://github.com/llvm/llvm-project/files/14984527/workaround.s.txt)

Assembly diff between both (as it's rather short):
```diff
--- broken.s.txt	2024-04-15 23:37:01.768508081 +0200
+++ workaround.s.txt	2024-04-15 23:38:10.508593836 +0200
@@ -2156,7 +2156,7 @@
 	callq	*%rax
 	movq	%rax, %r15
 	callq	objc_autoreleasePoolPush@PLT
-	movq	%rax, -80(%rbp)                 # 8-byte Spill
+	movq	%rax, -56(%rbp)                 # 8-byte Spill
 	testq	%r14, %r14
 	je	.LBB12_33
 # %bb.1:
@@ -2171,7 +2171,7 @@
 	movq	__objc_ivar_offset_OFIRIHandler._scheme@GOTPCREL(%rip), %rax
 	movq	(%rax), %rax
 	movl	(%rax), %eax
-	movq	%r12, -72(%rbp)                 # 8-byte Spill
+	movq	%r12, -80(%rbp)                 # 8-byte Spill
 	movq	(%r12,%rax), %r12
 	leaq	.objc_selector_list+448(%rip), %r13
 	movq	%rbx, %rdi
@@ -2216,6 +2216,9 @@
 	je	.LBB12_34
 # %bb.3:
 	movq	%rax, %r13
+	movq	-56(%rbp), %rax                 # 8-byte Reload
+	#APP
+	#NO_APP
                                         # implicit-def: $rax
                                         # kill: killed $rax
 	.p2align	4, 0x90
@@ -2223,14 +2226,14 @@
 .Ltmp67:
 	movq	%r13, %rdi
 	leaq	-104(%rbp), %rsi
-	leaq	-56(%rbp), %rdx
+	leaq	-64(%rbp), %rdx
 	callq	readdir_r@PLT
 .Ltmp68:
 # %bb.5:                                #   in Loop: Header=BB12_4 Depth=1
 	testl	%eax, %eax
 	jne	.LBB12_6
 # %bb.11:                               #   in Loop: Header=BB12_4 Depth=1
-	movq	-56(%rbp), %rbx
+	movq	-64(%rbp), %rbx
 	testq	%rbx, %rbx
 	je	.LBB12_32
 # %bb.12:                               #   in Loop: Header=BB12_4 Depth=1
@@ -2260,7 +2263,7 @@
 .Ltmp80:
 # %bb.16:                               #   in Loop: Header=BB12_4 Depth=1
 	movq	%rax, %r12
-	movq	-56(%rbp), %rbx
+	movq	-64(%rbp), %rbx
 .Ltmp81:
 	movq	%rax, %rdi
 	leaq	.objc_selector_list+688(%rip), %rsi
@@ -2323,7 +2326,7 @@
 	jmp	.LBB12_26
 .LBB12_28:                              #   in Loop: Header=BB12_4 Depth=1
 .Ltmp93:
-	movq	%rax, -64(%rbp)                 # 8-byte Spill
+	movq	%rax, -72(%rbp)                 # 8-byte Spill
 	movb	$1, %bl
 	jmp	.LBB12_23
 .LBB12_32:
@@ -2336,7 +2339,7 @@
 	movq	%r15, %rdi
 	movq	%rbx, %rsi
 	callq	*%rax
-	movq	-80(%rbp), %rdi                 # 8-byte Reload
+	movq	-56(%rbp), %rdi                 # 8-byte Reload
 	callq	objc_autoreleasePoolPop@PLT
 	movq	%r15, %rax
 	addq	$72, %rsp
@@ -2365,7 +2368,7 @@
 .Ltmp73:
 	movq	_OBJC_CLASS_OFReadFailedException@GOTPCREL(%rip), %rdi
 	leaq	.objc_selector_list+624(%rip), %rsi
-	movq	-72(%rbp), %rdx                 # 8-byte Reload
+	movq	-80(%rbp), %rdx                 # 8-byte Reload
 	xorl	%ecx, %ecx
 	movl	%ebx, %r8d
 	callq	*%rax
@@ -2378,7 +2381,7 @@
 # %bb.10:
 .LBB12_26:
 .Ltmp99:
-	movq	-64(%rbp), %rdi                 # 8-byte Reload
+	movq	-72(%rbp), %rdi                 # 8-byte Reload
 	callq	objc_exception_throw@PLT
 .Ltmp100:
 # %bb.27:
```

**Comment by rjmccall** [comment]
Yep, that's textbook perturbing the stack layout.

Bad version:
```
  -0: saved %rbp
  -8: saved %r15
 -16: saved %r14
 -24: saved %r13
 -32: saved %r12
 -40: saved %rbx
 -56: struct dirent *dirent;
 -64: unwind exception pointer (spill)
 -72: self (spill, in one place; also kept in %r12)
 -80: pool (spill)
-104: struct dirent buffer;
-112: (bottom of frame)
```

Good version:
```
  -0: saved %rbp
  -8: saved %r15
 -16: saved %r14
 -24: saved %r13
 -32: saved %r12
 -40: saved %rbx
 -56: pool (spill)
 -64: struct dirent *dirent;
 -72: unwind exception pointer (spill)
 -80: self (spill, in one place; also kept in %r12)
-104: struct dirent buffer;
-112: (bottom of frame)
```

The thing that immediately leaps out to me here is that there are only 24 bytes reserved for `buffer`.  [This appears to be the source for `struct dirent` in OpenIndiana](https://github.com/OpenIndiana/illumos-gate/blob/58ab7e661e4c475086d2dfe49e0eb5c9c8603cc5/usr/src/uts/common/sys/dirent.h#L44); there is no space for a path in this struct.  All of the uses of `readdir_r` in that repository appear to `malloc` a buffer with enough space for a maximally-sized path.  I don't know why the problem also happens with `readdir`, but I feel confident at this point that this is not a compiler bug.

**Comment by Midar** [comment]
Ouch, that `[1]` is pretty obvious in hindsight. Sorry for the noise!
