### ISSUE TITLE
[mlir][arith] Canonicalization causes miscompilation on mulsi_extended

### ISSUE THREAD

**Issue by pingshiyu** [llvm/llvm-project#88732]
The code below computes `mulsi_extended (-1) * (-1) : i1`, which should yield an extended vector with value `1 : i2`, or the bitvector `01`. However, canonicalization seems to cause the code to miscompile and output the bitvector `11`.

Reproduction: https://godbolt.org/z/8MYqsr1xd

**Comment by s-khechnev** [comment]
I would like to take this issue.
