### ISSUE TITLE
incorrect IR representation for bool vectors

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#8884]
|  |  |
| --- | --- |
| Bugzilla Link | [8512](https://llvm.org/bz8512) |
| Version | trunk |
| OS | All |
| Attachments | [test illustrating the problem](https://user-images.githubusercontent.com/60944935/143742217-5a22f6ce-9705-4e32-9844-6ff7af799355.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @sunfishcode |

## Extended Description 

Generation of IR from the following code

typedef bool v128b __attribute__ ((vector_size (16)));
int main() {
  v128b v1;
}

gives

define i32 @&#8203;main() nounwind {
entry:
  %v1 = alloca <16 x i1>, align 16
  ret i32 0
}

<16 x i1> is insufficient for 16-byte vector.

Attached is the test that compiles under GCC but gives assert under clang because of the wrong bool vector size:

**Comment by JOE1994** [comment]
Both `gcc` trunk & `clang` trunk emit a compile-time error when given the testcase:

* https://godbolt.org/z/fMfnc4sx8

**Comment by Endilll** [comment]
@JOE1994 CE links with only trunk compilers do not age well.
Clang 17 and GCC 13.2 both emit compiler-time errors as well: https://godbolt.org/z/vEqxKnKa7
