### ISSUE TITLE
llvm/include/llvm/ADT/ArrayRef.h:169: const T& llvm::ArrayRef<T>::front() const [with T = llvm::Value*]: Assertion `!empty()' failed.

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#88920]
From some fedora code compiled today with today's version of clang++,
I get this stack backtrace:

 #0 0x0000000001ef02eb llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/dcb38/llvm/trunk/llv
m/lib/Support/Unix/Signals.inc:723:22
 #1 0x0000000001eed49b llvm::sys::RunSignalHandlers() /home/dcb38/llvm/trunk/llvm/lib/Support/Signals
.cpp:105:20
 #2 0x0000000001eed5c5 SignalHandler(int) /home/dcb38/llvm/trunk/llvm/lib/Support/Unix/Signals.inc:41
3:1
 #3 0x00007f2ffd25fbb0 __restore_rt (/lib64/libc.so.6+0x3dbb0)
 #4 0x00007f2ffd2b0884 __pthread_kill_implementation (/lib64/libc.so.6+0x8e884)
 #5 0x00007f2ffd25fafe gsignal (/lib64/libc.so.6+0x3dafe)
 #6 0x00007f2ffd24887f abort (/lib64/libc.so.6+0x2687f)
 #7 0x00007f2ffd24879b _nl_load_domain.cold (/lib64/libc.so.6+0x2679b)
 #8 0x00007f2ffd258187 (/lib64/libc.so.6+0x36187)
 #9 0x000000000386dc04 llvm::DebugEpochBase::incrementEpoch() /home/dcb38/llvm/trunk/llvm/include/llv
m/ADT/EpochTracker.h:45:27
#10 0x000000000386dc04 llvm::detail::DenseSetPair<std::pair<llvm::Value*, llvm::Value*>>* llvm::Dense
MapBase<llvm::DenseMap<std::pair<llvm::Value*, llvm::Value*>, llvm::detail::DenseSetEmpty, llvm::Dens
eMapInfo<std::pair<llvm::Value*, llvm::Value*>, void>, llvm::detail::DenseSetPair<std::pair<llvm::Val
ue*, llvm::Value*>>>, std::pair<llvm::Value*, llvm::Value*>, llvm::detail::DenseSetEmpty, llvm::Dense
MapInfo<std::pair<llvm::Value*, llvm::Value*>, void>, llvm::detail::DenseSetPair<std::pair<llvm::Valu
e*, llvm::Value*>>>::InsertIntoBucketImpl<std::pair<llvm::Value*, llvm::Value*>>(std::pair<llvm::Valu
e*, llvm::Value*> const&, std::pair<llvm::Value*, llvm::Value*> const&, llvm::detail::DenseSetPair<st
d::pair<llvm::Value*, llvm::Value*>>*) /home/dcb38/llvm/trunk/llvm/include/llvm/ADT/DenseMap.h:594:19

[audio-688c11.cpp.gz](https://github.com/llvm/llvm-project/files/14999398/audio-688c11.cpp.gz)
[audio-688c11.sh.gz](https://github.com/llvm/llvm-project/files/14999400/audio-688c11.sh.gz)

**Comment by dcb314** [comment]
I've had a few goes at a reduction, but I always get a zero sized file ;-<

My cvise script is

source ./audio-688c11.sh 2>&1 | grep "llvm::DebugEpochBase::incrementEpoch"

Any advice how how to drive cvise better would be much appreciated.

**Comment by dcb314** [comment]
Removing -vectorize-slp from the shell script makes the code compile.

**Comment by Endilll** [comment]
@dcb314 Doesn't reproduce on the current trunk for me. Can you check on your side as well?

**Comment by dcb314** [comment]
Today's clang seems happy with it, so the problem seems
to have gone away. Deep joy !

**Comment by Endilll** [comment]
Thank you for getting back!
