### ISSUE TITLE
[x86][asm] invalid instruction mnemonic 'retf'

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#88941]
Clang's integrated assembler doesn't recognize "far return" x86 instructions.

https://godbolt.org/z/sd3P76nof

This is an issue for porting u-boot to be assembled by clang.

cc @phoebewang @pirama-arumuga-nainar

**Comment by phoebewang** [comment]
@nickdesaulniers According to TD defination, `retfq` is Intel syntax only. `retq` is used for AT&T https://godbolt.org/z/sK38sKh4q

**Comment by phoebewang** [comment]
Yes, I wanted to spell `lretq`. `lretl` == `retf` and `lretq` == `retfq`.

**Comment by nickdesaulniers** [comment]
Thanks!  We were able to get x86 u-boot to assemble with clang due to this hint!
https://android-review.googlesource.com/q/3047342
