### ISSUE TITLE
[libc] move pthread macros to a dedicated header

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#88997]
Forked from https://github.com/llvm/llvm-project/pull/88987#discussion_r1567968097

The macros defined in libc/include/pthread.h.def should be moved to a corresponding libc/include/llvm-libc-macros/pthreads-macros.h (unless these values are linux specific, in which case perhaps they should go in a newly created libc/include/llvm-libc-macros/linux/pthreads-macros.h).

**Comment by fabricerenard12** [comment]
Hi, if no one is working on this already I'd be glad to do it.

**Comment by nickdesaulniers** [comment]
You can do it @fabricerenard12 !

So a convention we have throughout most of the codebase is that:
- libc/include/stdbit.h.def doesn't declare any macros, but instead it includes
- libc/include/llvm-libc-macros/stdbit-macros.h

This allows us to simply include include/llvm-libc-macros/stdbit-macros.h to test just the macros separate from the rest of the header.  So in this case, the macros defined in libc/include/pthread.h.def should be moved to a new header libc/include/llvm-libc-macros/pthreads-macros.h. Don't forget to update:
- libc/include/CMakeLists.txt
- libc/include/llvm-libc-macros/CMakeLists.txt

**Comment by HendrikHuebner** [comment]
@fabricerenard12 are you still working on this?
