### ISSUE TITLE
OPENMP-5.0 conditional modifier for lastprivate clause

### ISSUE THREAD

**Issue by abidmalikwaterloo** [llvm/llvm-project#89]
Does this extension has been fully supported by the clang/LLVM framework?

**Comment by alexey-bataev** [comment]
Not supported for the NVPTX target yet.

**Comment by abidmalikwaterloo** [comment]
@alexey-bataev  Is it fully supported for multi-core processors?

**Comment by alexey-bataev** [comment]
Yes, it is fully supported for regular targets that rely on regular libomp.
