### ISSUE TITLE
_Imaginary not supported: "clang can't do complex arithmetic"

### ISSUE THREAD

**Issue by EdSchouten** [llvm/llvm-project#8904]
|  |  |
| --- | --- |
| Bugzilla Link | [8532](https://llvm.org/bz8532) |
| Version | trunk |
| OS | FreeBSD |
| CC | @lattner,@davidchisnall,@jordypotman,@tkremenek,@tydeman |

## Extended Description 
This is a bug report based on an observation from one of our Clang users at FreeBSD, Steve Kargl. Complete discussion thread can be found here:

http://lists.freebsd.org/pipermail/freebsd-toolchain/2010-November/000001.html

It seems that clang can't do complex arithmetic.
Not to worry gcc in base can't do it either.
```c
/*
 * The C99 standard intends x+I*y to be used for this, but x+I*y is
 * currently unusable because gcc introduces many overflow,
 * underflow, sign and efficiency bugs by rewriting I*y as
 * (0.0+I)*(y+0.0*I) and laboriously computing the full complex product.
 * In particular, I*Inf is corrupted to NaN+I*Inf, and I*-0 is corrupted
 * to -0.0+I*0.0.
 */
#include <complex.h>
#include <math.h>
#include <stdio.h>

int main(void) {

  double complex z;
  double x, y;

  x = 0.;
  y = 1. / x;
  x = copysign(x, -1.);

  /* z = 0 + i (-0) */
  z = I * x;
  printf("z = 0 + i (-0) = %e + i (%e)\n", creal(z), cimag(z));

  /* z = 0 + i Inf */
  z = I * y;
  printf("z = 0 + i Inf = %e + i %e\n", creal(z), cimag(z));

}
```
troutmask:sgk[204] clang -o z z.c -lm && ./z
z = 0 + i (-0) = -0.000000e+00 + i (0.000000e+00)
z = 0 + i Inf = nan + i inf

If I read Annex G in n1256.pdf correctly, the z = I*inf = NaN + I inf
is going to really bad things because the NaN is going to propagate
if z is used in further computations.  Annex G says z is an infinity.

**Comment by AaronBallman** [comment]
FWIW, `_Imaginary` was removed from Annex G in WG14 N3274 at the June 2024 meeting. I don't imagine (pun absolutely intended) that we'll be supporting this feature given its removal from the standard and the lack of adoption of it in the wild.
