### ISSUE TITLE
[clang++] Clang fails to call initializer_list constructor in specific cases

### ISSUE THREAD

**Issue by davidkjaer** [llvm/llvm-project#89079]
There seems to be a very specific case where clang does not call an initializer_list constructor even though it should apply.
The issues arises when the class `Foo` has an `std::initializer_list<Foo>` constructor and you create an object like this`Foo f{Foo{}};`:

```
#include <initializer_list>
#include <iostream>
#include <vector>

class Foo
{
public:
    Foo()
    {
    }

    explicit Foo(std::initializer_list<Foo> l)
    {
        std::cout << "Initializer list constructor\n";
    }

    void hi()
    {
        std::cout << "Hello\n";
    }
};

int main() {
    Foo other;
    Foo f{std::move(other)};
    f.hi();
}
```

When compiled with clang 18.1 the above example prints:
**Hello**

On both gcc and msvc the example prints:
**Initializer list constructor
Hello**

If I switch the initialization to `Foo f{{std::move(other)}}` or `Foo f{Foo{}, Foo{}}` clang correctly calls the initializer_list constructor.

**Comment by efriedma-quic** [comment]
Could you explain why you think gcc is right here?  I'm not an expert on overload resolution, but at first glance, `Foo(Foo&&)` should rank higher than `Foo(std::initializer_list<Foo>)` given the extra conversion required to construct the std::initializer_list.

**Comment by davidkjaer** [comment]
I must admit I just went by the majority vote (GCC and MSVC were in agreement)

I have had another look at the rules and the top rule for list initialisation says (from [cppreference.com](https://en.cppreference.com/w/cpp/language/list_initialization)):
"_If T is an aggregate class and the braced-init-list, which does not contain a designated initializer list,(since C++20) has a single element of the same or derived type (possibly cv-qualified), the object is initialized from that element (by [copy-initialization](https://en.cppreference.com/w/cpp/language/copy_initialization) for copy-list-initialization, or by [direct-initialization](https://en.cppreference.com/w/cpp/language/direct_initialization) for direct-list-initialization)._"

It indeed looks like clang is doing it right. If you agree feel free to close this bug.

For the curious there is an actual real-world use case for this. The `json` class of the nlohmann JSON library has an initializer_list-constructor taking a number of `json` objects (not actually of `json` type but something convertible to it). It is used for creating a JSON array of arbitrary elements. If we only supply one element clang did a direct initialization instead of an array of one element. That was a bit surprising. Especially since MSVC and GCC produced another result.

Furthermore, if `Foo` has a constructor taking an `int` as well as one taking an `initializer_list<int>`  `Foo{1}` would call the initializer_list constructor according to the rules. In conclusion I think C++ is being confusing here, but clang - at least to my understanding - seems to do the right thing :)

**Comment by davidkjaer** [comment]
Yes. That definitely looks like a duplicate.

I have deleted my previous comment since I had missed the word "aggregate" making my conclusion incorrect. No need to leave misinformation on the internet :)
