### ISSUE TITLE
New teams for LLVM offload

### ISSUE THREAD

**Issue by shiltian** [llvm/llvm-project#89071]
We are creating a new subproject called "offload" under LLVM top level directory. We need two teams for our bug reports and PRs:

- `issue-subscribers-offload`
- `pr-subscribers-offload`: this watches `offload/*` for now. (How can we update this part later?)

The maintainer of the two teams can be me and I'll add more later. Thanks!

**Comment by jdoerfert** [comment]
+1

**Comment by joker-eph** [comment]
In general the way to get this done in the past was to open a PR that defines the mapping between path and the team in the config file, and then add @tstellar as reviewer on the PR to create the teams matching the config.

**Comment by shiltian** [comment]
> In general the way to get this done in the past was to open a PR that defines the mapping between path and the team in the config file, and then add @tstellar as reviewer on the PR to create the teams matching the config.

K. Thanks for the info. I'll do that.

**Comment by asl** [comment]
> * `issue-subscribers-offload`

You do not need new team for issues. You can just subscribe to label.
