### ISSUE TITLE
Suggestion for implementing runtime defined _BitInt

### ISSUE THREAD

**Issue by awsdert** [llvm/llvm-project#89085]
I'm writing a custom library and I'd like to support all bit widths supported by _BitInt. As you can imagine doing a custom va_arg for each bit width is just unreasonable. I understand that the reason it's not implemented yet is lack of implementation ideas. Here's my suggestion:

The C should look like:
```
typedef struct { size_t leng; char text[BITINT_MAX+2]; } stdbitext_t;
extern __thread stdbitext_t *stdbitext;
#ifdef BUILD_LIBC
typedef _BitInt(BITINT_MAXWIDTH) bimax_t;
typedef unsigned _BitInt(BITINT_MAXWIDTH) ubimax_t;
typedef struct { ubimax quo, rem, ...; };
extern __thread stdbitmps_t *stdbitmps;
#endif
...
	printf( "%wu %wd", (unsigned _BitInt(N))1, (_BitInt(N))-1 );
...
int snprintf(...)
{
	...
	size_t len = 0;
	...
	unsigned _BitInt(...) biu = va_arg( va, _BitInt(...) );
	stdbiutostr( stdbitext, biu );
	...
	strncat(dst,stdbitext->text,stdbitext->leng);
	...
	_BitInt(...) bid = va_arg( va, _BitInt(...) );
	stdbidtostr( stdbitext, bid );
	...
	strncat(dst,stdbitext->text,stdbitext->leng);
	...
}
```
The `_BitInt(...)` should resolve to something like `struct { size_t width; void *biptr; } binum;`. The stdbitmps is an optimization thing to avoid constantly allocating large amounts of stack memory (I suggest doing likewise for the _BitInt(N)s if their big enough) just to copy values that should not be modified. 

Likewise with stdbitext, however since `stdbiutostr` and `stdbidtostr` are to be exposed to the user of clang I expect there'll be cases where peops want to keep the output for a little longer so I suggest making using stdbitext optional. It should be treated as an error to give NULL to those functions and the act of doing so should segfault during runtime.

To keep the size of binaries down when any non-native width is used I suggest using functions instead of inline asm when the values are to big for any kind of register on the CPU. Likewise if there are many non-std widths in use.

In all cases when _BitInt(N) != the width of whatever _BitInt(...) segments will be treated as they should be copied into stack elements of suitable size prior to being passed into the va_list. This will simplify the math functions greatly since they only need to be optimised for one segment size. So for instance _BitInt(1) could always upgrade to `qword` when passed into a va_list but once the function exits it gets copied back to it's source if the code was something like:

```
_BitInt(1) mybool = 0;
snscanf( "%wu", &mybool );
printf( "mybool = %s\n", mybool ? "true" : "false" );
```

**Comment by efriedma-quic** [comment]
`va_arg( va, _BitInt(...) )` would require an ABI change: the way everyone has chosen to define the ABI here, there's no way for the callee to automatically compute the bitwidth of a _BitInt argument.  And even if we were willing to change the ABI, it would add overhead for the cases where we don't need that information.

There might be some design that makes sense, but the bug tracker isn't really appropriate for open-ended discussion; maybe try https://discourse.llvm.org/ .

**Comment by awsdert** [comment]
How about this then?
```
stdbi_t bid = {0};
bid.width = va_arg(va,size_t);
bid.ptr = va_bitintarg(va,bid.width);
```
Doesn't change the ABI but instead puts the job of moving the va_list ptr into the compiler's hands while still being a runtime action.
