### ISSUE TITLE
-Wold-style-definition has no effect

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#8916]
|  |  |
| --- | --- |
| Bugzilla Link | [8544](https://llvm.org/bz8544) |
| Version | trunk |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
When the following program is compiled using GCC with -Wold-style-definition it warns about the definition of f(). Clang does not issue a warning for f().

This example was distilled from the GCC teststuite:
```c
typedef struct {
  long int p_x, p_y;
} Point;

void
f (p0, p1)
     Point p0, p1;
{
  if (p0.p_x != 0)
    abort ();
}

int
main ()
{
  Point p0, p1;
  p0.p_x = p1.p_x = 0;
  p0.p_y = p1.p_y = 1;
  f (p0, p1);
  exit(0);
}
```

**Comment by philnik777** [comment]
`-Wdeprecated-non-prototype` has been added in Clang 15 for this.

**Comment by Endilll** [comment]
It's even on-by-default https://godbolt.org/z/KKhc6963b
