### ISSUE TITLE
[flang] compiler crashed observed in gfortran class_allocate_19 test (hard to reproduce)

### ISSUE THREAD

**Issue by jeanPerier** [llvm/llvm-project#89179]
@tarunprabhu observes a compiler crash in a test I wanted to enable in llvm-test-suite, but I cannot reproduce.

Test is https://github.com/llvm/llvm-test-suite/blob/main/Fortran/gfortran/regression/class_allocate_19.f03

See for more contexts and the stack trace: https://github.com/llvm/llvm-test-suite/pull/109#issuecomment-2008008681

**Comment by tarunprabhu** [comment]
This does not seem to fail any longer.
