### ISSUE TITLE
llvm/include/llvm/CodeGen/MachineScheduler.h:810: pointless copy of a list ?

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#89193]
Static analyser cppcheck says:

llvm/include/llvm/CodeGen/MachineScheduler.h:810:51: performance: Function parameter 'Intervals' should be passed by const reference. [passedByValue]

Source code is

  explicit ResourceSegments(std::list<IntervalTy> Intervals)

**Comment by JOE1994** [comment]
The mentioned constructor isn't used anywhere in the codebase, so I think we can just remove the constructor altogether.
It can be added back in when it is actually needed.
