### ISSUE TITLE
[llvm][NVPTX] `cvta.local.u64` used with generic address as input

### ISSUE THREAD

**Issue by JOE1994** [llvm/llvm-project#89205]
PTX instruction [`cvta.local.u64`](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#data-movement-and-conversion-instructions-cvta) converts a 64-bit _**local address**_ to a 64-bit _**generic address**_ .

With the below input IR, `llc` emits PTX code that uses `cvta.local.u64` with an already _**generic address**_ as input.
This produces an invalid memory address, since `cvta.local.u64` [adds the base address of the "local address space window" to its input address](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#generic-addressing). A program using this invalid address can crash with **`CUDA_ERROR_ILLEGAL_ADDRESS`** runtime error.

### Minimal Reproducible Example
* Tested with llvm 19 trunk at `e90bc9cfd4d22c89dd993f62ede700ae25df49c5`

#### Input LLVM IR
```llvm
; mre.ll

target datalayout = "e-i64:64-i128:128-v16:16-v32:32-n16:32:64"
target triple = "nvptx64-nvidia-cuda"

declare hidden i32 @BAR(ptr %n)

define ptx_kernel void @FOO(ptr %aarg) noinline {
"BB0":
  %aloha = alloca i32, align 4
  store i32 25, ptr %aloha, align 4
  %r = ptrtoint ptr %aloha to i64
  %r2 = inttoptr i64 %r to ptr addrspace(5)
  %r3 = addrspacecast ptr addrspace(5) %r2 to ptr
  %r4 = call i32 @BAR(ptr %r3)
  store i32 %r4, ptr %aarg, align 4
  ret void
}
```

#### Output PTX code (from `llc -mcpu=sm_80 mre.ll`)

* Problematic code line is `cvta.local.u64  %rd5, %rd3;`
```ptx
.version 7.0
.target sm_80
.address_size 64

  // .globl FOO                     // -- Begin function FOO
.extern .func  (.param .b32 func_retval0) BAR
(
  .param .b64 BAR_param_0
)
;
                                        // @FOO
.visible .entry FOO(
  .param .u64 FOO_param_0
)
{
  .local .align 4 .b8   __local_depot0[4];
  .reg .b64   %SP;
  .reg .b64   %SPL;
  .reg .b32   %r<4>;
  .reg .b64   %rd<6>;

// %bb.0:                               // %BB0
  mov.u64   %SPL, __local_depot0;
  cvta.local.u64  %SP, %SPL;  // %SP holds generic address 
  ld.param.u64  %rd1, [FOO_param_0];
  cvta.to.global.u64  %rd2, %rd1;
  add.u64   %rd3, %SP, 0;  // %rd3 holds generic address
  add.u64   %rd4, %SPL, 0;
  mov.b32   %r1, 25;
  st.local.u32  [%rd4], %r1;
  cvta.local.u64  %rd5, %rd3;  // PROBLEMATIC: %rd3 holds a generic address, but used as input to `cvta.local.u64`
  { // callseq 0, 0
  .param .b64 param0;
  st.param.b64  [param0+0], %rd5;
  .param .b32 retval0;
  call.uni (retval0),
  BAR,
  (
  param0
  );
  ld.param.b32  %r2, [retval0+0];
  } // callseq 0
  st.global.u32   [%rd2], %r2;
  ret;
                                        // -- End function
}
```

**Comment by Artem-B** [comment]
I'm not convinced your IR is correct.

>  %aloha = alloca i32, align 4
>  %r = ptrtoint ptr %aloha to i64

%aloha is in generic AS, as far as LLVM is concerned.
So `%r` is an integer representation of that pointer

>  %r2 = inttoptr i64 %r to ptr addrspace(5)

Then you  `inttoptr` it to the local AS pointer, which looks wrong to me. It does not do any AS conversion, just tells LLVM that %r2 is in the local AS.

>  %r3 = addrspacecast ptr addrspace(5) %r2 to ptr

And then when you ask LLVM to cast it to the local AS, it does exectly that.

When LLVM lowers the IR, Allocas get lowered to the local AS, and the code that gets alloca pointer (still generic), accesses it via addrspacecast(local->generic) to preserve the AS uses in the original IR.

So, afaict, LLVM produced exactly what you've asked it to produce.

**Comment by JOE1994** [comment]
Thank you for your feedback!
