### ISSUE TITLE
llvm/utils/TableGen/Basic/CodeGenIntrinsics.cpp: 2 * pointless vector copy ?

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#89207]
Static analyser cppcheck says:

1.

llvm/utils/TableGen/Basic/CodeGenIntrinsics.cpp:58:58: performance: Function parameter 'DefaultProperties' should be passed by const reference. [passedByValue]

Source code is

CodeGenIntrinsic::CodeGenIntrinsic(Record *R,
                                   std::vector<Record *> DefaultProperties) {

2.

llvm/utils/TableGen/Basic/CodeGenIntrinsics.cpp:151:38: performance: Function parameter 'DefaultProperties' should be passed by const reference. [passedByValue]

Duplicate.

**Comment by JOE1994** [comment]
I'd suggest directly creating a PR with the suggested changes.

**Comment by dcb314** [comment]
Feel free to go right ahead with your PR. 

I gave up doing them years ago. I find bugs and folks who know
what they are doing fix them.
