### ISSUE TITLE
[flang] Linker for non-constant accesses to kind arrays (integer_kind, logical_kind, real_kind)

### ISSUE THREAD

**Issue by mjklemm** [llvm/llvm-project#89403]
When compiling a code like this:

```Fortran
program kinds_issue
   use, intrinsic :: iso_fortran_env, only: integer_kinds
   implicit none
   integer :: k
   k=1
   write (*,'(I0)') integer_kinds(k)
end program
```

Results in an error like this:

```
FIRModule:(.text+0x4e): undefined reference to `_QMiso_fortran_envECinteger_kinds'
flang-new: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by mjklemm** [comment]
After a short discussion with @klausler (Thanks for the input, BTW!), the solution I'm working on involves fully compiling the module file so that both the constant array and a dynamic instance is created.   I hope to have a solution for this soonish.

**Comment by Krande** [comment]
Hey @mjklemm, I see you've been busy making Flang PR's lately. 

I was just wondering if you've had any progress on this issue, and if there is anything I can do to help? :) 
(btw. I'm really excited about the prospect of LLVM flang support for HDF5 on MSVC, so I hope you'll forgive me asking for updates)
