### ISSUE TITLE
Missing assertion propagation

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#8941]
|  |  |
| --- | --- |
| Bugzilla Link | [8569](https://llvm.org/bz8569) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @lattner |

## Extended Description 
Trivial Test:
```c++
int g;
int foo (int i)
{

   if (i == 1)
   {
      g = i + 1;
   }
   else if (i == 10)
      g = 2*i;

  return g;
}
```
Clang -O2 -fomit-frame-pointer generates:

foo:
```asm
.Leh_func_begin0:
	cmpl	$1, %edi
	je	.LBB0_3
	cmpl	$10, %edi
	je	.LBB0_4
	movl	g(%rip), %eax
	ret
.LBB0_3:
	incl	%edi               <---
	movl	%edi, g(%rip)      <---
	movl	$2, %eax
	ret
.LBB0_4:
	addl	%edi, %edi        <---
	movl	%edi, g(%rip)     <---
	movl	$20, %eax
	ret
```

Compared with gcc -O2 result:

```asm
.LFB0:
	.cfi_startproc
	cmpl	$1, %edi
	je	.L6
	cmpl	$10, %edi
	je	.L4
	movl	g(%rip), %eax
	ret
	.p2align 4,,10
	.p2align 3
.L4:
	movl	$20, g(%rip)
	movl	$20, %eax
	ret
	.p2align 4,,10
	.p2align 3
.L6:
	movl	$2, g(%rip)
	movl	$2, %eax
	ret
```

**Comment by xgupta** [comment]
This is fixed already, just checked the latest trunk, both clang and gcc have emitted same code - https://godbolt.org/z/55cco9TTb. Hence closing.
