### ISSUE TITLE
[DAG] SelectionDAG.computeKnownBits - add NSW/NUW flags support to ISD::SHL handling

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#89414]
The call to KnownBits::shl is currently not handling nodes that have the NSW/NUW flags (or a known non zero shift amount).

https://github.com/llvm/llvm-project/blob/e553ac4d8148291914526f4f66f09e362ce0a63f/llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp#L3497-L3506

This task will mainly involve adding test coverage - my advice would be to disable the equivalent handling in ValueTracking, run `check-llvm-transforms` to see what tests start failing and see what equivalent tests can be created for CodeGen/X86

https://github.com/llvm/llvm-project/blob/e553ac4d8148291914526f4f66f09e362ce0a63f/llvm/lib/Analysis/ValueTracking.cpp#L1168-L1182

**Comment by zxc12523** [comment]
I would like to take this issue!

**Comment by zxc12523** [comment]
Hi @RKSimon ! Can you elaborate more on the equivalent handling and the equivalent tests you mentioned above? I'm not quite sure of the meaning of it.

**Comment by RKSimon** [comment]
If you set NUW = NSW = false in the ValueTracking.cpp snippet above and run `ninja check-llvm-transforms-instcombine` you should see a number of test failures that you can create DAG tests from
