### ISSUE TITLE
[libc][gnu ext] implement pthread_rwlockattr_{get|set}kind_np

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#89443]
These functions are perhaps useful. Not implemented in #89322 because I didn't know they existed outside of POSIX.

Since these aren't POSIX but instead gnu extensions, these should go in FOO rather than libc/spec/posix.td; we already have an entry for pthreads.h in that file.  It will be easier for someone to start on this once #89322 lands.

I would extend our definition of `pthread_rwlockattr_t` in libc/include/llvm-libc-types/pthread_rwlockattr_t.h to include a new `int` member named `pref` such that these functions are simple getters and setters.

Then it sounds like we should define 3 macros (in libc/include/pthread.h.def, though keep an eye on https://github.com/llvm/llvm-project/issues/88997, too)
- PTHREAD_RWLOCK_PREFER_READER_NP
- PTHREAD_RWLOCK_PREFER_WRITER_NP
- PTHREAD_RWLOCK_PREFER_WRITER_NONRECURSIVE_NP

**Comment by HendrikHuebner** [comment]
I would like to work on it if possible.

**Comment by nickdesaulniers** [comment]
@HendrikHuebner cool! Let me know if you get stuck.  Note: I'll be offline a bit soon ish, so expected delayed review+feedback from me.

**Comment by nickdesaulniers** [comment]
Hi @SchrodingerZhu thanks for the quick revert.

Did this issue ever get fixed up? If not looks like we should re-open it?

**Comment by SchrodingerZhu** [comment]
> Hi @SchrodingerZhu thanks for the quick revert.
> 
> 
> 
> Did this issue ever get fixed up? If not looks like we should re-open it?

I agree. I don't think it is fixed by now.

**Comment by HendrikHuebner** [comment]
Sorry I haven't gotten around to it yet. I'll update it tomorrow. Somehow one of the changes I made wasn't committed.

**Comment by nickdesaulniers** [comment]
fixed: https://github.com/llvm/llvm-project/commit/485f9f589595006a8d10b8d39bde7124b0dc2042
