### ISSUE TITLE
[x86] llvm #pragma pack behaviour is different from gcc

### ISSUE THREAD

**Issue by zhangtianhao6** [llvm/llvm-project#89581]
hello, I use #pragma pack(1) to change the  ExampleStruct member align and print the address of ExampleStruct, the ExampleStruct address printed by the gcc compiler is 8-byte aligned, but the ExampleStruct address printed by the llvm compiler is 1-byte aligned. why they are different, which is correct?

```
#include <iostream>
#include <mutex>
#pragma pack(1)


struct ExampleStruct {
    std::mutex mutex_;
    int b;
};

#pragma pack()


ExampleStruct example;

int main(){
    std::cout << &example << std::endl;
    std::cout << alignof(example) << std::endl;
}

```
```
result:
gcc print: 0x404160
llvm print: 0x555d1805f031
```
godbolt demo:
https://godbolt.org/z/Yv7Taxfqa

**Comment by zhangtianhao6** [comment]
remove #pragma pack(1),   the ExampleStruct address printed by the llvm compiler is 8-byte aligned
https://godbolt.org/z/qM4P1Pqhr

**Comment by Sirraide** [comment]
> the ExampleStruct address printed by the gcc compiler is 8-byte aligned, but the ExampleStruct address printed by the llvm compiler is 1-byte aligned. why they are different, which is correct?

The effect of `#pragma pack(1)` here irrc is to set the alignment of `ExampleStruct` to `1`; where exactly `example` here ends up in memory is implementation-defined. It just so happens that the address that GCC uses ends up being 16-byte aligned, whereas the address LLVM is choosing isn’t. This isn’t really an issue (unless I’m missing something here); it’s just an implementation detail; both are correct, if you will.

**Comment by hstk30-hw** [comment]
https://github.com/gcc-mirror/gcc/blame/ce343444c019f34172320d0873cc993d43750f41/gcc/config/aarch64/aarch64.h#L128

Yeap, GCC implement it diff, and weird also.  GCC force the alignment of arrays, unions and structures to a minimal align(in aarch64 is 8) even if we set pragma pack for it.

**Comment by shafik** [comment]
CC @AaronBallman @erichkeane

**Comment by erichkeane** [comment]
> CC @AaronBallman @erichkeane

I think this is the sort of thing that @efriedma-quic and @rjmccall are knowledgeable about.  I certainly am not :)

**Comment by rjmccall** [comment]
We could easily align structs on the stack higher than is required by the type alignment, but if you need this, you should probably just specify an alignment.  At any rate, there's no bug here.
