### ISSUE TITLE
3-component triple *-none-* is incorrectly normalized to *-none-unknown-* instead of *-unknown-none-*

### ISSUE THREAD

**Issue by wzssyqa** [llvm/llvm-project#89582]
```
$ clang --target=aarch64-none-elf --print-target-triple
aarch64-none-unknown-elf
$ clang --target=armv7m-none-eabi --print-target-triple
armv7m-none-unknown-eabi
```

The expected value is that `none` and `unknown` should be swapped.
Caused by `std::string Triple::normalize(StringRef Str)` in `llvm/lib/TargetParser/Triple.cpp`.

**Comment by wzssyqa** [comment]
@peterwaller-arm

**Comment by MaskRay** [comment]
> Is the title of this ticket correct? The issue is that Vendor=none and OS=unknown when triples for example `aarch64-none-elf` go through normalization, where I believe we expect Vendor=unknown and OS=none.

I've updated the title. Hopefully it's clearer now.
