### ISSUE TITLE
libstdc++ sort does not work... well

### ISSUE THREAD

**Issue by kelbon** [llvm/llvm-project#89591]
Recently I wanted to sort 2 separate arrays, one with the keys, the other with their corresponding values. A year ago this worked (iota | transform (tie(key, value)) + sort(by_key)), but now, after improvements and corrections to the standard, this is no longer possible.
But during the implementation process I discovered bugs/oddities in the libstd++ standard library:

1. even if range is std::sortable, stable_sort may throw compilation error:

https://godbolt.org/z/M8hWz1G7W

This error may be even worse if you use 'size_t' indexes:

https://godbolt.org/z/nzqqPWhd3

2. std::make_unsigned has no specialization for __int128_t, but it is used:

https://godbolt.org/z/GPa9E4h5a

**Comment by tbaederr** [comment]
Please test the examples with GCC as well and if both compilers don't work, report the problems on the libstdc++ bug tracker. If not, it  suggests a clang problem and the bugs are fine here.

**Comment by frederick-vs-ja** [comment]
GCC behaves almost same as Clang for these three examples.

**Comment by kelbon** [comment]
> GCC behaves almost same as Clang for these three examples.

yes, this is standard library error =(

**Comment by frederick-vs-ja** [comment]
Reported to GCC/libstdc++: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=117552.

I'm closing this because there doesn't seem anything wrong with Clang.
