### ISSUE TITLE
llvm/lib/Target/AArch64/AArch64InstrInfo.h: 2 * missing default case in switch ? 

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#89709]
Static analyser cppcheck says:

1.

llvm/lib/Target/AArch64/AArch64InstrInfo.h:722:14: error: Found an exit path from function with non-void return type that has missing return statement [missingReturn]

Source code is

  switch (K) {
  case IA: return Zero ? AArch64::AUTIZA : AArch64::AUTIA;
  case IB: return Zero ? AArch64::AUTIZB : AArch64::AUTIB;
  case DA: return Zero ? AArch64::AUTDZA : AArch64::AUTDA;
  case DB: return Zero ? AArch64::AUTDZB : AArch64::AUTDB;
  }

Suggest add a default case to the switch or a return at the end of the function.

2.

llvm/lib/Target/AArch64/AArch64InstrInfo.h:734:14: error: Found an exit path from function with non-void return type that has missing return statement [missingReturn]

Duplicate.

**Comment by Troy-Butler** [comment]
Hi, could this issue please be assigned to me?

I am a university student working on a project for a software development course. I need to make a series of contributions to an open-source project that are accepted and merged, but for those contributions to count, I must be assigned. Thank you!
