### ISSUE TITLE
Crash on ExecutionEngine::addGlobalMapping()

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#8972]
|  |  |
| --- | --- |
| Bugzilla Link | [8600](https://llvm.org/bz8600) |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
On MSVC 2008 I get a crash with while calling ExecutionEngine::addGlobalMapping (as seen below), in 2.7, 2.8 and trunk.
It throws an unhandled exception (an access violation) seemingly at MutexImpl::acquire().

Reduced test case:

void foo() { }
int main() {
  ExecutionEngine *jitengine = EngineBuilder(jitmodule).setEngineKind(EngineKind::JIT).create();
  Function *func = Function::Create(TypeBuilder<void(), false>::get(getGlobalContext()), GlobalValue::ExternalLinkage, "foo");
  jitengine->addGlobalMapping(func, (void*)foo);
}

**Comment by gwelymernans** [comment]
This is very old and things have changed drastically since 2010. Please open a new issue if this is still occurring.
