### ISSUE TITLE
coroutine: generateAwaitSuspendWrapper doesn't generate a valid mangled name

### ISSUE THREAD

**Issue by hokein** [llvm/llvm-project#89723]
The function name generated by the `CodeGenFunction::generateAwaitSuspendWrapper` is not a valid mangled name, it can not be demangled.

E.g. the name generated for the `clang/test/CodeGenCoroutines/pr65054.cpp` is `__await_suspend_wrapper__Z6FooBarv_await`, 

```
$  ./bin/llvm-cxxfilt __await_suspend_wrapper__Z6FooBarv_await
__await_suspend_wrapper__Z6FooBarv_await
```

**Comment by hokein** [comment]
I'm not an expert, but one naive idea I have is to change the way we construct the name.

Instead of concatenating all strings with `_`, maybe we can form a name like `_Z6FooBarv.await_suspend_wrapper__await`, and then we can demangle it as `FooBar( ) (.await_suspend_wrapper__await).`

cc @ChuanqiXu9 @fpasserby

**Comment by ChuanqiXu9** [comment]
Thanks for raising this. I don't have strong opinion on the naming. The suggestion looks fine.

Also I am slightly surprised this matters. Since I thought all such functions will be inlined.

**Comment by hokein** [comment]
Thanks for the prompt rely. I will send out a patch.

> Also I am slightly surprised this matters. Since I thought all such functions will be inlined.

Yes, these functions are inlined. However, for some profiling tools (this issue was spotted in pprof), they will show inlined functions in traces.
