### ISSUE TITLE
clangd: Remove "-misc-const-correctness" from disableUnusableChecks()

### ISSUE THREAD

**Issue by geza-herman** [llvm/llvm-project#89758]
As clangd has `FastCheckFilter`, I think "-misc-const-correctness" can be removed from `disableUnusableChecks()`, as it will be filtered by the default value of `FastCheckFilter` as well. So people who prefer to run misc-const-correctness from clangd, they can do it by setting `FastCheckFilter` to `None`.

**Comment by HighCommander4** [comment]
I think this would make sense. The check is specifically identified as being disabled [for performance reasons](https://searchfox.org/llvm/rev/6168e82c1e17c58ebc9c0b6c8f2273fd9a610977/clang-tools-extra/clangd/TidyProvider.cpp#226-230), and that pre-dates the introduction of the `FastCheckFilter` setting.

The magnitude of its performance impact ("has been observed to increase reparse time **by 10x**") is a bit concerning, but we probably still shouldn't prevent users from running the check altogether.

Maybe we can add a warning to the [documentation](https://clangd.llvm.org/config.html#fastcheckfilter) of `FastCheckFilter` that `misc-const-correctness` is known to cause a serious slowdown and if you're not setting `FastCheckFilter: None` specifically to get that check, consider disabling it with [Remove:](https://clangd.llvm.org/config.html#remove-1).

**Comment by geza-herman** [comment]
@HighCommander4 yes, I can do that this weekend.

Regarding the performance impact: I'm not sure where the 10x number comes from. Maybe this is not true anymore? If I run clang-tidy on one of my toy-sized personal project, the difference between "default config" and "default config" + misc-const-correctness is 8% (12.5 sec vs. 13.49 sec). I'd be good to know what project was that produced that 10x difference.

**Comment by geza-herman** [comment]
@HighCommander4 I created a PR, but it only touches the code, no doc change, because I don't know how to edit the doc (didn't find it in the repo).

**Comment by HighCommander4** [comment]
> @HighCommander4 I created a PR, but it only touches the code, no doc change, because I don't know how to edit the doc (didn't find it in the repo).

Thanks!

If you're interested in writing the doc patch as well, that's contained in this repo: https://github.com/llvm/clangd-www/blob/main/config.md#fastcheckfilter

**Comment by HighCommander4** [comment]
> Regarding the performance impact: I'm not sure where the 10x number comes from. Maybe this is not true anymore? If I run clang-tidy on one of my toy-sized personal project, the difference between "default config" and "default config" + misc-const-correctness is 8% (12.5 sec vs. 13.49 sec). I'd be good to know what project was that produced that 10x difference.

The commit which added the comment is [this one](https://github.com/llvm/llvm-project/commit/e78165f0ba1e2fbf72b36a36c8560645b69a168a). The commit message says:

> When (inadvertently) enabled for Fuchsia, it regressed BuildAST times by >10x (400ms -> 7s on my machine).

**Comment by kadircet** [comment]
we should probably document some release process, but nowadays we have `clang-tools-extra/clangd/TidyFastChecks.py` that can be used to detect performance of a specific clang-tidy check.

> Regarding the performance impact: I'm not sure where the 10x number comes from. Maybe this is not true anymore? If I run clang-tidy on one of my toy-sized personal project, the difference between "default config" and "default config" + misc-const-correctness is 8% (12.5 sec vs. 13.49 sec). I'd be good to know what project was that produced that 10x difference.

clangd doesn't just build the whole translation unit every time. it just reparses the main file and runs analysis on this section. hence the 8% increase to overall TU parsing time actually means a huge deal for clangd's interactive reparses.

**Comment by geza-herman** [comment]
> If you're interested in writing the doc patch as well, that's contained in this repo: https://github.com/llvm/clangd-www/blob/main/config.md#fastcheckfilter

Yes, I'll try to come up with something in the doc as well soon, thanks for pointing me to it!
