### ISSUE TITLE
clang/lib/Lex/Pragma.cpp:1447:14: style: Suspicious condition

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#89805]
Static analyser cppcheck says:

clang/lib/Lex/Pragma.cpp:1447:14: style: Suspicious condition (assignment + comparison); Clarify expression with parentheses. [clarifyCondition]

Source code is

         if ((SpecifierValid = SpecifierInt != -1))

I suspect the following code was intended:

         if (SpecifierValid = (SpecifierInt != -1))

**Comment by Troy-Butler** [comment]
Hi, could this issue please be assigned to me?

I am a university student working on a project for a software development course. I need to make a series of contributions to an open-source project that are accepted and merged, but for those contributions to count, I must be assigned. Thank you!

**Comment by MaskRay** [comment]
> I suspect the following code was intended:
> 
> ```
>      if (SpecifierValid = (SpecifierInt != -1))
> ```

#89923 adopted this style which caused `clang -Wparentheses` (part of `-Wall`) warning. I fixed it in 6f390ea60d987f6e1e027d1c72982c2eb7896005 . `a = b != -1` without parens is common in LLVM.
