### ISSUE TITLE
gep+load/store is optimized differently that insertvalue+store and load+extractvalue.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#8988]
|  |  |
| --- | --- |
| Bugzilla Link | [8616](https://llvm.org/bz8616) |
| Version | trunk |
| OS | Linux |
| Attachments | [ll with first class structs.](https://user-images.githubusercontent.com/60944935/143742303-6505ca40-429a-4379-b09b-7f146ef3bc17.gz), [ll with geps](https://user-images.githubusercontent.com/60944935/143742304-3524f92e-0ea9-413e-83c5-1b984582c29e.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I have attached to ll files, that differ simply in the use of GEP vs insert/extractvalue.

For gep.ll, opt -O3 optimizes most of the code away, and running opt -O3 gets rid of a single extra store.

For ev.ll, opt -O3 optimizes much less, but then running opt -O3 on the output again gets rid of all the alloca.

**Comment by arsenm** [comment]
[ev.ll.txt](https://github.com/llvm/llvm-project/files/12326080/ev.ll.txt)
[gep.ll.txt](https://github.com/llvm/llvm-project/files/12326081/gep.ll.txt)

opt -O3 turns both cases into a branch to an empty loop
