### ISSUE TITLE
Assertion `isa(Val) && "cast() argument of incompatible type!"' failed when using alive2

### ISSUE THREAD

**Issue by AFlexeder** [llvm/llvm-project#89941]
Using llvm in combination with the alive2 toolkit resulted in a core dump.
Attached is the error report
llvm-project/llvm/include/llvm/Support/Casting.h:578: decltype(auto) llvm::cast(From*) [with To = llvm::OverflowingBinaryOperator; From = const llvm::Instruction]: Assertion `isa<To>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
 #0 0x00007f7e172018b0 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (llvm-project/build/lib/libLLVMSupport.so.19.0git+0x2088b0)
 #1 0x00007f7e171fe8bf llvm::sys::RunSignalHandlers() (llvm-project/build/lib/libLLVMSupport.so.19.0git+0x2058bf)
 #2 0x00007f7e171fea15 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007f7e16bb2520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007f7e16c069fc __pthread_kill_implementation ./nptl/./nptl/pthread_kill.c:44:76
 #5 0x00007f7e16c069fc __pthread_kill_internal ./nptl/./nptl/pthread_kill.c:78:10
 #6 0x00007f7e16c069fc pthread_kill ./nptl/./nptl/pthread_kill.c:89:10
 #7 0x00007f7e16bb2476 gsignal ./signal/../sysdeps/posix/raise.c:27:6
 #8 0x00007f7e16b987f3 abort ./stdlib/./stdlib/abort.c:81:7
 #9 0x00007f7e16b9871b _nl_load_domain ./intl/./intl/loadmsgcat.c:1177:9
#10 0x00007f7e16ba9e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
#11 0x00007f7e175cd9bb (llvm-project/build/lib/libLLVMCore.so.19.0git+0x29a9bb)
#12 0x00007f7e196f666d (anonymous namespace)::llvm2alive_::visitCastInst(llvm::CastInst&) llvm2alive.cpp:0:0
#13 0x00007f7e196ff1e8 llvm::InstVisitor<(anonymous namespace)::llvm2alive_, std::unique_ptr<IR::Instr, std::default_delete<IR::Instr> > >::visit(llvm::Instruction&) llvm2alive.cpp:0:0
#14 0x00007f7e197027c3 (anonymous namespace)::llvm2alive_::run() llvm2alive.cpp:0:0
#15 0x00007f7e19703b61 llvm_util::llvm2alive(llvm::Function&, llvm::TargetLibraryInfo const&, bool, std::vector<std::basic_string_view<char, std::char_traits<char> >, std::allocator<std::basic_string_view<char, std::char_traits<char> > > > const&) (alive2/build/alive-tv+0x56b61)
#16 0x00007f7e196eac32 (anonymous namespace)::verify(llvm::Function&, llvm::Function&, llvm::TargetLibraryInfoWrapperPass&, smt::smt_initializer&, std::ostream&, bool, bool) compare.cpp:0:0
#17 0x00007f7e196ee294 llvm_util::Verifier::compareFunctions(llvm::Function&, llvm::Function&)

**Comment by dtcxzyw** [comment]
Please provide the following information:
1. LLVM version
2. alive2 version
3. input IR

**Comment by AFlexeder** [comment]
LLVM version 19.0.0git
 alive2 version 2fccad27

Ubuntu clang version 14.0.0-1ubuntu1.1
Target: x86_64-pc-linux-gnu

**Comment by dtcxzyw** [comment]
> LLVM version 19.0.0git

You should run `git rev-parse HEAD` to get the commit hash.

**Comment by dtcxzyw** [comment]
IIRC this problem should be fixed if your llvm version is newer than https://github.com/llvm/llvm-project/commit/7d3924cee30a87a51f9dc04ec843ae6bc3d1c90e.

**Comment by AFlexeder** [comment]
Thus, I new to have a new llvm-version and re-compile it for alive, right?

**Comment by dtcxzyw** [comment]
> Thus, I new to have a new llvm-version and re-compile it for alive, right?

Yeah.
