### ISSUE TITLE
Possible llvm problem when ModulePass requires FunctionPasses

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#8996]
|  |  |
| --- | --- |
| Bugzilla Link | [8624](https://llvm.org/bz8624) |
| Version | trunk |
| OS | Linux |
| Attachments | [Experimental Pass](https://user-images.githubusercontent.com/60944935/143742310-d4df9af3-fcf8-459d-93fc-823f79f92c95.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Consider a case when a module pass requires two function passes fp1, fp2. When
getAnalysis<fp1>() is called, both fp1 and fp2 are executed. That is fine. In
the worst case, we just spend lots of time running the analysis passes many
times.

But it should not crash. In the experimental pass, command "opt" got an assertion.

The experimental pass is attached. Using the following command:

$ opt -load LLVMTestPass.so  -mpass x.bc -o y.bc

got:

MyFPass running on __cxx_global_var_init
MyFPass2 running on __cxx_global_var_init
opt: /developer/home2/zsth/projects/llvm.org/llvm/include/llvm/PassAnalysisSupport.h:239: AnalysisType& llvm::Pass::getAnalysisID(const void*, llvm::Function&) [with AnalysisType = MyFPass]: Assertion `ResultPass && "Unable to find requested analysis info"' failed.

Seems the function pass fp1 and fp2 were correctly invoked by the module pass, but why it dumped the assertion at last.

**Comment by arsenm** [comment]
Old pass manager
