### ISSUE TITLE
[LLD] -Ttext-segment is not supported

### ISSUE THREAD

**Issue by tannal** [llvm/llvm-project#90044]
When building box64 with ninja. ld is a symbol linking to lld.
```bash
cc -Wl,-Ttext-segment,0x34800000 ...
```

ld: error: -Ttext-segment is not supported. Use --image-base if you intend to set the base address
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by MaskRay** [comment]
-Ttext-segment is not supported as intended. GNU ld 2.44 will support --image-base https://sourceware.org/bugzilla/show_bug.cgi?id=25207

**Comment by tannal** [comment]
👍
