### ISSUE TITLE
User defined SIN function is not called with O3 opt level

### ISSUE THREAD

**Issue by ararmine** [llvm/llvm-project#90047]
When compiling the following example with clang -O3 opt level, the program does not print the expected output, the user defined sin function is not called and the sin library function is called instead. While with -O0 level it works as expected.
Steps to reproduce:
```
cat bug.cpp 
#include <stdio.h>

extern "C" double sin(double x) {
  printf ("Inside the sin function\n");
  return 0.0;
}

int main() {
  printf ("Call 1 %f\n", sin(3.3));
  printf ("Call 2 %f\n", ::sin(3.3));
}
```
With clang 18.1.0
```
clang++ -O0 bug.cpp
./a.out
Inside the sin function
Call 1 0.000000
Inside the sin function
Call 2 0.000000

clang++ -O3 bug.cpp
./a.out
Inside the sin function
Call 1 -0.157746
Inside the sin function
Call 2 -0.157746
```

When compiling the program with GCC 13.2 , the output is expected with both opt. levels.
```
g++ -O0 bug.cpp
./a.out
Inside the sin function
Call 1 0.000000
Inside the sin function
Call 2 0.000000

g++ -O3 bug.cpp
./a.out
Inside the sin function
Call 1 0.000000
Inside the sin function
Call 2 0.000000
```

**Comment by dtcxzyw** [comment]
BTW, the behavior of this C++ program is undefined:
> 16.4.5.3.1 General [reserved.names.general]
> If a program declares or defines a name in a context where it is reserved, other than as explicitly allowed by Clause 16, its behavior is undefined.
> 16.4.5.3.4 External linkage [extern.names]
> Each name from the C standard library declared with external linkage is reserved to the implementation for use as a name with extern "C" linkage, both in namespace std and in the global namespace.
