### ISSUE TITLE
[[deprecated]] applied to local variables

### ISSUE THREAD

**Issue by cor3ntin** [llvm/llvm-project#90073]
GCC warns on local variables marked `[[deprecated]]`
https://compiler-explorer.com/z/nvfdTeveP

This behavior seems to be backed by the standard https://eel.is/c++draft/dcl.attr#deprecated-2.sentence-1

Should we follow suite? Arguably, it would be of limited usefulness.

**Comment by erichkeane** [comment]
I don't really see the usefulness, but I DEFINITELY think we should enforce it if we are going to permit it on local variable decls.  At the moment, the the standard permits them on local variable decls, AND encourages enforcement, so we should.

However, if the response to https://github.com/cplusplus/CWG/issues/530 results in disallowing 'local variables', that would be a valid solution ot this as well.

**Comment by shafik** [comment]
Note, if we remove the `[[deprecated]]` from `f` we warn for `a` now: https://compiler-explorer.com/z/f7o7Wc6W7
