### ISSUE TITLE
CTAD: incorrect transformed require-clause for the alias deduction guide

### ISSUE THREAD

**Issue by hokein** [llvm/llvm-project#90177]
Example:

```
struct Key1  {};

template <class Key>
struct Foo {
  Foo(Key);
};

template <class D>
constexpr bool C = sizeof(D);

template <class Key>
  requires (C<Key>)
Foo(Key) -> Foo<Key>;

template <class T>
struct HasTemplateParam {
  template <class Key>
  using Alias = Foo<Key>;
};

class Forward;
struct Test : HasTemplateParam<Forward> {
  using Foo1 = decltype(Alias{
    Key1(),
  });
};
```

clang rejects the above valid code with the following diagnostics:

```
<source>:9:20: error: invalid application of 'sizeof' to an incomplete type 'Forward'
    9 | constexpr bool C = sizeof(D);
      |                    ^~~~~~~~~
<source>:12:13: note: in instantiation of variable template specialization 'C<Forward>' requested here
   12 |   requires (C<Key>)
      |             ^
<source>:12:13: note: while substituting template arguments into constraint expression here
   12 |   requires (C<Key>)
      |             ^~~~~~
<source>:23:25: note: while checking constraint satisfaction for template '<deduction guide for Alias><Forward>' required here
   23 |   using Foo1 = decltype(Alias{
      |                         ^~~~~
<source>:23:25: note: in instantiation of function template specialization 'HasTemplateParam<Forward>::<deduction guide for Alias><Key1>' requested here
<source>:21:7: note: forward declaration of 'Forward'
   21 | class Forward;
```

It seems to be an issue in the transformed require-clause for the alias deduction guide. The require expression should be evaluated on  the type `Key1`, rather than the outer type `Forward`.

**Comment by hokein** [comment]
OK, I can confirm that the synthesized deduction guide (and its require-clause) for the alias is correct

```
FunctionTemplateDecl  <deduction guide for Alias>
|-TemplateTypeParmDecl class depth 0 index 0 Key
|-ParenExpr  '<dependent type>' lvalue
| `-UnresolvedLookupExpr  '<dependent type>' lvalue (no ADL) = 'C'
|   `-TemplateArgument type 'type-parameter-0-0'
|     `-TemplateTypeParmType  'type-parameter-0-0' dependent depth 0 index 0
`-CXXDeductionGuideDecl  <deduction guide for Alias> 'auto (type-parameter-0-0) -> Foo<type-parameter-0-0>'
  `-ParmVarDecl  'type-parameter-0-0'
```

Up to the function overload resolution point at https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/SemaTemplateDeduction.cpp#L3769-L3772, everything appears to be in order. The instantiated deduction guide looks like:

```
CXXDeductionGuideDecl <deduction guide for Alias> 'auto (Key1) -> Foo<Key1>' implicit_instantiation
|-TemplateArgument type 'Key1'
| `-RecordType 'Key1'
|   `-CXXRecord 'Key1'
`-ParmVarDecl 'Key1'
```

The issue seems to be in the `CheckInstantiatedFunctionTemplateConstraints(...)`.

**Comment by shafik** [comment]
If you switch `Key1` and `Forward` it fails as expected: https://godbolt.org/z/Pbzs7E3YY

this seems to have landed after clang-18, do you know which change brought this in?

**Comment by hokein** [comment]
>  this seems to have landed after clang-18, do you know which change brought this in?

I think this is caused by the recent changes to support CTAD for alias.

> OK, I can confirm that the synthesized deduction guide (and its require-clause) for the alias is correct
> 
> ```
> FunctionTemplateDecl  <deduction guide for Alias>
> |-TemplateTypeParmDecl class depth 0 index 0 Key
> |-ParenExpr  '<dependent type>' lvalue
> | `-UnresolvedLookupExpr  '<dependent type>' lvalue (no ADL) = 'C'
> |   `-TemplateArgument type 'type-parameter-0-0'
> |     `-TemplateTypeParmType  'type-parameter-0-0' dependent depth 0 index 0
> `-CXXDeductionGuideDecl  <deduction guide for Alias> 'auto (type-parameter-0-0) -> Foo<type-parameter-0-0>'
>   `-ParmVarDecl  'type-parameter-0-0'
> ```

Turns out it was wrong, the depth of the `TemplateTypeParam` in the require-clause is mixed up, and it seems like clang expects it to be `1` instead of `0`.

Taking on a working case (normal CTAD):

```
template <class D>
constexpr bool C = sizeof(D);

template <class T>
struct HasTemplateParam {
  template <class Key>
  struct Foo {
    Foo(Key);
  };

  template <class Key>
  requires (C<Key>)
  Foo(Key) -> Foo<Key>;
};

class Forward;
class Key1 {};
void kkk() {
  HasTemplateParam<Forward>::Foo k = Key1();
}
```
The explicit deduction guide for `Foo` inside the template specialization `HasTemplateParam<Forward>` is:

```
|-FunctionTemplateDecl 0x5560902690c0 <line:11:3, line:13:22> col:3 <deduction guide for Foo>
|   | |-TemplateTypeParmDecl 0x556090267b28 <line:11:13, col:19> col:19 class depth 0 index 0 Key
|   | |-ParenExpr 0x556090266d70 <line:12:12, col:19> '<dependent type>' lvalue
|   | | `-UnresolvedLookupExpr 0x556090266cf8 <col:13, col:18> '<dependent type>' lvalue (no ADL) = 'C' 0x556090245da0
|   | |   `-TemplateArgument type 'Key'
|   | |     `-TemplateTypeParmType 0x556090266ca0 'Key' dependent depth 1 index 0
|   | |       `-TemplateTypeParm 0x556090266c48 'Key'
|   | `-CXXDeductionGuideDecl 0x556090268ff8 <line:13:3, col:22> col:3 <deduction guide for Foo> 'auto (Key) -> Foo<Key>'
|   |   `-ParmVarDecl 0x556090268df8 <col:7> col:10 'Key' 'Key'
|   |     `-TemplateTypeParmType 0x556090267b80 'Key' dependent depth 0 index 0
|   |       `-TemplateTypeParm 0x556090267b28 'Key'
``` 

Note the difference in the occurrence of template parameter `Key` in the require expression (depth `1`) and the function parameter (depth `0`), even though they refer to the same template parameter.

My understanding is that this subtle difference is [intentional](https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/SemaConcept.cpp#L664-L666). When clang evaluates the constraint, it requires the entire template argument list (even the outer template is instantiated). @erichkeane can you confirm?

**Comment by zyn0217** [comment]
> My understanding is that this subtle difference is [intentional](https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/SemaConcept.cpp#L664-L666). When clang evaluates the constraint, it requires the entire template argument list (even the outer template is instantiated).

I think your understanding is correct because in [`TemplateDeclInstantiator::VisitTemplateTypeParmDecl`](https://github.com/llvm/llvm-project/blob/55c6bda01ef5a166a69b43956775272d9d67bda5/clang/lib/Sema/SemaTemplateInstantiateDecl.cpp#L2937-L2954), we won't update the depth of the parameter to which a constraint refers unless `EvaluateConstraints` is set on.

https://github.com/llvm/llvm-project/blob/55c6bda01ef5a166a69b43956775272d9d67bda5/clang/lib/Sema/SemaTemplateInstantiate.cpp#L3100-L3104

**Comment by erichkeane** [comment]
> > this seems to have landed after clang-18, do you know which change brought this in?
> 
> I think this is caused by the recent changes to support CTAD for alias.
> 
> > OK, I can confirm that the synthesized deduction guide (and its require-clause) for the alias is correct
> > ```
> > FunctionTemplateDecl  <deduction guide for Alias>
> > |-TemplateTypeParmDecl class depth 0 index 0 Key
> > |-ParenExpr  '<dependent type>' lvalue
> > | `-UnresolvedLookupExpr  '<dependent type>' lvalue (no ADL) = 'C'
> > |   `-TemplateArgument type 'type-parameter-0-0'
> > |     `-TemplateTypeParmType  'type-parameter-0-0' dependent depth 0 index 0
> > `-CXXDeductionGuideDecl  <deduction guide for Alias> 'auto (type-parameter-0-0) -> Foo<type-parameter-0-0>'
> >   `-ParmVarDecl  'type-parameter-0-0'
> > ```
> 
> Turns out it was wrong, the depth of the `TemplateTypeParam` in the require-clause is mixed up, and it seems like clang expects it to be `1` instead of `0`.
> 
> Taking on a working case (normal CTAD):
> 
> ```
> template <class D>
> constexpr bool C = sizeof(D);
> 
> template <class T>
> struct HasTemplateParam {
>   template <class Key>
>   struct Foo {
>     Foo(Key);
>   };
> 
>   template <class Key>
>   requires (C<Key>)
>   Foo(Key) -> Foo<Key>;
> };
> 
> class Forward;
> class Key1 {};
> void kkk() {
>   HasTemplateParam<Forward>::Foo k = Key1();
> }
> ```
> 
> The explicit deduction guide for `Foo` inside the template specialization `HasTemplateParam<Forward>` is:
> 
> ```
> |-FunctionTemplateDecl 0x5560902690c0 <line:11:3, line:13:22> col:3 <deduction guide for Foo>
> |   | |-TemplateTypeParmDecl 0x556090267b28 <line:11:13, col:19> col:19 class depth 0 index 0 Key
> |   | |-ParenExpr 0x556090266d70 <line:12:12, col:19> '<dependent type>' lvalue
> |   | | `-UnresolvedLookupExpr 0x556090266cf8 <col:13, col:18> '<dependent type>' lvalue (no ADL) = 'C' 0x556090245da0
> |   | |   `-TemplateArgument type 'Key'
> |   | |     `-TemplateTypeParmType 0x556090266ca0 'Key' dependent depth 1 index 0
> |   | |       `-TemplateTypeParm 0x556090266c48 'Key'
> |   | `-CXXDeductionGuideDecl 0x556090268ff8 <line:13:3, col:22> col:3 <deduction guide for Foo> 'auto (Key) -> Foo<Key>'
> |   |   `-ParmVarDecl 0x556090268df8 <col:7> col:10 'Key' 'Key'
> |   |     `-TemplateTypeParmType 0x556090267b80 'Key' dependent depth 0 index 0
> |   |       `-TemplateTypeParm 0x556090267b28 'Key'
> ```
> 
> Note the difference in the occurrence of template parameter `Key` in the require expression (depth `1`) and the function parameter (depth `0`), even though they refer to the same template parameter.
> 
> My understanding is that this subtle difference is [intentional](https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/SemaConcept.cpp#L664-L666). When clang evaluates the constraint, it requires the entire template argument list (even the outer template is instantiated). @erichkeane can you confirm?

Right, that is correct.  Constraints should NOT be instantiated at all unless they are being evaluated, this is so that they can refer to changes in types that happen after instantiation (and are useful for using them in CRTP in particular).

Thus, we don't substitute them at all if at all possible (and the AST always stores the uninstantiated version).  As a by-product of this, we end up having to recollect the entire set of template argument lists when we check constraints.

**Comment by hokein** [comment]
Thanks for the confirmation and clarification, @zyn0217, @erichkeane.

> Thus, we don't substitute them at all if at all possible (and the AST always stores the uninstantiated version). As a by-product of this, we end up having to recollect the entire set of template argument lists when we check constraints.

And in the implementation, we take a shortcut and reuse the require-clause of the primary (uninstantiated) template. In this example, the require-clause of the deduction guide `Foo` in `HasTemplateParam<Forward>` is the one in the primary template `HasTemplateParam`.

Given the way constraints work in clang, the `transformRequireClause` for alias CTAD is broken.

When we synthesize the alias deduction guide from the underlying deduction guide, we "replace" all occurrences of template parameters of the underlying deduction guide with the alias RHS template arguments. The RHS arguments come from the alias template in the instantiated `HasTemplateParam<Forward>` (note that the template argument `Key` in `using Alias = Foo<Key>` is `type-parameter-0-0` (depth:0, index: 0)). Thus, we end up having `type-parameter-0-0` in the require-clause of the final alias deduction guide.

One way to fix the require-clause depth issue is to use the alias template in the primary `HasTemplateParam` template when doing the transform specifically for require-clause, as this alias template has original depth information.
