### ISSUE TITLE
Raising awareness over xz compromise

### ISSUE THREAD

**Issue by joycebrum** [llvm/llvm-project#90218]
I'm reaching out to check if you might have been using a compromised version of the xz library (versions 5.6.0 or 5.6.1).  A recent security vulnerability was discovered in these versions, and I wanted to raise awareness over it to ensure no vulnerable version is being used.

Since only a few versions of linux distributions were affected (mostly testing and experimental versions), I know it is very unlikely that llvm-project got affected. But either way, since llvm actively uses xz on the released tarballs, could you please confirm if the project has directly installed xz versions 5.6.0 or 5.6.1 or either used one of the linux distribution affected versions? The linux distribution versions affected can be seen at [XZ Utils backdoor update: Which Linux distros are affected and what can you do?](https://www.helpnetsecurity.com/2024/03/31/xz-backdoored-linux-affected-distros/#:~:text=It%20has%20been%20established%20that%20XZ%20Utils%20versions%205.6.,that%20listens%20for%20SSH%20connections.)

I appreciate your time and attention to this matter.

**Comment by dtcxzyw** [comment]
cc @tstellar

**Comment by tstellar** [comment]
@joycebrum The tarballs were packaged using xz-5.2.5.  We also have community contributed binaries that were compressed using xz, the best way to find out what versions were used is to ask on  https://discourse.llvm.org/c/infrastructure/release-testers/66.
