### ISSUE TITLE
llvm/lib/Target/AMDGPU/SIMachineFunctionInfo.cpp:113: Possible bad expression ?

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#90281]
Static analyser cppcheck says:

llvm/lib/Target/AMDGPU/SIMachineFunctionInfo.cpp:113:38: style: Same expression on both sides of '||'. [duplicateExpression]

Source code is

  if (!AMDGPU::isGraphics(CC) ||
      ((CC == CallingConv::AMDGPU_CS || CC == CallingConv::AMDGPU_CS) &&
       ST.hasArchitectedSGPRs())) {

Suggest code rework.

**Comment by arsenm** [comment]
I think this is also missing the AMDGPU_CS_Chain and AMDGPU_CS_ChainPreserved cases
