### ISSUE TITLE
[libc] [docs] Broken links related to 'libc/config/linux/riscv64'

### ISSUE THREAD

**Issue by jchzhou** [llvm/llvm-project#90316]
A simple issue: 
Link [1](https://github.com/llvm/llvm-project/blob/9145514fde484916971e6bb147c18f9235a9f2b5/libc/docs/date_and_time.rst?plain=1#L25) and [2](https://github.com/llvm/llvm-project/blob/9145514fde484916971e6bb147c18f9235a9f2b5/libc/docs/math/index.rst?plain=1#L80) are pointing to `libc/config/linux/riscv64` which in the path is `libc/config/linux/riscv` instead.

1. https://github.com/llvm/llvm-project/blob/9145514fde484916971e6bb147c18f9235a9f2b5/libc/docs/date_and_time.rst?plain=1#L25
2. https://github.com/llvm/llvm-project/blob/9145514fde484916971e6bb147c18f9235a9f2b5/libc/docs/math/index.rst?plain=1#L80

Question: Considering riscv32 exists, should we: 
1. use the 'riscv' folder for both riscv{32,64} codes?
2. rename `riscv` to `riscv64`?
3. continue to denote `riscv64` with `riscv` and clarify it somewhere?

**Comment by justinchang91** [comment]
Hi! I would like to work on this issue :)

**Comment by justinchang91** [comment]
Looks like this issue has been solved already in this [commit](https://github.com/llvm/llvm-project/pull/100578/commits/384c10cb5932239e6689a7f1184174550abed32c) by @mikhailramalho.

Are we good to close this issue?

cc: @nickdesaulniers

**Comment by nickdesaulniers** [comment]
Yes, good catch! Thanks for finding the relevant commit that addressed this!
