### ISSUE TITLE
*(uint16*)==uint16 code gen (x86_64)

### ISSUE THREAD

**Issue by ordinary-github-user** [llvm/llvm-project#90355]
https://godbolt.org/z/K7abn3T1s

```c++
bool test(std::size_t ptr)
{
    return *(const std::uint16_t*)(ptr+10) == std::uint16_t(0x1234);
}
```

clang
```asm
0f b7 47 0a           movzx  eax,WORD PTR [rdi+0xa]
3d 34 12 00 00        cmp    eax,0x1234
0f 94 c0              sete   al
c3                    ret
```

gcc
```asm
66 81 7f 0a 34 12     cmp    WORD PTR [rdi+0xa],0x1234
0f 94 c0              sete   al
c3                    ret
```

looks like clang's code is a bit longer, is it less efficient?
this only happen with uint16
uint8, uint32, uint64 are fine

**Comment by topperc** [comment]
I believe we're aggressively avoiding compares with 16 bit immediates due to a Length Changing Prefix(LCP) stall in the decoder on Intel CPUs. This may be less of an issue these days with the decoded instruction cache on modern CPUs.

**Comment by topperc** [comment]
I think this should maybe re-evaluated.

**Comment by Explorer09** [comment]
The test code looks poorly written. `std::size_t` is not supposed to be decoded like a pointer; such code would be problematic when brought to real world applications.

The proper types for the job are `char *` and `std::uintptr_t`.

**Comment by RKSimon** [comment]
EmitCmp already does this for Intel Atom cores - I've been meaning to generalise this with a tuning flag instead (#62952) that we can add to other CPU types.
