### ISSUE TITLE
Clang frontend command failed with exit code 139 or SIGSEGV (in another variant)

### ISSUE THREAD

**Issue by vova7878** [llvm/llvm-project#90454]
Code causing the crash:
https://godbolt.org/z/GYnh4En78

Under #if there are two variants of code that cause different error messages

Clang can't handle code like this:
`template <...> using ... = struct __attribute__((packed)) alignas(...) {...};`
Without a template compiler just says the code is incorrect

**Comment by vova7878** [comment]
I did some testing, the bug has been present since Clang 6.0.0

**Comment by shafik** [comment]
Looks like no crash on trunk: https://godbolt.org/z/3TYqEYsqT

Also looks like other implementations reject this code.

**Comment by vova7878** [comment]
>>Also looks like other implementations reject this code.

The code is completely incorrect, but should not cause a crash
