### ISSUE TITLE
llvm/lib/DWP handling of debug_str_offsets with multiple contributions produces invalid output

### ISSUE THREAD

**Issue by molar** [llvm/llvm-project#90460]
Hello 

I encountered a crash in llvm-dwarfdump which i report here https://github.com/llvm/llvm-project/issues/85900 
I have investigated a bit further and it appears that in DWARF5 the ``debug_str_offsets`` section can contain multiple contributions each with their own header. This is not accounted for in the current code that merges the sections.

**Comment by molar** [comment]
https://github.com/llvm/llvm-project/pull/90461 with an attempted fix

**Comment by oltolm** [comment]
Fixed by #90461.
