### ISSUE TITLE
Clang fails to selfhost on i386-darwin10: missing __eprintf symbol

### ISSUE THREAD

**Issue by 1ba3d143-a64b-4671-82b2-0b31cfb91709** [llvm/llvm-project#9048]
|  |  |
| --- | --- |
| Bugzilla Link | [8676](https://llvm.org/bz8676) |
| Version | trunk |
| OS | MacOS X |

## Extended Description 
A simple i386-apple-darwin10 clang selfhost fails with a linker error:

http://google1.osuosl.org:8011/builders/clang-i386-darwin10-selfhost-rel/builds/15

Undefined symbols:
  "___eprintf", referenced from:
      ___eprintf$non_lazy_ptr in libLLVMSystem.a(SearchForAddressOfSpecialSymbol.o)
     (maybe you meant: ___eprintf$non_lazy_ptr)
ld: symbol(s) not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Presumably, compiling clang with compiler-rt should fix this, but that requires ARM bits to be installed, see llvm/llvm-project#9027 .

**Comment by arsenm** [comment]
Old build problem
