### ISSUE TITLE
[-Wunsafe-buffer-usage] unsafe_buffer_usage pragmas are not preserved in precompiled headers (PCH)

### ISSUE THREAD

**Issue by danakj** [llvm/llvm-project#90501]
a.h:
```
#ifndef A_H
#define A_H

int a(int *s) {
#pragma clang unsafe_buffer_usage begin
  return s[1];
#pragma clang unsafe_buffer_usage end
}

#endif
```

main.cc:
```
#include "a.h"

int main() {
  int s[] = {1, 2, 3};
  return a(s);
}
```

build.sh:
```
#!/bin/sh
set +x

CXX=/usr/bin/clang++

echo WITHOUT PCH
$CXX -I. -Werror=unsafe-buffer-usage -c main.cc -o main || exit

echo WITH PCH
$CXX -I. -Werror=unsafe-buffer-usage -x c++-header -c a.h -o a.gch || exit
$CXX -I. -Werror=unsafe-buffer-usage -include a -c main.cc -o main || exit
```
Result:
```
$ ./build.sh
WITHOUT PCH
WITH PCH
In file included from main.cc:1:
/Users/danakj/s/repro/a.h:6:10: error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
  return s[1];
         ^
1 error generated.
```

Here's a commit that added [support for (de)serializing `#pragma pack`](https://github.com/SNSystems/llvm-debuginfo-analyzer/commit/963695562cbe907b50d360c2d115b76ba09f4953), though it will look different for pragmas that are not annotating a record.

`#pragma clang diagnostic push/ignore/pop` are preserved in the PCH, and here's part of the mechanism for doing so: https://github.com/llvm/llvm-project/blob/d566a5cd22b4a653f10698f90c691a1452dad5ce/clang/lib/Serialization/ASTWriter.cpp#L1092

Note that replacing the `clang unsafe_buffer_usage` pragmas with `clang diagnostic` pragmas does resolve the compilation error through the PCH, confirming that the latter are serialized but the former are not.

**Comment by danakj** [comment]
cc: @haoNoQ @ziqingluo-90 @jkorous-apple

**Comment by nico** [comment]
Here are a few example commits adding serialization:

6622029d5ee15bfddacbda4825804ee89f8c30e6
cbbaeb13074400ead830be88143c31e7aac3c01c
779355f96bd5e6bff40bae824f3f13ccbb30d018
4293231e50ffb7bb85d75464c52dada8204ebc79

**Comment by ziqingluo-90** [comment]
Are we good to close this issue? @danakj

**Comment by danakj** [comment]
I just tried building some of Chromium with PCH enabled and the warning enabled and it worked correctly, so yeah looks good, thanks!

**Comment by danakj** [comment]
For posterity, we can't use unsafe-buffers with PCH in Chromium still, because we also have pragmas defined by our unsafe-buffers plugin for opting entire files in/out easily, and those won't be serialized. If only there was a way to hook extra things into the AST serialization from a plugin.

Maybe Windows doesn't use AST serialization for PCH, I am not sure why that works. But Mac showed the above issue.

**Comment by ziqingluo-90** [comment]
> For posterity, we can't use unsafe-buffers with PCH in Chromium still, because we also have pragmas defined by our unsafe-buffers plugin for opting entire files in/out easily, and those won't be serialized. If only there was a way to hook extra things into the AST serialization from a plugin.
> 
> Maybe Windows doesn't use AST serialization for PCH, I am not sure why that works. But Mac showed the above issue.

Thanks for this follow-up info. Do you have a rough idea of what a general solution could be?

**Comment by danakj** [comment]
I think the solution we'd need for this particular case would be either:
- Upstream our pragmas that enable/disable Wunsafe-buffers for a file at a time (these are just better ergonomics over the range-based push/pop approach, but meaningfully better at scale of 1000s of devs interacting with them). Or
- Hooks for plugins to tell the AST serialization about pragmas, or to have callbacks when registering pragmas that allow de/serialization or something along those lines.
