### ISSUE TITLE
apt.llvm.org repository for noble (ubuntu 24.04) only provides meta packages, can not install

### ISSUE THREAD

**Issue by FalcoGer** [llvm/llvm-project#90536]
I recently upgraded from ubuntu 22.04 to 24.04. I used to get the latest clang compiler and tools from the apt repository at http://apt.llvm.org/jammy/. After the upgrade I changed the sources configuration file to use http://apt.llvm.org/noble/ instead. It exists, but it only provides meta packages. For example the `clang` package is provided with dependencies on `clang-19`. But `clang-19` is not provided.

This results in issues like this:

```text
$ sudo apt install clang

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 clang : Depends: clang-19 (>= 19~) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

My current workaround was to install these packages using aptitude, which suggests to install the old meta-package provided by the distribution's repositories (which depend on clang-18 in this case). This will allow me to use clang, and have it upgraded whenever clang-19 is available through the llvm repository.

But it has been a few days since the official release of 24.04 and still those packages are not available.

**Comment by sylvestre** [comment]
I am blocked by:
https://bugs.launchpad.net/ubuntu/+source/ubuntu-dev-tools/+bug/2058395

**Comment by mpusz** [comment]
Are there any updates on LLVM support for "noble"?

**Comment by TerrorJack** [comment]
Despite no official announcement, https://apt.llvm.org/noble already existed for some time and works for me.

**Comment by mpusz** [comment]
The "noble" repo seems to be provided but there are no new packages there. I try to update all my Clang compilers every few days but I did not see any update to any llvm package for a long time.

**Comment by sylvestre** [comment]
One of the build machines on s390x has an issue to build with noble. I will have a look

**Comment by sylvestre** [comment]
i forgot to update the website to add noble, i just did:
https://apt.llvm.org/
and fixed the build machines. I think we are good now

**Comment by mpusz** [comment]
Thanks @sylvestre! I confirm that today, I was able to upgrade many new packages for Clang and LLVM.

**Comment by sylvestre** [comment]
Thanks for confirming

**Comment by sylvestre** [comment]
@mpusz please open a new bug with step to reproduce

**Comment by mpusz** [comment]
There might still be an issue here. For the last two weeks, I have not seen an update to any clang component for LLVM 16, 17, and 18. Is it possible that apt packages are not being built again?

**Comment by sylvestre** [comment]
ack. Seems that the cleanup script didn't run
I restarted it

**Comment by sylvestre** [comment]
ok, found the actual issue, the server had a too old version of deboostrap

**Comment by sylvestre** [comment]
and fixed now, thanks for the ping!

**Comment by Bouncner** [comment]
Sorry, if that is the wrong place to ask. But do you know if 24.04 is going to ship LLVM 19 at some point?

**Comment by sylvestre** [comment]
@Bouncner yeah, wrong place to ask, please ask on discord instead...
and it is already live:
https://apt.llvm.org/noble/pool/main/l/llvm-toolchain-19/
