### ISSUE TITLE
[C++20] [Modules] Cannot export type_info/operator new/operator delete

### ISSUE THREAD

**Issue by huangqinjin** [llvm/llvm-project#90620]
#### `test.cppm`

```c++
module;

#include <stddef.h>

export module test;

extern "C++"
{
    export class type_info;                                 // 0

    export void* operator new(size_t);                      // 1
    export void* operator new[](size_t);                    // 2
    export void operator delete(void*) noexcept;            // 3
    export void operator delete[](void*) noexcept;          // 4

    export void operator delete(void*, size_t) noexcept;    // 5
    export void operator delete[](void*, size_t) noexcept;  // 6
}
```

#### targeting x86_64-linux-gnu
```shell
✗ clang --target=x86_64-linux-gnu -std=c++20 --precompile test.cppm
test.cppm:11:18: error: cannot export redeclaration 'operator new' here since the previous declaration is not exported
   11 |     export void* operator new(size_t);                      // 1
      |                  ^
note: previous declaration is here
test.cppm:12:18: error: cannot export redeclaration 'operator new[]' here since the previous declaration is not exported
   12 |     export void* operator new[](size_t);                    // 2
      |                  ^
note: previous declaration is here
test.cppm:13:17: error: cannot export redeclaration 'operator delete' here since the previous declaration is not exported
   13 |     export void operator delete(void*) noexcept;            // 3
      |                 ^
note: previous declaration is here
test.cppm:14:17: error: cannot export redeclaration 'operator delete[]' here since the previous declaration is not exported
   14 |     export void operator delete[](void*) noexcept;          // 4
      |                 ^
note: previous declaration is here
4 errors generated.
```

#### targeting x86_64-windows-msvc
```shell
✗ clang --target=x86_64-windows-msvc -std=c++20 --precompile test.cppm
test.cppm:9:18: error: cannot export redeclaration 'type_info' here since the previous declaration is not exported
    9 |     export class type_info;                                 // 0
      |                  ^
note: previous declaration is here
test.cppm:11:18: error: cannot export redeclaration 'operator new' here since the previous declaration is not exported
   11 |     export void* operator new(size_t);                      // 1
      |                  ^
note: previous declaration is here
test.cppm:12:18: error: cannot export redeclaration 'operator new[]' here since the previous declaration is not exported
   12 |     export void* operator new[](size_t);                    // 2
      |                  ^
note: previous declaration is here
test.cppm:13:17: error: cannot export redeclaration 'operator delete' here since the previous declaration is not exported
   13 |     export void operator delete(void*) noexcept;            // 3
      |                 ^
note: previous declaration is here
test.cppm:14:17: error: cannot export redeclaration 'operator delete[]' here since the previous declaration is not exported
   14 |     export void operator delete[](void*) noexcept;          // 4
      |                 ^
note: previous declaration is here
5 errors generated.
```

~~The strange thing is that other overloads of `operator new` and `operator delete` can be exported without error.~~
**Edit:** Clang does not enable sized deallocation by default, adding `-fsized-deallocation` to the command line will cause 5 & 6 failed also.

**Comment by ChuanqiXu9** [comment]
I am not sure about typeinfo but I roughtly remember these operator new and deletes are special and implicitly declarared for every module units. So the behavior about operator new and delete is more or less correct if I remember correctly.

For typeinfo, I am not sure if this is the problme of headers in windows.

**Comment by ChuanqiXu9** [comment]
Yeah, the replaceable operator new and delete are implicit declared: https://eel.is/c++draft/basic.stc.dynamic and replace it doesn't require to export it. So I think the behavior is correct.

If we can find typeinfo in the header's of windows, we can close the issue.

**Comment by huangqinjin** [comment]
> Yeah, the replaceable operator new and delete are implicit declared: https://eel.is/c++draft/basic.stc.dynamic and replace it doesn't require to export it. So I think the behavior is correct.


But below two overloads can be exported.
```c++
export void operator delete(void*, size_t) noexcept;    // 5
export void operator delete[](void*, size_t) noexcept;  // 6
```

**Comment by huangqinjin** [comment]
> If we can find typeinfo in the header's of windows, we can close the issue.

I don't understand this, does it mean `type_info` is also implicit declared?

**Comment by huangqinjin** [comment]
> > Yeah, the replaceable operator new and delete are implicit declared: https://eel.is/c++draft/basic.stc.dynamic and replace it doesn't require to export it. So I think the behavior is correct.
> 
> But below two overloads can be exported.
> 
> ```c++
> export void operator delete(void*, size_t) noexcept;    // 5
> export void operator delete[](void*, size_t) noexcept;  // 6
> ```

Ok, it is because clang does not enable sized deallocation by default, adding `-fsized-deallocation` to the command line will cause them failed also.

**Comment by ChuanqiXu9** [comment]
> > If we can find typeinfo in the header's of windows, we can close the issue.
> 
> I don't understand this, does it mean `type_info` is also implicit declared?

I mean, if we can find `typeinfo` in `stddef.h` from windows, we can close this.

**Comment by huangqinjin** [comment]
`stddef.h` is a C header, it unlikely contains `class type_info`.

Pointed out by https://github.com/microsoft/STL/issues/4643, the declaration is in`eh.h`.

**Comment by ChuanqiXu9** [comment]
Fine. Then it looks like the behavior of clang is good. I'll close the issue. Feel free to reopen this if you have different opinions.

**Comment by huangqinjin** [comment]
It doesn't explain where is the `previous declaration`. Does clang include `eh.h` implicitly?

**Comment by ChuanqiXu9** [comment]
hmm, I am not sure. It might be windows specific.

**Comment by huangqinjin** [comment]
@ChuanqiXu9 This issue is no longer repeatable with Clang 19, could you please confirm and point out which change fixed this issue, thanks.

**Comment by ChuanqiXu9** [comment]
Probably e0d66c242462?

And I'll close this. Thanks for updating.
