### ISSUE TITLE
Miscompilation of some forms of (x + y) * z

### ISSUE THREAD

**Issue by glandium** [llvm/llvm-project#90668]
Reduced testcase:
```
#include <stdint.h>
#include <stddef.h>

size_t off(int8_t a) {
    return (uint8_t)(a + 128) * 8;
}
```
With clang 18, this compiled down to:
```
        add     dil, -128
        movzx   eax, dil
        shl     eax, 3
        ret
```
With trunk, this compiles down to:
```
        movzx   eax, dil
        lea     eax, [8*rax + 1024]
        ret
```

The math in the lea is actually fine, transforming (a+128) * 8 into 8 * a + 1024. But the problem is that a is zero extended instead of sign extended, so the results are wrong for negative values.

Bisection says it started happening with 7177dc2ef7f3a50a1d8b892d7bd298f3d52a1aab.

Cc: @fengfeng09

**Comment by topperc** [comment]
I think the problem is that this code has conflated addLike and NUWAddLike.

```
@@ -2346,21 +2346,21 @@ SDValue X86DAGToDAGISel::matchIndexRecursively(SDValue N,
     }
   }
 
   // index: zext(add_nuw(x,c)) -> index: zext(x), disp + zext(c)
   // index: zext(addlike(x,c)) -> index: zext(x), disp + zext(c)
   // TODO: call matchIndexRecursively(AddSrc) if we won't corrupt sext?
```

An i8 xor with 128 is AddLike, but its not NUWAddLike.
