### ISSUE TITLE
[bug](clang) wrong generated code for auto-vectorization

### ISSUE THREAD

**Issue by zclllyybb** [llvm/llvm-project#90727]
here is a minimal reproducible example:
https://godbolt.org/z/vKjT74oKr
you can see the output asm here:
```asm
        vmovups (%rsi), %ymm0
        movq    %rdi, %rax
        movq    %rsi, %rcx
.LBB0_3:                                #   Parent Loop BB0_1 Depth=1
        vmovups 32(%rcx), %ymm1
        vmovups 64(%rcx), %ymm2
        vmovups 96(%rcx), %ymm3
        vmovups 128(%rcx), %ymm4
        vmovups 160(%rcx), %ymm5
        vmovups 192(%rcx), %ymm6
        vmovups 224(%rcx), %ymm7
        leaq    256(%rcx), %rsi
        vmovups %ymm0, (%rax)
        vmovups 256(%rcx), %ymm0
        vmovups 288(%rcx), %ymm8
        vmovups 320(%rcx), %ymm9
        vmovups 352(%rcx), %ymm10
        vmovups 384(%rcx), %ymm11
        vmovups 416(%rcx), %ymm12
        vmovups 448(%rcx), %ymm13
        vmovups 480(%rcx), %ymm14
        vmovups %ymm1, 32(%rax)
        vmovups %ymm2, 64(%rax)
        vmovups %ymm3, 96(%rax)
        vmovups %ymm4, 128(%rax)
        vmovups %ymm5, 160(%rax)
        vmovups %ymm6, 192(%rax)
        vmovups %ymm7, 224(%rax)
        leaq    256(%rax), %rdi
        vmovups %ymm0, 256(%rax)
        vmovups %ymm8, 288(%rax)
        vmovups %ymm9, 320(%rax)
        vmovups %ymm10, 352(%rax)
        vmovups %ymm11, 384(%rax)
        vmovups %ymm12, 416(%rax)
        vmovups %ymm13, 448(%rax)
        vmovups %ymm14, 480(%rax)
```
it doesn't use `ymm15` but reuses `ymm0`, just like it doesn't know that `ymm15` is available.
but adding the mfence at line 19 will get the expected output asm. it uses `ymm0` to `ymm15`.
you can see gcc here is as expected.
Is it a bug?

**Comment by efriedma-quic** [comment]
"__restrict" means that all accesses through the pointer in question don't overlap with any other memory access in the function.  So the compiler is free to reorder the loads and stores.

**Comment by zclllyybb** [comment]
> "__restrict" means that all accesses through the pointer in question don't overlap with any other memory access in the function. So the compiler is free to reorder the loads and stores.

but why not use `ymm15`? Is it as expected?

**Comment by zclllyybb** [comment]
> The register allocation heuristics prefer to use lower-numbered ymm registers. So if the compiler has a choice between using ymm0 and ymm15, it'll use ymm0.

But here ymm0 and ymm15 are not equivalent, ymm0 is already used, and if you want to use it, there is an extra overhead compared to ymm15 (a leaq, as you can see). So I don't think it's a matter of arbitrary choice between ymm0 and ymm15.

Maybe I'm wrong. Can you explain this in more depth? Thank you very much.

**Comment by efriedma-quic** [comment]
If you're interested in seeing what happens in various transforms, on godbolt, you can click "add new" -> "Opt pipeline".  (This is a wrapper around -mllvm -print-after-all.)

**Comment by zclllyybb** [comment]
> If you're interested in seeing what happens in various transforms, on godbolt, you can click "add new" -> "Opt pipeline". (This is a wrapper around -mllvm -print-after-all.)

I just want to make sure if the extra overhead from reusing ymm0 instead of using ymm15 is in line with design expectations?

**Comment by zclllyybb** [comment]
> The way you're describing the issue is not consistent with the way the compiler is reasoning about this internally. Scheduling runs before register allocation; by the time we get to register allocation, the decisions that make the code suboptimal have already happened. Maybe something could be improved here, but it has nothing to do with ymm15.

now I got it. There's a step before register allocation have unnecessarily extracted data from ymm0 and made it available. I'll try to figure out is there any possible to optimize it. Thank you very much.
