### ISSUE TITLE
[DirectX] remove module flag and function attribute not supported by DXIL

### ISSUE THREAD

**Issue by python3kgae** [llvm/llvm-project#90773]
The only module flags DXIL used are "Dwarf Version" and "Debug Info Version".

And the only string function attributes allowed in DXIL are "waveops-include-helper-lanes" and "fp32-denorm-mode".

Other string function attributes and module flags should be removed before emit DXIL.

**Comment by python3kgae** [comment]
Reopen for missing the module flag part.

**Comment by python3kgae** [comment]
Add PR to document module flag at DXC repo https://github.com/microsoft/DirectXShaderCompiler/pull/6722

**Comment by llvm-beanz** [comment]
This is a duplicate of #96912
