### ISSUE TITLE
-mmacosx-version-min improperly added to options when build isn't on Darwin

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#9081]
|  |  |
| --- | --- |
| Bugzilla Link | [8709](https://llvm.org/bz8709) |
| Version | trunk |
| OS | Linux |
| Attachments | [patch to relocate target=darwin check within preceding host=darwin check](https://user-images.githubusercontent.com/60944935/143742372-d91c3108-027a-4464-9de7-73b17473db08.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

A check is made if the target for the built toolchain is darwin, and a darwin-specific option is added.

This option isn't applicable, however, when the toolchain is being built, or hosted, on another platform (eg, linux).

I've attached a patch that relocates this check within another check that the host platform is darwin.

**Comment by arsenm** [comment]
Patch is against removed makefile build
