### ISSUE TITLE
[HLSL] Set up internal nightly build that stores artifacts

### ISSUE THREAD

**Issue by damyanp** [llvm/llvm-project#90874]
In order to demonstrate that we have working end-to-end support for using Clang to build a simple shader we need to show that this is possible for someone without a checkout of the llvm-project repo achieve.

MVP for this would be to modify the our internal validation pipeline to also store prebuilt assets that can be used internally. As we don't intend to release these publicly we can avoid various compliance requirements.

**Comment by bob80905** [comment]
Closed with an internal PR
