### ISSUE TITLE
clang does not support / recognize attribute `[[msvc::noinline]]`

### ISSUE THREAD

**Issue by Febbe** [llvm/llvm-project#90941]
I am linking to glib-2.0, which defines a macro `#define G_NO_INLINE [[msvc::noinline]]`  `#if G_CXX_STD_CHECK_VERSION (20) && _MSC_VER >= 1927`.
But clang-cl does not support this attribute. I am sure, clang supports `[[gnu::noinline]]`. Therefore, it would pretty easy to also support `[[msvc::noinline]]` we only need an alias to it.

**Comment by simonzgx** [comment]
I'll work on this.

**Comment by simonzgx** [comment]
Hi all, I want to confirm that our goal is to make clang support ***msvc::noinline*** attribute and no longer report compilation warnings like ***unknown attribute 'noinline' ignored [-Wunknown-attributes]*** , is that right?

**Comment by Febbe** [comment]
> Hi all, I want to confirm that our goal is to make clang support ***msvc::noinline*** attribute and no longer report compilation warnings like ***unknown attribute 'noinline' ignored [-Wunknown-attributes]*** , is that right?

Yes that's right.

**Comment by simonzgx** [comment]
Hi all, I have created a PR(#91720), please review.

**Comment by Febbe** [comment]
You should mark anyone in your PR, who works on the clang-cl backend. Also recheck, if the way is correct you added `[[msvc::noinline]]` that attribute is backend specific and should be added as alias only for the CL backend. There is already a gnu alias in the gnu backend. The msvc alias should be implemented in a similar way.
