### ISSUE TITLE
Github `Comment on an issue` Action failing

### ISSUE THREAD

**Issue by patrick-rivos** [llvm/llvm-project#91033]
https://github.com/llvm/llvm-project/actions/runs/8946350596
https://github.com/llvm/llvm-project/actions/workflows/issue-write.yml

`Unable to download artifact(s): Bad credentials`
Looks like it's been happening for 10 hours now.

No incident reported on github's side: https://www.githubstatus.com/

**Comment by boomanaiden154** [comment]
@tstellar It seems like `secrets.ISSUE_WRITE_DOWNLOAD_ARTIFACT` needs to be regenerated potentially?

**Comment by tstellar** [comment]
This is fixed now, and I will re-run all the failed jobs.

**Comment by boomanaiden154** [comment]
@tstellar I'm assuming the token just needed to be rolled? Is there something we can do in the future so that the token gets rolled before it ends up expiring?

**Comment by tstellar** [comment]
@boomanaiden154 Yes, I need to set up a reminder to do it.
