### ISSUE TITLE
Clang format pointer alignment does not work when the type is defined via a macro

### ISSUE THREAD

**Issue by ilan-schemoul** [llvm/llvm-project#91062]
Formatting with the setting `PointerAlignmentStyle: right` gives an unexpected output when formatting a code where the type is defined through a macro
```c
struct e_t {
  int a;
};

typedef struct e_t e_t;
#define q(e) e_t

int a(e_t *argc, q(e) * argv[]) { printf("%s", argv[1] + 1); }
```
Note that we have `q(e) * argv[]` instead of `q(e) *argv[]`

**Comment by owenca** [comment]
You need to use [`TypenameMacros`](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#typenamemacros):
```
TypenameMacros: [q]
```
