### ISSUE TITLE
bugpoint should run tests in parallel

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#911]
|  |  |
| --- | --- |
| Bugzilla Link | [539](https://llvm.org/bz539) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @Bigcheese |

## Extended Description 
I will send a box of salty dead fish to anyone who can multithread bugpoint (or
rather, get bugpoint to spawn parallel gcc/llc processes in some effective manner)

**Comment by arsenm** [comment]
Obsoleted by llvm-reduce which does support parallel reduction
