### ISSUE TITLE
LLVM 18.1.5 Release Assets missing some code!

### ISSUE THREAD

**Issue by DigOrDog** [llvm/llvm-project#91121]
I have downloaded the source code for LLVM version 18.1.5 from [a source link](https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-18.1.5.tar.gz). However, after decompressing the downloaded source code, I discovered that the changeFCMPPredToAArch64CC method in the AArch64GlobalISelUtils.cpp file, located in the ./llvm/lib/Target/AArch64/GISel/ directory, does not include handling for FCMP_TRUE and FCMP_FALSE. This omission is related to a fix or feature discussed in the [issue](https://github.com/llvm/llvm-project/issues/86917) on the LLVM project's GitHub repository. Can you explain what this situation entails?

**Comment by marcauberer** [comment]
The fix was not downported to the `release/18.x` branch yet.
I just triggered the downport. Sorry for the inconvenience.

**Comment by marcauberer** [comment]
The cherry-pick is now merged to the `release/18.x` branch, so it will be included in the 18.1.6 release. I am closing this issue, if your problem persists, feel free to reopen it.
