### ISSUE TITLE
[packaging] apt.llvm.org/llvm.sh no workaround for noble dist structure.

### ISSUE THREAD

**Issue by 1aam2am1** [llvm/llvm-project#91147]
apt.llvm.org/llvm.sh adds 'archive_uri-http_apt_llvm_org_noble_-noble.list' source list, with:
deb http://apt.llvm.org/noble/ llvm-toolchain-noble-17 main
\# deb-src http://apt.llvm.org/noble/ llvm-toolchain-noble-17 main

But https://apt.llvm.org/noble/dists/
has only llvm-toolchain-noble, no distinctions of versions.

Error:
E: The repository 'http://apt.llvm.org/noble llvm-toolchain-noble-17 Release' does not have a Release file.
  Failed to install llvm via system package manager Error: Command failed with exit code 100: sudo 'bash' '/tmp/llvm-setup-cpp.sh' '17' 'all'

**Comment by sylvestre** [comment]
it is now fixed
