### ISSUE TITLE
Incorrect OR of conversion function templates against non-template conversion functions

### ISSUE THREAD

**Issue by be579e8c-b74b-475b-a126-3b8cefdd833c** [llvm/llvm-project#9122]
|  |  |
| --- | --- |
| Bugzilla Link | [8750](https://llvm.org/bz8750) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor |

## Extended Description 
Clang accepts the following code

```cpp
void f(int); 
void f(long); 

struct A { 
  template<typename T> operator T(); 
  operator long(); 
};

int main() {
  f(A());
}
```

However it's supposed to reject it: For the first f, you end up using the "operator T<int>" (since int -> int is better than long -> int), and for the second f, you end up using the non-template operator long (since it's a non-template, it's preferred over the function template specialization). 

The two user defined conversion sequences created aren't comparable because they don't use the same conversion function. So the call is ambiguous.

**Comment by shafik** [comment]
All implementations reject the first example: https://godbolt.org/z/sb9KW9zbs

and accept the second one: https://godbolt.org/z/YYe3147qr

I think this is correct, please reopen if you feel otherwise
