### ISSUE TITLE
[Clang] Attribute `[[assume]]` accepts unexpanded pack

### ISSUE THREAD

**Issue by Sirraide** [llvm/llvm-project#91232]
This code compiles, which means it looks like I forgot to check for unexpanded parameter packs here (https://godbolt.org/z/scafKKjsG):
```c++
template <bool ...val>
void f() { 
    [[assume(val)]]; 
}

```

**Comment by cor3ntin** [comment]
We are missing a call to `DiagnoseUnexpandedParameterPack` in `ActOnCXXAssumeAttr`.
It should be fairly easy to fix

**Comment by azmat-y** [comment]
Hi @Sirraide I would like to work on this issue. Could you assign this to me?

**Comment by Sirraide** [comment]
Feel free to @ me when you open a pr

**Comment by azmat-y** [comment]
@Sirraide I just created a pull request. Please Review.

**Comment by azmat-y** [comment]
@Sirraide  I accidentally closed my pull request because of discarding the commit. I will open another pr after doing the changes. Should I keep both the tests and modifications in the same pr?

**Comment by azmat-y** [comment]
And should I keep them both in the same commit?
