### ISSUE TITLE
[libc++][clang] Libc++ implements `std::from_chars` with default argument as one more overload, is it allowed?

### ISSUE THREAD

**Issue by SainoNamkho** [llvm/llvm-project#91268]
https://eel.is/c++draft/charconv#from.chars-1 says the signature should be
```c++
constexpr from_chars_result from_chars(const char* first, const char* last,
                                       integer-type& value, int base = 10);
```
But is implemented as
https://github.com/llvm/llvm-project/blob/fcf341d3ddfe2289ac88aa3c122b25df8732cc8e/libcxx/include/__charconv/from_chars_integral.h#L222-L233

I'm not should if there's any legal ways to inspect this. And if the following code is well-formed, it does make a difference.
https://godbolt.org/z/vE95qzhEM
```c++
#include <charconv>

static_assert(requires {
    static_cast<std::from_chars_result(*)(const char*, const char*, int&)>(std::from_chars);
});
```

In addition, if this code is rejected, should the _requires_ expression cause a hard error, or the code fail due to `static_assert` failure?

**Comment by philnik777** [comment]
I'm not aware of any way to detect this other than through non-conforming code, so I'd say it is a conforming implementation. Your code isn't conforming because you're forming a pointer to `std::from_chars`, which isn't an addressable function. http://eel.is/c++draft/namespace.std#6

**Comment by SainoNamkho** [comment]
> I'm not aware of any way to detect this other than through non-conforming code, so I'd say it is a conforming implementation. Your code isn't conforming because you're forming a pointer to `std::from_chars`, which isn't an addressable function. http://eel.is/c++draft/namespace.std#6

I'm sorry for unintentionally dropping out the `decltype` when editing my initial post. 

How about this? https://godbolt.org/z/rxdxqTExb
```c++
#include <type_traits>
#include <charconv>

static_assert(requires {
    typename std::type_identity_t<decltype(std::from_chars<int>)>;
});
```
(Msvc rejects it because the standard does not say it can be template, and Microsoft STL lists the overload exhaustively).

And I might argue that it is still unclear whether the code is conforming.

The paragraph you excerpts says
> Unless F is designated an addressable function, the behavior of a C++ program is unspecified (possibly ill-formed) if it explicitly or implicitly attempts to form a pointer to F.

The meaning of _attempts_ seems unclear and inconsistent in the standard regarding unevaluated contexts.
I found https://eel.is/c++draft/basic.lval#10
> A program that **attempts** to modify an object through a nonmodifiable lvalue or through an rvalue is ill-formed.

And https://eel.is/c++draft/basic.lval#11
> If a program **attempts** to access ([defns.access]) the stored value of an object through a glvalue through which it is not type-accessible, the behavior is undefined.

However, they don't mean https://godbolt.org/z/91vd513Pq
```c++
#include <type_traits>
const int i = 1;
// Reads are ruled out of _access_ when not odr-used but writes are not.
std::remove_reference_t<decltype(*reinterpret_cast<long*>(const_cast<int*>(&i)) = 2)> j = 3;
```
is ill-formed.

But <https://eel.is/c++draft/expr.static.cast#4>'s
> The conversion is ill-formed when **attempting** to convert an expression of class type to an inaccessible or ambiguous base class.

makes https://godbolt.org/z/dxxe8o3a5 ill-formed:
```c++
struct A{};
struct B : A, A{};
decltype(static_cast<A>(B{})) a;
```

The term _form a pointer_ seems working syntactically, not about actually evaluating the expression, but https://eel.is/c++draft/class.cdtor#3
>  To **form a pointer** to (or access the value of) a direct non-static member of an object obj, the construction of obj shall have started and its destruction shall not have completed, otherwise the computation of the pointer value (or accessing the member value) results in undefined behavior.

is not likely for make 
```c++
struct O {
    int* o;
};
struct A
{
    int a;
};

struct B : O, A
{
    B() : O(decltype(&this->a){}) {}
};
```
ill-formed.

@frederick-vs-ja How do you think of this?

**Comment by frederick-vs-ja** [comment]
As the restriction on taking addresses was added in C++20 (by [P0551R3](https://wg21.link/p0551r3)), should we guarantee the behavior of taking the address of `std::from_chars` in C++17? @philnik777

> (Msvc rejects it because the standard does not say it can be template, and Microsoft STL lists the overload exhaustively).
> 
> And I might argue that it is still unclear whether the code is conforming.

As the exact form of the overload set is unspecifed, the well-formedness of `std::from_chars<int>` itself is unspecified, so the example using it can be considered non-conforming, even without the introduction of (non-)addressable functions.

> The term _form a pointer_ seems working syntactically,

I'd say "_form a pointer_" is not itself a term in the standard.

Anyway, it's unlikely that the intent is that taking address of function is only OK in unevaluated contexts. I _think_ the intent should be relaxing the restriction on the exact forms of (non-addessable) standard functions, which also affects unevaluated contexts.

I think the standard wording is too terse on non-addressable functions. Perhaps we should explicitly identify possibly unevaluated function-to-pointer conversion or reference binding in [namespace.std]. An LWG issue or editorial issue seems needed.

**Comment by frederick-vs-ja** [comment]
The situation becomes chaotic if an overload set is consist of standard and program-defined functions.

I guess the following example needs to be well-formed. It seems to me that only the address of a program-defined function is taken.
```C++
#include <charconv>
#include <type_traits> 

namespace fvs {
template <class I, std::enable_if_t<std::is_integral_v<I>, int> = 0>
inline std::from_chars_result from_chars(const char*, const char*, I&) { return {}; }
}

int main()
{
    using std::from_chars; // perhaps shouldn't be considered
    using fvs::from_chars;
    auto p [[maybe_unused]] =
        static_cast<std::from_chars_result(*)(const char*, const char*, int&)>(from_chars);
}
```

[Godbolt link](https://godbolt.org/z/PjYsKGTP4)

**Comment by ldionne** [comment]
I believe the intent of the Standard is to let implementers do things like have different overloads instead of using a default argument. It is now clear that this intent is not fully captured by the existing wording (which only prevents people from taking the address of non-addressable functions), however I don't think this should be considered a bug in libc++ per se. At the very least, this isn't a guarantee we are willing to provide so we'd have a good chat with WG21 if they thought this was a legitimate use.

I would suggest opening a LWG issue to clarify the intent of the Standard. In the meantime, I'll close this since I don't think we want to change anything in libc++.
