### ISSUE TITLE
AllocaInst::getAllocationSize/AllocaInst::getAllocationSizeInBits should check for overflow

### ISSUE THREAD

**Issue by efriedma-quic** [llvm/llvm-project#91380]
Currently, the code just blindly multiplies the size, and can therefore return a nonsense result.  (The behavior isn't really defined in the overflow case, but reasoning based on the overflowed computation is likely to lead to weird results.)

https://github.com/llvm/llvm-project/blob/7115ed0fff027b65fa76fdfae215ed1382ed1473/llvm/lib/Transforms/Utils/InlineFunction.cpp#L2622 has code to compute the allocation size while conservatively checking for overflow; we should use similar logic, then make the inliner call getAllocationSize().  Maybe use the multiply-with-overflow helper from CheckedArithmetic.h instead of writing out that code.

**Comment by moghya** [comment]
Hi @efriedma-quic could you please assign this to me, I would like to work and get this fixed. Thanks.

**Comment by cjkenn** [comment]
@moghya are you still looking into this?

**Comment by tszhin-swe** [comment]
@cjkenn  can i be assigned? thx
