### ISSUE TITLE
libc++ iota constructor check hardened mode

### ISSUE THREAD

**Issue by gonzalobg** [llvm/llvm-project#91385]
@ldionne do you think that checking in `iota_view` constructor whether "bound is reachable from value" (pre-condition) would be a suitable check for hardened mode?

That would catch synthetic cases like:

```c++
iota(10, 5);
```

but also more common cases like:

```c++
iota(0, (int)vec.size());
```

where `(int)vec.size()` wraps around and ends up negative.

The compiler error for the most common `iota(0, vec.size())` with clang is not great. I was also wondering if instead of raising the error via a failure in the requires clause of the `iota_view` constructor guideline, it could be maybe raised earlier, e.g., from `iota` itself, with a nice message.

**Comment by ldionne** [comment]
We already implement that check, but it's basically always disabled: https://github.com/llvm/llvm-project/blob/b7768c5485844306cd3c8afeef609ddf9d79696a/libcxx/include/__ranges/iota_view.h#L316.

I think there's value in checking this more often.

**Comment by ldionne** [comment]
Extracted the poor diagnostic part of this issue into https://github.com/llvm/llvm-project/issues/96794.

**Comment by gonzalobg** [comment]
Thank you Louis!
