### ISSUE TITLE
Static initializers in locale.cpp .CRT$XCU

### ISSUE THREAD

**Issue by chrdavis** [llvm/llvm-project#91387]
Ever since the below changes we have seen an increase in global static initializers contributing to windows modules .CRT$XCU.  These impact performance as it increased code getting paged in and running at load time.

https://github.com/llvm/llvm-project/commit/1a5af34e6fcb56098e67d3272e1e89a05528f15e#diff-463b7637691d6f87528cb5cfd02889eff500ca37ace5cb450cbd7829aa429488

**Comment by ldionne** [comment]
Is the new static initializer you're seeing `locale::__imp::classic_locale_imp_`? That one should be `constinit` so there should be no initializer. The other statics already existed before that patch and they are function-local statics.

Either way, this is a tradeoff between the current solution or more work at runtime (ref counting the default locale like we did before), and I am tempted to think that we are making the right call here.

**Comment by ldionne** [comment]
Closing as invalid until we have more information. For now my understanding is that this is `constinit` and shouldn't end up with a static initializer.
