### ISSUE TITLE
[HLSL] Support RWBuffer loads and stores

### ISSUE THREAD

**Issue by bogner** [llvm/llvm-project#91405]
This issue tracks support for basic RWBuffer support such that we can read and write from a simple buffer:
```hlsl
RWBuffer<int> In;
RWBuffer<int> Out;

[numthreads(8,1,1)]
void main(uint GI : SV_GroupIndex) {
  Out[GI] = In[GI];
}
```

## Work
- [ ] #91366
- [ ] #91367
- [ ] #90631 (Or at least specifically the HLSLResource type)
- [ ] #95952
- [ ] #95956
- [ ] #84824

**Comment by damyanp** [comment]
This has been superceded by llvm/wg-hlsl#7
