### ISSUE TITLE
Poor diagnostics and error recovery for templated method call on mis-declared class member

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#9145]
|  |  |
| --- | --- |
| Bugzilla Link | [8773](https://llvm.org/bz8773) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 
$ cat ~/llvm/testcases/bad_templated_method_call.cc
```c++
class Bar;
class Baz {
  void f() {
    obj.method<Bar>();
  }
  Foo obj;
};
```
$ clang -fsyntax-only ~/llvm/testcases/bad_templated_method_call.cc 
```
/home/matthewbg/llvm/testcases/bad_templated_method_call.cc:6:3: error: unknown
      type name 'Foo'
  Foo obj;
  ^
/home/matthewbg/llvm/testcases/bad_templated_method_call.cc:4:16: error: 'Bar'
      does not refer to a value
    obj.method<Bar>();
               ^
/home/matthewbg/llvm/testcases/bad_templated_method_call.cc:1:7: note: declared
      here
class Bar;
      ^
/home/matthewbg/llvm/testcases/bad_templated_method_call.cc:4:21: error: 
      expected expression
    obj.method<Bar>();
                    ^
3 errors generated.
```
=====

Having "obj.method<Bar>();" parsed as an arithmetic expression is really confusing. It would be nice if there were some better recovery here. Also, if 'obj' is a local instead of a class member, it incurs a "use of undeclared identifier" error at the start of the method call statement, which helps point out what's wrong.

**Comment by philnik777** [comment]
Fixed in Clang 9: https://godbolt.org/z/qYqP8Td6o
