### ISSUE TITLE
argv marked external

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#9147]
|  |  |
| --- | --- |
| Bugzilla Link | [8775](https://llvm.org/bz8775) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
DSA marks the argv argument to main as external. This could be special cased, to not be marked so.

**Comment by arsenm** [comment]
Pretty sure "DSA" no longer exists
