### ISSUE TITLE
miscompile due to interaction between returned and range attributes

### ISSUE THREAD

**Issue by regehr** [llvm/llvm-project#91481]
https://alive2.llvm.org/ce/z/w_kBtY

this function:
```llvm
define i32 @f(i32 %0) {
  %2 = shl i32 %0, 1
  %3 = sub nuw i32 %2, %0
  ret i32 %3
}
```
is being optimized to:
```lllvm
define range(i32 0, -1) i32 @f(i32 returned %0) local_unnamed_addr #0 {
  ret i32 %0
}

attributes #0 = { mustprogress nofree norecurse nosync nounwind willreturn memory(none) }
```
but when we pass -1 to the optimized code this is out-of-bounds for the range, creating poison, violating the rules for `returned`

cc @nunoplopes

**Comment by dtcxzyw** [comment]
> but when we pass -1 to the optimized code this is out-of-bounds for the range, creating poison, violating the rules for returned

The source function also returns poison when we pass -1.

**Comment by regehr** [comment]
> The source function also returns poison when we pass -1.

That's right, but breaking the `returned` rule has to be immediate UB, not poison.

I'll just quote Nuno on this:

> It has to be UB so refinement composes. It's not obvious, but it can't be poison.
> Imagine you pass a non-poison value to a function and expect it to be returned. Also, you branch on it. Then you inline the function and it turns out the value is poison. Then you get UB.
> So the original program before inlining had to be UB already for the refinement to hold.

**Comment by dtcxzyw** [comment]
https://github.com/llvm/llvm-project/blob/ba5170f430b027c6d290f57d7a5d7ba6ee2b265b/llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp#L3779-L3786

IIUC the `returned` attribute just indicates `it is safe to replace the return value with one of its argument`. So it is ok to replace poison with -1 in this case.

cc @nikic Any thoughts?

**Comment by nikic** [comment]
Does this question reduce down to: "Is it only valid to replace the return value with the argument, or is it also valid to replace the argument with the return value?"

I think if it's just the former this is fine, while for the latter it's a problem. Do we do the latter anywhere?

**Comment by nikic** [comment]
> Do we do the latter anywhere?

I'm reasonably sure we don't do this in IR, but I guess the backend does this.

**Comment by dtcxzyw** [comment]
cc @RKSimon @topperc

**Comment by regehr** [comment]
> Does this question reduce down to: "Is it only valid to replace the return value with the argument, or is it also valid to replace the argument with the return value?"
> 
> I think if it's just the former this is fine, while for the latter it's a problem. Do we do the latter anywhere?

ok, this is interesting. if we want to go with a definition other than Alive's current strict interpretation of `returned` then let's try to come up with something that we can formalize (and document) and then I'll turn a fuzzer loose and it and we can just look for violations.

**Comment by nunoplopes** [comment]
I think you guys are right. I shouldn't be replying to emails about semantics after 10pm 😅
I've changed Alive2 to return poison if the returned value is different than the `returned` argument. I'll run it over the tests and report back if anything is amiss.
