### ISSUE TITLE
[DirectX] Add TableGen records for all supported DXIL ops

### ISSUE THREAD

**Issue by bharadwajy** [llvm/llvm-project#91496]
Currently only a small number of DXIL operations are specified. The remaining ones, along with tests to verify DXIL lowering, need to added.

Enhancements/tweaks may need to be done as specification of different kinds of DXIL ops is added.

**Comment by damyanp** [comment]
Plan is to use other work (eg intrinsics, feature implementation) to drive generation of the dxil ops that we need.
