### ISSUE TITLE
[RISCV] Backport "riscv-isa" module metadata to llvm 18

### ISSUE THREAD

**Issue by topperc** [llvm/llvm-project#91513]
This improves LTO support for RISC-V.

Relevant commits
f45b9d987dfc5904d4129aa006ab20614b3174e3
6afda56faa6260cff4e6e9264226737d96d952c1
891172d9be01dd7c7e5298f2d8fdb143add448da

I don't think they can be cherry-picked so I'll create a PR.

CC: @ilovepi

**Comment by asb** [comment]
@topperc I assume this was just left open accidentally and can be closed?
