### ISSUE TITLE
clang-format misbehavior for comment

### ISSUE THREAD

**Issue by dyzsr** [llvm/llvm-project#91552]
Running `clangformat --style=LLVM` on

``` cpp
void f() { /* OK */ }
void g() {
  /* OK */
}
```

results in

``` cpp
void f() { /* OK */
}
void g() { /* OK */ }
```

Which is confusing.
Clang version is 16.0.2.

**Comment by rymiel** [comment]
This has already been fixed by e1a4b0032f89355da94a5505bf308ab12668b1b0. The fix is present in clang-format 18
