### ISSUE TITLE
Could 

### ISSUE THREAD

**Issue by yuhui518** [llvm/llvm-project#91563]

**Comment by benshi001** [comment]
It would be better to ask your question at https://discourse.llvm.org/c/beginners/17

**Comment by yuhui518** [comment]
I download clang+llvm-18.1.5-x86_64-pc-windows-msvc.tar.xz and install this tool. I add "-fsanitize=address -fsanitize-recover=address,all" when I compile my project with VS2022. When I run my program ,the asan reports errors：
start ---- PutTextDataToClipboardFuzz
0AddressSanitizer: CHECK failed: asan_malloc_win.cpp:238 "(((HEAP_ALLOCATE_UNSUPPORTED_FLAGS & dwFlags) != 0 && "unsupported flags")) != (0)" (0x0, 0x0) (tid=41744)
AddressSanitizer: CHECK failed: asan_malloc_win.cpp:238 "(((HEAP_ALLOCATE_UNSUPPORTED_FLAGS & dwFlags) != 0 && "unsupported flags")) != (0)" (0x0, 0x0) (tid=41744)
AddressSanitizer: CHECK failed: sanitizer_symbolizer_win.cpp:66 "((dbghelp && "failed to load dbghelp.dll")) != (0)" (0x0, 0x0) (tid=41744)
my log print "GlobalLock unicodetext data failed with error 0x6".
0x6 is ERROR_INVALID_HANDLE, but I can run my program without asan.
So I think windows's llvm asan doesn't support GlobalLock function.
