### ISSUE TITLE
[X86] Suboptimal for logical test -> 0/1 with width > 8bit.

### ISSUE THREAD

**Issue by jsonn** [llvm/llvm-project#9157]
|  |  |
| --- | --- |
| Bugzilla Link | [8785](https://llvm.org/bz8785) |
| Version | trunk |
| OS | Linux |
| Blocks | llvm/llvm-bugzilla-archive#26299  |
| CC | @lattner,@davidbolvansky |

## Extended Description 
Test program:
```
int testf(int f)
{
	return f != 0;
}
```
Resulting assembler:
```
	testl	%edi, %edi
	setne	%al
	movzbl	%al, %eax
```
More compact assembler:
```
	xorl	%eax, %eax
	testl	%edi, %edi
	setne	%al
```
This saves one byte and may result in better scheduling.

**Comment by RKSimon** [comment]
Resolving - this has been fixed for a long time, and icc moved to the same pattern almost as long ago
