### ISSUE TITLE
[DirectX] Version in ProgramHeader is wrong on big endian host

### ISSUE THREAD

**Issue by python3kgae** [llvm/llvm-project#91793]
MinorVersion and MajorVersion in llvm::dxbc::ProgramHeader used bitfield.
But the order of allocation of bit-field within a unit is implementation-defined.

Wrong version will be read on big endian host right now.

**Comment by bogner** [comment]
The `SignatureElement` struct in DXContainer.h also uses bitfields and should be looked at as well.

**Comment by bogner** [comment]
Note that this isn't necessarily that the wrong version will be read on a big endian host - it could potentially be read incorrectly on *any* host depending on the compiler.

From [C++17's [class.bit]](https://timsong-cpp.github.io/cppwp/n4659/class.bit#1)
> Bit-fields are packed into some addressable allocation unit. [ Note: Bit-fields straddle allocation units on some machines and not on others. Bit-fields are assigned right-to-left on some machines, left-to-right on others.  — end note ]
