### ISSUE TITLE
[libc] Add deduction guide and LIBC_INLINE to `cpp::expected` and `cpp::unexpected`

### ISSUE THREAD

**Issue by SchrodingerZhu** [llvm/llvm-project#91904]
`cpp::expected` inside libc's support library needs to be updated:
- functions inside a header library should be marked with `LIBC_INLINE`
- proper deduction guide should be added so that we can avoid extra type parameters such that `<Error>` in `cpp::unexpected<Error>(Error::Invalid)`.

**Comment by changkhothuychung** [comment]
can this issue be assigned to me? I would like to take this issue, thanks!

**Comment by changkhothuychung** [comment]
@SchrodingerZhu 

all the functions of `cpp::expected` and `cpp::unexpected` are member functions, so they are inline by default, what functions are we trying to add `LIBC_INLINE` here?

**Comment by SchrodingerZhu** [comment]
`LIBC_INLINE` may not be the same as `inline`. Our policy is to always add these markers.
