### ISSUE TITLE
opencl.ocl.version can not reflect opencl cpp source

### ISSUE THREAD

**Issue by haonanya** [llvm/llvm-project#91912]
the option -cl-std=cl3.0 emits same metadata as -cl-std=clc++2021 and -cl-std=cl2.0 emits same metadata  as -cl-std=clc++. In llvm-spirv, spirv.Source metadata is determined by opencl.ocl.version, which results in unexpected spirv.Source metadata for opencl cpp source https://github.com/KhronosGroup/SPIRV-Headers/blob/main/include/spirv/unified1/spirv.hpp#L67,L68.
@svenvh, @AnastasiaStulova, @MrSidims, @VyacheslavLevytskyy

**Comment by svenvh** [comment]
It is probably long overdue to emit some metadata to distinguish between C and C++ sources.  I've created https://github.com/llvm/llvm-project/pull/92140 as a first step to address this.
