### ISSUE TITLE
[libc][docs] Outdated Code Review section in 'libc/src/math/docs/add_math_function.md'

### ISSUE THREAD

**Issue by cyuria** [llvm/llvm-project#91934]
Found this outdated section in the developer docs.
https://github.com/llvm/llvm-project/blob/ae2a18d6cbc3328410bdb7e629fdc59766b73e4b/libc/src/math/docs/add_math_function.md?plain=1#L197-L202
The section mentions and links to phabricator.
Possible Solutions:
- Remove entirely, using github should be implicit I think
- Change to mention github's PR review system
- Do nothing, it doesn't pose any problems, although the link is outdated

**Comment by lntue** [comment]
Change to mention github's PR review system sounds good to me.  Thanks!
