### ISSUE TITLE
[mlir][spirv] Add integration tests for `vector.shuffle` / `vector.interleave` 

### ISSUE THREAD

**Issue by kuhar** [llvm/llvm-project#91978]
These go through several layers of decomposition / unrolling / emulation when targeting SPIR-V and it would be good to have e2e coverage there.

The new tests should be added under: https://github.com/llvm/llvm-project/tree/main/mlir/test/mlir-vulkan-runner

**Comment by Rajveer100** [comment]
@kuhar 
Could you give a comprehensive insight about what has to be done?

**Comment by joker-eph** [comment]
Can we avoid using the Vulcan runner and start writing tests using the mlir-cpu-runner by now? Is there anything missing?

**Comment by rengolin** [comment]
> Can we avoid using the Vulcan runner and start writing tests using the mlir-cpu-runner by now? Is there anything missing?

Agreed. We should probably create a plan to deprecate the vulkan runner and rename the `mlir-cpu-runner` into just `mlir-runner`.

**Comment by kuhar** [comment]
@antiagainst for vulkan runner impl

**Comment by kuhar** [comment]
Ah, we have a tracking issue for vulkarn runner already: https://github.com/llvm/llvm-project/issues/73457

**Comment by antiagainst** [comment]
Yes. An there are interested contributors there. I asked them about the updates. To me the test is disjoint to the harness though. I think we should be able to add more tests while upgrading the harness.
