### ISSUE TITLE
What does this "%mlir_cuda_runtime"  refer to?

### ISSUE THREAD

**Issue by BruceDai003** [llvm/llvm-project#92059]
https://github.com/llvm/llvm-project/blob/e20800c16f0570562fea31e9a02d65ba56e6858a/mlir/test/Integration/GPU/CUDA/all-reduce-and.mlir#L4

Hello, I'm new to these tests. I'm trying to run this, but don't know what these `"%mlir_cuda_runtime", "%mlir_runner_utils", cubin-format=%gpu_compilation_format"` refer to. Could anybody tell me what they are? Thanks.

**Comment by joker-eph** [comment]
These are runtime libraries. It'll be expanded by lit according to the config here: https://github.com/llvm/llvm-project/blob/d488a54b408046eb4286727053cd44166dcd4daa/mlir/test/lit.cfg.py#L135

`mlir_cuda_runtime` is built here for example: https://github.com/llvm/llvm-project/blob/d488a54b408046eb4286727053cd44166dcd4daa/mlir/lib/ExecutionEngine/CMakeLists.txt#L232
