### ISSUE TITLE
Inconsistent results when using --buffer-deallocation

### ISSUE THREAD

**Issue by wangyongj1a** [llvm/llvm-project#92056]
I have the following MLIR program:
test.mlir:
```
module {
  func.func @func0(%arg0: tensor<19xi32>) -> (){
    %0 = arith.constant 2 : index
    %1 = tensor.extract %arg0[%0] : tensor<19xi32>
    vector.print %1 : i32
    return
  }
  func.func private @func1() {
    %0 = arith.constant 10 : i32
    %1 = tensor.from_elements %0 : tensor<1xi32>
    %2 = tensor.from_elements %0, %0, %0, %0, %0, %0, %0, %0, %0, %0, %0, %0, %0, %0, %0, %0, %0, %0, %0 : tensor<19xi32>
    call @func0(%2) : (tensor<19xi32>) -> ()
    return
  }
}
```
When I tried to lower the program with  ```mlir-opt --tensor-bufferize --buffer-deallocation --convert-scf-to-cf --convert-cf-to-llvm --func-bufferize --convert-func-to-llvm --convert-index-to-llvm --convert-vector-to-llvm --finalize-memref-to-llvm --convert-arith-to-llvm --reconcile-unrealized-casts test.mlir```, and executed the executable file, I got inconsistent results over multiple runs.
I noticed that after using the passes ```--tensor-bufferize --buffer-deallocation```, the program was lowered to:
```
module {
  func.func @func0(%arg0: tensor<19xi32>) {
    %0 = bufferization.to_memref %arg0 : memref<19xi32>
    %c2 = arith.constant 2 : index
    %1 = memref.load %0[%c2] : memref<19xi32>
    vector.print %1 : i32
    return
  }
  func.func private @func1() {
    %c10_i32 = arith.constant 10 : i32
    %alloc = memref.alloc() {alignment = 64 : i64} : memref<1xi32>
    %c0 = arith.constant 0 : index
    memref.store %c10_i32, %alloc[%c0] : memref<1xi32>
    memref.dealloc %alloc : memref<1xi32>
    %alloc_0 = memref.alloc() {alignment = 64 : i64} : memref<19xi32>
    %c0_1 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c2 = arith.constant 2 : index
    %c3 = arith.constant 3 : index
    %c4 = arith.constant 4 : index
    %c5 = arith.constant 5 : index
    %c6 = arith.constant 6 : index
    %c7 = arith.constant 7 : index
    %c8 = arith.constant 8 : index
    %c9 = arith.constant 9 : index
    %c10 = arith.constant 10 : index
    %c11 = arith.constant 11 : index
    %c12 = arith.constant 12 : index
    %c13 = arith.constant 13 : index
    %c14 = arith.constant 14 : index
    %c15 = arith.constant 15 : index
    %c16 = arith.constant 16 : index
    %c17 = arith.constant 17 : index
    %c18 = arith.constant 18 : index
    memref.store %c10_i32, %alloc_0[%c0_1] : memref<19xi32>
    memref.store %c10_i32, %alloc_0[%c1] : memref<19xi32>
    memref.store %c10_i32, %alloc_0[%c2] : memref<19xi32>
    memref.store %c10_i32, %alloc_0[%c3] : memref<19xi32>
    memref.store %c10_i32, %alloc_0[%c4] : memref<19xi32>
    memref.store %c10_i32, %alloc_0[%c5] : memref<19xi32>
    memref.store %c10_i32, %alloc_0[%c6] : memref<19xi32>
    memref.store %c10_i32, %alloc_0[%c7] : memref<19xi32>
    memref.store %c10_i32, %alloc_0[%c8] : memref<19xi32>
    memref.store %c10_i32, %alloc_0[%c9] : memref<19xi32>
    memref.store %c10_i32, %alloc_0[%c10] : memref<19xi32>
    memref.store %c10_i32, %alloc_0[%c11] : memref<19xi32>
    memref.store %c10_i32, %alloc_0[%c12] : memref<19xi32>
    memref.store %c10_i32, %alloc_0[%c13] : memref<19xi32>
    memref.store %c10_i32, %alloc_0[%c14] : memref<19xi32>
    memref.store %c10_i32, %alloc_0[%c15] : memref<19xi32>
    memref.store %c10_i32, %alloc_0[%c16] : memref<19xi32>
    memref.store %c10_i32, %alloc_0[%c17] : memref<19xi32>
    memref.store %c10_i32, %alloc_0[%c18] : memref<19xi32>
    %0 = bufferization.to_tensor %alloc_0 : memref<19xi32>
    memref.dealloc %alloc_0 : memref<19xi32>
    call @func0(%0) : (tensor<19xi32>) -> ()
    return
  }
}
```
The memory of ```%alloc_0``` seems to be deallocated before the related tensor ```%0``` was used as an attribute in the function call. I also tried to use the pass ```--buffer-deallocation-simplification``` after ```--buffer-deallocation```, but it seems couldn't help with this case. 
I'm not sure if there is any bug in my program or the wrong usage of ```--buffer-deallocation``` and ```--buffer-deallocation-simplification``` that caused this error.
My git version is 4c79d38f82e1f6fe8575d88d8c74f2f1806b19ce.

**Comment by IanWood1** [comment]
I think the problem originates from this series of passes`--one-shot-bufferize=dialect-filter=tensor,bufferization --buffer-deallocation --func-bufferize`. This results in:


```mlir
  %0 = bufferization.to_tensor %alloc_0 : memref<19xi32>
  %1 = bufferization.to_memref %0 : memref<19xi32>
  memref.dealloc %alloc_0 : memref<19xi32>
  %2 = call @func0(%1) : (memref<19xi32>) -> i32
```

which gets canonicalized to 

```mlir
 memref.dealloc %alloc : memref<19xi32>
%0 = call @func0(%alloc) : (memref<19xi32>) -> i32
```

I think it might be problematic to run deallocation before bufferizing all ops. But It could also be that `to_tensor` -> `to_memref` can't be folded (instead replaced with an allocation and copy). But I'm not sure, hopefully this helps provide some context to others can help

**Comment by wangyongj1a** [comment]
I tried to reproduce this issue on history commit versions, and I found these inconsistence results can be reproduced on commit 6bf043e7433680c6f4e36393734ef83699b30f14, and cannot be reproduced on the previous commit b2ffc867ada60fde361c198dfc31d9c90f70e1aa. Hi @maerhart, sorry to disturb but I was wondering if you would mind taking a look at this problem?

**Comment by wangyongj1a** [comment]
> It seems like you are using the deprecated buffer deallocation pass. Please use this pipeline instead for deallocation: https://github.com/llvm/llvm-project/blob/main/mlir/include/mlir/Dialect/Bufferization/Pipelines/Passes.h
> 
> Please also refer to https://mlir.llvm.org/docs/OwnershipBasedBufferDeallocation/ for more information about how the deallocation works and how it is intended to be used. General bufferization documentation is here: https://mlir.llvm.org/docs/Bufferization/
> 
> The pass you are using is marked deprecated here: https://mlir.llvm.org/docs/BufferDeallocationInternals/
> 
> As part of this deprecation, the deallocation capabilities of one-shot-bufferization were removed (the commit you pointed to above).

Thank you for your response! I tried using ```--ownership-based-buffer-deallocation``` to replace the ```--buffer-deallocation``` in the above pass, and the inconsistent result appeared to be fixed.
However, I've also got a test.mlir:
```
module {

  func.func @tensor_i32(%arg0: tensor<?xi32>) -> i32 {
    %idx0 = index.constant 0
    %idx1 = index.constant 1
    %c0_i32 = arith.constant 0 : i32
    %dim = tensor.dim %arg0, %idx0 : tensor<?xi32>
    %0 = scf.for %arg1 = %idx0 to %dim step %idx1 iter_args(%arg2 = %c0_i32) -> (i32) {
      %extracted = tensor.extract %arg0[%arg1] : tensor<?xi32>
      vector.print %extracted : i32
      %1 = arith.addi %arg2, %extracted : i32
      scf.yield %1 : i32
    }
    return %0 : i32
  }
  func.func @func1() -> f32 {

    %c9 = arith.constant 9 : index

    %c20_i32 = arith.constant 20 : i32
    %from_elements_69 = tensor.from_elements %c20_i32 : tensor<1xi32>

    %95 = scf.index_switch %c9 -> tensor<?x?xi32>
    case 1 {
      %from_elements_246 = tensor.splat %c20_i32 : tensor<2x1xi32>
      %cast_247 = tensor.cast %from_elements_246 : tensor<2x1xi32> to tensor<?x?xi32>
      scf.yield %cast_247 : tensor<?x?xi32>
    }
    default {
      %from_elements_243 = tensor.splat %c20_i32 : tensor<2x1xi32>
      %cast_244 = tensor.cast %from_elements_243 : tensor<2x1xi32> to tensor<?x?xi32>
      scf.yield %cast_244 : tensor<?x?xi32>
    }

    %cast_210 = tensor.cast %from_elements_69 : tensor<1xi32> to tensor<?xi32>
    %362 = call @tensor_i32(%cast_210) : (tensor<?xi32>) -> i32
    %collapsed_213 = tensor.collapse_shape %95 [[0, 1]] : tensor<?x?xi32> into tensor<?xi32>
    %365 = call @tensor_i32(%collapsed_213) : (tensor<?xi32>) -> i32

    vector.print %365 : i32
    %0 = arith.sitofp %365 : i32 to f32
    return %0 : f32
  }
}
```
When I ran 
```
/data/tmp/v1113/llvm-project/build/bin/mlir-opt \
--one-shot-bufferize="dialect-filter=tensor,linalg,bufferization" \
--convert-linalg-to-loops --convert-vector-to-llvm --convert-index-to-llvm --expand-strided-metadata --lower-affine --ownership-based-buffer-deallocation --canonicalize --buffer-deallocation-simplification --bufferization-lower-deallocations --cse --canonicalize --convert-scf-to-cf --convert-arith-to-llvm --func-bufferize --one-shot-bufferize="dialect-filter=tensor" --finalize-memref-to-llvm --convert-func-to-llvm --reconcile-unrealized-casts test.mlir  | /data/tmp/v1113/llvm-project/build/bin/mlir-cpu-runner -e func1 --shared-libs=/data/tmp/v1113/llvm-project/build/lib/libmlir_runner_utils.so,/data/tmp/v1113/llvm-project/build/lib/libmlir_c_runner_utils.so
```
on the program, I got inconsistent results over multiple runs.

However, when I ran 
```
/data/tmp/v1113/llvm-project/build/bin/mlir-opt \
--one-shot-bufferize \
--convert-linalg-to-loops --convert-vector-to-llvm --convert-index-to-llvm --expand-strided-metadata --lower-affine --ownership-based-buffer-deallocation --canonicalize --buffer-deallocation-simplification --bufferization-lower-deallocations --cse --canonicalize --convert-scf-to-cf --convert-arith-to-llvm --func-bufferize --one-shot-bufferize="dialect-filter=tensor" --finalize-memref-to-llvm --convert-func-to-llvm --reconcile-unrealized-casts test.mlir  | /data/tmp/v1113/llvm-project/build/bin/mlir-cpu-runner -e func1 --shared-libs=/data/tmp/v1113/llvm-project/build/lib/libmlir_runner_utils.so,/data/tmp/v1113/llvm-project/build/lib/libmlir_c_runner_utils.so
```
on the program, I got the expected consistent results of:
```
20
20
20
40
4.000000e+01
```
I noticed that in https://mlir.llvm.org/docs/OwnershipBasedBufferDeallocation/, it said "it's recommended to perform all bufferization here at latest, any allocations inserted after this point have to be handled manually". I wonder whether the use of ```--one-shot-bufferize="dialect-filter=tensor,linalg,bufferization"``` in the first command is correct. (whether this inconsistency exposes a bug, or it is caused by the wrong use)
My git version is de0fd64bedd23660f557833cc0108c3fb2be3918.

**Comment by matthias-springer** [comment]
A few things that I noticed in your pipeline:
- Don't call any `*-bufferize` passes. E.g., don't call `func-bufferize`. These passes are deprecated. Most of them have already been removed. `func-bufferize` is going to be deleted soon. (There's a PR on Github.)
- Run `one-shot-bufferize` only once and without "filter". The filter flag is mainly for testing.
- Run `one-shot-bufferize` with the `bufferize-function-boundaries` flag to make sure that func.func etc. are bufferized.
- Run `buffer-deallocation-pipeline` after `one-shot-bufferize`. The name is not ideal, but this pipeline uses the new ownership-based buffer deallocation pass.
- Do not use `buffer-deallocation`. This pass is deprecated and should be deleted.

**Comment by wangyongj1a** [comment]
> I'm not sure what the best pipeline for doing bufferization is nowadays. It looks wrong to me to call any bufferization passes after deallocation. At the point where you call deallocation, all tensors should have been lowered already and no passes that create more tensors should usually be called afterward. Also, I don't see a reason why you'd want to add a dialect filter to one-shot-bufferize.
> 
> CC @matthias-springer



> A few things that I noticed in your pipeline:
> 
> * Don't call any `*-bufferize` passes. E.g., don't call `func-bufferize`. These passes are deprecated. Most of them have already been removed. `func-bufferize` is going to be deleted soon. (There's a PR on Github.)
> * Run `one-shot-bufferize` only once and without "filter". The filter flag is mainly for testing.
> * Run `one-shot-bufferize` with the `bufferize-function-boundaries` flag to make sure that func.func etc. are bufferized.
> * Run `buffer-deallocation-pipeline` after `one-shot-bufferize`. The name is not ideal, but this pipeline uses the new ownership-based buffer deallocation pass.
> * Do not use `buffer-deallocation`. This pass is deprecated and should be deleted.

I've got it, Thank you all so much for your detailed explanation!
