### ISSUE TITLE
[clang-tidy] create a check that looks for constructing a string from a nullptr

### ISSUE THREAD

**Issue by LegalizeAdulthood** [llvm/llvm-project#92061]
Consider the following code:

```
std::string foo()
{
    return nullptr;
}
```
See [compiler explorer example](https://godbolt.org/z/azW348cbd)

This code compiles just fine with no warnings or errors, but crashes when you run it.  We should be able to detect cases where a `nullptr` is used to construct a string, at least in the simple case above.  I had a real-world bug that was exactly the above scenario, although I have simplified the example to remove irrelevant code.  Obviously more sophisticated data flow analysis can propagate `nullptr` through usages until it hits a `std::basic_string` constructor, but even detecting the above simple case would be a useful start.

Note: there are several constructor overloads that take a pointer to a character as an argument and they are all invalid if the pointer is `nullptr`.

**Comment by chrchr-github** [comment]
Caught by `bugprone-string-constructor` and `clang-analyzer-cplusplus.StringChecker`:
~~~
<source>:9:12: warning: constructing string from nullptr is undefined behaviour [bugprone-string-constructor]
    9 |     return nullptr;
      |            ^
<source>:9:12: warning: The parameter must not be null [clang-analyzer-cplusplus.StringChecker]
~~~

**Comment by vaisakh-prod** [comment]
Hi @chrchr-github, 
are you looking into this??
@LegalizeAdulthood 
I'd like to give have a look at this.

**Comment by carlosgalvezp** [comment]
Then I would say we don't need a third check ;)

**Comment by LegalizeAdulthood** [comment]
which two checks report the issue?
