### ISSUE TITLE
[lld] Why use PROVIDE_HIDDEN defined symbol in linker script is GLOBAL when partial linking?

### ISSUE THREAD

**Issue by hstk30-hw** [llvm/llvm-project#92116]
lds:
```
SECTIONS
{
  . mySec:
  {
    PROVIDE_HIDDEN(__mysec_start = .);
    KEEP (*(SORT(.probs*)))
    PROVIDE_HIDDEN(__mysec_end = .);
  }
};
```
main.c
```
extern void *__mysec_start;
extern void *__mysec_end;

int getNum(void) {
    return &__mysec_end - &__mysec_start;
}

int main() {
  return getNum();
}
```

Command like:

```
clang -c main.c -o main.o
ld.lld main.o -o main -T lds -r
```

And the symbol info like:

     8: 0000000000000000     0 NOTYPE  GLOBAL HIDDEN     1 __mysec_end
     9: 0000000000000000     0 NOTYPE  GLOBAL HIDDEN     1 __mysec_start

without `-r` the output like:

     8: 0000000000000000     0 NOTYPE  LOCAL HIDDEN     1 __mysec_end
     9: 0000000000000000     0 NOTYPE  LOCAL HIDDEN     1 __mysec_start

And `ld` always `LOCAL` w/wo `-r`

`gold` is `GLOBAL` with `-r`.

I'm not found the standard about this (about the bindind of symbol defined in linker script).

**Comment by hstk30-hw** [comment]
CC @rui314 @MaskRay

**Comment by MaskRay** [comment]
The generic ABI says:

> A hidden symbol contained in a relocatable object must be either removed or converted to STB_LOCAL binding by the link-editor when the relocatable object is included in an executable file or shared object.

lld converts hidden symbols to STB_LOCAL when producing an EXE/DSO. GNU ld and gold don't do this.
(gold seems inconsistent. It creates STB_LOCAL STV_HIDDEN `_GLOBAL_OFFSET_TABLE_`)

**Comment by hstk30-hw** [comment]
In my example, the symbol is defined in linker script, not in  a relocatable object. It's a trick :)

So, it seems lld not follow the rule. lld should output LOCAL HIDDEN symbol like ld?

**Comment by MaskRay** [comment]
lld actually follows the rule but GNU ld/gold don't.

Keeping a global symbol in relocatable output allows `ld -r a.o b.o -o ab.ro; ld ab.o c.o` to have a similar behavior to `ld a.o b.o c.o`.
