### ISSUE TITLE
Thread-safety diagnostic uses wrong capability name for negative requirements

### ISSUE THREAD

**Issue by apasel422** [llvm/llvm-project#92118]
Example: https://godbolt.org/z/hEdfTWYPK

Note that the output from the positive requirement correctly labels the capability as `xyz` while the output from the negative requirement incorrectly labels the capability as `mutex`.

**Comment by antoniofrighetto** [comment]
I'm taking a look, although it seems we fail at classifying the capability, defaulting to `"mutex"` in `ClassifyDiagnostic` when building the capability expression.
