### ISSUE TITLE
[DirectX] Introduce llvm.dx.updateCounter intrinsic and lower it to the dxil op

### ISSUE THREAD

**Issue by bogner** [llvm/llvm-project#92147]
We need the intrinsic lowering for the [bufferUpdateCounter](https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#bufferupdatecounter) DXIL op, which is emitted to implement [RWStructuredBuffer](https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/sm5-object-rwstructuredbuffer)'s increment and decrement counter methods as well as `Append`/`Consume` methods on [AppendStructuredBuffer](https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/sm5-object-appendstructuredbuffer) and [ConsumeStructuredBuffer](https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/sm5-object-consumestructuredbuffer).

This is needed for #92148

https://godbolt.org/z/qKGdYj5zj
```
struct MyStruct {
    float4 a;
};

AppendStructuredBuffer<MyStruct> AB;
ConsumeStructuredBuffer<MyStruct> CB;

[numthreads(4,1,1)]
void main() {
  MyStruct val = CB.Consume();
  AB.Append(val);
}
```

**Comment by joaosaffran** [comment]
I can work on that
