### ISSUE TITLE
[DAGCombine][RISC-V] VSelect miscompile at -O1

### ISSUE THREAD

**Issue by patrick-rivos** [llvm/llvm-project#92193]
Reduced LLVM IR:
``` llvm ir
target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
target triple = "riscv64-unknown-linux-gnu"

@g.var.0 = global i8 5
@g.arr.0 = global i32 0

define i8 @foo() {
entry:
  store i32 4, ptr @g.arr.0, align 32

  %g.var.0.val = load i8, ptr @g.var.0, align 1
  %loaded.arr = insertelement <4 x i8> <i8 1, i8 1, i8 1, i8 1>, i8 %g.var.0.val, i64 0

  %g.arr.elem.0 = load i32, ptr @g.arr.0, align 32
  %insert.0 = insertelement <4 x i32> zeroinitializer, i32 %g.arr.elem.0, i64 0
  %cmp.0 = icmp ult <4 x i32> %insert.0, <i32 1, i32 1, i32 1, i32 1>

  %shuffle.0 = shufflevector <4 x i32> %insert.0, <4 x i32> zeroinitializer, <4 x i32> zeroinitializer
  %or.0 = or <4 x i32> %shuffle.0, <i32 1, i32 1, i32 1, i32 1>

  %sel.0 = select <4 x i1> %cmp.0, <4 x i32> zeroinitializer, <4 x i32> %or.0

  %trunc.0 = trunc <4 x i32> %sel.0 to <4 x i8>

  %mul.0 = mul <4 x i8> %loaded.arr, %trunc.0
  %reduced.mul.0 = call i8 @llvm.vector.reduce.mul.v4i8(<4 x i8> %mul.0)

  ret i8 %reduced.mul.0
}
```

This should return 0 but instead returns 24 when invoking llc with -O1 or above.

Found via fuzzer.

Root of the issue is here:
https://github.com/llvm/llvm-project/blob/c5cd049566a795ba5de88dfbb2eb563cad4a9d8a/llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp#L12145-L12146
We continue without invalidating `bool AllAddOne = true;` and `bool AllSubOne = true;`.

This means at the end of the loop both `AllAddOne=true` and `AllSubOne=true` which isn't possible.

I'll file a PR shortly.

**Comment by patrick-rivos** [comment]
Godbolt: https://godbolt.org/z/q51qbqjPx

**Comment by patrick-rivos** [comment]
The i64 is introduced here: https://github.com/llvm/llvm-project/blob/c5cd049566a795ba5de88dfbb2eb563cad4a9d8a/llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp#L1625-L1638
I think this is because i32 is an illegal type for risc-v by default: https://github.com/llvm/llvm-project/blob/c5cd049566a795ba5de88dfbb2eb563cad4a9d8a/llvm/lib/Target/RISCV/RISCVISelLowering.cpp#L80-L81

**Comment by topperc** [comment]
it's a little surprising to me that we promote in getConstant without checking NewNodesMustHaveLegalTypes.

**Comment by patrick-rivos** [comment]
I'm still new to this part of the code so I can investigate further. I wasn't sure how surprising the type promotion from i32 to i64 was so I didn't dig in as much as I could have.

**Comment by topperc** [comment]
> I'm still new to this part of the code so I can investigate further. I wasn't sure how surprising the type promotion from i32 to i64 was so I didn't dig in as much as I could have.

It's been like that for a 12 years or more.

After type legalization we do need to avoid creating illegal types, but not necessarily before type legalization. It's weird to me that we do it before type legalization because it means different build_vectors have different scalar element types in the same phase of SelectionDAG depending on how they got created.
