### ISSUE TITLE
MergeFunction can't merge functions because of jump tables

### ISSUE THREAD

**Issue by yamt** [llvm/llvm-project#92201]
i observed MergeFunc missing merging opportunities due to switch jump tables.

workarounds i can think of:
* -fno-jump-tables
* move mergefunc before switch jump tables transformation
* move mergefunc after constmerge, which would merge switch jump tables

**Comment by nikic** [comment]
> move mergefunc after constmerge, which would merge switch jump tables

This sounds reasonable to me. I think it is a lot more likely that MergeFuncs can benefit from ConstMerge than the other way around.

**Comment by PiJoules** [comment]
@yamt do you have a small example of IR where there's missed merging?

**Comment by yamt** [comment]
> @yamt do you have a small example of IR where there's missed merging?

see:
https://github.com/yamt/garbage/tree/ebf39eafc3e61df66f109cc1115b3fde0fa79327/llvm/mergefunc/1

mergefunc can't merge functions because of tables:
https://github.com/yamt/garbage/blob/ebf39eafc3e61df66f109cc1115b3fde0fa79327/llvm/mergefunc/1/log#L5855-L5914

in the final output, functions are identical because of later constmerge:
https://github.com/yamt/garbage/blob/ebf39eafc3e61df66f109cc1115b3fde0fa79327/llvm/mergefunc/1/a.ll
