### ISSUE TITLE
`export inline` not initialize before static block

### ISSUE THREAD

**Issue by RichardLuo0** [llvm/llvm-project#92347]
Step to reproduce:
1. clone https://github.com/RichardLuo0/clang-export-inline
2. `clang++ -std=c++20 -fprebuilt-module-path=<path to std> hello.cppm --precompile -o Hello.pcm`
3. `clang++ -std=c++20 -fprebuilt-module-path=<path to std> -fmodule-file=Hello=Hello.pcm .\main.cpp libc++std.a .\Hello.pcm -o Hello.exe`

Expected:
construct
Module initialization...
00007FF6ED0971B8
00007FF6ED0971B8
main:
00007FF6ED0971B8
10
destruct

Actual output:
Module initialization...
00007FF6ED0971B8
00007FF6ED0971B8
construct
main:
00007FF6ED0971B8
0
destruct

If I instead use the good old header file pattern and put the inline variable in the header file, I will get the expected result.

**Comment by ChuanqiXu9** [comment]
It looks the behavior matches the current wording:  (https://clang.llvm.org/docs/StandardCPlusPlusModules.html#module-initializers):

> All importable module units are required to emit an initializer function to handle the dynamic initialization of non-inline variables in the module unit.

> Translation units that explicitly or implicitly import a named module must call the initializer functions of the imported named module within the sequence of the dynamic initializers in the translation unit. Initializations of entities at namespace scope are appearance-ordered.

What is the practical impact for this? Also it is not suggested to declare variables as inline in module purview since the ABI group feel the semantics is a little bit odd.

**Comment by RichardLuo0** [comment]
I want to make a shared variable across all modules, very much like the `inline` or `extern` in the header file.
Is there any other way I can achieve this?

**Comment by ChuanqiXu9** [comment]
I think `export` is fine here. 

I'll close the issue since the behavior looks not bad.
