### ISSUE TITLE
[DirectX] DXIL scalarization

### ISSUE THREAD

**Issue by python3kgae** [llvm/llvm-project#92422]
DXIL requires [Vectors](https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#vectors), and maybe some other things, to be scalarized - otherwise it isn't valid DXIL.  We need to come up with an overall design for this.

Notes:

Note that group-shared vectors need to be lowered to arrays to maintain layout consistency and avoid affecting access coalescing - see llvm/llvm-project#92153.

AC:

- [x] Design that enumerates all the things that require scalarization
    - [x] [Vector Ops and Call Instruction Proposal](https://github.com/llvm/wg-hlsl/pull/62/files?short_path=ac6e592#diff-ac6e59276afe8016e307eedc5c835f534c0cb353707760b44df0fa9d905a5cf8)
    - [x] Data layout transformations for scalarization proposal
- [x] [Add the scalarizer pass](https://github.com/llvm/llvm-project/pull/107427) https://github.com/llvm/llvm-project/issues/105178
- [x] #107433
- [x] #107920
- [x] #89646

**Comment by farzonl** [comment]
With the merging of https://github.com/llvm/llvm-project/pull/114332 This looks to be completed.
