### ISSUE TITLE
[lldb] Puzzling interaction between type summary and synthetic children provider

### ISSUE THREAD

**Issue by wolfpld** [llvm/llvm-project#92450]
I'm trying to add pretty printing to some types in my code. Let's say I have the following program:

```c++
struct A { int a; };

int main()
{
    A a = { 2 };
    int b = 0;
}
```

I also have the following python script:

```python
import lldb

def Summary(value, dict):
    return f"Value: {value.GetChildMemberWithName('a').GetValueAsUnsigned()}"

class Printer:
    def __init__(self, val, dict):
        self.val = val

    def update(self):
        self.a = self.val.GetChildMemberWithName('a').GetValueAsUnsigned()

    def num_children(self):
        return 1

    def get_child_index(self, name):
        return int(name.lstrip('[').rstrip(']'))

    def get_child_at_index(self, index):
        return self.val.CreateValueFromExpression(f'child', f'int v={self.a}; v')

def __lldb_init_module(debugger, dict):
    debugger.HandleCommand('type summary add -F pp.Summary -x A')
    debugger.HandleCommand('type synthetic add -l pp.Printer -x A')
```

If *only* the type summary is enabled, I get the following result, as expected:

```gdb
(lldb) command script import pp.py
(lldb) b a.cpp:6
Breakpoint 1: where = a.out`main + 11 at a.cpp:6:9, address = 0x0000000000001124
(lldb) r
Process 496203 launched: '/home/wolf/test/a.out' (x86_64)
Process 496203 stopped
* thread #1, name = 'a.out', stop reason = breakpoint 1.1
    frame #0: 0x0000555555555124 a.out`main at a.cpp:6:9
   3    int main()
   4    {
   5        A a = { 2 };
-> 6        int b = 0;
   7    }
(lldb) p a
(A) Value: 2
(lldb)
```

If *only* the synthetic provider is enabled, I get the following result, as expected:

```gdb
(lldb) p a
(A)  (child = 2)
```

But if *both* type handlers are enabled, the value passed to the summary provider is no longer valid:

```gdb
(lldb) p a
(A) Value: 0
```

I don't understand what's happening here. I would expect both summary and synthetic providers to provide valid output even if both are enabled. The summary provider might print out useful data, such as vector's capacity, that's not really related to any of the children that may be synthesized.

The following example suggests that summary and synthetic providers are supposed to get along together:

https://github.com/llvm/llvm-project/blob/f42f57b52dd279e6ae19270d063aeb8d59e3f11c/lldb/examples/synthetic/gnu_libstdcpp.py#L18-L51

The following example shows that a summary provider should be able to use synthetic provider facilities to access the data:

https://github.com/llvm/llvm-project/blob/f42f57b52dd279e6ae19270d063aeb8d59e3f11c/lldb/examples/synthetic/libcxx.py#L156-L158

I have tested this with lldb 17.0.6 and 19.0.0git (https://github.com/llvm/llvm-project.git revision 9a7f54ba4878c4e66c99430b52d8c014ab7b2a03).

**Comment by jimingham** [comment]
This is by design.  When an type has a synthetic child provider, and you ask "GetChildMemberWithName" of a SBValue of that type, it will return the Synthetic Child (or if no Synthetic child of that name exists it will return a "child not found" error.)  That's because we don't want the clients of the API (e.g. Local variables windows in GUI's) to have to make decisions about whether to use synthetic or raw children.  They just set "use_synthetic" and then they can query the SBValue for children, and get the right version automatically.

If you know in some code that you are writing that you are going to be asking for the raw, you can dial them up explicitly using the `SBValue.GetNonSyntheticValue()` and then asking for that SBValue's children.

**Comment by jimingham** [comment]
So you should be able to fix your issue with:

def Summary(value, dict):
    return f"Value: {value.GetNonSyntheticValue().GetChildMemberWithName('a').GetValueAsUnsigned()}"

**Comment by wolfpld** [comment]
Thanks. This does indeed fix the issue.

![obraz](https://github.com/llvm/llvm-project/assets/600573/cd047989-20d3-4abd-b85a-1ccb7023b951)
