### ISSUE TITLE
-Wtype-limits not implemented

### ISSUE THREAD

**Issue by 43113a5a-87dd-4095-9c20-18b5be2ae8c3** [llvm/llvm-project#9251]
|  |  |
| --- | --- |
| Bugzilla Link | [8879](https://llvm.org/bz8879) |
| Version | trunk |
| OS | Linux |
| Attachments | [Incomplete patch implementing -Wtype-limits](https://user-images.githubusercontent.com/92601587/143742467-fbe6af17-2a3c-4c7c-aa97-e66fe7049175.gz) |
| CC | @zygoloid,@rjmccall |

## Extended Description 
No warnings are given when comparing a type against impossible values.

Example:

int main(void) {
	unsigned short a = 0;
	if (a < 0) return 1;
	if (a > 65535) return 1;
	if (a == -1) return 1;
	return 0;
}

gcc warns:

test2.c:3: warning: comparison is always false due to limited range of data type
test2.c:4: warning: comparison is always false due to limited range of data type
test2.c:5: warning: comparison is always false due to limited range of data type

clang doesn't warn anything.

**Comment by AaronBallman** [comment]
-Wtype-limits has been implemented in Clang for quite some time now. Closing this issue as resolved.
