### ISSUE TITLE
InstCombine should fold ldexp(x, zext(i1 y)) to fmul x, (select y, 2.0, 1.0)

### ISSUE THREAD

**Issue by arsenm** [llvm/llvm-project#92538]
```
define float @src(float %x, i1 %bool) {
  %zext = zext i1 %bool to i32
  %ldexp = call float @llvm.ldexp.f32.i32(float %x, i32 %zext)
  ret float %ldexp
}

define float @tgt(float %x, i1 %bool) {
  %select = select i1 %bool, float 2.000000e+00, float 1.000000e+00
  %mul = fmul float %x, %select
  ret float %mul
}
```

I noticed the pattern while looking at builtin math library code

**Comment by dtcxzyw** [comment]
I think `-> select cond, (fadd x, x), x` is better. BTW, a freeze node is need as this fold introduces more uses of X.
Godbolt: https://godbolt.org/z/6hMT6q4Pa.

**Comment by arsenm** [comment]
> https://godbolt.org/z/6hMT6q4Pa

tgt3 should be using -0 as the fadd identical value, not +0

**Comment by arsenm** [comment]
> I think `-> select cond, (fadd x, x), x` is better. BTW, a freeze node is need as this fold introduces more uses of X. Godbolt: https://godbolt.org/z/6hMT6q4Pa.

This seems to require an additional register

**Comment by vfdff** [comment]
what about fscale ? according [PR67552](https://github.com/llvm/llvm-project/pull/67552)

**Comment by aidenfoxivey** [comment]
Would it be alright if I assigned this issue to myself?

**Comment by aidenfoxivey** [comment]
Thanks @arsenm! Looking forward to taking a crack at it. I've never worked with instcombine yet, so this is pretty exciting.

**Comment by aidenfoxivey** [comment]
Just wanted to give you folks an update - I've written a bit of code and have some to push soon, but midterms are coming up so I might not be super responsive. If someone else wants this issue really badly / already has code for it, I'm happy to hand it over.

Not that I don't want to do it myself, just don't want to hog an issue.

**Comment by aidenfoxivey** [comment]
> I would be happy to keep working on it.

Totally happy to pass the issue over to you if you'd like.
