### ISSUE TITLE
Two passes with the same argument (-livevars) attempted to be registered!

### ISSUE THREAD

**Issue by kiranmadhe** [llvm/llvm-project#92546]
Two passes with the same argument (-livevars) attempted to be registered!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: opt -load ./LiveVariableAnalysis.so -livevars -S
#0 0x000071050583fd01 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/lib/x86_64-linux-gnu/libLLVM-14.so.1+0xe3fd01)
#1 0x000071050583da3e llvm::sys::RunSignalHandlers() (/lib/x86_64-linux-gnu/libLLVM-14.so.1+0xe3da3e)
#2 0x0000710505840236 (/lib/x86_64-linux-gnu/libLLVM-14.so.1+0xe40236)
#3 0x0000710504242520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
#4 0x00007105059aca90 (/lib/x86_64-linux-gnu/libLLVM-14.so.1+0xfaca90)
#5 0x000071050b4ad010 _fini (./LiveVariableAnalysis.so+0x4010)
Segmentation fault (core dumped)
![Screenshot from 2024-05-17 19-19-45](https://github.com/llvm/llvm-project/assets/93565507/9c45ee6f-c033-4937-9fbc-2d1eff19e56b)

**Comment by asl** [comment]
So, the error is real, likely your pass has the same name as the standard one.
