### ISSUE TITLE
SIFixSGPRCopies inserts waterfall loop with undefined implicit use of scc

### ISSUE THREAD

**Issue by jayfoad** [llvm/llvm-project#92561]
With this [test case](https://github.com/llvm/llvm-project/files/15351548/reduced.txt) I get:
```
$ ~/llvm-release/bin/llc -mtriple=amdgcn -mcpu=gfx1100 -o /dev/null -verify-machineinstrs reduced.txt
[...]
*** Bad machine code: Using an undefined physical register ***
- function:    main
- basic block: %bb.0 bb (0x895f278)
- instruction: %65:sreg_32 = S_CSELECT_B32 1, 0, implicit $scc
- operand 3:   implicit $scc
LLVM ERROR: Found 1 machine code errors.
[...]
```

**Comment by arsenm** [comment]
This is because we have this arbitrary threshold for checking if SCC is live or not to preserve it: https://github.com/llvm/llvm-project/blob/ad884d97288c752ba9088d01cf7ab80b20e4d2a6/llvm/lib/Target/AMDGPU/SIInstrInfo.cpp#L6440

**Comment by jayfoad** [comment]
> This is because we have this arbitrary threshold for checking if SCC is live or not to preserve it:
> 
> https://github.com/llvm/llvm-project/blob/ad884d97288c752ba9088d01cf7ab80b20e4d2a6/llvm/lib/Target/AMDGPU/SIInstrInfo.cpp#L6440

I don't see how. That code tests `computeRegisterLiveness != LQR_Dead` which should be conservatively correct if `computeRegisterLiveness` returns `LQR_Unknown`.

**Comment by jayfoad** [comment]
> > This is because we have this arbitrary threshold for checking if SCC is live or not to preserve it:
> > https://github.com/llvm/llvm-project/blob/ad884d97288c752ba9088d01cf7ab80b20e4d2a6/llvm/lib/Target/AMDGPU/SIInstrInfo.cpp#L6440
> 
> I don't see how. That code tests `computeRegisterLiveness != LQR_Dead` which should be conservatively correct if `computeRegisterLiveness` returns `LQR_Unknown`.

Oh, I see, it's saving scc when it was not live (not the other way around).
