### ISSUE TITLE
CTAD: crashes on `clang::Expr::EvaluateAsConstantExpr`

### ISSUE THREAD

**Issue by hokein** [llvm/llvm-project#92596]
clang current crashes on the following code.

```
template <typename>
constexpr bool C = true;
template<class T1, typename T2>
struct Foo {
  template<class V> requires C<V> // Index of V in the Foo deduction guide is 2
  Foo(V, T1);
};

template<class T3>
using AFoo = Foo<T3, T3>;
AFoo afoo{0, 1};
```

The `index` of template parameter occurrence `V` in the require-clause of the synthesized `AFoo` deduction guide `auto (T3, V) -> Foo<T3, T3>`is wrong (`2`), it should be `1`.  We miss this case at https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/SemaTemplate.cpp#L2857-L2858.

**Comment by shafik** [comment]
Confirmed: https://godbolt.org/z/KcfEqd69v
