### ISSUE TITLE
Reverted 0ec3b972e and cef6387e5

### ISSUE THREAD

**Issue by vitalybuka** [llvm/llvm-project#92687]
Reverted 0ec3b972e58bcbcdc1bebe1696ea37f2931287c3 and cef6387e5
to fix
https://lab.llvm.org/buildbot/#/builders/5/builds/43403
https://lab.llvm.org/buildbot/#/builders/236/builds/11283
https://lab.llvm.org/buildbot/#/builders/168/builds/20392

**Comment by delcypher** [comment]
@vitalybuka Thanks for reverting #90786. I think I know the problem and I'll put up a new PR once I've tested it more.

**Comment by delcypher** [comment]
Looks like this was already done:

```
commit c587483da0b50efa04146fde205da1d16731e12e
Author: Vitaly Buka <vitalybuka@google.com>
Date:   Sun May 19 06:21:40 2024 -0700

    Revert "[Bounds-Safety] Fix `pragma-attribute-supported-attributes-list.test`"
    
    Issue #92687
    
    This reverts commit 112eadd55f06bee15caadff688ea0b45acbfa804.
```
