### ISSUE TITLE
[clang-format] A space is missing after a word token

### ISSUE THREAD

**Issue by heiher** [llvm/llvm-project#92688]
A space is missing after `xor` in the following case with the PR https://github.com/llvm/llvm-project/pull/90161.

Expected formatting:

```c
void test(void) {
  static void (*xor)(uint8_t *, size_t, uint8_t);
  xor = resolve_xor_x86();
}
```

Actual formatting:

```c
 void test(void) {
  static void (*xor)(uint8_t *, size_t, uint8_t);
  xor= resolve_xor_x86();
}
```

**Comment by robincaloudis** [comment]
As `xor` is a keyword, it cannot be used as a name. Must the correct formatting of the code in Clang be guaranteed, even if the code is not valid? If the function name gets changed from `xor` to `valid_func_name`, Clang formats the code correctly.

Actual and expected formatting:
```c++
void test(void) {
  static void (*valid_func_name)(uint8_t *, size_t, uint8_t);
  valid_func_name = resolve_xor_x86();
}
```

**Comment by robincaloudis** [comment]
> As `xor` is a keyword, it cannot be used as a name. Must the correct formatting of the code in Clang be guaranteed, even if the code is not valid? If the function name gets changed from `xor` to `valid_func_name`, Clang formats the code correctly.
> 
> Actual and expected formatting:
> 
> ```c++
> void test(void) {
>   static void (*valid_func_name)(uint8_t *, size_t, uint8_t);
>   valid_func_name = resolve_xor_x86();
> }
> ```

I forgot that there is also the pure C world, where `xor` can be used as a valid function name.

**Comment by robincaloudis** [comment]
Hi @owenca, stumbled across the problem myself and opened a PR as a starting point. I'm not sure how far you've gotten. I left some questions in the PR as some things are still not clear to me.

**Comment by owenca** [comment]
@robincaloudis see https://github.com/llvm/llvm-project/pull/92741#issuecomment-2121935049.
