### ISSUE TITLE
[RISCV][Vector] Generating `vsetvl` LMUL=1/8 for zve32* extension might be illegal

### ISSUE THREAD

**Issue by SharzyL** [llvm/llvm-project#92772]
## `vill` might be set when LMUL=1/8 with zve32*

RISCV Vector extension includes a series of zve32* extension for embedded processors that supports a maximum EEW of 32 (instead of 64 for standard Vector extension).

For zve32* architectures, `vsetvl` instruction that sets LMUL=1/8 might be illegal, as described in riscv-v-spec 1.0 document (Section 3.4.2):

> When LMUL < SEW_MIN/ELEN, there is no guarantee an implementation would have enough bits in the fractional vector register to store at least one element, as VLEN=ELEN is a valid implementation choice. For example, with VLEN=ELEN=32, and SEW_MIN=8, an LMUL of 1/8 would only provide four bits of storage in a vector register.

> The use of vtype encodings with LMUL < SEW_MIN/ELEN is reserved, but implementations can set vill if they do not support these congurations.

Also we can find in the implementation of Spike, `vill` is set when seeing `vsew > vflmul * ELEN`.

https://github.com/riscv-software-src/riscv-isa-sim/blob/c81d8e73daf1875d79a54f28f67df150fba0e44c/riscv/vector_unit.cc#L42

```cpp
    vill = !(vflmul >= 0.125 && vflmul <= 8)
           || vsew > std::min(vflmul, 1.0f) * ELEN
           || (newType >> 8) != 0;
```

In conclusion, setting LMUL=1/8 might cause `vill` being set in some zve32* implementations, crashing all subsequent vector instructions.

## Miscompilation with LLVM/clang

LLVM/clang is not aware of this problem currently. It will generate vsetvl instruction with LMUL=1/8 with `-march=rv32gcv_zve32x`. The following is a minimum example:

```c
void foo(unsigned char *restrict d, unsigned char const *restrict s) {
    *d++ = *s++;
    *d++ = *s++;
}
```

When compiling with `-march=rv32gcv_zve32x -O3`, it generates
```asm
foo:                                    # @foo
        vsetivli        zero, 2, e8, mf8, ta, ma   # <- setting mf8 might cause problems!
        vle8.v  v8, (a1)
        vse8.v  v8, (a0)
        ret
```

https://godbolt.org/z/j85n9Pchv is an interactive playground for above code. It could be noticed that gcc generated the same code.

**Comment by SharzyL** [comment]
Oh that's true. When compiled with `rv32gc_zve32x` we have `mf2`. It seems not an issue now. But just curious why `mf2` instead of `mf4` is generated now, since `mf4` would be also legal.

**Comment by sequencer** [comment]
tried with: `-march=rv32imac_zve32f -O3`
look fine now...
```
foo:
        vsetivli        zero,2,e8,mf2,ta,ma
        vle8.v  v1,0(a1)
        vse8.v  v1,0(a0)
        ret
```

**Comment by SharzyL** [comment]
Got it. Thanks for your nice explanation!
