### ISSUE TITLE
Clang accepts declaration in a statement other than a compound statement

### ISSUE THREAD

**Issue by AaronBallman** [llvm/llvm-project#92775]
The following code is grammatically incorrect:
```
void func() {
  if (1)
    int x;
}
```
because an iteratation statement must be followed by a secondary-block, which is a kind of statement, which does not accept declarations accept as allowed by compound-statement. GCC properly rejects this code as did Clang 17, so this is a recent regression: https://godbolt.org/z/sj3de1T74

**Comment by jrtc27** [comment]
Bisected to 8bd06d5b65845e5e01dd899a2deb773580460b89, which seems plausible
