### ISSUE TITLE
lld sometimes does not generate PHDRs for orphaned input sections

### ISSUE THREAD

**Issue by mintsuki** [llvm/llvm-project#92864]
Hello,

The following was tested with LLVM/Clang version 17.0.6.

lld and ld.bfd differ in behaviour if there are orphaned input sections, and if there aren't other non-orphaned input sections triggering the output of an appropriate PHDR, even if said PHDR is explicitly defined in the linker script.

Reproducer: https://github.com/limine-bootloader/limine-c-template/archive/cd873447da8d405905285d325c13e43e0b473670.tar.gz

Usage (in extracted directory):
```sh
make -C kernel clean all KCC=clang KLD=ld.lld # To build with clang/ld.lld
make -C kernel clean all KCC=gcc KLD=ld.bfd # To build with gcc/ld.bfd
```
Then, running `llvm-readelf -l` on `kernel/bin/kernel`, we get the following 2 outputs:

With clang/ld.lld:
```
Elf file type is DYN (Shared object file)
Entry point 0xffffffff80001270
There are 4 program headers, starting at offset 64

Program Headers:
  Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
  LOAD           0x001000 0xffffffff80000000 0xffffffff80000000 0x000080 0x000080 RW  0x1000
  LOAD           0x002000 0xffffffff80001000 0xffffffff80001000 0x00036d 0x00036d R E 0x1000
  LOAD           0x003000 0xffffffff80002000 0xffffffff80002000 0x000090 0x000090 RW  0x1000
  DYNAMIC        0x003000 0xffffffff80002000 0xffffffff80002000 0x000090 0x000090 RW  0x8

 Section to Segment mapping:
  Segment Sections...
   00     .requests 
   01     .text .dynsym .gnu.hash .hash .dynstr 
   02     .dynamic 
   03     .dynamic 
   None   .debug_loclists .debug_abbrev .debug_info .debug_rnglists .debug_str_offsets .debug_str .debug_addr .comment .debug_frame .debug_line .debug_line_str .symtab .shstrtab .strtab
```
With gcc/ld.bfd:
```
Elf file type is EXEC (Executable file)
Entry point 0xffffffff80001110
There are 5 program headers, starting at offset 64

Program Headers:
  Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
  LOAD           0x001000 0xffffffff80000000 0xffffffff80000000 0x000080 0x000080 RW  0x1000
  LOAD           0x002000 0xffffffff80001000 0xffffffff80001000 0x00018b 0x00018b R E 0x1000
  LOAD           0x003000 0xffffffff80002000 0xffffffff80002000 0x00004c 0x00004c R   0x1000
  LOAD           0x004000 0xffffffff80003000 0xffffffff80003000 0x0000e0 0x0000e0 RW  0x1000
  DYNAMIC        0x004000 0xffffffff80003000 0xffffffff80003000 0x0000e0 0x0000e0 RW  0x8

 Section to Segment mapping:
  Segment Sections...
   00     .requests 
   01     .text 
   02     .dynsym .dynstr .hash .gnu.hash 
   03     .dynamic 
   04     .dynamic 
   None   .debug_info .debug_abbrev .debug_loclists .debug_aranges .debug_rnglists .debug_line .debug_str .debug_line_str .comment .symtab .strtab .shstrtab
```

As one can see, the lld version of the created file lacks an appropriate read-only PHDR, despite one being defined in the linker script (`kernel/linker.ld`), because there are no input sections for the compiled template kernel matching the names `.rodata/.rodata.*`, thus not triggering the creation of the `rodata` PHDR as described in the linker script.

This causes the orphaned input sections `.dynsym .gnu.hash .hash .dynstr` to be assigned to the `text` PHDR instead, giving them unintended executable permissions, thus also being a potential security issue.

It also does not align with what ld.bfd does.

Is there something I am missing in the reproducer, like a flag or linker script directive, that would ensure consistent behaviour here? (Preferably BFD's) Or if this is an LLD bug, it would be nice if it was fixed in coming versions.

Thanks!

**Comment by EugeneZelenko** [comment]
Could you please try 18 or `main` branch?

**Comment by mintsuki** [comment]
> Could you please try 18 or `main` branch?

Same thing.

**Comment by mintsuki** [comment]
CC @MaskRay

**Comment by MaskRay** [comment]
I think lld's orphan placement is reasonable. The GNU ld behavior is due to `.rodata` being special.

No `.rodata` input section means there is no `.rodata` output section.
We don't know the sort rank of `.rodata` and it cannot be used as an anchor to place orphan sections.
Note: placing `.rodata` into the `rodata` PHDR does not infer any section flag for `.rodata`.
The best place for the orphans .dynsym/.dynstr/.hash/.gnu.hash is after `.text`.

```
  [Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            0000000000000000 000000 000000 00      0   0  0
  [ 1] .requests         PROGBITS        ffffffff80000000 001000 000080 00  WA  0   0 16
  [ 2] .text             PROGBITS        ffffffff80001000 002000 000323 00  AX  0   0 16
## .dynsym if after .text, which is before `. = ALIGN(CONSTANT(MAXPAGESIZE));`
  [ 3] .dynsym           DYNSYM          ffffffff80001328 002328 000018 18   A  6   1  8
  [ 4] .gnu.hash         GNU_HASH        ffffffff80001340 002340 00001c 00   A  3   0  8
  [ 5] .hash             HASH            ffffffff8000135c 00235c 000010 04   A  3   0  4
  [ 6] .dynstr           STRTAB          ffffffff8000136c 00236c 000001 00   A  0   0  1
  [ 7] .dynamic          DYNAMIC         ffffffff80002000 003000 000090 10  WA  6   0  8
  [ 8] .debug_loclists   PROGBITS        0000000000000000 003090 00037e 00      0   0  1
```

In GNU ld, the `.rodata` output section is a special section that automatically gets the `SHF_ALLOC` flag.
Its orphan placement rule places .dynsym/.dynstr/.hash/.gnu.hash after the empty .rodata

```
  [Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            0000000000000000 000000 000000 00      0   0  0
  [ 1] .requests         PROGBITS        ffffffff80000000 001000 000080 00  WA  0   0 16
  [ 2] .text             PROGBITS        ffffffff80001000 002000 000323 00  AX  0   0 16
## .dynsym if after .rodata, which is after `. = ALIGN(CONSTANT(MAXPAGESIZE));`
  [ 3] .dynsym           DYNSYM          ffffffff80002000 003000 000018 18   A  4   1  8
  [ 4] .dynstr           STRTAB          ffffffff80002018 003018 000001 00   A  0   0  1
  [ 5] .hash             HASH            ffffffff80002020 003020 000010 04   A  3   0  8
  [ 6] .gnu.hash         GNU_HASH        ffffffff80002030 003030 00001c 00   A  3   0  8
  [ 7] .dynamic          DYNAMIC         ffffffff80003000 004000 0000e0 10  WA  4   0  8
  [ 8] .debug_loclists   PROGBITS        0000000000000000 0040e0 00037e 00      0   0  1
```

However, if you edit linker.ld to use a different output section name. GNU ld's behavior will
match lld.

```
    .myrodata : {
        *(.rodata .rodata.*)
    } :rodata
```

We try to keep our linker script rule simple and avoid magic behaviors.
We should not give `.rodata` special semantics.

**Comment by MaskRay** [comment]
As my previous comment says,

> However, if you edit linker.ld to use a different output section name. GNU ld's behavior will
match lld.

GNU ld's behavior change when you rename these special output sections is surprising.
We intentionally do not follow it.

You can add `.dynsym : { *(.dynsym) } :rodata` after `.rodata`, which will cause lld's orphan placement rule to place .dynsym/.dynstr/.gnu.hash after the empty .rodata.

The lld implemention can be improved. For example, I noticed that there is a `hasInputSections` condition, which is not necessary. I created #93761 to remove it.
We want reasonable rules that can be explained and close to GNU ld, but we don't want to blindly copy surprising/complex behaviors.

**Comment by mintsuki** [comment]
Alright, after re-reading this issue multiple times, and doing further research, I think I now understand how this works better. Please bear with me.

What you're basically saying is that we need to forget about PHDRs entirely, as they aren't relevant here, and what matters is output sections and output section flags, the latter being determined by the first input section placed in the output section(?). Because otherwise I see no other way to specify output section flags.

Since there is no `.rodata/.rodata.*` input section, there is no `.rodata` output section, and thus LLD cannot rank other output sections by flags around it.

Instead, with ld.bfd, a `.rodata` output section is always implicitly created, with `SHF_ALLOC` flag (at least? what about the other flags?), assuming it is specified in the linker script (even if empty).

This should be the case for `.text`, and `.data` as well, I presume.

> You can add `.dynsym : { *(.dynsym) } :rodata` after `.rodata`, which will cause lld's orphan placement rule to place .dynsym/.dynstr/.gnu.hash after the empty .rodata.

Yeah, this would make sense, though it seems rather fragile to me (what guarantees `.dynsym` specifically to be the first ranked output section, of read-only rank, after the empty .rodata?), and fragility aside, I feel like it would make a linker script harder to grasp without knowing the ins and outs.

Please correct me if any of my understanding here is wrong; also feel free to close the issue after this, assuming this is something that is not going to be changed. For what I am concerned, I will keep the template reproducer above as-is, because, in due time, any serious program will end up generating `.rodata` and `.data` output sections, and when that happens, the issue sorts itself out.

**Comment by mintsuki** [comment]
Actually, it seems that the `.dynsym : { *(.dynsym) } :rodata` hack may be less fragile than I had originally assumed, as it seems that `.dynsym` always has flags `A`, the same as `.rodata` should, which means it can be used as an anchor to place any subsequent `A` type section.

I guess with an exhaustive comment explaining why this is done, it may not be *too* confusing.

**Comment by MaskRay** [comment]
> Alright, after re-reading this issue multiple times, and doing further research, I think I now understand how this works better. Please bear with me.
> 
> What you're basically saying is that we need to forget about PHDRs entirely, as they aren't relevant here, and what matters is output sections and output section flags, the latter being determined by the first input section placed in the output section(?). Because otherwise I see no other way to specify output section flags.
> 
> Since there is no `.rodata/.rodata.*` input section, there is no `.rodata` output section, and thus LLD cannot rank other output sections by flags around it.

Right.

> Instead, with ld.bfd, a `.rodata` output section is always implicitly created, with `SHF_ALLOC` flag (at least? what about the other flags?), assuming it is specified in the linker script (even if empty).
>
> This should be the case for `.text`, and `.data` as well, I presume.

Yes. I believe `bfd/elf.c:special_sections_r` sets the flag for `.rodata`.

> > You can add `.dynsym : { *(.dynsym) } :rodata` after `.rodata`, which will cause lld's orphan placement rule to place .dynsym/.dynstr/.gnu.hash after the empty .rodata.
> 
> Yeah, this would make sense, though it seems rather fragile to me (what guarantees `.dynsym` specifically to be the first ranked output section, of read-only rank, after the empty .rodata?), and fragility aside, I feel like it would make a linker script harder to grasp without knowing the ins and outs.
> Please correct me if any of my understanding here is wrong; also feel free to close the issue after this, assuming this is something that is not going to be changed. For what I am concerned, I will keep the template reproducer above as-is, because, in due time, any serious program will end up generating `.rodata` and `.data` output sections, and when that happens, the issue sorts itself out.



Let's say the expected linker output contains a few PT_LOAD segments.
For best portability, you need to define the first output section for each PT_LOAD segment.
There may be an `. = ...` assignment before the first output section.

In lld and (I believe) in ld (except special sections like `.rodata`/`.text`/`.data`), orphan sections can be placed after output section A if A contains at least one input section.
In your `linker.ld`, the read-only PT_LOAD region does not have such an anchor.

```

    /* Move to the next memory page for .rodata */
    . = ALIGN(CONSTANT(MAXPAGESIZE));

    .rodata : {   /// empty
        *(.rodata .rodata.*)
    } :rodata

    /* Move to the next memory page for .data */
    . = ALIGN(CONSTANT(MAXPAGESIZE));
```

I think this `hasInputSections` rule isn't needed, so I have proposed https://github.com/llvm/llvm-project/pull/93761#discussion_r1621270430 .
That patch will not create a R PT_LOAD for this case, though.

**Comment by mintsuki** [comment]
That's cool. But why wouldn't this be something you want to apply? Furthermore, I assume this patch isn't perfect as it wouldn't work if there are 2 or more subsequent output sections with no input sections (like e.g. `.rodata` and `.data`) right?

So that's another way in which GNU ld's approach, if a bit ugly, works, at least imho.

**Comment by mintsuki** [comment]
@MaskRay so, what is the state wrt this issue? Asking because I see that it's been left open...

**Comment by MaskRay** [comment]
I think some improvements have been made to lld and there are some behaviors lld will stay different from GNU ld to avoid certain special rules.
