### ISSUE TITLE
Clang outputs incorrect IR for aligning inner structures when using 'packed' and 'aligned' attributes in the outer struct

### ISSUE THREAD

**Issue by pav-code** [llvm/llvm-project#92886]
I am using the following code: https://godbolt.org/z/K4ffnE6jv
The generated `%struct.outerStruct = type <{ i8, i8, %struct.innerStruct, i8, [13 x i8] }>` will not allow the innerStruct's 'intArray' to be aligned to 16 bytes.

If the code is changed to the following: https://godbolt.org/z/zY7PWejMK (**_Alignas(16)**` struct innerStruct tt;`)
The generated IR will be correctly aligned:
`%struct.outerStruct = type { i8, i8, [14 x i8], %struct.innerStruct, i8, [15 x i8] }`

I am trying to understand if this is a bug, undefined interaction between the `packed` and `aligned` attributes or perhaps invalid/undefined code.

**Comment by jyknight** [comment]
Answering question on [discourse thread](https://discourse.llvm.org/t/clang-ir-clang-seems-to-output-incorrect-ir-for-alignment-of-inner-structures-when-using-packed-and-aligned-attributes-in-outer-struct/79118) instead.

**Comment by pav-code** [comment]
I will leave the question on Discourse instead. Closing issue
