### ISSUE TITLE
bfloat typed return values assert on X86

### ISSUE THREAD

**Issue by arsenm** [llvm/llvm-project#92899]
```
; RUN: llc -mtriple=i386-linux-generic -mattr=sse < %s

define bfloat @load_bfloat(ptr %fptr) {
  %v = load bfloat, ptr %fptr, align 2
  ret bfloat %v
}

```
```
Assertion failed: (DAG.getTargetLoweringInfo().isTypeLegal(PartVT) && "Copying to an illegal type!"), function getCopyToParts, file SelectionDAGBuilder.cpp, line 524.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /Users/matt/src/llvm-project/build_rel_with_debinfo/bin/llc -mtriple=i386-linux-generic -mattr=sse
1.	Running pass 'Function Pass Manager' on module '<stdin>'.
2.	Running pass 'X86 DAG->DAG Instruction Selection' on function '@load_bfloat'
 #0 0x00000001023d1380 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/Users/matt/src/llvm-project/build_rel_with_debinfo/bin/llc+0x102371380)
 #1 0x00000001023cf87c llvm::sys::RunSignalHandlers() (/Users/matt/src/llvm-project/build_rel_with_debinfo/bin/llc+0x10236f87c)
 #2 0x00000001023d1a08 SignalHandler(int) (/Users/matt/src/llvm-project/build_rel_with_debinfo/bin/llc+0x102371a08)
 #3 0x00000001828ada24 (/usr/lib/system/libsystem_platform.dylib+0x18046da24)
 #4 0x000000018287dcc0 (/usr/lib/system/libsystem_pthread.dylib+0x18043dcc0)
 #5 0x0000000182789a40 (/usr/lib/system/libsystem_c.dylib+0x180349a40)
 #6 0x0000000182788d30 (/usr/lib/system/libsystem_c.dylib+0x180348d30)
 #7 0x00000001037d2330 getCopyToParts(llvm::SelectionDAG&, llvm::SDLoc const&, llvm::SDValue, llvm::SDValue*, unsigned int, llvm::MVT, llvm::Value const*, std::__1::optional<unsigned int>, llvm::ISD::NodeType) (.cold.21) (/Users/matt/src/llvm-project/build_rel_with_debinfo/bin/llc+0x103772330)
 #8 0x0000000102212afc getCopyToParts(llvm::SelectionDAG&, llvm::SDLoc const&, llvm::SDValue, llvm::SDValue*, unsigned int, llvm::MVT, llvm::Value const*, std::__1::optional<unsigned int>, llvm::ISD::NodeType) (/Users/matt/src/llvm-project/build_rel_with_debinfo/bin/llc+0x1021b2afc)
 #9 0x0000000102217328 llvm::SelectionDAGBuilder::visitRet(llvm::ReturnInst const&) (/Users/matt/src/llvm-project/build_rel_with_debinfo/bin/llc+0x1021b7328)
```

**Comment by phoebewang** [comment]
We don't allow `bfloat` pass/return without SSE2, see https://godbolt.org/z/qooGGdTEh

Besides, the `i386-linux-generic` doesn't see a valid triple?

**Comment by arsenm** [comment]
> We don't allow `bfloat` pass/return without SSE2, see https://godbolt.org/z/qooGGdTEh

Doesn't matter, the IR is the IR and should work 

> 
> Besides, the `i386-linux-generic` doesn't see a valid triple?

Doesn't matter, it asserts

**Comment by phoebewang** [comment]
The point is the IR is not valid. The `half`/`bfloat` type support requires SSE2 instructions, so we limit it to SSE2 in FE. IR has more flexibility and can represent more invalid combination to the backend. I don't think we need to handle the exhaustless invalid cases.

**Comment by arsenm** [comment]
> The point is the IR is not valid. The `half`/`bfloat` type support requires SSE2 instructions, so we limit it to SSE2 in FE. 
The IR is valid. What clang bothers to support has no bearing on the validity of the IR. You can always handle this in some way, by bitcasting to i16 or whatever you want. You can invent whatever ABI you want for the IR. 

> IR has more flexibility and can represent more invalid combination to the backend. I don't think we need to handle the exhaustless invalid cases.

This is an extremely poor QoI, and restricts the ability to share tests. I ran into this trying to add tests that had 32-bit run lines, and now I have to work around backend bugs.
