### ISSUE TITLE
quick_exit is not _Exit / _exit

### ISSUE THREAD

**Issue by frobtech** [llvm/llvm-project#92977]
Currently llvm-libc's actual OS-specific exit code is implemented as `quick_exit`, and `_Exit` and `_exit` call that.  This is backwards.  `_Exit` (C11 name) and `_exit` (POSIX name) are the underlying OS-specific thing (in Unix, the system call).  `quick_exit` is the new C11 function that runs `at_quick_exit` hooks and then calls `_Exit`.

llvm-libc is missing `at_quick_exit` entirely.

**Comment by michaelrj-google** [comment]
It seems like someone got confused about the names while implementing these functions. Here's the TODOs from what I can tell:

- [ ] rename the existing `quick_exit` (defined in [/__support/OSUtils/quick_exit.h](https://github.com/llvm/llvm-project/blob/465bfd41fa27383d93521a31458e6496ebfc590d/libc/src/__support/OSUtil/quick_exit.h#L14)) to something else, and put it in the `internal` namespace.
  - [ ] The function `__llvm_libc_quick_exit` is forward declared in [/__support/OSUtil/baremetal/quick_exit.cpp](https://github.com/llvm/llvm-project/blob/main/libc/src/__support/OSUtil/baremetal/quick_exit.cpp) and intended to be provided by vendors. We should check with them before we rename the symbol (cc @petrhosek)
- [ ] add new entrypoints for `quick_exit` and `at_quick_exit`
  - [ ] See if the code for `atexit` can be shared with `at_quick_exit`

I'm assigning this bug to myself for the moment, but I will probably end up splitting this up into multiple smaller bugs.

**Comment by michaelrj-google** [comment]
The internal `quick_exit` function was renamed in patch #93620 and `__llvm_libc_quick_exit` is now `__llvm_libc_exit`, found in  [OSUtil/baremetal/exit.cpp](https://github.com/llvm/llvm-project/blob/main/libc/src/__support/OSUtil/baremetal/exit.cpp)

`at_quick_exit` will be added next, tracked by #94060

**Comment by michaelrj-google** [comment]
the internal `exit` function has been renamed, and both `quick_exit` and `at_quick_exit` have been added. Closing this as fixed.

Patches:
https://github.com/llvm/llvm-project/pull/93620
https://github.com/llvm/llvm-project/pull/94317
