### ISSUE TITLE
clang emits C++ guarded initialization for Objective-C static variables in functions

### ISSUE THREAD

**Issue by hyp** [llvm/llvm-project#93]
After commit 2b4fa5348ee157b6b1a1af44d0137ca8c7a71573, clang has started emitting unexpected `__cxa_guard_acquire` and `__cxa_guard_release` checks for static variables in functions in Objective-C code. This breaks a lot of downstream Objective-C code that doesn't have any C++ and doesn't link with libc++/libc++abi. 

Patch to partially revert 2b4fa5348ee157b6b1a1af44d0137ca8c7a71573:
https://reviews.llvm.org/D72411
Test case:
```
// RUN: %clang_cc1 -triple x86_64-apple-macos10.15 -emit-llvm -fobjc-arc -o - %s | FileCheck %s

@interface I
@end

I *i() {
  static I *i = ((void *)0);
  return i;
}
```

**Comment by rjmccall** [comment]
Resolved in https://github.com/llvm/llvm-project/commit/7a38468e34eeeb59e80b176b97213d205d8d9b41
