### ISSUE TITLE
TestImportStdModule.py fails on Linux AArch64

### ISSUE THREAD

**Issue by dzhidzhoev** [llvm/llvm-project#93049]
The `lldb/test/API/commands/expression/import-std-module/basic/TestImportStdModule.py` test seems to fail on Linux AArch64 (Ubuntu).

The problem can be reproduced this way using the sample program from the test:
```
#include <iostream>

int main(int argc, char **argv) {
  std::cout << "Test" << std::endl;
  return 0; // Set break point at this line.
}
```
If we compile it, run lldb, and evaluate this expression, it fails after jumping to an illegal instruction:
```
(lldb) file a.out
Current executable set to 'a.out' (aarch64).
(lldb) settings set target.import-std-module true
(lldb) b main.cpp:6
Breakpoint 1: where = a.out`main + 68 at main.cpp:6:3, address = 0x0000000000000f58
(lldb) r
Process 274596 launched: 'a.out' (aarch64)
Process 274596 stopped
* thread #1, name = 'a.out', stop reason = breakpoint 1.1
    frame #0: 0x0000aaaaaaaa0f58 a.out`main(argc=1, argv=0x0000ffffffffeed8) at main.cpp:6:3
   3   	
   4   	int main(int argc, char **argv) {
   5   	  std::cout << "Test" << std::endl;
-> 6   	  return 0; // Set break point at this line.
   7   	}
(lldb) expr --unwind-on-error 0 -- std::minmax<int>(1, 2).first
error: Execution was interrupted, reason: signal SIGILL: illegal opcode.
The process has been left at the point where it was interrupted, use "thread return -x" to return to the state before expression evaluation.
Process 274596 stopped
* thread #1, name = 'a.out', stop reason = signal SIGILL: illegal opcode
    frame #0: 0x0000fffff7fef124
->  0xfffff7fef120: udf    #0x0
    0xfffff7fef124: udf    #0x0
    0xfffff7fef128: udf    #0x0
    0xfffff7fef12c: udf    #0x0
(lldb) 
```

It seems to be a problem with relocations of jitted code. When LLDB jit-compiles an expression, it chooses to split jitted code into a separate section for each function from LLVM IR.
In the provided example, the buggy jump is a call from `_Z12$__lldb_exprPv` (entry function for expressions) to `_ZNSt3__16minmaxB8sn190000IiEENS_4pairIRKT_S4_EES4_S4_`.
The relocation for this call is resolved correctly for code in lldb process address space, and it is represented as `_Z12$__lldb_exprPv function address + value`, where value is `call pc + "std::minmax<>" addr -_Z12$__lldb_exprPv addr`. "std::minmax<>" is located in a different section from _Z12$__lldb_exprPv, since all function are located in separate sections.
After jitted code sections are copied into the target's memory, the offset between "std::minmax<>" text section and `_Z12$__lldb_exprPv` changes, but the "value" of relocation isn't recalculated, which causes a jump to the address 16 bytes less than the actual function address in my environment.

**Comment by Michael137** [comment]
CC @al45tair who was looking at exactly this last week (but in a different context)

**Comment by dzhidzhoev** [comment]
> CC @al45tair who was looking at exactly this last week (but in a different context)

Thanks! That fixes the problem.

**Comment by Michael137** [comment]
Now that https://github.com/llvm/llvm-project/pull/92245 is merged, we can close this
