### ISSUE TITLE
[clang][ARCH64] sparse dot product optimization

### ISSUE THREAD

**Issue by JulianMarcusSchroeder** [llvm/llvm-project#93060]
I'm looking into a sparse dot product function. When compiled with `-march=armv8.4a+sve` it runs twice as fast as with `-mcpu=neoverse-v1` or `-mcpu=native`. When adding `-mllvm -opt-bisect-limit=40` I see the performance with neoverse/native on par with armv8.4a+sve. When plotting the range of `-opt-bisect-limit` I see the optimization results making very large swings.
I've tried this wing clang-15, clang-18 and clang top-of-tree. 
Is this is a bug?
If so, how should I proceed debugging this?

Code:
```
float v_sparse_dot(uint32_t *lhs_idx, uint32_t *rhs_idx, float *lhs_val,
                   float *rhs_val, size_t lhs_len, size_t rhs_len) {
  size_t lhs_pos = 0, rhs_pos = 0;
  float xy = 0;

  while (lhs_pos < lhs_len && rhs_pos < rhs_len) {
    if (lhs_idx[lhs_pos] == rhs_idx[rhs_pos]) {
      xy += lhs_val[lhs_pos] * rhs_val[rhs_pos];
      lhs_pos++;
      rhs_pos++;
    } else if (lhs_idx[lhs_pos] < rhs_idx[rhs_pos]) {
      lhs_pos++;
    } else {
      rhs_pos++;
    }
  }
  return xy;
}
```

**Comment by JulianMarcusSchroeder** [comment]
I just tried compiling the code on a Xeon 8375C and have a similar outcome where the code, after the final optimization, runs roughly twice as slow as the best intermediate optimization result.

**Comment by davemgreen** [comment]
Hi - here is a repo:
https://godbolt.org/z/f8o4r3rYG

My guess would be that this differences in scheduling info is making the backend pick ifcvt differently. You might find that it is is dependant on the predictability of the data and in different cases one would be better than the other.

Considering that we enable FeaturePredictableSelectIsExpensive for that core there might be an argument to make for turning off the ifcvt, but that would require some careful benchmarking to make sure it performs well on average. You can use the option `-mllvm -aarch64-enable-early-ifcvt=false` to disable the ifcvt pass. https://godbolt.org/z/9zh8hrcfE

**Comment by JulianMarcusSchroeder** [comment]
Updated results with appropriate input test data:
```
clang-18 -Wall -O3 -mcpu=neoverse-v1 neo-test.c neo-lib.c
./a.out 
changing matrix data for all iterations
1662ns runtime
./a.out 1
keeping matrix data for all iterations
1581ns runtime
```
versus
```
clang-18 -Wall -O3 -march=armv8.4-a+sve neo-test.c neo-lib.c
./a.out 1
keeping matrix data for all iterations
897ns runtime
./a.out 
changing matrix data for all iterations
2550ns runtime
```
Conclusion: The observed behavior is due to branch prediction. In a real use case the clang compiler produces better code with `-mcpu=neoverse-v1` than with `-march=armv8.4-a+sve`, as one would expect.
