### ISSUE TITLE
-ast-print of an extern-C declaration skips closing semi-colon

### ISSUE THREAD

**Issue by erichkeane** [llvm/llvm-project#93085]
https://godbolt.org/z/c1K3nMj6f

Given:
```
extern "C" int printf(const char *, ...);

template<typename T> void foo(T val) {
  printf("%d\n", val);
}

int main() {
  foo(10);
}
```

`-Xclang -ast-print` results in:

```
extern "C" int printf(const char *, ...)
template <typename T> void foo(T val) {
    printf("%d\n", val);
}
template<> void foo<int>(int val) {
    printf("%d\n", val);
}
int main() {
    foo(10);
}
```

Notice the missing semi-colon after the 'printf' declaration.  This comes back if `extern "C"` is not there.

**Comment by MitalAshok** [comment]
Also happens with `extern "C++"` and it only prints the first declaration if there are multiple https://godbolt.org/z/PvxPGr6Y4

```c++
extern "C++" int f(const char*...), g(const char*...);

using printf_t = int(const char*...);
extern "C" printf_t printf, printf2;

template<typename T> void foo(T val) {
  printf("%d\n", val);
  g("%d\n", val);
}

int main() {
  foo(10);
}
```

```c++
extern "C++" int f(const char *, ...)
using printf_t = int (const char *, ...);
extern "C" int printf(const char *, ...)
template <typename T> void foo(T val) {
    printf("%d\n", val);
    g("%d\n", val);
}
template<> void foo<int>(int val) {
    printf("%d\n", val);
    g("%d\n", val);
}
int main() {
    foo(10);
}
```

**Comment by erichkeane** [comment]
> Also happens with `extern "C++"` and it only prints the first declaration if there are multiple https://godbolt.org/z/PvxPGr6Y4
> 
> ```c++
> extern "C++" int f(const char*...), g(const char*...);
> 
> using printf_t = int(const char*...);
> extern "C" printf_t printf, printf2;
> 
> template<typename T> void foo(T val) {
>   printf("%d\n", val);
>   g("%d\n", val);
> }
> 
> int main() {
>   foo(10);
> }
> ```
> 
> ```c++
> extern "C++" int f(const char *, ...)
> using printf_t = int (const char *, ...);
> extern "C" int printf(const char *, ...)
> template <typename T> void foo(T val) {
>     printf("%d\n", val);
>     g("%d\n", val);
> }
> template<> void foo<int>(int val) {
>     printf("%d\n", val);
>     g("%d\n", val);
> }
> int main() {
>     foo(10);
> }
> ```

Yikes!  Good catch, yeah, something odd is happening with the `LinkageSpec` printing in general.  Bracketed works fine, so I wonder if it is just doing a 'print first child'.

**Comment by erichkeane** [comment]
Just saw the quoted text, line 1154 looks like the issue :D

**Comment by temyurchenko** [comment]
I'd like to work on this issue.

**Comment by temyurchenko** [comment]
> Also happens with `extern "C++"` and it only prints the first declaration if there are multiple https://godbolt.org/z/zWf589vEd

According to [cppreference](https://en.cppreference.com/w/cpp/language/language_linkage) and the standard draft, the `extern <language>` declaration without braces can only have _one_ declaration. That was probably the reason for the original implementation.

However, both clang and LLVM have historically supported several declaration with the (apparently) same semantics as a declaration-seq within the braces. Thus, it seems like it would make sense to treat «un-braced» declarations the same as if they had braces.

Does that seem reasonable?

**Comment by erichkeane** [comment]
> I'd like to work on this issue.

Assigned, have at it!  Feel free to ask for advice, and add me to the code review.

**Comment by temyurchenko** [comment]
> > I'd like to work on this issue.
> 
> Assigned, have at it! Feel free to ask for advice, and add me to the code review.

Thanks! Unfortunately, I can't add you to the reviewers list myself, as I don't have the access rights. Could you please add yourself to the PR linked above?
