### ISSUE TITLE
[clang] Bug with constraints when using nested classes and sizeof causing compilation failure of GNU ranges library

### ISSUE THREAD

**Issue by elizabethandrews** [llvm/llvm-project#93099]
Newer versions of the library compile due to a workaround in the library for clang. I think the issue described below is still a bug though.

Short reproducer - https://godbolt.org/z/1qzac3vEj

```
template<typename T=int>
class bg {
public:
  template <int... h>
      requires (sizeof...(h) > 0) friend class l;
};
template <int... h>
    requires (sizeof...(h) > 0) class l;
void m() { bg v; } 
```

You need the nested class in a template (https://godbolt.org/z/1qzac3vEj) and sizeof (https://godbolt.org/z/3exhT3ahh) to reproduce this. 

It might be related to https://github.com/llvm/llvm-project/issues/61763

**Comment by shafik** [comment]
CC @erichkeane

**Comment by BenBrock** [comment]
This bug appears to prevent Clang trunk from compiling certain parts of ranges (`zip_view` and `zip_transform_view`) with libstdc++ versions earlier than 13.3.0.

13.3.0 [includes a workaround](https://github.com/gcc-mirror/gcc/commit/be34a8b538c0f04b11a428bd1a9340eb19dec13f) that allows Clang to compile.  (Some Linux repo's distributions of GCC, e.g. Ubuntu's 13.2.0-23 and OpenSUSE's 13.2.1 include the workaround as well.)

**Comment by zyn0217** [comment]
@sdkrystian Is this something your patch would fix?

**Comment by sdkrystian** [comment]
@zyn0217 I think this is an issue with `sizeof...` itself

**Comment by zyn0217** [comment]
@BenBrock The issue raised in libstdc++ has been fixed in clang trunk: https://godbolt.org/z/MnjYoqq3T

cc @jwakely
