### ISSUE TITLE
Clang doesn't allow casting in constexpr

### ISSUE THREAD

**Issue by LevoDeLellis** [llvm/llvm-project#93127]
Below is a one liner to reproduce the issue. Change clang++ to g++ is it compiles fine. I skimmed the standard and from what I can tell it didn't forbid it

    echo "constexpr void* test(long long v) { return (void*)v; }" | clang++ -std=c++20 -x c++ -

**Comment by tbaederr** [comment]
Pass `-std=c++2b` instead: https://godbolt.org/z/7Ybe3aYqc

**Comment by frederick-vs-ja** [comment]
Such cast effectively performs `reinterpret_cast`, which always results in constant evaluation failure. Before C++23/[P2448R2](https://wg21.link/p2448r2), a `constexpr` function that can never produce a constant subexpression is ill-formed, no diagnostic required. So it's conforming to reject such function definition before C++23.

**Comment by LevoDeLellis** [comment]
I see, I need to use the trunk instead of 17. I was looking at the c++23 standard which explains why I didn't realize it's not valid <23. Closed
