### ISSUE TITLE
[AMDGPU] Use existing TargetTransformInfo instances in AMDGPUSplitModule

### ISSUE THREAD

**Issue by Pierre-vh** [llvm/llvm-project#93166]
As AMDGPUSplitModule sits outside the PassManager, it can't access TTI normally and it has to build a new instance.
It works as a short term hack for the pass MVP, but it really shouldn't do that.

A better solution would be to make AMDGPUSplitModule a proper pass (and likely the original SplitModule too) that runs last, so it can easily access all the analysis it needs. This in turns opens the door to using more powerful analysis in the future if needed.

The pass can take a callback so the driver can allocate new contexts/modules and write them out without the pass having any idea of how that works.

**Comment by EugeneZelenko** [comment]
@Pierre-vh: Could you please elaborate?

**Comment by Pierre-vh** [comment]
Yes, sorry. The fix was landed #95773 - I forgot to close the ticket.
