### ISSUE TITLE
Edge splitting should update LiveIntervals

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#9325]
|  |  |
| --- | --- |
| Bugzilla Link | [8953](https://llvm.org/bz8953) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @stoklund |

## Extended Description 
Edge splitting should update LiveIntervals so that we can split edges on demand throughout the register allocation pipeline.

**Comment by arsenm** [comment]
MachineBasicBlock::SplitCriticalEdge looks like it tries to preserve LiveIntervals
