### ISSUE TITLE
LLVM 2.8: still crashes on CPUs without CMOV instruction

### ISSUE THREAD

**Issue by edwintorok** [llvm/llvm-project#9336]
|  |  |
| --- | --- |
| Bugzilla Link | [8964](https://llvm.org/bz8964) |
| Version | 2.8 |
| OS | Linux |

## Extended Description 
LLVM 2.8 still crashes on CPUs without CMOV instruction like AMD K6-2, VIA C3, etc.

See http://bugs.debian.org/609759

Here's an output of the JIT with --debug, appears to contain all instruction selection stuff:
http://bugs.debian.org/cgi-bin/bugreport.cgi?msg=45;filename=2011-01-12_clambc.767944.cbc.log;att=2;bug=609759

The .td files seem to properly guard all CMOV* instructions with HasCMOV, so I don't see where its coming from.
Are there some machine-instr level optimizers that introduce it?

**Comment by gwelymernans** [comment]
It's possible that the CMOVs could be added by the target passes. Is this still an issue?

**Comment by RKSimon** [comment]
Closing old bug - debian upgraded from 2.8 a long time ago and this issue hasn't been seen since
