### ISSUE TITLE
Dependant function lookup into a superclass via CRTP fails

### ISSUE THREAD

**Issue by apache-hb** [llvm/llvm-project#93425]
```cpp
#include <cstdio>

template<typename T>
struct BaseClass {
    void doThing() {
        this->thing();
    }
};

struct ChildClass : public BaseClass<ChildClass> {
    void thing() {
        std::printf("a\n");
    }
};
```
Clang issues: `no member named 'thing' in 'BaseClass<T>'`.
`doThing()` should not be instantiated until `ChildClass::doThing` is invoked, this appears to be a regression.

https://godbolt.org/z/TfG8oq9eP

**Comment by dtcxzyw** [comment]
`static_cast<T*>(this)->thing();` works. You can use it as a workaround :)

https://godbolt.org/z/v64a9qa71

**Comment by cor3ntin** [comment]
@sdkrystian Didn't you do something in this area recently?

**Comment by sdkrystian** [comment]
> ```c++
> #include <cstdio>
> 
> template<typename T>
> struct BaseClass {
>     void doThing() {
>         this->thing();
>     }
> };
> 
> struct ChildClass : public BaseClass<ChildClass> {
>     void thing() {
>         std::printf("a\n");
>     }
> };
> ```
> 
> Clang issues: `no member named 'thing' in 'BaseClass<T>'`. `doThing()` should not be instantiated until `ChildClass::doThing` is invoked, this appears to be a regression.
> 
> https://godbolt.org/z/TfG8oq9eP

Clang is right here. `BaseClass<T>` _doesn't_ have a member named `thing` (nor does `BaseClass<ChildClass>` -- only `ChildClass` does). The only difference is that clang will now diagnose this before `doThing` is instantiated, e.g. in the following example ([godbolt](https://godbolt.org/z/GchGTfG4n)):
```cpp
template<typename T>
struct A 
{
    void f() 
    {
        this->g(); // clang trunk: diagnoses at point of definition 
    }
};

struct B : public A<B> 
{
    void g();
};

template struct A<B>; // clang 18.1: diagnoses at point of instantiation
```
cc @cor3ntin
