### ISSUE TITLE
[flang] Undefined reference for iso_fortran_env xxx_kinds

### ISSUE THREAD

**Issue by MarDiehl** [llvm/llvm-project#93440]
When trying to build HDF5 with Clang/Flang-new, I got the following error

```
/usr/bin/ld: /tmp/aclocal_fc-eba825.o: in function `_QQmain':
FIRModule:(.text+0xbe): undefined reference to `_QMiso_fortran_envECinteger_kinds'
/usr/bin/ld: FIRModule:(.text+0x359): undefined reference to `_QMiso_fortran_envECreal_kinds'
/usr/bin/ld: FIRModule:(.text+0x5ef): undefined reference to `_QMiso_fortran_envEClogical_kinds'
```
It can be circumvented by defining a temp variable.

Note that this happened with flang-new version **17.0.6** from https://aur.archlinux.org/packages/flang, so it might be that the bug is fixed already or that it is related to a non-standard installation.

The code for reproducing is attached, originally it had the *.f90 extension.

[aclocal_fc.txt](https://github.com/llvm/llvm-project/files/15451097/aclocal_fc.txt)
[aclocal_fc_fixed.txt](https://github.com/llvm/llvm-project/files/15451098/aclocal_fc_fixed.txt)

**Comment by MarDiehl** [comment]
I can't add labels, this should have at least `flang`

**Comment by k-arrows** [comment]
This looks like a duplicate of https://github.com/llvm/llvm-project/issues/77282 or https://github.com/llvm/llvm-project/issues/89403.

**Comment by MarDiehl** [comment]
my bad, sorry for overlooking the other issues.
