### ISSUE TITLE
[Clang] Unexpected Overloading of Static and Non-Static Member Functions

### ISSUE THREAD

**Issue by 16bit-ykiko** [llvm/llvm-project#93456]
According to the C++ Standard, static and non-static member functions with the same parameter types cannot be overloaded. The following code should fail to compile.

```cpp
struct X {
    void f() const;
    static void f();
};
```

It fails in clang 17, but succeeds in clang 18. And I find it is related to the declaration order. If swap the declaration order of the two functions

```cpp
struct X {
    static void f();
    void f() const;
};
```

It fails as expected, please see [Compiler Explorer](https://godbolt.org/z/h11vhjTGb).

**Comment by zyn0217** [comment]
@cor3ntin https://github.com/llvm/llvm-project/blob/7a28a5b3fee6c78ad59af79a3d03c00db153c49f/clang/lib/Sema/SemaOverload.cpp#L1483-L1486
I suppose this should be `!OldMethod->isStatic() && !NewMethod->isStatic()`? Otherwise, we would consider the non-static and static as overload functions.

**Comment by cor3ntin** [comment]
@zyn0217 Probably, yes. Do you plan to make a PR?

**Comment by zyn0217** [comment]
Not yet; if you're going to have one, please feel free. :)
