### ISSUE TITLE
`#pragma GCC diagnostic warning "-Wimplicit-function-declaration"` fails at turning -Werror=implicit-function-declaration into to just a warning

### ISSUE THREAD

**Issue by pskocik** [llvm/llvm-project#93474]
`#pragma GCC diagnostic warning "-Wimplicit-function-declaration"` fails at turning -Werror=implicit-function-declaration into to just a warning.
It does make it warn as expected if `-Wimplicit-function-declaration` was previously `ignored`, but it won't make it go from error to warning.

Gcc works as expected. Clang not, since clang 15:

https://godbolt.org/z/qc7MKc75b

**Comment by shafik** [comment]
CC @AaronBallman

**Comment by AaronBallman** [comment]
This relates to #92630 in that `-w` also does not disable warnings that default to being an error.
