### ISSUE TITLE
Invalid size request in SelectionDAGBuilder::EmitFuncArgumentDbgValue

### ISSUE THREAD

**Issue by sdesmalen-arm** [llvm/llvm-project#93537]
Reproducer:

```
#include <arm_sve.h>

void bar(svint32x4_t, svint32x4_t, svint32x2_t);
void foo(svint32x4_t a, svint32x4_t b, svint32x2_t c) {
    bar(a, b, c);
}
```

Build with `clang -march=armv9-a -O1 -g2`.

[Godbolt link](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:2,endLineNumber:6,positionColumn:2,positionLineNumber:6,selectionStartColumn:2,selectionStartLineNumber:6,startColumn:2,startLineNumber:6),source:'%23include+%3Carm_sve.h%3E%0A%0Avoid+bar(svint32x4_t,+svint32x4_t,+svint32x2_t)%3B%0Avoid+foo(svint32x4_t+a,+svint32x4_t+b,+svint32x2_t+c)+%7B%0A++++bar(a,+b,+c)%3B%0A%7D'),l:'5',n:'1',o:'C%2B%2B+source+%231',t:'0')),k:33.333341711984495,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:armv8-clang-trunk,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'1',libraryCode:'0',trim:'0',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:2,lang:c%2B%2B,libs:!(),options:'-march%3Darmv9-a+-O1+-g2',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+armv8-a+clang+(trunk)+(Editor+%231)',t:'0')),header:(),k:33.33332495468219,l:'4',m:100,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'armv8-a+clang+(trunk)',editorid:1,fontScale:14,fontUsePx:'0',j:2,wrap:'1'),l:'5',n:'0',o:'Output+of+armv8-a+clang+(trunk)+(Compiler+%232)',t:'0')),k:33.33333333333333,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

**Comment by paulwalker-arm** [comment]
Fixed by https://github.com/llvm/llvm-project/pull/108008
