### ISSUE TITLE
[gsoc2024][libc][math][c23] Implement _Float16 basic operations

### ISSUE THREAD

**Issue by overmighty** [llvm/llvm-project#93566]
This issue is part of the following Google Summer of Code 2024 project: https://summerofcode.withgoogle.com/programs/2024/projects/1vPVUj93.

- [x] `ceilf16`: #94001
- [x] `canonicalizef16`: #94341
- [x] `copysignf16`: #94351
- [x] `fabsf16`: #93567
- [x] `fdimf16`: #94354
- [x] `floorf16`: #94001
- [x] `fmaxf16`: #94131
- [x] `fmaximumf16`: #94510
- [x] `fmaximum_magf16`: #94510
- [x] `fmaximum_mag_numf16`: #94510
- [x] `fmaximum_numf16`: #94510
- [x] `fminf16`: #94131
- [x] `fminimumf16`: #94510
- [x] `fminimum_magf16`: #94510
- [x] `fminimum_mag_numf16`: #94510
- [x] `fminimum_numf16`: #94510
- [x] `fmodf16`: #94629
- [x] `frexpf16`: #94758
- [x] `fromfpf16`: #94254
- [x] `fromfpxf16`: #94254
- [x] `ilogbf16`: #94758
- [x] `ldexpf16`: #94797
- [x] `llogbf16`: #94758
- [x] `llrintf16`: #94218
- [x] `llroundf16`: #94218
- [x] `logbf16`: #94758
- [x] `lrintf16`: #94218
- [x] `lroundf16`: #94218
- [x] `modff16`: #94758
- [x] `nanf16`: #94767
- [x] `nearbyintf16`: #94218
- [x] `nextafterf16`: #94535
- [x] `nextdownf16`: #94535
- [x] `nexttowardf16`: #94535
- [x] `nextupf16`: #94535
- [x] `remainderf16`: #94773
- [x] `remquof16`: #94773
- [x] `rintf16`: #94218
- [x] `roundf16`: #94001
- [x] `roundevenf16`: #94001
- [x] `scalbnf16`: #94797
- [x] `scalblnf16`: #94797
- [x] `truncf16`: #94001
- [x] `ufromfpf16`: #94254
- [x] `ufromfpxf16`: #94254
- [x] `totalorderf16`: #95014
- [x] `totalordermagf16`: #95014
- [x] `getpayloadf16`: #95159
- [x] `setpayloadf16`: #95159
- [x] `setpayloadsigf16`: #95159
- [x] `f16add` (extension): #97072
- [x] `f16addf` (extension): #96787
- [x] `f16addl` (extension): #97072
- [x] `f16addf128`: #97072
- [x] `f16sub` (extension): #97072
- [x] `f16subf` (extension): #96787
- [x] `f16subl` (extension): #97072
- [x] `f16subf128`: #97072
- [x] `f16mul` (extension): #98972
- [x] `f16mulf` (extension): #98972
- [x] `f16mull` (extension): #98972
- [x] `f16mulf128`: #98972
- [x] `f16div` (extension): #97054
- [x] `f16divf` (extension): #96131
- [x] `f16divl` (extension): #97054
- [x] `f16divf128`: #97054
- [x] `f16fma` (extension): #96711
- [x] `f16fmaf` (extension): #95483
- [x] `f16fmal` (extension): #96711
- [x] `f16fmaf128`: #96711

**Comment by JonChesterfield** [comment]
I think this broke the aarch64 libc bot, e.g. https://lab.llvm.org/buildbot/#/builders/138

**Comment by overmighty** [comment]
@JonChesterfield See https://github.com/llvm/llvm-project/pull/94569.
