### ISSUE TITLE
[libc] add `quick_exit`

### ISSUE THREAD

**Issue by michaelrj-google** [llvm/llvm-project#93581]
The `quick_exit` function is defined in the C standard on page 382 of this PDF: https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3220.pdf

For this issue we'll skip `at_quick_exit`, it will be handled in a followup patch.

### Build System

In [entrypoints.txt](https://github.com/llvm/llvm-project/blob/main/libc/config/linux/x86_64/entrypoints.txt)
- [ ] Add the new function to the list of entrypoints for stdlib.h (you need to do this before it will build)

In [stdlib/CMakeLists.txt](https://github.com/llvm/llvm-project/blob/main/libc/src/stdlib/CMakeLists.txt)
- [ ] Add new entrypoint objects to the list

In [stdc.td](https://github.com/llvm/llvm-project/blob/main/libc/spec/stdc.td)
- [ ] Add the functions to the list of functions for unistd.h (this can be confusing, ask for help if you're stuck).

### Code

Rename existing `quick_exit`
- [ ] There is currently a function named `quick_exit` defined in [src/__support/OSUtil/quick_exit.h](https://github.com/llvm/llvm-project/blob/main/libc/src/__support/OSUtil/quick_exit.h) which should be put in the `LIBC_NAMESPACE::internal` namespace and renamed to just `exit`.
- [ ] Make sure to rename all of the `quick_exit` files and functions in the subfolders of `OSUtil`

Create `stdlib/quick_exit.h`
- [ ] look at [exit.h](https://github.com/llvm/llvm-project/blob/main/libc/src/stdlib/exit.h) for an example of how this should be laid out (copying the whole file and modifying it is fine).

Create `stdlib/quick_exit.cpp`
- [ ] Again, look at look at [exit.cpp](https://github.com/llvm/llvm-project/blob/main/libc/src/stdlib/exit.cpp) for an example.

### Testing

Create `test/src/stdlib/quick_exit_test.cpp`
- [ ] This should be based on [_Exit_test.cpp](https://github.com/llvm/llvm-project/blob/main/libc/test/src/stdlib/_Exit_test.cpp).
  - [ ] That test should also be split into tests for `_Exit` and `exit` so either add a `TODO` or split it in this patch.

Add your tests to [test/src/stdlib/CMakeLists.txt](https://github.com/llvm/llvm-project/blob/main/libc/test/src/stdlib/CMakeLists.txt)
- [ ] Hopefully self-explanatory

Fixes #92977

**Comment by aaryanshukla** [comment]
Please assign to me, thanks.

**Comment by RoseZhang03** [comment]
Please assign

**Comment by michaelrj-google** [comment]
Completed, thanks!
