### ISSUE TITLE
[Flang] Asynchronous: missing diagnose of undefinable array section actual corresponding to asynchronous dummy

### ISSUE THREAD

**Issue by DanielCChen** [llvm/llvm-project#93600]
Consider the following case:
```
       interface
         subroutine sub(arg)
           integer, asynchronous :: arg(3)
         end subroutine
       end interface
       integer :: i(10)
       call sub(i( (/2, 3, 4/)))
       end
```

The standard says [15.5.2.5]
```
If the procedure is nonelemental, the dummy argument does not have the VALUE attribute, and the actual argument is an array section having a vector subscript, the dummy argument is not definable and shall not have the ASYNCHRONOUS, INTENT (OUT), INTENT (INOUT), or VOLATILE attributes.
```

Flang currently is missing the diagnose.

**Comment by klausler** [comment]
I've considered that requirement (F'2023 15.5.2.5 p21) to be a bug in the standard in the case of `ASYNCHRONOUS` and `VOLATILE` attributes.  These two attributes, like `TARGET`, can be applied to a dummy argument and have their effect last only during the duration of the procedure reference; they can also be scoped with `BLOCK` constructs.

I'll document this better and add a portability warning.

**Comment by klausler** [comment]
And I almost forgot: it is possible for a variable (including a dummy argument) to silently acquire the `ASYNCHRONOUS` attribute in its scope merely from appearing in an I/O data transfer statement with `ASYNCHRONOUS=`YES`` in its control list.  So we really can't know at a call site whether a dummy argument is ASYNCHRONOUS or not, even when an explicit interface is in hand.  (Many compilers don't implement this aspect of Fortran correctly, but I think that f18 does.)

**Comment by DanielCChen** [comment]
I see your point. I will bring it to the standard meeting next Month and see if it will become an interp.

**Comment by klausler** [comment]
I have never yet had a useful interp response from J3 and wouldn't expect one in this case either.

**Comment by klausler** [comment]
https://github.com/llvm/llvm-project/pull/93851

**Comment by DanielCChen** [comment]
> I have never yet had a useful interp response from J3 and wouldn't expect one in this case either.

I will give it a try :).

**Comment by DanielCChen** [comment]
At the same time, if you don't mind, I will keep this one open until I get answer from the standard committee (end of June).

**Comment by klausler** [comment]
> > I have never yet had a useful interp response from J3 and wouldn't expect one in this case either.
> 
> I will give it a try :).

If you really think that you can get useful interp responses, there's about a hundred other discrepancies at https://github.com/klausler/fortran-wringer-tests?tab=readme-ov-file#results that you could submit.  Many cases elicit 6 or more distinct behaviors from the compilers that I've tested.

**Comment by DanielCChen** [comment]
Yeah, I have read some of those cases. I will dig a bit more and see what I can do.
