### ISSUE TITLE
[libc++] _LIBCPP_HAS_NO_UNICODE is missing from __config_site

### ISSUE THREAD

**Issue by BlamKiwi** [llvm/llvm-project#93638]
`_LIBCPP_HAS_NO_UNICODE` is not defined in `__config_site.in` and causes the CMake variable `LIBCXX_ENABLE_UNICODE` to not be honored.

**Comment by ldionne** [comment]
Are you sure that's true? We do seem to define it in https://github.com/llvm/llvm-project/blob/6b21e170497ae69a387ff3eebae025926742bb84/libcxx/CMakeLists.txt#L778.

Please reopen with a reproducer if you're really seeing this. (I am only closing early to keep issues tidy, don't hesitate to reopen)

**Comment by BlamKiwi** [comment]
> Are you sure that's true? We do seem to define it in
> 
> https://github.com/llvm/llvm-project/blob/6b21e170497ae69a387ff3eebae025926742bb84/libcxx/CMakeLists.txt#L778
> .
> 
> Please reopen with a reproducer if you're really seeing this. (I am only closing early to keep issues tidy, don't hesitate to reopen)

Your CMake defines it, but it's never propagated to the `__config_site` header because `__config_site.in` doesn't have `#cmakedefine _LIBCPP_HAS_NO_UNICODE`

**Comment by ldionne** [comment]
You're right, thanks a lot!
