### ISSUE TITLE
[clang-format] Possible regression clang-format-19?

### ISSUE THREAD

**Issue by prj-** [llvm/llvm-project#93678]
Could you please let me know which one is correct?
```cpp
$ clang-format foo.cpp 
struct func_traits_impl<Ret (C::*)(Args...) const> {};
$ clang-format-19 foo.cpp                                                                               
struct func_traits_impl<Ret (C:: *)(Args...) const> {};
$ clang-format-19 --version
Debian clang-format version 19.0.0 (++20240527100630+434ee06d7761-1~exp1~20240527220812.2113)
```

**Comment by owenca** [comment]
Version 19 is correct. See #86253.

**Comment by prj-** [comment]
Thank you!

**Comment by prj-** [comment]
@owenca, this has changed yet again, so which version is correct, 18 and 20, or 19?
```
$ clang-format-20 foo.cpp 
struct func_traits_impl<Ret (C::*)(Args...) const> {};
$ clang-format-20 --version
Debian clang-format version 20.0.0 (++20240825100934+5b41eb3a6dcd-1~exp1~20240825221045.2294)
```

**Comment by owenca** [comment]
See https://github.com/llvm/llvm-project/pull/86253#issuecomment-2298404887 and the followup commit 714033a6bf3a81b1350f969ddd83bcd9fbb703e8, which has been backported to the 19.x Release branch. So the soon-to-be released 19.1.0 and the trunk (20.0.0git) are deemed to be correct right now.

**Comment by owenca** [comment]
Fixed by 714033a6bf3a81b1350f969ddd83bcd9fbb703e8.

**Comment by prj-** [comment]
OK, nice, no change in between 18, 19, and 20 then!

**Comment by owenca** [comment]
Yes, 18 is also correct.
