### ISSUE TITLE
[Flang] Unexpected generic interface symbol reference causes error in mangling

### ISSUE THREAD

**Issue by rofirrim** [llvm/llvm-project#93707]
Consider the following module, simplified from a real module of OpenMPI

```fortran
! mini_mpi.f90
module mini_mpi
  interface
    subroutine mpi_allreduce(sendbuf,recvbuf,count,datatype,op,comm,ierror)
      real(4),intent(in)::sendbuf(10)
      real(4)::recvbuf(10)
      integer(4),intent(in)::count
      integer(4),intent(in)::datatype
      integer(4),intent(in)::op
      integer(4),intent(in)::comm
      integer(4),intent(out)::ierror
    end subroutine mpi_allreduce
  end interface

  ! Generic interface
  interface mpi_allreduce
      procedure :: mpi_allreduce
  end interface
  contains
end module mini_mpi
```

And the following three modules, each one in a different file (stated in the first comment)

```fortran
! comm.f90
module comm
  use mini_mpi

  contains
    subroutine my_sub_in_comm
      real(4)::sendbuf(10)
      real(4)::recvbuf(10)
      integer(4)::count
      integer(4)::datatype
      integer(4)::op
      integer(4)::comm
      integer(4)::ierror

      call mpi_allreduce(sendbuf, recvbuf, count, datatype, op, comm, ierror)
    end subroutine my_sub_in_comm

end module comm
```

```fortran
! math.f90
module math
  use comm

  contains
    subroutine my_sub_in_math
      real(4)::sendbuf(10)
      real(4)::recvbuf(10)
      integer(4)::count
      integer(4)::datatype
      integer(4)::op
      integer(4)::comm
      integer(4)::ierror

      call mpi_allreduce(sendbuf, recvbuf, count, datatype, op, comm, ierror)
    end subroutine my_sub_in_math
end module math
```
```fortran
! mesh.f90
module mesh
  use comm
  use math

  contains
    subroutine my_sub_in_mesh
      real(4)::sendbuf(10)
      real(4)::recvbuf(10)
      integer(4)::count
      integer(4)::datatype
      integer(4)::op
      integer(4)::comm
      integer(4)::ierror

      call mpi_allreduce(sendbuf, recvbuf, count, datatype, op, comm, ierror)
    end subroutine my_sub_in_mesh
end module mesh
```

If we compile them in the proper order

```
flang-new -c mini_mpi.f90
flang-new -c comm.f90
flang-new -c math.f90
flang-new -c mesh.f90
```
`mesh.f90` fails to compile with the following error

```
LLVM ERROR: <path>/llvm-src/flang/lib/Lower/Mangler.cpp:174: not yet implemented: symbol mangling
```

We try to mangle a `GenericDetails`.

It seems the problem stems in the exported symbols my `math` (and `mesh`) in which we see repeated references to `mpi_allreduce` (this suggests we might be exporting both the generic interface name and the external name) from these modules.

```
$ grep -rw mpi_allreduce {mesh,math}.mod
mesh.mod:use comm,only:mpi_allreduce
mesh.mod:use math,only:comm$mini_mpi$mpi_allreduce
math.mod:use comm,only:mpi_allreduce
math.mod:use mini_mpi,only:comm$mini_mpi$mpi_allreduce=>mpi_allreduce
```

but somehow is not a problem for `comm` (which is hopefully exporting only the generic name?)

```
$ grep  mpi_allreduce comm.mod
use mini_mpi,only:mpi_allreduce
```

The problem seems related to the generic interface in `mini_mpi.f90` because commenting it solves the problem. But modifying the OpenMPI module is a bit of an inconvenient workaround.

**Comment by klausler** [comment]
Fortran unfortunately allows one name to refer to multiple symbols in the same scope in a few cases.  One of these cases is the use of a single name to refer to both a generic interface as well as one of its specific procedures.  When this happens, it is not possible for a module to contain one and not the other.

f18's module files are just Fortran, so you can `cat` them and see this in action.

I suspect that the name mangling code isn't checking for this case.  In the symbol table built by semantics, it is represented as a GenericDetails symbol in the scope's name map, and the GenericDetails has a `specific()` member function that points to the SubprogramDetails symbol of the same name that is not in the scope's name map.

**Comment by rofirrim** [comment]
Looking at the backtrace leading to the problem I see a symbol from a `ProcedureDesignator` that looks like this (I understand this one is the specific)

```
(gdb) p symbol->dump()
comm$mini_mpi$mpi_allreduce, PUBLIC (Subroutine): Use from comm$mini_mpi$mpi_allreduce in math
```
but its ultimate is

```
(gdb) p symbol->GetUltimate().dump() 
mpi_allreduce, PUBLIC (Subroutine): Generic Name (specific) procs: mpi_allreduce
```

I'd expect that the ultimate symbol (which I understand is the leading symbol after navigating the "use chain") of a specific procedure also be a specific symbol. Not sure if this makes sense. Thanks!

**Comment by klausler** [comment]
The ultimate symbol is not a host or use association, but it can still be a generic that's shadowing a specific procedure or a derived type of the same name.

**Comment by hakostra** [comment]
Hi. I just encountered this same error in a Fortran file I'm trying to compile with flang-new (most recent flang-new from Git). It's a fairly big file, and I have no clue to where the error comes from (i.e. which line or symbol). Is there any easy way for me to figure out this? The only thing I know is which file it is, but that does not help that much as the file is big. If I know what symbol it is, maybe I can workaround the limitation...
