### ISSUE TITLE
Assert valid target data string in LLVMCreateTargetData

### ISSUE THREAD

**Issue by c1f2da5c-3510-4ef9-b7bb-24e698b33024** [llvm/llvm-project#9370]
|  |  |
| --- | --- |
| Bugzilla Link | [8998](https://llvm.org/bz8998) |
| Version | 2.8 |
| OS | All |
| CC | @thielema |

## Extended Description 
Please add an assert to LLVMCreateTargetData (i.e. the C++ function that it calls), that checks whether the input string is correct. It seems that there is no way to find out, if an input string is actually valid. If I pass "nonsense" I get a non-NULL pointer as result (that is, the TargetDataRef does not show me, that the input was wrong), and if I pass that to LLVMAddTargetData then things go silently wrong in a very awful way.
See ticket #&#8203;6394 for an example.
http://llvm.org/bugs/show_bug.cgi?id=6394

**Comment by JOE1994** [comment]
(checked with `llvmorg-17.0.6`)

Function `LLVMTargetDataRef LLVMCreateTargetData (const char *StringRep)` feeds its input string to the following constructor of `llvm::DataLayout`:

```cpp
explicit DataLayout(StringRef LayoutDescription) {
  reset(LayoutDescription);
}
```

`DataLayout::reset` performs validation checks on input parameter `StringRef LayoutDescription`, via function `DataLayout::parseSpecifier`.

https://github.com/llvm/llvm-project/blob/6009708b4367171ccdbf4b5905cb6a803753fe18/llvm/lib/IR/DataLayout.cpp#L195-L221

As there are validation checks in place as requested, I think this ticket can be closed.
