### ISSUE TITLE
[libc] Implement `fdopen`

### ISSUE THREAD

**Issue by alanzhao1** [llvm/llvm-project#93711]
See https://pubs.opengroup.org/onlinepubs/009696899/functions/fdopen.html

**Comment by michaelrj-google** [comment]
Hi, thanks for picking this up! Feel free to comment on this issue or reach out over discord if you get stuck

**Comment by simonzgx** [comment]
Some progress up to now:

* I found a memory leak bug in the implementation of GLIBC's ``fdopen`` function and have submitted a [bug report](https://sourceware.org/bugzilla/show_bug.cgi?id=31838).
* I found that the ``fcntl`` function of ``llvmlibc`` could not always set the ``errno`` correctly, which I hava give it a fix in the PR(#93711). However, it may still take a day or two before the PR is ready for review.
