### ISSUE TITLE
how to enable clang with c++23 import std; or import std.compat on windows?

### ISSUE THREAD

**Issue by lengye7** [llvm/llvm-project#93722]
import std; and import std.compat; is a good feature to speed up C++ compile. 

Is there any way to enable clang with this feature on windows?

msvc19.40(vs2022) can use this feature. documentation:https://learn.microsoft.com/en-us/cpp/cpp/tutorial-import-stl-named-module?view=msvc-170

Can clang use msvc std module?

**Comment by ChuanqiXu9** [comment]
I think this is not a clang issue. The std module is a library feature. So I expect you can import std from libc++ on windows too. I guess what you expect is to use clang to import std module from MSSTL. In this case you need to report an issue to MSSTL and they should work to adopt it. If there are problems (compiler bugs or they use some extensions), they should communicate the concrete problems with us again in different issue thread.

So I'll close this as invalid.
