### ISSUE TITLE
[llvm-cov] Use-after-move of CoverageData

### ISSUE THREAD

**Issue by nikic** [llvm/llvm-project#93798]
There are two places that move CoverageData inside a loop:
https://github.com/llvm/llvm-project/blob/43100766f287185642a3ccbf1a629915f85575e2/llvm/tools/llvm-cov/CodeCoverage.cpp#L351-L353
https://github.com/llvm/llvm-project/blob/43100766f287185642a3ccbf1a629915f85575e2/llvm/tools/llvm-cov/CodeCoverage.cpp#L377-L379

This looks incorrect to me, but I'm also unsure on what the right fix for this would be, as `SourceCoverageView::create()` accepts `CoverageData` by rvalue reference.

cc @evodius96 @MaskRay

**Comment by evodius96** [comment]
Ah, good catch.  Should this created as a shared_ptr and then copied?
