### ISSUE TITLE
[Flang] Incorrect diagnose on NULL(mold) being actual arg to `same_type_as` and `extends_type_of`

### ISSUE THREAD

**Issue by DanielCChen** [llvm/llvm-project#93845]
Consider the following code
```
type dt
  real :: r1
end type
logical :: res
type(dt), pointer :: a, b
res = same_type_as(null(a), b)
res = extends_type_of(null(a), b)
end
```

Flang currently issues errors as:
```
./tt.f:6:20: error: A NULL() pointer is not allowed for 'a=' intrinsic argument
  res = same_type_as(null(a), b)
                     ^^^^^^^
./tt.f:7:23: error: A NULL() pointer is not allowed for 'a=' intrinsic argument
  res = extends_type_of(null(a), b)
                        ^^^^^^^
```

The code seems standard conforming to me. 
`null(a)` returns a disassociated pointer that has the characteristics as `a`. The argument of `same_type_as` and `extends_type_of` requires it does not have an `undefined` association status. `Disassociated` is not `undefined`.

**Comment by klausler** [comment]
https://github.com/llvm/llvm-project/pull/93866
