### ISSUE TITLE
Compile time evaluation does not match runtime evaluation with -ffp-contract=on

### ISSUE THREAD

**Issue by bfraboni** [llvm/llvm-project#93870]
Hello LLVM team,

I am not entirely sure this is an actual bug, but the following code does not enforce the multiplication order compiled with clang and optimization level 1 to 3. I feel this is simple enough that is should return the right result.
````c++
#include <iostream>

struct Vec2 {
    float x, y;
};

// wrong result for SA(a,a,b)
float signedAreaBroken(const Vec2& a, const Vec2& b, const Vec2& c) {
    return (((a.x - c.x) * (b.y - c.y)) - ((b.x - c.x) * (a.y - c.y)));
}

// correct result for SA(a,a,b)
float signedAreaRobust(const Vec2& a, const Vec2& b, const Vec2& c) {   
    const float u = (a.x - c.x) * (b.y - c.y);
    const float v = (b.x - c.x) * (a.y - c.y);
    return u - v;
}

int main() {
    const Vec2 b = {0.5f, 0.5f}, a = {1.4f, 0.7f};

    printf("robust(a,a,b)=%.12f\nbroken(a,a,b)=%.12f\nrobust(a,b,a)=%.12f\nbroken(a,b,a)=%.12f\n", 
        signedAreaRobust(a,a,b), // 0
        signedAreaBroken(a,a,b), // not 0
        signedAreaRobust(a,b,a), // 0 
        signedAreaBroken(a,b,a)); // 0
    
    return 0;
}
````

The scalar version in godbolt does not explain at all why the result between the two functions would be different, the generated instructions are identical: https://godbolt.org/z/5d7P6sxhE

However, using the flag -mavx2 gives more info on registers: https://godbolt.org/z/z61zj9d5d
And it seems that the second multiplication (instruction l.13) is done in reversed order for `signedAreaBroken`, in comparison to the one for `signedAreaRobust` (instruction l.28).
I can't explain why breaking down the same equation in two separate variables would enforce the order of operations.

Is that an expected behavior ? If yes, is there any good resources on how to enforce multiplication order with clang and optimization ON ?

Thank you 🙏

**Comment by topperc** [comment]
Try -ffp-contract=off

**Comment by bfraboni** [comment]
Hey @topperc ,
Thanks for the fast answer, ok I see that indeed gives the right result with ` -ffp-contract=off`.
What if I want to keep ` -ffp-contract=on` as optimization default but still enforce operations order in one function , isn't there a function flag for that ?

**Comment by bfraboni** [comment]
Ok I've played a little more and there is an inconsistency :
- `-ffp-contract=off` gives the right result;
- `-ffp-contract=on` gives the wrong result;
- `-ffp-contract=fast` gives the right result.

Is that behavior expected ? Could that be a bug with `-ffp-contract=on` ?

There is no fma instruction generated at all so I don't get why the expression gets less precise by flipping one operation, and not consistently across different modes. The doc says that it should do the opposite:
> Specify when the compiler is permitted to form fused floating-point operations, such as fused multiply-add (FMA). Fused operations are permitted to produce more precise results than performing the same operations separately

**Comment by bfraboni** [comment]
Ok I got fooled by this simple example, it turns out to be related to compile time evaluation that does not match the runtime evaluation. Passing the values as arguments and forcing runtime evaluation results in the same answer for all function calls:
https://godbolt.org/z/chroejME1

The problem is then that the preprocessed values are not done with the same expression / precision than the runtime ones; and that only happens with `-fp-contract=on`, the two other modes do not precompute any result.
