### ISSUE TITLE
Create a team for backend:NVPTX label on issues

### ISSUE THREAD

**Issue by justinfargnoli** [llvm/llvm-project#93899]
Requesting the creation of a new GitHub team within the LLVM organization to subscribe to _issues_ with the https://github.com/llvm/llvm-project/labels/backend%3ANVPTX label.

Following up on the steps listed: [[llvm-dev] Subscribing to GitHub issue labels](https://groups.google.com/g/llvm-dev/c/Nmfknpaumos)

**Comment by justinfargnoli** [comment]
See also #93900

**Comment by asl** [comment]
@justinfargnoli You do not need team for this. Just directly subscribe to label.

**Comment by justinfargnoli** [comment]
Closing based on [Label-based notification](https://discourse.llvm.org/t/label-based-notification/60517)
