### ISSUE TITLE
Create a team for backend:NVPTX label on pull requests

### ISSUE THREAD

**Issue by justinfargnoli** [llvm/llvm-project#93900]
Requesting the creation of a new GitHub team within the LLVM organization to subscribe to _pull requests_ with the https://github.com/llvm/llvm-project/labels/backend%3ANVPTX label.

**Comment by justinfargnoli** [comment]
See also #93899

**Comment by joker-eph** [comment]
You don't need an issue: the way it works is that you send a pull-request to setup the subscription mechanism, add tstellar as reviewers so that they can create the team at this moment.

**Comment by tstellar** [comment]
Team Created: @llvm/pr-subscribers-backend-nvptx

You will need to create a PR to modify: https://github.com/llvm/llvm-project/blob/main/.github/new-prs-labeler.yml in order to actually get the notifications.

**Comment by justinfargnoli** [comment]
Thanks @tstellar!
