### ISSUE TITLE
How to set call attributes via C binding?

### ISSUE THREAD

**Issue by c1f2da5c-3510-4ef9-b7bb-24e698b33024** [llvm/llvm-project#9394]
|  |  |
| --- | --- |
| Bugzilla Link | [9022](https://llvm.org/bz9022) |
| Version | 2.8 |
| OS | Linux |
| Attachments | [attempt to set ReadNone attribute at call](https://user-images.githubusercontent.com/92601667/143742579-347566a3-6ecc-46c7-b74b-dcd5dada670a.gz) |
| CC | @asl |

## Extended Description 

I wonder how to set an attribute like readnone to a call.
Attached is a C program where I try to do add the readnone attribute using LLVMAddInstrAttribute, which seems to be wrong, since this adds the attribute to the result of the call. The verifier pass thus complains:

Attribute readnone only applies to the function!
  %2 = call readnone double @&#8203;llvm.exp.f64(double %0)
Attribute readnone only applies to the function!
  %3 = call readnone double @&#8203;llvm.sin.f64(double %1)
Broken module found, compilation aborted!
Stack dump:
0.      Running pass 'Function Pass Manager' on module '_module'.
1.      Running pass 'Module Verifier' on function '@arithmetic'
Aborted

I also tried LLVMAddAttribute (but as far as I understand this is for parameters of the surrounding function) and LLVMAddFunctionAttr (but I want to add to a call, not a function). Both do not work.

How can I add an attribute to a call? Or is this not necessary at all?

**Comment by arsenm** [comment]
I see the C API now has LLVMAddCallSiteAttribute
