### ISSUE TITLE
[libc] add `link.h`/`elf.h` 

### ISSUE THREAD

**Issue by SchrodingerZhu** [llvm/llvm-project#94128]
These definitions are currently missing in libc. They are useful in the `startup` library and the `vdso` parts.

See https://github.com/llvm/llvm-project/pull/91572

**Comment by changkhothuychung** [comment]
I can take this issue if this is available.

**Comment by michaelrj-google** [comment]
assigned

**Comment by changkhothuychung** [comment]
@michaelrj-google thanks for assigning this to me. Can you give me some instructions on what to do with this one? What functions am i going to add to those files, and what directory am I putting it under?

**Comment by michaelrj-google** [comment]
@SchrodingerZhu can hopefully tell you more, I'm not sure what he needs from these headers.

**Comment by changkhothuychung** [comment]
@SchrodingerZhu I have a few questions 

Dont we link linux when building LLVM? So we can just include the elf.h file of linux kernel and use the values right? Why do we need to move it over to llvm? 

what folder under libc should I put these files?

**Comment by nickdesaulniers** [comment]
Take a look at glibc's elf.h: https://sourceware.org/git/?p=glibc.git;a=blob;f=elf/elf.h;h=33aea7f743b885c5d74736276e55ef21756293ee;hb=HEAD

or musl's: https://git.musl-libc.org/cgit/musl/tree/include/elf.h

Some of the definitions there are useful for a libc to provide (and include via our hdr/ proxy pattern).  Specifically, look at what https://github.com/llvm/llvm-project/pull/91572/files is using from elf.h. We should have our own, and include that.

**Comment by SchrodingerZhu** [comment]
> what folder under libc should I put these files?
I think you can following the convention to put definitions inside `libc/include/` with types and macros separated into two sub folders.

**Comment by changkhothuychung** [comment]
@SchrodingerZhu Schoa
I will first create a patch with macors from elf.h file.

**Comment by nickdesaulniers** [comment]
4371c79d45e8fca88957eaac42da1211c830b076 created these. There's probably a lot more that can be added to these two, but closing the issue for now.
