### ISSUE TITLE
Impossible to redirect diagnostic output getStyle function

### ISSUE THREAD

**Issue by pointhex** [llvm/llvm-project#94205]
We in QtCreator use getStyle function while the user typing the code. If the .clang-format file contains some issue then every call generates a stdout. It is clatter up the whole QtC output so to mitigate it would be good to have the possibility to redirect getStyle function diagnostic output. That possibility already exists in parseConfiguration function.

**Comment by mydeveloperday** [comment]
So QtCreator links with libclang-format?
