### ISSUE TITLE
libc++'s std::string::operator== could be more libfuzzer friendly

### ISSUE THREAD

**Issue by zmodem** [llvm/llvm-project#94222]
libfuzzer intercepts `memcmp` (and other functions) to augment the fuzzer's corpus with data likely to hit more code paths.

That means it will very quickly hit the "Found it" branch in this example:

```
extern "C" int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size) {
  std::string the_string(reinterpret_cast<const char*>(data), size);
  if (the_string == "Hello, world!") {
    std::cout << "Found it!\n";
    exit(1);
  }
  return 0;
}
```

However, in this example where it compares two `std::string`'s instead, it does not find it so easily:

```
extern "C" int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size) {
  std::string the_string(reinterpret_cast<const char*>(data), size);
  std::string hello = "Hello, world!";
  if (the_string == hello) {
    std::cout << "Found it!\n";
    exit(1);
  }
  return 0;
}
```

Interestingly, if we make the string too long to fit in the short-string optimization storage, it works again.

The reason seems to be that libc++ uses a hand written loop for "short" strings instead of calling `char_traits<char>::compare` which presumably ends up calling `memcmp`.

I don't know what the fix is here, but maybe libc++ could use memcmp in more cases (or when using fuzzer instrumentation), or libfuzzer could be smarter somehow?

(This was originally reported in https://crbug.com/343801371)

**Comment by ldionne** [comment]
@zmodem Where did you see the hand-written loop for short strings? Looking at the code, what I see is this:

```c++
string::operator==
-> string_view::operator==
-> string_view::compare
-> char_traits::compare and a bit of "setup" code around it
```

**Comment by adetaylor** [comment]
[Here it is!](https://github.com/llvm/llvm-project/blob/main/libcxx/include/string#L3756) - it's specifically in `bool
operator==(const basic_string<char, char_traits<char>, _Allocator>& __lhs, const basic_string<char, char_traits<char>, _Allocator>& __rhs)`.
