### ISSUE TITLE
Trivial requires clause difference makes definition not match declaration

### ISSUE THREAD

**Issue by pkasting** [llvm/llvm-project#94238]
The following code compiles in gcc trunk with -std=c++20, but not in Clang:
```
struct S {
  template <typename T>
    requires((true))
  void f();
};

template <typename T>
  requires(true)
void S::f() {}  // [Clang-only] error: out-of-line definition of 'f' does not match any declaration in 'S'
```
Live repro: https://godbolt.org/z/fnPWb6vY1

I don't know which compiler matches the standard. gcc's behavior seems better in the abstract -- it doesn't feel as if adding or removing parens around a requirement should make it distinct for this purpose. But I don't know how far that stretches; is "true" the same requirement as "true && true"? How deeply should the compiler evaluate these before matching?

**Comment by zyn0217** [comment]
We determine the “identity” by profiling these requires expressions, and what we probably miss here is to call ignoreParens() before profiling.

Similar issue: https://github.com/llvm/llvm-project/issues/76181

**Comment by pkasting** [comment]
Ugh. Not sure I love that this is IFNDR (would be nice if these were equivalent) _or_ that compilers differ in practice as to whether they accept (would be nice if none did), but I don't care enough to chase the other vendors or EWG.
