### ISSUE TITLE
Does libc++'s span have a non-standard converting constructor?

### ISSUE THREAD

**Issue by ldionne** [llvm/llvm-project#94364]
I just came across these constructors which I can't find anywhere in the Standard: https://github.com/llvm/llvm-project/blob/492417278d986ddd8206b2b9bba626ce690ea244/libcxx/include/span#L296-L303

Are they non-standard constructors we provide?

Also, it is possible that the constructor at line 297 is missing a `noexcept` (thanks @mclow for the heads up).

**Comment by mclow** [comment]
This is in the implementation of the fixed-size span.
These constructors two versions of last constructor listed in https://eel.is/c++draft/views#span.cons

**Comment by ldionne** [comment]
@mclow I think you're totally right. PR open.
