### ISSUE TITLE
[Flang] Missing diagnostic on character argument that has length greater than 1 for intrinsic `ICHAR`

### ISSUE THREAD

**Issue by DanielCChen** [llvm/llvm-project#94371]
Consider the following test case:
```
character*5 :: char
integer :: res
char = "ABCDE"
res = ichar(char)
print*, res
end
```

The standard requires the argument of `ICHAR` to have length 1. Flang is silent to the code and print the collation sequence for 'A'
XLF has the same behavior as Flang, but both gfortran and ifort flag an error.

I didn't find it in  `Extensions.md`.

**Comment by klausler** [comment]
```
flang-new -pedantic t.f90
./t.f90:4:7: portability: Character in intrinsic function ichar should have length one
  res = ichar(char)
        ^^^^^^^^^^^
```
