### ISSUE TITLE
Compiling C++ codes with arm-eabi target triple wrongly defines _GNU_SOURCE

### ISSUE THREAD

**Issue by lbmeng** [llvm/llvm-project#94428]
**Version**: LLVM 17.0.6
**Download URL**: https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.6/clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04.tar.xz

Considering the following test code:
```
$ cat test.c
#ifdef _GNU_SOURCE
#warning "_GNU_SOURCE is defined!"
#endif

int main() {return 0;}
$ ln -s test.c test.cpp
```

Compiling the test.c and test.cpp with clang and clang++, with arm-eabi target gives me:
```
$ clang --target=arm-eabi -c test.c -o test
$ clang++ --target=arm-eabi -c test.cpp -o test
test.cpp:2:2: warning: "_GNU_SOURCE is defined!" [-W#warnings]
    2 | #warning "_GNU_SOURCE is defined!"
      |  ^
1 warning generated.
```

Testing arm64, i386, x86_64, riscv32, riscv64 targets does not expose the same behavior:
```
$ clang --target=arm64 -c test.c -o test
$ clang++ --target=arm64 -c test.cpp -o test
$ clang --target=i386 -c test.c -o test
$ clang++ --target=i386 -c test.cpp -o test
$ clang --target=x86_64 -c test.c -o test
$ clang++ --target=x86_64 -c test.cpp -o test
$ clang --target=riscv32 -c test.c -o test
$ clang++ --target=riscv32 -c test.cpp -o test
$ clang --target=riscv64 -c test.c -o test
$ clang++ --target=riscv64 -c test.cpp -o test
```

If I append _-linux_ to the target triple, arm64, i386, x86_64, riscv32, riscv64 targets for C++ will throw out the warning, but C will not, e.g.: riscv64-linux

```
$ clang --target=riscv64-linux -c test.c -o test
$ clang++ --target=riscv64-linux -c test.cpp -o test
test.cpp:2:2: warning: "_GNU_SOURCE is defined!" [-W#warnings]
    2 | #warning "_GNU_SOURCE is defined!"
      |  ^
1 warning generated.
```

Appending _-linux_ to arm-eabi triple does not make any difference:
```
$ clang --target=arm-eabi-linux -c test.c -o test
$ clang++ --target=arm-eabi-linux -c test.cpp -o test
test.cpp:2:2: warning: "_GNU_SOURCE is defined!" [-W#warnings]
    2 | #warning "_GNU_SOURCE is defined!"
      |  ^
1 warning generated.
```

There are two issues:

1. It looks the arm-eabi target wrongly defines _GNU_SOURCE when compiling C++ code
2. Why compiling C code does not get _GNU_SOURCE defined, either with or without the -linux triple, for these targets (arm-eabi/arm64/i386/x86_64/riscv32/riscv64)?

**Comment by efriedma-quic** [comment]
A very long time ago, the developers of g++ decided to define _GNU_SOURCE by default, to expose relevant C library functions for use by libstdc++.  For compatibility, this forced a bunch of other C++ compilers for various targets to also define it.

See https://reviews.llvm.org/D136712 for discussion of ARM baremetal in particular.

**Comment by EugeneZelenko** [comment]
Could you please try 18 or `main` branch?

**Comment by lbmeng** [comment]
> Could you please try 18 or `main` branch?

I just built an LLVM/clang from main branch, the symptom is the same.
