### ISSUE TITLE
[KnownBits] Remove hasConflict() assertions

### ISSUE THREAD

**Issue by nikic** [llvm/llvm-project#94436]
The KnownBits infrastructure currently has pervasive !hasConflict() assertions, which ensure that KnownBits don't claim that a bit is both zero *and* one at the same time. However, these kinds of conflicts can naturally arise whenever the value is known to be poison. At this point, these assertions no longer provide value and just result in a steady stream of compiler crashes.

We should remove these assertions. Once that is done, we may also make use of conflicting KnownBits to fold values to poison.

**Comment by CedricSwa** [comment]
I would like to tackle this issue

**Comment by jayfoad** [comment]
> We should remove these assertions. Once that is done, we may also make use of conflicting KnownBits to fold values to poison.

An obvious next step would be to remove all instances of this from `KnownBits.cpp`:
```
  if (Known.hasConflict())
    Known.setAllZero();
```
That will result in KnownBits returning conflict more often, so callers may need to be fixed to handle it correctly.

**Comment by CedricSwa** [comment]
Ok I'm building it right now with the changes of #94568 and the change to KnownBits.cpp is there something I should check about testing it?
