### ISSUE TITLE
[clang] Ungrammatical "a enum specifier" error message

### ISSUE THREAD

**Issue by Rajveer100** [llvm/llvm-project#94443]
Clang throws ungrammatical error message for alias.

[GodBolt](https://godbolt.org/z/714cPYG3c)

Old:
```C++
error: type alias 'A' cannot be referenced with a enum specifier
```

New:
```C++
error: type alias 'A' cannot be referenced with the 'enum' specifier
```

This can be rephrased for other cases as well, ex:

```C++
template<class T> using A = int;
struct A s;
```

**Comment by akshaykumars614** [comment]
I am new here, but the error message seems to be correct as A is a type alias here. But as I can see, it is being changed to alias. Please correct me if I am wrong. @Rajveer100

**Comment by Rajveer100** [comment]
@akshaykumars614 
Apologies, I have updated the issue description.

**Comment by Rajveer100** [comment]
For the new snippet in the description, it would be applicable:

```C++
template<class T> using A = int;
struct A s;
```

```C++
Old: type alias template 'A' cannot be referenced with a struct specifier
New: alias template 'A' cannot be referenced with the 'struct' specifier
```

**Comment by kper** [comment]
@Rajveer100 is the change from old to new just a grammar change or do I have to change the analysis?

```
Old: type alias template...
New: alias template...
```

**Comment by Rajveer100** [comment]
It's a grammatical change.
