### ISSUE TITLE
[RISCV] Vector Store/Load whole-register for multiple registers only has DWARF CFI for one register

### ISSUE THREAD

**Issue by ilovepi** [llvm/llvm-project#94500]
As seen in our tests (https://github.com/llvm/llvm-project/blob/0295c2ada4d9964a2b6289c905e320bd42461f99/llvm/test/CodeGen/RISCV/rvv-cfi-info.ll#L80C1-L84C8), when spilling vector registers to the stack, we only emit DWARF CFI directives for the register named in the store. Note, that in the code listing in the test, there are other `.cfi_directives`, but those are for other stores earlier in the function.

```asm
 vs4r.v v4, (a0) ;; Unknown-size Folded Spill
;; ...
.cfi_escape 0x10, 0x64, 0x0b, 0x11, 0x60, 0x22, 0x11, 0x78, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 ;; $v4m4 @ cfa - 32 - 8 * vlenb
```

This seems like an oversight in [createDefCFAOffset](https://github.com/llvm/llvm-project/blob/f4681be06b465736cc993b114dd8e2625d37b779/llvm/lib/Target/RISCV/RISCVFrameLowering.cpp#L500), or maybe it's callers.

It may be worth considering extending the DWARF registers with some kind of pseudo register for these groups, to keep the debug info compact.

**Comment by ilovepi** [comment]
cc: @topperc, @hiraditya, @petrhosek. @frobtech

**Comment by topperc** [comment]
CC @kito-cheng @BeMg

**Comment by kito-cheng** [comment]
Checked with ARM32 code gen around neon, they have similar usage like LMUL [1], but for floating point, they also using minimal unit to describe the register, e.g. d0 = s0, s1, so debug info will describe spilling d0 to sp+0 as s0 to sp+0 + s0 to sp+4 (not accurate but the idea is something like that).

I think for short term we should fix that in that way, and honest I am not really family with debug info too much, so I am not sure how to extending DWARF register to cover such register group issue, especially there is some subreg relationship with other DWARF register

[1] https://developer.arm.com/documentation/den0024/a/ARMv8-Registers/NEON-and-floating-point-registers/NEON-in-AArch32-execution-state-
