### ISSUE TITLE
Problems with the output of the -show-branches parameter

### ISSUE THREAD

**Issue by iejzh** [llvm/llvm-project#94567]
As shown, the same condition is displayed twice.
<img width="754" alt="截屏2024-06-06 12 28 44" src="https://github.com/llvm/llvm-project/assets/32932199/cf78c38d-57c5-4cd1-ab86-f738f4cd87e3">

**Comment by asl** [comment]
Please upload minimal reproducible testcase

**Comment by iejzh** [comment]
[llvm_cov_mcdc.zip](https://github.com/user-attachments/files/15604329/llvm_cov_mcdc.zip)
Please run it in the project root directory: `cmake -B build -S . -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -GNinja && ninja -C build ccov-cartesian_to_polar`,then use your browser to open the`build/ccov/cartesian_to_polar/index.html`.

**Comment by EugeneZelenko** [comment]
@iejzh: Could you please elaborate?
