### ISSUE TITLE
AMDGPU lowering of abs is bad for i16 vectors with more than 2 elements

### ISSUE THREAD

**Issue by arsenm** [llvm/llvm-project#94606]
We currently get a simple 2-instruction expansion in the v2i16 case, but larger vectors scalarize and produce bad code instead of vector splitting 

```
; RUN: llc -march=amdgcn -mcpu=gfx900 < %s

; v_pk_sub_i16 v1, 0, v0
; v_pk_max_i16 v0, v0, v1
define <2 x i16> @v_abs_v2i16(<2 x i16> %arg) {
  %res = call <2 x i16> @llvm.abs.v2i16(<2 x i16> %arg, i1 false)
  ret <2 x i16> %res
}

; This should decompose into 2 x v2i16 and 4 instructions, but we get this long sequence

;	v_lshrrev_b32_e32 v2, 16, v1
;	v_sub_u16_e32 v3, 0, v2
;	v_max_i16_e32 v2, v2, v3
;	v_lshrrev_b32_e32 v3, 16, v0
;	v_sub_u16_e32 v4, 0, v3
;	v_max_i16_e32 v3, v3, v4
;	v_sub_u16_e32 v4, 0, v1
;	v_max_i16_e32 v1, v1, v4
;	v_sub_u16_e32 v4, 0, v0
;	v_max_i16_e32 v0, v0, v4
;	s_mov_b32 s4, 0x5040100
;	v_perm_b32 v0, v3, v0, s4
;	v_perm_b32 v1, v2, v1, s4
define <4 x i16> @v_abs_v4i16(<4 x i16> %arg) {
  %res = call <4 x i16> @llvm.abs.v4i16(<4 x i16> %arg, i1 false)
  ret <4 x i16> %res
}
```

**Comment by Rajveer100** [comment]
@arsenm 
I believe in the above `IR`, we are calculating the absolute value for each element in the vector. For the optimisation part, could you provide pointers for the same?

Also, does the vector size affect the sequence size?

**Comment by arsenm** [comment]
> @arsenm I believe in the above `IR`, we are calculating the absolute value for each element in the vector. For the optimisation part, could you provide pointers for the same?

SelectionDAG makes this difficult because of how it assumes vectors work. If the wider vector types were illegal, the vector legalizer would produce the correct code. We usually work around this by custom lowering wider vector operations and then doing the split ourselves.

> 
> Also, does the vector size affect the sequence size?

No, any 16-bit vector should be decomposed into 2-element sequences. 6 x i16 and 8 x i16 should just be decomposed into 2 x i16 pieces. Ideally the 3 x case would be a 2 x i16 plus a scalar
