### ISSUE TITLE
mingw-w64: native threading implementation

### ISSUE THREAD

**Issue by rubenvb** [llvm/llvm-project#9461]
|  |  |
| --- | --- |
| Bugzilla Link | [9089](https://llvm.org/bz9089) |
| Version | unspecified |
| OS | Windows NT |
| Blocks | llvm/llvm-project#9456  |
| CC | @compnerd |

## Extended Description 
libc++ can use pthreads, but that would be inefficient on Windows in the long run.

Since Vista (NT6), Windows has native support for all the POSIX default multi-threading API that pretty much makes up the C++0x threading support.

See for example: http://msdn.microsoft.com/en-us/library/ms682052%28v=vs.85%29.aspx

Alternatively, the mingw-w64 project is working on a new pthreads for windows internal library, because pthreads-win32 is awfully old and stale.

Mailing list discussion: http://lists.cs.uiuc.edu/pipermail/cfe-dev/2011-January/012770.html

**Comment by philnik777** [comment]
ToT libc++ supports the win32 threading API.
