### ISSUE TITLE
alignas not fully implemented

### ISSUE THREAD

**Issue by FraserRoss** [llvm/llvm-project#94747]
This use of alignas is not accepted by Clang 5.0.2.

	template <
		typename T
		>
	struct CreateStatic {
		static T * Create() {
			static char alignas(T) staticMemory_[sizeof(T)];
			return new (&staticMemory_) T;
			}

		static void Destroy(T * const p) {
			p->~T();
			}
		};

**Comment by tbaederr** [comment]
>  Clang 5.0.2.

Please try clang 18 or trunk.

**Comment by FraserRoss** [comment]
I only have access to Clang 15.  It is still a problem with it.

**Comment by EugeneZelenko** [comment]
@FraserRoss: 15 (and even 18) is no longer maintained. You could experiment on https://godbolt.org.

**Comment by FraserRoss** [comment]
I have found the issue has been fixed: https://github.com/llvm/llvm-project/issues/81472
