### ISSUE TITLE
confusing diagnostic for extra qualification on member

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#9487]
|  |  |
| --- | --- |
| Bugzilla Link | [9115](https://llvm.org/bz9115) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 
For this code:
```c++
class MyClass {
public:
MyClass::MyClass();
};
```
g++ gives:
```
test.cpp:3: error: extra qualification ‘MyClass::’ on member ‘MyClass’
```
and comeau gives:
```
"ComeauTest.c", line 3: error: qualified name is not allowed in member declaration
      MyClass::MyClass();
```
but clang++ gives:
```
test.cpp:3:22: error: expected member name or ';' after declaration specifiers
MyClass::MyClass();
~~~~~~~~~~~~~~~~ ^
1 error generated.
```
which is confusing.

**Comment by philnik777** [comment]
Fixed in Clang 3.3: https://godbolt.org/z/Y1oMYdPP5
