### ISSUE TITLE
[libcxx] Trying to use `atomic_ref<const T>` and `atomic_ref<volatile T>` fails with a compilation error

### ISSUE THREAD

**Issue by lewissbaker** [llvm/llvm-project#94879]
The following code fails to compile, complaining that it cannot pass a `const T*` or `volatile T*` to the relevant intrinsic.

```c++
int i = 0;
std::atomic_ref<const int> cref(i);
int val = cref.load(); // error
cref.wait(); // error

volatile int vi =  0;
std::atomic_ref<volatile int> vref(v);
val = vref.load(); // error
vref.exchange(val); // error
vref.compare_exchange_weak(val, 0); // error
vref.compare_exchange_strong(val, 0); // error
vref.wait(0); // error
```

See  https://godbolt.org/z/TbjYdd3Kx

The problem is that the local variable `__ret` used to receive the result of a load has type `_Tp*`, whereas it really needs to have type `remove_cv_t<_Tp>*`.

e.g. you can fix the `atomic_ref::load()` method by applying the following change:
```diff
   _LIBCPP_HIDE_FROM_ABI _Tp load(memory_order __order = memory_order::seq_cst) const noexcept
       _LIBCPP_CHECK_LOAD_MEMORY_ORDER(__order) {
     _LIBCPP_ASSERT_ARGUMENT_WITHIN_DOMAIN(
         __order == memory_order::relaxed || __order == memory_order::consume || __order == memory_order::acquire ||
             __order == memory_order::seq_cst,
         "atomic_ref: memory order argument to atomic load operation is invalid");
     alignas(_Tp) byte __mem[sizeof(_Tp)];
-    auto* __ret = reinterpret_cast<_Tp*>(__mem);
+    auto* __ret = reinterpret_cast<remove_cv_t<_Tp>*>(__mem);
     __atomic_load(__ptr_, __ret, std::__to_gcc_order(__order));
     return *__ret;
   }
```

**Comment by pinskia** [comment]
https://lists.isocpp.org/lib/2024/06/28451.php
https://cplusplus.github.io/LWG/issue3508

**Comment by ldionne** [comment]
Thanks @pinskia.

Since this is handled as a LWG issue, I'll close this and we'll handle it as it comes through LWG (which is what we do for LWG issues). This will avoid stale Github issues.

**Comment by pinskia** [comment]
From the GCC bug report:
https://cplusplus.github.io/LWG/issue4069

```
There is a paper being written to address both those issues, but it hasn't been published yet. It should be P3323 when it's ready.
```

**Comment by pkasting** [comment]
> Since this is handled as a LWG issue, I'll close this and we'll handle it as it comes through LWG (which is what we do for LWG issues). This will avoid stale Github issues.

Does it make sense to at least implement support for what P3323 proposes better-specifying (`atomic_ref<const T>` that provides read-only support, and `atomic_ref<volatile T>` for lock-free cases)? Those cases seem sane, and would allow clients with these use cases to make use of `atomic_ref`.

**Comment by philnik777** [comment]
> > Since this is handled as a LWG issue, I'll close this and we'll handle it as it comes through LWG (which is what we do for LWG issues). This will avoid stale Github issues.
> 
> Does it make sense to at least implement support for what P3323 proposes better-specifying (`atomic_ref<const T>` that provides read-only support, and `atomic_ref<volatile T>` for lock-free cases)? Those cases seem sane, and would allow clients with these use cases to make use of `atomic_ref`.

Since we don't know what the outcome will be in the end we shouldn't implement potentially incompatible extensions that users start to rely on.

**Comment by pkasting** [comment]
It wouldn't be an extension, since the standard today claims those should work. Most of what the paper does is carve those cases out from the other cases the standard _also_ says should work, but which don't make much sense. Just implementing support for the sane cases doesn't risk incompatibility, unless I'm mistaken.

**Comment by ldionne** [comment]
I tend to agree with @philnik777 -- I'd wait the paper to come in before we do anything.

**Comment by frederick-vs-ja** [comment]
Now tracked in #118378.
