### ISSUE TITLE
FLang: Compiler Flags for Lexer Tokens and Lexing/Parsing Phases

### ISSUE THREAD

**Issue by AkhilAkkapelli** [llvm/llvm-project#94870]
1. What is the compiler flag to get lexer tokens in Flang? I am aware that -fdebug-dump-parse-tree dumps the parse tree, but I would like to know the specific flag to obtain tokens after the lexer phase.
2. In Flang, do the lexing and parsing phases of the compiler occur separately, or are they integrated in some manner?

**Comment by banach-space** [comment]
For questions on "how things work", please use Discourse:
* https://discourse.llvm.org/c/subprojects/flang

You can also use Flang's Slack space: https://flang.llvm.org/docs/GettingInvolved.html#id3. As for GitHub Issues, that's predominantly for reporting ... issues/bugs ;-)
