### ISSUE TITLE
FileCheck error: '<stdin>' is empty.

### ISSUE THREAD

**Issue by lyl-seu** [llvm/llvm-project#94888]
ninja check-dynamatic
******************** TEST 'Dynamatic :: Conversion/CfToHandshake/memory.mlir' FAILED ********************

FileCheck error: '<stdin>' is empty.
FileCheck command line:  /home/lyl/dynamatic/polygeist/llvm-project/build/bin/FileCheck /home/lyl/dynamatic/test/Conversion/CfToHandshake/memory.mlir

**Comment by joker-eph** [comment]
> FileCheck error: '<stdin>' is empty. 

This means that the tool providing an input to FileCheck crashed without providing an output. 
The log after what you pasted should provide information about it, but right now you don't provide enough information to point at the problem.

**Comment by joker-eph** [comment]
Closing as it's not actionable as is, but feel free to re-open with more information!

**Comment by Yurii-huang** [comment]
[1/2] Preparing lit tests
[1/2] Running all regression tests
-- Testing: 44875 tests, 16 workers --
Testing:  0.. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 
FAIL: LLVM :: tools/llvm-ar/error-opening-permission.test (35951 of 44875)
******************** TEST 'LLVM :: tools/llvm-ar/error-opening-permission.test' FAILED ********************
Script:
--
: 'RUN: at line 5';   rm -rf /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ar/Output/error-opening-permission.test.tmp && mkdir -p /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ar/Output/error-opening-permission.test.tmp
: 'RUN: at line 6';   echo file1 > /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ar/Output/error-opening-permission.test.tmp/1.txt
: 'RUN: at line 9';   /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/llvm-ar rc /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ar/Output/error-opening-permission.test.tmp/permission.b /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ar/Output/error-opening-permission.test.tmp/1.txt
: 'RUN: at line 10';   chmod 100 /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ar/Output/error-opening-permission.test.tmp/permission.b
: 'RUN: at line 11';   not /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/llvm-ar p /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ar/Output/error-opening-permission.test.tmp/permission.b 2>&1 |    /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/FileCheck /root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-ar/error-opening-permission.test --check-prefix=NO-PERMISSION -DARCHIVE=/root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ar/Output/error-opening-permission.test.tmp/permission.b -DMSG='Permission denied'
--
Exit Code: 1

Command Output (stderr):
--
/root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-ar/error-opening-permission.test:14:18: error: NO-PERMISSION: expected string not found in input
# NO-PERMISSION: error: unable to open '[[ARCHIVE]]': [[MSG]]
                 ^
<stdin>:1:1: note: scanning from here
file1
^
<stdin>:1:1: note: with "ARCHIVE" equal to "/root/rpmbuild/BUILD/llvm-13\\.0\\.1\\.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ar/Output/error-opening-permission\\.test\\.tmp/permission\\.b"
file1
^
<stdin>:1:1: note: with "MSG" equal to "Permission denied"
file1
^

Input file: <stdin>
Check file: /root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-ar/error-opening-permission.test

-dump-input=help explains the following input dump.

Input was:
<<<<<<
            1: file1 
check:14'0     X~~~~~ error: no match found
check:14'1            with "ARCHIVE" equal to "/root/rpmbuild/BUILD/llvm-13\\.0\\.1\\.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ar/Output/error-opening-permission\\.test\\.tmp/permission\\.b"
check:14'2            with "MSG" equal to "Permission denied"
>>>>>>

--

********************
Testing:  0.. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 
FAIL: LLVM :: tools/llvm-dwarfdump/X86/output.s (36279 of 44875)
******************** TEST 'LLVM :: tools/llvm-dwarfdump/X86/output.s' FAILED ********************
Script:
--
: 'RUN: at line 1';   rm -f /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp1.txt /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp2.txt /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp3.txt
: 'RUN: at line 2';   /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/llvm-mc /root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-dwarfdump/X86/brief.s -filetype obj -triple x86_64-apple-darwin -o /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp.o
: 'RUN: at line 4';   /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/llvm-dwarfdump -o=- /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp.o | /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/FileCheck /root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-dwarfdump/X86/output.s
: 'RUN: at line 6';   /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/llvm-dwarfdump -o=/root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp1.txt /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp.o
: 'RUN: at line 7';   /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/FileCheck /root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-dwarfdump/X86/output.s --input-file /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp1.txt
: 'RUN: at line 9';   touch /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp2.txt
: 'RUN: at line 10';   /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/llvm-dwarfdump -o=/root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp2.txt /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp.o
: 'RUN: at line 11';   /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/FileCheck /root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-dwarfdump/X86/output.s --input-file /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp2.txt
: 'RUN: at line 13';   touch /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp3.txt
: 'RUN: at line 14';   chmod 444 /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp3.txt
: 'RUN: at line 15';   not /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/llvm-dwarfdump -o=/root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp3.txt /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp.o 2>&1 | /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/FileCheck /root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-dwarfdump/X86/output.s  --check-prefix=ERROR1 -DFILE=/root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp3.txt -DMSG='Permission denied'
: 'RUN: at line 17';   not /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/llvm-dwarfdump -o= /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp.o 2>&1 | /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/FileCheck /root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-dwarfdump/X86/output.s  --check-prefix=ERROR2 -DMSG='No such file or directory'
--
Exit Code: 2

Command Output (stderr):
--
/root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-dwarfdump/X86/brief.s:33:2: warning: .macosx_version_min used while targeting darwin
        .macosx_version_min 10, 12
        ^
FileCheck error: '<stdin>' is empty.
FileCheck command line:  /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/FileCheck /root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-dwarfdump/X86/output.s --check-prefix=ERROR1 -DFILE=/root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp3.txt -DMSG=Permission denied

--

********************
Testing:  0.. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 
FAIL: LLVM :: tools/llvm-ifs/fail-file-write.test (36430 of 44875)
******************** TEST 'LLVM :: tools/llvm-ifs/fail-file-write.test' FAILED ********************
Script:
--
: 'RUN: at line 4';   rm -rf /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ifs/Output/fail-file-write.test.tmp.TestDir
: 'RUN: at line 5';   mkdir /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ifs/Output/fail-file-write.test.tmp.TestDir
: 'RUN: at line 6';   touch /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ifs/Output/fail-file-write.test.tmp.TestDir/Output.TestFile
: 'RUN: at line 7';   chmod 400 /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ifs/Output/fail-file-write.test.tmp.TestDir
: 'RUN: at line 8';   not /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/llvm-ifs --output-format=ELF --output=/root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ifs/Output/fail-file-write.test.tmp.TestDir/Output.TestFile /root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-ifs/fail-file-write.test 2>&1 | /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/FileCheck -DMSG='Permission denied' /root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-ifs/fail-file-write.test --check-prefix=ERR
: 'RUN: at line 9';   chmod 777 /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ifs/Output/fail-file-write.test.tmp.TestDir
: 'RUN: at line 10';   rm -rf /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ifs/Output/fail-file-write.test.tmp.TestDir
--
Exit Code: 2

Command Output (stderr):
--
FileCheck error: '<stdin>' is empty.
FileCheck command line:  /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/FileCheck -DMSG=Permission denied /root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-ifs/fail-file-write.test --check-prefix=ERR

--

********************
Testing:  0.. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90.. 
********************
Failed Tests (3):
  LLVM :: tools/llvm-ar/error-opening-permission.test
  LLVM :: tools/llvm-dwarfdump/X86/output.s
  LLVM :: tools/llvm-ifs/fail-file-write.test


Testing Time: 328.02s
  Unsupported      :  1719
  Passed           : 43005
  Expectedly Failed:   148
  Failed           :     3
FAILED: CMakeFiles/check-all 
cd /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu && /usr/bin/python3.7 /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/./bin/llvm-lit -v -sv /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/utils/lit /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test
ninja: build stopped: subcommand failed.
error: Bad exit status from /var/tmp/rpm-tmp.PSG7Oo (%check)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.PSG7Oo (%check)
[root@DAS-OS ~]#

**Comment by Yurii-huang** [comment]
```bash
[1/2] Preparing lit tests
[1/2] Running all regression tests
-- Testing: 44875 tests, 16 workers --
Testing:  0.. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 
FAIL: LLVM :: tools/llvm-ar/error-opening-permission.test (35951 of 44875)
******************** TEST 'LLVM :: tools/llvm-ar/error-opening-permission.test' FAILED ********************
Script:
--
: 'RUN: at line 5';   rm -rf /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ar/Output/error-opening-permission.test.tmp && mkdir -p /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ar/Output/error-opening-permission.test.tmp
: 'RUN: at line 6';   echo file1 > /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ar/Output/error-opening-permission.test.tmp/1.txt
: 'RUN: at line 9';   /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/llvm-ar rc /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ar/Output/error-opening-permission.test.tmp/permission.b /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ar/Output/error-opening-permission.test.tmp/1.txt
: 'RUN: at line 10';   chmod 100 /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ar/Output/error-opening-permission.test.tmp/permission.b
: 'RUN: at line 11';   not /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/llvm-ar p /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ar/Output/error-opening-permission.test.tmp/permission.b 2>&1 |    /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/FileCheck /root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-ar/error-opening-permission.test --check-prefix=NO-PERMISSION -DARCHIVE=/root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ar/Output/error-opening-permission.test.tmp/permission.b -DMSG='Permission denied'
--
Exit Code: 1

Command Output (stderr):
--
/root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-ar/error-opening-permission.test:14:18: error: NO-PERMISSION: expected string not found in input
# NO-PERMISSION: error: unable to open '[[ARCHIVE]]': [[MSG]]
                 ^
<stdin>:1:1: note: scanning from here
file1
^
<stdin>:1:1: note: with "ARCHIVE" equal to "/root/rpmbuild/BUILD/llvm-13\\.0\\.1\\.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ar/Output/error-opening-permission\\.test\\.tmp/permission\\.b"
file1
^
<stdin>:1:1: note: with "MSG" equal to "Permission denied"
file1
^

Input file: <stdin>
Check file: /root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-ar/error-opening-permission.test

-dump-input=help explains the following input dump.

Input was:
<<<<<<
            1: file1 
check:14'0     X~~~~~ error: no match found
check:14'1            with "ARCHIVE" equal to "/root/rpmbuild/BUILD/llvm-13\\.0\\.1\\.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ar/Output/error-opening-permission\\.test\\.tmp/permission\\.b"
check:14'2            with "MSG" equal to "Permission denied"
>>>>>>

--

********************
Testing:  0.. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 
FAIL: LLVM :: tools/llvm-dwarfdump/X86/output.s (36279 of 44875)
******************** TEST 'LLVM :: tools/llvm-dwarfdump/X86/output.s' FAILED ********************
Script:
--
: 'RUN: at line 1';   rm -f /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp1.txt /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp2.txt /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp3.txt
: 'RUN: at line 2';   /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/llvm-mc /root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-dwarfdump/X86/brief.s -filetype obj -triple x86_64-apple-darwin -o /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp.o
: 'RUN: at line 4';   /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/llvm-dwarfdump -o=- /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp.o | /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/FileCheck /root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-dwarfdump/X86/output.s
: 'RUN: at line 6';   /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/llvm-dwarfdump -o=/root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp1.txt /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp.o
: 'RUN: at line 7';   /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/FileCheck /root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-dwarfdump/X86/output.s --input-file /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp1.txt
: 'RUN: at line 9';   touch /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp2.txt
: 'RUN: at line 10';   /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/llvm-dwarfdump -o=/root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp2.txt /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp.o
: 'RUN: at line 11';   /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/FileCheck /root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-dwarfdump/X86/output.s --input-file /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp2.txt
: 'RUN: at line 13';   touch /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp3.txt
: 'RUN: at line 14';   chmod 444 /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp3.txt
: 'RUN: at line 15';   not /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/llvm-dwarfdump -o=/root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp3.txt /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp.o 2>&1 | /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/FileCheck /root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-dwarfdump/X86/output.s  --check-prefix=ERROR1 -DFILE=/root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp3.txt -DMSG='Permission denied'
: 'RUN: at line 17';   not /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/llvm-dwarfdump -o= /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp.o 2>&1 | /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/FileCheck /root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-dwarfdump/X86/output.s  --check-prefix=ERROR2 -DMSG='No such file or directory'
--
Exit Code: 2

Command Output (stderr):
--
/root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-dwarfdump/X86/brief.s:33:2: warning: .macosx_version_min used while targeting darwin
        .macosx_version_min 10, 12
        ^
FileCheck error: '<stdin>' is empty.
FileCheck command line:  /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/FileCheck /root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-dwarfdump/X86/output.s --check-prefix=ERROR1 -DFILE=/root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-dwarfdump/X86/Output/output.s.tmp3.txt -DMSG=Permission denied

--

********************
Testing:  0.. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 
FAIL: LLVM :: tools/llvm-ifs/fail-file-write.test (36430 of 44875)
******************** TEST 'LLVM :: tools/llvm-ifs/fail-file-write.test' FAILED ********************
Script:
--
: 'RUN: at line 4';   rm -rf /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ifs/Output/fail-file-write.test.tmp.TestDir
: 'RUN: at line 5';   mkdir /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ifs/Output/fail-file-write.test.tmp.TestDir
: 'RUN: at line 6';   touch /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ifs/Output/fail-file-write.test.tmp.TestDir/Output.TestFile
: 'RUN: at line 7';   chmod 400 /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ifs/Output/fail-file-write.test.tmp.TestDir
: 'RUN: at line 8';   not /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/llvm-ifs --output-format=ELF --output=/root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ifs/Output/fail-file-write.test.tmp.TestDir/Output.TestFile /root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-ifs/fail-file-write.test 2>&1 | /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/FileCheck -DMSG='Permission denied' /root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-ifs/fail-file-write.test --check-prefix=ERR
: 'RUN: at line 9';   chmod 777 /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ifs/Output/fail-file-write.test.tmp.TestDir
: 'RUN: at line 10';   rm -rf /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test/tools/llvm-ifs/Output/fail-file-write.test.tmp.TestDir
--
Exit Code: 2

Command Output (stderr):
--
FileCheck error: '<stdin>' is empty.
FileCheck command line:  /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/bin/FileCheck -DMSG=Permission denied /root/rpmbuild/BUILD/llvm-13.0.1.src/test/tools/llvm-ifs/fail-file-write.test --check-prefix=ERR

--

********************
Testing:  0.. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90.. 
********************
Failed Tests (3):
  LLVM :: tools/llvm-ar/error-opening-permission.test
  LLVM :: tools/llvm-dwarfdump/X86/output.s
  LLVM :: tools/llvm-ifs/fail-file-write.test


Testing Time: 328.02s
  Unsupported      :  1719
  Passed           : 43005
  Expectedly Failed:   148
  Failed           :     3
FAILED: CMakeFiles/check-all 
cd /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu && /usr/bin/python3.7 /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/./bin/llvm-lit -v -sv /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/utils/lit /root/rpmbuild/BUILD/llvm-13.0.1.src/x86_64-openEuler-linux-gnu/test
ninja: build stopped: subcommand failed.
```
