### ISSUE TITLE
flang/lib/Semantics/expression.cpp:4413: Pointless vector copy ?

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#94929]
Static analyser cppcheck says:

flang/lib/Semantics/expression.cpp:4413:31: performance: Function parameter 'oprs' should be passed by const reference. [passedByValue]

Source code is

MaybeExpr ArgumentAnalyzer::TryDefinedOp(
    std::vector<const char *> oprs, parser::MessageFixedText error) {

Code that avoids the vector copy is:

MaybeExpr ArgumentAnalyzer::TryDefinedOp(
    const std::vector<const char *> & oprs, parser::MessageFixedText error) {

**Comment by klausler** [comment]
https://github.com/llvm/llvm-project/pull/95050
