### ISSUE TITLE
flang/lib/Semantics/scope.cpp:59: Suggest avoid pointless copy of a map

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#94932]
Static analyser cppcheck says:

flang/lib/Semantics/scope.cpp:59:44: performance: Function parameter 'symbols' should be passed by const reference. [passedByValue]

Source code is

static std::vector<common::Reference<T>> GetSortedSymbols(
    std::map<SourceName, MutableSymbolRef> symbols) {

Suggest new code:

static std::vector<common::Reference<T>> GetSortedSymbols(
    const std::map<SourceName, MutableSymbolRef> & symbols) {

**Comment by klausler** [comment]
https://github.com/llvm/llvm-project/pull/95048
