### ISSUE TITLE
Allows using-declaration to refer to scoped enumerator

### ISSUE THREAD

**Issue by be579e8c-b74b-475b-a126-3b8cefdd833c** [llvm/llvm-project#9496]
|  |  |
| --- | --- |
| Bugzilla Link | [9124](https://llvm.org/bz9124) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor,@gnzlbg,@zygoloid |

## Extended Description 
Clang is supposed to reject the below, but doesn't

```cpp
enum class A { B };
int main() {
  using A::B; // should be an error
}
```

Although the spec (N3225) doesn't say so currently (DR already filed), clang should presumably also reject referring to an unscoped enumerator in a using declaration: 

```cpp
enum A { B };
int main() {
  using A::B; // presumably should be error too. 
}
```

I think best may be to forbid the using declaration of having a nested name specifier referring to an enumeration.

**Comment by shafik** [comment]
There are both valid and accepted by all the implementations I checked.
