### ISSUE TITLE
llvm/lib/CodeGen/RegAllocGreedy.h:428: Pointless copy of object ?

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#95033]
Static analyser cppcheck says:

llvm/lib/CodeGen/RegAllocGreedy.h:428:28: performance: Function parameter 'other' should be passed by const reference. [passedByValue]

Source code is

    void add(RAGreedyStats other) {

Suggest new code

    void add( const RAGreedyStats & other) {

**Comment by RKSimon** [comment]
Fixed by 79ce70b8033815b6abd3a9a5cc2335de70f1aaab
