### ISSUE TITLE
llvm/include/llvm/Frontend/OpenMP/OMPIRBuilder.h:201: Pointless copy of object ? 

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#95036]
Static analyser cppcheck says:

llvm/include/llvm/Frontend/OpenMP/OMPIRBuilder.h:201:46: performance: Function parameter 'RHS' should be passed by const reference. [passedByValue]

Source code is

  bool operator<(const TargetRegionEntryInfo RHS) const {

Suggest new code:

  bool operator<(const TargetRegionEntryInfo & RHS) const {

**Comment by shiltian** [comment]
feel free to submit a PR for this simple fix
