### ISSUE TITLE
[clang-format] Considering macros as access modifiers

### ISSUE THREAD

**Issue by omarcou33** [llvm/llvm-project#95094]
This is not a bug but rather a suggestion for a new feature.

In the (quite old) project we are working on with my team, we are considering using clang-format for formatting our C++ code, but we have currently one blocking problem that prevents us from doing so:
In our public headers, we use certain macros in front of access modifiers in order to give complementary information to whatever processes we use for documentation/wrapping (typically something like `SOME_MACRO public:`, etc). The problem is that there is currently nothing to inform clang-format that some macros should be treated as access modifiers (for indentation mainly). After investigation, every solution we tried with the currently existing options either breaks indentation of the public/private modifiers preceded by macros, or breaks the documentation/wrapping processes that follow.

Would it be possible to add an option to define a list of macros that should be treated as access modifiers during formatting?

**Comment by owenca** [comment]
Did you try the `AttributeMacros` option?

**Comment by omarcou33** [comment]
Yes, we tried options `AttributeMacros` as well as `StatementMacros`, `StatementAttributeLikeMacros`, `WhitespaceSensitiveMacros`... (even `NamespaceMacros` at some point...).
