### ISSUE TITLE
[Missed optimization] `has_single_bit` when the value is known to be non-zero

### ISSUE THREAD

**Issue by MitalAshok** [llvm/llvm-project#95255]
```c++
bool test1(unsigned n) {
    __builtin_assume(n);
    return __builtin_popcount(n) == 1;
}

bool test2(unsigned n) {
    __builtin_assume(n);
    return (n != 0) && ((n & (n-1u)) == 0);
}
```

Where `test1` looks like libstdc++'s `std::has_single_bit` and `test2` looks like libc++'s `std::has_single_bit`.  
These are optimized differently with the non-zero assumption: https://godbolt.org/z/b8jTae91x

```asm
test1:                                  # @test1
        popcnt  eax, edi
        cmp     eax, 1
        sete    al
        ret
test2:                                  # @test2
        blsr    eax, edi
        sete    al
        ret
```

(without the assumption, they are both optimized to use `popcnt`)

`return __builtin_popcount(n) <= 1;` *is* optimized to `blsr`

**Comment by dtcxzyw** [comment]
As we don't know which form (ctpop(x) <u 2 or == 1) is better for this pattern (See https://github.com/llvm/llvm-project/pull/67268), do we need a new intrinsic function like `i1 is_power_of_2(iN %x, i1 zero_is_poison)`?

@goldsteinn @nikic @topperc @arsenm @RKSimon

**Comment by arsenm** [comment]
A new intrinsic is way too heavy of a solution for a very specific optimization

**Comment by dtcxzyw** [comment]
> A new intrinsic is way too heavy of a solution for a very specific optimization

How about adding a new parameter `i1 is_zero_poison` to `ctpop`?

**Comment by efriedma-quic** [comment]
Isn't that the same as `call range(i32 1, 33) i32 @llvm.ctpop.i32(i32 %x)`?

**Comment by dtcxzyw** [comment]
> Isn't that the same as `call range(i32 1, 33) i32 @llvm.ctpop.i32(i32 %x)`?

You are right :)
