### ISSUE TITLE
clang doesn't support -Wa,--defsym

### ISSUE THREAD

**Issue by stsp** [llvm/llvm-project#95386]
```
$ clang -x assembler -c - -m32 -Wa,--defsym -Wa,_DJ64=1
clang: error: unsupported argument '--defsym' to option '-Wa,'
clang: error: unsupported argument '_DJ64=1' to option '-Wa,'
```

With gcc+gas this works as expected.

**Comment by MaskRay** [comment]
https://reviews.llvm.org/D26213 `-Wa,-defsym` is supported. I am testing a patch to add `-Wa,--defsym`. Note: when the integrated assembler is enabled, clangDriver implements a small set of popular -Wa, options. I think `--defsym` is kinda popular. I personally use `--defsym` a lot in assembly tests, especially in lld/test/ELF, though mostly using an internal-facing tool llvm-mc.

**Comment by stsp** [comment]
Thanks for the patch and a work-around!
`-defsym` works for me as well.
