### ISSUE TITLE
Backport 493422ecb4451b721fe6e66b17292bad7578bc3e to release/18.x

### ISSUE THREAD

**Issue by johnplatts** [llvm/llvm-project#95454]
/cherry-pick 493422ecb4451b721fe6e66b17292bad7578bc3e

Backporting the fix in commit 493422ecb4451b721fe6e66b17292bad7578bc3e to the release/18.x branch should resolve issues #92615 and #92602.

Are there plans to release an LLVM 18.1.8 release as the backport of commit 493422ecb4451b721fe6e66b17292bad7578bc3e to the release/18.x branch fixes a major bug with LLVM on the s390x target?

**Comment by EugeneZelenko** [comment]
@tstellar: Is 18.x is still maintained? If not, should relevant milestone be removed?

**Comment by nikic** [comment]
That's not the commit that landed upstream.

/cherry-pick 7e4c6e98fa05f5c3bf14f96365ae74a8d12c6257

**Comment by nikic** [comment]
@johnplatts Can you please clarify whether this fix is for a regression in LLVM 18 or a pre-existing issue?

**Comment by johnplatts** [comment]
> @johnplatts Can you please clarify whether this fix is for a regression in LLVM 18 or a pre-existing issue?

This fix is for a pre-existing issue in LLVM 18 and earlier on s390x (with the `-march=z14 -mzvector` compiler options) that is breaking code that compiles correctly with GCC.
