### ISSUE TITLE
Some clang interpreter tests are failing on Windows if vcvarsall isn't run

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#95451]
See http://45.33.8.238/win/89424/step_6.txt

```
-- Testing: 20527 tests, 48 workers --
...
C:\src\llvm-project\out\gn\obj\clang\unittests\Interpreter\.\ClangReplInterpreterTests.exe --gtest_filter=InterpreterTest.Value
--
JIT session error: Symbols not found: [ ??3@YAXPEAX_K@Z ]
```

This used to work back in March (and for years before). I'm currently bisecting; current regression range is https://github.com/llvm/llvm-project/compare/675e7bd1b94...434ee06d77

**Comment by nico** [comment]
new range: https://github.com/llvm/llvm-project/compare/675e7bd1b94...6552af1968

**Comment by nico** [comment]
new range: https://github.com/llvm/llvm-project/compare/675e7bd1b94...4351787fb

**Comment by nico** [comment]
new range: https://github.com/llvm/llvm-project/compare/446f66d6...4351787fb

**Comment by nico** [comment]
new range: https://github.com/llvm/llvm-project/compare/7630775e...4351787fb

**Comment by nico** [comment]
```
$ demumble '??3@YAXPEAX_K@Z'
void __cdecl operator delete(void *, unsigned __int64)
```

Hm, probably https://github.com/llvm/llvm-project/commit/130e93cc26ca9d3ac50ec5a92e3109577ca2e702 . Should we turn this off in clang-interp?

@tbaederr, looks like you touched clang-interp some. Do you have an opinion here?

**Comment by nico** [comment]
new range: https://github.com/llvm/llvm-project/compare/7630775e...7370b109b

**Comment by nico** [comment]
Yup, bisect finished, and it's indeed due to https://github.com/llvm/llvm-project/commit/130e93cc26ca9d3ac50ec5a92e3109577ca2e702

**Comment by tbaederr** [comment]
That's not the kind of interpreter I've been touching

**Comment by nico** [comment]
😅 Oh, apologies!

**Comment by wangpc-pp** [comment]
What does the `vcvarsall isn't run` mean here? (Not familiar with Windows...)

**Comment by nico** [comment]
`vsvarsall` opens a MSVC shell that has `%LIB%` pointing at all the library directories, etc.

Maybe that part's actually a red herring though, and that system just doesn't have a new enough c++ runtime to have sized deallocs. Not sure.

Since these two tests don't test anything with sized deallocation, maybe we should make these tests just pass `-fno-sized-deallocation`.

**Comment by nico** [comment]
My bot is happy again 🙂
