### ISSUE TITLE
warn when code would be treated differently under gcc

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#9557]
|  |  |
| --- | --- |
| Bugzilla Link | [9185](https://llvm.org/bz9185) |
| Version | trunk |
| OS | Linux |
| Attachments | [testcase 1: no ADL](https://user-images.githubusercontent.com/60944935/143742722-fc5e01dd-abd7-4e14-830f-fc42497bb5a6.gz), [testcase 2: ADL only](https://user-images.githubusercontent.com/60944935/143742723-9218bbcf-55f0-4fce-9b33-1b4c4be4425f.gz), [testcase 3: ADL and non-ADL lookups match](https://user-images.githubusercontent.com/60944935/143742724-522aa2a7-efce-4f0e-9653-f06c7287738c.gz), [testcase 4: ADL and non-ADL differ](https://user-images.githubusercontent.com/60944935/143742725-f9ee5300-fbc3-4db3-ae22-32358a6a77ca.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor |

## Extended Description 
Attached are four testcases, all of which print "AAAAAAAAAAAAAAAAAAAAAA" when compiled correctly, under clang.

Gcc prints "BBBBBBBBBBBBBBBBBBBBBB" for all of them. It would be really cool if we could emit a warning in cases we can inexpensively detect where gcc is going to miscompile the code. This would save lots of gcc to clang porting time.

**Comment by philnik777** [comment]
All of the test cases have been fixed in GCC, so I don't think there is any point in pursuing this.
