### ISSUE TITLE
[libc] Investigate if the current implementation of the fcntl is correct.

### ISSUE THREAD

**Issue by simonzgx** [llvm/llvm-project#95570]
There is a very puzzling piece of code in our current implementation of `fcntl`. As follows:

```c++
  case F_GETOWN: {
    struct f_owner_ex fex;
    int retVal = syscall_impl<int>(SYS_fcntl, fd, F_GETOWN_EX, &fex);
    if (retVal == -EINVAL)
      return syscall_impl<int>(SYS_fcntl, fd, cmd,
                               reinterpret_cast<void *>(arg));
    if (static_cast<unsigned long>(retVal) <= -4096UL)
      return fex.type == F_OWNER_PGRP ? -fex.pid : fex.pid;

    libc_errno = -retVal;
    return -1;
  }
```

It was copied from [GLIBC](https://github.com/bminor/glibc/blob/master/sysdeps/unix/sysv/linux/fcntl.c#L92), and we need to confirm whether it is correct and appropriate to write it this way.

**Comment by nickdesaulniers** [comment]
Perhaps something in the kernel might allude to what's going on here?

**Comment by lntue** [comment]
The question I have with:
```
    if (static_cast<unsigned long>(retVal) <= -4096UL)
      return fex.type == F_OWNER_PGRP ? -fex.pid : fex.pid;
```
is that it treat the erroneous condition `retVal < -4096` the same as ok condition `retVal >= 0`.

**Comment by simonzgx** [comment]
First of all, as far as I know, GLIBC makes extensive use of the expression `static_cast<unsigned long>(retVal) <= -4096UL` to handle system call errors, mainly for the sake of robustness. Linux system call error codes typically fall within the range of [-1, -4095]. Therefore, if `static_cast<unsigned long>(retVal)` is greater than `-4096UL`, it indicates that an error has definitely occurred in the system call.

Secondly, referring to https://www.man7.org/linux/man-pages/man2/fcntl.2.html, in versions prior to Linux 2.6.32, the handling of the return value for the **F_GETOWN** command in the ``fcntl`` function was not perfect, there exists an ambiguity in distinguishing whether a negative return value is an error code or a legitimate process group id.
> ```
> F_GETOWN (void)
>     Return (as the function result) the process ID or process
>     group ID currently receiving SIGIO and SIGURG signals for
>     events on file descriptor fd.  Process IDs are returned as
>     positive values; process group IDs are returned as
>     negative values (but see BUGS below).  arg is ignored.
> 
> BUGS
>     A limitation of the Linux system call conventions on some
>     architectures (notably i386) means that if a (negative) process
>     group ID to be returned by F_GETOWN falls in the range -1 to
>     -4095, then the return value is wrongly interpreted by glibc as
>     an error in the system call; that is, the return value of fcntl()
>     will be -1, and errno will contain the (positive) process group
>     ID.  The Linux-specific F_GETOWN_EX operation avoids this
>     problem.  Since glibc 2.11, glibc makes the kernel F_GETOWN
>     problem invisible by implementing F_GETOWN using F_GETOWN_EX.
> ```

Finally, returning to the code mentioned in this issue, the two expressions ``static_cast<unsigned long>(retVal) <= -4096UL`` and ``retVal >= 0`` are indeed equivalent. We might consider making the following simple modification:
```c++
  case F_GETOWN: {
    struct f_owner_ex fex;
    int retVal =
        LIBC_NAMESPACE::syscall_impl<int>(SYS_fcntl, fd, F_GETOWN_EX, &fex);
    if (retVal >= 0)
      return fex.type == F_OWNER_PGRP ? -fex.pid : fex.pid;
    // If the return value is EINVAL, it means that the current Linux version
    // may be lower than 2.6.32, which does not support F_GETOWN_EX. Therefore,
    // it is necessary to try again using F_GETOWN.
    if (retVal == -EINVAL)
      return LIBC_NAMESPACE::syscall_impl<int>(SYS_fcntl, fd, F_GETOWN,
                                               reinterpret_cast<void *>(arg));
    libc_errno = -retVal;
    return -1;
  }
```

**Comment by nickdesaulniers** [comment]
>  // If the return value is EINVAL, it means that the current Linux version
>    // may be lower than 2.6.32,

That version of linux is 3000 years old, and if have users trying to use that long unsupported kernel version, they should seek help. Let's not support such theoretical users.

**Comment by nickdesaulniers** [comment]
If I need to, I'll add documentation that we ONLY support kernel versions listed on https://kernel.org/. Anything older is out of scope for llvm-libc.
