### ISSUE TITLE
[mc] init_array entsize diff from binutils as

### ISSUE THREAD

**Issue by hstk30-hw** [llvm/llvm-project#95626]
https://godbolt.org/z/a156efnK3

The `ES` is 0 when use llvm-as, but 8 for binutils as.

```
entsize
  Size in bytes for entries in fixed-size tables such as the symbol table.
```

**Comment by hstk30-hw** [comment]
CC @efriedma-quic @dongjianqiang2

**Comment by efriedma-quic** [comment]
I'm not sure why binutils is adding the entsize here; it doesn't have any meaning in this context.  Along those lines, nothing should care about the entsize in the first place, so I can't see how it matters if it's different.

**Comment by dongjianqiang2** [comment]
The EntrySize field in an ELF file is used to indicate the size of each entry in the Program Header Table and Section Header Table, as well as the size of entries in certain specific sections. This is crucial for parsing and reading different parts of the ELF file, ensuring that compilers, linkers, and loaders can correctly handle the structure and content of ELF files.

**Comment by efriedma-quic** [comment]
> The EntrySize field in an ELF file is used to indicate the size [...]

Copy-pasting ChatGPT responses into bug reports isn't helpful.

**Comment by dongjianqiang2** [comment]
> > The EntrySize field in an ELF file is used to indicate the size [...]
> 
> Copy-pasting ChatGPT responses into bug reports isn't helpful.

Yes, currently we are testing the differences between LLVM and binutils assemblers and have identified this particular difference. We are not very clear about the historical origin of this difference, so Hanwei raised this issue to seek advice on this point of divergence ; )

**Comment by efriedma-quic** [comment]
Like I said originally, the entsize of sections really only matters for mergeable sections.  binutils as syntax doesn't even allow specifying the entsize for non-mergeable sections (see https://sourceware.org/binutils/docs/as/Section.html).

If you want to know why binutils behaves the way it does, maybe you can ask on the binutils mailing list.

**Comment by MaskRay** [comment]
Solaris sets `sh_entsize` for `.init_array` and their elfdump influenced binutils to set it in 2016: 
https://sourceware.org/bugzilla/show_bug.cgi?id=20118

But I don't think that is useful.... There is some value to reserve `sh_entsize!=0` sections in relocatable file to indicate SHF_MERGE sections.
