### ISSUE TITLE
DSA needs support for Vector Type.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#9564]
|  |  |
| --- | --- |
| Bugzilla Link | [9192](https://llvm.org/bz9192) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
At the very least
1. Adding support for insertelement, extractelement, shufflevector.
2. Recognizing vector type in GEP, SelectInst, BitcastInst.

Basic testcases can be found in SingleSource/UnitTests/Vector.

**Comment by arsenm** [comment]
Don't think DSA exists anymore
