### ISSUE TITLE
[clang-tidy] bugprone-empty-catch in destructor

### ISSUE THREAD

**Issue by joto** [llvm/llvm-project#95663]
Destructors are not supposed to throw. Sometimes there is nothing you can do in a destructor but catching a possible exception and ignoring it. The alternative is that the program is terminated and you loose all control over what's happening.

Typical cases include an error message being logged in a destructor or a temp file being removed in a destuctors. In both cases you might already be in a situation where something broke and you are doing your best to report this or clean up. But if that fails, you have no other option but to ignore that failure.

So I believe clang-tidy should make an exception for destructors in the bugprone-empty-catch check.

**Comment by PiotrZSL** [comment]
You can always but comment there with info that exception is not handled on prupose, or "return statement".
Also watch out for try-catch blocks like:
```

~Destructor()
try
{
    throw 1;
}
catch(...)
{
}
```

as in such situation std::abort will be called anyway.

**Comment by PiotrZSL** [comment]
I'm closing this issue, as I don't see a way forward and check provides a way to deal with this issues via comments.
If current answer is not sufficient, please re-open.
