### ISSUE TITLE
Regression in impact of `-new-struct-path-tbaa` on strict-alias analysis

### ISSUE THREAD

**Issue by OfekShilon** [llvm/llvm-project#95661]
```cpp
struct Wrapper { int t; };
struct T { Wrapper a, b; };

void g(T& t1, const T& t2 ) {
    t1.a = t2.a;
    t1.b = t2.b;
}
```
Up until clang 17, `-new-struct-path-tbaa` used to be able to deduce that `t1.a` and `t2.b` do not alias.  in clang 18 it no longer does
In this godbolt https://godbolt.org/z/MGG98Gfra it can be seen that clang17 is able to vectorize the two assigments into one, but clang18 isn't.  The diff is also visible in the opt-remarks view.

**Comment by antoniofrighetto** [comment]
Think this makes the regression a bit more evident: https://godbolt.org/z/qfxPvcGPa.

**Comment by antoniofrighetto** [comment]
@OfekShilon Do you require this to be backported to 19.x by any chance?
