### ISSUE TITLE
fatal error: error in backend: Cannot select: intrinsic %llvm.preserve.union.access.index

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#95691]
From the clang testsuite, file ./CodeGen/bpf-preserve-access-index.c
does this with recent clang:

test $ /home/dcb40b/llvm/results/bin/clang -g ./CodeGen/bpf-preserve-access-index.c
fatal error: error in backend: Cannot select: intrinsic %llvm.preserve.union.access.index
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 19.0.0git (https://github.com/llvm/llvm-project.git 7cb5faf6da5a6f6335aca8a2532e5320ec434458)
Target: x86_64-unknown-linux-gnu

[bpf-preserve-access-index-47d72d.c.gz](https://github.com/user-attachments/files/15856636/bpf-preserve-access-index-47d72d.c.gz)
[bpf-preserve-access-index-47d72d.sh.gz](https://github.com/user-attachments/files/15856637/bpf-preserve-access-index-47d72d.sh.gz)

**Comment by phoebewang** [comment]
Some buildins are not supported by all target. You need to specify `-target bpfeb` like the RUN command in this test.
