### ISSUE TITLE
[feat] clang-tidy could accept multiple source files in one invocation

### ISSUE THREAD

**Issue by peakschris** [llvm/llvm-project#95717]
We are integrating clang-tidy into the bazel build system, and for consistency with other linters we would like clang-tidy to accept multiple source files on the command line, and process them in sequence returning a composite set of results. The single set of clang-tidy and compilation options should apply to alll source files, and the caller should ensure that the set of source files passed in are all consistent in this regard.

This would give clang-tidy a similar usage paradigm to pmd, eslint, ktlint, vale, buf, flake8, shellcheck

**Comment by 5chmidti** [comment]
clang-tidy already supports multiple source files to be passed to the tool: `clang-tidy -p build src/a.cpp src/b.cpp` (from the help: `clang-tidy [options] <source0> [... <sourceN>]`)
Are you having a particular issue?

**Comment by peakschris** [comment]
@5chmidti Oh, that could be really useful! We are not using compile commands, and are using the `--` version of the invocation that doesn't appear in the manpage but is mentioned in one sentence in the docs:

```
clang-tidy test.cpp -- -Imy_project/include -DMY_DEFINES ...
```

Can we pass multiple source files before the `--`?

Thanks!

**Comment by peakschris** [comment]
Multiple files passed together with -- is working for us, thanks!
