### ISSUE TITLE
error::install  package

### ISSUE THREAD

**Issue by hattorikohei76** [llvm/llvm-project#95737]
'(v1.10) pkg> add StaticArrays

   Resolving package versions...
  No Changes to `/lustre/home/kohei76/.julia/environments/v1.10/Project.toml`
  No Changes to `/lustre/home/kohei76/.julia/environments/v1.10/Manifest.toml`
Precompiling project...
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libLLVM-15jl.so(+0xa3d44f)[0x7fbe72ff444f]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libLLVM-15jl.so(+0xa3adfc)[0x7fbe72ff1dfc]
/lib64/libpthread.so.0(+0x12cf0)[0x7fbe77966cf0]
/lib64/libc.so.6(gsignal+0x10f)[0x7fbe71c0aacf]
/lib64/libc.so.6(abort+0x127)[0x7fbe71bddea5]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libstdc++.so.6(+0xa89bb)[0x7fbe723ab9bb]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libstdc++.so.6(+0xb836a)[0x7fbe723bb36a]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libstdc++.so.6(+0xb83d5)[0x7fbe723bb3d5]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libstdc++.so.6(+0xb8627)[0x7fbe723bb627]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libstdc++.so.6(_ZSt20__throw_system_errori+0x83)[0x7fbe723ae627]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libstdc++.so.6(+0xe4eb5)[0x7fbe723e7eb5]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libLLVM-15jl.so(+0x986af3)[0x7fbe72f3daf3]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libstdc++.so.6(+0xe4b23)[0x7fbe723e7b23]
/lib64/libpthread.so.0(+0x81ca)[0x7fbe7795c1ca]
/lib64/libc.so.6(clone+0x43)[0x7fbe71bf5e73]
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libLLVM-15jl.so(+0xa3d44f)[0x7fb7c280f44f]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libLLVM-15jl.so(+0xa3adfc)[0x7fb7c280cdfc]
/lib64/libpthread.so.0(+0x12cf0)[0x7fb7c7181cf0]
/lib64/libc.so.6(gsignal+0x10f)[0x7fb7c1425acf]
/lib64/libc.so.6(abort+0x127)[0x7fb7c13f8ea5]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libstdc++.so.6(+0xa89bb)[0x7fb7c1bc69bb]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libstdc++.so.6(+0xb836a)[0x7fb7c1bd636a]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libstdc++.so.6(+0xb83d5)[0x7fb7c1bd63d5]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libstdc++.so.6(+0xb8627)[0x7fb7c1bd6627]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libstdc++.so.6(_ZSt20__throw_system_errori+0x83)[0x7fb7c1bc9627]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libstdc++.so.6(+0xe4eb5)[0x7fb7c1c02eb5]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libLLVM-15jl.so(+0x986af3)[0x7fb7c2758af3]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libstdc++.so.6(+0xe4b23)[0x7fb7c1c02b23]
/lib64/libpthread.so.0(+0x81ca)[0x7fb7c71771ca]
/lib64/libc.so.6(clone+0x43)[0x7fb7c1410e73]
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libLLVM-15jl.so(+0xa3d44f)[0x7fcd8c89144f]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libLLVM-15jl.so(+0xa3adfc)[0x7fcd8c88edfc]
/lib64/libpthread.so.0(+0x12cf0)[0x7fcd91203cf0]
/lib64/libc.so.6(gsignal+0x10f)[0x7fcd8b4a7acf]
/lib64/libc.so.6(abort+0x127)[0x7fcd8b47aea5]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libstdc++.so.6(+0xa89bb)[0x7fcd8bc489bb]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libstdc++.so.6(+0xb836a)[0x7fcd8bc5836a]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libstdc++.so.6(+0xb83d5)[0x7fcd8bc583d5]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libstdc++.so.6(+0xb8627)[0x7fcd8bc58627]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libstdc++.so.6(_ZSt20__throw_system_errori+0x83)[0x7fcd8bc4b627]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libstdc++.so.6(+0xe4eb5)[0x7fcd8bc84eb5]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libLLVM-15jl.so(+0x986af3)[0x7fcd8c7daaf3]
/lustre/home/kohei76/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/lib/julia/libstdc++.so.6(+0xe4b23)[0x7fcd8bc84b23]
/lib64/libpthread.so.0(+0x81ca)[0x7fcd911f91ca]
/lib64/libc.so.6(clone+0x43)[0x7fcd8b492e73]
  ◓ PkgVersion
  ◓ DocStringExtensions
  ◓ Preferences`

**Comment by asl** [comment]
Consider reporting Julia issues to Julia bugtracker. Also, here we're seeing:
```
terminate called after throwing an instance of 'std::system_error'
what(): Resource temporarily unavailable
```

So the problem likely is related to some I/O error on your end.
