### ISSUE TITLE
[clang] template template class with std::vector as a default parameter fails to compile with __is_pointer requires template arguments

### ISSUE THREAD

**Issue by bobby3605** [llvm/llvm-project#95733]
While investigating a separate [issue](https://github.com/llvm/llvm-project/issues/95732) with clang, I came across this issue.
The following code compiles on gcc, but not clang.
https://godbolt.org/z/3boKbWqc8

**Comment by cor3ntin** [comment]
@mizvekov

**Comment by philnik777** [comment]
This is most likely #95598.

**Comment by jwakely** [comment]
> This is most likely #95598.

Yes, definitely.
