### ISSUE TITLE
llc crashes on fp128

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#9573]
|  |  |
| --- | --- |
| Bugzilla Link | [9201](https://llvm.org/bz9201) |
| Version | 2.8 |
| OS | Linux |
| Attachments | [IR file that when assembled and passed to llc, triggers behaviour.](https://user-images.githubusercontent.com/60944935/143742731-fffd0822-0267-4be1-ba5f-06cbc545e672.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Running the following on my machine results in this:

$ llvm-as test6.ll; llc test6.bc
llvm-as: test6.ll:8:28: error: use of undefined value '%int'
  store i1 %primitive, i1* %int
                           ^
llc: /home/bernard/src/llvm-2.8/lib/Target/TargetData.cpp:293: unsigned int llvm::TargetData::getAlignmentInfo(llvm::AlignTypeEnum, uint32_t, bool, const llvm::Type*) const: Assertion `AlignType == VECTOR_ALIGN && "Unknown alignment type!"' failed.
0  libLLVM-2.8.so 0xf6f2e4eb
1  libLLVM-2.8.so 0xf6f2e278
2                 0xf771f400 __kernel_sigreturn + 0
Stack dump:
0.	Program arguments: llc test6.bc 
1.	Running pass 'Function Pass Manager' on module 'test6.bc'.
2.	Running pass 'X86 DAG->DAG Instruction Selection' on function '@main'
Aborted

**Comment by arsenm** [comment]
Seems to work fine now
