### ISSUE TITLE
[HLSL] Add DirectXTargetCodeGenInfo and the code paths to convert HLSL types to DirectX target types

### ISSUE THREAD

**Issue by bogner** [llvm/llvm-project#95952]
Introduce `CGHLSLRuntime::convertHLSLSpecificType` and `TargetInfo::getHLSLType` interfaces and implement these in DirectXTargetCodeGenInfo to lower the HLSLResource built in type to DirectX-specific TargetExtTypes.

The interfaces should be similar to the OpenCL interfaces of the same names.

AC:
- The HLSLResource built in type used in HLSL's `RWBuffer` is converted to a `target("dx.TypedBuffer")` during clang codegen when targeting DXIL
- It's obvious where and how to add logic for other HLSL buffer and DXIL target types

**Comment by hekota** [comment]
Blocked by #104861
