### ISSUE TITLE
[Clang] [Parser] Unambiguous CTAD expression disambiguated as function type

### ISSUE THREAD

**Issue by MitalAshok** [llvm/llvm-project#95985]
https://godbolt.org/z/6sraGGjYE

```c++
template<typename T>
struct X {
    constexpr X(T) {}
};

int i = sizeof(X(int()));
```

Clang complains that:

```
<source>:6:16: error: use of class template 'X' requires template arguments; argument deduction not allowed in function return type
    6 | int i = sizeof(X(int()));
      |                ^
<source>:2:8: note: template is declared here
    2 | struct X {
      |        ^
```

Because it incorrectly assumes that since `Parser::isCXXDeclarationSpecifier` at `X`, and `(int())` is a valid [*parameters-and-qualifiers*](https://eel.is/c++draft/dcl.decl.general#nt:parameters-and-qualifiers), it must be parsed as a type and not an expression.

But there is no ambiguity since `X(int())` cannot be a function type, so https://eel.is/c++draft/dcl.ambig.res doesn't apply and it should be an expression.

This would also solve #95598 if fixed, since `__is_pointer(T)` could no longer be a function type.

**Comment by zygoloid** [comment]
> But there is no ambiguity since X(int()) cannot be a function type

How do you conclude that? The grammar says:

> *simple-type-specifier*: *nested-name-specifier*[opt] *template-name*

So `X(int())` can parse as a type, so it is disambiguated as a type. The disambiguation rules don't care about semantic concerns like where CTAD is permitted.

**Comment by MitalAshok** [comment]
@zygoloid That makes sense: I thought that "syntactically" meant it could be parsed and return a type, but it looks like just if the grammar matches. So `X(int())` is not a syntax/parser error but a semantic error
