### ISSUE TITLE
Excessive optimization removes necessary code in Clang Compiler for ARM and AARCH64

### ISSUE THREAD

**Issue by P1119r1m** [llvm/llvm-project#96054]
## TL;DR.

The Clang compiler, starting from version 15.0.0, demonstrates a critical issue where aggressive optimization (-Os) removes essential code in scenarios targeting both ARM and AARCH64 platforms.

#### Clang 15.0.0 - ARM - NO PROBLEM
- https://godbolt.org/z/39sn3TT61

#### Clang (trunk) - AARCH64 - BUG
- https://godbolt.org/z/6cY6ob5e6

#### Clang (trunk) - ARM - BUG
- https://godbolt.org/z/5YE3f5M3K

## Steps to reproduce the issues.

C code:
```
#include <stdint.h>
#include <stddef.h>

typedef struct {
  uint8_t arr[16];
  void (*show)(uint8_t arr[16]);
} CONTEXT;

static void xor16(uint8_t out[16], uint8_t a[16], uint8_t b[16]) {
  for (size_t i = 0; i < 16; i ++)
    out[i] = a[i] ^ b[i];
}

int function_that_is_incorrectly_compiled(CONTEXT *ctx) {
  volatile uint8_t block[16];

  xor16(ctx->arr, ctx->arr, block); // BUG. This code has no effect!!!

  ctx->show(ctx->arr);

  return 0;
}
```

The disassembly of the compiled code doesn't contain code, related to the "xor16(...)" function call:
```
function_that_is_incorrectly_compiled:
        push    {r11, lr}
        mov     r11, sp
        ldr     r1, [r0, #16]
        blx     r1
        mov     r0, #0
        pop     {r11, pc}
```

**Comment by DimitryAndric** [comment]
The function is simply inlined, and clang sees that it effectively does nothing. Try adding a `noinline` attribute, e.g.:

```c
__attribute__((__noinline__))
static void xor16(uint8_t out[16], uint8_t a[16], uint8_t b[16]) {
  for (size_t i = 0; i < 16; i ++)
    out[i] = a[i] ^ b[i];
}
```

then the xor16 function will become:

```asm
        .p2align        2                               // -- Begin function xor16
        .type   xor16,@function
xor16:                                  // @xor16
        .cfi_startproc
// %bb.0:
        ldrb    w8, [x1]
        ldrb    w9, [x2]
        eor     w8, w9, w8
        strb    w8, [x0]
        ldrb    w8, [x1, #1]
        ldrb    w9, [x2, #1]
        eor     w8, w9, w8
        strb    w8, [x0, #1]
        ldrb    w8, [x1, #2]
        ldrb    w9, [x2, #2]
        eor     w8, w9, w8
        strb    w8, [x0, #2]
        ldrb    w8, [x1, #3]
        ldrb    w9, [x2, #3]
        eor     w8, w9, w8
        strb    w8, [x0, #3]
        ldrb    w8, [x1, #4]
        ldrb    w9, [x2, #4]
        eor     w8, w9, w8
        strb    w8, [x0, #4]
        ldrb    w8, [x1, #5]
        ldrb    w9, [x2, #5]
        eor     w8, w9, w8
        strb    w8, [x0, #5]
        ldrb    w8, [x1, #6]
        ldrb    w9, [x2, #6]
        eor     w8, w9, w8
        strb    w8, [x0, #6]
        ldrb    w8, [x1, #7]
        ldrb    w9, [x2, #7]
        eor     w8, w9, w8
        strb    w8, [x0, #7]
        ldrb    w8, [x1, #8]
        ldrb    w9, [x2, #8]
        eor     w8, w9, w8
        strb    w8, [x0, #8]
        ldrb    w8, [x1, #9]
        ldrb    w9, [x2, #9]
        eor     w8, w9, w8
        strb    w8, [x0, #9]
        ldrb    w8, [x1, #10]
        ldrb    w9, [x2, #10]
        eor     w8, w9, w8
        strb    w8, [x0, #10]
        ldrb    w8, [x1, #11]
        ldrb    w9, [x2, #11]
        eor     w8, w9, w8
        strb    w8, [x0, #11]
        ldrb    w8, [x1, #12]
        ldrb    w9, [x2, #12]
        eor     w8, w9, w8
        strb    w8, [x0, #12]
        ldrb    w8, [x1, #13]
        ldrb    w9, [x2, #13]
        eor     w8, w9, w8
        strb    w8, [x0, #13]
        ldrb    w8, [x1, #14]
        ldrb    w9, [x2, #14]
        eor     w8, w9, w8
        strb    w8, [x0, #14]
        ldrb    w8, [x1, #15]
        ldrb    w9, [x2, #15]
        eor     w8, w9, w8
        strb    w8, [x0, #15]
        ret
.Lfunc_end1:
        .size   xor16, .Lfunc_end1-xor16
        .cfi_endproc
```

Also, what are you trying to accomplish with the `volatile` specifier? It should not be required.

**Comment by DimitryAndric** [comment]
Oh actually, the `volatile uint8_t block[16];` variable is uninitialized. So this is undefined behavior. :)  Try memsetting it, or passing in some defined value from outside the function.

**Comment by P1119r1m** [comment]
@DimitryAndric

But this function isn't doing nothing.
It is XORing some input data.
The same problem happens when assigning some data to `uint8_t block[16]`.

**Comment by DimitryAndric** [comment]
As I said, the function is simply inlined, and this is why you think it is is "disappearing", while it is not the case. If you want to prevent inlining, add an attribute to do so.

**Comment by P1119r1m** [comment]
@DimitryAndric 

> Oh actually, the volatile uint8_t block[16]; variable is uninitialized. So this is undefined behavior. :) Try memsetting it, or passing in some defined value from outside the function.

Please check complete (non-reduced) example of the same problem:
- https://godbolt.org/z/q5v9v9WE9

**Comment by P1119r1m** [comment]
@DimitryAndric Thank you for re -opening this issue.

**Comment by DimitryAndric** [comment]
If you are really convinced this is a compiler bug (I am not), then you should reduce it further. As far as I am concerned, you are seeing fairly standard inlining behavior.

**Comment by P1119r1m** [comment]
But inlining shouldn't remove the code.

The idea of this code is following:
- 1. XOR each value from `ctx->arr` with some values from another `block` array
- 2. Show result by calling function pointer `ctx->show(ctx->arr)`

If you're correct and compiler simply inlining the code from the step "1" then why we don't have it in final binary result?

**Comment by DimitryAndric** [comment]
I think the problem might be related to `-Os`. With `-O1` or `-O2` I don't see the behavior. E.g. targeting x86_64 (doesn't matter in this case) with clang 18 and `-O2` I get this inner loop:

```asm
# %bb.1:
        cmpl    $0, 292(%rbx)
        je      .LBB0_3
.LBB0_2:
        leaq    256(%rbx), %rdi
        movq    %rbx, %rsi
        callq   *%r14
.LBB0_3:
        movq    272(%rbx), %rax
        shlq    $3, %rax
        bswapq  %rax
        movq    %rax, -32(%rbp)
        movq    280(%rbx), %rax
        shlq    $3, %rax
        bswapq  %rax
        movq    %rax, -24(%rbp)
        leaq    256(%rbx), %rdi
        movq    $-4, %rax
        .p2align        4, 0x90
.LBB0_4:                                # =>This Inner Loop Header: Depth=1
        movl    -28(%rbp,%rax), %ecx
        xorl    %ecx, 260(%rbx,%rax)
        addq    $4, %rax
        cmpq    $12, %rax
        jb      .LBB0_4
# %bb.5:
        movq    %rbx, %rsi
        callq   *%r14
```

with `-Os` it's indeed not emitting anything there:

```asm
# %bb.1:
        cmpl    $0, 292(%rbx)
        je      .LBB0_3
.LBB0_2:
        leaq    256(%rbx), %rdi
        movq    %rbx, %rsi
        callq   *%r14
.LBB0_3:
```

Bisecting currently shows `llvmorg-16-init-10912-g`4105794e661 working, and `llvmorg-16-init-10932-g`0ccc45f76b4 doesn't. May take some time to pinpoint the exact change.

**Comment by P1119r1m** [comment]
Currently the minimum (valid) example code:
- https://godbolt.org/z/xdr7v346e

**Comment by nikic** [comment]
Your code violates strict aliasing, because you are accessing the same memory both through uint64_t and uint32_t. Use ` -fno-strict-aliasing` to opt out of C strict aliasing requirements.

**Comment by P1119r1m** [comment]
@nikic
Thank you for your comment!
You're right.
However "strict aliasing violation" is present only in revised example code:
- https://godbolt.org/z/xdr7v346e

There is no "strict aliasing violation" in initial, reduced, example code:
- https://godbolt.org/z/5YE3f5M3K

**Comment by nikic** [comment]
Your initial example doesn't have a strict aliasing violation, but reads uninitialized memory instead.

**Comment by P1119r1m** [comment]
> Your initial example doesn't have a strict aliasing violation, but reads uninitialized memory instead.

It's a pity that the compiler simply removes code with undefined behavior without notifying the user.
IMHO, it would be more user-friendly if the compiler provided some information or a warning to the user.
