### ISSUE TITLE
[libc++] Identifier `ptr` is unconditionally used although it is not reserved by the standard library until C++17

### ISSUE THREAD

**Issue by frederick-vs-ja** [llvm/llvm-project#96071]
This program is supposed be valid until C++17, because the identifier `ptr` is initially introduced into the C++ standard library alongwith `to_chars_result` and `from_chars_result`.

```C++
#define ptr delete
#include <vector>
int main() {}
```

However, it doesn't compile with libc++ in older modes ([Godbolt link](https://godbolt.org/z/aKhKEhKK1)), because the internal helper type `__allocation_result` is used in modes older than C++23 and unconditionally holds a member of name `ptr`. (`count` is OK as `std::count` has been present since C++98.)
https://github.com/llvm/llvm-project/blob/5574a5894fdb7f9a46a4fbe6c8970fd39890dc9b/libcxx/include/__memory/allocate_at_least.h#L31-L35

This seems already discussed in https://reviews.llvm.org/D122877#inline-1179553 but the complete history is no longer accessible...

CC @ldionne @philnik777

**Comment by philnik777** [comment]
Yes, we decided that we don't care. `ptr` is used a _lot_: https://sourcegraph.com/search?q=context:global+ptr%5B%5Cs.-%5D+count:all&patternType=regexp&case=yes&sm=0&filters=%5B%5B%22lang%22%2C%22C%2B%2B%22%2C%22lang%3Ac%2B%2B%22%5D%5D (as a reference, the number of `std::`s: https://sourcegraph.com/search?q=context:global+std::+count:all&patternType=regexp&case=yes&sm=0&filters=%5B%5B%22lang%22%2C%22C%2B%2B%22%2C%22lang%3Ac%2B%2B%22%5D%5D)
