### ISSUE TITLE
Clang 18 crashes with codes involving lambdas capturing 'this'

### ISSUE THREAD

**Issue by nommse** [llvm/llvm-project#96077]
Hello,

I stumbled over a `clangd` crash when analyzing our code base with `clang-tidy`. Trying to break this down resulted in the following code snippet:

```
#include <functional>

struct S
{
  std::function<void()> func;
};

struct F
{
  std::function<S(int)> f = [this] (auto) { return S{.func = [this]() {}}; };
};

int main() {}

```
[clangd-18.1.6-crash.log](https://github.com/user-attachments/files/15902010/clangd-18.1.6-crash.log)
[clangd-19.0.0-crash.log](https://github.com/user-attachments/files/15902011/clangd-19.0.0-crash.log)

The crash can be reproduced with versions 18.1.3, 18.1.6 and 19.0.0 when invoking `clangd` like so:

`clangd --clang-tidy --check=test.cpp --log=verbose`

If the function `F::f` is defined in one of the following ways, `clangd` does not crash:

- `std::function<S(int)> f = [this] (int)       { return S{.func = [this]() {}}; };`
- `std::function<S(int)> f = [this] (auto) -> S { return S{.func = [this]() {}}; };`
- `std::function<S(int)> f = []     (auto)      { return S{.func = []()     {}}; };`

Thank you and best regards,
nommse

PS: the crash does not occur with clangd version 15.0.6.

**Comment by zyn0217** [comment]
https://gcc.godbolt.org/z/Gfvzdhzvh

@Sirraide Did you see/fix anything very similar recently?

**Comment by zyn0217** [comment]
(This is not specific to clangd so I removed the clangd label.)

**Comment by Sirraide** [comment]
> @Sirraide Did you see/fix anything very similar recently?

Most of my lambda-related changes have been wrt lambdas with an explicit object parameter. I don’t think there’s anything here that would be affected by a change that I’ve made, but I may be forgetting something. Either way, it seems to be fixed on trunk.

**Comment by Sirraide** [comment]
> The crash can be reproduced with versions 18.1.3, 18.1.6 and 19.0.0:

@nommse Did you test this with a recent version of 19? Because it seems odd to me that it would still be broken if Clang 18 asserts on this but Clang 19 doesn’t, unless there’s *another* problem here somewhere...

**Comment by zyn0217** [comment]
OK, so it's hard to tell which patch regarding the lambda has fixed this crash without reducing it further...

**Comment by Sirraide** [comment]
> `clangd --clang-tidy --check=test.cpp --log=verbose`

Yeah, running this exact command on the code here with a version of `clangd` trunk that I built earlier today, everything works just fine.

**Comment by nommse** [comment]
@Sirraide I have tested this with version 19.0.0 (which comes with the Clion IDE). For testing this with a newer version I would have to build `clangd` myself, I guess. Unfortunately I cannot do this right now. But it sounds good - the issue seems to already have been fixed on the trunk.

**Comment by Sirraide** [comment]
> I have tested this with version 19.0.0 (which comes with the Clion IDE)

I see, yeah, they’re likely still on an older commit then.

**Comment by Sirraide** [comment]
Given that we’re already very late in the release cycle for 18 and considering that it’d take some digging to figure out what actually fixed this, I don’t think we’ll be backporting a fix for this to 18, so I’m closing this considering that it’s already been fixed on trunk.
