### ISSUE TITLE
[clang 17] wrong code at -O2/O3 with restrict-qualified pointers

### ISSUE THREAD

**Issue by tangyixuan01** [llvm/llvm-project#96070]
I think it is legal to call f(a+1,a) with restrict, and it replaces each element with a copy of the prior one. It seems that Clang-17 outputs wrong code with optimizations -O2/O3.

The behavior can be verified on Godbolt: https://godbolt.org/z/jnYMvrfr7

```c
int printf(const char *, ...);
void g(int*__restrict a, int* b)
{
  *a = *b;
}

void f(int* c,int* d)
{
  for(int i=0;i<99;++i)
    g(c+i,d+i);
}

int main()
{
  int a[100];
  for (int i = 0; i < 100; ++i)
    a[i] = i+1;
  f(a+1, a);
  for (int i = 0; i < 100; ++i)
    printf("%d\n",a[i]);
  return 0;
}
```

**Comment by nikic** [comment]
Your example does not reproduce on Clang 18. Do you have a case where this is miscompiles on current Clang?

**Comment by tangyixuan01** [comment]
> Your example does not reproduce on Clang 18. Do you have a case where this is miscompiles on current Clang?

Thanks for your reply. This bug can be reproduced on Clang 17 and before.

**Comment by nikic** [comment]
Clang 17 is no longer support by the LLVM project. If this does not reproduce on newer versions, I'll go ahead and close the issue.
