### ISSUE TITLE
Add support for stdLib function checks for the Baggy Bounds runtime.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#9613]
|  |  |
| --- | --- |
| Bugzilla Link | [9241](https://llvm.org/bz9241) |
| Version | unspecified |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

**Comment by arsenm** [comment]
Subject only issue isn't really enough description for a feature request. I don't know what baggy bounds is, but it looks like it isn't something that's been touched recently
