### ISSUE TITLE
release_file_streams_for_task and __abort on clang 2.9 (trunk 124557)

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#9635]
|  |  |
| --- | --- |
| Bugzilla Link | [9263](https://llvm.org/bz9263) |
| Version | trunk |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Hello,

This objective C line (Xcode 3.2.5 on MacOsxx 10.6.6) :

if (!(file = fopen([aPath UTF8String],"wb"))) STAssertEquals( 0, 1, @"Cannot write generated test file, probably autorization problem");

( STAssertEquals is in SenTestCase.h )

Cause this one on crash :

3   libSystem.B.dylib             	0x00007fff88e6fc75 __abort + 113
4   libSystem.B.dylib             	0x00007fff88e542cc release_file_streams_for_task + 0

Its works fine on gcc4.2, 4.5.2 and on default macosx clang (Apple clang version 1.6 (tags/Apple/clang-70)), but not on lastest i update every day.

Thank you

--
Stephane

**Comment by arsenm** [comment]
No full reproducer supplied
