### ISSUE TITLE
Does llvm support cross compile QNX os?

### ISSUE THREAD

**Issue by chengven027** [llvm/llvm-project#96397]
Hello everyone:
Does llvm support cross compile QNX 7.1.0 os？ I got a error like this: 
`llvm/include/llvm/ADT/bit.h:52:10: fatal error: machine/endian.h: 
No such file or directory#include <machine/endian.h>`
compilation terminated.  the command is : 
`cmake-DLLVM_BUILD_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Debug -DLLVM_ENABLE_ SERTIONS=On -G "Unix Makefiles"../llvm;  make -j4`
should I do some other config?

**Comment by MaxEW707** [comment]
The answer to this is most likely no.

I don't fully understand if you are referring to building clang on QNX or using clang to output QNX binaries.
For both of these questions the answer is almost certainly no.

QNX only supports the compiler shipped with the SDP which is qcc, their wrapper around their GCC.
Clang/LLVM is not actively built on qcc.

If you have access to the SDP you can probably get clang/llvm to output binaries how QNX expects. Follow the config that is used for their GCC. However you applications will almost certainly not be safety certified if you do this which is kinda the point of QNX overall outside of being a hard real-time OS.

If you really want clang on QNX I suggest going to your QNX rep and/or the QNX forums which if you have a QNX license you have access to.

**Comment by chengven027** [comment]
ok, thanks for your answer.
