### ISSUE TITLE
Please give a configuration parameter in the new version. After setting it to true, you can add a space between the /**/ method comment and the comment content.

### ISSUE THREAD

**Issue by 202244060124** [llvm/llvm-project#96419]
Please give a configuration parameter in the new version. After setting it to true, you can add a space between the /**/ method comment and the comment content.
Example：
![image](https://github.com/llvm/llvm-project/assets/133141655/e3049bdf-3835-4e2b-a79c-29f479432166)
![image](https://github.com/llvm/llvm-project/assets/133141655/87505a22-a7c9-4b5d-b7c8-967c168fda31)

**Comment by rymiel** [comment]
You do not need to open another issue, https://github.com/llvm/llvm-project/issues/94231 is fine
