### ISSUE TITLE
Strange behaviour with lambdas returned from module exported member function

### ISSUE THREAD

**Issue by kamrann** [llvm/llvm-project#96428]
The following code leads to some somewhat unintuitive error messages, and has some behaviour differences in comparison to gcc.
```c++
export module mod;

export struct s
{
    /*inline*/ auto make_lambda() const
    {
        return [/*this*/]{};
    }
};
```
```c++
import mod;

int main ()
{
    auto const s1 = s{};
    auto const f = s1.make_lambda();
    auto const g = f; // error here
}
```

As above, the code will fail on both: however clang will report an unavailable copy constructor whereas gcc compiles but raises a multiple definition linker error. With a captured `this`, gcc is happy but clang continues to give the same compilation error. Making the member function `inline` fixes the problem on both.

I'm not certain what the correct behaviour should be here, but either one of clang and gcc is wrong, and even if clang is correct it seems the error messages could be better.

Compiler explorer repro: https://godbolt.org/z/Knfjf3aMe.

**Comment by ChuanqiXu9** [comment]
This looks duplicated with https://github.com/llvm/llvm-project/issues/59513
