### ISSUE TITLE
CTAD for alias template with deduction guide fails "argument deduction only allowed for class templates"

### ISSUE THREAD

**Issue by GuzevArtem** [llvm/llvm-project#96441]
Inconsistent behaviour with GCC and MSVC.

https://godbolt.org/z/oxo1qh8sa

**Comment by antangelo** [comment]
Support for CTAD for alias templates is not available in clang 18. The provided example matches MSVC/gcc on trunk: https://godbolt.org/z/188Kv7876

**Comment by GuzevArtem** [comment]
as well as in trunk.
https://godbolt.org/z/jTvjPcqvh
