### ISSUE TITLE
[Clang] Warning not displayed when using `-include`

### ISSUE THREAD

**Issue by VitorRamos** [llvm/llvm-project#96476]
## Description

While compiling a c++ source file with clang++ using the `-include` flag to include a header file, some warnings are not shown.

## Steps to Reproduce

1. header file `assert.h`:
    ```c++
    #pragma once

    #define CUSTOM_MACRO(expr) (void)(!!(expr))
    ```

2. cpp file `main.cpp` :
    ```c++
    int main()
    {
        int x = 0;
        CUSTOM_MACRO(x > 0 || x <= 0);
    }
    ```

3. Compile the file with the following command:
    ```sh
    clang++ -Wall -Wextra -include assert.h -c main.cpp
    ```
4. Observe that no warning is outputted.

5. Compile the file again with the additional `-save-temps=obj` flag:
    ```sh
    clang++ -Wall -Wextra -include assert.h -c main.cpp -save-temps=obj
    ```
6. Observe that the following warning is generated:
    ```log
    main.cpp:5:21: warning: overlapping comparisons always evaluate to true [-Wtautological-overlap-compare]
        (void)(!!(x > 0 || x <= 0));
                  ~~~~~~^~~~~~~~~
    1 warning generated.
    ```

## Expected Behavior
The warning indicating that the comparison always evaluates to true should be displayed regardless of the use of the `-save-temps=obj` flag.

## Additional Information
- **Compiler Version:** Clang 16.0.0
- **Operating System:** Ubuntu 22.04

**Comment by VitorRamos** [comment]
Apparently we don't even need the -include, this also has the same behavior 

```
#define CUSTOM_MACRO(s) if (s) {} else 0

int main()
{
    CUSTOM_MACRO(false);
}
```
`clang++ -Wall -Wextra -c main.cpp`
Nothing
`clang++ -Wall -Wextra -c main.cpp -save-temps=obj`
```
main.cpp:5:24: warning: expression result unused [-Wunused-value]
    if (false) {} else 0;
                       ^
1 warning generated.
```

**Comment by dwblaikie** [comment]
Likely intended behavior - clang suppresses certain warnings in the context of macros due to common idioms & the possibility that a piece of code doesn't make sense if written literally, but might make sense if it was composed out of parts due to some macro expansion.

**Comment by dwblaikie** [comment]
Sorry, wrong closure.
