### ISSUE TITLE
Bug in InstrProfilingPlatformOther.c

### ISSUE THREAD

**Issue by bbarwik** [llvm/llvm-project#96536]
In InstrProfilingPlatformOther.c, there are the following functions:
```cpp
COMPILER_RT_VISIBILITY
char *__llvm_profile_begin_bitmap(void) { return BitmapFirst; }
COMPILER_RT_VISIBILITY
char *__llvm_profile_end_bitmap(void) { return BitmapLast; }
```

However, `BitmapFirst` and `BitmapLast` are nowhere defined, causing compiler error in my case. Pinging @evodius96 because it seems he introduced this code, I am not experienced enough to fix it.

**Comment by evodius96** [comment]
Thanks!  It looks like this was overlooked because this file isn't build for Apple, Linux, and Windows.   

To fix the compile error, you have to add the declarations to the top of the file beneath the corresponding ones for `counters`.

```
--- a/compiler-rt/lib/profile/InstrProfilingPlatformOther.c
+++ b/compiler-rt/lib/profile/InstrProfilingPlatformOther.c
@@ -26,6 +26,8 @@ static const char *VNamesFirst = NULL;
 static const char *VNamesLast = NULL;
 static char *CountersFirst = NULL;
 static char *CountersLast = NULL;
+static char *BitmapFirst = NULL;
+static char *BitmapLast = NULL;
 static uint32_t *OrderFileFirst = NULL;
 
 static const void *getMinAddr(const void *A1, const void *A2) {
```


Can you try that fix out?  You can go ahead and create a PR for it, or I can.

Thanks!

**Comment by bbarwik** [comment]
> Thanks! It looks like this was overlooked because this file isn't build for Apple, Linux, and Windows.
> 
> To fix the compile error, you have to add the declarations to the top of the file beneath the corresponding ones for `counters`.
> 
> ```
> --- a/compiler-rt/lib/profile/InstrProfilingPlatformOther.c
> +++ b/compiler-rt/lib/profile/InstrProfilingPlatformOther.c
> @@ -26,6 +26,8 @@ static const char *VNamesFirst = NULL;
>  static const char *VNamesLast = NULL;
>  static char *CountersFirst = NULL;
>  static char *CountersLast = NULL;
> +static char *BitmapFirst = NULL;
> +static char *BitmapLast = NULL;
>  static uint32_t *OrderFileFirst = NULL;
>  
>  static const void *getMinAddr(const void *A1, const void *A2) {
> ```
> 
> Can you try that fix out? You can go ahead and create a PR for it, or I can.
> 
> Thanks!

Thanks for quick response! I just wasn't sure if that was enough. Created PR - https://github.com/llvm/llvm-project/pull/96539
