### ISSUE TITLE
libc: enable -Wunused

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#96689]
via https://github.com/llvm/llvm-project/pull/96591#discussion_r1653050200 it seems like we don't have `-Wunused` set.

We should enable it and clean up the instances it finds.

We should append that to `compile_options` in libc/cmake/modules/LLVMLibCObjectRules.cmake.

**Comment by elchukc** [comment]
This issue should be closed, as concluded in [this discussion](https://github.com/llvm/llvm-project/pull/96949#issuecomment-2338802855).
