### ISSUE TITLE
[RISCV] MachineCopyPropagationPass may cause link time error

### ISSUE THREAD

**Issue by Yunzezhu94** [llvm/llvm-project#96727]
In RISCV target pipeline MachineCopyPropagationPass is placed in addPreEmitPass and after BranchRelaxationPass and RISCVMakeCompressibleOptPass now. I've encountered a unusual case that contains a R_RISCV_BRANCH at maximum jump distance with some Compressed instructions, while MachineCopyPropagationPass breaks generates of some Compressed instructions and make jump distance exceeds maximum jump distance of R_RISCV_BRANCH, and linker reports relocation truncated to fit. It looks BranchRelaxationPass estimates jump distance with Compressed instructions successfully generated, and MachineCopyPropagationPass may make real jump distance differ from estimated jump distance.  I wonder if it is better to place MachineCopyPropagationPass earlier in addPreEmitPass prior to BranchRelaxationPass and RISCVMakeCompressibleOptPass, so that BranchRelaxationPass could correctly estimate jump distance of relocations.

**Comment by Yunzezhu94** [comment]
Gentle ping.

**Comment by topperc** [comment]
I think we should move the pass earlier. Have you tried this?

**Comment by Yunzezhu94** [comment]
> I think we should move the pass earlier. Have you tried this?

Yes. I tried to move MachineCopyPropagationPass before BranchRelaxationPass and it works on the case I met R_RISCV_BRANCH error before.

**Comment by topperc** [comment]
> > I think we should move the pass earlier. Have you tried this?
> 
> Yes. I tried to move MachineCopyPropagationPass before BranchRelaxationPass and it works on the case I met R_RISCV_BRANCH error before.

Can you post a PR?

**Comment by Yunzezhu94** [comment]
> > > I think we should move the pass earlier. Have you tried this?
> > 
> > 
> > Yes. I tried to move MachineCopyPropagationPass before BranchRelaxationPass and it works on the case I met R_RISCV_BRANCH error before.
> 
> Can you post a PR?

Sure.
