### ISSUE TITLE
Configuring incomplete, errors occurred!

### ISSUE THREAD

**Issue by dincerkilic** [llvm/llvm-project#96756]
Hello,

I am running the script below:
`/home/ubuntu/environments/my_env/bin/cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ ..`
However, I get an error as below:

> - Automatic GPU detection failed. Building for common architectures.
-- Autodetected CUDA architecture(s): 5.3;6.0;6.1;7.0;7.5;8.0;8.6;8.6+PTX
-- Found LIBOMPTARGET_DEP_CUDA_DRIVER: /usr/lib/x86_64-linux-gnu/libcuda.so
-- Could NOT find LIBOMPTARGET_DEP_VEO (missing: LIBOMPTARGET_DEP_VEO_LIBRARIES LIBOMPTARGET_DEP_VEOSINFO_LIBRARIES LIBOMPTARGET_DEP_VEO_INCLUDE_DIRS) 
-- LIBOMPTARGET: Building offloading runtime library libomptarget.
CMake Error at libomptarget/src/CMakeLists.txt:28 (add_library):
  add_library cannot create target "omptarget" because an imported target
  with the same name already exists.
  CMake Error at libomptarget/src/CMakeLists.txt:35 (target_compile_definitions):
  target_compile_definitions may only set INTERFACE properties on IMPORTED
  targets
  CMake Error at libomptarget/src/CMakeLists.txt:36 (target_link_libraries):
  Cannot specify link libraries for target "omptarget" which is not built by
  this project.
-- Configuring incomplete, errors occurred!

Do you have uggestions on how to solve it? 
Thank you!

**Comment by jhuber6** [comment]
Did you solve the issue? The CMake messages look ancient, we can only fix things in the current releases.
