### ISSUE TITLE
trunc nuw x to i1 as branch/select cond implies x

### ISSUE THREAD

**Issue by sftlbcn** [llvm/llvm-project#96765]
https://alive2.llvm.org/ce/z/grTNkc
```
----------------------------------------
define i32 @src(i32 %x, i32 %y) {
#0:
  %trunc = trunc nuw i32 %x to i1
  %ret = select i1 %trunc, i32 %x, i32 %y
  ret i32 %ret
}
=>
define i32 @tgt(i32 %x, i32 %y) {
#0:
  %trunc = trunc nuw i32 %x to i1
  %ret = select i1 %trunc, i32 1, i32 %y
  ret i32 %ret
}
Transformation seems to be correct!

```
```

----------------------------------------
declare void @f()

define i32 @src2(i32 %x, i32 %y) {
bb1:
  %cond = trunc nuw i32 %x to i1
  br i1 %cond, label %bb2, label %bb3

bb2:
  call void @f()
  br label %bb3

bb3:
  %ret = phi i32 [ %y, %bb2 ], [ %x, %bb1 ]
  ret i32 %ret
}
=>
declare void @f()

define i32 @tgt2(i32 %x, i32 %y) {
bb1:
  %cond = trunc nuw i32 %x to i1
  br i1 %cond, label %bb2, label %bb3

bb2:
  call void @f()
  br label %bb3

bb3:
  %ret = phi i32 [ %y, %bb2 ], [ 0, %bb1 ]
  ret i32 %ret
}
Transformation seems to be correct!

Summary:
  2 correct transformations
  0 incorrect transformations
  0 failed-to-prove transformations
  0 Alive2 errors
```

**Comment by v01dXYZ** [comment]
This missed optimisation is related to the semantics of `nuw/nsw` with `trunc`:

> If the nuw keyword is present, and any of the truncated bits are non-zero, the result is a [poison value](https://llvm.org/docs/LangRef.html#poisonvalues). If the nsw keyword is present, and any of the truncated bits are not the same as the top bit of the truncation result, the result is a [poison value](https://llvm.org/docs/LangRef.html#poisonvalues).

Essentially your code assume `%x` can ve only 0 or 1.

**Comment by dtcxzyw** [comment]
Confirmed that this pattern exists in some real-world code :)

**Comment by HendrikHuebner** [comment]
I'd like to work on this

**Comment by akshaykumars614** [comment]
@HendrikHuebner are you still working on this?

**Comment by HendrikHuebner** [comment]
Yes.

**Comment by HendrikHuebner** [comment]
Hi @dtcxzyw , I've had a look through InstCombineSelect, which I think looks like the best place to put this. I did not find any similar folds there so I think I will add a new "foldTruncNoUnsignedWrap" function (or something like that) which tries to find this pattern. I'm just a bit worried that this pattern is going to be very rare?

**Comment by dtcxzyw** [comment]
>  I'm just a bit worried that this pattern is going to be very rare?

See https://github.com/llvm/llvm-project/issues/96765. This pattern exists in gromacs/verilator/php/hyperscan/tokenizers-rs/...

**Comment by HendrikHuebner** [comment]
@c8ef I'm a bit busy right now. You can work on it if you want.
