### ISSUE TITLE
clang should prohibit creating complete objects with a protected constructor in a subclass

### ISSUE THREAD

**Issue by nico** [llvm/llvm-project#9680]
|  |  |
| --- | --- |
| Bugzilla Link | [9308](https://llvm.org/bz9308) |
| Version | trunk |
| OS | All |
| CC | @DougGregor,@tkremenek,@rjmccall,@RealLitb |

## Extended Description 
gcc rejects this, clang should too:
```c++
class A {
 protected:
  A(int a) {}
};
class B : public A {
  void f() {
    A a(32);
  }
};
```

**Comment by philnik777** [comment]
Fixed in Clang 3.1: https://godbolt.org/z/jqEY4P8Pd
