### ISSUE TITLE
MCContext: Rmove the `const char *BeginSymName` parameter from getXCOFFSection

### ISSUE THREAD

**Issue by MaskRay** [llvm/llvm-project#96810]
The `BeginSymName` parameter was designed for Mach-O, which uses the
`.subsections_via_symbols` mechanism. (I think it could be removed for better semantics, but I haven't analyzed thoroughly yet.)

`BeginSymName` got copied to other object file formats, but it doesn't play
well with section symbols (ELF, COFF).

* 13a79bbfe583e1d8cc85d241b580907260065eb8 removed `BeginSymbol` for ELF.
* #96459 removed `BeginSymbol` for COFF.

For better assembler semantics XCOFF should remove `const char *BeginSymName` parameter as well.
Instead, always define the section symbol.
Then, the definition of `DwarfAbbrevSection` and its friends in MCObjecFileInfo.cpp will not need
to provide `const char *BeginSymName`.

**Comment by MaskRay** [comment]
@chenzheng1030 @daltenty

**Comment by chenzheng1030** [comment]
Do you want to remove the BeginSymbol parameter or do you want to remove the BeginSymbol member in the base class? X86 seems just remove the parametet, it still sets the BeginSymbol member in the base class?

**Comment by MaskRay** [comment]
> Do you want to remove the BeginSymbol parameter or do you want to remove the BeginSymbol member in the base class? X86 seems just remove the parametet, it still sets the BeginSymbol member in the base class?

Thanks for the reply. You might be the best to implement this? :)

I think the `BeginSymName` parameter should be removed from all `get*Section`.
They are cargo culting programming for Mach-O, which uses `BeginSymName` as a hack.

The COFF patch might be a good reference on removing `BeginSymName`.

**Comment by chenzheng1030** [comment]
Will check. Removing the parameter should be quite simple as the parameter is just used for debug sections on XCOFF. But reusing the section symbol for debug section needs more investigation. On AIX, the section symbol has a qualname which is not same with the normal label symbols.
