### ISSUE TITLE
[X86] llvm.experimental.constrained.fptrunc ignores rounding for fp32 to fp16 conversion

### ISSUE THREAD

**Issue by ienkovich** [llvm/llvm-project#96815]
**Problem**
Codegen for `llvm.experimental.constrained.fptrunc` intrinsic doesn't respect the requested rounding mode. Using different rounding modes in this intrinsic doesn't affect the resulting code. 

**Details**
Here is a test IR to convert a vector with zero rounding:
```
; ModuleID = 'LLVMDialectModule'
source_filename = "LLVMDialectModule"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn
define void @type_convert(ptr %0, ptr %1) local_unnamed_addr #0 {
  %3 = load <16 x float>, ptr %0, align 4
  %4 = tail call <16 x half> @llvm.experimental.constrained.fptrunc.v16f16.v16f32(<16 x float> %3, metadata !"round.towardzero", metadata !"fpexcept.ignore") #2
  store <16 x half> %4, ptr %1, align 2
  ret void
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)
declare <16 x half> @llvm.experimental.constrained.fptrunc.v16f16.v16f32(<16 x float>, metadata, metadata) #1

attributes #0 = { mustprogress nofree norecurse nosync nounwind willreturn }
attributes #1 = { mustprogress nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite) }
attributes #2 = { strictfp }
```
A command used to compile:
```
llc test.ll -mcpu=sapphirerapids
```
The produced result uses `vcvtps2phx` instruction to make a conversion:
```
type_convert:
        vcvtps2phx      (%rdi), %ymm0
        vmovups %ymm0, (%rsi)
        vzeroupper
        retq
```
This code doesn't provide the requested rounding and produces incorrect results. I'd expect the resulting ASM to use explicit rounding, e.g:
```
        vmovups (%rdi), %zmm0
        vcvtps2ph       $3, %zmm0, (%rsi)
```

**Comment by phoebewang** [comment]
The rounding mode in `llvm.experimental.constrained.fptrunc` is a hint to compiler optimizer, which is used to block scheduling across different rounding mode.
You need to use target specific intrinsic like `_mm256_cvtps_ph` to control the rounding mode in codegen.

**Comment by ienkovich** [comment]
@phoebewang The documentation of constrained fp instrinsics specifically says that these are used to support non-default rounding. All operations in the function are constrained. Adding `fpstrict` to the function attributes also doesn't change the behavior. What would be a proper LLVM IR to convert fp vectors with guaranteed rounding then?

**Comment by phoebewang** [comment]
> @phoebewang The documentation of constrained fp instrinsics specifically says that these are used to support non-default rounding. All operations in the function are constrained. Adding `fpstrict` to the function attributes also doesn't change the behavior. What would be a proper LLVM IR to convert fp vectors with guaranteed rounding then?

That's correct. There's no general LLVM IR to control rounding of each individual operation. You should use `llvm.set.rounding` or `llvm.set.fpenv` to set the environment rounding for them. The constrained fp instrinsics are used to make sure compiler optimizer won't do anything violate it, because the rounding is always assumed to the default one without constrained fp.
