### ISSUE TITLE
Use LLD by default in Clang, without the flag `-fuse-ld=lld`

### ISSUE THREAD

**Issue by 3119369616** [llvm/llvm-project#96897]
On Windows, Clang & LLD try to invoke Microsoft's linker `link.exe` by default. If there isn't a `link.exe` on my system, LLD won't work. To use LLD itself, I must manually enable the flag `-fuse-ld=lld` in Clang.

Is it possible to use LLD itself by default without enabling this flag?

**Comment by MaskRay** [comment]
https://clang.llvm.org/docs/UsersManual.html#configuration-files https://blogs.gentoo.org/mgorny/2022/10/07/clang-in-gentoo-now-sets-default-runtimes-via-config-file/ 
You can place `$triple.cfg`, which specifies `-fuse-ld=lld`, beside `clang` executable.

There is also a CMake variable `CLANG_DEFAULT_LINKER`, but the trend is to discourage such CMake customizations in favor of configuration files.
