### ISSUE TITLE
[libcxx][compiler-rt] using std::format/std::print should not be a "modernize" thing.

### ISSUE THREAD

**Issue by trcrsired** [llvm/llvm-project#96938]
https://github.com/llvm/llvm-project/commit/83f875dc94d7a5cc9b2da32e2a7b1502e3b0640c
Could any libcxx dev tell me how this is even a "modernize" when using std::format/std::print slows down the program and bloats binary size? 
![image](https://github.com/llvm/llvm-project/assets/100043421/526b480d-a40e-455c-90cb-560ed429dddb)
![image](https://github.com/llvm/llvm-project/assets/100043421/3d7d47d9-19a0-4397-977f-1e0f08ed1c6b)
@mikecrowe

**Comment by mikecrowe** [comment]
Would you be willing to share the source code for your test programs?

**Comment by philnik777** [comment]
Closing, since there is nothing actionable.
