### ISSUE TITLE
memcpy() missing from clang's intrin.h on Windows

### ISSUE THREAD

**Issue by a-p-jo** [llvm/llvm-project#96941]
To reproduce this issue:
Try to compile the below code on clang on windows (for example, if installed through visual studio, run `clang <filename>.c` in the Developer Command Prompt):

```c
#include <intrin.h>

int main(void)
{
        memcpy((void *)0xdeadbeef, (void *)(0xdeadbeef+1), 1);
}
```

The following error message will be printed:
```c
error: call to undeclared library function 'memcpy' with type 'void *(void *, const void *, unsigned int)'; ISO C99 and later do not support
      implicit function declarations [-Wimplicit-function-declaration]
      |         memcpy((void *)0xdeadbeef, (void *)(0xdeadbeef+1), 1);
      |         ^
note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
```
Refer [microsoft documentation](https://learn.microsoft.com/en-us/cpp/intrinsics/intrinsics-available-on-all-architectures): `mempcy` is listed under a table titled "_The following UCRT functions have intrinsic forms on all architectures:_".  So, the symbol should be defined in `intrin.h`.

The code compiles with gcc (minGW) as well as msvc (visual studio built tools). 

Upon some ctrl+click-ing to and ctrl+f-ing through the `intrin.h` (and its `#include`s) that `clangd` uses in visual studio code on windows, it appears that the llvm/clang version of this header file does not export the symbol `memcpy`, when it should.

**Comment by a-p-jo** [comment]
I noticed this code when trying to produce a `portable_freestanding_memcpy.h`, like so:
```c
#ifndef PORTABLE_FREESTANDING_MEMCPY_H
#define PORTABLE_FREESTANDING_MEMCPY_H

#ifdef _MSC_VER
/* https://learn.microsoft.com/en-us/cpp/intrinsics/intrinsics-available-on-all-architectures
 * MSVC compiler intrinsics include memcpy()
 */
#include <intrin.h>

#elif defined(__GNUC__)
// https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html
#define memcpy __builtin_memcpy

#else // roll our own
#include <stddef.h> // size_t
static inline void *memcpy(
        void *restrict const dst,
        const void *restrict const src, 
        const size_t nbytes
)
{
        for (size_t i = 0; i < nbytes; i++)
                ((unsigned char *)dst)[i] = ((const unsigned char *)src)[i];
        return dst;
}
#endif

#endif
```

The above *should* work, but **cannot** work with clang on windows, because it defines `_MSC_VER`, but fails to export `memcpy` in its `intrin.h`.

**Comment by MaxEW707** [comment]
@a-p-jo What version of clang does this occur on? I don't see it reported in your bug report here but I am assuming you mean "clang version 17.0.3" shipped with VS2022 17.10.x since you mentioned, "for example, if installed through visual studio, run clang <filename>.c in the Developer Command Prompt".

**Comment by MaxEW707** [comment]
```
#include <intrin.h>

char buf[2];

int main(void)
{
    memcpy(&buf[0], &buf[1], 1);
}
```

The above does not build with MSVC 1940. You get, "error C3861: 'memcpy': identifier not found". `memcpy` is not included from `intrin.h` after digging through the header and its dependencies.
After refreshing my memory and as cited in, https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/memcpy-wmemcpy?view=msvc-170, `memcpy` is available in <memory.h> or <string.h>. <intrin.h> is intended for msvc's concept of compiler builtins, not c lib functions that it may treat as intrinsics with known behaviour.

In MSVC 1940 `memcpy` is defined inside `vcruntime_string.h`.

Both `string.h` and `memory.h` include `<corecrt_memory.h>` which ultimately includes `vcruntime_string.h` to get the decl of `memcpy`.

`vcruntime` headers are apart of your MSVC installation and differ between every MSVC version.
The `libc` headers and `corecrt_memory.h` are apart of UCRT and differ between Windows SDK versions.

I tested against MSVC 1940 and Windows SDK 10.0.22621.0.
If you can build by just including `intrin.h` then we need the MSVC and Windows SDK version to see what the headers looked like at that point in time.

Eitherway you would be relying on a transitive include and only `memory.h` and `string.h` are guaranteed to include the declaration for `memcpy`.

**Comment by a-p-jo** [comment]
You're right, @MaxEW707. I can close this bug.


```c
// tst.c
#include <intrin.h>

char buf[2];

int main(void)
{
    memcpy(&buf[0], &buf[1], 1);
}
```

The below is the output for `cl tst.c /Wall /std:c11` in the Developer Command Prompt:
```
Microsoft (R) C/C++ Optimizing Compiler Version 19.40.33811 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

tst.c
tst.c(7): warning C4013: 'memcpy' undefined; assuming extern returning int
Microsoft (R) Incremental Linker Version 14.40.33811.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:tst.exe
tst.obj
```

It turns out clang was doing the better job after all by not _silently_ assuming an undeclared function was `extern int ()`.

**Comment by a-p-jo** [comment]
One question I do have is: how can I make `__builtin_memcpy()` available on clang when its target is set to `i686-pc-windows-msvc`?

**Comment by MaxEW707** [comment]
> One question I do have is: how can I make __builtin_memcpy() available on clang when its target is set to i686-pc-windows-msvc?

Works for me on clang 18. https://godbolt.org/z/WEWqxEcro

Is there a specific version of clang where `__builtin_memcpy` isn't available on 32-bit windows msvc target?
What version of clang are you using to test this?

**Comment by a-p-jo** [comment]
@MaxEW707 No, you're right, it can. I just forgot to test separately for `__clang__` outside of testing for `__GNUC__` and `_MSC_VER`.
