### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by vskdtc** [llvm/llvm-project#96978]
from concrete import fhe

def max_two_numbers(a, b):
    return (a + b + abs(a - b)) // 2

def max_in_list(numbers):
    max_value = numbers[0]
    for num in numbers[1:]:
        max_value = max_two_numbers(max_value, num)
    return max_value

numbers = [3, 1, 4, 1, 5, 9, 2]
compiler = fhe.Compiler(max_in_list, {"numbers": "encrypted"})
inputset = [[numbers]]
circuit = compiler.compile(inputset)
encrypted_inputs = circuit.encrypt(numbers)
encrypted_result = circuit.run(encrypted_inputs)
result = circuit.decrypt(encrypted_result)

print("Maximum value in the list:", result)

-------

Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):

0  _mlir.cpython-311-darwin.so             0x000000010ab3dbd7 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 39
1  _mlir.cpython-311-darwin.so             0x000000010ab3ca06 llvm::sys::RunSignalHandlers() + 198
2  _mlir.cpython-311-darwin.so             0x000000010ab3e2b0 llvm::sys::PrintStackTraceOnErrorSignal(llvm::StringRef, bool) + 848
3  libsystem_platform.dylib                0x00007ff8145475ed _sigtramp + 29
4  libsystem_platform.dylib                0x0000000000000008 _sigtramp + 18446603370239855160
5  libConcretelangBindingsPythonCAPI.dylib 0x00000001103cd979 mlir::SymbolTable::getSymbolName(mlir::Operation*) + 25
6  _concretelang.cpython-311-darwin.so     0x000000010bb6b163 mlir::concretelang::createTFHECircuitSolutionParametrizationPass(std::__1::optional<concrete_optimizer::dag::CircuitSolution>) + 53779
7  _concretelang.cpython-311-darwin.so     0x000000010bb6aab7 mlir::concretelang::createTFHECircuitSolutionParametrizationPass(std::__1::optional<concrete_optimizer::dag::CircuitSolution>) + 52071
8  libConcretelangBindingsPythonCAPI.dylib 0x00000001103dbac7 mlir::detail::walk(mlir::Operation*, llvm::function_ref<mlir::WalkResult (mlir::Operation*)>, mlir::WalkOrder) + 199
9  _concretelang.cpython-311-darwin.so     0x000000010bb5fbfe mlir::concretelang::createTFHECircuitSolutionParametrizationPass(std::__1::optional<concrete_optimizer::dag::CircuitSolution>) + 7342
10 _concretelang.cpython-311-darwin.so     0x000000010bb5efff mlir::concretelang::createTFHECircuitSolutionParametrizationPass(std::__1::optional<concrete_optimizer::dag::CircuitSolution>) + 4271
11 libConcretelangBindingsPythonCAPI.dylib 0x0000000110296f16 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) + 582
12 libConcretelangBindingsPythonCAPI.dylib 0x0000000110297606 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) + 358
13 libConcretelangBindingsPythonCAPI.dylib 0x000000011029941d mlir::PassManager::run(mlir::Operation*) + 1037
14 _concretelang.cpython-311-darwin.so     0x000000010b8fb9d1 mlir::concretelang::pipeline::parametrizeTFHE(mlir::MLIRContext&, mlir::ModuleOp&, std::__1::optional<mlir::concretelang::V0FHEContext>&, std::__1::function<bool (mlir::Pass*)>) + 1425
15 _concretelang.cpython-311-darwin.so     0x000000010b90e993 mlir::concretelang::CompilerEngine::compile(mlir::ModuleOp, mlir::concretelang::CompilerEngine::Target, std::__1::optional<std::__1::shared_ptr<mlir::concretelang::CompilerEngine::Library>>) + 4355
16 _concretelang.cpython-311-darwin.so     0x000000010b91289c mlir::concretelang::CompilerEngine::compile(mlir::ModuleOp, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, bool, bool, bool) + 380
17 _concretelang.cpython-311-darwin.so     0x000000010b91278d mlir::concretelang::CompilerEngine::compile(mlir::ModuleOp, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, bool, bool, bool) + 109
18 _concretelang.cpython-311-darwin.so     0x000000010b7c2a27 PyInit__concretelang + 99639
19 _concretelang.cpython-311-darwin.so     0x000000010b7c2495 PyInit__concretelang + 98213
20 _concretelang.cpython-311-darwin.so     0x000000010b817c2c PyInit__concretelang + 448316
21 _concretelang.cpython-311-darwin.so     0x000000010b7b5348 PyInit__concretelang + 44632
22 libpython3.11.dylib                     0x0000000109fc4028 cfunction_call + 72
23 libpython3.11.dylib                     0x0000000109f7bcd4 _PyObject_MakeTpCall + 228
24 libpython3.11.dylib                     0x000000010a069a97 _PyEval_EvalFrameDefault + 57351
25 libpython3.11.dylib                     0x000000010a05b9e0 _PyEval_Vector + 336
26 libpython3.11.dylib                     0x0000000109f7bb72 _PyObject_FastCallDictTstate + 258
27 libpython3.11.dylib                     0x0000000109f7c80a _PyObject_Call_Prepend + 154
28 libpython3.11.dylib                     0x0000000109fe3669 slot_tp_init + 185
29 libpython3.11.dylib                     0x0000000109fd9bb4 type_call + 356
30 libpython3.11.dylib                     0x0000000109f7bcd4 _PyObject_MakeTpCall + 228
31 libpython3.11.dylib                     0x000000010a069a97 _PyEval_EvalFrameDefault + 57351
32 libpython3.11.dylib                     0x000000010a05b84c PyEval_EvalCode + 188
33 libpython3.11.dylib                     0x000000010a0b97d3 run_mod + 147
34 libpython3.11.dylib                     0x000000010a0b8424 PyRun_InteractiveOneObjectEx + 564
35 libpython3.11.dylib                     0x000000010a0b7af3 _PyRun_InteractiveLoopObject + 179
36 libpython3.11.dylib                     0x000000010a0b79a3 _PyRun_AnyFileObject + 83
37 libpython3.11.dylib                     0x000000010a0b819a PyRun_AnyFileExFlags + 58
38 libpython3.11.dylib                     0x000000010a0d7037 Py_RunMain + 2551
39 libpython3.11.dylib                     0x000000010a0d7310 pymain_main + 320
40 libpython3.11.dylib                     0x000000010a0d736b Py_BytesMain + 43
41 dyld                                    0x00007ff8141bf41f start + 1903
zsh: segmentation fault  python

**Comment by dtcxzyw** [comment]
Please file this issue to the downstream repo https://github.com/zama-ai/concrete.
