### ISSUE TITLE
[AMDGPU] [NVPTX] Infer Address Spaces pass leaving behind GEP with no operands

### ISSUE THREAD

**Issue by StackDoubleFlow** [llvm/llvm-project#97086]
This crash was found using an IR fuzzer. It looks like Infer Address Spaces only runs under the AMDGPU and NVPTX backends. The only way I've been able to reproduce this was with a byval struct argument in a function that gets inlined. The inlined function is reading the second field of the struct in this case.

```
%struct = type { i64, i64 }

define i64 @bar(ptr byval(%struct) %a) alwaysinline {
  %1 = getelementptr %struct, ptr %a, i64 0, i32 1
  %2 = load i64, ptr %1, align 4
  ret i64 0
}

define i64 @foo(%struct* %arg) {
  %1 = call i64 @bar(%struct* byval(%struct) align 8 %arg)
  ret i64 0
}
```

Compiler Explorer: https://godbolt.org/z/9zW6nnffT

Here's the IR dump before and after the pass:
```
*** IR Dump After Infer address spaces (infer-address-spaces) ***
; Function Attrs: alwaysinline
define i64 @bar(ptr byval(%struct) %a) #0 {
  %1 = getelementptr %struct, ptr %a, i64 0, i32 1
  %2 = load i64, ptr %1, align 4
  ret i64 0
}
*** IR Dump After Infer address spaces (infer-address-spaces) ***
define i64 @foo(ptr %arg) #1 {
  %arg1 = alloca %struct, align 8, addrspace(5)
  call void @llvm.lifetime.start.p5(i64 16, ptr addrspace(5) %arg1)
  call void @llvm.memcpy.p5.p0.i64(ptr addrspace(5) align 1 %arg1, ptr align 1 %arg, i64 16, i1 false)
  %1 = getelementptr
  %2 = load i64, ptr addrspace(5) %1, align 4
  call void @llvm.lifetime.end.p5(i64 16, ptr addrspace(5) %arg1)
  ret i64 0
}
```

Notice how %1 turned into an empty GEP. This will cause an ICE when later passes assume GEP operands.

**Comment by arsenm** [comment]
Something weird is happening with the example, as it's mixing opaque and non-opaque pointers. This is also using the wrong address space for the byval (though that should still result in well formed IR)

**Comment by arsenm** [comment]
If I extract the IR from the godbolt link with -print-before and -print-module-scope, the IR looks like it's already invalid:
opt: /tmp/bug.ll:20:22: error: '%1' defined with type 'ptr addrspace(5)' but expected 'ptr'
  %2 = load i64, ptr %1, align 4

**Comment by arsenm** [comment]
This looks like it's actually a bug in always-inline.
`opt -S -passes=always-inline` gives me `GEP address space doesn't match type
  %1 = getelementptr %struct, ptr addrspace(5) %arg1, i64 0, i32 1`
