### ISSUE TITLE
llvm/test/Transforms/SampleProfile/csspgo-import-list.ll fails in -DLLVM_ENABLE_EXPENSIVE_CHECKS=on builds

### ISSUE THREAD

**Issue by MaskRay** [llvm/llvm-project#97108]
The test fails in `-DLLVM_ENABLE_EXPENSIVE_CHECKS=on -DLLVM_ENABLE_ASSERTIONS=on` builds, both Debug and Release.

At `llvm/lib/Transforms/IPO/SampleProfile.cpp:1420`, the initialized `NewCandidate` may have a `null` `CalleeSamples`, leading to `assert(LCS && RCS && "Expect non-null FunctionSamples"); ` failure in `(anonymous namespace)::CandidateComparer::operator()`

@WenleiHe

**Comment by WenleiHe** [comment]
Thanks for flagging, we will take a look.
