### ISSUE TITLE
[llvm-strip] llvm-strip doesn't remove empty group sections

### ISSUE THREAD

**Issue by chestnykh** [llvm/llvm-project#97139]
`gcc -g3` produces ELF objects that contains group sections with `.debug_` sections inside.
If such ELF object will be processed with `llvm-strip --strip-debug` then the output ELF will contain

`group section [    1]  .group [foo_grp] contains 0 sections:.`

Such objects cannot be processed for example by GNU binutils (`file format not recognized`).
The Full test case:

`echo 'int main(){return 0;}' > test.c`
`gcc -g3 -c test.c -o test.o`
`llvm-strip --strip-debug test.o -o test.stripped.o`
`ld.bfd test.stripped.o -o test`
`test.stripped.o: file not recognized: file format not recognized`

**Comment by MaskRay** [comment]
I happened to notice that GNU ld reported `file not recognized: file format not recognized` with empty section groups 4 and pinged https://sourceware.org/bugzilla/show_bug.cgi?id=20520  4 weeks ago.

Alan Modra fixed the issue 2 weeks ago for binutils 2.43  :)
