### ISSUE TITLE
u8 prefixed strings have type char instead of char8_t (aka unsigned char)

### ISSUE THREAD

**Issue by StreetwareGames** [llvm/llvm-project#97202]
example: https://godbolt.org/z/KzPz9qj6M

for reference:
https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2418.pdf
https://www.open-std.org/JTC1/SC22/WG14/www/docs/n2653.htm

**Comment by AaronBallman** [comment]
C23 6.4.5p6: "... For UTF-8 string literals, the array elements have type char8_t, and are initialized with the characters of the multibyte character sequence, as encoded in UTF-8. ..."

C23 7.30p3: "... char8_t which is an unsigned integer type used for 8-bit characters and is the same type as unsigned char; ..."

We get it right for character literals (N2418), but not string literals (N2653): https://godbolt.org/z/8oad889GK

(Note, we claim to conform to N2418, we don't claim to conform to N2653 yet.)

**Comment by AaronBallman** [comment]
https://github.com/llvm/llvm-project/pull/97208 should address this.
