### ISSUE TITLE
[RISC-V] Empty structs are ignored when passing in C++

### ISSUE THREAD

**Issue by tomeksowi** [llvm/llvm-project#97285]
According to RISC-V integer calling convention:
> Empty structs or union arguments or return values are ignored by C compilers which support them
as a non-standard extension. **This is not the case for C++, which requires them to be sized types.**

```C++
struct Empty {};

int after_empty(int i0, Empty e, int i1)
{
	return i1;
}

int after_empty_on_stack(
    int i0, int i1, int i2, int i3, int i4, int i5, int i6, int i7, Empty e, int i8)
{
	return i8;
}
```

Clang doesn't assign a register nor a stack slot to the empty struct for passing:
```asm
after_empty(int, Empty, int):                # @after_empty(int, Empty, int)
        mv      a0, a1
        ret
after_empty_on_stack(int, int, int, int, int, int, int, int, Empty, int): # @after_empty_on_stack(int, int, int, int, int, int, int, int, Empty, int)
        ld      a0, 0(sp)
        ret
```

I'd expect these functions to be `mv a0, a2` and `ld a0, 8(sp)` respectively.

This also doesn't match GCC which does allocate a register and stack slot to the empty struct argument. [Comparison with GCC on Godbolt](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXLnwEEAqgGdMABQAenAAy8AVhNK0mDUMgCkAJgBCZ86UX1kBPAMqN0AYVS0AriwYhTpFwAZPAZMADlvACNMYgl/AAdUeUJHBncvH11E5IcBYNCIlmjYqVtMe1ShAiZiAnTvX38yioEqmoJ88KiYuJtq2vrM0v6OkK6inq4AShtUT2Jkdg55AmJPewBqbBZ4ggBPDeMAdksjgBFjAGZLdQBBYzuQgg2mKgIYgH1MHf2IJ428OpSFsfgdMMD/nhpg97icYQ8AJzETAEeYMAFcK43WEXO4w/6vd7EL6gj4CD4rJjIADWEBhGwZAMEAKBTOeUIhzLw/jZAMunPZABYBQCAKwivAANglR2B212YIlAA4pvC4Xj1EiUWiAUqsWqzhwZrROKLeL5uLxUJxXFYrBt5HMFphDqZLjxSAQNEaZtSQJdLgA6AMh0Nh6UmjiC83e0jWji8eQgIFejiaGZwWBINA7OgxciUHPxPOxYgAN0lgoAtMh9IYuEquECaLQiUmIJFY5EQjU9pwPd3mMQ9gB5SJacqpj05tiCEcMWh9tO8LCRTzAVxiWhJy2kLAsAzAcTLvd4ZEVMuYHeaAIqcqed793hPTCRm%2B0PCRYi99xYWOrPAWCfUhL2ISIkkwM5vkPD9DG9GYqH0YB5AANTwTAAHcR3iRhgP4QQRDEdhJGkQQFGUNQTx0KQ6yMO0LD0T8k0gGZUF2VIdyrEcAC8rVA4g8CwZiIBmZpcl8CAXEGXwuH8IIxkKYoQGlbIUgEaTelU8TOkUnppTEyoRg02SbFfSdDPaHTulifSjI8BpekpWorImGzRKdRYJGNU0YxPeMNgAJQASSEVwqxQjZy0rYBkA2WtDw2BtAy4QN1A2CBcEIEhXXdKZeFTdNfX9IMw1KkMI04aNSAtG940TZNPXg0hM0QFBUFzegyAoCAixLEAourGLkC4QUmz4Og20oTsT0HXtgNm4cxwnexgJnRgCHnRdY1XddN1obdgP3GClhvfBzwcS9r14TA72QB8lg9F8314D8vx/DATvygSgN3UDwMUKCD0MWDQGXBCkNQ9CsJwi0PXw4RRHEEj4fI1RYx0fxaJQejrFe4TWPYgROJ4viYgEoT4FEsyWgkqT7KGAIGHQFylKkLTUmM0h2byBTrN0AzWjsjIZNMuxxLaZzedc/mhYc4ZLKl1n3PmTzpj0HzqtjfzgtC8L0srKtuwIeQpg2IbEsFZLUvSzKiGIHLpny%2BCioDYMytK9Wo182rOHqlNnc90xvatX3GrBmZQOSJxBSAA%3D%3D)

ISA: rv64gc
Clang version: 18.1.0 and Godbolt "trunk" at the time of filing this issue (2024-07-01).

**Comment by tomeksowi** [comment]
Part of dotnet/runtime#84834

**Comment by svs-quic** [comment]
The following change seems to fix the issue:

```
--- a/clang/lib/CodeGen/Targets/RISCV.cpp
+++ b/clang/lib/CodeGen/Targets/RISCV.cpp
@@ -361,12 +361,12 @@ ABIArgInfo RISCVABIInfo::classifyArgumentType(QualType Ty, bool IsFixed,
                                            CGCXXABI::RAA_DirectInMemory);
   }
 
+  uint64_t Size = getContext().getTypeSize(Ty);
+
   // Ignore empty structs/unions.
-  if (isEmptyRecord(getContext(), Ty, true))
+  if (isEmptyRecord(getContext(), Ty, true) && Size == 0)
     return ABIArgInfo::getIgnore();
 
-  uint64_t Size = getContext().getTypeSize(Ty);
-
   // Pass floating point values via FPRs if possible.
   if (IsFixed && Ty->isFloatingType() && !Ty->isComplexType() &&
       FLen >= Size && ArgFPRsLeft) {

```

**Comment by tomeksowi** [comment]
@svs-quic Looks like the same problem exists on 32-bit ARM. [Comparison against GCC on Godbolt](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXLnwEEAqgGdMABQAenAAy8AVhNK0mDUMgCkAJgBCZ86UX1kBPAMqN0AYVS0AriwYhTpFwAZPAZMADlvACNMYgl/AAdUeUJHBncvHz9SROSHAWDQiJZo2K5/W0x7VKECJmICdO9fcsw7PIYauoIC8KiYuJta%2BsbM8qHukN7i/rKAShtUT2Jkdg55AmJPewBqbBZ4ggBPbeMAdktTgBFjAGZLdQBBY0eQgm2mKgIYgH1MfaOIK9tnh1KRdv9jpgwUC8FxZs8nucEc8AJzETAEJYMYFcW73RHXR4IoEfL7EX4Q74Cb7rJjIADWEAR2xZwMEwNBbLesOh7Lw/i5wJuvO5ABYRcCAKwSvAANhlpzBewOkJlAA54USkUT1GiMVjgWq8cirhx5rROJLeL5uLxUJxXFYrNt5ItlpgTqYbjxSAQNGb5vSQDcbgA6EMRyNR%2BUWjii63%2B0j2ji8eQgUF%2BjiaeZwWBIND7OgxciUAvxIuxOosABupwAtMh9IYuGquKCaLQyWmIJFE5EQnVDpwff3mMRDgB5SJaSqZn0FtiCCcMWhDrO8LCRTzAVxiWhp22kLAsAzAcTro94dFVauYA%2BaAIqSqeL7D3ivVqJ2h4SLEQfuLBEw2PAWDfUhb2ISIkkwS4/lPb9DH9eYqH0YB5AANTwTAAHcJ3iRgwP4QQRDEdhJGkQQFGUNQLx0KQmyMJ0LD0H800geZUAOVIDzrCcAC87Qg4g8CwNiIHmCoqicCAXBGXwpCCSYihKXQchSAQ5NUpJ1IYHplJmGxWlnapxk0qRJPaTp6j0vpSkGLozPs6ylNsiQJLdFY3L0S0EwvZN3mIGt6yYbZG1PbYW1DLhQ3UbYIFwQgSE9b1Zl4TNs0DYMwyjHKIxjTh41IG0H2TVN019JDSFzRAUFQQt6DICgIDLCsQCrYAuFFNs%2BDoLtKF7C9R0HMChvHKcZ3sMCF0YAhl1XRNN23XdaH3MDj3g1YH3wa8HFve9eEwJ9kBfVYfQ/WMH2/X9/wwTa0uE0DDwgqDFFgk9DAQ0B12Q1CMKw3D8JtH0iOEURxHIkGqNURMdH8BiUCY6wrrEjiuIEHj%2BMEmJhNE%2BAJKMqTfBkhg3A8JpdEUwpXKkNT2kc2nUhs6Y7IskyHLJzJzIJyzxiZlTzNMjn5KciYqeZrzXSWTy4W8jgrSKxN/IeAAlABZbYAHFXFcCLRSimK4oSohiGSuE0qQzKQ3DXKctlwrirtTgyozC3ZdMXySqdirvvmCDkicUUgA%3D)

I'm less familiar with ARM 32 so I can't point to the exact wording in the ABI that specifies empty struct treatment.
