### ISSUE TITLE
[Github] Run failed: Comment on an issue

### ISSUE THREAD

**Issue by Sirraide** [llvm/llvm-project#97294]
I got an email today about a failing workflow; I figured it was spurious failure at first, but then I got a second one, so maybe there’s something more to this:

- https://github.com/llvm/llvm-project/actions/runs/9744623941
- https://github.com/llvm/llvm-project/actions/runs/9745315904

CC @tstellar, @boomanaiden154

**Comment by boomanaiden154** [comment]
The most recent change that seems like it touched the file was https://github.com/llvm/llvm-project/pull/94784.

**Comment by boomanaiden154** [comment]
It looks like #94784 made the request release notes workflow use the issue commentor (which is the workflow that's erroring out). It gets skipped if the PR is not opened against a release branch, but the issue comment workflow runs anyways.
