### ISSUE TITLE
`cabs (x + 0i)`and `cabs(0.0 + xi)` should be optimized to `abs(x)` even without `-ffast-math`

### ISSUE THREAD

**Issue by pinskia** [llvm/llvm-project#97336]
Take the fortran testcase:
```
subroutine foo(a,b,n)
  real(kind(1d0))::a
  real(kind(1d0))::b
  integer::i,n
  complex(kind(1d0))::c

  c = a
     b=abs(c)

end subroutine foo
```

This should be just optimized to `abs(a)` rather than a call to `cabs`.

C testcase:
```
double
foo (double e)
{
  _Complex double x = __builtin_complex(0.0,e);
  return __builtin_cabs(e);
}
double
foo1 (double e)
{
  return __builtin_cabs(e);
}
```

Likewise for `hypot` too.
```
double
fooh (double e)
{
  return __builtin_hypot(e, 0.0);
}
```

The definition of hypot in C99 allows for this.

GCC has been handling `foo1`  function since before GCC 3.4.0. `fooh` function since GCC 4.4.0.
This is more likely to show up with fortran code than C or C++ code.

**Comment by dtcxzyw** [comment]
We can handle this pattern in `LibCallSimplifier::optimizeCAbs` before the `CI->isFast` check.

> Likewise for hypot too.
```
double
fooh (double e)
{
  return __builtin_hypot(e, 0.0);
}
```

Please file a separate issue to track the progress.

**Comment by HendrikHuebner** [comment]
Can I work on this?

**Comment by Mehdibenhadjkhelifa** [comment]
hello @HendrikHuebner . Are you still working on this?

**Comment by HendrikHuebner** [comment]
yes. I would still like to work on this

**Comment by akshaykumars614** [comment]
@pinskia, can you help me understand this issue please? I am new here. This should be optimized even without any optimizations specified?

If yes, the, should there be a cmp inst to check if any of them is zero or we do it internally and just generate the cabs(x) ?

**Comment by HendrikHuebner** [comment]
@akshaykumars614 the libcall simplify pass optimizes calls to libc functions before generating IR. It's like simplifying a mathematical formula. In this case, if the real or imaginary part of the input is zero, we can just replace the call to cabs with a call to abs. But please do not work on this. I'm about to submit a PR.

**Comment by akshaykumars614** [comment]
Ohh okay! I'm not working on it. I'm new here and trying to understand the issue. Thanks for the explanation.

**Comment by HendrikHuebner** [comment]
you can have a look through the code in SimplifyLibCalls.cpp. It's very interesting imo.

**Comment by akshaykumars614** [comment]
Got it.
