### ISSUE TITLE
[InstCombine] Miscompilation with llvm.assume in unreachable blocks

### ISSUE THREAD

**Issue by dtcxzyw** [llvm/llvm-project#97330]
Reproducer: https://alive2.llvm.org/ce/z/zKvpXV
```
; bin/opt -passes=instcombine reduced.ll -S
define i16 @src(i16 %g, ptr %e, ptr %d) {
entry:
  %0 = load i64, ptr %d, align 8
  %conv = trunc i64 %0 to i16
  %tobool.not.i = icmp eq i16 %g, 0
  br i1 %tobool.not.i, label %i.exit, label %for.cond.preheader.i

for.cond.preheader.i:
  %cmp5.i = icmp ne i16 %g, %conv
  %conv6.i = zext i1 %cmp5.i to i32
  store i32 %conv6.i, ptr %e, align 4
  %cmp7.i = icmp eq i64 %0, 1
  call void @llvm.assume(i1 %cmp7.i)
  unreachable

i.exit:
  ret i16 %conv
}
```
```
define i16 @tgt(i16 %g, ptr %e, ptr %d) {
entry:
  %tobool.not.i = icmp eq i16 %g, 0
  br i1 %tobool.not.i, label %i.exit, label %for.cond.preheader.i

for.cond.preheader.i:                             ; preds = %entry
  unreachable

i.exit:                                           ; preds = %entry
  ret i16 1
}
```

llvm version: a8e1c3e1239604ac787b6a2d39b5278ddec8aa8a

cc @nikic

**Comment by dtcxzyw** [comment]
Reverting https://github.com/llvm/llvm-project/commit/11484cb817bcc2a6e2ef9572be982a1a5a4964ec fixes this issue.

**Comment by nikic** [comment]
I've applied two fixes for this. https://github.com/llvm/llvm-project/commit/86b37944a70229b07626e63bdb9a46b4bc3d1460 tries to stick closer to the current logic, while https://github.com/llvm/llvm-project/commit/05670b42f5b45710bfdba48dcb7e8c30c8c7478f is a more thorough fix on top of that.

**Comment by dtcxzyw** [comment]
Confirmed that the original case has been fixed. Thank you!

**Comment by chapuni** [comment]
@nikic Fixed, thanks!
