### ISSUE TITLE
[RISC-V] .insn directive does not support constant arg

### ISSUE THREAD

**Issue by charlie-rivos** [llvm/llvm-project#97498]
GNU-as supports a constant value to the .insn assembler directive as of commit: https://github.com/bminor/binutils-gdb/commit/a262b82fdbf4cda3b0648b1adc32245ca3f78b7a. The RISC-V LLVM assembler currently only supports the .insn directive with in the form of `.insn <type>, <operand1>, <operand2>`. Can the form of `.insn <value>` also be supported by Clang?

**Comment by lenary** [comment]
These are in a PR against the asm manual, but it hasn't landed yet: https://github.com/riscv-non-isa/riscv-asm-manual/pull/106

**Comment by charlie-rivos** [comment]
I will push that through first then, thank you!
