### ISSUE TITLE
Synchronous mode, Ctrl-C operation leads to an assertion fails.

### ISSUE THREAD

**Issue by zzh1010016195** [llvm/llvm-project#97511]
It seems that LLDB is using an unsupported format.
System info:
```
LSB Version:	security-11.1.0ubuntu4-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```
It's easy to reproduce this situation. 
First, we need to run an infinite loop and let LLDB attach to the process.
Then, we set LLDB to synchronous mode and  type continue.
Now, by pressing Ctrl-C twice, LLDB will report an error.
```
(lldb) process attach -n deadloop 
Process 1032676 stoppeddexing DWARF: libc.so.6...
* thread #1, name = 'deadloop', stop reason = signal SIGSTOP
    frame #0: 0x0000646a9e9b2131 deadloop`main at deadloop.cpp:2:3
   1   	int main() {
-> 2   	  while(1) {
   3   	
   4   	  }
   5   	  return 0;
   6   	}
Executable module set to "/home/antlia/zzh/Test/X86/deadloop".
Architecture set to: x86_64-unknown-linux-gnu.
(lldb) script lldb.debugger.SetAsync(False)
(lldb) c
^C^Clldb: /home/antlia/zzh/SourceCode/llvm-project/llvm/include/llvm/Support/FormatProviders.h:149: static void llvm::format_provider<unsigned long>::format(const T &, llvm::raw_ostream &, llvm::StringRef) [T = unsigned long, Enable = void]: Assertion `Style.empty() && "Invalid integral format style!"' failed.
LLDB diagnostics will be written to /tmp/diagnostics-c8ceeb
Please include the directory content when filing a bug report
Aborted
```

I have seen this string in LLDB: "Interrupted dumping stack for thread {0:hex} with {1} shown."
The 'hex' format doesn't seem to be supported.

By the way, why do I need to press Ctrl-C twice?

**Comment by jimingham** [comment]
In general, the first ^C to lldb is directed to the command currently running, to see if it can interrupt itself.  If the command doesn't handle the interrupt, then the next ^C is sent directly to the process (if there is one).

In synchronous mode, lldb is calling WaitForEvent with no timeout, so it doesn't respond to interrupts.  We could make it wait with a timeout and check for interrupt after each timeout, and interrupt the process.  But at present, we didn't make any of the "process running" commands interrupt themselves, so they require two ^C's.

We could also define a chain of interrupt handlers, and try them one by one after a ^C, so if `continue` didn't interrupt itself, we could directly try the process.  Not sure how tricky that would be to manage.

**Comment by bulbazord** [comment]
`{0:hex}` is wrong, should be `{0:x}`. I'll open a PR.

**Comment by EugeneZelenko** [comment]
Not merged to `main` yet.

**Comment by bulbazord** [comment]
Oh... wow. I accidentally merged it into a fork of LLVM. Sorry about that.
