### ISSUE TITLE
[clang-tidy] update clang-tidy documentation to include the version where each check was first introduced

### ISSUE THREAD

**Issue by kiselik** [llvm/llvm-project#97717]
currently, there is no way to determine in which version each check (and its options) first appeared

please extend documentation by this information (like in clang-format) 
![image](https://github.com/llvm/llvm-project/assets/16230320/0004aa1b-48a1-4567-98fb-bb31faf1ed28)

**Comment by PiotrZSL** [comment]
You should use documentation generated for version of clang-tidy that you actually using.
