### ISSUE TITLE
FP optimization wrong wrt NaNs?

### ISSUE THREAD

**Issue by regehr** [llvm/llvm-project#97837]
here's a function:
```llvm
define float @f(float %0) {
  %2 = fpext float %0 to double
  %3 = fptrunc double %2 to float
  ret float %3
}
```
```
$ ~/llvm-project/for-alive/bin/opt -passes=instcombine bar.ll -S -o -
; ModuleID = 'bar.ll'
source_filename = "bar.ll"

define float @f(float %0) {
  ret float %0
}
```

InstCombine elides the ext/trunc and just returns %0. Alive finds that this optimization changes the behavior-- the original code quiets an incoming SNaN, whereas the optimized code obviously doesn't do that (sorry, no CE link, this example times out there)
```
Example:
float %#0 = #x7f808003 (SNaN)

Source:
double %#2 = #x7ff8000000000000 (QNaN)
float %#3 = #x7fc00000 (QNaN)

Target:
Source value: #x7fc00000 (QNaN)
Target value: #x7f808003 (SNaN)
```
our understanding is that this behavior is a violation of what LLVM is currently trying to do. is Alive right here, or LLVM? thanks
cc @RalfJung @nunoplopes

**Comment by arsenm** [comment]
This is correct. Non strictfp ops do not guarantee sNaN quieting

**Comment by nikic** [comment]
See https://llvm.org/docs/LangRef.html#behavior-of-floating-point-nan-values, with one of the possibilities being:

> The quiet bit and payload are copied from any input operand that is a NaN. (“Unchanged NaN propagation” case)

I guess the case here is slightly trick because of the different FP types involved, so you can't just copy the payload, but as long as fpext+fptrunc treat it consistency you can still preserve it through the operation pair.

**Comment by RalfJung** [comment]
Specifically, fpext says

> NaN values follow the usual [NaN behaviors](https://llvm.org/docs/LangRef.html#floatnan), except that _if_ a NaN payload is propagated from the input (“Quieting NaN propagation” or “Unchanged NaN propagation” cases), then it is copied to the high order bits of the resulting payload, and the remaining low order bits are zero.

and fptrunc says

> NaN values follow the usual [NaN behaviors](https://llvm.org/docs/LangRef.html#floatnan), except that _if_ a NaN payload is propagated from the input (“Quieting NaN propagation” or “Unchanged NaN propagation” cases), then the low order bits of the NaN payload which cannot fit in the resulting type are discarded. Note that if discarding the low order bits leads to an all-0 payload, this cannot be represented as a signaling NaN (it would represent an infinity instead), so in that case “Unchanged NaN propagation” is not possible.

So... seems like an Alive bug to me.

**Comment by nunoplopes** [comment]
It was a bug in fptrunc indeed. It was getting the lower-order bits rather than the higher-order bits of the payload.
Thanks!
