### ISSUE TITLE
[memcpyopt] memset not created out of per-field store instructions

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#9789]
|  |  |
| --- | --- |
| Bugzilla Link | [9417](https://llvm.org/bz9417) |
| Version | trunk |
| OS | Linux |
| Attachments | [testcase .ll](https://user-images.githubusercontent.com/60944935/143742843-d1c2418f-05af-45b4-abc5-bc4adc91482c.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @lattner |

## Extended Description 

The attached file is a .ll with a simple loop doing 3 stores of 0 to each member in @&#8203;glbl. Loop idiom recognizer won't merge it because each store has a stride larger than the width of the store.

Who's responsible for merging:

  A = gep foo, 0
  B = gep foo, 1
  store 0, A
  store 0, B

into one store/memset instruction?

This is pulled from MultiSource/Benchmarks/Ptrdist/ks which has gcc/llc = 0.46 on x86-64 linux.

**Comment by arsenm** [comment]
```
target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:64-s0:64:64-f80:128:128-n8:16:32:64"
target triple = "x86_64-unknown-linux-gnu"

%s = type { i64, i64, i64 }

@glbl = unnamed_addr global [256 x %s] zeroinitializer, align 16

define void @test() {
entry:
  br label %loop

loop:                                             ; preds = %loop, %entry
  %indvar = phi i64 [ 0, %entry ], [ %indvar2, %loop ]
  %x = getelementptr [256 x %s], ptr @glbl, i64 0, i64 %indvar, i32 0
  %y = getelementptr [256 x %s], ptr @glbl, i64 0, i64 %indvar, i32 1
  %z = getelementptr [256 x %s], ptr @glbl, i64 0, i64 %indvar, i32 2
  store i64 0, ptr %x, align 8
  store i64 0, ptr %y, align 8
  store i64 0, ptr %z, align 8
  %indvar2 = add i64 %indvar, 1
  %exitcond = icmp eq i64 %indvar2, 256
  br i1 %exitcond, label %exit, label %loop

exit:                                             ; preds = %loop
  ret void
}
```
opt -p=memcpyopt does produce a memset. opt -O3 reduces the whole function to just the memset
