### ISSUE TITLE
[clang-format] BasedOnStyle: dummy

### ISSUE THREAD

**Issue by feelamee** [llvm/llvm-project#97892]
Hey

Is it possible to create dummy style, which will ignore all what is not configured?
I want to use clang-format in already big not formatted repository, but some of it code-style rules can't be represented in clang-format options.

One of example is namespace braces formatting. We always break before braces. But we also use compact record for several sequenced namespaces (we use C++14). See example.
Our code style is
```cpp
namespace foo
{
```
```cpp
namespace foo { namespace boo
{
```
But clang-format can only
```cpp
namespace foo
{
namespace boo
{
```
or
```cpp
namespace foo { namespace boo {
```

This isn't the one such example that's why for us is much easier to ignore this then change code-style.

So, I think better have 90% of  auto formatted rules then 0.

I'm ready to contribute to add this feature if it is possible to add it in current clang-format implementation at all

**Comment by mydeveloperday** [comment]
This isn't technically possible, were possible we try to add "Leave" options to new code, but  there are many options where that wasn't done in the past or may not even always be possible.

Honestly its better to pick a style which matches yours as closely as possible and go with that, if there are rules that aren't support either propose a fix, or maybe you team should consider moving to a common open source theme, its often better than a companies "special snowflake"

If all else fails there is always //clang-format off/on that can be used to ignore changes between those lines.
