### ISSUE TITLE
can't format file using clang-format command

### ISSUE THREAD

**Issue by Wh0mever** [llvm/llvm-project#98031]
![Screenshot_20240708_194748](https://github.com/llvm/llvm-project/assets/134455247/59aa32c7-9008-48ae-9b74-80365291b947)

**Comment by EugeneZelenko** [comment]
Could you please try 18 or `main` branch?

Please also provide configuration and reproducer if newer versions of Clang-format still crash.

**Comment by DimitryAndric** [comment]
Works fine here, with any version of clang-format that I tried. It is probably best to post the original cpp file instead of a screenshot.
