### ISSUE TITLE
clang crash backtrace with `/usr/include/c++/14.1.1/bits/stl_vector.h:1130: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = llvm::SUnit; _Alloc = std::allocator<llvm::SUnit>; reference = llvm::SUnit&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.`.

### ISSUE THREAD

**Issue by dreirund** [llvm/llvm-project#98045]
`clang` did tell me that I should submit a bug report:

> *`PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.`*

I was compiling the Linux kernel with [XanMod-patch](https://sourceforge.net/projects/xanmod/files/releases/main/6.9.8-xanmod1/patch-6.9.8-xanmod1.xz/download), version 6.9.8, using [this kernel `.config`](https://github.com/user-attachments/files/16132097/config-6.9-xanmod-custom-clang.txt).

While doing so, I got the following error which told me that I should report it here.  
Note that I do not know C stuff, linking stuff, and compiler specialities. I just report here because I was told so, I cannot interpret the issue.

```
[...]
  LD      vmlinux.o
/usr/include/c++/14.1.1/bits/stl_vector.h:1130: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = llvm::SUnit; _Alloc = std::allocator<llvm::SUnit>; reference = llvm::SUnit&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: ld.lld -m elf_x86_64 -mllvm -import-instr-limit=5 -z noexecstack -r -o vmlinux.o -T .tmp_initcalls.lds --whole-archive vmlinux.a --no-whole-archive --start-group --end-group
1.	Running pass 'Function Pass Manager' on module 'ld-temp.o'.
2.	Running pass 'X86 DAG->DAG Instruction Selection' on function '@ip6_rcv_core'
 #0 0x00007f1b91db7911 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/libLLVM.so.18.1+0x7b7911)
 #1 0x00007f1b91db48e3 (/usr/lib/libLLVM.so.18.1+0x7b48e3)
 #2 0x00007f1b9105a770 (/usr/lib/libc.so.6+0x3c770)
 #3 0x00007f1b910ab32c (/usr/lib/libc.so.6+0x8d32c)
 #4 0x00007f1b9105a6c8 raise (/usr/lib/libc.so.6+0x3c6c8)
 #5 0x00007f1b910424b8 abort (/usr/lib/libc.so.6+0x244b8)
 #6 0x00007f1b912d2242 (/usr/lib/libstdc++.so.6+0xd2242)
 #7 0x00007f1b9288ac98 llvm::ScheduleDAGSDNodes::AddSchedEdges() (/usr/lib/libLLVM.so.18.1+0x128ac98)
 #8 0x00007f1b9288318e (/usr/lib/libLLVM.so.18.1+0x128318e)
 #9 0x00007f1b9296f813 llvm::SelectionDAGISel::CodeGenAndEmitDAG() (/usr/lib/libLLVM.so.18.1+0x136f813)
#10 0x00007f1b92972b79 llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/usr/lib/libLLVM.so.18.1+0x1372b79)
#11 0x00007f1b92974bb5 (/usr/lib/libLLVM.so.18.1+0x1374bb5)
#12 0x00007f1b92976481 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/usr/lib/libLLVM.so.18.1+0x1376481)
#13 0x00007f1b95ecb9f7 (/usr/lib/libLLVM.so.18.1+0x48cb9f7)
#14 0x00007f1b922f8ebd (/usr/lib/libLLVM.so.18.1+0xcf8ebd)
#15 0x00007f1b91f68289 llvm::FPPassManager::runOnFunction(llvm::Function&) (/usr/lib/libLLVM.so.18.1+0x968289)
#16 0x00007f1b91f68604 llvm::FPPassManager::runOnModule(llvm::Module&) (/usr/lib/libLLVM.so.18.1+0x968604)
#17 0x00007f1b91f6a08c llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/lib/libLLVM.so.18.1+0x96a08c)
#18 0x00007f1b93d65361 (/usr/lib/libLLVM.so.18.1+0x2765361)
#19 0x00007f1b93d65a1f llvm::lto::backend(llvm::lto::Config const&, std::function<llvm::Expected<std::unique_ptr<llvm::CachedFileStream, std::default_delete<llvm::CachedFileStream>>> (unsigned int, llvm::Twine const&)>, unsigned int, llvm::Module&, llvm::ModuleSummaryIndex&) (/usr/lib/libLLVM.so.18.1+0x2765a1f)
#20 0x00007f1b93d5a446 llvm::lto::LTO::runRegularLTO(std::function<llvm::Expected<std::unique_ptr<llvm::CachedFileStream, std::default_delete<llvm::CachedFileStream>>> (unsigned int, llvm::Twine const&)>) (/usr/lib/libLLVM.so.18.1+0x275a446)
#21 0x00007f1b93d5a957 llvm::lto::LTO::run(std::function<llvm::Expected<std::unique_ptr<llvm::CachedFileStream, std::default_delete<llvm::CachedFileStream>>> (unsigned int, llvm::Twine const&)>, std::function<llvm::Expected<std::function<llvm::Expected<std::unique_ptr<llvm::CachedFileStream, std::default_delete<llvm::CachedFileStream>>> (unsigned int, llvm::Twine const&)>> (unsigned int, llvm::StringRef, llvm::Twine const&)>) (/usr/lib/libLLVM.so.18.1+0x275a957)
#22 0x00007f1b99916c53 lld::elf::BitcodeCompiler::compile() (/usr/lib/liblldELF.so.18.1+0x116c53)
#23 0x00007f1b998a06e3 lld::elf::LinkerDriver::link(llvm::opt::InputArgList&) (/usr/lib/liblldELF.so.18.1+0xa06e3)
#24 0x00007f1b998864d9 lld::elf::LinkerDriver::linkerMain(llvm::ArrayRef<char const*>) (/usr/lib/liblldELF.so.18.1+0x864d9)
#25 0x00007f1b998880c5 lld::elf::link(llvm::ArrayRef<char const*>, llvm::raw_ostream&, llvm::raw_ostream&, bool, bool) (/usr/lib/liblldELF.so.18.1+0x880c5)
#26 0x00007f1b99ad5a47 lld::unsafeLldMain(llvm::ArrayRef<char const*>, llvm::raw_ostream&, llvm::raw_ostream&, llvm::ArrayRef<lld::DriverDef>, bool) (/usr/lib/liblldCommon.so.18.1+0xba47)
#27 0x00005618b6e54a74 lld_main(int, char**, llvm::ToolContext const&) (/usr/bin/ld.lld+0x2a74)
#28 0x00005618b6e5428a main (/usr/bin/ld.lld+0x228a)
#29 0x00007f1b91043cd0 (/usr/lib/libc.so.6+0x25cd0)
#30 0x00007f1b91043d8a __libc_start_main (/usr/lib/libc.so.6+0x25d8a)
#31 0x00005618b6e542e5 _start (/usr/bin/ld.lld+0x22e5)
make[2]: *** [scripts/Makefile.vmlinux_o:62: vmlinux.o] Error 134
make[1]: *** [/var/cache/makepkg/build/linux-dreieck/src/build/xanmod-customconfig-clang/Makefile:1292: vmlinux_o] Error 2
make: *** [Makefile:240: __sub-make] Error 2
```

---

*EDIT: Addition:* After first fail I wiped the Linux compilation directory and tried again, failure re-appeared. So at least I could reproduce it. (Appeared in two of two cases.)

Regards!

**Comment by dreirund** [comment]
> @llvm/issue-subscribers-backend-x86
> 
> Author: None (dreirund)
> 
> <details>
> `clang` did tell me that I should submit a bug report:
> 
> &gt; *`PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.`*
> 
> I was compiling the Linux kernel with [XanMod-patch](https://sourceforge.net/projects/xanmod/files/releases/main/6.9.8-xanmod1/patch-6.9.8-xanmod1.xz/download), version 6.9.8, using [this kernel `.config`](https://github.com/user-attachments/files/16132097/config-6.9-xanmod-custom-clang.txt).
> 
> While doing so, I got the following error which told me that I should report it here.
> Note that I do not know C stuff, linking stuff, and compiler specialities. I just report here because I was told so, I cannot interpret the issue.
> 
> ```
> [...]
> LD      vmlinux.o
> /usr/include/c++/14.1.1/bits/stl_vector.h:1130: std::vector&lt;_Tp, _Alloc&gt;::reference std::vector&lt;_Tp, _Alloc&gt;::operator[](size_type) [with _Tp = llvm::SUnit; _Alloc = std::allocator&lt;llvm::SUnit&gt;; reference = llvm::SUnit&amp;; size_type = long unsigned int]: Assertion '__n &lt; this-&gt;size()' failed.
> PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
> Stack dump:
> 0.	Program arguments: ld.lld -m elf_x86_64 -mllvm -import-instr-limit=5 -z noexecstack -r -o vmlinux.o -T .tmp_initcalls.lds --whole-archive vmlinux.a --no-whole-archive --start-group --end-group
> 1.	Running pass 'Function Pass Manager' on module 'ld-temp.o'.
> 2.	Running pass 'X86 DAG-&gt;DAG Instruction Selection' on function '@ip6_rcv_core'
> #0 0x00007f1b91db7911 llvm::sys::PrintStackTrace(llvm::raw_ostream&amp;, int) (/usr/lib/libLLVM.so.18.1+0x7b7911)
> #1 0x00007f1b91db48e3 (/usr/lib/libLLVM.so.18.1+0x7b48e3)
> #2 0x00007f1b9105a770 (/usr/lib/libc.so.6+0x3c770)
> #3 0x00007f1b910ab32c (/usr/lib/libc.so.6+0x8d32c)
> #4 0x00007f1b9105a6c8 raise (/usr/lib/libc.so.6+0x3c6c8)
> #5 0x00007f1b910424b8 abort (/usr/lib/libc.so.6+0x244b8)
> #6 0x00007f1b912d2242 (/usr/lib/libstdc++.so.6+0xd2242)
> #7 0x00007f1b9288ac98 llvm::ScheduleDAGSDNodes::AddSchedEdges() (/usr/lib/libLLVM.so.18.1+0x128ac98)
> #8 0x00007f1b9288318e (/usr/lib/libLLVM.so.18.1+0x128318e)
> #9 0x00007f1b9296f813 llvm::SelectionDAGISel::CodeGenAndEmitDAG() (/usr/lib/libLLVM.so.18.1+0x136f813)
> #10 0x00007f1b92972b79 llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&amp;) (/usr/lib/libLLVM.so.18.1+0x1372b79)
> #11 0x00007f1b92974bb5 (/usr/lib/libLLVM.so.18.1+0x1374bb5)
> #12 0x00007f1b92976481 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&amp;) (/usr/lib/libLLVM.so.18.1+0x1376481)
> #13 0x00007f1b95ecb9f7 (/usr/lib/libLLVM.so.18.1+0x48cb9f7)
> #14 0x00007f1b922f8ebd (/usr/lib/libLLVM.so.18.1+0xcf8ebd)
> #15 0x00007f1b91f68289 llvm::FPPassManager::runOnFunction(llvm::Function&amp;) (/usr/lib/libLLVM.so.18.1+0x968289)
> #16 0x00007f1b91f68604 llvm::FPPassManager::runOnModule(llvm::Module&amp;) (/usr/lib/libLLVM.so.18.1+0x968604)
> #17 0x00007f1b91f6a08c llvm::legacy::PassManagerImpl::run(llvm::Module&amp;) (/usr/lib/libLLVM.so.18.1+0x96a08c)
> #18 0x00007f1b93d65361 (/usr/lib/libLLVM.so.18.1+0x2765361)
> #19 0x00007f1b93d65a1f llvm::lto::backend(llvm::lto::Config const&amp;, std::function&lt;llvm::Expected&lt;std::unique_ptr&lt;llvm::CachedFileStream, std::default_delete&lt;llvm::CachedFileStream&gt;&gt;&gt; (unsigned int, llvm::Twine const&amp;)&gt;, unsigned int, llvm::Module&amp;, llvm::ModuleSummaryIndex&amp;) (/usr/lib/libLLVM.so.18.1+0x2765a1f)
> #20 0x00007f1b93d5a446 llvm::lto::LTO::runRegularLTO(std::function&lt;llvm::Expected&lt;std::unique_ptr&lt;llvm::CachedFileStream, std::default_delete&lt;llvm::CachedFileStream&gt;&gt;&gt; (unsigned int, llvm::Twine const&amp;)&gt;) (/usr/lib/libLLVM.so.18.1+0x275a446)
> #21 0x00007f1b93d5a957 llvm::lto::LTO::run(std::function&lt;llvm::Expected&lt;std::unique_ptr&lt;llvm::CachedFileStream, std::default_delete&lt;llvm::CachedFileStream&gt;&gt;&gt; (unsigned int, llvm::Twine const&amp;)&gt;, std::function&lt;llvm::Expected&lt;std::function&lt;llvm::Expected&lt;std::unique_ptr&lt;llvm::CachedFileStream, std::default_delete&lt;llvm::CachedFileStream&gt;&gt;&gt; (unsigned int, llvm::Twine const&amp;)&gt;&gt; (unsigned int, llvm::StringRef, llvm::Twine const&amp;)&gt;) (/usr/lib/libLLVM.so.18.1+0x275a957)
> #22 0x00007f1b99916c53 lld::elf::BitcodeCompiler::compile() (/usr/lib/liblldELF.so.18.1+0x116c53)
> #23 0x00007f1b998a06e3 lld::elf::LinkerDriver::link(llvm::opt::InputArgList&amp;) (/usr/lib/liblldELF.so.18.1+0xa06e3)
> #24 0x00007f1b998864d9 lld::elf::LinkerDriver::linkerMain(llvm::ArrayRef&lt;char const*&gt;) (/usr/lib/liblldELF.so.18.1+0x864d9)
> #25 0x00007f1b998880c5 lld::elf::link(llvm::ArrayRef&lt;char const*&gt;, llvm::raw_ostream&amp;, llvm::raw_ostream&amp;, bool, bool) (/usr/lib/liblldELF.so.18.1+0x880c5)
> #26 0x00007f1b99ad5a47 lld::unsafeLldMain(llvm::ArrayRef&lt;char const*&gt;, llvm::raw_ostream&amp;, llvm::raw_ostream&amp;, llvm::ArrayRef&lt;lld::DriverDef&gt;, bool) (/usr/lib/liblldCommon.so.18.1+0xba47)
> #27 0x00005618b6e54a74 lld_main(int, char**, llvm::ToolContext const&amp;) (/usr/bin/ld.lld+0x2a74)
> #28 0x00005618b6e5428a main (/usr/bin/ld.lld+0x228a)
> #29 0x00007f1b91043cd0 (/usr/lib/libc.so.6+0x25cd0)
> #30 0x00007f1b91043d8a __libc_start_main (/usr/lib/libc.so.6+0x25d8a)
> #31 0x00005618b6e542e5 _start (/usr/bin/ld.lld+0x22e5)
> make[2]: *** [scripts/Makefile.vmlinux_o:62: vmlinux.o] Error 134
> make[1]: *** [/var/cache/makepkg/build/linux-dreieck/src/build/xanmod-customconfig-clang/Makefile:1292: vmlinux_o] Error 2
> make: *** [Makefile:240: __sub-make] Error 2
> ```
> 
> Regards!


Note: &uarr; [this doubling](#issuecomment-2214924973) of my [initial post](#issue-2396088755) has the stacktrace corrupted (e.g. added `<!-- -->` which were not there originally) (besides other formatting corruptions). Just be careful. *(And why is the post doubled anyway?)*

Regards!

**Comment by GuzLightyear** [comment]
I had a similar issue compiling [linux-cachyos](https://aur.archlinux.org/packages/linux-cachyos) 6.9.8 from the arch repository. Downgrading clang, llvm and lld to version 17 (from 18.1) worked and fixed the issue.

**Comment by RKSimon** [comment]
Does #85081 / 46505b3cbfc5f48f28431b9141085c5d71ddf1c4 fix this?

**Comment by dreirund** [comment]
For me the issue now vanished. (Tried again with the same kernel version I used initially).

Only changed:

* Disabled `ccache` use,
* system upgrade (but `clang` was not updated).

@GuzLightyear, @xuanruiqi: Do you still reproduce this issue? With/ without `ccache`?

---

[@RKSimon wrote on 2024-07-17](#issuecomment-2233769519):  
> *Does [#85081](https://github.com/llvm/llvm-project/pull/85081) / [`46505b3`](https://github.com/llvm/llvm-project/commit/46505b3cbfc5f48f28431b9141085c5d71ddf1c4) fix this?*

I do not try. I do not take the burden to compile `clang` myself, I stick to what [my distribution](http://artixlinux.org/) offers to me.

**Comment by RKSimon** [comment]
> > Does #85081 / [46505b3](https://github.com/llvm/llvm-project/commit/46505b3cbfc5f48f28431b9141085c5d71ddf1c4) fix this?
> 
> I was experiencing this same issue, backporting this commit to 18.1.8 appears to have fixed it.

Thank you for confirming, we're not intending to do any more 18.x releases, and the 19.x release cycle is imminent so I'm going to close this as fixed in trunk.
