### ISSUE TITLE
UnrollMaxUpperBound is not respected

### ISSUE THREAD

**Issue by hiraditya** [llvm/llvm-project#98064]
```cpp
#include<cstring>
#include<wctype.h>

enum {
  WC_TYPE_INVALID = 0,
  WC_TYPE_ALNUM,
  WC_TYPE_ALPHA,
  WC_TYPE_BLANK,
  WC_TYPE_CNTRL,
  WC_TYPE_DIGIT,
  WC_TYPE_GRAPH,
  WC_TYPE_LOWER,
  WC_TYPE_PRINT,
  WC_TYPE_PUNCT,
  WC_TYPE_SPACE,
  WC_TYPE_UPPER,
  WC_TYPE_XDIGIT,
  WC_TYPE_MAX
};

wctype_t wctype(const char* property) {
  static const char* const  properties[WC_TYPE_MAX] = {
    "<invalid>",
    "alnum", "alpha", "blank", "cntrl", "digit", "graph",
    "lower", "print", "punct", "space", "upper", "xdigit"
  };
  for (size_t i = 0; i < WC_TYPE_MAX; ++i) {
    if (!strcmp(properties[i], property)) {
      return static_cast<wctype_t>(i);
    }
  }
  return static_cast<wctype_t>(0);
}
```

`$ clang -O2 -mllvm -unroll-max-upperbound=2` unrolls the loop completely.

https://godbolt.org/z/KcaExhThq

**Comment by nikic** [comment]
As the name suggests, `unroll-max-upperbound` is the maximum unroll factor for upper-bound unrolling. Your loop is fully unrolled, not upper-bound unrolled.

**Comment by hiraditya** [comment]
Is there a flag to prevent full unrolling when total trip count is more than a certain value say 8?

**Comment by nikic** [comment]
@hiraditya Yes, `-unroll-full-max-count`.

**Comment by hiraditya** [comment]
Closing this. It is a bit confusing to have separate flags `-unroll-full-max-count` (where description suggests that this is for testing purposes) and `-unroll-max-upperbound`. I feel like `-unroll-max-upperbound` should also set the value of `-unroll-full-max-count`, unless explicitly asked not to.
