### ISSUE TITLE
Fortran c_f_pointer with deferred attributes

### ISSUE THREAD

**Issue by mfvalin** [llvm/llvm-project#98218]
> cat dynamic.F90 
subroutine c_f_strpointer1(cstrarray, fstrptr, nchars)
  use ISO_C_BINDING
  implicit none
  character(C_CHAR), dimension(*), intent(IN), target :: cstrarray
  character(len=:), pointer, intent(OUT) :: fstrptr
  integer, intent(IN) :: nchars
  type(C_PTR) :: cstrptr
  character(len=:), pointer :: fptr

  cstrptr = C_LOC(cstrarray(1))
  call c_f_pointer(cstrptr, fptr)
  fstrptr => fptr(1:nchars)
end subroutine c_f_strpointer1
[software@nemesis ~/GITHUB-ECCC/librmn/build : (dev_alpha *%|u=)]
 > flang-new -c dynamic.F90
error: Semantic errors in dynamic.F90
./dynamic.F90:11:29: error: FPTR= argument to C_F_POINTER() may not have a deferred type parameter
    call c_f_pointer(cstrptr, fptr)
                              ^^^^
========================================
this compiles with gnu C/intel C/AMD aoccc C/nvidia C

**Comment by klausler** [comment]
This is a valid error and some other compilers catch it as well.  The length of `fptr` cannot be determined.

The declaration `character(C_CHAR), ...` is also a likely error, as it sets the *length* of `cstrarray` to whatever the character kind code `C_CHAR` might be (usually 1).  You probably want `character(kind=C_CHAR), ...`.
