### ISSUE TITLE
[OpenMP] Pass the -DPython3_EXECUTABLE flag to the runtimes build 

### ISSUE THREAD

**Issue by kkwli** [llvm/llvm-project#98265]
In the build environment, `python` is in a nondefault location. The `-DPython3_EXECUTABLE` flag is specified in the cmake command. Somehow the `find_package(Python3 ...)` function call in `runtimes/CMakeLists.txt` returns the `python` in the default location instead of the desired one. The build fails at building the LIT tests.

https://github.com/llvm/llvm-project/blob/66470112d6e00832cae2970fb56f491cd5f7b14a/runtimes/CMakeLists.txt#L170-L171

**Comment by shiltian** [comment]
I think you will need to use `Python3_ROOT` CMake variable to tell CMake how to find the package. See [here](https://cmake.org/cmake/help/latest/module/FindPython3.html#hints) for more information.
