### ISSUE TITLE
[RISCV][MC] How can I get MCInst operand size?

### ISSUE THREAD

**Issue by tianboh** [llvm/llvm-project#98279]
Hi there, I don't know if it is right to post here, but I can't find any answer from google, so i am asking here.

I am working on a disassembling project([llvm-mctoll](https://github.com/microsoft/llvm-mctoll)) recently, and found MCInst quite useful. I need to disassemble the RISCV bytecode to LLVM IR, so basically what i am going to do first is to reconstruct function signature. Each register which is not defined before use is treated as parameter register.  However, unlike x86 which can distinguish the register size by its prefix (%rax, %eax, %ax, etc,.), RISCV seems use the whole register.

Based on the RISCV Spec base ISA opcode map, I classified the instructions to three types: Load/Store, Algo, Algo-Op-Imm-32. For load/store, the instruction will tell the size it processes. For Algo, the instruction will use the whole register based on its ISA. For algo-op-imm-32, which is basically ISA 64G, it uses 32 bit of registers.

However, thing gets complicated when taking C extension into consideration. I cannot easily classify the instructions like before. I am wondering if I can get any access size information from `MCInst`, or `MachineInstr` classes? I know there is a `Operand` class and `MachineOperand` class, but like I said, some instructions record the size thet're going to access(load/store), this size information should be found in the instructions.

Please correct me if I am wrong or missing anything, any suggestions are welcome!

**Comment by michaelmaitland** [comment]
Maybe [`MachineRegisterInfo::getType`](https://llvm.org/doxygen/classllvm_1_1MachineRegisterInfo.html#a5dc0a32516ce31f495b440d47287028b) is what you are looking for. Once you have a LLT type, you can use the [`LLT::getSizeInBits`](https://llvm.org/doxygen/classllvm_1_1LLT.html#a956ffd0de93798f523683b447646dd92) or [`getSizeInBytes`](https://llvm.org/doxygen/classllvm_1_1LLT.html#ae456a811703836ee5d9e32c3e51a15b6) functions.

**Comment by topperc** [comment]
> However, thing gets complicated when taking C extension into consideration.

Every C instruction should have a corresponding non-C instruction. The only compressed instructions that don't belong to the Zcmp and Zcmt extensions.

**Comment by topperc** [comment]
> Maybe [MachineRegisterInfo::getType](https://llvm.org/doxygen/classllvm_1_1MachineRegisterInfo.html#a5dc0a32516ce31f495b440d47287028b) is what you are looking for. Once you have a LLT type, you can use the [LLT::getSizeInBits](https://llvm.org/doxygen/classllvm_1_1LLT.html#a956ffd0de93798f523683b447646dd92) or [LLT::getSizeInBytes](https://llvm.org/doxygen/classllvm_1_1LLT.html#ae456a811703836ee5d9e32c3e51a15b6) functions.

Isn't `MachineRegisterInfo::getType` only relevant inside of the GlobalISel passes?

**Comment by topperc** [comment]
I see [llvm-mctoll](https://github.com/microsoft/llvm-mctoll)) says it supports ARM32. ARM32 has only 1 size of register. How does llvm-mctoll recover the function signature for it?

**Comment by tianboh** [comment]
@topperc  Thank you for your reply and suggestion! In fact, this project is developed by two teams(one for x86 and one for ARM). The ARM group use [default type for the parameters](https://github.com/microsoft/llvm-mctoll/blob/master/ARM/ARMFunctionPrototype.cpp#L134). Though there is an assignment when `TyArr[Idx] == nullptr`, but the previous assignment is still default type. This default type here is pointer size, which is like a super class for all type size.

**Comment by tianboh** [comment]
> @topperc Thank you for your reply and suggestion! In fact, this project is developed by two teams(one for x86 and one for ARM). The ARM group use [default type for the parameters](https://github.com/microsoft/llvm-mctoll/blob/master/ARM/ARMFunctionPrototype.cpp#L134). Though there is an assignment when `TyArr[Idx] != nullptr`, but the previous assignment is still default type. This default type here is pointer size, which is like a super class for all type size.

**Comment by tianboh** [comment]
> > @topperc Thank you for your reply and suggestion! In fact, this project is developed by two teams(one for x86 and one for ARM). The ARM group use [default type for the parameters](https://github.com/microsoft/llvm-mctoll/blob/master/ARM/ARMFunctionPrototype.cpp#L134). Though there is an assignment when `TyArr[Idx] != nullptr`, but the previous assignment is still default type. This default type here is pointer size, which is like a super size for all type size.

**Comment by tianboh** [comment]
> > However, thing gets complicated when taking C extension into consideration.
> 
> Every C instruction should have a corresponding non-C instruction. The only compressed instructions that don't have a non-compressed version belong to the Zcmp and Zcmt extensions.

That's right, I am trying to uncompress the C instructions to their base ISA. However, this is quite elegent beacuse I need to handle EVERY instructions listed in the RVC opcode instructions using bit calculation.

Picture from [RISCV Spec](https://drive.google.com/file/d/1uviu1nH-tScFfgrovvFCrj7Omv8tFtkp/view)
![screenshot-20240711-095017](https://github.com/llvm/llvm-project/assets/54729592/85e54633-8e9f-4342-ba3c-1a104d713440)

I am doing something like
```C
//omitted enum class declaration and some helper function.
riscv::BaseOpcode
RISCV64MachineInstructionRaiser::getInst16Type(ArrayRef<uint8_t> Bytes) {
  uint16_t Inst = decode16(Bytes);
  uint16_t MaskLo = 3;     // 0000 0000 0000 0011
  uint16_t MaskHi = 57344; // 1110 0000 0000 0000
  // First check inst[1:0]
  switch (Inst & MaskLo) {
  case 0:
    switch ((Inst & MaskHi) >> 13) {
    case 0:
      return RaiseMap[COpcode::ADDI4SPN];
    case 1:
      return RaiseMap[COpcode::FLD];
    case 2:
      return RaiseMap[COpcode::LW];
    case 3:
      return RaiseMap[COpcode::LD];
    blah blah blah
    }
}
```

**Comment by topperc** [comment]
> > > However, thing gets complicated when taking C extension into consideration.
> > 
> > 
> > Every C instruction should have a corresponding non-C instruction. The only compressed instructions that don't have a non-compressed version belong to the Zcmp and Zcmt extensions.
> 
> That's right, I am trying to uncompress the C instructions to their base ISA. However, this is not elegent beacuse I need to handle EVERY instructions listed in the RVC opcode instructions using bit calculation.
> 
> Picture from [RISCV Spec](https://drive.google.com/file/d/1uviu1nH-tScFfgrovvFCrj7Omv8tFtkp/view) ![screenshot-20240711-095017](https://private-user-images.githubusercontent.com/54729592/347653278-85e54633-8e9f-4342-ba3c-1a104d713440.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NjQxODAsIm5iZiI6MTcyMDY2Mzg4MCwicGF0aCI6Ii81NDcyOTU5Mi8zNDc2NTMyNzgtODVlNTQ2MzMtOGU5Zi00MzQyLWJhM2MtMWExMDRkNzEzNDQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDAyMTEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1OGU2Mzc1Mjc3NTg1OTg4YTg0NWUzN2RmODAxZDg4MTQzY2JmY2Y4MmY1NGUwOTQ1NDc0ZDY2ZjVkNTJlZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EdjUcVdrJhHLuVXSlKWpIq6LVmtuJ5Im1AimN_Ed5Ak)
> 
> I am doing something like
> 
> ```c
> //omitted enum class declaration and some helper functions.
> riscv::BaseOpcode
> RISCV64MachineInstructionRaiser::getInst16Type(ArrayRef<uint8_t> Bytes) {
>   uint16_t Inst = decode16(Bytes);
>   uint16_t MaskLo = 3;     // 0000 0000 0000 0011
>   uint16_t MaskHi = 57344; // 1110 0000 0000 0000
>   // First check inst[1:0]
>   switch (Inst & MaskLo) {
>   case 0:
>     switch ((Inst & MaskHi) >> 13) {
>     case 0:
>       return RaiseMap[COpcode::ADDI4SPN];
>     case 1:
>       return RaiseMap[COpcode::FLD];
>     case 2:
>       return RaiseMap[COpcode::LW];
>     case 3:
>       return RaiseMap[COpcode::LD];
>     blah blah blah
>     }
> }
> ```

Can you use `RISCVRVC::uncompress` from llvm/lib/Target/RISCV/MCTargetDesc/RISCVBaseInfo.cpp

**Comment by tianboh** [comment]
> > > > However, thing gets complicated when taking C extension into consideration.
> > > 
> > > 
> > > Every C instruction should have a corresponding non-C instruction. The only compressed instructions that don't have a non-compressed version belong to the Zcmp and Zcmt extensions.
> > 
> > 
> > That's right, I am trying to uncompress the C instructions to their base ISA. However, this is not elegent beacuse I need to handle EVERY instructions listed in the RVC opcode instructions using bit calculation.
> > Picture from [RISCV Spec](https://drive.google.com/file/d/1uviu1nH-tScFfgrovvFCrj7Omv8tFtkp/view) ![screenshot-20240711-095017](https://private-user-images.githubusercontent.com/54729592/347653278-85e54633-8e9f-4342-ba3c-1a104d713440.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NjQxODAsIm5iZiI6MTcyMDY2Mzg4MCwicGF0aCI6Ii81NDcyOTU5Mi8zNDc2NTMyNzgtODVlNTQ2MzMtOGU5Zi00MzQyLWJhM2MtMWExMDRkNzEzNDQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDAyMTEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1OGU2Mzc1Mjc3NTg1OTg4YTg0NWUzN2RmODAxZDg4MTQzY2JmY2Y4MmY1NGUwOTQ1NDc0ZDY2ZjVkNTJlZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EdjUcVdrJhHLuVXSlKWpIq6LVmtuJ5Im1AimN_Ed5Ak)
> > I am doing something like
> > ```c
> > //omitted enum class declaration and some helper functions.
> > riscv::BaseOpcode
> > RISCV64MachineInstructionRaiser::getInst16Type(ArrayRef<uint8_t> Bytes) {
> >   uint16_t Inst = decode16(Bytes);
> >   uint16_t MaskLo = 3;     // 0000 0000 0000 0011
> >   uint16_t MaskHi = 57344; // 1110 0000 0000 0000
> >   // First check inst[1:0]
> >   switch (Inst & MaskLo) {
> >   case 0:
> >     switch ((Inst & MaskHi) >> 13) {
> >     case 0:
> >       return RaiseMap[COpcode::ADDI4SPN];
> >     case 1:
> >       return RaiseMap[COpcode::FLD];
> >     case 2:
> >       return RaiseMap[COpcode::LW];
> >     case 3:
> >       return RaiseMap[COpcode::LD];
> >     blah blah blah
> >     }
> > }
> > ```
> 
> Can you use `RISCVRVC::uncompress` from llvm/lib/Target/RISCV/MCTargetDesc/RISCVBaseInfo.cpp

Thank you for the insight! Unfortunately, I can't because the LLVM-MCTOLL is currently hooked with LLVM 15, and uncompress is not added back then(I am trying to update this project to fit with latest LLVM as well). However, there is a generated uncompress function in build/lib/Target/RISCV/RISCVGenCompressInstEmitter.inc, which I found quite useful.

Even though I can uncompress this instruction, I still need to figure out the size of its operand.

**Comment by topperc** [comment]
> @topperc Thank you for your reply and suggestion! In fact, this project is developed by two teams(one for x86 and one for ARM). The ARM group use [default type for the parameters](https://github.com/microsoft/llvm-mctoll/blob/master/ARM/ARMFunctionPrototype.cpp#L134). Though there is an assignment when TyArr[Idx] != nullptr, but the previous assignment is still default type. This default type here is pointer size, which is like a super size for all type size.

Why can't you use pointer size for RISC-V?

> For now, I am decoding the raw bytes and then determine the size by its type(Store/Load, Alg, Alg-Op-32). Sadly, MCInst do not help in this process.

How is size determine for ARM? ARM also has one size of register, but has byte, half, and word loads/stores.

**Comment by tianboh** [comment]
> Why can't you use pointer size for RISC-V?
Using pointer size for RISC-V is totally fine, but I guess accurate size information can provide more space for LLVM IR optimization later. Please correct me if I am wrong, I am not quite familiar with LLVM IR optimization yet. Intuitively, some hardware/ISA may support handling two operands on the same register(say two int32 on a 64-bit register, like SIMD), but if it is translated as a 64-bit, it loses this opportunity.

> How is size determine for ARM? ARM also has one size of register, but has byte, half, and word loads/stores.
That's a good point, I just skimmed the function prototype part. I will check the instruction raise part and see if there are some ways.

**Comment by tianboh** [comment]
Finally, I decided to use MCInst opcode, though there are many cases to merge, I think this may be the best way to handle it. Anyway, thank you all for the suggestions!
