### ISSUE TITLE
cmake should build libLTO and the gold-plugin.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#9828]
|  |  |
| --- | --- |
| Bugzilla Link | [9456](https://llvm.org/bz9456) |
| Version | trunk |
| OS | Linux |
| Blocks | llvm/llvm-project#9693  |
| Attachments | [cmake configuration to build the gold-plugin.](https://user-images.githubusercontent.com/60944935/143742863-6d33c90d-3f9c-43ed-be32-36896bcb70e7.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @oscarfv |

## Extended Description 
Currently cmake does ignore libLTO and the gold-plugin.

**Comment by arsenm** [comment]
cmake is now the only build so this is done or doesn't matter anymore
