### ISSUE TITLE
[NSAN] request of improvement: allow not to exit after first error 

### ISSUE THREAD

**Issue by VinInn** [llvm/llvm-project#98300]
Currently the numerical-sanitizer exits when the first "error" is found.
```-fno-sanitize-trap=all -fsanitize-recover=all``` have no effect.
In particular for the numerical-sanitizer it would be useful to be able to get the full list of errors encountered in a program as some are not really critical (and difficult to fix) while others may be more serious.

**Comment by chestnykh** [comment]
Can i work on this improvement?

**Comment by alexander-shaposhnikov** [comment]
@VinInn NSAN_OPTIONS=halt_on_error=0 might work, e.g.
`NSAN_OPTIONS=halt_on_error=0 ./hello_world.exe`
