### ISSUE TITLE
P2985R0 A type trait for detecting virtual base classes

### ISSUE THREAD

**Issue by Endilll** [llvm/llvm-project#98310]
This paper introduces `std::is_virtual_base_of` trait, and was voted into the working draft in St. Louis.
Like other traits, we're planning to support this with a `__is_virtual_base_of` builtin.
Tagging @STL, @jwakely, and @ldionne to make sure they are fine with this spelling, and hopefully to prevent implementation divergence on the name.

**Comment by Endilll** [comment]
@StephanTLavavej

**Comment by ldionne** [comment]
The name LGTM. For what it's worth, I would have preferred if all of the type trait builtins started with `__builtin` (eg `__builtin_is_signed(...)`), but at this point we should just be consistent with everything else.

**Comment by StephanTLavavej** [comment]
Name LGTM too.

**Comment by ldionne** [comment]
@jwakely Would it be controversial to propose that we support both the `__builtin_XXXXX` spelling and the normal spelling in compilers for a while, and perhaps document that we want to move away from the non-`__builtin_XXXXX` spellings? If we started now, we could be in a better world just a few years from now.

**Comment by jwakely** [comment]
I asked, and the C++ maintainers would be happy with that direction.

**Comment by AaronBallman** [comment]
Thanks! I think that's a reasonable approach.

**Comment by Endilll** [comment]
Given that the decision to use `__builtin` prefix was made after 19 branch date, are there objections to keep the changes related to this to Clang 20?

**Comment by cor3ntin** [comment]
`__builtin_is_virtual_base_of` is Clang 20 material anyway, and the names of previously existing type traits was already agreed upon so we can't change them without being disruptive.

**Comment by Endilll** [comment]
Technically we can still change `__is_layout_compatible` name.

**Comment by jwakely** [comment]
GCC already defines `__is_layout_compatible` and libstdc++ uses `__has_builtin(__is_layout_compatible)` so if Clang adds it with that name, it will Just Work :tm: with existing releases of libstdc++. If you add it with the new name, it won't work unless/until libstdc++ transitions to using the new form of names (which won't happen until GCC starts supporting them with both names).

**Comment by Endilll** [comment]
Thank you for letting us know. This is strong enough argument to keep `__is_layout_compatible` spelling.

**Comment by ldionne** [comment]
This seems to be the consensus anyway, but I think we should simply adopt the new `__builtin_foo` spelling for patches that haven't landed yet. I wouldn't try to rush and change the name of any builtin that we've already landed in the tree but "not released yet". That doesn't seem to be worth it.
