### ISSUE TITLE
[libc] Create a separate proxy header for math-function-macros.h

### ISSUE THREAD

**Issue by lntue** [llvm/llvm-project#98393]
Currently, math function macros are included via the proxy header `hdr/math_macros.h`.  We should create a separate proxy header `hdr/math_function_macros.h` for it to be separated from `hdr/math_macros.h`.

**Comment by changkhothuychung** [comment]
I would like to take this issue if it is available, thanks!

**Comment by changkhothuychung** [comment]
@lntue Ln
what functions declarations / defintions will go into the new file `hdr/math_function_macros.h` ?

**Comment by lntue** [comment]
> @lntue Ln what functions declarations / defintions will go into the new file `hdr/math_function_macros.h` ?

Currently `hdr/math_macros.h` includes both headers in full build modes:
```
#include "include/llvm-libc-macros/math-function-macros.h"
#include "include/llvm-libc-macros/math-macros.h"
```
https://github.com/llvm/llvm-project/blob/main/libc/hdr/math_macros.h#L14

We should move the `#include "include/llvm-libc-macros/math-function-macros.h"` to a separate proxy header `hdr/math_function_macros.h` and update the header includes and dependency accordingly.
