### ISSUE TITLE
'noinline' attribute is ignored

### ISSUE THREAD

**Issue by Sainan** [llvm/llvm-project#98458]
- GCC-style attribute: https://godbolt.org/z/qhT7zhM4e
- MSVC-style attribute: https://godbolt.org/z/xo5eajn3b

Notice how in both cases, `main` does not call `my_func`.

**Comment by AaronBallman** [comment]
Same happens even with `[[clang::noinline]]` used at the statement level: https://godbolt.org/z/935sM1j14

**Comment by nikic** [comment]
noinline prevents inlining only, not other interprocedural optimizations (probably IPSCCP here). I'm going to close this as a duplicate of existing issues like https://github.com/llvm/llvm-project/issues/45808 and https://github.com/llvm/llvm-project/issues/40819. There is a very extensive body of existing discussions on the noinline/noipa distinction.
