### ISSUE TITLE
[clang] Feature request: Allow qualified names in namespace definitions

### ISSUE THREAD

**Issue by ay0ks** [llvm/llvm-project#98463]
Example code:
Before:
```cpp
namespace fx
{
    namespace multidimensional
    {
        namespace details
        {
            // it can be even more nested than this
        }

        class test_class
        {};
    }
}
```
After:
```cpp
namespace fx::multidimensional
{
    namespace details
    {
        // nothing more than just a qualified name
    }

    class test_class
    {};
}
```
It makes code a bit more readable (a bit only in this example, it may make more sense in bigger code bases.)

https://en.cppreference.com/w/cpp/language/namespace

This is against the language standard, but can be implemented as a compiler extension.

Thanks.

**Comment by cor3ntin** [comment]
This is already supported (since C++17 and as an extension in older language modes)
Look at the (8) syntax in the link you posted.

Cheers!

**Comment by ay0ks** [comment]
> This is already supported (since C++17 and as an extension in older language modes) Look at the (8) syntax in the link you posted.
> 
> Cheers!

Oh, I missed that. Thanks!
