### ISSUE TITLE
[LLVM][RISC-V] Use AUIPC instruction in conjunction with more than one JALR instruction where possible

### ISSUE THREAD

**Issue by RamNalamothu** [llvm/llvm-project#98470]
The sample code in https://godbolt.org/z/ad4qn1xTa has repeated calls to function _foo_ and looking at the assembly generated by LLVM trunk, it seems the address calculation of _foo_ (AUIPC) can be re-used with all the calls to _foo_ (JALR) but the compiler is not able to do that. And this leads to increase in code size which can be avoided.

I found that this is happening because RISC-V uses _PseudoCALL_ which is expanded into the AUIPC and JALR instruction pair very late in the MCCodeEmitter. Here are the [patch](https://github.com/llvm/llvm-project/commit/98f9389f65e630a7243f9c99717009107758d492) which made this change and the llvm-dev [thread](https://lists.llvm.org/pipermail/llvm-dev/2018-July/124542.html) having @asb's comments on late expansion of _PseudoCALL_.

Since @asb says _There may be better ways of structuring the current logic to achieve that aim of course_ and the RISC-V psABI says:

_The AUIPC instruction is used in conjunction with one or more I-Type instructions (add immediate or load) with R_RISCV_PCREL_LO12_I relocations or S-Type instructions (store) with R_RISCV_PCREL_LO12_S relocations._

_Note the compiler emitted instructions for PC-relative symbol addresses are not necessarily sequential or in pairs. There is a constraint is that the instruction with the R_RISCV_PCREL_LO12_I or R_RISCV_PCREL_LO12_S relocation label points to a valid HI20 PC-relative relocation pointing to the symbol._

Does it make sense to revisit the implementation/handling of _PseudoCALL_ and change it so that the above-mentioned code size increase can be avoided? If yes, I can take up this work.

CC: @topperc @jrtc27

**Comment by topperc** [comment]
I think reusing the AUIPC would violate the contract with the linker for the R_RISCV_CALL relocation. That relocation can only be used when the AUIPC and JALR are adjacent. The linker uses this relocation to relax the AUIPC+JALR to a single instruction if the destination is near enough.

> The AUIPC instruction is used in conjunction with one or more I-Type instructions (add immediate or load) with R_RISCV_PCREL_LO12_I relocations or S-Type instructions (store) with R_RISCV_PCREL_LO12_S relocations.

> Note the compiler emitted instructions for PC-relative symbol addresses are not necessarily sequential or in pairs. There is a constraint is that the instruction with the R_RISCV_PCREL_LO12_I or R_RISCV_PCREL_LO12_S relocation label points to a valid HI20 PC-relative relocation pointing to the symbol.

This text seems to be referring to loads, stores, and address calculations for accessing global variables. Calls are different and use a different relocation.

**Comment by jrtc27** [comment]
Exactly. It is baked into the ABI that consecutive AUIPC+JALR is the canonical sequence for a function call.

**Comment by asb** [comment]
Yes, I think we can't reuise the AUIPC for the reasons above. Are you happy we close this @RamNalamothu?

**Comment by RamNalamothu** [comment]
Thanks for the comments. I should have done my homework better before posting this.

Yes, closing it.

However, I would appreciate any suggestions on other ways to address the code size increase for the sample code scenario I mentioned in this issue report.

**Comment by jrtc27** [comment]
Linker relaxation may automatically help you here if your binary is small
