### ISSUE TITLE
Portability problem in slave build step

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#9850]
|  |  |
| --- | --- |
| Bugzilla Link | [9478](https://llvm.org/bz9478) |
| Version | trunk |
| OS | Windows XP |
| Attachments | [zorg patch](https://user-images.githubusercontent.com/60944935/143742875-030b5c92-2b63-4895-b447-f5bf02a70da5.gz) |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 

Windows machines don't generally support pwd.  The enclosed patch needs some more testing, but wanted you to have it now.

**Comment by arsenm** [comment]
Old build issue
