### ISSUE TITLE
[clang] Missing predefined macroses?

### ISSUE THREAD

**Issue by chestnykh** [llvm/llvm-project#98506]
I've noticed that for x86-64 gcc (i use gcc-14.1.1) defines
`__SIG_ATOMIC_MIN__` to `-__SIG_ATOMIC_MAX__ - 1`
and
`__SIG_ATOMIC_TYPE__` to `int`
when clang doesn't define these macroses.
clang (trunk) defines only `__SIG_ATOMIC_MAX__` and `__SIG_ATOMIC_WIDTH__` (which are also defined by gcc).
Should we define `__SIG_ATOMIC_MIN__` and `__SIG_ATOMIC_TYPE__` for more compatibility with gcc?

**Comment by chestnykh** [comment]
CC @ChuanqiXu9 @AaronBallman @Endilll @shafik

**Comment by chestnykh** [comment]
Seems that gcc defines all __SIG_ATOMIC_* marcoses for all targets where sig_atomic_t is supported.

**Comment by AaronBallman** [comment]
Clang provides the standards-required macros in stdint.h as expected: https://github.com/llvm/llvm-project/blob/dd44003f579cc0f3538b58ef2cba2b6870598bc0/clang/lib/Headers/stdint.h#L919 so in terms of conformance we're fine.

In terms of compatibility with GCC on the predefined macros, it wouldn't hurt, but it doesn't seem like a priority given that they're not really used in the wild: https://sourcegraph.com/search?q=context:global+__SIG_ATOMIC_TYPE__+-file:.*gcc.*+-file:.*gnu.*+-file:.*predefs.*+-file:.*lint.*+-file:CMakeCache%5C.txt&patternType=keyword&sm=0

**Comment by chestnykh** [comment]
> Clang provides the standards-required macros in stdint.h as expected:
> 
> https://github.com/llvm/llvm-project/blob/dd44003f579cc0f3538b58ef2cba2b6870598bc0/clang/lib/Headers/stdint.h#L919
> so in terms of conformance we're fine.
> 
> In terms of compatibility with GCC on the predefined macros, it wouldn't hurt, but it doesn't seem like a priority given that they're not really used in the wild: https://sourcegraph.com/search?q=context:global+__SIG_ATOMIC_TYPE__+-file:.*gcc.*+-file:.*gnu.*+-file:.*predefs.*+-file:.*lint.*+-file:CMakeCache%5C.txt&patternType=keyword&sm=0

Thanks for the response. The issue can be closed i think
