### ISSUE TITLE
[HLSL] Move resource attributes to resource's handles instead of the class itself

### ISSUE THREAD

**Issue by bogner** [llvm/llvm-project#98556]
Currently resource attributes sit on the resource class itself, like so:
```hlsl
[[hlsl::resource(...)]]
[[hlsl::resource_class(uav)]]
template <typename T> class RWBuffer {
  // ...
};
```

We'd like the attributes to be attached to the resource's internal handle instead as we move towards the "intangible" handle type:
```hlsl
template <typename T> class RWBuffer {
  [[hlsl::resource(...)]]
  [[hlsl::resource_class(uav)]]
  __hlsl_resource_t Handle;
};
```

Note that this is *not* blocked by the introduction of the intangible handle type - resources already have a `void *Handle` member, and we can simply attach these attributes there.

AC:
- All of the HLSL resource attributes are attached to the handle
- Diagnostic and backend logic that refers to these attributes continues to work
- Existing tests are updated to conform to this approach
- Utility functions added to find information about resource types based on these attributes

**Comment by damyanp** [comment]
@bob80905 - this may be worth doing before implementing the diagnostics?
