### ISSUE TITLE
Implement C++26 P2893 "Variadic friends"

### ISSUE THREAD

**Issue by zyn0217** [llvm/llvm-project#98587]
Note that I'm self-assigning it because I started to [work on it](https://github.com/zyn0217/llvm-project/commits/variadic-friends/) a few weeks ago. I'll try to find some time to complete it, but if someone else has beaten me to it, let me know and I'll give up my implementation.

**Comment by Sirraide** [comment]
> I'll try to find some time to complete it, but if someone else has beaten me to it, let me know and I'll give up my implementation

@zyn0217 I have some time and was going to look into this anyway, so if you’re currently not actively working on or planning to work on it, I could take over from or based on what you have so far and then list you as a co-author.

**Comment by zyn0217** [comment]
@Sirraide no problem, thanks!

My patch is at its very infant stage so feel free to pick it up or rewrite the whole on your own.
