### ISSUE TITLE
CTAD: implement DR2707 trailing requires-clause should be allowed in deduction guides

### ISSUE THREAD

**Issue by hokein** [llvm/llvm-project#98595]
https://cplusplus.github.io/CWG/issues/2707.html

**Comment by shafik** [comment]
Is this a proper example: https://godbolt.org/z/1jvffM3d6

```cpp
template<typename...>
struct A { 
    A(bool);
};

template <typename...>
A(bool) -> A<> requires true;

```

**Comment by hokein** [comment]
I think we are targeting the case `A(bool) requires true -> A<>;`. None of the compilers support it currently https://godbolt.org/z/ojYcc783K.

The case `A(bool) -> A<> requires true;` is illegal according to the [standard grammar](https://eel.is/c++draft/temp.deduct.guide#nt:deduction-guide), as the `require-clause` cannot be attached at the end of the deduction guide.

**Comment by zygoloid** [comment]
The grammar in the standard is wrong. Someone should file a core issue for that. The *requires-clause* should be at the end.

**Comment by zygoloid** [comment]
Filed as core issue: https://github.com/cplusplus/CWG/issues/576

**Comment by hokein** [comment]
ah, thanks for the clarification.
