### ISSUE TITLE
[flang] preprocessor issue for macro consisting of `!` followed by &

### ISSUE THREAD

**Issue by DavidTruby** [llvm/llvm-project#98651]
When we have a macro that consists of `!` and that macro is followed by `&` to indicate a line continuation, flang-new processes the line continuation first. Other compilers process the macro first and therefore ignore the line continuation. For example:

```
#define MAC !
MAC&
subroutine test
end subroutine test
```
processes on flang-new to:
```
      MACsubroutine test

      end subroutine test
```
but on gfortran to:
```
!&
subroutine test
end subroutine test
```

This causes quantum-espresso to fail to compile as it contains usage like this:
https://github.com/QEF/q-e/blob/de3035747f5d8f2ec9a67869827341ebb43f5b12/CPV/src/potentials.f90#L387
where DEV_ACC is defined as `!!!`

**Comment by DavidTruby** [comment]
In the case of quantum espresso this results in the line after the macro being commented out, as it doesn't start in the first column so the macro _does_ get processed into `!!!`

**Comment by klausler** [comment]
Put a space between `MAC` and the following `&` and it'll work today.

https://github.com/llvm/llvm-project/pull/98684 fixes this exact case.

**Comment by pawosm-arm** [comment]
Can build quantum espresso with recent flang-new, and also the example from this task is preprocessed properly, so I'm closing this one.
