### ISSUE TITLE
er/preprocessor.cpp:389:39: style: Obsolete function 'std::asctime' called

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#98720]
Source code is

    if (std::string time{std::asctime(std::localtime(&modTime))};

but man asctime says "Marked obsolete in POSIX.1-2008"

2008 is 16 years ago now. It might be a good time to upgrade to strftime.

**Comment by EugeneZelenko** [comment]
@dcb314: Please fix file path in title.

**Comment by klausler** [comment]
The timestamp format of the GNU Fortran extension being implemented here is documented as being the output of `asctime`.  So I use `asctime` here.  Thanks for the lesson in subtraction, though.

**Comment by dcb314** [comment]
> So I use `asctime` here. 

I think this is what the static tool is complaining about.
It's an obsolete function and so shouldn't be used.

>Thanks for the lesson in subtraction, though.

I am not sure what this means ?
