### ISSUE TITLE
clang/lib/Lex/PPMacroExpansion.cpp: 2 * calls to obsolete function asctime

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#98724]
Static analyser cppcheck says:

1.

trunk/clang/lib/Lex/PPMacroExpansion.cpp:1728:16: style: Obsolete function 'asctime' called. It is recommended to use 'strftime' instead. [asctimeCalled]

Source code is

     Result = asctime(TM);

2.

trunk/clang/lib/Lex/PPMacroExpansion.cpp:1738:18: style: Obsolete function 'asctime' called. It is recommended to use 'strftime' instead. [asctimeCalled]

Source code is

      Result = asctime(TM);

But "man asctime" says:

    Marked obsolete in POSIX.1-2008 (recommending strftime(3)).

2008 is 16 years ago.

**Comment by shafik** [comment]
This does seem like a valid concern: https://wiki.sei.cmu.edu/confluence/display/c/MSC33-C.+Do+not+pass+invalid+data+to+the+asctime%28%29+function

Probably not high priority but perhaps a good first issue, I don't see any obvious traps switching to `strftime` here but maybe I am missing something CC @AaronBallman

**Comment by AaronBallman** [comment]
Agreed, this should be a straightforward refactoring, I'm not aware of any gotchas.

**Comment by yichi170** [comment]
I'm interested in working on this issue. How can I get assigned?

**Comment by yichi170** [comment]
Hi @AaronBallman, I have submitted the PR. Could you please help review it? Thank you!
