### ISSUE TITLE
[aarch64] use sabd to optimize the float abs

### ISSUE THREAD

**Issue by vfdff** [llvm/llvm-project#98733]
* test : https://gcc.godbolt.org/z/Gohebqbqe
```
float foo (float a, float b) {
    return abs (a - b);
}
```

the aarch64 target has **sabd** to address the **abs**, and S registers is alias to V registers,  so would it possible to use **sabd** address the scalar float type of abs ?

**Comment by davemgreen** [comment]
Do you mean could it use fabd?
Both compiler seem to use it under -Ofast or if using __builtin_fabs: https://gcc.godbolt.org/z/c3a677ds5

The problem is likely nan's and signed-zeroes.

**Comment by vfdff** [comment]
Yes, thanks. I see it already supported with -Ofast
