### ISSUE TITLE
[instcombine] select of symmetric selects

### ISSUE THREAD

**Issue by sftlbcn** [llvm/llvm-project#98800]
https://alive2.llvm.org/ce/z/4QAm4K
```
define i32 @src(i32 %a, i32 %b, i1 %c1, i1 %c2) {
  %sel1 = select i1 %c1, i32 %a, i32 %b
  %sel2 = select i1 %c1, i32 %b, i32 %a
  %ret = select i1 %c2, i32 %sel1, i32 %sel2
  ret i32 %ret
}

define i32 @tgt(i32 %a, i32 %b, i1 %c1, i1 %c2) {
  %xor = xor i1 %c1, %c2
  %ret = select i1 %xor, i32 %b, i32 %a
  ret i32 %ret
}
```

**Comment by dtcxzyw** [comment]
> This does not really result in improvements in codegen so I'm closing this.

This fold improves the codegen on X86/AArch64/RISC-V. See https://godbolt.org/z/hY9z8GGvf.
Anyway, it always enables more folds in the middle-end.

Would you like to continue with this?
