### ISSUE TITLE
CSA (Clang Static Analyzer) incorrectly treat as a return for calling of noreturn functions.

### ISSUE THREAD

**Issue by farta1986** [llvm/llvm-project#98803]
When we're calling a noreturn function (both C++11 [[noreturn]] attribute and GNU C extension __attribute__((__noreturn__)) repro this issue), we mean this is an exit point of the entire program, not just this function call. However, it looks like CSA treat it as an end of current function call.

Consider the following C++ code:

```cpp
[[noreturn]]void crash();

void set_value(int* a, bool flag)
{
    if (!flag)
        crash();
    *a = 10;
}

int foo(bool flag)
{
    int a;
    set_value(&a, flag);
    return a; // CSA reports a not initialized.
}
```

CSA reports a is not initialized when used as a return value. It is due to in function set_value, call to crash was treated as a return from set_value, not an exit of the entire program. The explode graph shows it.

I guess it may be related to CFG, as CFGs only describe control flow within a function, so it may be lack of information to distinguish an exit of a function call from an exit of the program.

**Comment by steakhal** [comment]
I think this is a valid finding in case the flag value is false. I bet the bug report has a note like "assuming flag is false".
Consequently, I think it works as expected.

**Comment by farta1986** [comment]
> I think this is a valid finding in case the flag value is true. I bet the bug report has a note like "assuming flag is true". Consequently, I think it works as expected.
> 
> We make this claim under the assumpzion of no dead code, such that why would foo have a flag parameter if it would be always of a constant false - which would make the if branch effectively dead.

It doesn't have the note.
![image](https://github.com/user-attachments/assets/f311f29b-893e-436d-8e6b-9f69924405eb)
[explode_graph.pdf](https://github.com/user-attachments/files/16227976/explode_graph.pdf)

But I can see the issue is in the false branch in the explode graph. CSA just return to the caller foo when it runs into a noreturn call.

**Comment by steakhal** [comment]
Hmm, ill have a look tomorrow.

**Comment by steakhal** [comment]
This issue does not reproduce on my end: https://godbolt.org/z/zxxjEe9cj

What checkers did you exactly enable? What exact clang version did you use?

**Comment by farta1986** [comment]
> This issue does not reproduce on my end: https://godbolt.org/z/zxxjEe9cj
> 
> What checkers did you exactly enable? What exact clang version did you use?

This issue is about CSA analyzer core, not AST parser. I’m not familiar with compiler explorer. Does it provide CSA checkers?
I believe at least all clang version between clang 14 & clang 18 has this issue. My environment with clang 18 is a fedora 40 box. Steps are:
1. Fedora 40 with llvm/clang 18 installed via fedora’s dnf repository.
2. Create a cpp source file with the repro code.
3. Use clang installed to reproduce this issue:
 clang -cc1 -w -analyze -analyzer-checker=core.uninitialized.UndefReturn 1.cc
4. We’ll see the warning from UndefReturn checker.
5. If you want you can use debug.ViewExplodedGraph checker to dump the exploded graph and use dot to convert it to a pdf file. The result should be identical to the one I once pasted.
![image](https://github.com/user-attachments/assets/65977b09-84f2-4bd4-8dd4-2d3cd64d4508)

**Comment by farta1986** [comment]
> > > This issue does not reproduce on my end: https://godbolt.org/z/zxxjEe9cj
> > > What checkers did you exactly enable? What exact clang version did you use?
> > 
> > 
> > This issue is about CSA analyzer core, not AST parser. I’m not familiar with compiler explorer. Does it provide CSA checkers? I believe at least all clang version between clang 14 & clang 18 has this issue. My environment with clang 18 is a fedora 40 box. Steps are:
> > ```
> > 1. Fedora 40 with llvm/clang 18 installed via fedora’s dnf repository.
> > 
> > 2. Create a cpp source file with the repro code.
> > 
> > 3. Use clang installed to reproduce this issue:
> >    clang -cc1 -w -analyze -analyzer-checker=core.uninitialized.UndefReturn 1.cc
> > 
> > 4. We’ll see the warning from UndefReturn checker.
> > 
> > 5. If you want you can use debug.ViewExplodedGraph checker to dump the exploded graph and use dot to convert it to a pdf file. The result should be identical to the one I once pasted.
> > ```
> 
> This looks weird. This is likely just some misconfiguration of the analyzer. I'd recommend using `scan-build` or `CodeChecker` to get it configured the right way. FYI the checker handling noreturn functions is `core.builtin.NoReturnFunctions` - which supposed to sink the path where you have the FP. By default, all `core` checkers are/should be enabled, which still makes me puzzle why you have this FP.
> 
> For you I'd recommend explicitly enabling the `core` package. After this, it should work and no longer report the FP.
> 
> PS: I found the bug. Usually users enable CSA with the `--analyze` flag, which will configure the default options, etc. However, you used the `-cc1 -analyze` which does not set the default options - and users should not really use that flag anyways so I suppose that is the intended meaning of the `-analyze`.

After added core.builtin.NoReturnFunctions along with core.uninitialized.UndefReturn the PF disappears. Use --analyze instead of -cc1 -analyze works as well.

Thanks a lot for your help.

**Comment by steakhal** [comment]
> After added core.builtin.NoReturnFunctions along with core.uninitialized.UndefReturn the PF disappears. Use --analyze instead of -cc1 -analyze works as well.

Please, prefer `--analyze` over `-analyze`.
