### ISSUE TITLE
missing include header

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#9885]
|  |  |
| --- | --- |
| Bugzilla Link | [9513](https://llvm.org/bz9513) |
| Version | trunk |
| OS | Solaris |
| Reporter | LLVM Bugzilla Contributor |
| CC | @Bigcheese |

## Extended Description 
lib/Support/Unix/PathV2.inc is using PATH_MAX but does not include limits.h where is PATH_MAX defined on Solaris

**Comment by arsenm** [comment]
Old build issue
