### ISSUE TITLE
Trying to build with libc runtime but no libc headers generated

### ISSUE THREAD

**Issue by Desperado17** [llvm/llvm-project#98872]
Clang 17, Ubuntu 22.04, llvm 17.0.6:

```
cmake -G Ninja -S runtimes -B msan_out  \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_ENABLE_RUNTIMES="compiler-rt;libc;libcxx;libcxxabi;libunwind" \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DLLVM_USE_SANITIZER=MemoryWithOrigins
```

I see the libcxx headers in output include directory but no libc headers like time.h and no libc.so are generated.

Am I missing something?

Regards

**Comment by vortex73** [comment]
I think [this](https://libc.llvm.org/full_host_build.html) solves your issue?

**Comment by Desperado17** [comment]
I modified the configuration as follows now:

`cmake -G Ninja -S runtimes -B msan_out 
-DCMAKE_BUILD_TYPE=Release \
-DLLVM_ENABLE_RUNTIMES="compiler-rt;libc;libcxx;libcxxabi;libunwind" \ 
-DLLVM_LIBC_FULL_BUILD=ON \
-DCMAKE_C_COMPILER=clang \
-DCMAKE_CXX_COMPILER=clang++  \
-DLLVM_USE_SANITIZER=MemoryWithOrigins \
-DDEFAULT_SYSROOT=/home/user/instrumentedlibcpp/llvm-project \
-DCMAKE_INSTALL_PREFIX=/home/user/instrumentedlibcpp/llvm-project`

Result:

FAILED: libc/utils/HdrGen/CMakeFiles/libc-hdrgen.dir/PublicAPICommand.cpp.o 
/usr/bin/clang++ -DGTEST_HAS_RTTI=0 -I/home/user/instrumentedlibcpp/llvm-project/msan_out/include -I/home/user/instrumentedlibcpp/llvm-project/libc -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fno-omit-frame-pointer -gline-tables-only -fsanitize=memory -fsanitize-memory-track-origins -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG -std=gnu++17  -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-rtti -MD -MT libc/utils/HdrGen/CMakeFiles/libc-hdrgen.dir/PublicAPICommand.cpp.o -MF libc/utils/HdrGen/CMakeFiles/libc-hdrgen.dir/PublicAPICommand.cpp.o.d -o libc/utils/HdrGen/CMakeFiles/libc-hdrgen.dir/PublicAPICommand.cpp.o -c /home/user/instrumentedlibcpp/llvm-project/libc/utils/HdrGen/PublicAPICommand.cpp
In file included from /home/user/instrumentedlibcpp/llvm-project/libc/utils/HdrGen/PublicAPICommand.cpp:9:
In file included from /home/user/instrumentedlibcpp/llvm-project/libc/utils/HdrGen/PublicAPICommand.h:12:
/home/user/instrumentedlibcpp/llvm-project/libc/utils/HdrGen/Command.h:12:10: fatal error: 'llvm/ADT/SmallVector.h' file not found
   12 | #include "llvm/ADT/SmallVector.h"

**Comment by Desperado17** [comment]
Some more attempts.

cmake ../llvm  \
   -G Ninja  \
   -DLLVM_ENABLE_PROJECTS="clang;libc;lld;compiler-rt"   \
   -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind"   \
   -DCMAKE_BUILD_TYPE=Release  \
   -DCMAKE_C_COMPILER=clang \
   -DCMAKE_CXX_COMPILER=clang++ \
   -DLLVM_LIBC_FULL_BUILD=ON \
   -DLLVM_LIBC_INCLUDE_SCUDO=ON \
   -DCOMPILER_RT_BUILD_SCUDO_STANDALONE_WITH_LLVM_LIBC=ON \
   -DCOMPILER_RT_BUILD_GWP_ASAN=OFF                       \
   -DCOMPILER_RT_SCUDO_STANDALONE_BUILD_SHARED=OFF        \
   -DCLANG_DEFAULT_LINKER=lld \
   -DCLANG_DEFAULT_RTLIB=compiler-rt \
   -DDEFAULT_SYSROOT=$SYSROOT \
   -DCMAKE_INSTALL_PREFIX=$SYSROOT
   
 
will succeed but adding DLLVM_USE_SANITIZER=MemoryWithOrigins

cmake ../llvm  \
   -G Ninja  \
   -DLLVM_ENABLE_PROJECTS="clang;libc;lld;compiler-rt"   \
   -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind"   \
   -DCMAKE_BUILD_TYPE=Release  \
   -DCMAKE_C_COMPILER=clang \
   -DCMAKE_CXX_COMPILER=clang++ \
   -DLLVM_LIBC_FULL_BUILD=ON \
   -DLLVM_LIBC_INCLUDE_SCUDO=ON \
   -DCOMPILER_RT_BUILD_SCUDO_STANDALONE_WITH_LLVM_LIBC=ON \
   -DCOMPILER_RT_BUILD_GWP_ASAN=OFF                       \
   -DCOMPILER_RT_SCUDO_STANDALONE_BUILD_SHARED=OFF        \
   -DLLVM_USE_SANITIZER=MemoryWithOrigins \
   -DCLANG_DEFAULT_LINKER=lld \
   -DCLANG_DEFAULT_RTLIB=compiler-rt \
   -DDEFAULT_SYSROOT=$SYSROOT \
   -DCMAKE_INSTALL_PREFIX=$SYSROOT
   
   
   will fail with:
   
   CMake Error at /home/user/instrumentedlibcpp/llvm-project/compiler-rt/cmake/Modules/AddCompilerRT.cmake:460 (sanitizer_test_compile):
  Unknown CMake command "sanitizer_test_compile".
Call Stack (most recent call first):
  /home/user/instrumentedlibcpp/llvm-project/compiler-rt/lib/scudo/standalone/tests/CMakeLists.txt:80 (generate_compiler_rt_tests)
  /home/user/instrumentedlibcpp/llvm-project/compiler-rt/lib/scudo/standalone/tests/CMakeLists.txt:126 (add_scudo_unittest)

**Comment by Desperado17** [comment]
This fails for me on current main branch:

cmake -G Ninja -S llvm -B msan_out  \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_ENABLE_PROJECTS="all" \
    -DLLVM_ENABLE_RUNTIMES="all" \
    -DLLVM_LIBC_FULL_BUILD=ON \
    -DLLVM_LIBC_INCLUDE_SCUDO=ON \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DLLVM_USE_SANITIZER=MemoryWithOrigins

CMake Error at /media/user/SSD1TB/llvmalt/llvm-project/compiler-rt/cmake/Modules/AddCompilerRT.cmake:461 (sanitizer_test_compile):
  Unknown CMake command "sanitizer_test_compile".
Call Stack (most recent call first):
  /media/user/SSD1TB/llvmalt/llvm-project/compiler-rt/lib/scudo/standalone/tests/CMakeLists.txt:79 (generate_compiler_rt_tests)
  /media/user/SSD1TB/llvmalt/llvm-project/compiler-rt/lib/scudo/standalone/tests/CMakeLists.txt:124 (add_scudo_unittest)

**Comment by Desperado17** [comment]
Btw, is it possible to build everything regularly without sanitizer and then only libcxx https://github.com/google/sanitizers/wiki/MemorySanitizerLibcxxHowTo with -DLLVM_USE_SANITIZER=MemoryWithOrigins and all in one output workspace?

**Comment by lntue** [comment]
Can you try your build command with `libc` removed from `-DLLVM_ENABLE_PROJECTS` and move it to `-DLLVM_ENABLE_RUNTIMES` instead?

**Comment by EugeneZelenko** [comment]
Could you please try 19 or `main` branch?

**Comment by nickdesaulniers** [comment]
Please reopen with more info.
