### ISSUE TITLE
[flang][debuginfo] Module variable needs to be qualified with module name.

### ISSUE THREAD

**Issue by abidh** [llvm/llvm-project#98883]
To evalaute the variable in a module, we need to qualify it with the module name.

```
module helper
  integer var1
end module

PROGRAM minimal
  use helper
  var1 = 2
  print *, var1
end
```

In the above program, when stopped at line `  print *, var1`, if I need to get the value of `var1`, I need to qualify it with the module name. With the right debug info, it should work without need to qualify the name with the module name.

```
(gdb) p var1
No symbol "var1" in current context.
(gdb) p helper::var1
$1 = 2
```

**Comment by kiranchandramohan** [comment]
@abidh Do you have a patch in progress for this? Is this just about adding the DI Imported Module tag?

**Comment by abidh** [comment]
> @abidh Do you have a patch in progress for this? Is this just about adding the DI Imported Module tag?

I have been working on a fix. But it is proving difficult. You are right that it requires a `!DIImportedEntity(tag: DIImportedModule)` in the IR. Also `imports` field of the `!DICompileUnit` needs to be populated with the correct reference.

Problem I am facing is that when I create `DIImportedEntityAttr` in `AddDebugInfo` pass, I have no good place to attach it to. I thought that I could add a new field in `DICompileUnitAttr` and attach the list of `DIImportedEntityAttr` to it when all functions have been processed. This does not work because `DICompileUnitAttr` can't be changed once created. I am now working on the idea that I can perhaps attach it to ModuleOp as attr and then process it in the MLIR and generate the required debug metadata.
