### ISSUE TITLE
[Offload][amdgpu] Regression in OpenMP unit tests

### ISSUE THREAD

**Issue by jplehr** [llvm/llvm-project#98903]
https://github.com/llvm/llvm-project/pull/83131 caused four test failures that are `XFAIL` via https://github.com/llvm/llvm-project/pull/98899

**Comment by arsenm** [comment]
Can you attach bitcode from the before/after failing cases with the invocation

**Comment by jhuber6** [comment]
Looking at the tests, this might just be yet another case of https://github.com/llvm/llvm-project/issues/64863, It fails with the same message. I'll try to get some IR.

**Comment by jhuber6** [comment]
> Can you attach bitcode from the before/after failing cases with the invocation

https://godbolt.org/z/fGMfvdYo3 is the IR for one of the failing tests. Doing `llvm-reduce` on it just nets the same IR as the existing issue, so it's definitely the same thing. Normally the LTO pass pipeline would run at `O2` by default which would at least do DCE even if all the functions had `noopt` on them from `-O0`. I wonder what your patch changed that resulted in these not being dropped.

**Comment by arsenm** [comment]
I have a vague memory that the AMDGPUAttributor run happened to delete the unreachable functions, which was the main reason the problem only happened at -O0

**Comment by jhuber6** [comment]
> I have a vague memory that the AMDGPUAttributor run happened to delete the unreachable functions, which was the main reason the problem only happened at -O0

That checks out, honestly we could probably make the backend do a mandatory DCE pass if we really wanted to hack around this. Any updates on the real fix to this? I know someone's working on it but it's been awhile.

**Comment by arsenm** [comment]
@JanekvO

**Comment by arsenm** [comment]
Which commit fixed this?

**Comment by jhuber6** [comment]
> Which commit fixed this?

1a3cfe5b9dc9c80a375506262b54b51d929df52d I don't know why, but after landing that it stopped failing. The patch basically just uses `ld.lld`'s LTO instead of reinventing it.
