### ISSUE TITLE
LLVM is not considering X u > C, a, b to be the same as X <= C, b, a.

### ISSUE THREAD

**Issue by AtariDreams** [llvm/llvm-project#98926]
LLVM is not considering X u > C, a, b to be the same as X <= C, b, a.

To fix this, let's move the folds to after the canonicalization of -1 to TrueVal.

Alive2 Proof:
https://alive2.llvm.org/ce/z/8QbZfx

_Originally posted by @AtariDreams in https://github.com/llvm/llvm-project/pull/97973_

**Comment by nikic** [comment]
Please do not create dummy issues for already open PRs.
