### ISSUE TITLE
Should warn when comparing differing enum types

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#9893]
|  |  |
| --- | --- |
| Bugzilla Link | [9521](https://llvm.org/bz9521) |
| Version | trunk |
| OS | MacOS X |
| Attachments | [example](https://user-images.githubusercontent.com/60944935/143742900-22f17761-b003-4a28-ad96-3df58f597847.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @lattner,@rjmccall |

## Extended Description 

At some point, clang started warning when passing arguments of one enum type into a function taking a differing enum type. But, if enum types are going to be considered different to this extent, then comparison of values/variables of differing enum types should warn too (and don't as of r128001).

See the attached example that calls out a few constructs that should warn but don't (certainly not exhaustive).

**Comment by arsenm** [comment]
See this in attached testcase:
`warning: implicit conversion from enumeration type 'Texture' to different enumeration type 'Color' [-Wenum-conversion]`
