### ISSUE TITLE
x86 CodeGen Question: Why is eax set to zero before function calls?

### ISSUE THREAD

**Issue by Toni-Graphics** [llvm/llvm-project#98934]
Hi,
I experimented a little bit with clang in godbold: [https://godbolt.org/z/GnvM4jKxM](https://godbolt.org/z/GnvM4jKxM)
I came across that there is a `xor eax, eax` before each function is called. Why is that?
Eax is no argument register. And the printf function doesn't depend on the content of eax.
Also max optimizations are turned on (-O3)

(In the godbold; the right tab; line 5 and 14)

Note: If i am understanding something here wrong please let me know that
Bye

**Comment by topperc** [comment]
If I remember right, the x86-64 SystemV ABI uses EAX to indicate the number of vector registers passed to a variadic fucntion.

**Comment by topperc** [comment]
psABI doc is here https://gitlab.com/x86-psABIs/x86-64-ABI

Relevant text from section 3.5.7 Variable Argument Lists

"When a function taking variable-arguments is called, %al must be set to the total number of floating point parameters passed to the function in vector registers."

**Comment by Toni-Graphics** [comment]
Thank you
