### ISSUE TITLE
Refactor uses of `Cand->Function` in `SemaOverload.cpp`

### ISSUE THREAD

**Issue by shafik** [llvm/llvm-project#98942]
We use `Cand->Function` all over `SemaOverload.cpp` e.g. 

https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/SemaOverload.cpp#L12583-L12585

In some places it is safe to use without checking b/c in the calling function we checked it prior. It is hard to see that without carefully checking the call chain.

It seems like once we check `Cand->Function` we should pass it as a separate `FunctionDecl*` argument and assert on that argument or at minimum we should assert on `Cand->Function` in the called function.

**Comment by vortex73** [comment]
Since this is basically a superset of #98769 i shall submit a combined PR.

**Comment by zyn0217** [comment]
Fixed by #98965
