### ISSUE TITLE
ld terminated with signal 7 [Bus error]

### ISSUE THREAD

**Issue by SiliconSelf** [llvm/llvm-project#98988]
I am trying to build my project [cubby](https://github.com/SiliconSelf/cubby/tree/f50e2dd01d9fe34a75102a3553c3d847bd5c8a59) and while my builds work in GitHub Actions and my laptop, on my desktop machine I have started experiencing ld crashes with the message.

> collect2: fatal error: ld terminated with signal 7 [Bus error]

I have attached the backtrace here:
[backtrace.txt](https://github.com/user-attachments/files/16243191/backtrace.txt)

I'm not sure this is an issue with LLVM itself as this project compiles without issues on other machines, but the crashlog says to submit a report here with the backtrace so that's what I'm doing.

**Comment by efriedma-quic** [comment]
There isn't really enough information to figure out what's happening.  Maybe if you file a bug report in the Rust bugtracker, they can help you reduce a testcase.

**Comment by SiliconSelf** [comment]
I've since figured out that this was happening because I was running because I was running out of space on the drive i
