### ISSUE TITLE
Unable to build universal binaries of LLVM

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#9906]
|  |  |
| --- | --- |
| Bugzilla Link | [9534](https://llvm.org/bz9534) |
| Version | trunk |
| OS | MacOS X |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Unable to build universal binaries of LLVM with the following operations:

./configure --enable-optimized --enable-shared UNIVERSAL=1 UNIVERSAL_ARCH="i386 x86_64" UNIVERSAL_SDK_PATH=/Developer/SDKs/MacOSX10.5.sdk/ DARWIN_VERSION=10.5

(actually it doesn't depends on environment variables pointed as configure arguments)

make UNIVERSAL=1 UNIVERSAL_ARCH="i386 x86_64" UNIVERSAL_SDK_PATH=/Developer/SDKs/MacOSX10.5.sdk/ DARWIN_VERSION=10.5

Make process reports the error:

make[2]: *** No rule to make target `/Users/cyril/llvm/Release+Asserts/lib/libLLVM-3.0svn.dylib', needed by `/Users/cyril/llvm/Release+Asserts/bin/opt'.  Stop.
make[1]: *** [opt/.makeall] Error 2

**Comment by arsenm** [comment]
Old build issue, autotools was removed
