### ISSUE TITLE
[mlir][spirv] Serializer produces incorrect generator metadata in SPIR-V header

### ISSUE THREAD

**Issue by andfau-amd** [llvm/llvm-project#99071]
See https://github.com/KhronosGroup/SPIRV-Tools/issues/5717 for more. Probably a trivial one-line fix, good low-hanging fruit for a newcomer?

**Comment by andfau-amd** [comment]
https://github.com/llvm/llvm-project/blob/bbcb3d6aabef60c2dd2c32764ca4fd297782c322/mlir/lib/Target/SPIRV/SPIRVBinaryUtils.cpp#L38-L57

**Comment by andfau-amd** [comment]
https://github.com/KhronosGroup/SPIRV-Headers/blob/3c355ec439dcf821c50fb4660ef0e50d19ae2b63/include/spirv/spir-v.xml#L35-L50

**Comment by kuhar** [comment]
Nice catch @andfau-amd!
