### ISSUE TITLE
Implement the `asint` HLSL Function

### ISSUE THREAD

**Issue by farzonl** [llvm/llvm-project#99091]
> Note: see how we did [`asfloat`](https://github.com/llvm/llvm-project/pull/108686) and [`asuint`](https://github.com/llvm/llvm-project/pull/107292/files).

- [ ] Link  bitcast clang builtin  for int with `asint` `hlsl_intrinsics.h`
- [ ] Add checks for `asint`
- [ ] Add codegen tests to `clang/test/CodeGenHLSL/builtins/asint.hlsl`
- [ ] Add sema tests to `clang/test/SemaHLSL/BuiltIns/asint-errors.hlsl`

## DirectX

There were no DXIL opcodes found for `asint`.

## SPIR-V

There were no SPIRV opcodes found for `asint`.

### Example 1
```hlsl
//dxc asint_test.hlsl -T lib_6_8 -enable-16bit-types -O0

export int4 fn(float p1) {
    return asint(p1);
}
```
 ### Example 2
```hlsl
//dxc asint_1_test.hlsl -T lib_6_8 -enable-16bit-types -O0

export int4 fn(uint p1) {
    return asint(p1);
}
```
 ### Example 3
```hlsl
//dxc asint_2_test.hlsl -T lib_6_8 -enable-16bit-types -O0

export int4 fn(int p1) {
    return asint(p1);
}
```
## HLSL:

Interprets the bit pattern of *x* as an integer.

| ret asint(*x*) |
|----------------|

 

## Parameters

| Item                                                   | Description                        |
|--------------------------------------------------------|------------------------------------|
| <span id="x"></span><span id="X"></span>*x*<br/> | \[in\] The input value.<br/> |

 

## Return Value

The input interpreted as an integer.

## Type Description

| Name  | [**Template Type**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-intrinsic-functions.md)                                                  | [**Component Type**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-intrinsic-functions.md)                  | Size                           |
|-------|----------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------|--------------------------------|
| *x*   | [**scalar**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-intrinsic-functions.md), **vector**, or **matrix** | [**float**](/windows/desktop/WinProg/windows-data-types), [**uint**](/windows/desktop/WinProg/windows-data-types) | any                            |
| *ret* | same as input *x*                                                                                              | [**int**](/windows/desktop/WinProg/windows-data-types)                                           | same dimension(s) as input *x* |

 

## Minimum Shader Model

This function is supported in the following shader models.

| Shader Model                                                        | Supported |
|---------------------------------------------------------------------|-----------|
| [Shader Model 4](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-sm4.md) and higher shader models | yes       |
| [Shader Model 3 (DirectX HLSL)](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-sm3.md)           | no        |
| [Shader Model 2 (DirectX HLSL)](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-sm2.md)           | no        |
| [Shader Model 1 (DirectX HLSL)](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-sm1.md)           | no        |

 

## See also

<dl> <dt>

[**Intrinsic Functions (DirectX HLSL)**](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-intrinsic-functions.md)
</dt> </dl>

**Comment by inbelic** [comment]
I will start working on this
