### ISSUE TITLE
Implement the `countbits` HLSL Function

### ISSUE THREAD

**Issue by farzonl** [llvm/llvm-project#99094]
> Note The SPIRV Work is completed https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp#L481C3-L482C63
> We just need to add the test case.

- [ ] Implement `countbits` clang builtin,
- [ ] Link `countbits` clang builtin with `hlsl_intrinsics.h`
- [ ] Add sema checks for `countbits` to `CheckHLSLBuiltinFunctionCall` in `SemaChecking.cpp`
- [ ] Add codegen for `countbits` to `EmitHLSLBuiltinExpr` in `CGBuiltin.cpp`
- [ ] Add codegen tests to `clang/test/CodeGenHLSL/builtins/countbits.hlsl`
- [ ] Add sema tests to `clang/test/SemaHLSL/BuiltIns/countbits-errors.hlsl`
- [ ] Create the `DXILOpMapping` of `int_ctpop` to  `31` in `DXIL.td`
- [ ] Create the  `countbits.ll` and `countbits_errors.ll` tests in `llvm/test/CodeGen/DirectX/`
- [ ] Create SPIR-V backend test case in `llvm/test/CodeGen/SPIRV/hlsl-intrinsics/countbits.ll`

## DirectX

| DXIL Opcode | DXIL OpName | Shader Model | Shader Stages |
| ----------- | ----------- | ------------ | ------------- |
| 31 | Countbits | 6.0 | () |

## SPIR-V

# [OpBitCount](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpBitCount):

## Description:
  
Count the number of set bits in an object.  
  
Results are computed per component.  
  
*Result Type* must be a scalar or vector of [*integer type*](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Integer).
The components must be wide enough to hold the unsigned *Width* of
*Base* as an unsigned value. That is, no sign bit is needed or counted
when checking for a wide enough result width.  
  
*Base* must be a scalar or vector of [*integer type*](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Integer). It must
have the same number of components as *Result Type*.  
  
The result is the unsigned value that is the number of bits in *Base*
that are 1.

<table>
<colgroup>
<col style="width: 20%" />
<col style="width: 20%" />
<col style="width: 20%" />
<col style="width: 20%" />
<col style="width: 20%" />
</colgroup>
<thead>
<tr>
<th>Word Count</th>
<th>Opcode</th>
<th>Results</th>
<th>Operands</th>
<th></th>
</tr>
</thead>
<tbody>
<tr>
<td class="tableblock halign-left valign-top"><p>4</p></td>
<td class="tableblock halign-left valign-top"><p>205</p></td>
<td
class="tableblock halign-left valign-top"><p><em>&lt;id&gt;</em><br />
<em>Result Type</em></p></td>
<td class="tableblock halign-left valign-top"><p><a
href="#ResultId"><em>Result &lt;id&gt;</em></a></p></td>
<td
class="tableblock halign-left valign-top"><p><em>&lt;id&gt;</em><br />
<em>Base</em></p></td>
</tr>
</tbody>
</table>

### Example 1
```hlsl
//dxc countbits_test.hlsl -T lib_6_8 -enable-16bit-types -O0

export uint4 fn(int4 p1) {
    return countbits(p1);
}
```
## HLSL:

Counts the number of bits (per component) set in the input integer.

## Syntax

``` syntax
uint countbits(
  in uint value
);
```

## Parameters

<dl> <dt>

*value* \[in\]
</dt> <dd>

Type: **uint**

The input value.

</dd> </dl>

## Return value

Type: **uint**

The number of bits.

## Remarks

The following overloaded versions are also available:

``` syntax
uint count_bits(uint value);
uint2 count_bits(uint2 value);
uint3 count_bits(uint3 value);
uint4 count_bits(uint4 value);
```

### Minimum Shader Model

This function is supported in the following shader models.

| Shader Model                                                                | Supported |
|-----------------------------------------------------------------------------|-----------|
| [Shader Model 5](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/d3d11-graphics-reference-sm5.md) and higher shader models | yes       |

 

This function is supported in the following types of shaders:

| Vertex | Hull | Domain | Geometry | Pixel | Compute |
|--------|------|--------|----------|-------|---------|
| x      | x    | x      | x        | x     | x       |

 

## See also

<dl> <dt>

[Intrinsic Functions](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/dx-graphics-hlsl-intrinsic-functions.md)
</dt> <dt>

[Shader Model 5](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src//direct3dhlsl/d3d11-graphics-reference-sm5.md)
</dt> </dl>

**Comment by spall** [comment]
looking at this
