### ISSUE TITLE
Discrepancies with clang::RecursiveASTVisitor between Windows and Unix (mac/linux)

### ISSUE THREAD

**Issue by tcanabrava** [llvm/llvm-project#99261]
Hello All.

I develop [codevis](http://invent.kde.org/sdk/codevis) that heavily uses llvm and clang for it's introspection.
Today I was debugging a failure in one of the unittests that just happened on windows, in the end I was able to create a minimal example that showcased the error, and tested it on windows and linux, getting different results.

If we have a 
```c++
class LogicalDepVisitor : public clang::RecursiveASTVisitor<LogicalDepVisitor> {
    bool VisitVarDecl(clang::VarDecl *varDecl) {
       std::cout << "Visiting variable " << varDecl->getDeclName().getAsString() << std::endl; 
   }
```

and use it to introspect this code:

```c++
   class C {};

   class D {
     public:
       template <typename T>
       static void some_method(T t, int a = 0)
       {
           C c;
       }
   };

   class E {
     public:
       void some_method()
       {
           D::some_method(1);
       }
   };
```

The result in Linux and MacOS is:
```
<- Analyzing Template
t
a
c
<- Analyzing Template Expansion
t
a
c
```

whereas in windows is

```
<- Analyzing Template
t
a
<- Analyzing Template Expansion
t
a
c
```
I'm attaching a minimal example (cmake based project, minimal files) that shows this discrepancy.

Windows LLVM Version: 18.1.2
Linux: 18.1.8

[logical_visitor.zip](https://github.com/user-attachments/files/16258011/logical_visitor.zip)

**Comment by mizvekov** [comment]
I assume your unittests are not fixing a target, and thus are targeting different machines when built under linux and windows.

The relevant difference here is that we default to `-fdelayed-template-parsing` when the target machine is 'MSVC', unless using C++20 or higher. Otherwise, we default to `-fno-delayed-template-parsing`, which is the conforming behavior.

Can you confirm these results are affected by these flags?

**Comment by tcanabrava** [comment]
Thanks for promptly replying.
I'm not using clang as a front-end, but as a library.

Currently I'm configuring the compiler frontend as this:

```
// try our best not to bail on compilation errors
        clang::FrontendOptions& fOpts = compiler.getFrontendOpts();
        fOpts.FixWhatYouCan = true;
        fOpts.FixAndRecompile = true;
        fOpts.FixToTemporaries = true;

        // Attempt to obliterate any -Werror options
        clang::DiagnosticOptions& dOpts = compiler.getDiagnosticOpts();
        dOpts.Warnings = {"-Wno-everything"};
```

I have searched in all of the get*Ops() calls from ClangCompiler, but couldn't find one that sets the DelayedTemplateParsing bits.

**Comment by tcanabrava** [comment]
Fixed by acessing compiler.getLangOpts().DelayedTemplateParsing = False

Thanks. <3
