### ISSUE TITLE
Delay(disable) common instruction hoisting (by default)

### ISSUE THREAD

**Issue by hiraditya** [llvm/llvm-project#99270]
As per https://reviews.llvm.org/D84108 common code hoisting so early in the pass may not be beneficial so maybe we should do hoisting at the late stage?

cc: @lebedev.ri

**Comment by nikic** [comment]
Can you be more clear about what you want here? We already disable hoisting early in the pipeline.

**Comment by hiraditya** [comment]
Oh, I didn't notice that. Sorry for the confusion.
