### ISSUE TITLE
[clang-format] Cannot recognize multiplication semantic of `*`

### ISSUE THREAD

**Issue by chestnykh** [llvm/llvm-project#99271]
Consider the following sample
```
enum X {
        two = 2
};

#define FN(N) \
void fn(void *addr) \
{ \
        __builtin_memset(addr, 0, N * two); \
} \

FN(4)
```

And .clang-format containing just `BasedOnStyle: LLVM` 

Then we get the output where clang-format made a 'pointer of type N' instead of multiplication:
```
#define FN(N)                                                                  \
  void fn(void *addr) { __builtin_memset(addr, 0, N *two); }
```

**Comment by chestnykh** [comment]
Reduced repro:
`#define X M(a * b)` -> `#define X M(a *b)`

**Comment by owenca** [comment]
Reverted by 7e7a9069d4240d2ae619cb50eba09f948c537ce3.

**Comment by owenca** [comment]
> Reduced repro: `#define X M(a * b)` -> `#define X M(a *b)`

That's intended. Instead, a min repro is e.g.:
```
#define X     \
  {           \
    M(a * b); \
  }
```
