### ISSUE TITLE
[Clangd] No (good) autocomplete for new files

### ISSUE THREAD

**Issue by JVApen** [llvm/llvm-project#99295]
- Startup vs code with clangd (18.1.3) on windows (might be irrelevant)
 - Create a new header file my_specialclass.h
 - Add following content:
````
namespace My
{
    class SpecialClass
    {
          void qqqqqqqqqqqqqqq();
    };
}
````
 - Create a new cpp file my_specialclass.cpp
 - Add following content:
````
void My::
````
 - Notice that you get an auto-complete for SpecialClass
 - Select the auto-complete
 - Effect: `SpecialClass` is inserted
 - Expected: `SpecialClass` is inserted + include to my_specialclass.h was added
 - Extend the content to:
 ````
 void My::SpecialClass::
 ````
  - Effect: no auto-complete
  - Expected: get auto-complete for function `qqqqqqqqqqqqqqq`
  - Extend the content to:
 ````
 void My::SpecialClass::qqqq
 ````
  - Effect: no auto-complete
  - Expected: get auto-complete for function `qqqqqqqqqqqqqqq`

**Comment by JVApen** [comment]
I already did some debugging myself and believe there are 2 problems:
 - A file that was added in the workspace doesn't get `IncludeHeaders` in its symbol
 - The iterator for `RestrictedForCodeCompletion` jumps too far in when `AndIterator` is constructed. When `advanceTo` is called with a SyncID, the ChunkIterator somehow goes to SyncID+1

**Comment by kadircet** [comment]
this is WAI, clangd won't insert includes for non-self-contained headers (e.g. headers without include-guards).

you can fix this issue by adding `#pragma once` or a traditional `#ifndef FOO_H_GURAD ...` into your `my_specialclass.h`

**Comment by JVApen** [comment]
@kadircet : I just tried this with the `#pragma once` in the header, it doesn't change the behavior I'm getting

**Comment by kadircet** [comment]
@JVApen if that's the case, then I can't really reproduce :/

can you try with proper include guards as well? e.g.:

foo.h:
```
#ifndef _FOO_H_
#define _FOO_H_

namespace ns {
struct Foo {
  void bar();
};
} // namespace ns

#endif
```

then open up both `foo.h` and `foo.cc` in your editor, start typing `ns::Foo` in foo.cc, you should see a completion with insertion (dot "." next to symbol name, and also the "from a.h" in the description indicates the symbol is attributed to relevant header):
![Screenshot from 2024-07-17 15-05-42](https://github.com/user-attachments/assets/586b16fa-9cad-4e0f-be3b-905c150dc78a)

**Comment by HighCommander4** [comment]
For me, adding `#pragma once` fixes the first problem (not getting the header insertion).

The second problem (not getting a completion proposal for `qqqqqq`) is a known issue, https://github.com/clangd/clangd/issues/880, related to the fact that the method is private. (It works if the method is public.)

**Comment by JVApen** [comment]
I messed up in my own reproductions. It indeed works with clangd 18, it doesn't with clangd 16. I somehow used the wrong version when doing the reproduction again.
