### ISSUE TITLE
Clang accepts invalid overload involving explicit object member function

### ISSUE THREAD

**Issue by ranaanoop** [llvm/llvm-project#99304]
The following invalid program is accepted by clang. [Demo](https://godbolt.org/z/77M9z85e9)

```
struct C {
    
       void f(this C );   
       void f(C);         //EDG:Nope, clang:OK gcc:OK. msvc:OK    
};

```
The reason this program is invalid was explained in [this thread](https://stackoverflow.com/questions/78758215/explicit-object-member-function-discrepancies-between-different-compilers).

**Comment by cor3ntin** [comment]
This is valid per https://eel.is/c++draft/basic.scope.scope#4.4

See https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2797r0.html for details (this paper resolves https://cplusplus.github.io/CWG/issues/2692.html by making it well formed)

**Comment by shafik** [comment]
I don't believe this is correct, the second `f` has an implicit object parameter and a parameter of type `C`, we can see this more clearly by looking at codegen: https://godbolt.org/z/8hMTrMdPo

I hope I am not missing something here.

**Comment by ranaanoop** [comment]
It is unvalid. I think you're misreading your quoted reference and this
issue should be reopened.

**Comment by shafik** [comment]
CC @opensdh

**Comment by opensdh** [comment]
I'm not following here.  Should I ignore this because it's closed, or is there some CWG issue or so brewing that I might want to talk about?

**Comment by cor3ntin** [comment]
@opensdh I was confused for a while but I think this is perfectly valid per https://eel.is/c++draft/basic.scope.scope#4.4 and there is nothing for you, clang or cwg to do here. We were not certain for a while.

Of course, my initial analysis was wrong so there is a possibility that I'm wrong again, but I hope not.

**Comment by ranaanoop** [comment]
@opensdh  This is well-formed as explained [here](https://stackoverflow.com/a/78758250). Basically, even though object parameters after removing the reference are of same type(`C`), one of them have a non-object parameter while the other doesn't. So well-formed.
