### ISSUE TITLE
[SLPVectorizer] Unable to finish compile in 1 hour caused by SLP Vectorizer with #66740

### ISSUE THREAD

**Issue by cyyself** [llvm/llvm-project#99327]
I came across a very long compile time, which was unfinished after 1 hour on Intel i9 13900K with [some Verilator-generated C++ code](https://github.com/cyyself/verilator-slow-compile-cases/tree/master/XiangShan-136f64975e-0a9b31bb30) since the commit a7f962c00745c8e28991379985fcd6b51ac0d671 and still exists in the current main branch (at least 8ca7e24b359ab2b6d2868f9252c7cd11eb48c787 have been confirmed).

Steps to reproduce the bug:

```bash
git clone https://github.com/cyyself/verilator-slow-compile-cases.git
cd verilator-slow-compile-cases
cd XiangShan-136f64975e-0a9b31bb30
make CXX=clang++
```

After 1 hour, the clang process didn't stop. I attached gdb to clang, and [the stack dump](https://gist.github.com/cyyself/4d1473b46e0448d630aee3986ad24b71) shows it is running SLP Vectorizer.

I tried reverting commit a7f962c00745c8e28991379985fcd6b51ac0d671 based on commit 8ca7e24b359ab2b6d2868f9252c7cd11eb48c787. It finished in a few minutes.

I also tried to add `-fno-slp-vectorize` or remove `-fprofile-generate` based on commit 8ca7e24b359ab2b6d2868f9252c7cd11eb48c787. It also finished in a few minutes.

**Comment by alexey-bataev** [comment]
Need a reproducer

**Comment by dtcxzyw** [comment]
> Need a reproducer

[test.ll.log](https://github.com/user-attachments/files/16267047/test.ll.log)

```
bin/opt -passes=slp-vectorizer test.ll.log
```

**Comment by alexey-bataev** [comment]
Fixed in 82b800ecb35fb46881aa52000fa40b1b99aa654e

**Comment by cyyself** [comment]
@alexey-bataev I found performance regression on nearly every verilator-generated C++ code since this code will quickly surpass your limit. I think it's better to find out why it does not stop than only add a limit.

**Comment by cyyself** [comment]
@alexey-bataev I think we should better increase `UsesLimit` from 8 to 64 to cover the need for verilator-generated workloads.

Baseline: https://github.com/cyyself/llvm-project/commit/73d693ca2332c6b265153b97dcb0bc1896820b1e#commitcomment-144346225 37.55s
After 82b800ecb35fb46881aa52000fa40b1b99aa654e: https://github.com/cyyself/llvm-project/commit/cb44bba22c7df024f2c280aa22e0d421aaf3ae28#commitcomment-144367497 42.80s
Increase the limit to 64: https://github.com/cyyself/llvm-project/commit/d1d1357a889970b0da1151e426569abdaa309966#commitcomment-144371913 37.54s

**Comment by alexey-bataev** [comment]
This limit is not a lower limit, this is upper limit. If the value has more than 8 uses, we just replace all the uses of this value with the extractelement instruction. But I can try to increase the limit.
