### ISSUE TITLE
[MC][RISCV]MCID::Return

### ISSUE THREAD

**Issue by tianboh** [llvm/llvm-project#99438]
I noticed that RISCV bytecode use `C_JR` and `JALR` as return, here is a toy example
```
int bar(){return 0;}
```
and its byte code looks like
```
0000000080002060 <bar>:
80002060: 13 01 01 ff   addi    sp, sp, -16
80002064: 23 34 11 00   sd      ra, 8(sp)
80002068: 23 30 81 00   sd      s0, 0(sp)
8000206c: 13 04 01 01   addi    s0, sp, 16
80002070: 13 05 00 00   mv      a0, zero
80002074: 03 34 01 00   ld      s0, 0(sp)
80002078: 83 30 81 00   ld      ra, 8(sp)
8000207c: 13 01 01 01   addi    sp, sp, 16
80002080: 67 80 00 00   ret
```
Compile with `C` extension, the result is
```
000000008000204c <bar>:
8000204c: 41 11         addi    sp, sp, -16
8000204e: 06 e4         sd      ra, 8(sp)
80002050: 22 e0         sd      s0, 0(sp)
80002052: 00 08         addi    s0, sp, 16
80002054: 01 45         mv      a0, zero
80002056: 02 64         ld      s0, 0(sp)
80002058: a2 60         ld      ra, 8(sp)
8000205a: 41 01         addi    sp, sp, 16
8000205c: 82 80         ret
```
After checking the RISCV Spec, I noticed that ret instruction "0x00 0x00 0x80 0x67" and "0x80 0x82" is `JALR` and `C_JR` respectively. However, when I checked the generated table "RISCVGenInstrInfo.inc", these two instruction does not have `MCID::Return` tag.
```
    { 12802,	3,	1,	4,	6,	0,	0,	RISCVImpOpBase + 0,	7835,	0, 0x3ULL },  // Inst #12802 = JALR
    { 12473,	1,	0,	2,	6,	0,	0,	RISCVImpOpBase + 0,	7991,	0|(1ULL<<MCID::Barrier)|(1ULL<<MCID::Terminator), 0x8ULL },  // Inst #12473 = C_JR
```
Instead, the instruction with `MCID::Return` is `SRET`, `URET`. Why do we ignore `JALR` and `C_JR` for the `Return` tag?

I am using `isReturn` from MCInstrDesc.h to check whether an instruction is of return type. If `JALR` and `C_JR` do not have this tag, the result from `isReturn` is inaccurate.

**Comment by topperc** [comment]
JALR is not only used for returns. It's also used for calls. There's no way to make the flags accurate. You have to look at the operands too.

Can you use MCInstrAnalysis? It should have functions with the right operand checks.

**Comment by tianboh** [comment]
Thank you for clarification and suggestion! I noticed RISCVMCTargetDesc.cpp, which inherits MCInstrAnalysis, does have `isReturn` function. It treats `JALR` and `C_JR` with `ra` as return instruction. It totally answers my question. Many thanks :-)
