### ISSUE TITLE
[ScanDeps] ScanDeps shouldn't dependent on clangCodeGen

### ISSUE THREAD

**Issue by ChuanqiXu9** [llvm/llvm-project#99479]
From https://github.com/llvm/llvm-project/pull/66462#pullrequestreview-2185579768, it shows that now `clangDependencyScanning` depends on `clangCodeGen`, which cause the size of clangd to be much larger.

I found the reason why `clangDependencyScanning` depends on `clangCodeGen` is that `DependencyScanningWorker.cpp` uses  `ObjectFilePCHContainerReader`: https://github.com/llvm/llvm-project/blob/b634e057ddecc41dce046887d0f0854fed305374/clang/lib/Tooling/DependencyScanning/DependencyScanningWorker.cpp#L489-L490 

It looks odd that `clangDependencyScanning` depends on `clangCodeGen`. Is there any chance to get rid of that?

CC: @Bigcheese @jansvoboda11 @benlangmuir @akyrtzi

**Comment by ChuanqiXu9** [comment]
It looks like clangDependencyScanning only depends on the class `ObjectFilePCHContainerReader`. And the implementation of `ObjectFilePCHContainerReader` only depends on LLVMObject. And clangDriver already depends on `LLVMObject` and `clangDaemon` depends on `LLVMObject`.

So if we can split `ObjectFilePCHContainerReader` from `ObjectFilePCHContainerOperations.h` and `ObjectFilePCHContainerOperations.cpp`, it looks like we get rid of clangCodeGen. Then clangd can get rid of  redundant  dependency and the clang-scan-deps can reduce its site too.

**Comment by jansvoboda11** [comment]
That sounds good to me!

**Comment by benlangmuir** [comment]
Agreed; if we can reduce binary size by splitting out the reader that makes sense to me.

**Comment by ChuanqiXu9** [comment]
Sent https://github.com/llvm/llvm-project/pull/99599
