### ISSUE TITLE
Host-dependent (unstable) emitting SwitchInst

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#9953]
|  |  |
| --- | --- |
| Bugzilla Link | [9581](https://llvm.org/bz9581) |
| Version | 2.9 |
| OS | Windows NT |
| Depends On | llvm/llvm-project#7279  |
| Blocks | llvm/llvm-bugzilla-archive#9591  |
| Attachments | [foo.ll: from BlackfinRegisterInfo.cpp](https://user-images.githubusercontent.com/60944935/143742929-058cab65-3dbf-4ba0-b744-e5dd163cb1c8.gz), [Release+Assertshttps://user-images.githubusercontent.com/60944935/143742930-66c08398-d73b-409b-972a-3b1e05843095.gz), [Releasehttps://user-images.githubusercontent.com/60944935/143742931-4c14e1bd-a1fa-44df-905d-14d05684e7a8.gz), [clang-Releasehttps://user-images.githubusercontent.com/60944935/143742932-ff0443f5-0bc3-424c-9314-8ad6a55ab30c.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @asl,@dexonsmith,@rnk |

## Extended Description 

With g++.exe (TDM-1 mingw32) 4.4.0,

--enable-assertions affects behavior of code generator.
It seems floating point arithmetics would affect.

I can see identical outputs to suppress one debug print.

--- a/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp
+++ b/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp
@@ -2035,11 +2035,13 @@ bool SelectionDAGBuilder::handleBTSplitSwitchCase(CaseRe
c& CR,
                            (Last - RBegin + 1ULL).roundToDouble();
     double Metric = Range.logBase2()*(LDensity+RDensity);
     // Should always split in some non-trivial place
+#if 0
     DEBUG(dbgs() <<"=>Step\n"
                  << "LEnd: " << LEnd << ", RBegin: " << RBegin << '\n'
                  << "LDensity: " << LDensity
                  << ", RDensity: " << RDensity << '\n'
                  << "Metric: " << Metric << '\n');
+#endif
     if (FMetric < Metric) {
       Pivot = J;
       FMetric = Metric;

**Comment by arsenm** [comment]
Seems like all the FP was removed in 15823d49b61fc7ddafc2cb10b12f4498d53fb216
