### ISSUE TITLE
[IR] Missing assertion for empty range attribute

### ISSUE THREAD

**Issue by nikic** [llvm/llvm-project#99619]
Per LangRef, range attributes cannot represent an empty range. However, this is currently only enforced in the IR parser, but there is neither an assertion nor verifier check otherwise. As such, you'll only notice this mistake when trying to round-trip through textual IR.

cc @andjo403

**Comment by andjo403** [comment]
I can look at it next week I'm away from the computer now.

**Comment by andjo403** [comment]
hmm I do not know how to test this if I add a check of empty and full range in the verifier it will still fail on the check in the IR parser. Shall we change the IR parser check to exclude empty and full range and only handle them in the verifier? feels like we shall still have a check in the IR parser to avoid the assert in [ConstantRange constructor ](https://github.com/llvm/llvm-project/blob/3db78fa1dd639ba5db761023e04f97418cfcd00e/llvm/lib/IR/ConstantRange.cpp#L55-L56)

**Comment by nikic** [comment]
Usually, we either have a check in the verifier (but not parser), or we have a check in the parser and an assertion. So instead of moving the check to the verifier, you could also add an assertion to the attribute constructor.
