### ISSUE TITLE
llvm/IR/RuntimeLibcalls.h has introduced layering violation

### ISSUE THREAD

**Issue by chapuni** [llvm/llvm-project#99610]
#98512 introduced layering violation, including CodeGen from IR.
This also brought vt_gen into LLVMCore.

I strongly suggest reverting #98512 (c05126bdfc3b, bb604ae9b8ad, and 5b54f36fb607), at the moment.

I guess it can be rewritten with IR stuff.

**Comment by MaskRay** [comment]
I support reverting the patches. LLVM:Core should not include CodeGen includes, even if they are header-only.

**Comment by chapuni** [comment]
Reverted. Cc: @jhuber6
