### ISSUE TITLE
Assertion fail "Should not predicate a uniform recipe"

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#99625]
[RomBlocks-4aa6a4.cpp.gz](https://github.com/user-attachments/files/16310648/RomBlocks-4aa6a4.cpp.gz)
[RomBlocks-4aa6a4.sh.gz](https://github.com/user-attachments/files/16310650/RomBlocks-4aa6a4.sh.gz)

clang++: /home/dcb40b/llvm/trunk/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:8583: llvm::VPReplicateRecipe* llvm::VPRecipeBuilder::handleReplication(llvm::Instruction*, llvm::VFRange&): Assertion `(Range.Start.isScalar() || !IsUniform || !IsPredicated || (Range.Start.isScalable() && isa<IntrinsicInst>(I))) && "Should not predicate a uniform recipe"' failed.

**Comment by fhahn** [comment]
This one should also be fixed by https://github.com/llvm/llvm-project/pull/98892
