### ISSUE TITLE
[META][Win] non-identical binaries with clang and llvm among stage2 and stage3

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#9963]
|  |  |
| --- | --- |
| Bugzilla Link | [9591](https://llvm.org/bz9591) |
| Version | 2.9 |
| OS | Windows XP |
| Depends On | #11509 #9822 #9941 #9962  |
| Blocks | #8762  |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I have met several issues with 3-stage build on cygming.

  - nondeterministic behavior (eg. address-dependent map iterator)
  - floating point precision issue

On 2.9, They are dubious below.

  - SimplifyCFG(r127650)
  - DSE (r128482)
  - utils/TableGen/ClangSACheckersEmitter.cpp
  - CodeGen/SelectionDAGBuilder.cpp
  - CodeGen/LiveIntervalAnalysis.cpp

**Comment by arsenm** [comment]
Old build issue
