### ISSUE TITLE
Why bolt will covert tail call to normal call in Bolt? 

### ISSUE THREAD

**Issue by liusy58** [llvm/llvm-project#99650]
Hi, I am reading Bolt source code, https://github.com/llvm/llvm-project/blob/main/bolt/lib/Passes/Inliner.cpp#L341
I noticed that when inlining a function A, tail calls in A will be transformed into normal call? Could anyone tell me why? For the safety of stack?

**Comment by yota9** [comment]
Hi @liusy58 ! As I know you've got the answer in Discord, so currently I'm closing the issue if you don't mind. Fill free to re-open it if you have some further questions.
