### ISSUE TITLE
P0429: A Standard flat_map

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#99665]
See https://eel.is/c++draft/flat.map.

**Comment by ldionne** [comment]
@huixie90 Is already working on a patch for this, we discussed it a few weeks ago. To avoid duplicate work.

**Comment by ldionne** [comment]
Closing as a duplicate of the "official paper tracking issue" here: https://github.com/llvm/llvm-project/issues/105190

There's no difference other than the other issue was created via my scripts and added to the Conformance Table, and this one wasn't.
