### ISSUE TITLE
[BUG] Weird coloring in x86 assembly in llvm-objdump

### ISSUE THREAD

**Issue by Cr0a3** [llvm/llvm-project#99661]
Hi,
I am experimenting a little with writing my own backend (for another project).
To test the correctness of code generatation and object file emiting i use `llvm-mc` and `llvm-objdump`.
I dissasembled an file and i noticed a bracket is green and the closing one is gray.
I think it would be prettier to use gray for both ones:
![image](https://github.com/user-attachments/assets/536b3b4c-4efa-4a63-9d6d-d0f4bfcd315c)

(You maybe need to zoom in a little to view the difference)

**Comment by Toni-Graphics** [comment]
I fixed the bug myself. Just need to test it and then create a pull request

**Comment by MaskRay** [comment]
The underlying issue is that we don't handle coloring correctly with nested `WithMarkup`. We need to maintain a color stack.
