### ISSUE TITLE
[libc] add `pthread_rwlock_clockrdlock` and `pthread_rwlock_clockwrlock` GNU extensions

### ISSUE THREAD

**Issue by SchrodingerZhu** [llvm/llvm-project#99697]
> Function: `int pthread_rwlock_clockrdlock (pthread_rwlock_t *rwlock, clockid_t clockid, const struct timespec *abstime)`
> Preliminary: | MT-Safe | AS-Unsafe lock | AC-Unsafe lock | See [POSIX Safety Concepts](https://www.gnu.org/software/libc/manual/html_node/POSIX-Safety-Concepts.html).
> Behaves like pthread_rwlock_timedrdlock except the time abstime is measured against the clock specified by clockid rather than CLOCK_REALTIME. Currently, clockid must be either CLOCK_MONOTONIC or CLOCK_REALTIME, otherwise EINVAL is returned.

> Function: `int pthread_rwlock_clockwrlock (pthread_rwlock_t *rwlock, clockid_t clockid, const struct timespec *abstime)`
> Preliminary: | MT-Safe | AS-Unsafe lock | AC-Unsafe lock | See [POSIX Safety Concepts](https://www.gnu.org/software/libc/manual/html_node/POSIX-Safety-Concepts.html).
> Behaves like pthread_rwlock_timedwrlock except the time abstime is measured against the clock specified by clockid rather than CLOCK_REALTIME. Currently, clockid must be either CLOCK_MONOTONIC or CLOCK_REALTIME, otherwise EINVAL is returned.

These should be easy to do since we already have all the abilities to handle realtime and monolithic clocks. See:
https://github.com/llvm/llvm-project/blob/9b02b75c4d035192d9f24038f70107d7ffbb0f77/libc/src/pthread/pthread_rwlock_timedwrlock.cpp#L31

**Comment by SchrodingerZhu** [comment]
It is also within POSIX.1-2024 now.

**Comment by Eric977** [comment]
Hi! I would like to give this a try.

**Comment by SchrodingerZhu** [comment]
Sure, go ahead!

**Comment by nickdesaulniers** [comment]
fixed in 44df89cc30fc4
