### ISSUE TITLE
clang-format adding spaces around the arrow operator

### ISSUE THREAD

**Issue by winterz** [llvm/llvm-project#99758]
Since upgrading from v17.0.6 to 18 code like this:

```
void UiIntegration::requestNavigateToCode(const QUrl &url, int lineNumber, int columnNumber)
{
    if (UiIntegration::instance())
        emit UiIntegration::instance()->navigateToCode(url, lineNumber, columnNumber);
}
```

is being reformatted like this:
```
void UiIntegration::requestNavigateToCode(const QUrl &url, int lineNumber, int columnNumber)
{
    if (UiIntegration::instance())
        emit UiIntegration::instance() -> navigateToCode(url, lineNumber, columnNumber);
}

```

ie. spaces are being added around the arrow operator.  I don't want those spaces

is there a configuration to control this behavior that I'm missing?
else I think this is a bug.

**Comment by rymiel** [comment]
Bisected to c83d64f17a6e38f39fde611f06479e6f2a62b70f

**Comment by owenca** [comment]
> Bisected to [c83d64f](https://github.com/llvm/llvm-project/commit/c83d64f17a6e38f39fde611f06479e6f2a62b70f)

which uncovered a bug in annotating `StartOfName`.

**Comment by owenca** [comment]
> is there a configuration to control this behavior that I'm missing? else I think this is a bug.

You need to add `emit` to [`StatementAttributeLikeMacros`](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#statementattributelikemacros) with #99791.
