### ISSUE TITLE
[AVX] clang 18.1.8 AVX vector return of type '__m256' (vector of 8 'float' values) without 'avx' enabled changes the ABI

### ISSUE THREAD

**Issue by GaoXiangYa** [llvm/llvm-project#99847]
My clang version is 18.1.8, when I compile my program like these, I meet some problems:
```c++
__m256 vsum0 = _mm256_setzero_ps();
__m256 vsum1 = _mm256_setzero_ps();
```
The compiler told me :
```
error: AVX vector return of type '__m256' (vector of 8 'float' values) without 'avx' enabled changes the ABI
error: always_inline function '_mm256_loadu_ps' requires target feature 'avx', but would be inlined into function 'MatmulSingleUnrollAVXN1' that is compiled without support for 'avx'
```

**Comment by dzaima** [comment]
Are you compiling with `-mavx2`/`-march=<something with avx2>` or have an `__attribute__((target("avx2")))` on the function in question? If not, errors are the correct behavior.

**Comment by GaoXiangYa** [comment]
I add the -max to the compile flags, and compile it again, however, I meet a new problem:
```
error: always_inline function `_mm256_fmadd_ps` requires target feature 'fma` , but would be inlined into funcion `AddDot8x8` that is compiled without support for `fma`
```
@dzaima

**Comment by dzaima** [comment]
That'll need `-mfma`; if you're building for running the code yourself, `-march=native` should cover everything your CPU supports.

**Comment by phoebewang** [comment]
The error is excepted. You need to enable related features when using target specific intrinsics.
