### ISSUE TITLE
[Libc] Having issues compiling libc for MacOS

### ISSUE THREAD

**Issue by medievalghoul** [llvm/llvm-project#99879]
I recently tried compiling libc on overlay and got this message after running `ninja libc`:
```
ninja: error: 
'/Users/juliusalexandre/GitDownloads/llvm-project/libc/config/darwin/api.td', 
needed by 'projects/libc/include/ctype.h', missing and no known rule to make it
```

the cmake command I ran:
```
cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS='clang;libc' ../llvm \
   -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ \
   -DCMAKE_BUILD_TYPE=Release \
   -DLLVM_TARGET_ARCH=AArch64 \ 
   -DLLVM_USE_LINKER=lld \
   -DLLVM_CCACHE_BUILD=true
```

I'm on the Apple Silicon M2 Pro

**Comment by michaelrj-google** [comment]
Hi, sorry this issue got missed. It looks like you're running into an issue with headergen. We just recently updated headergen to not need that file, so it should work now if you pull and build again.

**Comment by medievalghoul** [comment]
> Hi, sorry this issue got missed. It looks like you're running into an issue with headergen. We just recently updated headergen to not need that file, so it should work now if you pull and build again.

All good, thank you for letting me know :)
