### ISSUE TITLE
warn on semi-colon after function definition

### ISSUE THREAD

**Issue by nlewycky** [llvm/llvm-project#9989]
|  |  |
| --- | --- |
| Bugzilla Link | [9617](https://llvm.org/bz9617) |
| Version | unspecified |
| OS | Linux |
| CC | @d0k |

## Extended Description 
I'd like a warning on this code:
```c
  void foo() { };
```
with fixit to remove the trailing semi-colon. Comeau says "error: extra ";" ignored", gcc and clang accept the code with no comment.

(This code is valid, right?)

**Comment by philnik777** [comment]
Looks like this was never a problem: https://godbolt.org/z/eWGTs81EE (just ignore the crash)
