### ISSUE TITLE
LWG2687: {inclusive,exclusive}_scan misspecified

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#99963]
**Link:** https://wg21.link/lwg2687

This issue doesn't appear to refer to the parallel overloads.

**Comment by strega-nil** [comment]
I think this is "Nothing to do", as it was a simple specification issue that libc++ never misimplemented (alternatively, it's certainly "Complete" if it's not ntd)

**Comment by ldionne** [comment]
I think this is "Done" since we do implement it correctly (i.e. we don't have an off-by-one). Either way this is closed now :-). Thanks!
