### ISSUE TITLE
P0619R4: Reviewing Deprecated Facilities of C++17 for C++20

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#99985]
**Link:** https://wg21.link/p0619r4

```
BEGIN-RST-NOTES
Only sections D.7, D.8, D.9, D.10, D.11, D.12 and D.13 are implemented. Section D.4 remains undone.
END-RST-NOTES
```

**Comment by frederick-vs-ja** [comment]
- [ ] D.4 remove `<ccomplex>`, `<ciso646>`, `<cstdalign>`, `<cstdbool>`, and `<ctgmath>`
- [ ] D.7 remove `uncaught_exception`
- [x] D.11 remove `raw_storage_iterator` - this was already done in 578d09c1b195d859ca7e62840ff6bb83421a77b5 (https://reviews.llvm.org/D101730) but the staus page wasn't updated correspondingly.
- [ ] D.12 remove `get_temporary_buffer` and `return_temporary_buffer`

**Comment by frederick-vs-ja** [comment]
It seems that `<cstdalign>` is undesired at all per #37759. But why are other deprecated & removed header provided?
